New Presence: Stips
PreMiD/Presences pull request #1981
Opened 2020-08-19 15:02 UTC by VerifyBot

Presence for [stips.co.il](stips.co.il) (Hebrew)
![image](https://user-images.githubusercontent.com/47427791/90651713-07858380-e246-11ea-8e5f-a77bec173e89.png)
![image](https://user-images.githubusercontent.com/47427791/90651740-12401880-e246-11ea-8361-45e82a418e88.png)

2020-08-19 15:41 UTC, doomlerd requested changes
JS files aren't allowed anymore, please read the contributing guidelines before making a PR.

2020-08-20 12:19 UTC, Bas950 requested changes

2020-08-20 12:19 UTC, Bas950 commented on websites/S/Stips/dist/metadata.json
> +  "version": "0.0.1",
version 1.0.0

2020-08-20 14:51 UTC, Bas950 approved these changes

2020-08-20 22:26 UTC, merged