CloudFM to CloudX + API Integration
PreMiD/Presences pull request #2008
Opened 2020-08-23 21:50 UTC by marinofranz

2020-08-23 21:53 UTC, marinofranz commented
![image](https://user-images.githubusercontent.com/48334228/90989658-02e50600-e58b-11ea-8292-8fcfbdb8252b.png)
![image](https://user-images.githubusercontent.com/48334228/90989660-07a9ba00-e58b-11ea-9850-db596167523d.png)

2020-08-23 22:21 UTC, Bas950 requested changes
Dont upload js file, fix deepscan issues

2020-08-23 22:21 UTC, Bas950 commented on websites/C/CloudX/dist/metadata.json
> +  "version": "1.0.1",
version 1.0.0 on first release

2020-08-24 08:40 UTC, marinofranz commented on websites/C/CloudX/dist/metadata.json
> +  "version": "1.0.1",
fixed

2020-08-24 11:22 UTC, Bas950 approved these changes

2020-08-24 20:31 UTC, merged