Add new site for store
PreMiD/Presences pull request #2009
Opened 2020-08-23 23:33 UTC by Hime-Dev

Add new site for store

2020-08-23 23:40 UTC, Bas950 requested changes
Fix deepscan errors, upload proof of it working

2020-08-23 23:40 UTC, Bas950 commented on websites/A/AnimeWho/dist/metadata.json
> +  "version": "V4 - Beta",
version: 1.0.0

2020-08-23 23:40 UTC, Bas950 commented on websites/A/AnimeWho/dist/metadata.json
> +  "service": "AnimeWho?",
service name and folder name must be the same (question mark included)

2020-08-24 09:20 UTC, Hime-Dev commented
![unknown](https://user-images.githubusercontent.com/57987392/91026918-184a4680-e604-11ea-93cb-7a760f6b9898.png)
@Bas950

2020-08-24 11:25 UTC, Bas950 requested changes

2020-08-24 11:25 UTC, Bas950 commented on websites/A/AnimeWho/dist/metadata.json
> +  "version": "0.1.0",
version: 1.0.0

2020-08-24 11:26 UTC, Hime-Dev commented on websites/A/AnimeWho/dist/metadata.json
> +  "version": "0.1.0",
fixed

2020-08-24 11:43 UTC, Bas950 approved these changes

2020-08-24 20:32 UTC, merged