Adding keepitwholesome.com presence to PreMiD.
PreMiD/Presences pull request #2031
Opened 2020-08-26 20:04 UTC by PapiVenom

by venom from premid

2020-08-26 20:27 UTC, Bas950 requested changes
upload proof of it working

2020-08-26 20:45 UTC, PapiVenom commented
My bad, 
![11111](https://user-images.githubusercontent.com/67442920/91354985-84bb7600-e7bb-11ea-9fd4-844bf578ac73.png)

2020-08-26 21:05 UTC, PapiVenom commented
> upload proof of it working

![unknown (2)](https://user-images.githubusercontent.com/67442920/91356899-6014cd80-e7be-11ea-9bdb-b77a056eb693.png)

2020-08-27 16:10 UTC, Bas950 approved these changes

2020-08-27 16:11 UTC, merged