⏫Update 1.4.3⏫
PreMiD/Presences pull request #2032
Opened 2020-08-26 21:24 UTC by EvilBrain

Add new icon

2020-08-27 06:59 UTC, EvilBrain commented
![image](https://user-images.githubusercontent.com/49623340/91408116-9ba5ab00-e843-11ea-8b0a-4bb7b660cfa4.png)

2020-08-27 16:12 UTC, Bas950 requested changes
uhm this only adds a js file, which we dont even allow.

2020-08-30 21:14 UTC, doomlerd requested changes
Fix the app icon.

2020-09-05 14:23 UTC, doomlerd commented
Closing due to inactivity.

2020-09-05 14:23 UTC, closed without merging