Adding JKAnime
PreMiD/Presences pull request #2033
Opened 2020-08-27 00:25 UTC by Zerlingg

Pause:
![DiscordPTB_gwPGOR0ojK](https://user-images.githubusercontent.com/38077912/91369562-63cf4100-e80c-11ea-99ae-9afc0b7265a9.png)

Play:
![DiscordPTB_H768CDog4m](https://user-images.githubusercontent.com/38077912/91369565-692c8b80-e80c-11ea-97db-ea4e1a088e92.png)

2020-08-27 00:27 UTC, Zerlingg commented
Oh an error, what do i have to do?

2020-08-27 16:15 UTC, Bas950 requested changes
Dont upload js files and fix deepscan issues.

2020-08-27 16:15 UTC, Bas950 commented on websites/J/JKAnime/dist/metadata.json
> +  "version": "1.0",
version 1.0.0

2020-08-30 21:16 UTC, doomlerd requested changes
It would be better if you use the icons provided in the resources folder.

2020-08-31 12:38 UTC, Zerlingg commented
Changed icons to the ones provided in resources folder and JS files deleted

2020-08-31 12:39 UTC, Zerlingg commented
IDK how to fix the "SV / Schema Validation Check (pull_request)" thing

2020-08-31 12:40 UTC, kawakami commented
You have incorrect version. It must be 1.0.0

2020-08-31 12:41 UTC, doomlerd commented
> Changed icons to the ones provided in resources folder

Take and upload a screenshot of the change.

2020-08-31 13:26 UTC, Zerlingg commented
![image](https://user-images.githubusercontent.com/38077912/91724919-44cf0700-eb9e-11ea-8022-6c75a16b53f5.png)

2020-08-31 13:38 UTC, doomlerd commented
I mean the presence itself

2020-09-02 18:11 UTC, SeMiD commented on websites/J/JKAnime/presence.ts
> +    video = data;
Codacy found an issue: [Expected linebreaks to be 'LF' but found 'CRLF'.](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113512)

2020-09-02 18:11 UTC, SeMiD commented on websites/J/JKAnime/presence.ts
> +}
Codacy found an issue: [Expected linebreaks to be 'LF' but found 'CRLF'.](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113512)

2020-09-02 18:11 UTC, SeMiD commented on websites/J/JKAnime/presence.ts
> +  return [Math.floor(startTime / 1000), (Math.floor(endTime))];
Codacy found an issue: [Expected linebreaks to be 'LF' but found 'CRLF'.](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113512)

2020-09-02 18:11 UTC, SeMiD commented on websites/J/JKAnime/presence.ts
> +presence.on("UpdateData", async () => {
Codacy found an issue: [Expected linebreaks to be 'LF' but found 'CRLF'.](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113512)

2020-09-02 18:11 UTC, SeMiD commented on websites/J/JKAnime/presence.ts
> +        (data.smallImageKey = video.paused ? "pause" : "play");
Codacy found an issue: [Expected linebreaks to be 'LF' but found 'CRLF'.](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113512)

2020-09-02 18:11 UTC, SeMiD commented on websites/J/JKAnime/presence.ts
> +      video.currentTime,
Codacy found an issue: [Expected linebreaks to be 'LF' but found 'CRLF'.](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113512)

2020-09-02 18:11 UTC, SeMiD commented on websites/J/JKAnime/presence.ts
> +  videoDuration: number
Codacy found an issue: [Expected linebreaks to be 'LF' but found 'CRLF'.](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113512)

2020-09-02 18:11 UTC, SeMiD commented on websites/J/JKAnime/presence.ts
> +  videoTime: number,
Codacy found an issue: [Expected linebreaks to be 'LF' but found 'CRLF'.](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113512)

2020-09-02 18:11 UTC, SeMiD commented on websites/J/JKAnime/iframe.ts
> +
Codacy found an issue: [Expected linebreaks to be 'LF' but found 'CRLF'.](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113512)

2020-09-02 18:11 UTC, SeMiD commented on websites/J/JKAnime/iframe.ts
> +			iframe.send({
Codacy found an issue: [Expected linebreaks to be 'LF' but found 'CRLF'.](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113512)

2020-09-02 18:11 UTC, SeMiD commented on websites/J/JKAnime/presence.ts
> +        "#reproductor-box > div.video-header > h1"
Codacy found an issue: [Expected linebreaks to be 'LF' but found 'CRLF'.](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113512)

2020-09-02 18:11 UTC, SeMiD commented on websites/J/JKAnime/presence.ts
> +    const timestamps = getTimestamps(
Codacy found an issue: [Expected linebreaks to be 'LF' but found 'CRLF'.](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113512)

2020-09-02 18:11 UTC, SeMiD commented on websites/J/JKAnime/presence.ts
> +    const title = document.querySelector(
Codacy found an issue: [Expected linebreaks to be 'LF' but found 'CRLF'.](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113512)

2020-09-02 18:11 UTC, SeMiD commented on websites/J/JKAnime/presence.ts
> +    !isNaN(video.duration)
Codacy found an issue: [Expected linebreaks to be 'LF' but found 'CRLF'.](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113512)

2020-09-02 18:11 UTC, SeMiD commented on websites/J/JKAnime/presence.ts
> +  "iFrameData",
Codacy found an issue: [Expected linebreaks to be 'LF' but found 'CRLF'.](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113512)

2020-09-02 18:11 UTC, SeMiD commented on websites/J/JKAnime/presence.ts
> +  duration: 0,
Codacy found an issue: [Expected linebreaks to be 'LF' but found 'CRLF'.](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113512)

2020-09-02 18:11 UTC, SeMiD commented on websites/J/JKAnime/presence.ts
> +    play: "presence.playback.playing",
Codacy found an issue: [Expected linebreaks to be 'LF' but found 'CRLF'.](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113512)

2020-09-02 18:11 UTC, SeMiD commented on websites/J/JKAnime/iframe.ts
> +iframe.on("UpdateData", async () => {
Codacy found an issue: [Expected linebreaks to be 'LF' but found 'CRLF'.](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113512)

2020-09-02 18:11 UTC, SeMiD commented on websites/J/JKAnime/presence.ts
> +  const endTime = Math.floor(startTime / 1000) - videoTime + videoDuration;
Codacy found an issue: [Expected linebreaks to be 'LF' but found 'CRLF'.](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113512)

2020-09-02 18:11 UTC, SeMiD commented on websites/J/JKAnime/presence.ts
> +  (data: { duration: number; currentTime: number; paused: boolean }) => {
Codacy found an issue: [Expected linebreaks to be 'LF' but found 'CRLF'.](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113512)

2020-09-02 18:11 UTC, SeMiD commented on websites/J/JKAnime/iframe.ts
> +			});
Codacy found an issue: [Expected linebreaks to be 'LF' but found 'CRLF'.](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113512)

2020-09-02 18:11 UTC, SeMiD commented on websites/J/JKAnime/iframe.ts
> +		if(video != null && !isNaN(video.duration)) {
Codacy found an issue: [Expected linebreaks to be 'LF' but found 'CRLF'.](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113512)

2020-09-02 18:11 UTC, SeMiD commented on websites/J/JKAnime/presence.ts
> +    largeImageKey: "jkanime"
Codacy found an issue: [Expected linebreaks to be 'LF' but found 'CRLF'.](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113512)

2020-09-02 18:11 UTC, SeMiD commented on websites/J/JKAnime/presence.ts
> +    video != null &&
Codacy found an issue: [Expected linebreaks to be 'LF' but found 'CRLF'.](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113512)

2020-09-02 18:11 UTC, SeMiD commented on websites/J/JKAnime/presence.ts
> +  console.log(video);
Codacy found an issue: [Unexpected console statement.](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113512)

2020-09-03 15:04 UTC, Bas950 requested changes
Ignore deepscan and fix codacy issues.

2020-09-05 14:22 UTC, doomlerd commented
Closing due to inactivity.

2020-09-05 14:22 UTC, closed without merging