Add pony.town presence
PreMiD/Presences pull request #2041
Opened 2020-08-28 21:44 UTC by Tschrock

Adds presence for the pixel game https://pony.town/

![1598650538-RN95](https://user-images.githubusercontent.com/2406499/91617022-08f53100-e955-11ea-9f47-4d5607466207.png)
![1598650519-MkWo](https://user-images.githubusercontent.com/2406499/91617025-098dc780-e955-11ea-9cec-760692515139.png)

2020-08-28 22:34 UTC, Bas950 requested changes

2020-08-28 22:34 UTC, Bas950 commented on websites/P/PonyTown/dist/metadata.json
> +  "thumbnail": "https://p.cp3.es/pony.town-thumbnail2.png",
upload to imgur

2020-08-28 22:35 UTC, Bas950 commented
also update your fork

2020-08-29 04:16 UTC, Tschrock commented
rebased & imgur'd

2020-08-29 13:48 UTC, Bas950 requested changes

2020-08-29 13:48 UTC, Bas950 commented on websites/P/PonyTown/presence.ts
> +});
Somehow you are not getting any deepscan issues
but no-var

2020-08-29 13:48 UTC, Bas950 commented on websites/P/PonyTown/presence.ts
> +let lastStateTime = Date.now();
one-var (merge lets to just 1)

2020-08-30 21:20 UTC, doomlerd requested changes

2020-08-30 21:20 UTC, doomlerd commented on websites/P/PonyTown/presence.ts
> +}
Combine those two consts and fix any issues that _may_ be reported by DeepScan.

2020-09-02 18:12 UTC, SeMiD commented on websites/P/PonyTown/presence.ts
> +  const gameElement = document.querySelector(selectors.GAME_ELEMENT)
Codacy found an issue: [Missing semicolon.](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113511)

2020-09-02 18:12 UTC, SeMiD commented on websites/P/PonyTown/presence.ts
> +}
Codacy found an issue: [Missing semicolon.](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113511)

2020-09-02 18:12 UTC, SeMiD commented on websites/P/PonyTown/presence.ts
> +const selectors = {
Codacy found an issue: [Combine this with the previous 'const' statement.](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113511)

2020-09-03 15:05 UTC, Bas950 requested changes
Fix codacy issues

2020-09-05 14:24 UTC, doomlerd commented
Closing due to inactivity.

2020-09-05 14:24 UTC, closed without merging