Adding a new presence.
PreMiD/Presences pull request #2047
Opened 2020-08-30 15:59 UTC by eren885

![image](https://user-images.githubusercontent.com/58482989/91663645-1ee42c80-eae2-11ea-91d1-0999ebac5e07.png)
![image](https://user-images.githubusercontent.com/58482989/91663658-2d324880-eae2-11ea-81fd-a154f00db875.png)

2020-08-30 17:32 UTC, Bas950 requested changes

2020-08-30 17:32 UTC, Bas950 commented on websites/D/DevTR/presence.ts
> +  const browsingStamp = Math.floor(Date.now() / 1000);
merge consts

2020-08-30 19:09 UTC, eren885 commented on websites/D/DevTR/presence.ts
> +  const browsingStamp = Math.floor(Date.now() / 1000);
why

2020-08-30 19:13 UTC, Bas950 commented on websites/D/DevTR/presence.ts
> +  const browsingStamp = Math.floor(Date.now() / 1000);
rules

2020-08-30 21:41 UTC, doomlerd requested changes
Update your fork.

2020-08-30 23:16 UTC, Bas950 requested changes

2020-08-30 23:16 UTC, Bas950 commented on websites/D/DevTR/presence.ts
> +    const page = window.location.pathname,
combine consts

2020-08-31 15:00 UTC, closed without merging

2020-08-31 15:03 UTC, Bas950 commented
@eren885 
Combining consts:
```
 const presenceData: PresenceData = {
        largeImageKey: "logo"
    },
     page = window.location.pathname,
    browsingStamp = Math.floor(Date.now() / 1000);
```