Presence | DevTR
PreMiD/Presences pull request #2055
Opened 2020-08-31 15:11 UTC by eren885

2020-08-31 15:13 UTC, Bas950 requested changes
upload proof of it working

2020-08-31 17:44 UTC, eren885 commented
its been 3 hours and deepscan still analyzing it out, bruh

2020-09-02 18:10 UTC, SeMiD commented on websites/D/DevTR/presence.ts
> +        presenceData.smallImageKey = "js"
Codacy found an issue: [Missing semicolon.](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113506)

2020-09-02 19:21 UTC, eren885 commented
ah

2020-09-02 19:22 UTC, doomlerd approved these changes

2020-09-03 15:03 UTC, Bas950 commented on websites/D/DevTR/presence.ts
> +  //a
remove the random comment

2020-09-03 17:48 UTC, Bas950 approved these changes

2020-09-04 20:00 UTC, doomlerd approved these changes

2020-09-04 20:00 UTC, merged