Presence update: skindb.co
PreMiD/Presences pull request #2093
Opened 2020-09-03 17:42 UTC by NotOfficer

Added support for [skindb.co/fallguys](https://skindb.co/fallguys).
Proof: [media.wtf/95781050](https://media.wtf/95781050)

2020-09-03 17:50 UTC, Bas950 requested changes
Fix codacy issues.

2020-09-03 17:52 UTC, NotOfficer commented
For real...?

2020-09-03 17:53 UTC, NotOfficer commented
I dont even get what it wants me to change.

2020-09-03 17:57 UTC, Bas950 commented on websites/S/skindb.co/presence.ts
> +      const skinRarity = document.querySelector(".skin-rarity-string > .rarity-label");
like merge these consts, so like:
```
const var = val,
 var2 = val,
 var3 = val;
```

2020-09-03 18:02 UTC, NotOfficer commented on websites/S/skindb.co/presence.ts
> +      const skinRarity = document.querySelector(".skin-rarity-string > .rarity-label");
thanks

2020-09-03 18:56 UTC, Bas950 approved these changes

2020-09-04 20:02 UTC, doomlerd approved these changes

2020-09-04 20:02 UTC, merged