Fix Aternos presence
PreMiD/Presences pull request #2095
Opened 2020-09-03 18:04 UTC by Allvaa

fix that the presence text is "Home Page" even when the user opens the panel

2020-09-03 18:56 UTC, Bas950 requested changes
upload proof of it working

2020-09-04 00:20 UTC, Allvaa commented
![image](https://user-images.githubusercontent.com/52526068/92185811-0af05000-ee7f-11ea-861d-323dfc57adaa.png)
![image](https://user-images.githubusercontent.com/52526068/92185832-13e12180-ee7f-11ea-9640-178faa961b65.png)
![image](https://user-images.githubusercontent.com/52526068/92185838-18a5d580-ee7f-11ea-8c5c-9708fb3bdd07.png)

2020-09-05 14:26 UTC, doomlerd approved these changes

2020-09-08 15:10 UTC, Bas950 approved these changes

2020-09-08 15:11 UTC, merged