Add Mark Scan presence
PreMiD/Presences pull request #2097
Opened 2020-09-04 05:51 UTC by markinhozz1

![01](https://user-images.githubusercontent.com/38191703/92204302-cb0e7600-ee48-11ea-9587-9580b9f2694c.png)
![02](https://user-images.githubusercontent.com/38191703/92204306-cc3fa300-ee48-11ea-9393-1aa440772956.png)
![03](https://user-images.githubusercontent.com/38191703/92204308-ccd83980-ee48-11ea-9965-b389cdf13c58.png)

2020-09-08 15:11 UTC, Bas950 approved these changes

2020-09-10 16:12 UTC, Alanexei approved these changes

2020-09-10 16:13 UTC, Alanexei commented
Please leave this pull request open.

2020-09-11 16:07 UTC, Alanexei requested changes
@markinhozz1 Can you use `Git CLI` or `GItHub Desktop` to upload the files instead of using the website. The line endings need to be `LF`.

2020-09-15 17:33 UTC, doomlerd commented
Closing in 2 days.

2020-09-16 00:08 UTC, closed without merging