Radiot Suomi Presence
PreMiD/Presences pull request #2098
Opened 2020-09-04 12:19 UTC by TehRamsus

![kuva](https://user-images.githubusercontent.com/50022415/92238492-0dc06480-eec2-11ea-8b18-78bbafbf006a.png)
![kuva](https://user-images.githubusercontent.com/50022415/92238463-fe411b80-eec1-11ea-90d0-810b93627c94.png)

2020-09-08 15:13 UTC, Bas950 requested changes
Fix codacy issues

2020-09-08 15:13 UTC, Bas950 commented on websites/R/Radiot-Suomi/dist/metadata.json
> +    ],
Doesnt need to be in an array if its only 1

2020-09-08 15:13 UTC, Bas950 commented on websites/R/Radiot-Suomi/dist/metadata.json
> +    "logo": "http://www.radio-suomi.com/static/icons/App_512x512/fi.png",
version 1.0.0 on first release
and upload logo to imgur

2020-09-08 15:13 UTC, Bas950 commented on websites/R/Radiot-Suomi/presence.ts
> +//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicHJlc2VuY2UuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyIuLi9wcmVzZW5jZS50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQSxJQUFJL
how did you manage to get a sourcemapping url in your ts file....

2020-09-08 17:30 UTC, TehRamsus commented
Fixed SourceMappingURL, fixed array, changed version to 1.0.0 and added logo to imgur.

2020-09-08 17:56 UTC, Bas950 commented
well you did something wrong.... you made a new metadata file outside of the dist folder...

2020-09-08 19:19 UTC, TehRamsus commented
oh fuck accidentally, sorry :D i'll fix that xD

2020-09-10 13:50 UTC, Bas950 requested changes

2020-09-10 13:50 UTC, Bas950 commented on websites/R/Radiot-Suomi/dist/metadata.json
> +    "logo": "https://i.imgur.com/nhxjVmG.png",
version 1.0.0 on release

2020-09-10 13:50 UTC, Bas950 commented on websites/R/Radiot-Suomi/presence.ts
> +let browsingStamp = Math.floor(Date.now() / 1000);
const and merge the consts

2020-09-11 16:08 UTC, Alanexei requested changes
Please resolve the Codacy issues.

2020-09-12 12:05 UTC, Bas950 approved these changes

2020-09-13 01:03 UTC, Alanexei approved these changes

2020-09-13 01:03 UTC, merged