OnlyHit
PreMiD/Presences pull request #2104
Opened 2020-09-06 02:09 UTC by a6doff

Adding onlyhit.us
Proof of it working:
![image](https://user-images.githubusercontent.com/67640562/92316596-ba036780-eff6-11ea-94f5-e39d71ca2d05.png)

2020-09-06 02:22 UTC, a6doff reviewed
Changed some stuff

2020-09-07 00:05 UTC, Alanexei requested changes

2020-09-07 00:05 UTC, Alanexei commented on websites/O/OnlyHit/dist/metadata.json
> +  "logo": "https://api.onlyhit.us/logo.png",
Publish this to imgur.

2020-09-07 02:34 UTC, a6doff commented
Uploaded image to imgur

2020-09-07 02:35 UTC, a6doff commented on websites/O/OnlyHit/dist/metadata.json
> +  "logo": "https://api.onlyhit.us/logo.png",
done

2020-09-07 03:29 UTC, a6doff commented
All edited

2020-09-08 15:17 UTC, Bas950 requested changes

2020-09-08 15:17 UTC, Bas950 commented on websites/O/OnlyHit/presence.ts
> +    lastTimeStart = Math.floor(Date.now() / 1000);
this doesnt seem needed
(twice the same thing)

2020-09-08 15:17 UTC, Bas950 commented on websites/O/OnlyHit/presence.ts
> +          radio = document.querySelector(".stream-name").textContent;
move the consts down to the pageName one and then combine the consts

2020-09-08 15:17 UTC, Bas950 commented on websites/O/OnlyHit/presence.ts
> +    if (document.querySelector(".stream-name").textContent == 'OnlyHit Gold') {
move the consts down to the pageName one and then combine the consts

2020-09-08 15:17 UTC, Bas950 commented on websites/O/OnlyHit/presence.ts
> +  });
set traytitle not needed

2020-09-09 19:05 UTC, a6doff commented
(Updated)

2020-09-11 16:10 UTC, Alanexei approved these changes

2020-09-11 16:10 UTC, merged