Updates | Tatsumaki, Kahve BOT, Kabal's and more!
PreMiD/Presences pull request #2107
Opened 2020-09-06 18:50 UTC by eren885

![image](https://user-images.githubusercontent.com/58482989/92333011-a4d81880-f08a-11ea-9006-d2abcb5f52d2.png)
![image](https://user-images.githubusercontent.com/58482989/92333040-e799f080-f08a-11ea-91e4-dbd356c50405.png)

2020-09-07 00:06 UTC, Alanexei requested changes

2020-09-07 00:06 UTC, Alanexei commented on websites/D/Discord Bots/dist/metadata.json
> +    "en": "Discord bots is a website that listing discord bots.",
Change the English description, this isn't grammatically correct. `listing` -> `lists`

2020-09-08 15:22 UTC, Bas950 approved these changes

2020-09-11 16:15 UTC, Alanexei approved these changes

2020-09-11 16:15 UTC, merged