ReaperX Presence Update
PreMiD/Presences pull request #2129
Opened 2020-09-11 17:00 UTC by InwTanRew

- Change Color
- Renew Description
- Change user Id
- Delete /backend in presence.ts

2020-09-11 17:03 UTC, Bas950 submitted a review, later dismissed

2020-09-12 10:56 UTC, InwTanRew commented
Add /backend Again Already Fix backend didn't detected in presence

2020-09-12 12:10 UTC, Bas950 requested changes
Upload proof of the changes working.

2020-09-12 18:57 UTC, InwTanRew commented
![9119C59E-7B61-4955-B9A6-394B5127ECDF](https://user-images.githubusercontent.com/32316341/93002911-7fed1500-f564-11ea-9536-07f32bc0f93c.png)

here you are

2020-09-12 20:45 UTC, Bas950 approved these changes

2020-09-13 01:01 UTC, Alanexei approved these changes

2020-09-13 01:01 UTC, Alanexei commented
@InwTanRew It seems that your presence has been modified since you've made the pull request. You will need to resolve those conflicting files.

2020-09-13 01:04 UTC, InwTanRew commented
okay wait a second

2020-09-13 01:11 UTC, InwTanRew commented
How its conflicting files am confused

2020-09-13 14:06 UTC, InwTanRew commented
Updated Logo

2020-09-13 18:37 UTC, Bas950 requested changes

2020-09-13 18:37 UTC, Bas950 commented on websites/R/ReaperX/dist/metadata.json
> +    "logo": "https://i.imgur.com/vbdVmLg_d.jpg",
logo should at least be 512x512

2020-09-13 23:06 UTC, InwTanRew commented on websites/R/ReaperX/dist/metadata.json
> +    "logo": "https://i.imgur.com/vbdVmLg_d.jpg",
Fixed

2020-09-14 17:01 UTC, Bas950 approved these changes

2020-09-15 17:35 UTC, doomlerd requested changes

2020-09-15 17:35 UTC, doomlerd commented on websites/R/ReaperX/dist/metadata.json
> +    "version": "1.0.1",
Increase the version.

2020-09-15 22:48 UTC, InwTanRew commented on websites/R/ReaperX/dist/metadata.json
> +    "version": "1.0.1",
Here you are, Fixed

2020-09-17 00:04 UTC, Bas950 approved these changes

2020-09-17 15:13 UTC, merged