OnlyHit - Update smallImageKey
PreMiD/Presences pull request #2131
Opened 2020-09-11 18:49 UTC by a6doff

2020-09-12 12:11 UTC, Bas950 requested changes
Bump version in metadata

2020-09-12 12:12 UTC, Bas950 commented
Also upload proof of it working

2020-09-12 21:52 UTC, a6doff commented
![image](https://user-images.githubusercontent.com/67640562/93005619-f54fea00-f552-11ea-946b-1afe2a2c5346.png)
There we go

2020-09-13 00:23 UTC, Bas950 commented
#2137

2020-09-13 00:23 UTC, closed without merging