Add users rank/problem points to rich presence
PreMiD/Presences pull request #2140
Opened 2020-09-13 03:14 UTC by Yolodude25

![DiscordCanary_gq2Z8HjrMS](https://user-images.githubusercontent.com/41439633/93009327-aa7fa380-f54d-11ea-8060-d1d03a30ac5a.png)
![DiscordCanary_IFGn4gAmBp](https://user-images.githubusercontent.com/41439633/93009330-ac496700-f54d-11ea-9e74-26a52bf5396b.png)

2020-09-13 03:40 UTC, Alanexei requested changes
Bump the version. `1.0.0` -> `1.0.1`

2020-09-13 18:40 UTC, Bas950 submitted a review, later dismissed

2020-09-13 22:42 UTC, Bas950 approved these changes

2020-09-14 16:45 UTC, Alanexei approved these changes

2020-09-14 16:45 UTC, merged