Add XKCD Presence
PreMiD/Presences pull request #2142
Opened 2020-09-13 06:13 UTC by theusaf

## What is XKCD?
XKCD is a webcomic of romance, sarcasm, math, and language made by Randall Munroe.
## Example:
**Non-Comic Page**
![Browsing XKCD](https://cdn.discordapp.com/attachments/710280407777673277/754583365117542420/Screen_Shot_2020-09-12_at_11.02.28_PM.png)
**Comic Page**
![Reading Comic](https://cdn.discordapp.com/attachments/710280407777673277/754583371312791632/Screen_Shot_2020-09-12_at_11.02.07_PM.png)
**Title Text**
![Title text on small image](https://cdn.discordapp.com/attachments/710280407777673277/754583366615171092/Screen_Shot_2020-09-12_at_11.01.58_PM.png)

2020-09-13 18:42 UTC, Bas950 requested changes

2020-09-13 18:42 UTC, Bas950 commented on websites/X/XKCD/dist/metadata.json
> +  "thumbnail": "https://cdn.discordapp.com/attachments/710280407777673277/754552040545583302/Screen_Shot_2020-09-12_at_8.59.55_PM.png",
upload to imgur

2020-09-13 18:42 UTC, Bas950 commented on websites/X/XKCD/dist/metadata.json
> +  "version": "0.0.1",
version 1.0.0 on release

2020-09-14 16:44 UTC, Alanexei commented on websites/X/XKCD/dist/metadata.json
> +  "thumbnail": "https://i.imgur.com/sdVsYvZ.png",
Reviewers, check this if you haven't already.

2020-09-14 16:44 UTC, Alanexei approved these changes

2020-09-14 17:37 UTC, Bas950 requested changes
logo must be square like the one you use in discord

2020-09-14 17:46 UTC, Bas950 approved these changes

2020-09-15 17:41 UTC, doomlerd approved these changes

2020-09-15 17:42 UTC, merged