Multiple pages added, small icons and logo URL update
PreMiD/Presences pull request #2148
Opened 2020-09-13 17:59 UTC by SenkaWolf

- Added Support for branding, privacy, terms of service, cookie policy, and advertising pages.
- Added small icon to index and create event presences
- Change presences logo URL (Image no longer has a transparent background)

### Images
![image](https://user-images.githubusercontent.com/28118201/93025032-b40f1700-f5f2-11ea-92c1-ad738c5a37a6.png)
![Discord_2020-09-13_18-56-58](https://user-images.githubusercontent.com/28118201/93025069-e91b6980-f5f2-11ea-96ef-bde5343d7ec3.png)
![Discord_2020-09-13_18-57-19](https://user-images.githubusercontent.com/28118201/93025078-f59fc200-f5f2-11ea-84cd-b52f99ce706f.png)
![Discord_2020-09-13_18-58-40](https://user-images.githubusercontent.com/28118201/93025107-27188d80-f5f3-11ea-990b-824be7711cee.png)
![Discord_2020-09-13_18-54-06](https://user-images.githubusercontent.com/28118201/93025050-cc7f3180-f5f2-11ea-9864-91259a5d0d88.png)
![Discord_2020-09-13_18-54-24](https://user-images.githubusercontent.com/28118201/93025053-cee18b80-f5f2-11ea-9daf-90430fdc7070.png)
![Discord_2020-09-13_18-55-07](https://user-images.githubusercontent.com/28118201/93025054-d0ab4f00-f5f2-11ea-998d-645b061893b0.png)

2020-09-13 18:43 UTC, Bas950 requested changes
Update your fork and bump version

2020-09-13 19:50 UTC, SenkaWolf commented
The fork and the version number has been updated.

2020-09-13 19:52 UTC, Bas950 approved these changes

2020-09-14 16:43 UTC, Alanexei approved these changes

2020-09-14 16:43 UTC, merged