Add Town of Salem Presence
PreMiD/Presences pull request #2152
Opened 2020-09-14 02:11 UTC by theusaf

## Town of Salem
A deception game made by BlankMediaGames.
This PR closes #2126 

|Event|Image|Description|
|-|-|-|
|Non-game page|![Browsing BlankMediaGames](https://cdn.discordapp.com/attachments/710280407777673277/754881552638410822/Screen_Shot_2020-09-13_at_5.23.45_PM.png)|Shows the current page the user is browsing and how long they were browsing|
|Logging into the page|![Logging in](https://cdn.discordapp.com/attachments/710280407777673277/754881561203310743/Screen_Shot_2020-09-13_at_5.22.17_PM.png)|Appears when the user loads the page and begins logging in|
|In the main menu|![Browsing Home Screen](https://cdn.discordapp.com/attachments/710280407777673277/754881551560343734/Screen_Shot_2020-09-13_at_5.22.32_PM.png)|Appears in the main, the shop, cauldron, achievements, etc. screens|
|In a game lobby|![Waiting in the lobby](https://cdn.discordapp.com/attachments/710280407777673277/754881557503934594/Screen_Shot_2020-09-13_at_5.29.28_PM.png)|Appears when joining a non-ranked game lobby|
|Ranked Queue|![Ranked Queue](https://cdn.discordapp.com/attachments/710280407777673277/754881556392312872/Screen_Shot_2020-09-13_at_5.26.10_PM.png)|Appears when waiting for a ranked game to start|
|During the game (day)|![Day 1](https://cdn.discordapp.com/attachments/710280407777673277/754881559458218074/Screen_Shot_2020-09-13_at_6.11.57_PM.png) ![Day 2](https://cdn.discordapp.com/attachments/710280407777673277/754881549240893540/Screen_Shot_2020-09-13_at_6.13.49_PM.png)|Appears during the game in the 'day' stage|
|During the game (night)|![Night 1](https://cdn.discordapp.com/attachments/710280407777673277/754881550281080862/Screen_Shot_2020-09-13_at_6.13.12_PM.png)|Appears during the night stage|

2020-09-14 16:40 UTC, Alanexei commented on websites/T/Town of Salem/dist/metadata.json
> +  "thumbnail": "https://i.imgur.com/xdm53K3.jpg",
Reviewers, check this please.

2020-09-14 16:41 UTC, Alanexei submitted a review, later dismissed

2020-09-14 17:42 UTC, Bas950 requested changes

2020-09-14 17:42 UTC, Bas950 commented on websites/T/Town of Salem/dist/metadata.json
> +  "logo": "https://i.imgur.com/G15NoTR.png",
probs better to use the same logo as the one you use in the Discord status.

2020-09-15 17:44 UTC, doomlerd requested changes

2020-09-15 17:44 UTC, doomlerd commented on websites/T/Town of Salem/dist/metadata.json
> +    "en": "Town of Salem is a browser-based game that challenges players on their ability to convincingly lie as well as detect when other players are lying. The game ranges from 7 to 15 players. The
Make the description shorter, possibly remove everything after the first dot.

2020-09-15 23:05 UTC, doomlerd approved these changes

2020-09-17 00:06 UTC, Bas950 approved these changes

2020-09-17 00:06 UTC, merged