New presence: Laftel
PreMiD/Presences pull request #2166
Opened 2020-09-16 11:11 UTC by parangee

2020-09-17 00:12 UTC, Bas950 requested changes
Fix codacy issues

_btw if you are korean yourself please help us out translating PreMiD to korean_ :)

2020-09-17 00:12 UTC, Bas950 commented on websites/L/Laftel/dist/metadata.json
> +    "contributors": [],
you dont need the contributors if you dont have it

2020-09-17 00:12 UTC, Bas950 commented on websites/L/Laftel/dist/metadata.json
> +    ],
doesnt need to be in an array since its only 1

2020-09-17 00:12 UTC, Bas950 commented on websites/L/Laftel/dist/metadata.json
> +    "logo": "https://asset.laftel.net/favicon.ico",
version 1.0.0
and upload to imgur

2020-09-17 15:17 UTC, doomlerd commented
Provide proof screenshots.

2020-09-17 15:33 UTC, Bas950 requested changes
Upload proof of it working

2020-09-17 15:33 UTC, Bas950 commented on websites/L/Laftel/dist/metadata.json
> +    },
ko_KR

2020-09-17 15:33 UTC, Bas950 commented on websites/L/Laftel/dist/metadata.json
> +    "logo": "https://i.imgur.com/XP7IP0A.png",
logo should atleast be 512x512 like the one in the presence

2020-09-19 00:27 UTC, Bas950 reviewed
Shouldn't you set a large image key in the presence?

2020-09-19 02:06 UTC, pikokr commented
> Shouldn't you set a large image key in the presence?

I don't have images for it

2020-09-19 11:24 UTC, Bas950 commented
> > Shouldn't you set a large image key in the presence?
> 
> I don't have images for it

The logo of the website?

2020-09-19 11:26 UTC, Bas950 commented
And for small images keys you can download these and then upload them to the app. https://www.github.com/PreMiD/Presences/tree/master/.resources

2020-09-22 07:13 UTC, pikokr commented
![image](https://user-images.githubusercontent.com/68010770/93853241-7a26ca80-fcee-11ea-93fb-f7d6bbe3857c.png)
added small and large image keys.

2020-09-22 11:38 UTC, Bas950 approved these changes

2020-09-26 02:24 UTC, Alanexei approved these changes

2020-09-26 02:24 UTC, merged