New presence: CatchPlay
PreMiD/Presences pull request #2201
Opened 2020-09-23 08:24 UTC by gfjaru

### What is?
CATCHPLAY is a Taiwanese multimedia company founded in 2007, whose businesses include OTT VOD streaming service operation, linear television channel operation and theatrical film distribution. Legally, it operates as a Taiwan branch of CatchPlay, Inc., a company registered in Cayman Islands.

### Demo
![Screen Shot 2020-09-23 at 15 08 55](https://user-images.githubusercontent.com/14217969/93986493-9ee37680-fdb0-11ea-9b2e-f19bc1d7f94c.png)
![Screen Shot 2020-09-23 at 15 09 11](https://user-images.githubusercontent.com/14217969/93986498-a0ad3a00-fdb0-11ea-95b0-72902f76db3e.png)
![Screen Shot 2020-09-23 at 15 09 27](https://user-images.githubusercontent.com/14217969/93986503-a145d080-fdb0-11ea-92f6-f67d641c1413.png)
![Screen Shot 2020-09-23 at 15 09 47](https://user-images.githubusercontent.com/14217969/93986506-a1de6700-fdb0-11ea-9254-a435ed8df698.png)
![Screen Shot 2020-09-23 at 15 19 20](https://user-images.githubusercontent.com/14217969/93986507-a1de6700-fdb0-11ea-9ebe-bf02cf678bd7.png)

2020-09-23 11:25 UTC, Bas950 requested changes

2020-09-23 11:25 UTC, Bas950 commented on websites/C/CatchPlay/dist/metadata.json
> +  "version": "1.2.0",
version 1.0.0

2020-09-23 11:56 UTC, gfjaru commented on websites/C/CatchPlay/dist/metadata.json
> +  "version": "1.2.0",
fixed in new commit

2020-09-23 11:57 UTC, Bas950 approved these changes

2020-09-26 02:27 UTC, Alanexei approved these changes

2020-09-26 02:27 UTC, merged