Fixed Glynet, Log.com.tr and Teknobuk Presences
PreMiD/Presences pull request #2202
Opened 2020-09-23 10:23 UTC by ardasoyturk

![image](https://user-images.githubusercontent.com/33841775/94000299-abab9e80-fd9f-11ea-8221-eb409dbfc690.png)
![image](https://user-images.githubusercontent.com/33841775/94000403-cc73f400-fd9f-11ea-9fea-b0b26282f251.png)
![image](https://user-images.githubusercontent.com/33841775/94000479-e31a4b00-fd9f-11ea-8f81-93c8f55d6c31.png)

2020-09-23 11:24 UTC, Bas950 requested changes

2020-09-23 11:24 UTC, Bas950 commented on websites/G/Glynet/presence.ts
> +const presenceData : PresenceData = {
merge consts

2020-09-23 15:13 UTC, Bas950 requested changes
Fix codacy errors

2020-09-23 19:25 UTC, Bas950 approved these changes

2020-09-26 02:28 UTC, Alanexei approved these changes

2020-09-26 02:28 UTC, merged