Added Milk and Cookies Presence
PreMiD/Presences pull request #2217
Opened 2020-09-25 17:44 UTC by JeffreyDeveloper

Presence for website Milk and Cookies

2020-09-25 18:22 UTC, Bas950 requested changes
Dont upload JS file

2020-09-25 18:22 UTC, Bas950 commented on websites/M/Milk and Cookies/dist/metadata.json
> +  "thumbnail": "https://cdn.discordapp.com/icons/740677919919046788/52922d16a00f0a8de2b9d5cbcec3f8fd.webp?size=2048",
upload to imgur

2020-09-25 18:22 UTC, Bas950 commented on websites/M/Milk and Cookies/dist/metadata.json
> +  "version": "1.0",
version 1.0.0

2020-09-25 18:22 UTC, Bas950 commented on websites/M/Milk and Cookies/dist/metadata.json
> +    "es": "¡Comunidad de Discord para todos!"
you also need an english description

2020-09-25 18:22 UTC, Bas950 commented on websites/M/Milk and Cookies/dist/metadata.json
> +    "galletas y leche"
cant have spaces in tags

2020-09-25 18:22 UTC, Bas950 commented on websites/M/Milk and Cookies/presence.ts
> +
no var (see codacy errors)

2020-09-25 18:49 UTC, Bas950 requested changes

2020-09-25 18:49 UTC, Bas950 commented on websites/M/Milk and Cookies/dist/metadata.json
> +    "en": "Discord Community for everyone!"
, not .

2020-09-25 19:10 UTC, ririxichan requested changes
change to i.imgur.com

2020-09-25 19:10 UTC, ririxichan commented on websites/M/Milk and Cookies/dist/metadata.json
> +  "thumbnail": "https://imgur.com/g2C5xmp",
Change to https://i.imgur.com/g2C5xmp.png

2020-09-25 19:18 UTC, ririxichan requested changes

2020-09-25 19:18 UTC, ririxichan commented on websites/M/Milk and Cookies/dist/metadata.json
> +  "thumbnail": "https://i.imgur.com/g2C5xmp",
add .png to end in both

2020-09-25 19:25 UTC, ririxichan approved these changes

2020-09-25 19:32 UTC, ririxichan requested changes

2020-09-25 19:32 UTC, ririxichan commented on websites/M/Milk and Cookies/presence.ts
> +const browsingStamp = Math.floor(Date.now() / 1000);
merge consts (just noticed it)

2020-09-25 19:46 UTC, ririxichan requested changes

2020-09-25 19:46 UTC, ririxichan commented on websites/M/Milk and Cookies/presence.ts
> +  browsingStamp = Math.floor(Date.now() / 1000);
```javascript
const presence = new Presence({ 
  clientId: "758753662079729764" 
}),
  browsingStamp = Math.floor(Date.now() / 1000);
```
or
```javascript
const presenceData: PresenceData = {
		largeImageKey: "icon"
	},
  browsingStamp = Math.floor(Date.now() / 1000);
```

2020-09-25 21:57 UTC, Bas950 requested changes
Upload proof of the presence working

2020-09-25 21:57 UTC, Bas950 commented on websites/M/Milk and Cookies/dist/metadata.json
> +  "color": "#FF0098",
thumbnail should be a promotional image or a screenshot of the website homepage

2020-09-25 21:58 UTC, ririxichan requested changes

2020-09-25 21:58 UTC, ririxichan commented on websites/M/Milk and Cookies/presence.ts
> +
delete blank line

2020-09-25 22:16 UTC, JeffreyDeveloper commented
![image](https://user-images.githubusercontent.com/51806683/94320548-798a7000-ff4a-11ea-8e6c-19c2bd22bf20.png)

2020-09-25 22:48 UTC, Bas950 approved these changes

2020-09-25 23:01 UTC, ririxichan approved these changes

2020-09-26 02:32 UTC, Alanexei approved these changes

2020-09-26 02:32 UTC, merged