New Presence: IMDBFilmIzle
PreMiD/Presences pull request #2220
Opened 2020-09-25 21:11 UTC by Serhann

![image](https://user-images.githubusercontent.com/26342121/94315790-e540fd00-ff8b-11ea-8b4b-79cff6197049.png)
![image](https://user-images.githubusercontent.com/26342121/94315799-ea9e4780-ff8b-11ea-961b-d8327c9d63d5.png)
![image](https://user-images.githubusercontent.com/26342121/94315813-ee31ce80-ff8b-11ea-93d7-59b4a761f6e3.png)
![image](https://user-images.githubusercontent.com/26342121/94315820-f0942880-ff8b-11ea-8a0c-fee0ea7f5e3f.png)

2020-09-25 21:20 UTC, ririxichan requested changes

2020-09-25 21:20 UTC, ririxichan commented on websites/I/IMDbFilmIzle/dist/metadata.json
> +    "dizi izle"
remove spaces and add ``-`` or delete these tags.

2020-09-25 21:20 UTC, ririxichan commented on websites/I/IMDbFilmIzle/iframe.ts
> +    } else iframe.send({ error: true })
```javascript
} else {
```

2020-09-25 21:20 UTC, ririxichan commented on websites/I/IMDbFilmIzle/presence.ts
> +  var endTime = Math.floor(startTime / 1000) - videoTime + videoDuration;
var -> const and combine them

2020-09-25 21:20 UTC, ririxichan commented on websites/I/IMDbFilmIzle/presence.ts
> +    let timestamps = getTimestamps(Math.floor(video.currentTime), Math.floor(video.duration));
let -> const

2020-09-25 21:20 UTC, ririxichan commented on websites/I/IMDbFilmIzle/presence.ts
> +presence.on("iFrameData", (data:any) => {
Change any to another type

2020-09-25 21:20 UTC, ririxichan commented on websites/I/IMDbFilmIzle/presence.ts
> +
delete this blank line.

2020-09-25 21:55 UTC, ririxichan approved these changes

2020-09-25 22:00 UTC, Bas950 approved these changes

2020-09-26 02:34 UTC, Alanexei approved these changes

2020-09-26 02:34 UTC, merged