Fix chapter number exibition on MangaHost
PreMiD/Presences pull request #2241
Opened 2020-09-28 15:01 UTC by igorquintaes

Selector before changes (last line):

![image](https://user-images.githubusercontent.com/10831729/94449136-2438a380-0182-11eb-86ba-9f5c5c30beee.png)

Selector after chances (two possible cases):

![image](https://user-images.githubusercontent.com/10831729/94449161-2bf84800-0182-11eb-93b8-43e5fe7beec7.png)

2020-09-28 15:09 UTC, Bas950 requested changes
bump version in metadata and upload proof of it working

2020-09-28 16:38 UTC, igorquintaes commented
Proof of work:
![image](https://user-images.githubusercontent.com/10831729/94460989-e5114f00-018f-11eb-9623-ba9241c6cf9e.png)

Previous version:
![image](https://user-images.githubusercontent.com/10831729/94460899-c7dc8080-018f-11eb-8da9-42a725c1d298.png)

2020-09-28 20:56 UTC, Bas950 approved these changes

2020-09-29 13:15 UTC, Alanexei approved these changes

2020-09-29 13:15 UTC, merged