Fix Bilibili
PreMiD/Presences pull request #2262
Opened 2020-10-01 10:02 UTC by Kotoki1337

![image](https://user-images.githubusercontent.com/35394151/94795605-24e66980-0410-11eb-8a17-415a66cba5ca.png)

Just make it work.
Some things in bilibili have changed, and I will recode some things when I have free time.

2020-10-01 10:23 UTC, ririxichan requested changes
Fix codacy error

2020-10-01 12:31 UTC, Bas950 approved these changes

2020-10-01 14:02 UTC, ririxichan approved these changes

2020-10-08 03:58 UTC, Timeraa approved these changes

2020-10-08 03:58 UTC, merged