Roll20
PreMiD/Presences pull request #2264
Opened 2020-10-01 16:51 UTC by MrBartusek

I have added presence for most of the [roll20.net](https://roll20.net) a popular website for playing tabletop role-playing games (like dungeons and dragons)

![image](https://user-images.githubusercontent.com/23432278/94836857-c3c09500-0413-11eb-84cc-557f455c6b25.png)
![image](https://user-images.githubusercontent.com/23432278/94839090-d38da880-0416-11eb-9c95-6358adcb4c01.png)

Supports hiding of details:
![image](https://user-images.githubusercontent.com/23432278/94838813-69750380-0416-11eb-88ff-8bba28d6f3f5.png)
![image](https://user-images.githubusercontent.com/23432278/94839021-b9ec6100-0416-11eb-8fce-4a18966af9e3.png)

2020-10-01 17:08 UTC, MrBartusek commented
Not sure if I should fix these `Combine this with the previous 'const' statement`?

2020-10-01 17:09 UTC, Bas950 commented
> Not sure if I should fix these `Combine this with the previous 'const' statement`?

const var1 = obj,
var2 = obj2;

2020-10-01 21:16 UTC, Bas950 requested changes

2020-10-01 21:16 UTC, Bas950 commented on websites/R/Roll20/dist/metadata.json
> +   "logo": "https://s3.amazonaws.com/files.d20.io/marketplace/527279/nvsTfqKL38EeMpudZyiUeg/med.png?1526331193298",
upload to imgur

2020-10-01 21:16 UTC, Bas950 commented on websites/R/Roll20/dist/metadata.json
> +   ]
upload a screenshot of the setting in the extension

2020-10-02 12:48 UTC, Bas950 approved these changes

2020-10-04 17:26 UTC, Timeraa approved these changes

2020-10-04 17:26 UTC, merged