New Presence: Invidious
PreMiD/Presences pull request #2267
Opened 2020-10-02 17:23 UTC by TheLastZombie

Adds support for [Invidious](https://github.com/iv-org/invidious/).

Invidious can be self-hosted. There used to be an [official instance](https://invidio.us/), but it was since replaced with a [list of popular public instances](https://instances.invidio.us/). URLs were taken from said list, minus .onion and .i2p domains.

### Screenshots

![image](https://user-images.githubusercontent.com/8181990/94951043-e4582000-04e3-11eb-9441-9ddd5f076822.png)
![image](https://user-images.githubusercontent.com/8181990/94951197-26816180-04e4-11eb-839c-f695653c35d2.png)
![image](https://user-images.githubusercontent.com/8181990/94951217-2ed99c80-04e4-11eb-985f-1aa4ff026a02.png)

2020-10-02 22:39 UTC, Bas950 requested changes
Add support for pages other then /watch
As it might look broken on the other pages.

2020-10-02 22:39 UTC, Bas950 commented on websites/I/Invidious/dist/metadata.json
> +  "logo": "https://invidio.us/static/img/invidious-logo-dark.svg",
upload to imgur

2020-10-03 08:38 UTC, TheLastZombie commented
New screenshots:

| ![2020-10-03_10-28](https://user-images.githubusercontent.com/8181990/94987159-67b95600-0564-11eb-924b-27fb5d8d7783.png) | ![2020-10-03_10-34](https://user-images.githubusercontent.com/8181990/94987162-6851ec80-0564-11eb-9616-872349c2c858.png) |
|-|-|
| ![2020-10-03_10-35](https://user-images.githubusercontent.com/8181990/94987163-68ea8300-0564-11eb-9e12-5a26ba1f1f71.png) | ![2020-10-03_10-35_1](https://user-images.githubusercontent.com/8181990/94987165-69831980-0564-11eb-97b8-4e78a5a7329c.png) |
| ![2020-10-03_10-35_2](https://user-images.githubusercontent.com/8181990/94987166-6a1bb000-0564-11eb-8f2a-4bdba4c5b955.png) | ![2020-10-03_10-35_3](https://user-images.githubusercontent.com/8181990/94987167-6ab44680-0564-11eb-9528-a2be93e2de4d.png) |
| ![2020-10-03_10-35_4](https://user-images.githubusercontent.com/8181990/94987169-6b4cdd00-0564-11eb-8d6d-0c27fa2edae1.png) | ![2020-10-03_10-35_5](https://user-images.githubusercontent.com/8181990/94987170-6b4cdd00-0564-11eb-9c60-9188d5a5e666.png) |

2020-10-03 13:58 UTC, Bas950 requested changes
Add support for pages other then /watch
As it might look broken on the other pages.

2020-10-03 13:58 UTC, Bas950 commented on websites/I/Invidious/presence.ts
> +      break;
dont set it to undefined.

2020-10-03 13:58 UTC, Bas950 commented on websites/I/Invidious/presence.ts
> +      break;
it can actually cause issues.

2020-10-03 14:22 UTC, Bas950 approved these changes
Add support for pages other then /watch
As it might look broken on the other pages.

2020-10-04 18:14 UTC, fr0r approved these changes
test

2020-10-08 03:59 UTC, Timeraa approved these changes

2020-10-08 03:59 UTC, merged