Reckless Life Presence
PreMiD/Presences pull request #2269
Opened 2020-10-03 05:55 UTC by misapprehending

2020-10-03 11:33 UTC, Bas950 commented
Upload proof of it working

2020-10-03 11:37 UTC, misapprehending commented
https://streamable.com/ovmv9l

2020-10-03 14:01 UTC, Bas950 requested changes

2020-10-03 14:01 UTC, Bas950 commented on websites/R/Reckless Life/dist/metadata.json
> +    "color": "#d61515",
thumbnail should be a promotional banner or a screenshot of the website homepage

2020-10-03 14:01 UTC, Bas950 commented on websites/R/Reckless Life/dist/metadata.json
> +    "logo": "https://i.imgur.com/SnK6byp.png",
logo is for something called Foster? you also named the presence that in discord, is this correct? Since you called it Reckless Life here...

2020-10-03 14:07 UTC, Bas950 requested changes
Dont forget to change folder name & location

2020-10-03 14:07 UTC, Bas950 commented on websites/R/Reckless Life/dist/metadata.json
>      },
Description should be of what the website is, not information like this.

2020-10-03 14:07 UTC, Bas950 commented on websites/R/Reckless Life/dist/metadata.json
>      },
Found their official description:
Foster. The Powerful Discord Bot.

2020-10-04 12:05 UTC, Bas950 requested changes
change folder name and location to F -> Foster

2020-10-04 12:22 UTC, Bas950 approved these changes
change folder name and location to F -> Foster

2020-10-08 04:14 UTC, misapprehending commented
I noticed you approved one of my other pull requests, do you need to add yourself to this one as well? @Timeraa

2020-10-08 05:48 UTC, Timeraa approved these changes

2020-10-08 05:48 UTC, merged

2020-10-08 05:48 UTC, Timeraa commented
Nope x2