New presence: FurAffinity
PreMiD/Presences pull request #2287
Opened 2020-10-06 20:24 UTC by Keenora

![browsing-category](https://user-images.githubusercontent.com/1299217/95256021-8a789280-0822-11eb-947e-1c538af6559f.jpg)
![creates-journal](https://user-images.githubusercontent.com/1299217/95256025-8ba9bf80-0822-11eb-88e1-cecfa483f749.jpg)
![reading-note](https://user-images.githubusercontent.com/1299217/95256026-8ba9bf80-0822-11eb-8f6f-e389c71c116b.jpg)
![search](https://user-images.githubusercontent.com/1299217/95256027-8c425600-0822-11eb-9149-5ae45bcd898e.jpg)
![settings](https://user-images.githubusercontent.com/1299217/95256029-8c425600-0822-11eb-9284-998cfdb2ea6a.jpg)
![updating-journal](https://user-images.githubusercontent.com/1299217/95256030-8cdaec80-0822-11eb-94bc-8d8a6fa9dbf7.jpg)
![viewing-art](https://user-images.githubusercontent.com/1299217/95256032-8cdaec80-0822-11eb-8e19-cb349f0dde13.jpg)
![viewing-profile](https://user-images.githubusercontent.com/1299217/95256033-8d738300-0822-11eb-836b-48e1637631e8.jpg)
![viewing-submissions](https://user-images.githubusercontent.com/1299217/95256037-8d738300-0822-11eb-904e-1e67083c8ec8.jpg)
![writes-a-note](https://user-images.githubusercontent.com/1299217/95256038-8e0c1980-0822-11eb-9d8f-ced351e8942a.jpg)

2020-10-07 13:21 UTC, Bas950 requested changes

2020-10-07 13:21 UTC, Bas950 commented on websites/F/FurAffinity/dist/metadata.json
> +  "version": "1.0.1",
version 1.0.0 on release

2020-10-08 03:54 UTC, Timeraa approved these changes

2020-10-08 13:17 UTC, Bas950 approved these changes

2020-10-08 13:18 UTC, merged