Add my Invidious Instance
PreMiD/Presences pull request #2308
Opened 2020-10-11 16:28 UTC by ChaseHall

Adds invidious.cmh.pw to Invidious App.

2020-10-11 19:14 UTC, Bas950 requested changes
Bump version and upload proof of it working

2020-10-12 00:05 UTC, ChaseHall commented
[Proof of it working](https://i.imgur.com/SDSFX5Q.png)

2020-10-12 12:57 UTC, Bas950 approved these changes

2020-10-14 07:12 UTC, Timeraa approved these changes

2020-10-14 07:13 UTC, merged