Fix Hulu video player element
PreMiD/Presences pull request #2312
Opened 2020-10-12 00:17 UTC by kagbogre

Fixes Hulu’s presence. The video element it’s currently looking for is no longer correct.

Before fix:
![image](https://user-images.githubusercontent.com/4789757/95694211-04e55000-0c31-11eb-90f4-676769926ca9.png)

After fix:
![image](https://user-images.githubusercontent.com/4789757/95694198-f434da00-0c30-11eb-88cc-8dc1cf9181d0.png)

2020-10-12 12:57 UTC, Bas950 requested changes
bump version

2020-10-12 16:29 UTC, Bas950 requested changes
it isn't that big of a change to be able to add yourself as contributor of the presence.

2020-10-12 17:48 UTC, Bas950 approved these changes

2020-10-14 07:07 UTC, Timeraa approved these changes

2020-10-14 07:07 UTC, merged