Updated Gogoanime url
PreMiD/Presences pull request #2341
Opened 2020-10-16 07:37 UTC by PsychoPast

2020-10-16 12:29 UTC, Bas950 requested changes
upload proof of it working

2020-10-17 14:05 UTC, PsychoPast commented
> upload proof of it working

![image](https://user-images.githubusercontent.com/33565739/96339092-eb159400-109a-11eb-937d-08958e22a2b9.png)

2020-10-17 14:23 UTC, Bas950 approved these changes

2020-10-17 17:38 UTC, Timeraa approved these changes

2020-10-17 17:39 UTC, merged