New Presence: Peacock
PreMiD/Presences pull request #2348
Opened 2020-10-18 15:19 UTC by kagbogre

Presence for [Peacock](https://www.peacocktv.com), 3 states: Browsing, Watching and Paused.

![Discord_Nqv8rloAj1](https://user-images.githubusercontent.com/4789757/96372170-fe416600-1165-11eb-9dc7-458e81cb6213.png)
![Discord_BusNjrcCou](https://user-images.githubusercontent.com/4789757/96372173-026d8380-1166-11eb-9171-b51d7a033466.png)
![Discord_68sfiWnvSK](https://user-images.githubusercontent.com/4789757/96372177-04cfdd80-1166-11eb-8375-db06849b4362.png)
![Discord_2xBmaIDic0](https://user-images.githubusercontent.com/4789757/96372180-07323780-1166-11eb-9827-ed876acc0772.png)

2020-10-18 15:22 UTC, Bas950 requested changes

2020-10-18 15:22 UTC, Bas950 commented on websites/P/Peacock/presence.ts
> +});
make sure that if something is undefined you dont send it,
you just dont .setActivity at all or you need to delete presenceData.state lets say to it doesnt send it.

2020-10-18 18:41 UTC, Bas950 commented
You only fixed it for state, but rn everything can be undefined so you need to fix it for everything...

2020-10-18 19:09 UTC, kagbogre commented
> You only fixed it for state, but rn everything can be undefined so you need to fix it for everything...

It now checks every value that can be undefined.

2020-10-19 14:41 UTC, Bas950 approved these changes

2020-10-21 21:11 UTC, ririxichan approved these changes

2020-10-21 21:13 UTC, merged