DreamSub Discord Presence
PreMiD/Presences pull request #2367
Opened 2020-10-20 22:44 UTC by diskxo

I created the discord presence for the website dreamsub.stream.

2020-10-20 23:50 UTC, Bas950 requested changes
Fix codacy issues.

2020-10-20 23:50 UTC, Bas950 commented on websites/D/DreamSub/tsconfig.json
> +}
fix spacing

2020-10-22 16:24 UTC, diskxo commented
Ok, I should have fixed everything

2020-10-22 17:16 UTC, Bas950 approved these changes
Fix codacy issues.

2020-10-22 17:17 UTC, ririxichan approved these changes

2020-10-22 17:18 UTC, merged