Update the IframeRegExp of metadata.json
PreMiD/Presences pull request #2387
Opened 2020-10-25 23:02 UTC by diskxo

I updated the IframeRegExp  of the metadata.json file, and edited the version of the presence

2020-10-25 23:10 UTC, Bas950 requested changes
upload proof of the presence working

2020-10-25 23:39 UTC, diskxo commented
> upload proof of the presence working

https://prnt.sc/v6p2l5

https://prnt.sc/v6p2sq

https://prnt.sc/v6p340

2020-10-26 16:00 UTC, ririxichan requested changes
Fix conflicting files

2020-10-26 17:38 UTC, diskxo commented
Okay, I should have fixed everything

2020-10-26 17:41 UTC, ririxichan submitted a review, later dismissed

2020-10-26 22:40 UTC, Bas950 requested changes
bump version

2020-10-28 14:19 UTC, ririxichan requested changes
Well, you added DreamSub to Diziay folder, so please resolve it, and bump this version

2020-10-28 16:02 UTC, Bas950 requested changes
yea something is wrong with your folders mate...

2020-10-28 23:36 UTC, diskxo commented
> yea something is wrong with your folders mate...

i'm new to github in general, and having no idea how to bump version, so i think i broke the folders ... could you remove the folder from your repository, so i can put it back as the first version?

2020-10-30 07:50 UTC, diskxo reviewed
I have reviewed the project and everything seems correct

2020-10-30 07:52 UTC, diskxo commented
I also added another presence of the figma.com site

2020-10-30 07:53 UTC, ririxichan commented
No, ![](https://i.ririxi.dev/dc28gmxxG) 
it doesn't...

2020-10-30 08:37 UTC, diskxo commented
Ok, I fixed it.. -_- 

as a last thing I would like to ask you how to bump version with the repository, because I am new to github and I have no idea how to do it

2020-10-30 12:56 UTC, ririxichan requested changes
proofs, please change and run prettier on this because you have a spaces after ifs and not. so please fix it.

2020-10-30 12:56 UTC, ririxichan commented on websites/D/DreamSub/dist/metadata.json
> +    "version": "1.0.1",
version 1.0.2

2020-10-30 12:56 UTC, ririxichan commented on websites/F/Figma/presence.ts
> +const browsingStamp = Math.floor(Date.now() / 1000);
combine consts

2020-10-30 12:56 UTC, ririxichan commented on websites/F/Figma/presence.ts
> +})
no semicolon

2020-10-30 13:16 UTC, ririxichan commented
I will ask last time for proofs of working for these presences. If not we will close this ticket in ~2 days.

2020-10-31 00:32 UTC, merged