Updated Starz Presence
PreMiD/Presences pull request #2399
Opened 2020-10-26 22:40 UTC by kagbogre

Modified the `title !== null` check to `if(title)` to cover all falsy values (including "").

Had problems while developing the Philo presence because the title was "", so I'm changing it here as well, just in case.

2020-10-26 22:43 UTC, Bas950 requested changes
Upload proof of it working

2020-10-26 22:47 UTC, kagbogre commented
> Upload proof of it working

![image](https://user-images.githubusercontent.com/4789757/97236430-6ab30980-17e5-11eb-8ae8-913de688b786.png)
![image](https://user-images.githubusercontent.com/4789757/97236501-83bbba80-17e5-11eb-92fe-34c32e74760c.png)

2020-10-27 02:44 UTC, Bas950 approved these changes

2020-10-27 14:18 UTC, ririxichan approved these changes

2020-10-27 14:19 UTC, merged