VRChat: New Precense
PreMiD/Presences pull request #2424
Opened 2020-11-02 15:12 UTC by KnuffelBeestje

**Supports:**
- VRChat Portal (vrchat.com)
- VRChat Landing Page (hello.vrchat.com)

**Features:**
- Show username if logged in
- Show search results
- Show the world/avatar/user you're viewing

**Settings:**
- Privacy Mode (Hide your username when logged in. Also doesn't show the avatar/world/user you're currently viewing.)
- Timer (Hide/Show timer)

**hello.vrchat.com**:
![image](https://user-images.githubusercontent.com/22412324/97883798-9b36fe00-1d25-11eb-95fe-0255148205fb.png)

Discord: 
![image](https://user-images.githubusercontent.com/22412324/97883652-72166d80-1d25-11eb-8cf7-17d6d59bf03f.png)

**vrchat.com (portal)**:
![image](https://user-images.githubusercontent.com/22412324/97883589-5a3ee980-1d25-11eb-93ef-015806eb28ca.png)

Discord (Without Privacy Mode turned on): 
![image](https://user-images.githubusercontent.com/22412324/97883881-b4d84580-1d25-11eb-9973-9cd2671eedc4.png)
Discord (With Privacy Mode turned on): 
![image](https://user-images.githubusercontent.com/22412324/97884003-d6d1c800-1d25-11eb-993c-0d11331a8904.png)

2020-11-02 15:20 UTC, ririxichan requested changes
Fix things, also if you would run [Prettier](https://prettier.io) to just make code style better, it would be great

2020-11-02 15:20 UTC, ririxichan commented on VRChat/dist/metadata.json
> +    "thumbnail": "https://i.imgur.com/0Kf1m7Q.png",
There isn't any vrchat banner or could you change it to vrchat site screenshot?

2020-11-02 15:20 UTC, ririxichan commented on VRChat/dist/presence.js
> +});
delete this file

2020-11-02 15:20 UTC, ririxichan commented on VRChat/presence.ts
> +
delete 1 blank space

2020-11-02 15:20 UTC, ririxichan commented on VRChat/presence.ts
> +  var browsingStamp = Math.floor(Date.now() / 1000);
var -> const, merge consts

2020-11-02 15:20 UTC, ririxichan commented on VRChat/presence.ts
> +  var tempusername = document.querySelector(".user-info > h6");
var -> const

2020-11-02 15:20 UTC, ririxichan commented on VRChat/presence.ts
> +
delete this blank line

2020-11-02 15:20 UTC, ririxichan commented on VRChat/presence.ts
> +  const timertoggle = await presence.getSetting("timer");
merge consts

2020-11-02 15:20 UTC, ririxichan commented on VRChat/presence.ts
> +  var viewingprofilename = document.querySelector("div.col-md-12 > h2").textContent;
var -> const, merge consts

2020-11-02 15:20 UTC, ririxichan commented on VRChat/presence.ts
> +    const timertoggle = await presence.getSetting("timer");
merge consts

2020-11-02 15:20 UTC, ririxichan commented on VRChat/presence.ts
> +              var worldname = document.querySelector(".col-md-12 > h3").textContent;
var -> const

2020-11-02 15:20 UTC, ririxichan commented on VRChat/presence.ts
> +              var searchresult = window.location.toString().substr(window.location.toString().lastIndexOf('/')+1);
var -> const

2020-11-02 15:20 UTC, ririxichan commented on VRChat/presence.ts
> +              var avatarpublicstatus = document.querySelector("div.col-12.col-md-8 > h4 > span > small").textContent;
var -> const, merge consts

2020-11-02 18:06 UTC, KnuffelBeestje reviewed
Everything is working as expected.

2020-11-03 09:31 UTC, ririxichan approved these changes

2020-11-04 22:26 UTC, Bas950 approved these changes

2020-11-04 22:37 UTC, merged