Upload Voz.vn Rich Presence
PreMiD/Presences pull request #2433
Opened 2020-11-05 00:26 UTC by TheDyet94

![2020-11-5 7-24-45](https://user-images.githubusercontent.com/73962796/98182370-2c7dbe80-1f38-11eb-85ab-206691963fee.png)
![2020-11-5 7-26-1](https://user-images.githubusercontent.com/73962796/98182372-2daeeb80-1f38-11eb-82de-36557315f3de.png)

2020-11-05 15:39 UTC, Bas950 requested changes
Fix codacy errors.

2020-11-06 10:58 UTC, ririxichan requested changes

2020-11-06 10:58 UTC, ririxichan commented on websites/V/Voz.vn/presence.ts
> +  const presenceData: presenceData = {
this is PresenceData

2020-11-06 10:58 UTC, ririxichan commented on websites/V/Voz.vn/presence.ts
> +const browsingStamp = Math.floor(Date.now() / 1000);
merge consts

2020-11-06 10:58 UTC, ririxichan commented on websites/V/Voz.vn/dist/metadata.json
> +  "version": "1.0.1",
1.0.0

2020-11-10 08:52 UTC, ririxichan commented
No response from author. If you want to do pull requested with fixed changes, sure. For now I am closing this pull request.

2020-11-10 08:52 UTC, closed without merging