Changed API keys and incremented version
PreMiD/Presences pull request #2438
Opened 2020-11-07 10:39 UTC by DefectivenessYT

Changed some API values to ones that function

2020-11-07 10:42 UTC, ririxichan requested changes
upload proof of working presence

2020-11-07 10:52 UTC, DefectivenessYT commented
https://i.imgur.com/7Ekt5nL.png

2020-11-07 20:47 UTC, ririxichan approved these changes

2020-11-09 18:42 UTC, Bas950 approved these changes

2020-11-09 18:43 UTC, merged