Added xero.gg support.
PreMiD/Presences pull request #2451
Opened 2020-11-09 21:41 UTC by Dekirai

Showcase: [Showcase](https://streamable.com/k0od9w)
What it is: xero.gg is a player and clan database for the private server called "S4 Xero" of the base game "S4 League".
What the presence does: The presence mainly shows what profile or clan you are currently looking at or what news you are currently reading. More features included and might follow.

2020-11-10 08:49 UTC, ririxichan requested changes
upload proof of working presence

2020-11-10 08:50 UTC, ririxichan approved these changes

2020-11-11 00:23 UTC, Dekirai commented
Uhh how do I fix this Codacy stuff?

2020-11-11 00:28 UTC, Dekirai commented
Whats wrong with the codacy?
How do I fix this?

2020-11-11 00:39 UTC, Dekirai commented
I don't understand why I'm getting the codacy errors now.
It worked before and I haven't touched anything where it throws the error.
How would I fix this? I don't understand it.

2020-11-11 13:20 UTC, ririxichan requested changes
You don't need let variables for them, because you only use these variables in if statements so please change it to const.

2020-11-11 14:42 UTC, Dekirai commented
I hope it's okay now..

2020-11-11 14:46 UTC, Bas950 requested changes

2020-11-11 14:46 UTC, Bas950 commented on websites/X/Xero.gg/presence.ts
> +    ];
thats an array, thats now how you merge consts

```
const var1 = obj,
var2 = obj2;
```

2020-11-11 14:57 UTC, Dekirai commented
Okay I hope I finally understood it now.
I feel so stupid, I'm so sorry.

2020-11-11 14:58 UTC, ririxichan approved these changes

2020-11-11 14:59 UTC, Bas950 commented
just to be sure please upload new proof of it working

2020-11-11 14:59 UTC, Dekirai commented
Ah sure, 1 sec

2020-11-11 15:03 UTC, Dekirai commented
@Bas950 I replaced the Showcase Link with a new video (You can also see the current date and time of windows)

2020-11-11 15:05 UTC, Bas950 approved these changes

2020-11-11 15:05 UTC, merged