:sparkles: Updated.
PreMiD/Presences pull request #2458
Opened 2020-11-11 19:40 UTC by TheDropX

2020-11-11 19:47 UTC, ririxichan requested changes
and upload proof of working presence

2020-11-11 19:47 UTC, ririxichan commented on websites/P/PornHub/presence.ts
> +  let endTime = Math.floor(startTime / 1000) - videoTime + videoDuration;
const and merge consts

2020-11-11 19:47 UTC, ririxichan commented on websites/P/PornHub/presence.ts
> +  let video: HTMLVideoElement = document.querySelector(
let -> const

2020-11-11 19:47 UTC, ririxichan commented on websites/P/PornHub/presence.ts
> +    let uploader: HTMLElement = document.querySelector(
can be const, and merge them

2020-11-12 11:11 UTC, ririxichan requested changes

2020-11-12 11:11 UTC, ririxichan commented on websites/P/PornHub/presence.ts
> +    let timestamps = getTimestamps(
let -> const

2020-11-12 15:59 UTC, Bas950 requested changes
Upload proof of it working

2020-11-13 02:38 UTC, merged