MojeVideo Presence
PreMiD/Presences pull request #2462
Opened 2020-11-12 12:13 UTC by Blyster111

Presence for site MojeVideo.sk
![mvpreview](https://user-images.githubusercontent.com/23199079/98938817-cae5c300-24e8-11eb-9f3a-2108c4e82613.png)

2020-11-12 12:17 UTC, ririxichan requested changes

2020-11-12 12:17 UTC, ririxichan commented on websites/M/MojeVideo/dist/metadata.json
> +    "en": "MojeVideo is a Slovak video streaming/sharing website mostly with funny, short videos."
add description in lang that this presence is written (slovak)

2020-11-12 12:17 UTC, ririxichan commented
and fix codacy errors

2020-11-13 02:41 UTC, Bas950 approved these changes

2020-11-14 14:09 UTC, ririxichan approved these changes

2020-11-14 14:09 UTC, merged