Proxer: New presence
PreMiD/Presences pull request #2465
Opened 2020-11-12 18:34 UTC by Paul1365972

New presence for proxer.me, focuses on displaying the current episode for now

2020-11-13 02:45 UTC, Bas950 requested changes
Upload proof of it working and fix codacy errors

2020-11-13 13:11 UTC, Paul1365972 commented
Fixed code style errors and here is the currently working version
![image](https://user-images.githubusercontent.com/11490082/99075488-de149380-25b9-11eb-83ed-ff2698c5e155.png)
![image](https://user-images.githubusercontent.com/11490082/99075611-0d2b0500-25ba-11eb-9f29-f153e160733b.png)

2020-11-14 13:13 UTC, Bas950 requested changes

2020-11-14 13:13 UTC, Bas950 commented on websites/P/Proxer/dist/metadata.json
> +  "version": "1.0.1",
version 1.0.0 on release

2020-11-14 23:12 UTC, ririxichan approved these changes

2020-11-16 23:04 UTC, Bas950 approved these changes

2020-11-16 23:05 UTC, merged