Added Symphony and Harmony as a presence
PreMiD/Presences pull request #2467
Opened 2020-11-12 22:59 UTC by xxdjbobbyxx

I have checked everything and it all works and I have added:
Symphony
Harmony as a radio presence

2020-11-13 02:47 UTC, Bas950 requested changes
Undo change in package.json
Fix codacy errors
Version 1.0.0 on release

2020-11-13 09:55 UTC, xxdjbobbyxx commented
I have changed the following ages ago but for some reason git push never did anything so I have manually changed them and fixed the errors

2020-11-14 13:11 UTC, Bas950 requested changes
Don't upload the JS files.
Upload proof of it working.

2020-11-14 13:11 UTC, Bas950 commented on websites/H/Harmony/dist/metadata.json
> +  "color": "#46356e",
why is the thumbnail blurred?

2020-11-14 13:11 UTC, Bas950 commented on websites/H/Harmony/dist/metadata.json
> +  "service": "Harmony",
change service name and folder name to "Harmony Radio"

2020-11-14 14:07 UTC, xxdjbobbyxx commented
Everything has been fixed and as you can see I have made sure everything works!
![image](https://user-images.githubusercontent.com/70226753/99148921-96a60a00-2682-11eb-89ea-bcde442315d4.png)
![image](https://user-images.githubusercontent.com/70226753/99148941-b9382300-2682-11eb-8f0a-8c340e220eb3.png)

2020-11-14 14:13 UTC, ririxichan commented
Harmony radio is not 2months old. Symphony one is on free domain. We do not accept these websites. Feel free to open pull request at 19.11.2020 for harmony radio but not for symphony.

2020-11-14 14:13 UTC, closed without merging

2020-11-14 14:13 UTC, DefectivenessYT commented
sorry to butt in, but these sites are totally not 2 months old as stated in the contributor rules. both of these were made recently and one of them is on a free domain

2020-11-14 14:14 UTC, DefectivenessYT commented
oh ririxichan you beat me to it