Added Dizimag support.
PreMiD/Presences pull request #2480
Opened 2020-11-16 20:04 UTC by erdem85

**While watching**
![watching-gif](https://github.com/erdem85/erdem85/blob/main/n2d7JSUdd4.gif?raw=true)

**in user profile**
![image](https://user-images.githubusercontent.com/41632465/99301739-72ebeb00-285f-11eb-817f-12f6966f5db9.png)

**in tv series page**
![image](https://user-images.githubusercontent.com/41632465/99301865-a595e380-285f-11eb-8312-c3eb0e74aa4d.png)

[it's working fine.](https://dizimag2.org/)

2020-11-16 23:01 UTC, Bas950 requested changes

2020-11-16 23:01 UTC, Bas950 commented on websites/D/Dizimag/dist/metadata.json
> +    "version": "1.0.1",
v 1.0.0 on release

2020-11-17 07:15 UTC, erdem85 commented on websites/D/Dizimag/presence.ts
> +  };
👍 i changed test to presenceData

2020-11-17 07:24 UTC, ririxichan approved these changes

2020-11-17 14:39 UTC, Bas950 approved these changes

2020-11-17 14:40 UTC, merged