Add Bonk2.io presence
PreMiD/Presences pull request #2482
Opened 2020-11-17 06:44 UTC by Snazzah

[Bonk2.io](https://bonk2.io) is a multiplayer browser game where the objective is to knock all of the opponents off the edge of the screen and be the last man standing.

<details>
  <summary>Screenshots</summary>

![menu](https://get.snaz.in/4MyTNeL.png)
![lobby](https://get.snaz.in/7yVw3Ya.png)
![ingame](https://get.snaz.in/3c2L85i.png)
</details>

<details>
  <summary>Settings Screenshot</summary>

![](https://get.snaz.in/8uXoBjr.png)
</details>

2020-11-17 07:23 UTC, ririxichan requested changes

2020-11-17 07:23 UTC, ririxichan commented on websites/B/Bonk2.io/dist/metadata.json
> +  "thumbnail": "https://get.snaz.in/6kRAysH.png",
should be imgur link

2020-11-17 14:58 UTC, Bas950 approved these changes

2020-11-19 09:04 UTC, ririxidev approved these changes

2020-11-19 09:05 UTC, merged