New Presence: Dropbox
PreMiD/Presences pull request #2483
Opened 2020-11-17 13:36 UTC by MrBartusek

![image](https://user-images.githubusercontent.com/23432278/99396489-167ddf80-28e2-11eb-84c4-8687bf604906.png)
![image](https://user-images.githubusercontent.com/23432278/99396585-36150800-28e2-11eb-84ab-8975600bb694.png)
![image](https://user-images.githubusercontent.com/23432278/99396619-40370680-28e2-11eb-8bd6-ebf7d314960f.png)
![image](https://user-images.githubusercontent.com/23432278/99396638-46c57e00-28e2-11eb-995f-57ad04b9d82d.png)

2020-11-17 14:59 UTC, Bas950 requested changes
Add some presence settings for privacy, like for hiding file names etc.

2020-11-19 09:02 UTC, ririxidev submitted a review, later dismissed

2020-11-19 09:55 UTC, MrBartusek commented
![image](https://user-images.githubusercontent.com/23432278/99650295-85c81080-2a55-11eb-9729-36060c9d30a2.png)
![image](https://user-images.githubusercontent.com/23432278/99650315-8c568800-2a55-11eb-91ef-1320409d00c9.png)
![image](https://user-images.githubusercontent.com/23432278/99650334-91b3d280-2a55-11eb-9848-e16d30e4f70f.png)

2020-11-19 09:57 UTC, ririxidev approved these changes

2020-11-19 16:25 UTC, Bas950 approved these changes

2020-11-19 16:26 UTC, merged