added animepill.com
PreMiD/Presences pull request #2490
Opened 2020-11-18 18:33 UTC by Venipa

Website: [animepill.com](animepill.com)

![image](https://user-images.githubusercontent.com/17952364/99572374-da777700-29d4-11eb-8bd8-914867eb8999.png)

2020-11-18 20:00 UTC, Venipa commented
how does updating metadata cause these codacy errors...

2020-11-18 21:46 UTC, Venipa commented
fyi @Timeraa @Bas950

2020-11-19 08:52 UTC, ririxidev requested changes

2020-11-19 08:52 UTC, ririxidev commented on websites/A/AnimePill/dist/metadata.json
> +  "version": "1.0.2",
1.0.0 on release

2020-11-19 08:52 UTC, ririxidev commented on websites/A/AnimePill/dist/metadata.json
> +  "thumbnail": "https://i.mavis.moe/f/vpOrz4JxUA/2020-11-18-18-14-01png.png",
upload to imgur and use i.imgur

2020-11-19 08:52 UTC, ririxidev commented on websites/A/AnimePill/presence.ts
> +const initialize = async () => {
for what reason you are initializing because events works every 1 seconds or something :)

2020-11-19 16:06 UTC, Venipa commented
@ririxidev should be fine now (requested changes have been made)

2020-11-19 16:07 UTC, ririxidev approved these changes

2020-11-19 16:27 UTC, Bas950 approved these changes

2020-11-19 16:27 UTC, merged