AnimeDao: Updated website url, and some bug fixes
PreMiD/Presences pull request #2509
Opened 2020-11-22 06:35 UTC by Viruzaum

**Changes:**
- Updated website URL from `animedao.com/animedao2*.stream` to `animedao.to`.
- Removed regExp since the new URL doesn't change when playing videos anymore.
- Updated video providers in iFrames.
- Fixed playing/paused icons showing before the video is played.

**Screenshots:**
![Discord_1NIeoLdJOR](https://user-images.githubusercontent.com/23330390/99896879-61e21600-2c73-11eb-92ed-287a7b5de513.png)
![Discord_oUGUI6q07Y](https://user-images.githubusercontent.com/23330390/99896882-660e3380-2c73-11eb-97d1-d684f58ee213.png)
![Discord_mR90yHFtIH](https://user-images.githubusercontent.com/23330390/99896884-68708d80-2c73-11eb-9502-b3a7154f23eb.png)
![Discord_XUZSwSpDa9](https://user-images.githubusercontent.com/23330390/99896886-6d354180-2c73-11eb-8661-e527b0c6e945.png)
![Discord_8k1EGlsjkG](https://user-images.githubusercontent.com/23330390/99896888-71615f00-2c73-11eb-8156-7e5b316befc8.png)

2020-11-22 16:42 UTC, ririxidev requested changes

2020-11-22 16:42 UTC, ririxidev commented on websites/A/AnimeDao/presence.ts
> +  const endTime = Math.floor(startTime - videoTime + videoDuration);
merge consts

2020-11-22 16:42 UTC, ririxidev commented on websites/A/AnimeDao/dist/metadata.json
> +  "version": "1.2.7",
should be 1.2.6 don't jump over 2 versions

2020-11-22 17:50 UTC, Bas950 approved these changes

2020-11-23 16:42 UTC, ririxidev approved these changes

2020-11-23 16:42 UTC, merged