Updated API Link
PreMiD/Presences pull request #2531
Opened 2020-11-25 17:15 UTC by mainboiii

Updated Repeats API link as we now have a new one.

2020-11-25 17:17 UTC, ririxidev requested changes
bump version & upload proof of working presence :)

2020-11-25 17:20 UTC, mainboiii commented
What do you mean by bump version? soory lol

2020-11-25 18:18 UTC, mainboiii commented
Will get a screenshot soon for you.

2020-11-25 20:50 UTC, Bas950 requested changes

2020-11-25 20:50 UTC, Bas950 commented on websites/R/Repeat/presence.ts
> +    .fetch("https://repeat.bozzy.online/api/nowplaying/1")
You may only make HTTP/HTTPS requests to `premid.app` or the presence website API. If you are using external domains, you will be required to explain why it is necessary.

bozzy.online is not the presence website, so you need an api from repeat.pw or repeatradio.net

2020-11-26 08:58 UTC, mainboiii commented
Here is the PreMiD precence working:
![xebYu0DR](https://user-images.githubusercontent.com/29954924/100329456-95030d00-2fc5-11eb-9b06-6cc80e7072d2.png)

2020-11-26 13:17 UTC, Bas950 approved these changes

2020-11-26 16:33 UTC, mainboiii reviewed
Bump Version and showed screenshot and fixed other isuues.

2020-11-27 08:19 UTC, Timeraa approved these changes

2020-11-27 08:29 UTC, ririxidev approved these changes

2020-11-27 08:30 UTC, merged