[FIX] Wrong selected array element causes command category not to be found
PreMiD/Presences pull request #2532
Opened 2020-11-26 00:25 UTC by pablo1v

2020-11-26 13:17 UTC, Bas950 requested changes
Upload proof of it working

2020-11-27 22:17 UTC, pablo1v commented
![1](https://user-images.githubusercontent.com/62220882/100486954-2321e500-30e5-11eb-932e-0b5e14813896.png)
![2](https://user-images.githubusercontent.com/62220882/100486959-24531200-30e5-11eb-8e19-dff8e5a8fbf8.png)
![3](https://user-images.githubusercontent.com/62220882/100486960-24eba880-30e5-11eb-8b5b-bd73965612be.png)

2020-11-27 23:51 UTC, Bas950 requested changes
Fix codacy errors

2020-11-29 00:31 UTC, Bas950 approved these changes

2020-11-29 12:15 UTC, ririxidev approved these changes

2020-11-29 12:15 UTC, merged