Facepunch Wiki Presence
PreMiD/Presences pull request #2555
Opened 2020-11-30 14:00 UTC by MatStef132

Hello!
I have again made a rich presence, this time for facepunch wiki. It supports all the pages on all of the wikis.
Proof of working and settings here: https://imgur.com/a/TCVE9ZO

2020-11-30 14:24 UTC, ririxidev requested changes
You could do more than just showing "Viewing" messages...

2020-11-30 14:27 UTC, MatStef132 commented
I know, but really what else could be put in here? You can only put viewing here because there's nothing more. Maybe you have an idea to what can be added?

2020-11-30 14:28 UTC, ririxidev commented
You could add for example getting title on what site user is and showing it, showing on what guide they are etc.

2020-11-30 14:30 UTC, MatStef132 commented
It's showing on which wiki the user is and which page he is on.

2020-11-30 14:31 UTC, ririxidev commented
I meant different thing, but fine.

2020-11-30 14:31 UTC, ririxidev submitted a review, later dismissed

2020-11-30 14:46 UTC, ririxidev approved these changes

2020-11-30 15:02 UTC, Bas950 requested changes

2020-11-30 15:02 UTC, Bas950 commented on websites/F/Facepunch Wiki/dist/metadata.json
> +  "thumbnail": "https://imgur.com/dkTbScQ.png",
upload a better logo
and thumbnail should be a promotional banner or a screenshot of the website homepage

2020-11-30 15:02 UTC, Bas950 commented on websites/F/Facepunch Wiki/presence.ts
> +  }
maybe add some more statuses?
and I would personally put the document.title then on presenceData.state

2020-12-04 09:35 UTC, ririxidev commented
no response from author - closing. Feel free to open new pr after doing some changes

2020-12-04 09:35 UTC, closed without merging