Blockchain Presence
PreMiD/Presences pull request #2556
Opened 2020-11-30 22:43 UTC by TheGamerzs

![image](https://user-images.githubusercontent.com/44209534/100673910-32f72e80-335c-11eb-8b44-ce5f7bb0dc88.png)
![image](https://user-images.githubusercontent.com/44209534/100674604-540c4f00-335d-11eb-8be5-ad24052e2270.png)
![image](https://user-images.githubusercontent.com/44209534/100674687-74d4a480-335d-11eb-8806-aaa22d0fbb90.png)

2020-11-30 22:51 UTC, Bas950 requested changes

2020-11-30 22:51 UTC, Bas950 commented on websites/B/Blockchain/dist/metadata.json
> +  "logo": "https://i.imgur.com/tz8fOEn.png",
upload a logo of at least 512x512 size

2020-11-30 22:51 UTC, Bas950 commented on websites/B/Blockchain/dist/metadata.json
> +  "color": "#3d89f5",
thumbnail should be a promotional banner or screenshot of the website homepage.

2020-11-30 22:51 UTC, Bas950 commented on websites/B/Blockchain/presence.ts
> +var currencyList = [
bro really.... var?

2020-11-30 23:27 UTC, TheGamerzs commented
Fixed

2020-12-01 02:18 UTC, Bas950 requested changes

2020-12-01 02:18 UTC, Bas950 commented on websites/B/Blockchain/dist/metadata.json
> +  "version": "1.0.3",
version 1.0.0 on release

2020-12-01 02:18 UTC, Bas950 commented on websites/B/Blockchain/presence.ts
> +const browsingStamp = Math.floor(Date.now() / 1000);
merge

2020-12-01 02:18 UTC, Bas950 commented on websites/B/Blockchain/presence.ts
> +let pageStatus: string;
merge

2020-12-01 11:35 UTC, TheGamerzs commented on websites/B/Blockchain/presence.ts
> +const browsingStamp = Math.floor(Date.now() / 1000);
wdym by this?

2020-12-01 11:42 UTC, ririxidev commented on websites/B/Blockchain/presence.ts
> +const browsingStamp = Math.floor(Date.now() / 1000);
bruh.
e.g.
```javascript
const d = f(),
g = h();
```

2020-12-01 12:47 UTC, ririxidev approved these changes

2020-12-01 13:28 UTC, Bas950 approved these changes

2020-12-01 13:29 UTC, merged