Botsbase - Website
PreMiD/Presences pull request #2574
Opened 2020-12-05 13:46 UTC by Roxza

Hello, my english may be bad, I wanted to add my long-running website here and I guess it's happening Since I will add it for the first time, I do not have much information, I will be glad if you help.

Website: https://botsbase.net

2020-12-05 15:43 UTC, Bas950 requested changes
Upload proof of the presence working

2020-12-05 15:43 UTC, Bas950 commented on websites/B/BotsBase/dist/metadata.json
> +  "version": "1.0.4",
v1.0.0 on release

2020-12-05 15:43 UTC, Bas950 commented on websites/B/BotsBase/dist/metadata.json
> +  "service": "botsbase.net",
service name and foldername must be the same, and this is the name displayed on our website.

2020-12-05 15:43 UTC, Bas950 commented on websites/B/BotsBase/presence.ts
> +const browsingStamp = Math.floor(Date.now() / 1000);
merge consts

2020-12-05 16:09 UTC, Roxza commented
Hello again, I made the edits you want, the screenshots are below.

Home : https://i.imgur.com/xL1Fz7a.png
Add Bot : https://i.imgur.com/aD7CqNL.png
View Bot : https://i.imgur.com/fRXDuGQ.png
Bots Page : https://i.imgur.com/taJlrie.png
Search Page : https://i.imgur.com/SxBWhgr.png
Profile : https://i.imgur.com/7zITfyQ.png
Tags : https://i.imgur.com/S40ztyg.png
Vote : https://i.imgur.com/kaokEfi.png

2020-12-05 18:07 UTC, Bas950 requested changes
Fix codacy errors

2020-12-05 18:07 UTC, Bas950 commented
Also service name and folder name are still not the same

2020-12-06 09:34 UTC, Roxza commented
> Fix codacy errors

If you tell me a little detail where the error is located, I will fix it faster.

2020-12-06 10:57 UTC, Bas950 commented
> > Fix codacy errors
> 
> If you tell me a little detail where the error is located, I will fix it faster.

At the bottom of your screen it says checks failed and then click on details at codacy

2020-12-06 11:16 UTC, Roxza commented
all bugs solved

2020-12-06 22:00 UTC, Bas950 approved these changes

2020-12-07 18:27 UTC, ririxidev approved these changes
Merry Christmas 🎉 and GJ

2020-12-07 18:27 UTC, ririxidev commented on websites/B/BotsBase/presence.ts
> +	presenceData.startTimestamp = browsingStamp;
you could move startTimestamp to this object :/ but fine

2020-12-07 18:28 UTC, merged