🍃 Overleaf Presence
PreMiD/Presences pull request #2575
Opened 2020-12-06 05:36 UTC by Enevevet

NB: some titles on the Screenshots are in French because my Overleaf document was named in French. The plugin was entirely written in English.

![Untitled-1](https://user-images.githubusercontent.com/39494222/101272503-2ffda300-378d-11eb-9e17-970bfdd2aca0.png)

2020-12-06 10:57 UTC, Bas950 requested changes
Fix codacy errors

2020-12-06 21:58 UTC, Bas950 requested changes

2020-12-06 21:58 UTC, Bas950 commented on websites/O/Overleaf/dist/metadata.json
> +    "logo": "https://i.imgur.com/OjYpU5R.png",
would probs be nicer to get a transparent background version

2020-12-12 19:09 UTC, ririxidev commented
No response from author.

2020-12-12 19:09 UTC, closed without merging