Updated because codare.fun site is updated.
PreMiD/Presences pull request #2576
Opened 2020-12-06 11:14 UTC by baybeku

i updated this presence because https://codare.fun is updated.

![6Lfu27Q](https://user-images.githubusercontent.com/40503804/101278582-40ce0900-37cd-11eb-8940-f1e95f3d5552.png)

2020-12-06 21:56 UTC, Bas950 requested changes
Fix codacy errors

2020-12-06 22:05 UTC, Bas950 requested changes

2020-12-06 22:05 UTC, Bas950 commented on websites/C/CodAre/presence.ts
> +      if (searchCategory)
why not just use else?

2020-12-06 22:05 UTC, Bas950 commented on websites/C/CodAre/presence.ts
> +    if (window.location.pathname.toLowerCase() === "/kategori/js") {
ever heard of `else if`?

2020-12-06 22:25 UTC, Bas950 approved these changes

2020-12-07 18:28 UTC, ririxidev approved these changes
Merry Christmas 🎉 and GJ

2020-12-07 18:29 UTC, merged