NPM Package Registry: Added support for scoped packages
PreMiD/Presences pull request #2578
Opened 2020-12-06 17:24 UTC by BlyatManGopnik

- Added scoped package support
![image](https://user-images.githubusercontent.com/50471185/101287375-cb4e4280-37a4-11eb-8117-1d5910dc31ea.png)

2020-12-06 21:52 UTC, Bas950 requested changes
bump version in metadata

2020-12-06 22:08 UTC, BlyatManGopnik commented
Did that

2020-12-06 22:08 UTC, Bas950 requested changes
this is not a big change v1.1.6 is enough

2020-12-06 22:17 UTC, BlyatManGopnik commented
Fixed

2020-12-06 22:17 UTC, Bas950 submitted a review, later dismissed

2020-12-07 18:29 UTC, ririxidev requested changes

2020-12-07 18:29 UTC, ririxidev commented on websites/N/NPM Package Registry/dist/metadata.json
>    "thumbnail": "https://crugg.de/premid/npmbanner.png",
could you move thumbnail to imgur? Thanks

2020-12-07 18:51 UTC, BlyatManGopnik commented
Done

2020-12-07 19:26 UTC, ririxidev commented on websites/N/NPM Package Registry/dist/metadata.json
> +  "thumbnail": "https://i.imgur.com/zHN2g49.png",
could you change it to screenshot of npm site xD bc like reed isnt like promotional banner or something

2020-12-07 20:16 UTC, BlyatManGopnik commented
done

2020-12-07 20:17 UTC, ririxidev approved these changes
Approved! Merry Christmas 🎉

2020-12-07 20:29 UTC, Bas950 approved these changes

2020-12-07 20:30 UTC, merged