Pxls.space presence
PreMiD/Presences pull request #2592
Opened 2020-12-08 21:34 UTC by Morrays

New pxls.space presence.

Tracking canvas pixels and overall pixels placed.

![Discord_8rNZFsxjef](https://user-images.githubusercontent.com/55636996/101543210-3a45ba00-39a4-11eb-99d7-56993167ae62.png)
![chrome_6Galv65Yz5](https://user-images.githubusercontent.com/55636996/101543218-3d40aa80-39a4-11eb-8a7c-eb8efeaf95d9.png)

2020-12-08 23:14 UTC, Bas950 requested changes
Fix sv and codacy errors

2020-12-09 18:33 UTC, Bas950 requested changes

2020-12-09 18:33 UTC, Bas950 commented on websites/P/pxls.space/dist/metadata.json
> +    "version": "1.0.1",
version 1.0.0 on release

2020-12-10 00:20 UTC, Bas950 approved these changes

2020-12-10 14:32 UTC, ririxidev approved these changes

2020-12-10 14:32 UTC, merged