Added some updates for codare.fun
PreMiD/Presences pull request #2593
Opened 2020-12-08 23:13 UTC by baybeku

2020-12-08 23:14 UTC, Bas950 requested changes
upload proof of working

2020-12-08 23:24 UTC, baybeku commented
> upload proof of working

![image](https://user-images.githubusercontent.com/40503804/101553437-abe23000-39c5-11eb-8087-b09328cfee52.png)

2020-12-08 23:25 UTC, Bas950 approved these changes
upload proof of working

2020-12-09 06:17 UTC, ririxidev approved these changes

2020-12-09 06:17 UTC, merged