add binarysearch presence
PreMiD/Presences pull request #2596
Opened 2020-12-10 03:44 UTC by sylvesteryue

[binarysearch](binarysearch.com) is a website where people practice coding questions for technical interviews and also race with your friends to solve problems

![binarysearch_presence_screenshot1](https://user-images.githubusercontent.com/56140648/101718671-8e10db80-3a56-11eb-9e49-ceb1b1e39d77.png)
![binarysearch_presence_screenshot2](https://user-images.githubusercontent.com/56140648/101718675-8f420880-3a56-11eb-809e-0347b6f5776d.png)
![binarysearch_presence_screenshot3](https://user-images.githubusercontent.com/56140648/101718681-92d58f80-3a56-11eb-887e-d5fe00fca743.png)
![image](https://user-images.githubusercontent.com/56140648/101718763-bc8eb680-3a56-11eb-8790-8d988daf14a5.png)
![image](https://user-images.githubusercontent.com/56140648/101718803-d203e080-3a56-11eb-96db-ef89fec2ac42.png)

2020-12-10 14:30 UTC, Bas950 requested changes

2020-12-10 14:30 UTC, Bas950 commented on websites/B/binarysearch/presence.ts
> +  };
remove unneeded comments

2020-12-12 19:08 UTC, ririxidev approved these changes

2020-12-12 19:09 UTC, Bas950 approved these changes

2020-12-12 19:10 UTC, merged