Add NativShark Presence
PreMiD/Presences pull request #2601
Opened 2020-12-11 22:21 UTC by moka491

[https://www.nativshark.com/](www.nativshark.com/) is a paid language learning platform for learning Japanese.
This presence allows you to share what you're currently reading, learning or practicing on the site.

![image](https://user-images.githubusercontent.com/31903525/101959963-a9bae400-3c06-11eb-98c6-cff32f3d945b.png)
![image](https://user-images.githubusercontent.com/31903525/101959979-b2abb580-3c06-11eb-885a-635d83b19da4.png)
![image](https://user-images.githubusercontent.com/31903525/101960370-8f353a80-3c07-11eb-8f5a-37bcd477dee2.png)
![image](https://user-images.githubusercontent.com/31903525/101960283-66ad4080-3c07-11eb-9066-37c0ed19f901.png)

2020-12-12 13:31 UTC, Bas950 requested changes

2020-12-12 13:31 UTC, Bas950 commented on websites/N/NativShark/dist/metadata.json
> +  "logo": "https://www.nativshark.com/static/icons/icon-512x512.png",
Upload to imgur

2020-12-12 13:31 UTC, Bas950 commented on websites/N/NativShark/dist/metadata.json
> +  "version": "1.0.2",
1.0.0

2020-12-12 22:28 UTC, Bas950 approved these changes

2020-12-13 11:57 UTC, ririxidev approved these changes

2020-12-13 11:58 UTC, merged