VK Rebranding
PreMiD/Presences pull request #2619
Opened 2020-12-14 06:36 UTC by MrZillaGold

VK recently rebranded. The logo and color for this PR was taken from the official brand book: https://vk.com/brand

2020-12-14 12:49 UTC, ririxidev requested changes

2020-12-14 12:49 UTC, ririxidev commented on websites/V/VK/dist/metadata.json
> +      "id": "342146975065702400"
You can't add ourself as author/contributor since you didn't do anything. (Owner is only one)

2020-12-14 14:20 UTC, Bas950 requested changes
bump version

2020-12-14 14:38 UTC, ririxidev requested changes

2020-12-14 14:38 UTC, ririxidev commented on websites/V/VK/dist/metadata.json
> +  "version": "2.3.0",
2.2.10

2020-12-14 15:35 UTC, Bas950 approved these changes

2020-12-15 08:53 UTC, ririxidev approved these changes

2020-12-15 08:54 UTC, merged