added fastani.net
PreMiD/Presences pull request #2622
Opened 2020-12-14 16:54 UTC by Blatzar

based on twist.moe source code

2020-12-14 17:07 UTC, Blatzar commented
Will hopefully fix Codacy Static Code Analysis tomorrow

2020-12-16 13:47 UTC, Blatzar commented
![image](https://user-images.githubusercontent.com/46196380/102356364-674e2a00-3fad-11eb-996b-e8c2a2657781.png)
Example image of fastani status. 

This PR is ready for review.

2020-12-16 18:23 UTC, ririxidev requested changes

2020-12-16 18:23 UTC, ririxidev commented on websites/F/fastani.net/presence.ts
> + */
remove these comments

2020-12-16 22:14 UTC, Blatzar commented on websites/F/fastani.net/presence.ts
> + */
fixed :)

2020-12-18 07:58 UTC, ririxidev submitted a review, later dismissed

2020-12-18 11:09 UTC, Bas950 requested changes
Support other parts of the website too and not only/watch

2020-12-18 11:09 UTC, Bas950 commented on websites/F/fastani.net/presence.ts
> +  playback = document.querySelector("div.plyr__video-wrapper > video") !== null ? true : false;
Pretty sure that if statement is not needed.

2020-12-18 11:09 UTC, Bas950 commented on websites/F/fastani.net/presence.ts
> +    delete presenceData.smallImageKey;
Don't delete if it ain't set yet

2020-12-18 15:21 UTC, Blatzar commented
> Support other parts of the website too and not only/watch

I added support for viewing an anime title (looking at episodes and such). I don't really see more exciting presences you can add, there's only home and anime list screens, both with pretty much same content. Example of looking at attack on titan, e.g this screen:
![image](https://user-images.githubusercontent.com/46196380/102630535-f5144b80-414c-11eb-8ccb-4d243fe8511e.png)
![image](https://user-images.githubusercontent.com/46196380/102630602-0b220c00-414d-11eb-8c50-f7825ba7d852.png)

2020-12-20 15:39 UTC, Bas950 approved these changes

2020-12-21 15:30 UTC, ririxidev approved these changes

2020-12-21 15:46 UTC, merged