ln.hako.re website
PreMiD/Presences pull request #2625
Opened 2020-12-15 08:46 UTC by Kinue72

![lz2jsq4p](https://user-images.githubusercontent.com/40353755/102191928-a9fbfd80-3eec-11eb-9b5c-5b9986f0aefa.png)
![w0y2vn4r](https://user-images.githubusercontent.com/40353755/102191936-ac5e5780-3eec-11eb-9a5c-a51abc8c541e.png)
![7wtul3xa](https://user-images.githubusercontent.com/40353755/102191939-acf6ee00-3eec-11eb-83c1-d410280ff789.png)

2020-12-15 19:50 UTC, ririxidev requested changes

2020-12-15 19:50 UTC, ririxidev commented on websites/H/Hako/dist/metadata.json
> +    "en": "Reading vietnamese translated light/web novels."
if you support vietnamese in presence add vietnamese desc too. Also you should do it as description not like you're doing this thing. Doesn't this site have some description or whatever? If not change it to ``Read vietnamese translated light/web novels online.``

2020-12-16 18:18 UTC, ririxidev requested changes
proof of working presence Yoakemoe

2020-12-17 04:49 UTC, Kinue72 commented
![3i8rlm92](https://user-images.githubusercontent.com/40353755/102445348-e307af80-405d-11eb-9dd2-39e268a5f945.png)

2020-12-18 07:56 UTC, ririxidev approved these changes

2020-12-18 11:04 UTC, Bas950 approved these changes

2020-12-18 11:04 UTC, merged