gog.com | website presence
PreMiD/Presences pull request #2636
Opened 2020-12-16 13:35 UTC by Dom-in

![image](https://user-images.githubusercontent.com/55330408/102355188-6d3f0d80-3fa3-11eb-8980-1076e7e6f437.png)
![image](https://user-images.githubusercontent.com/55330408/102355239-8051dd80-3fa3-11eb-89ef-52d75e44b3c9.png)
![image](https://user-images.githubusercontent.com/55330408/102355263-88aa1880-3fa3-11eb-98f4-f3f84e31a561.png)

2020-12-16 18:16 UTC, ririxidev requested changes
and show proof of working settings in presence too :)

2020-12-16 18:16 UTC, ririxidev commented on websites/G/gog/presence.ts
> +  const showprofile = await presence.getSetting("profiles");
merge consts

2020-12-16 18:16 UTC, ririxidev commented on websites/G/gog/presence.ts
> +const browsingStamp = Math.floor(Date.now() / 1000);
merge consts

2020-12-16 18:16 UTC, ririxidev commented on websites/G/gog/dist/metadata.json
> +  "version": "1.0.1",
1.0.0

2020-12-18 07:56 UTC, ririxidev requested changes

2020-12-18 07:56 UTC, ririxidev commented on websites/G/gog/presence.ts
> +  const showmoney = await presence.getSetting("money"),
still not merged

2020-12-18 07:56 UTC, ririxidev commented on websites/G/gog/dist/metadata.json
> +  "color": "#FFFFFF",
give it better color

2020-12-18 09:28 UTC, ririxidev requested changes

2020-12-18 09:28 UTC, ririxidev commented on websites/G/gog/dist/metadata.json
> +  "color": "#0000ff",
once again, why blue? use this #4c1785

2020-12-20 15:43 UTC, Bas950 requested changes

2020-12-20 15:43 UTC, Bas950 commented on websites/G/gog/presence.ts
> +    presenceData.state = document.querySelector("body > div.universe > div.wrapper.cf > div > article > h1 > b").textContent;
looks like you got some syntax error in your ifs here

2020-12-24 14:48 UTC, Bas950 requested changes
idk what editor you use but you f*ed it all xD

2020-12-24 14:48 UTC, Bas950 commented on websites/G/gog/presence.ts
> +  clientId 788755903838027776
no?

2020-12-24 14:48 UTC, Bas950 commented on websites/G/gog/presence.ts
> -    largeImageKey: "logo"
no?

2020-12-24 14:48 UTC, closed without merging