Fixes for css-changes on site
PreMiD/Presences pull request #2656
Opened 2020-12-20 05:30 UTC by Hopefuls

This fix includes the following sections that were partially to fully nonfunctional due to the recent css-changes on top.gg:

- DSL (top.gg servers)
- DBL (top.gg bots)
- top.gg Staff Sections (including queue etc)

2020-12-20 15:44 UTC, Bas950 requested changes
Upload proof of it working

2020-12-20 15:44 UTC, Bas950 commented on websites/T/top.gg/dist/metadata.json
> +  "version": "1.4.0",
Not a big change, v1.3.8

2020-12-20 15:44 UTC, Bas950 commented on websites/T/top.gg/dist/metadata.json
>      }
Not a big change, dont add yourself as contributor

2020-12-20 16:35 UTC, Hopefuls commented
> Upload proof of it working

Please bear in mind that the staff-section is not viewable by the public and confidential, thus only being able to screenshot the actual presence, not the site. Thanks for your understanding.

Main Pages
Bots: https://i.imgur.com/mkzaTFD.png
Servers: https://i.imgur.com/D53q8pN.png


Bots 

Tag Examples
Music Bots: https://i.imgur.com/KGEFkk7.png
Top Bots: https://i.imgur.com/44oevcE.png

Bot Page Example
https://i.imgur.com/eXurMjE.png 

User Profile
https://i.imgur.com/GPdJ6KQ.png (previously broken)


DSL (top.gg servers)

Tag Examples
Gaming Discord Servers: https://i.imgur.com/105k25Y.png (previously broken)
Top Discord Servers: https://i.imgur.com/B4IBx11.png (previously broken)

Server Page Example
https://i.imgur.com/cDstBx8.png (previously broken)

User's Servers (partially censored due to private servers etc)
https://i.imgur.com/v9J181v.png

Staff Sections (only able to show the Presence, as this section is restricted to staff and confidential)

Main Moderation Section: https://i.imgur.com/vIxdEog.png
Verification Queue: https://i.imgur.com/wxmpYtA.png
Viewing an unapproved Bot: https://i.imgur.com/fCxnUwp.png
Declining a Bot: https://i.imgur.com/s9OwVb0.png (previously broken)

2020-12-20 20:16 UTC, Bas950 approved these changes
Upload proof of it working

2020-12-21 15:33 UTC, ririxidev approved these changes

2020-12-21 15:47 UTC, merged