New presence: Monkeytype.
PreMiD/Presences pull request #2660
Opened 2020-12-21 13:06 UTC by drull1000

I hope you like it.
screenshots:
![about page](https://user-images.githubusercontent.com/55260356/102780028-02f7e580-4374-11eb-8df5-27cf271a77e6.png)
![account page](https://user-images.githubusercontent.com/55260356/102780031-04291280-4374-11eb-94a0-e2dac26ec2e8.png)
![initial page](https://user-images.githubusercontent.com/55260356/102780033-04291280-4374-11eb-8661-52349b75c9d6.png)
![login page](https://user-images.githubusercontent.com/55260356/102780036-04c1a900-4374-11eb-9084-9500fc8499e5.png)
![settings page](https://user-images.githubusercontent.com/55260356/102780037-055a3f80-4374-11eb-8681-aebc540efaa9.png)

2020-12-22 13:23 UTC, Bas950 requested changes

2020-12-22 13:23 UTC, Bas950 commented on websites/M/Monkeytype/dist/metadata.json
> +    },
shorten it please

2020-12-22 13:32 UTC, drull1000 commented on websites/M/Monkeytype/dist/metadata.json
> +    },
Alright

2020-12-22 21:52 UTC, Bas950 approved these changes

2020-12-23 17:20 UTC, ririxidev approved these changes

2020-12-23 17:20 UTC, merged