NativShark v1.0.1: Keep url structure up to date with website
PreMiD/Presences pull request #2661
Opened 2020-12-21 16:31 UTC by moka491

These are some minor changes to reflect the newest URL changes of NativShark, as they're working on their platform.

2020-12-22 13:24 UTC, Bas950 approved these changes

2020-12-23 17:21 UTC, ririxidev requested changes
please upload proof of working presence :)

2020-12-27 19:04 UTC, moka491 commented
![image](https://user-images.githubusercontent.com/31903525/103177585-1d522780-487c-11eb-91ca-65384243b03b.png)
![image](https://user-images.githubusercontent.com/31903525/103177681-d3b60c80-487c-11eb-926d-805378f1906c.png)
![image](https://user-images.githubusercontent.com/31903525/103177870-7e7afa80-487e-11eb-8d2c-2590a113d1ea.png)
![image](https://user-images.githubusercontent.com/31903525/103177873-86d33580-487e-11eb-8d09-a1e3f5cea48c.png)

@ririxidev Those are screenshots of all the changes made :)

2020-12-27 19:08 UTC, ririxidev approved these changes

2020-12-27 19:08 UTC, merged