Added new pages | MyAnimeList.net
PreMiD/Presences pull request #2664
Opened 2020-12-22 00:40 UTC by notkyoyo

Working proves are added below.

**Viewing clubs, invitations, and joined clubs:** 

![image](https://user-images.githubusercontent.com/62479310/102835024-a18b5180-441b-11eb-9eb0-d9e86330e8fc.png)
![image](https://user-images.githubusercontent.com/62479310/102835037-aa7c2300-441b-11eb-961f-7a744bb1144a.png)
![image](https://user-images.githubusercontent.com/62479310/102835047-b1a33100-441b-11eb-94fe-b632fabe40fa.png)
![image](https://user-images.githubusercontent.com/62479310/102835055-b667e500-441b-11eb-84eb-675c786970a9.png)

**Viewing Blogs:** 

![image](https://user-images.githubusercontent.com/62479310/102835113-d8f9fe00-441b-11eb-87de-a6ec3ad3a367.png)

**Viewing News:** 

![image](https://user-images.githubusercontent.com/62479310/102835136-ea430a80-441b-11eb-9dae-e23125ee7cc4.png)

**Viewing featured articles:**

![image](https://user-images.githubusercontent.com/62479310/102835153-f4fd9f80-441b-11eb-9355-46cb3900e929.png)
![image](https://user-images.githubusercontent.com/62479310/102835165-fd55da80-441b-11eb-990c-1d1d661e731b.png)

**Viewing Peoples:**

![image](https://user-images.githubusercontent.com/62479310/102835181-09419c80-441c-11eb-8e05-3586b572bc4f.png)
![image](https://user-images.githubusercontent.com/62479310/102835193-0e9ee700-441c-11eb-8d0e-7787d2d14071.png)

**Viewing Characters:** 
![image](https://user-images.githubusercontent.com/62479310/102835211-1c546c80-441c-11eb-9e1b-6917c21e9fba.png)
![image](https://user-images.githubusercontent.com/62479310/102835223-20808a00-441c-11eb-818a-9ffdd6753f7e.png)

2020-12-22 13:29 UTC, Bas950 requested changes

2020-12-22 13:29 UTC, Bas950 commented on websites/M/MyAnimeList/dist/metadata.json
> +    "thumbnail": "https://crugg.de/premid/malbanner.png",
upload to imgur

2020-12-22 15:09 UTC, notkyoyo commented on websites/M/MyAnimeList/dist/metadata.json
> +    "thumbnail": "https://crugg.de/premid/malbanner.png",
done

2020-12-22 22:07 UTC, Bas950 approved these changes

2020-12-23 17:22 UTC, ririxidev approved these changes

2020-12-23 17:22 UTC, merged