New Rich Presence: Multporn
PreMiD/Presences pull request #2675
Opened 2020-12-23 16:54 UTC by SammCheese

Name: Multporn.net
About: Website for Adult Comics

Working Proof below, although i cant show the Site as its Full of NSFW Content.

![image](https://user-images.githubusercontent.com/52699291/103019110-95e87980-4546-11eb-91b1-0db915c7c96c.png)
![image](https://user-images.githubusercontent.com/52699291/103019152-a993e000-4546-11eb-9af5-8692a1ffb1f8.png)
![image](https://user-images.githubusercontent.com/52699291/103019203-b9abbf80-4546-11eb-9e32-4b05ad4ea4a9.png)
![image](https://user-images.githubusercontent.com/52699291/103019234-c6c8ae80-4546-11eb-9d91-47601cd99041.png)

Ill gladly Fix any Errors, Mistakes and Bugs you encounter!

2020-12-23 17:12 UTC, ririxidev requested changes
and upload new proof of working presence

2020-12-23 17:12 UTC, ririxidev commented on websites/M/Multporn/presence.ts
> +let viewing: unknown;
HTMLElement :)

2020-12-23 17:12 UTC, ririxidev commented on websites/M/Multporn/presence.ts
> +
delete this blank line

2020-12-23 17:12 UTC, ririxidev commented on websites/M/Multporn/presence.ts
> +    presence.setActivity(presenceData); //Update the presence with all the values from the presenceData object
remove these comment lines

2020-12-23 17:12 UTC, ririxidev commented on websites/M/Multporn/dist/metadata.json
> +  "iframe": false
delete them bc u dont need regexp nor even iframeregexp and iframe

2020-12-23 17:12 UTC, ririxidev commented on websites/M/Multporn/dist/metadata.json
> +    "name": "Samm-Cheese#9500",
without tag

2020-12-23 17:42 UTC, SammCheese commented
New proof of working presence
![image](https://user-images.githubusercontent.com/52699291/103023503-63db1580-454e-11eb-9209-a84a63422239.png)
![image](https://user-images.githubusercontent.com/52699291/103023566-7e14f380-454e-11eb-9da5-be9938c22c7b.png)
![image](https://user-images.githubusercontent.com/52699291/103023595-88cf8880-454e-11eb-9f73-e89400987094.png)

2020-12-23 22:46 UTC, Bas950 requested changes

2020-12-23 22:46 UTC, Bas950 commented on websites/M/Multporn/dist/metadata.json
> +  "version": "1.0.3",
1.0.0 on release

2020-12-23 22:54 UTC, SammCheese commented on websites/M/Multporn/dist/metadata.json
> +  "version": "1.0.3",
Version Number set back to 1.0.0

2020-12-24 12:08 UTC, ririxidev approved these changes

2020-12-24 14:47 UTC, Bas950 approved these changes

2020-12-24 14:48 UTC, merged