SuperiorServers.co Presence release
PreMiD/Presences pull request #2692
Opened 2020-12-27 05:23 UTC by nickiscool1022

2020-12-27 13:11 UTC, Bas950 requested changes

2020-12-27 13:11 UTC, Bas950 commented on websites/S/SuperiorServers.co/dist/metadata.json
> +  "version": "1.0",
v 1.0.0

2020-12-27 13:11 UTC, Bas950 commented on websites/S/SuperiorServers.co/dist/metadata.json
> +  "color": "#273341",
thumbnail should be a promotional banner or a screenshot of the website homepage.

2020-12-27 13:11 UTC, Bas950 commented on websites/S/SuperiorServers.co/presence.ts
> +});
remove comment

2020-12-27 13:11 UTC, Bas950 commented on websites/S/SuperiorServers.co/presence.ts
> +var homeURL = new URL(document.location.href);
no var

2020-12-27 13:11 UTC, Bas950 commented on websites/S/SuperiorServers.co/presence.ts
> +      var totalStaff = (parseInt(DRPStaff) + parseInt(SWRPStaff) + parseInt(MilRPStaff) + parseInt(AllServersStaff)).toString();
no var

2020-12-27 13:11 UTC, Bas950 commented on websites/S/SuperiorServers.co/presence.ts
> +      var lastPage = document.querySelector("#bans_paginate > ul > li:nth-child(8) > a");
no var

2020-12-27 16:33 UTC, Bas950 approved these changes

2020-12-27 16:34 UTC, Bas950 requested changes

2020-12-27 16:34 UTC, Bas950 commented on websites/S/SuperiorServers.co/dist/metadata.json
> +  },
whoops this is wrong actually, this should be a description of the website, not the presence

2020-12-28 01:17 UTC, Bas950 approved these changes

2020-12-28 18:56 UTC, ririxidev requested changes

2020-12-28 18:56 UTC, ririxidev commented on websites/S/SuperiorServers.co/dist/metadata.json
> +  "logo": "https://i.imgur.com/TmuYDD4.png",
this is 500x500, couldn't it be 512x512?

2020-12-28 18:56 UTC, ririxidev commented on websites/S/SuperiorServers.co/dist/metadata.json
> +  "thumbnail": "https://i.imgur.com/3lLFBZ7.png",
next time blur your nick or something 🤔

2020-12-28 18:56 UTC, ririxidev commented on websites/S/SuperiorServers.co/presence.ts
> +      AllServersStaff = AllServersStaff.substr((AllServersStaff.indexOf(" of") + 3), AllServersStaff.indexOf(" entries")).replace(" entries", "");
please change it to const and do substr after textContent because you can do it obviously

2020-12-28 18:56 UTC, ririxidev commented on websites/S/SuperiorServers.co/presence.ts
> +      presenceData.details = "Viewing " + numBans + " bans";
please change it to const and do substr after textContent because you can do it obviously

2020-12-28 18:56 UTC, ririxidev commented on websites/S/SuperiorServers.co/presence.ts
> +        GMs = GMs.substr((GMs.indexOf(" of") + 3), GMs.indexOf(" entries")).replace(" entries", "");
please change it to const and do substr after textContent because you can do it obviously

2020-12-28 18:56 UTC, ririxidev commented on websites/S/SuperiorServers.co/presence.ts
> +        GMs = GMs.substr((GMs.indexOf(" of") + 3), GMs.indexOf(" entries")).replace(" entries", "");
please change it to const and do substr after textContent because you can do it obviously

2020-12-28 23:31 UTC, nickiscool1022 commented on websites/S/SuperiorServers.co/dist/metadata.json
> +  "thumbnail": "https://i.imgur.com/3lLFBZ7.png",
Would you like me to?

2020-12-29 13:13 UTC, Bas950 approved these changes

2020-12-29 15:47 UTC, ririxidev approved these changes

2020-12-29 15:47 UTC, merged