add brubsby.com presence
PreMiD/Presences pull request #2726
Opened 2020-12-30 17:30 UTC by brubsby

I have a personal website that hosts a random media player related to discord servers that I'm in, so I'd like to add this presence that tells people what media the user is viewing (and that my website is being used).

thanks,
brubsby

2020-12-31 00:07 UTC, Bas950 requested changes
Upload proof of it working

2020-12-31 00:07 UTC, Bas950 commented on websites/B/brubsby/dist/metadata.json
> +  "thumbnail": "https://brubsby.com/assets/favicon.png",
upload to imgur

2020-12-31 00:07 UTC, Bas950 commented on websites/B/brubsby/dist/metadata.json
> +  },
English is not a description

2020-12-31 00:07 UTC, Bas950 commented on websites/B/brubsby/dist/metadata.json
> +  "version": "1.0.0",
service name and folder name must be the same

2020-12-31 00:07 UTC, Bas950 commented on websites/B/brubsby/presence.ts
> +    presence.setActivity(presenceData); //Update the presence with all the values from the presenceData object
remove comments

2020-12-31 04:05 UTC, brubsby commented
> Upload proof of it working

![image](https://user-images.githubusercontent.com/57653502/103393941-24cb3800-4aeb-11eb-88a7-a5d28aaf2f1c.png)

2020-12-31 15:27 UTC, Bas950 requested changes

2020-12-31 15:27 UTC, Bas950 commented on websites/B/brubsby.com/dist/metadata.json
> +  "logo": "https://imgur.com/Miem17T.png",
thats not really a logo....

2020-12-31 15:27 UTC, Bas950 commented on websites/B/brubsby.com/dist/metadata.json
>    "color": "#FFFFFF",
thumbnail most be a promotional banner or a screenshot of the website homepage.

2021-01-03 19:47 UTC, ririxidev commented
no response from author - closing.

2021-01-03 19:47 UTC, closed without merging