SImulator FM Update
PreMiD/Presences pull request #2732
Opened 2020-12-31 20:19 UTC by DubStepMad

This updates the Simulator FM presence as I have re-designed the Simulator FM website which resolved in changes to the selectors.

2020-12-31 22:24 UTC, Bas950 requested changes
Upload proof of it working and fix codacy errors

2021-01-01 01:21 UTC, DubStepMad commented
@Bas950 Not sure on the errors with Codacy as  there isn't much info I can see but here is the proof the update is working.

![image](https://user-images.githubusercontent.com/13799856/103431897-7fd65b00-4bcf-11eb-9114-38ee6c8ade4f.png)
![image](https://user-images.githubusercontent.com/13799856/103431901-a399a100-4bcf-11eb-8ba5-50439df6822c.png)
![image](https://user-images.githubusercontent.com/13799856/103431902-a72d2800-4bcf-11eb-8f1f-27e6b7c333ed.png)
![image](https://user-images.githubusercontent.com/13799856/103431903-a8f6eb80-4bcf-11eb-82d8-da2301f007ec.png)
![image](https://user-images.githubusercontent.com/13799856/103431904-ab594580-4bcf-11eb-9014-e8c5027ca5c6.png)
![image](https://user-images.githubusercontent.com/13799856/103431907-aeeccc80-4bcf-11eb-8584-89d648abb502.png)

2021-01-01 01:25 UTC, Bas950 approved these changes

2021-01-01 19:57 UTC, ririxidev approved these changes

2021-01-01 20:01 UTC, merged