Add astral.cool presence
PreMiD/Presences pull request #2739
Opened 2021-01-03 02:17 UTC by aspectiscool

![image](https://user-images.githubusercontent.com/43763882/103470385-c945b800-4d3f-11eb-9051-e41bcba11bda.png)
![image](https://user-images.githubusercontent.com/43763882/103470398-d9f62e00-4d3f-11eb-8a77-f1d1fe027f3d.png)

2021-01-03 19:51 UTC, ririxidev requested changes

2021-01-03 19:51 UTC, ririxidev commented on websites/A/Astral/presence.ts
> +  }
don't use switch(true) pls, if path will change it will detect it...

2021-01-03 20:50 UTC, Bas950 requested changes

2021-01-03 20:50 UTC, Bas950 commented on websites/A/Astral/presence.ts
> +    presenceData.details = "";
dont set empty details

2021-01-04 03:20 UTC, Bas950 requested changes

2021-01-04 03:20 UTC, Bas950 commented on websites/A/Astral/presence.ts
>         presenceData.state = "Editing their embed";
instead of only setting state, only set the details.
*some on all those other edits*

2021-01-06 15:01 UTC, ririxidev commented
no response from pull requeqst creator. closing 🤷

2021-01-06 15:01 UTC, closed without merging