Adding Brick Hill
PreMiD/Presences pull request #2779
Opened 2021-01-10 20:34 UTC by dragonismcode

2021-01-10 22:44 UTC, Bas950 requested changes
fix codacy issues

2021-01-11 03:27 UTC, Bas950 requested changes
Fix codacy errors

2021-01-11 04:49 UTC, dragonismcode commented
I cannot seem to find a fix to these errors. If you can help me, that would be greatly appreciated.

2021-01-11 08:07 UTC, Bas950 requested changes

2021-01-11 08:07 UTC, Bas950 commented on websites/B/Brick Hill/presence.ts
> +const browsingStamp = Math.floor(Date.now() / 1000);
merge consts

```
const a = "b",
  b = "c";
```

2021-01-11 08:07 UTC, Bas950 commented on websites/B/Brick Hill/presence.ts
> +var title: any;
Dont use var, dont use any

2021-01-11 21:39 UTC, Bas950 approved these changes

2021-01-11 21:50 UTC, ririxidev approved these changes

2021-01-11 21:51 UTC, merged