Fixed freeCodeCamp
PreMiD/Presences pull request #2792
Opened 2021-01-12 17:59 UTC by RedS-DEV

Changed the client id.
Presence will be maintained by me, made myself author in the metadata. (ririxi said I can do it)
Proof it works: https://reds-dev.is-inside.me/TodUZkP8.png

2021-01-13 02:43 UTC, Bas950 requested changes

2021-01-13 02:43 UTC, Bas950 commented on websites/F/FreeCodeCamp/dist/metadata.json
> +  "service": "freeCodeCamp",
update folder name too.

2021-01-13 05:49 UTC, RedS-DEV commented on websites/F/FreeCodeCamp/dist/metadata.json
> +  "service": "freeCodeCamp",
k

2021-01-13 12:00 UTC, ririxidev approved these changes

2021-01-13 13:08 UTC, Bas950 requested changes

2021-01-13 13:08 UTC, Bas950 commented on websites/F/freeCodeCamp/dist/metadata.json
> +  "version": "1.1.1",
1.1.0

2021-01-13 13:24 UTC, RedS-DEV commented on websites/F/freeCodeCamp/dist/metadata.json
> +  "version": "1.1.1",
k

2021-01-14 02:55 UTC, Bas950 approved these changes

2021-01-16 13:14 UTC, ririxidev approved these changes

2021-01-16 13:15 UTC, merged