Updating Brick Hill
PreMiD/Presences pull request #2793
Opened 2021-01-12 23:22 UTC by dragonismcode

Make it so that it displays what they are looking at in the catalog

Proof of working:
![image](https://user-images.githubusercontent.com/76412158/104386398-b9c22e00-54fa-11eb-99ee-159241f02308.png)

2021-01-13 02:43 UTC, Bas950 requested changes
Bump version

2021-01-14 02:57 UTC, Bas950 approved these changes

2021-01-16 13:15 UTC, ririxidev approved these changes

2021-01-16 13:58 UTC, Bas950 requested changes
Update your fork (Fix merge conflicts)

2021-01-21 19:51 UTC, ririxidev commented
no response

2021-01-21 19:51 UTC, closed without merging