Add Keyma.sh
PreMiD/Presences pull request #2798
Opened 2021-01-13 20:42 UTC by CameronCT

2021-01-14 02:57 UTC, Bas950 requested changes
Upload proof of it working

2021-01-14 02:57 UTC, Bas950 commented on websites/K/Keymash/dist/metadata.json
> +  "service": "KEYMA.SH",
Service name and folder name must be the same

2021-01-14 02:57 UTC, Bas950 commented on websites/K/Keymash/dist/metadata.json
> +  "logo": "https://i.imgur.com/vDGvohb.png",
Version 1.0.0

2021-01-18 10:26 UTC, ririxidev commented
no response.

2021-01-18 10:26 UTC, closed without merging