Added Human Benchmark
PreMiD/Presences pull request #2809
Opened 2021-01-15 20:14 UTC by StrikerFRFX

**Proof of working:** (these are a few miscellaneous screenshots of what shows on what tests etc)

![](https://i.imgur.com/ttVH3Hh.png)
![](https://i.imgur.com/5uHJhyg.png)
![](https://i.imgur.com/fjvubL8.png)
![](https://i.imgur.com/xHpUhKj.png)
![](https://i.imgur.com/kOTAK8f.png)
![](https://i.imgur.com/ALKe0ZO.png)
![](https://i.imgur.com/OScBplU.png)

2021-01-15 20:16 UTC, StrikerFRFX commented
Only included a few test screenshots as there are way too many possible combinations of what the 2 status fields could be. If more screenshots are required or specific ones, please ask :)

2021-01-16 00:19 UTC, Bas950 requested changes

2021-01-16 00:19 UTC, Bas950 commented on websites/H/Human Benchmark/presence.ts
> +numbers = "4";
just set these in the let above

2021-01-16 00:19 UTC, Bas950 commented on websites/H/Human Benchmark/dist/metadata.json
> +    "logo": "https://i.imgur.com/biMzNKF.png",
logo must be atleast 512x512

2021-01-16 13:28 UTC, ririxidev approved these changes

2021-01-16 13:57 UTC, Bas950 approved these changes

2021-01-16 13:58 UTC, merged