grailed update
PreMiD/Presences pull request #2814
Opened 2021-01-17 09:10 UTC by kznvii

new browsing section layout

2021-01-17 20:19 UTC, Bas950 requested changes
upload proof of it working

2021-01-17 23:08 UTC, kznvii commented
![proof 1](https://user-images.githubusercontent.com/75966600/104858686-e2b93900-58d5-11eb-9f79-929a4961bdd8.JPG)
![proof 2](https://user-images.githubusercontent.com/75966600/104858687-e51b9300-58d5-11eb-8b3e-fd6a2fbe9ecf.JPG)
![proof 3](https://user-images.githubusercontent.com/75966600/104858690-e77ded00-58d5-11eb-8a62-6a2fccf43c7b.JPG)

2021-01-17 23:09 UTC, kznvii commented
everything else on the website that i checked stayed the same

2021-01-18 10:22 UTC, ririxidev approved these changes

2021-01-19 01:07 UTC, Bas950 approved these changes
upload proof of it working

2021-01-19 01:07 UTC, merged