Fix: Google Translate Presence
PreMiD/Presences pull request #2817
Opened 2021-01-17 21:28 UTC by StrikerFRFX

**Proof of Working**:
![Discord_0L5CkSkx6x](https://user-images.githubusercontent.com/34070194/104855200-49a11700-5903-11eb-9aa1-319d77b480fe.png)
![Discord_4oaMyrrSdL](https://user-images.githubusercontent.com/34070194/104855203-4c9c0780-5903-11eb-80e8-f02743742aca.png)
The above is **working** (with the setting "Show translation type" toggled in the settings).

**and Previously Broken Screenshot**:
![Discord_TBjvZdxAet](https://user-images.githubusercontent.com/34070194/104855256-971d8400-5903-11eb-88dc-3329e5a74fa7.png)
The above is **broken** (NOTE: this shows when the webpage is just a "translate.google.com/" URL meaning no languages have been selected yet. It does not mean the presence is broken if this is displayed. In the broken version, this shows even with a language selected for translation (source and destination) ). "Show translation type" is not toggled in the settings in this screenshot.

However:
The same would show on the below screenshot, which is with the setting "Show translation type" toggled in the settings. The difference is this one updates upon typing in the appropriate translation fields. This one is an example of the **working** one, with just the "translate.google.com/" (no translation searches)
![Discord_rVDXWr6S6G](https://user-images.githubusercontent.com/34070194/104856325-fbdbdd00-5909-11eb-9406-119bde7d5da2.png)

NOTE:
The miscellaneous commits on this PR (such as 12c2929) mean that this PR MUST be merged before #2807 else breaking changes (TLDR; I had to remove all commits of Yandex.Translate in order to open this PR otherwise there would be breaking changes (2 presences in one PR) )

Resolves #2806

2021-01-18 10:20 UTC, ririxidev approved these changes

2021-01-19 01:07 UTC, Bas950 requested changes

2021-01-19 01:07 UTC, Bas950 commented on websites/G/Google Translate/dist/metadata.json
> +    {
remove that space

2021-01-19 02:02 UTC, StrikerFRFX commented on websites/G/Google Translate/dist/metadata.json
> +    {
sure can do

2021-01-19 12:45 UTC, ririxidev approved these changes

2021-01-19 14:18 UTC, Bas950 approved these changes

2021-01-19 14:19 UTC, merged