Added AniTube Presence
PreMiD/Presences pull request #2829
Opened 2021-01-18 14:25 UTC by Yuujet

![image](https://user-images.githubusercontent.com/42509424/104927035-52333500-5977-11eb-9706-76e7bb3ca175.png)

2021-01-19 12:43 UTC, ririxidev requested changes

2021-01-19 12:43 UTC, ririxidev commented on AniTube/dist/metadata.json
> +  "version": "1.0",
1.0.0

2021-01-19 12:43 UTC, ririxidev commented on AniTube/dist/metadata.json
> +  "logo": "https://i.imgur.com/RkIE0qc.png",
min. 512x512

2021-01-19 12:43 UTC, ririxidev commented on AniTube/dist/presence.js
> +}); });
delete this file

2021-01-19 12:43 UTC, ririxidev commented on AniTube/presence.ts
> +}
you should delete this function and use presence.getTimestamps

2021-01-19 12:43 UTC, ririxidev commented on AniTube/presence.ts
> +var presence = new Presence({
no vars, change to const

2021-01-19 12:43 UTC, ririxidev commented on AniTube/presence.ts
> +var browsingStamp = Math.floor(Date.now() / 1000);
no vars, change to const/let and merge them

2021-01-19 12:43 UTC, ririxidev commented on AniTube/presence.ts
> +  const tempo = Math.floor(Date.now() / 1000),
merge consts

2021-01-19 12:43 UTC, ririxidev commented on AniTube/presence.ts
> +    var timestamps = getTimestamps(
no vars

2021-01-19 12:43 UTC, ririxidev commented
ah, and this folder should be in ``websites`` folder not in root folder :P

2021-01-19 14:17 UTC, Bas950 requested changes
Fix sv and codacy issues

2021-01-22 12:34 UTC, ririxidev commented
one pr or nothing. decide

2021-01-22 12:34 UTC, closed without merging