Added pays.host presence
PreMiD/Presences pull request #2836
Opened 2021-01-19 14:52 UTC by hiitsdan

![image](https://user-images.githubusercontent.com/37845774/105050514-c0eebc00-5a65-11eb-984f-ae349c2b5ff4.png)
![image](https://user-images.githubusercontent.com/37845774/105050605-de238a80-5a65-11eb-9020-bb05ea3db72e.png)
![image](https://user-images.githubusercontent.com/37845774/105050691-f4c9e180-5a65-11eb-9af9-6c345fe98031.png)

2021-01-19 15:20 UTC, Bas950 requested changes

2021-01-19 15:20 UTC, Bas950 commented on websites/P/pays.host/dist/metadata.json
> +	"readLogs": false
You dont need to set these, they are false by default.

2021-01-19 15:23 UTC, Bas950 requested changes

2021-01-19 15:23 UTC, Bas950 commented on websites/P/pays.host/presence.ts
> +    }
make a privacy setting for this or hide it.

2021-01-20 10:05 UTC, ririxidev requested changes

2021-01-20 10:05 UTC, ririxidev commented on websites/P/pays.host/presence.ts
> +        presenceData.state = "";
don't set "", do ``delete presenceData.state``

2021-01-20 10:05 UTC, ririxidev commented on websites/P/pays.host/presence.ts
> +        presenceData.state = "";
``delete presenceData.state``

2021-01-20 16:24 UTC, Bas950 approved these changes

2021-01-22 12:34 UTC, ririxidev approved these changes

2021-01-22 12:34 UTC, merged