Add KaraokeType
PreMiD/Presences pull request #2844
Opened 2021-01-21 12:43 UTC by memetrollsXD

Add a website

2021-01-21 20:47 UTC, Bas950 requested changes

2021-01-21 20:47 UTC, Bas950 commented on websites/K/KaraokeType/metadata.json
> +  "thumbnail": "https://memetrolls.net/etc/KaraokeType/karaoketype.png",
upload to imgur

2021-01-21 20:47 UTC, Bas950 commented on websites/K/KaraokeType/presence.ts
> +let presenceData: PresenceData = {
merge the consts and lets

2021-01-22 12:37 UTC, ririxidev commented
![image](https://user-images.githubusercontent.com/9348108/105491631-e4f50c00-5cb6-11eb-816d-e7f7c376cc6c.png)
huh it isn't even website that you I think wanted to do lol

2021-01-22 12:37 UTC, closed without merging

2021-01-22 12:49 UTC, memetrollsXD commented
It's supposed to be https://memetrolls.net/etc/KaraokeType, not just "memetrolls.net"

2021-01-22 13:11 UTC, ririxidev commented
Ehhh, but yeah. still. This domain is for minecraft server and is not even related to it. So I'm saying no to it and big sorry.