Added gunivers.net network and kanishiel.com
PreMiD/Presences pull request #2846
Opened 2021-01-21 17:28 UTC by fantomitechno

I love PreMiD so I tried to implemented the organisation's web site, I'm in.

2021-01-21 20:48 UTC, Bas950 requested changes
Same issues in the other presence

2021-01-21 20:48 UTC, Bas950 commented on websites/G/Gunivers/dist/metadata.json
> +    "thumbnail": "https://cdn.discordapp.com/emojis/801804688302276628.png?v=1",
upload to imgur

2021-01-21 20:48 UTC, Bas950 commented on websites/G/Gunivers/dist/metadata.json
> +      "id": "563749920683720709"
remove your tag (#8888)

2021-01-21 20:48 UTC, Bas950 commented on websites/G/Gunivers/dist/metadata.json
> +    "$schema": "https://schemas.premid.app/metadata/1.0",
Use the latest schema

2021-01-22 06:06 UTC, fantomitechno commented
I will modify this as faster I can

2021-01-22 06:49 UTC, fantomitechno commented
Fixed

2021-01-22 12:39 UTC, ririxidev requested changes
yikes

2021-01-22 12:39 UTC, ririxidev commented on websites/G/Gunivers/dist/metadata.json
> +    "logo": "https://i.imgur.com/pjuZo1A.png",
logo must be 512x512 or more

2021-01-22 12:39 UTC, ririxidev commented on websites/G/Gunivers/dist/metadata.json
> +    "thumbnail": "https://i.imgur.com/sNN579z.png",
it should be promotional banner or screenshot of website

2021-01-22 14:42 UTC, fantomitechno commented
I will update this in 2 hors (I cant before)

2021-01-22 16:26 UTC, fantomitechno commented
Modified

2021-01-23 14:47 UTC, fantomitechno commented
I find some way to improve the gunivers.net presence, I used the link to have the articles or chronicles names but I learned a way to read the page

2021-01-24 02:50 UTC, Bas950 requested changes
Upload proof of it working

2021-01-24 12:57 UTC, fantomitechno commented
Gunivers : 
![image](https://user-images.githubusercontent.com/67735304/105630816-75fcec00-5e4b-11eb-89ff-d9e3272a48c0.png)

![image](https://user-images.githubusercontent.com/67735304/105630786-5f569500-5e4b-11eb-91b3-7470943a46db.png)

![image](https://user-images.githubusercontent.com/67735304/105630833-88772580-5e4b-11eb-866e-6918fdcdd576.png)

KaniShiel : 

![image](https://user-images.githubusercontent.com/67735304/105630863-b3fa1000-5e4b-11eb-83a6-dde08d274a8d.png)

![image](https://user-images.githubusercontent.com/67735304/105630903-e73c9f00-5e4b-11eb-8f0e-7cb4cfe1264e.png)

![image](https://user-images.githubusercontent.com/67735304/105630927-04716d80-5e4c-11eb-8e56-abb23644ecf3.png)

2021-01-24 18:25 UTC, Bas950 reviewed
Upload proof of it working

2021-01-24 18:25 UTC, Bas950 commented on websites/K/KaniShiel/dist/metadata.json
> +    "logo": "https://i.imgur.com/e9IeASG.png",
logo must at least be 512x512

2021-01-24 18:43 UTC, fantomitechno commented
Done

You need more proof of it working or these aren't good ?

2021-01-25 13:44 UTC, Bas950 commented
> Done
> 
> You need more proof of it working or these aren't good ?

No sorry forgot to delete the old text

2021-01-25 13:45 UTC, Bas950 approved these changes

2021-01-26 07:35 UTC, ririxidev approved these changes

2021-01-26 07:35 UTC, merged