Added Salty Bet (www.saltybet.com)
PreMiD/Presences pull request #2854
Opened 2021-01-22 21:14 UTC by magumboi

i hope you like it!

2021-01-24 02:51 UTC, Bas950 requested changes

2021-01-24 02:51 UTC, Bas950 commented on websites/S/Salty Bet/dist/metadata.json
> +  },
Make the description shorter

2021-01-24 02:51 UTC, Bas950 commented on websites/S/Salty Bet/dist/metadata.json
> +  "version": "1.1.3",
Version 1.0.0 on release

2021-01-24 02:51 UTC, Bas950 commented on websites/S/Salty Bet/presence.ts
> +}),
remove comment

2021-01-24 04:33 UTC, magumboi commented
done 👌

2021-01-24 18:22 UTC, Bas950 approved these changes

2021-01-26 07:36 UTC, ririxidev approved these changes

2021-01-26 07:37 UTC, merged