New Presence - Online Sequencer (https://onlinesequencer.net/)
PreMiD/Presences pull request #2855
Opened 2021-01-23 06:30 UTC by YJJcoolcool

2021-01-23 11:35 UTC, YJJcoolcool commented
Closed Pull Request due to errors

2021-01-23 11:40 UTC, ririxidev commented
just fix them there?

2021-01-23 12:55 UTC, YJJcoolcool commented
Ok, all issues fixed.

2021-01-24 02:50 UTC, Bas950 requested changes
upload proof of it working

2021-01-24 02:50 UTC, Bas950 commented on websites/O/Online-Sequencer/presence.ts
> +*/
remove comments

2021-01-24 03:05 UTC, YJJcoolcool commented
> upload proof of it working

Do I send like a screenshot or video of it working?

2021-01-24 03:20 UTC, Bas950 commented
> > upload proof of it working
> 
> Do I send like a screenshot or video of it working?

Just screenshot proof of how its shown in Discord.

2021-01-24 03:48 UTC, YJJcoolcool commented
> > > upload proof of it working
> > 
> > 
> > Do I send like a screenshot or video of it working?
> 
> Just screenshot proof of how its shown in Discord.

Hi, I've sent the screenshots to the #presence-dev channel on the PreMiD discord. For your convenience, here's the link to the screenshots: https://imgur.com/a/fGZ9RZe

2021-01-24 18:24 UTC, Bas950 approved these changes
upload proof of it working

2021-01-26 07:37 UTC, ririxidev approved these changes

2021-01-26 07:37 UTC, merged