globoplay: big brother n' stuff
PreMiD/Presences pull request #2874
Opened 2021-01-26 07:54 UTC by fr0r

Big Brother is back for another season!

This means i need to ~~spam the shit out of ``if else``~~ add the 12 new cameras they've added + some random radio station.

<details>

<summary><b>changelog</b> <i>(click to expand)</i></summary>

- Added Big Brother cameras.
- Added local CBN (all-news radio) stations.
- shortened some unnecessary shit

</details>

<details>

<summary><b>screenshots</b> <i>(click to expand)</i></summary>

![image](https://user-images.githubusercontent.com/34042085/105815969-bb90f480-5fc4-11eb-9dbc-22289eb7d3ab.png)

![image](https://user-images.githubusercontent.com/34042085/105815936-addb6f00-5fc4-11eb-8ca2-75133aac360a.png)

</details>

2021-01-26 07:55 UTC, fr0r commented
there we go lol @ririxidev

2021-01-26 08:27 UTC, ririxidev requested changes

2021-01-26 08:27 UTC, ririxidev commented on websites/G/globoplay/dist/metadata.json
> +    "id": "515668127829458945"
bas accepted owner change?

2021-01-26 16:54 UTC, fr0r commented on websites/G/globoplay/dist/metadata.json
> +    "id": "515668127829458945"
yup
![image](https://user-images.githubusercontent.com/34042085/105876698-44814d80-6010-11eb-9edb-c2855d800238.jpeg)

2021-01-26 17:15 UTC, ririxidev approved these changes

2021-01-26 17:23 UTC, Bas950 requested changes
bump version

2021-01-27 17:42 UTC, Bas950 approved these changes
bump version

2021-01-28 14:17 UTC, ririxidev approved these changes

2021-01-28 14:18 UTC, merged