Add Keyma.sh
PreMiD/Presences pull request #2875
Opened 2021-01-26 07:56 UTC by CameronCT

Due to last pull request the version has been changed to 1.0.0 and the service name matches the folder contents and here is the screenshot of viewing a profile page.

[https://i.imgur.com/eqwGRe8.png](url)

2021-01-26 17:22 UTC, Bas950 submitted a review, later dismissed

2021-01-28 14:18 UTC, ririxidev requested changes

2021-01-28 14:18 UTC, ririxidev commented on websites/K/Keymash/presence.ts
> +      details: "Here",
for what reason you set details?

2021-01-28 19:24 UTC, CameronCT commented on websites/K/Keymash/presence.ts
> +      details: "Here",
I pushed a change to resolve that.

2021-01-28 21:04 UTC, ririxidev approved these changes

2021-01-28 22:21 UTC, Bas950 approved these changes

2021-01-28 22:22 UTC, merged