Updated of kanishiel.com and gunivers.net
PreMiD/Presences pull request #2876
Opened 2021-01-26 11:11 UTC by fantomitechno

I know that these have just been accepted but I added a few thing : small images for the precence and privacy option 

**Proof that the changes work :**

*For gunivers :*
I added this little image when you are on the workspace
![image](https://user-images.githubusercontent.com/67735304/105836981-4d512f80-5fce-11eb-95ba-b68133f5c0cf.png)

I also forget to add the presence when your looking for a user on the main website
![image](https://user-images.githubusercontent.com/67735304/105837061-6bb72b00-5fce-11eb-9a1e-a8a63d9d5432.png)

I added a privacy mode that remove all the presence and set your status the same everywhere
![image](https://user-images.githubusercontent.com/67735304/105837144-8d181700-5fce-11eb-9dd6-fef537caedf3.png)

*For kanishiel :* 
I added images for the dashboard 
![image](https://user-images.githubusercontent.com/67735304/105837257-bcc71f00-5fce-11eb-831d-521608379b3e.png)
And for the werewolves roles 
![image](https://user-images.githubusercontent.com/67735304/105837737-69090580-5fcf-11eb-86f6-ad6716481f26.png)

I added two type of privacy : one which hide the server you're editing 
![image](https://user-images.githubusercontent.com/67735304/105837478-09125f00-5fcf-11eb-8be1-76cc41199f42.png)
And an other that remove all the presence and set your status the same everywhere
![image](https://user-images.githubusercontent.com/67735304/105837523-1d565c00-5fcf-11eb-89f9-24ca242f4754.png)

Oh and for gunivers, I have registered the url status.gunivers.net but after I speak about this presence with the website owner, he move it to another website so I removed it.

2021-01-26 17:22 UTC, Bas950 requested changes
bump version

2021-01-26 18:52 UTC, fantomitechno commented
oh i forgot for gunivers

2021-01-27 17:44 UTC, Bas950 approved these changes
bump version

2021-01-28 14:19 UTC, ririxidev approved these changes

2021-01-28 14:20 UTC, merged