Updated Salty Bet presence.ts
PreMiD/Presences pull request #2879
Opened 2021-01-26 19:19 UTC by magumboi

Found an issue when closing and reopening the website, the presence didn't refresh right away so I added a check to keeping it alive.

2021-01-27 17:44 UTC, Bas950 requested changes
upload proof of it working

2021-01-27 18:20 UTC, magumboi commented
![Screenshot_15](https://user-images.githubusercontent.com/27692047/106035659-fe70cc00-6099-11eb-9de8-9224455a5dc1.png)
![Screenshot_14](https://user-images.githubusercontent.com/27692047/106035660-ff096280-6099-11eb-9848-8f33ee5209c9.png)
![Screenshot_16](https://user-images.githubusercontent.com/27692047/106035661-ff096280-6099-11eb-8356-3ea534b97c87.png)

2021-01-28 14:21 UTC, ririxidev approved these changes

2021-01-28 22:10 UTC, Bas950 approved these changes
upload proof of it working

2021-01-28 22:11 UTC, merged