✍ Added kickassanime presence
PreMiD/Presences pull request #2882
Opened 2021-01-27 15:30 UTC by StrikerFRFX

All screenshots are of mapped out pages
I chose not to add the settings page in but I can add it on request
Timestamps work as expected

![guxKvGVs2H](https://user-images.githubusercontent.com/34070194/106013342-4270ca80-60b4-11eb-8ee2-122fd11736d8.png)
![bsDZgpex99](https://user-images.githubusercontent.com/34070194/106013358-47357e80-60b4-11eb-988d-8aa00372148c.png)
![E5IAXb73UF](https://user-images.githubusercontent.com/34070194/106013363-4997d880-60b4-11eb-95e9-887b7ea1fd2e.png)
![RVmD6876Zk](https://user-images.githubusercontent.com/34070194/106013372-4ac90580-60b4-11eb-9e73-250dfd53cfac.png)
![aUYlB18fEr](https://user-images.githubusercontent.com/34070194/106013378-4bfa3280-60b4-11eb-9eae-c6d932dda815.png)
![DskKDzlQNl](https://user-images.githubusercontent.com/34070194/106013384-4d2b5f80-60b4-11eb-98fb-ba3f54d39106.png)
![CyZrIMxBQk](https://user-images.githubusercontent.com/34070194/106013386-4e5c8c80-60b4-11eb-9881-aebc15875c41.png)
![KiDzzFQpx0](https://user-images.githubusercontent.com/34070194/106013389-4f8db980-60b4-11eb-8f3b-5cb787dcfdd8.png)
![9Dze8uxAxH](https://user-images.githubusercontent.com/34070194/106013394-50bee680-60b4-11eb-8357-86997ed6825b.png)
![FU5SaUoGU6](https://user-images.githubusercontent.com/34070194/106013396-51577d00-60b4-11eb-9a17-ef4efe50ee03.png)

Resolves #834

2021-01-27 17:47 UTC, Bas950 requested changes

2021-01-27 17:47 UTC, Bas950 commented on websites/K/Kickassanime/dist/metadata.json
> +    "version": "1.3.6",
version 1.0.0 on release

2021-01-27 17:47 UTC, Bas950 commented on websites/K/Kickassanime/presence.ts
> +  }
use the presence.getTimestamps instead

2021-01-27 17:51 UTC, StrikerFRFX commented on websites/K/Kickassanime/dist/metadata.json
> +    "version": "1.3.6",
Oops typo from copying existing metadata files sry

2021-01-27 17:51 UTC, StrikerFRFX commented on websites/K/Kickassanime/presence.ts
> +  }
Okay

2021-01-28 14:22 UTC, ririxidev requested changes

2021-01-28 14:22 UTC, ririxidev commented on websites/K/Kickassanime/presence.ts
> +   */
eee delete it?

2021-01-28 14:40 UTC, StrikerFRFX commented on websites/K/Kickassanime/presence.ts
> +   */
oopsies XD

2021-01-28 22:16 UTC, Bas950 approved these changes

2021-01-30 11:01 UTC, ririxidev approved these changes

2021-01-30 11:01 UTC, merged