Update metadata.json
PreMiD/Presences pull request #2895
Opened 2021-01-28 14:14 UTC by DarkstaIkers

O AnimesHouse trocou o visual do site e logo do site, fiz as alterações necessárias.

2021-01-28 14:15 UTC, ririxidev requested changes
next time talk in english 😉

2021-01-28 14:15 UTC, ririxidev commented on websites/A/Animes House/dist/metadata.json
> +  "logo": "https://i.imgur.com/CDlLwID.png",
it is not 512x512

2021-01-28 14:15 UTC, ririxidev commented on websites/A/Animes House/dist/metadata.json
> +  "version": "1.0.7",
1.0.6

2021-01-28 14:30 UTC, DarkstaIkers commented on websites/A/Animes House/dist/metadata.json
> +  "logo": "https://i.imgur.com/CDlLwID.png",
what can I do

2021-01-28 14:30 UTC, DarkstaIkers commented on websites/A/Animes House/dist/metadata.json
> +  "version": "1.0.7",
really?

2021-01-28 14:30 UTC, ririxidev commented on websites/A/Animes House/dist/metadata.json
> +  "logo": "https://i.imgur.com/CDlLwID.png",
resize it?

2021-01-28 14:35 UTC, DarkstaIkers reviewed
okay

2021-01-28 14:35 UTC, DarkstaIkers commented on websites/A/Animes House/dist/metadata.json
> +  "logo": "https://i.imgur.com/CDlLwID.png",
alright

2021-01-28 15:09 UTC, DarkstaIkers commented on websites/A/Animes House/dist/metadata.json
> +  "version": "1.0.7",
okay

2021-01-28 16:00 UTC, DarkstaIkers reviewed
Done

2021-01-28 17:25 UTC, DarkstaIkers reviewed
That's it?

2021-01-28 18:07 UTC, ririxidev commented
logo is still not resized to 512x512

2021-01-28 18:52 UTC, DarkstaIkers reviewed
Logo in 512x512 added

2021-01-28 19:04 UTC, ririxidev approved these changes

2021-01-28 22:20 UTC, Bas950 requested changes
Upload proof that you changed the logo in the app too. (App assets)

2021-01-29 00:01 UTC, DarkstaIkers commented
> Upload proof that you changed the logo in the app too. (App assets)

I did not understand you question, could you clarify?

2021-01-30 22:02 UTC, Bas950 commented
> > Upload proof that you changed the logo in the app too. (App assets)
> 
> I did not understand you question, could you clarify?

![Uploading image.png…]()

2021-01-31 16:42 UTC, DarkstaIkers commented
> > > Upload proof that you changed the logo in the app too. (App assets)
> > 
> > 
> > I did not understand you question, could you clarify?
> 
> ![image](https://user-images.githubusercontent.com/34792838/106369143-3f453b00-634f-11eb-8bc4-25c75df291bd.png)

Okay, it's done. Do I need send something for you?

2021-02-01 13:13 UTC, Bas950 commented
> > > > Upload proof that you changed the logo in the app too. (App assets)
> > > 
> > > 
> > > I did not understand you question, could you clarify?
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/34792838/106369143-3f453b00-634f-11eb-8bc4-25c75df291bd.png)
> 
> Okay, it's done. Do I need send something for you?

yea just upload a screenshot of it

2021-02-01 14:34 UTC, DarkstaIkers commented
> > > > > Upload proof that you changed the logo in the app too. (App assets)
> > > > 
> > > > 
> > > > I did not understand you question, could you clarify?
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/34792838/106369143-3f453b00-634f-11eb-8bc4-25c75df291bd.png)
> > 
> > 
> > Okay, it's done. Do I need send something for you?
> 
> yea just upload a screenshot of it

![6AahoMC](https://user-images.githubusercontent.com/16582975/106472462-73207d80-6481-11eb-9639-7adadf82f31c.png)
it's done

2021-02-01 14:37 UTC, ririxidev commented
okay looks like you are not owner of this presence so you can't update itxd

2021-02-01 14:37 UTC, closed without merging