Add atomicradio presence 📜
PreMiD/Presences pull request #2899
Opened 2021-01-28 15:46 UTC by InstabilSpielt

We would like to make the **atomicradio** Presence available in the PreMiD Store. We are a web radio station from Hamburg in Germany.

<img src="https://i.imgur.com/92bC7CF.png" />
<img src="https://i.imgur.com/Lag8vSV.png" />
<img src="https://i.imgur.com/0J2WFoz.png" />

2021-01-28 22:19 UTC, Bas950 requested changes

2021-01-28 22:19 UTC, Bas950 commented on websites/A/atomicradio/dist/metadata.json
> +    "contributors": [],
remove

2021-01-28 22:19 UTC, Bas950 commented on websites/A/atomicradio/dist/metadata.json
> +    "iframe": false,
remove

2021-01-28 22:22 UTC, InstabilSpielt commented
@Bas950, we have made the requested changes!

2021-01-28 22:24 UTC, Bas950 approved these changes

2021-01-30 11:03 UTC, ririxidev approved these changes

2021-01-30 11:04 UTC, merged