Added Cuevana 3 Presence
PreMiD/Presences pull request #2902
Opened 2021-01-28 23:38 UTC by magumboi

I hope you like it!
![image](https://user-images.githubusercontent.com/27692047/106212029-56d5c580-618f-11eb-8654-25a55a085030.png)
![image](https://user-images.githubusercontent.com/27692047/106212108-7ec52900-618f-11eb-9fd2-002a24e0b0cd.png)
![image](https://user-images.githubusercontent.com/27692047/106212157-96041680-618f-11eb-83a6-58bb95f22a2d.png)
![image](https://user-images.githubusercontent.com/27692047/106212175-a1efd880-618f-11eb-9552-6db9212b4633.png)

2021-01-29 03:47 UTC, magumboi commented
yikes:
![Screenshot_19](https://user-images.githubusercontent.com/27692047/106228816-c3fa5280-61b1-11eb-8188-e227a341df4c.png)

sometimes the website have a delay when showing new info, so I added a "loading" state:

![Screenshot_20](https://user-images.githubusercontent.com/27692047/106228954-1dfb1800-61b2-11eb-9a99-08423f73b50f.png)

proof of presence working:
![Screenshot_21](https://user-images.githubusercontent.com/27692047/106229078-6c101b80-61b2-11eb-9182-0b0d73d47745.png)

2021-01-30 11:06 UTC, ririxidev requested changes

2021-01-30 11:06 UTC, ririxidev commented on websites/C/Cuevana 3/presence.ts
> +}
use presence.getTimestamps

2021-01-30 18:47 UTC, magumboi commented
done 👌
![image](https://user-images.githubusercontent.com/27692047/106365146-39246f80-62f9-11eb-9e12-b1a57a9ef0fd.png)

2021-01-30 22:03 UTC, Bas950 approved these changes

2021-02-01 13:15 UTC, Bas950 approved these changes

2021-02-01 14:16 UTC, ririxidev approved these changes

2021-02-01 14:17 UTC, merged