Add Musixmatch
PreMiD/Presences pull request #2909
Opened 2021-01-30 18:57 UTC by NMW03

---
Name: Presence Creation
About: Pull request template for adding presences.
---

_In order to property create presences, please take a look at the [documentation](https://docs.premid.app/dev/presence). Take a look at the guidelines to see what is acceptable._

**Screenshots**
Please upload screenshots to github showing what the presence looks like in action. _Do not use third-party image hosting websites._

> After your pull request has been made, you should have a screenshot and the code.

2021-01-30 22:21 UTC, Bas950 submitted a review, later dismissed

2021-02-01 14:20 UTC, ririxidev requested changes

2021-02-01 14:20 UTC, ririxidev commented on websites/M/Musixmatch/dist/metadata.json
> +    "logo": "https://i.imgur.com/cAnKIMM.png",
512x512

2021-02-02 15:06 UTC, Bas950 approved these changes

2021-02-03 15:06 UTC, ririxidev approved these changes

2021-02-03 15:09 UTC, merged