Added Altearn.xyz and BuildTheEarth.net
PreMiD/Presences pull request #2918
Opened 2021-01-31 15:52 UTC by fantomitechno

So, I added two website as always x)

> Proof it's working : 

Altearn.xyz 
without ![image](https://user-images.githubusercontent.com/67735304/106389532-f8edeb80-63e3-11eb-88c9-10df808afbfa.png)
and with the privacy mode 
![image](https://user-images.githubusercontent.com/67735304/106389545-0a36f800-63e4-11eb-860e-92749918046e.png)
(This website was realy easy because with the website construction I can just see that page your looking with the window title)

BuildTheEarth.net
![image](https://user-images.githubusercontent.com/67735304/106389595-5c781900-63e4-11eb-9dd2-84f6b397b98c.png)
without 
![image](https://user-images.githubusercontent.com/67735304/106389602-66018100-63e4-11eb-8e02-59ef57ae7850.png)
and with Hide map position 
![image](https://user-images.githubusercontent.com/67735304/106389610-744f9d00-63e4-11eb-884e-cccf09c769ef.png)
(I'm realy proud of the follow with the map)
![image](https://user-images.githubusercontent.com/67735304/106389630-90ebd500-63e4-11eb-970d-12097bcfc8ee.png)
and finaly with privacy mode 
![image](https://user-images.githubusercontent.com/67735304/106389633-9f39f100-63e4-11eb-81d0-e35fd13e500d.png)

2021-02-01 13:12 UTC, Bas950 requested changes

2021-02-01 13:12 UTC, Bas950 commented on websites/A/Altearn/dist/metadata.json
> +    "logo": "https://i.imgur.com/5BHWXzu.png",
Please get a better quality pic

2021-02-01 14:37 UTC, fantomitechno commented
I asked one to the owner

2021-02-01 16:13 UTC, fantomitechno commented
And that's it

2021-02-01 22:24 UTC, Bas950 approved these changes

2021-02-03 15:07 UTC, ririxidev commented
Domain is not 2 months old 🤷

2021-02-03 15:07 UTC, closed without merging