✍ Add Animelon Presence
PreMiD/Presences pull request #2933
Opened 2021-02-03 15:35 UTC by StrikerFRFX

**Screenshots of working (with what page screenshot is from)**

Link (all links are https://animelon.com/) | Image
|-------|-----------------------------------|
homepage | ![LzyiqPMO3B](https://user-images.githubusercontent.com/34070194/106769686-22ea1c80-6635-11eb-83a3-f5ec09ee6b9c.png)
series | ![pBZkzSZF2q](https://user-images.githubusercontent.com/34070194/106769742-3301fc00-6635-11eb-8880-3bd24e6d0a1e.png)
video | ![sngHB9qUSi](https://user-images.githubusercontent.com/34070194/106769773-3ac1a080-6635-11eb-8e9c-757487492fcb.png)

Resolves #2884

2021-02-04 08:30 UTC, Bas950 requested changes

2021-02-04 08:30 UTC, Bas950 commented on websites/A/Animelon/dist/metadata.json
> +    "version": "1.0.1",
v 1.0.0 on release

2021-02-05 11:27 UTC, Bas950 approved these changes

2021-02-07 19:27 UTC, ririxidev approved these changes

2021-02-07 19:27 UTC, merged