Add Discord.FR
PreMiD/Presences pull request #2936
Opened 2021-02-03 22:30 UTC by PixelNotix

Hello ! 
I would like to add the presence for the https://discord.fr website.
Here is my discord ID: 552550090796171265

2021-02-04 01:42 UTC, PixelNotix commented
> **Screenshots of working**

> HomePage	![homepage](https://i.discord.fr/Yfq.png)
> Wiki	![wiki](https://i.discord.fr/gBh.png)
> Blog	![blog](https://i.discord.fr/TqJ.png)
> Server page 	![server](https://i.discord.fr/Lyp.png)
> Forms 1	![forms1](https://i.discord.fr/NZM.png)
> Forms 2	![forms2](https://i.discord.fr/Wlc.png)
> Forms 3	![forms3](https://i.discord.fr/T0Z.png)
> Privacy 	![privacy](https://i.discord.fr/zF5.png)
> Staff	![staff](https://i.discord.fr/4Gc.png)
> Status	![status](https://i.discord.fr/fNq.png)
> Support	![support](https://i.discord.fr/4xg.png)

2021-02-04 08:35 UTC, Bas950 requested changes
Fix codacy issues

2021-02-04 08:35 UTC, Bas950 commented on websites/D/Discord FR/dist/metadata.json
> +    "thumbnail": "https://i.discord.fr/nmj.jpg",
upload to imgur

2021-02-04 08:35 UTC, Bas950 commented on websites/D/Discord FR/presence.ts
> +  }
remove comments

2021-02-04 09:15 UTC, ririxidev requested changes

2021-02-04 09:15 UTC, ririxidev commented on websites/D/Discord FR/dist/metadata.json
> +    ],
delete contributors.

2021-02-04 09:15 UTC, ririxidev commented on websites/D/Discord FR/presence.ts
> +setInterval(updatePresenceData, 10000);
why? xD

2021-02-04 09:15 UTC, ririxidev commented on websites/D/Discord FR/presence.ts
> +var title: any;
no vars

2021-02-04 09:15 UTC, ririxidev commented on websites/D/Discord FR/presence.ts
> +let presence = new Presence({
const

2021-02-04 09:15 UTC, ririxidev commented on websites/D/Discord FR/presence.ts
> +let timestamp = Math.floor(Date.now() / 1000);
const

2021-02-04 09:15 UTC, ririxidev commented on websites/D/Discord FR/presence.ts
> +const search = document.location.pathname.split("/?q=");
merge together

2021-02-04 09:15 UTC, ririxidev commented on websites/D/Discord FR/presence.ts
> +let presenceData: PresenceData = {
const and merge with other...

2021-02-04 16:24 UTC, ririxidev requested changes

2021-02-04 16:24 UTC, ririxidev commented on websites/D/Discord FR/presence.ts
> +const presenceData: PresenceData = {
merge these consts

2021-02-04 16:24 UTC, ririxidev commented on websites/D/Discord FR/presence.ts
> +let title: any;
no any type 😉

2021-02-04 16:24 UTC, ririxidev commented on websites/D/Discord FR/presence.ts
> +  updatePresenceData();
still why ;-; please use ``presence.on("UpdateData", async () => { });`` pls not different function bruh.

2021-02-04 16:25 UTC, Isa27-0 commented
Sorry to disturb you, but changing the large image and the small image on each page not go against Discord guidelines for presence?

2021-02-04 16:27 UTC, ririxidev commented
They don't really have guidelines for it, but yea, maybe really remove changing the largeImageKey on every webpage.

2021-02-05 11:29 UTC, Bas950 requested changes
Not even an updatedata function...

2021-02-07 19:28 UTC, ririxidev commented
no response from pull request author.

2021-02-07 19:28 UTC, closed without merging