Update DreamSub domain
PreMiD/Presences pull request #2943
Opened 2021-02-05 10:09 UTC by diskxo

I updated the DreamSub domain into the Discord presence

2021-02-05 11:31 UTC, Bas950 requested changes

2021-02-05 11:31 UTC, Bas950 commented on websites/D/DreamSub/dist/metadata.json
>      "description": {
remove extra space

2021-02-07 17:13 UTC, Bas950 requested changes
Fix merge conflicts

2021-02-08 16:11 UTC, ririxidev commented
no conflict fix. closing till you will fix it.

2021-02-08 16:11 UTC, closed without merging