Add Binance presence
PreMiD/Presences pull request #2946
Opened 2021-02-06 15:03 UTC by Hibanka

Website: [Binance](https://www.binance.com/)

![1](https://user-images.githubusercontent.com/48926119/107121807-12d47600-689d-11eb-89d0-b640252c2699.png)
![2](https://user-images.githubusercontent.com/48926119/107121808-1405a300-689d-11eb-867b-5d760f80aa60.png)
![3](https://user-images.githubusercontent.com/48926119/107121809-1405a300-689d-11eb-9fac-d26a01860b13.png)
![4](https://user-images.githubusercontent.com/48926119/107121810-149e3980-689d-11eb-94fc-9ac75fe2a8eb.png)

2021-02-07 17:16 UTC, Bas950 requested changes

2021-02-07 17:16 UTC, Bas950 commented on websites/B/Binance/dist/metadata.json
> +  "thumbnail": "https://i.postimg.cc/Xqyg6PCL/ogImage.jpg",
upload to imgur

2021-02-07 17:16 UTC, Bas950 commented on websites/B/Binance/presence.ts
> +const browsingStamp = Math.floor(Date.now() / 1000)
merge consts

2021-02-07 17:16 UTC, Bas950 commented on websites/B/Binance/presence.ts
> +    presenceData.details = "Browsing...";
you are not setting the data afterwords...

2021-02-07 21:13 UTC, Bas950 requested changes
Fix codacy issues

2021-02-08 16:13 UTC, ririxidev approved these changes

2021-02-08 16:25 UTC, Bas950 approved these changes
Fix codacy issues

2021-02-08 16:25 UTC, merged