Added Altearn.xyz and BuildTheEarth.net
PreMiD/Presences pull request #2952
Opened 2021-02-07 16:24 UTC by fantomitechno

This time with Altearn.xyz with 2 mounth

> Proof it's working : 

Altearn.xyz 
without 
![image](https://user-images.githubusercontent.com/67735304/106389532-f8edeb80-63e3-11eb-88c9-10df808afbfa.png)
and with the privacy mode 
![image](https://user-images.githubusercontent.com/67735304/106389545-0a36f800-63e4-11eb-860e-92749918046e.png)
(This website was realy easy because with the website construction I can just see that page your looking with the window title)

BuildTheEarth.net
![image](https://user-images.githubusercontent.com/67735304/106389595-5c781900-63e4-11eb-9dd2-84f6b397b98c.png)
without 
![image](https://user-images.githubusercontent.com/67735304/106389602-66018100-63e4-11eb-8e02-59ef57ae7850.png)
and with Hide map position 
![image](https://user-images.githubusercontent.com/67735304/106389610-744f9d00-63e4-11eb-884e-cccf09c769ef.png)
(I'm realy proud of the follow with the map)
![image](https://user-images.githubusercontent.com/67735304/106389630-90ebd500-63e4-11eb-970d-12097bcfc8ee.png)
and finaly with privacy mode 
![image](https://user-images.githubusercontent.com/67735304/106389633-9f39f100-63e4-11eb-81d0-e35fd13e500d.png)

2021-02-07 17:20 UTC, Bas950 requested changes
Why WebSite in the names of the apps, and altearn presence seems pretty low quality

2021-02-07 19:15 UTC, fantomitechno commented
for the "Website", I modified this ![Screenshot_2021-02-07-20-10-27-42.jpg](https://user-images.githubusercontent.com/67735304/107156787-a29f2080-6980-11eb-9eb0-e40288b7d00f.jpg)

for the Altearn presence, I forget to update my github, I leave it in local ^^'
That was the first version and I forget my local version, I will update this tomorow.

2021-02-08 10:48 UTC, fantomitechno commented
So that's now the true version : 
> Proof it work

![image](https://user-images.githubusercontent.com/67735304/107209536-387b8f80-6a03-11eb-9fc5-0da44d5a1f4a.png)

![image](https://user-images.githubusercontent.com/67735304/107209573-47624200-6a03-11eb-994a-dabde90525e2.png)

![image](https://user-images.githubusercontent.com/67735304/107209620-52b56d80-6a03-11eb-8806-9eba4f0b502b.png)

![image](https://user-images.githubusercontent.com/67735304/107209652-5ea12f80-6a03-11eb-9def-c0945f7d9624.png)

![image](https://user-images.githubusercontent.com/67735304/107209751-855f6600-6a03-11eb-9f68-f8258f7fe8f5.png)

![image](https://user-images.githubusercontent.com/67735304/107209780-9019fb00-6a03-11eb-87c1-328e3fb11d55.png)

![image](https://user-images.githubusercontent.com/67735304/107209812-9c05bd00-6a03-11eb-99e8-599555764728.png)

2021-02-08 16:16 UTC, ririxidev requested changes

2021-02-08 16:16 UTC, ririxidev commented on websites/B/BuildTheEarth/presence.ts
> +    if (sprivacy) presenceData.state = "Map";
fr?

2021-02-08 16:16 UTC, ririxidev commented on websites/B/BuildTheEarth/presence.ts
> +    if (window.location.pathname.length != 1) presenceData.details = "Viewing a BuildTeams:";
fr?

2021-02-08 16:52 UTC, fantomitechno commented
Modified

2021-02-09 15:30 UTC, Bas950 requested changes

2021-02-09 15:30 UTC, Bas950 commented on websites/B/BuildTheEarth/dist/metadata.json
> +        "id": "sprivacy",
please give the ID a better name
something like mappos or something along those lines

2021-02-09 19:38 UTC, Bas950 approved these changes

2021-02-12 15:32 UTC, ririxidev approved these changes

2021-02-12 15:32 UTC, merged