Transfer of Presences from Bryan to Myself
PreMiD/Presences pull request #2980
Opened 2021-02-09 19:33 UTC by StrikerFRFX

This PR also includes another change to a different Presence owned by me, Metastream (just fixing Codacy issues) which I forgot in my previous PR lel (#2955)

The list of Presences transferred to myself are as follows:

- Skribbl.io
- Gmail
- Gartic.io & Gartic.com.br
- MangaDex
- Wattpad
- Amazon Music
- Anime Digital Network
- Pokémon Showdown
- Vimeo
- iHeartRadio

The rest of the Presences which I have not transferred will be taken by @snoweyfoxx (and a few by @Bas950 as well)

All Logos and Thumbnails have been updated since the older Gyazo links do not resolve, and I have bumped versions as well. I'll add broken Presences needed bugfixes (referencing Issues) to my TODO List and they will be gradually fixed over the next few weeks. New applications have also been created and assets have been uploaded too (and IDs changed).

Any issues, LMK.

2021-02-09 19:42 UTC, Bas950 requested changes
upload proof of them working

2021-02-09 21:15 UTC, StrikerFRFX commented
Proof of working:
![99hEuvWSyX](https://user-images.githubusercontent.com/34070194/107429457-da8e9b00-6b1b-11eb-9b4f-0428ddd0d9c3.png)
![zvLVMrQd3W](https://user-images.githubusercontent.com/34070194/107429464-dbbfc800-6b1b-11eb-84bc-6e688c2df459.png)
![ofUMPC95GQ](https://user-images.githubusercontent.com/34070194/107429469-dcf0f500-6b1b-11eb-86c4-a1901be1ec86.png)
![7d1vzww9MN](https://user-images.githubusercontent.com/34070194/107429473-dd898b80-6b1b-11eb-8c5e-352d27aef356.png)
![ZkzDuavidw](https://user-images.githubusercontent.com/34070194/107429482-debab880-6b1b-11eb-8858-6c5dbd7cf33d.png)
![CSdUOCIH0x](https://user-images.githubusercontent.com/34070194/107429483-dfebe580-6b1b-11eb-8201-5ec16334973f.png)
![dZcFaM7WGJ](https://user-images.githubusercontent.com/34070194/107429487-e11d1280-6b1b-11eb-99bf-300f9072561e.png)
![PDiQ7zahQT](https://user-images.githubusercontent.com/34070194/107429492-e1b5a900-6b1b-11eb-9883-b89d8cc3f128.png)
![NUcZt7M9Na](https://user-images.githubusercontent.com/34070194/107429510-e5e1c680-6b1b-11eb-9a4c-f31d56005b41.png)
![uRRBmxaumr](https://user-images.githubusercontent.com/34070194/107429513-e712f380-6b1b-11eb-9bab-fc8e852cc454.png)

2021-02-09 21:19 UTC, StrikerFRFX commented
And Vimeo:
![cjLf22WBZ9](https://user-images.githubusercontent.com/34070194/107430001-889a4500-6b1c-11eb-9190-d8f54eda5e11.png)

2021-02-10 23:06 UTC, Bas950 requested changes

2021-02-10 23:06 UTC, Bas950 commented on websites/A/Amazon Music/dist/metadata.json
> +  "version": "1.2.7",
that bump doesnt make sense xD

2021-02-10 23:06 UTC, Bas950 commented on websites/A/AnimeDigitalNetwork/dist/metadata.json
> +  "version": "1.2.7",
same why go up 2 versions

2021-02-10 23:06 UTC, Bas950 commented on websites/I/iHeartRadio/dist/metadata.json
> +  "version": "1.1.8",
here too

2021-02-10 23:06 UTC, Bas950 commented on websites/P/Pokémon Showdown/dist/metadata.json
> +  "version": "1.1.8",
another one

2021-02-12 15:44 UTC, Bas950 approved these changes

2021-02-14 12:28 UTC, ririxidev approved these changes

2021-02-14 12:29 UTC, merged