Update Binance presence
PreMiD/Presences pull request #2986
Opened 2021-02-12 09:10 UTC by Hibanka

Added forgotten pages

2021-02-12 15:45 UTC, ririxidev requested changes
upload proof of working presence on these subdomains

2021-02-12 15:50 UTC, Bas950 requested changes
Upload proof of it working

2021-02-12 19:06 UTC, Hibanka commented
![5](https://user-images.githubusercontent.com/48926119/107810902-0f962a00-6d76-11eb-9bae-6cd56bd70242.png)
![6](https://user-images.githubusercontent.com/48926119/107810906-10c75700-6d76-11eb-8f26-cdda5dfd6199.png)
![1](https://user-images.githubusercontent.com/48926119/107810916-14f37480-6d76-11eb-9471-2030897906d4.png)
![2](https://user-images.githubusercontent.com/48926119/107810923-158c0b00-6d76-11eb-9b63-d7dbca2eabc7.png)
![3](https://user-images.githubusercontent.com/48926119/107810925-158c0b00-6d76-11eb-8b66-5f86a21a8d3d.png)

2021-02-13 21:07 UTC, Bas950 approved these changes
Upload proof of it working

2021-02-14 12:30 UTC, ririxidev approved these changes

2021-02-14 12:30 UTC, merged