🐛 Fixed Bug in Kickassanime Presence
PreMiD/Presences pull request #2991
Opened 2021-02-12 15:19 UTC by StrikerFRFX

Anime's title and episode was not displaying properly, so I restructured the variables and changed how exactly it fetches the title and episode. Anime's with the character "-" in it would trip the shorter, previous system into thinking it should split there and that was the Episode. This is fixed now 😄 

Before fix:
![C5qbkKrZ9n](https://user-images.githubusercontent.com/34070194/107786209-7c450080-6d45-11eb-8410-64a90b3ea95d.png)

After fix:
![6uG9yYUqEo](https://user-images.githubusercontent.com/34070194/107786218-81a24b00-6d45-11eb-9b66-5f76f7e196cd.png)

2021-02-12 15:47 UTC, ririxidev requested changes

2021-02-12 15:47 UTC, ririxidev commented on websites/K/Kickassanime/presence.ts
> +      if (isMovie == false) {
fr? ``!isMovie``

2021-02-12 15:47 UTC, ririxidev commented on websites/K/Kickassanime/presence.ts
> +      if (isMovie == false) {
fr? !isMovie

2021-02-13 21:06 UTC, Bas950 approved these changes

2021-02-14 12:40 UTC, ririxidev approved these changes

2021-02-14 12:41 UTC, merged