Fix Hytale thumbnail
PreMiD/Presences pull request #2992
Opened 2021-02-12 18:24 UTC by ImRodry

It do be bigger now

2021-02-13 21:06 UTC, Bas950 approved these changes

2021-02-13 21:07 UTC, Bas950 requested changes
Update your fork

2021-02-13 21:47 UTC, Bas950 requested changes
Bump version

2021-02-14 12:19 UTC, Bas950 approved these changes

2021-02-14 12:41 UTC, ririxidev approved these changes

2021-02-14 12:41 UTC, merged