🐛FIX: metadata.json file
PreMiD/Presences pull request #3005
Opened 2021-02-14 11:08 UTC by diskxo

Updated and fixed metadata.json file (Changed DreamSub domain)

2021-02-14 12:21 UTC, Bas950 approved these changes

2021-02-14 12:42 UTC, ririxidev requested changes
proof of working presence :D

2021-02-14 17:40 UTC, diskxo commented
![105256420-073b3c80-5b86-11eb-8e97-040c7b303c1d](https://user-images.githubusercontent.com/64780086/107884211-0a5ee980-6ef4-11eb-8da5-112f753c2e94.png)
![105256442-10c4a480-5b86-11eb-81d7-9f5adbec13cb](https://user-images.githubusercontent.com/64780086/107884219-13e85180-6ef4-11eb-946d-4983a87ef87a.png)
![105256472-1c17d000-5b86-11eb-834e-49c63cb60513](https://user-images.githubusercontent.com/64780086/107884221-16e34200-6ef4-11eb-94f6-47872a0f338c.png)
![105256501-276afb80-5b86-11eb-9e40-2a88a3cf39da](https://user-images.githubusercontent.com/64780086/107884225-1b0f5f80-6ef4-11eb-9926-00e9bad71742.png)
![105256525-32be2700-5b86-11eb-98b3-fc1e6e843214](https://user-images.githubusercontent.com/64780086/107884228-1d71b980-6ef4-11eb-9bb3-91bbe67685fc.png)

2021-02-16 09:11 UTC, ririxidev approved these changes

2021-02-16 09:12 UTC, merged