Transfer of presences from Bryan to Myself, Removal of Sparklin Labs
PreMiD/Presences pull request #3008
Opened 2021-02-14 14:30 UTC by snoweyfoxx

Transferring Tubi, StopotS, Yahoo Mail, TuneIn, TV Time, Showtime, myCANAL, and Q-Dance. Sparklin Labs' games are no longer hosted the same way, and would take a complete rewrite to be compatable with jklm.fun, so I have removed that presence. Also removed Audiomack as the presence does not currently work, and needs to be troubleshooted.

![image](https://user-images.githubusercontent.com/56901798/107878575-431da500-6e99-11eb-9970-193c60f88225.png)
![image](https://user-images.githubusercontent.com/56901798/107878631-a4457880-6e99-11eb-80c9-80f5bf819294.png)
![image](https://user-images.githubusercontent.com/56901798/107878703-1027e100-6e9a-11eb-9a4e-e1ace938c2f3.png)
![image](https://user-images.githubusercontent.com/56901798/107878751-4c5b4180-6e9a-11eb-801e-cf66da999b77.png)
![image](https://user-images.githubusercontent.com/56901798/107878804-9a704500-6e9a-11eb-8339-82a8e10d737f.png)
![image](https://user-images.githubusercontent.com/56901798/107879429-4b2c1380-6e9e-11eb-979e-27d4e9d638c7.png)
![image](https://user-images.githubusercontent.com/56901798/107879459-7c0c4880-6e9e-11eb-96e7-dbe11a73184c.png)
![image](https://user-images.githubusercontent.com/56901798/107879476-9c3c0780-6e9e-11eb-921a-d21afde1cb1f.png)

2021-02-16 09:11 UTC, ririxidev requested changes

2021-02-16 09:11 UTC, ririxidev commented on websites/M/myCANAL/dist/metadata.json
> +  "logo": "https://i.imgur.com/wVDH1ja.png",
512x512

2021-02-16 09:11 UTC, ririxidev commented on websites/S/Showtime/dist/metadata.json
> +  "logo": "https://i.imgur.com/CYiIopj.png",
512x512

2021-02-16 09:11 UTC, ririxidev commented on websites/Y/Yahoo Mail/dist/metadata.json
> +  "logo": "https://i.imgur.com/qSAVHh4.png",
512x512

2021-02-18 13:18 UTC, Bas950 approved these changes

2021-02-18 13:47 UTC, ririxidev approved these changes

2021-02-18 13:47 UTC, merged