✏️ Add support for calmx.site
PreMiD/Presences pull request #3009
Opened 2021-02-14 16:39 UTC by StrikerFRFX

Proof of working on calmx.site:
![sMBz1Rmw4o](https://user-images.githubusercontent.com/34070194/107882779-3de54800-6ee3-11eb-972b-774d53502be2.png)

2021-02-16 09:09 UTC, ririxidev requested changes

2021-02-16 09:09 UTC, ririxidev commented on websites/T/TheSite/dist/metadata.json
>    "version": "1.0.6",
bump ver

2021-02-17 12:51 UTC, Bas950 approved these changes

2021-02-18 13:47 UTC, ririxidev approved these changes

2021-02-18 13:47 UTC, merged