✨ Rewrite of Amazon Music
PreMiD/Presences pull request #3023
Opened 2021-02-15 15:43 UTC by StrikerFRFX

So I've rewritten the Amazon Music Presence and it now shows what song is playing. 
The only thing I could not get working at all was the timestamps and recognizing the song was paused.
So I've removed the timestamps and the pausing logic because otherwise, it would constantly keep the time ticking even if they paused the song.

Screenshots:
![2AWWfs66Gf](https://user-images.githubusercontent.com/34070194/107966977-77ca5300-6fa4-11eb-833a-031703124296.png)
![QqxVSYSF9r](https://user-images.githubusercontent.com/34070194/107966987-7b5dda00-6fa4-11eb-8acf-963bb4d4ba5a.png)

2021-02-16 09:09 UTC, ririxidev commented
resolve conflicts

2021-02-17 09:29 UTC, Cairo2k18 requested changes
Bump the presence version in the `metadata.json` file.

2021-02-17 12:52 UTC, Bas950 requested changes
Bump version

2021-02-17 15:11 UTC, Bas950 requested changes
Bump version

2021-02-17 16:21 UTC, StrikerFRFX commented
> Bump version

It's bumped, from 1.2.6 to 1.2.7

2021-02-17 16:21 UTC, StrikerFRFX commented
> Bump version

It's bumped, from 1.2.6 to 1.2.7

2021-02-18 13:26 UTC, Bas950 requested changes

2021-02-18 13:26 UTC, Bas950 commented on websites/A/Amazon Music/presence.ts
>  }
![image](https://user-images.githubusercontent.com/34792838/108363526-501df980-71f5-11eb-8be5-156542527e8c.png)

2021-02-18 14:19 UTC, Bas950 requested changes
upload new proof of it workin

2021-02-18 16:21 UTC, StrikerFRFX commented
New Screenshots:
![JKJKgOO6UD](https://user-images.githubusercontent.com/34070194/108387210-4bf9d800-7205-11eb-9374-cffd34266217.png)
![0cokssFiqo](https://user-images.githubusercontent.com/34070194/108387217-4c926e80-7205-11eb-863e-7c3de4b1b79e.png)
![A9XnR5DwZ5](https://user-images.githubusercontent.com/34070194/108387223-4dc39b80-7205-11eb-9529-b7de6ff9e86c.png)

2021-02-19 06:41 UTC, ririxidev approved these changes

2021-02-19 15:48 UTC, Bas950 approved these changes

2021-02-19 15:49 UTC, merged