Added Mediafire
PreMiD/Presences pull request #3039
Opened 2021-02-18 15:36 UTC by DarkVillager

![mediafire6 2](https://user-images.githubusercontent.com/42322979/108380768-7482d180-7207-11eb-9f99-3bc887db54e4.jpg)
![mediafire 2 1](https://user-images.githubusercontent.com/42322979/108380771-75b3fe80-7207-11eb-80c0-09fb6207d2ab.jpg)
![Mediafire 3 1](https://user-images.githubusercontent.com/42322979/108380774-76e52b80-7207-11eb-9d06-efefb364f12e.jpg)
![mediafire1 1](https://user-images.githubusercontent.com/42322979/108380776-76e52b80-7207-11eb-96dd-7eac75057d09.jpg)
![Mediafire4 1](https://user-images.githubusercontent.com/42322979/108380777-777dc200-7207-11eb-857f-e6d32ae73d59.jpg)
![Mediafire5 1](https://user-images.githubusercontent.com/42322979/108380780-777dc200-7207-11eb-9f26-dad4bf33b9df.jpg)

2021-02-18 16:13 UTC, DarkVillager commented
(Resolves #3022)

2021-02-19 06:34 UTC, ririxidev requested changes
You should look at this:
~~ps. __Resolves__ thing must be in description of Pull request, not in comment nor title to get it working~~

2021-02-19 06:34 UTC, ririxidev commented on websites/M/Mediafire/presence.ts
> +    //   }
Delete commented statements

2021-02-19 06:34 UTC, ririxidev commented on websites/M/Mediafire/presence.ts
> +    // }
Delete commented statements

2021-02-19 08:50 UTC, DarkVillager commented on websites/M/Mediafire/presence.ts
> +    //   }
Will do.

2021-02-19 08:50 UTC, DarkVillager commented on websites/M/Mediafire/presence.ts
> +    // }
Will do.

2021-02-19 08:55 UTC, DarkVillager commented
> You should look at this:
> 
> ~~ps. __Resolves__ thing must be in description of Pull request, not in comment nor title to get it working~~

Fixed

2021-02-19 10:50 UTC, ririxidev commented
You already kinda "baked it". Because you added updates for another presence, but this pull request about Mediafire. So please, do seperate pull request for this update that you did. For now, I'm closing it till you will not fix it 😃

2021-02-19 10:52 UTC, DarkVillager commented
> You already kinda "baked it". Because you added updates for another presence, but this pull request about Mediafire. So please, do seperate pull request for this update that you did. For now, I'm closing it till you will not fix it 😃

I hope it's fixed. Can you check for me? 👍

2021-02-19 11:19 UTC, ririxidev commented
Still things from Markplaats

2021-02-19 11:20 UTC, closed without merging