Riot games presence added and made translation changes to LoL Esports
PreMiD/Presences pull request #3046
Opened 2021-02-19 13:15 UTC by KazoNighting

![Screenshot 2021-02-19 140647](https://user-images.githubusercontent.com/52106280/108508998-f1bc4e00-72bc-11eb-9f3e-68a1aed51898.png)
![Screenshot 2021-02-19 140726](https://user-images.githubusercontent.com/52106280/108508999-f254e480-72bc-11eb-99ba-f1cc2e455b45.png)
![Screenshot 2021-02-19 140752](https://user-images.githubusercontent.com/52106280/108509001-f254e480-72bc-11eb-8a76-7c5088b9e522.png)

2021-02-19 15:53 UTC, Bas950 requested changes

2021-02-19 15:53 UTC, Bas950 commented on websites/L/LoL Esports/dist/metadata.json
>    "version": "1.0.1",
Bump version

2021-02-19 20:31 UTC, ririxidev approved these changes
Looks fine for me!

2021-02-20 21:02 UTC, Bas950 approved these changes

2021-02-20 21:03 UTC, merged