Marktplaats Updated to V1.0.3
PreMiD/Presences pull request #3053
Opened 2021-02-20 21:07 UTC by DarkVillager

![marktplaats4 1](https://user-images.githubusercontent.com/42322979/108608555-f7eb2100-73c7-11eb-96ba-ed4af0178dc6.jpg)
![Marktplaats5 1](https://user-images.githubusercontent.com/42322979/108608556-f883b780-73c7-11eb-8d32-31c6f3297b25.jpg)

2021-02-20 21:30 UTC, Bas950 requested changes

2021-02-20 21:30 UTC, Bas950 commented on websites/M/Marktplaats/dist/metadata.json
> +  "version": "1.0.3",
1.1.0 or 1.0.2

2021-02-20 21:49 UTC, Bas950 approved these changes

2021-02-21 15:29 UTC, ririxidev approved these changes

2021-02-21 15:29 UTC, merged