LoLEsports Update + Riot Games Update
PreMiD/Presences pull request #3061
Opened 2021-02-21 03:37 UTC by KazoNighting

Added Button function to LoL Esports presence, made minor changes to Riot Games Presence

2021-02-21 13:38 UTC, Bas950 requested changes
upload proof

2021-02-21 16:55 UTC, KazoNighting commented
LoLEsports button integration:
![Screenshot 2021-02-21 175214](https://user-images.githubusercontent.com/52106280/108632192-ea887200-746d-11eb-8b51-6d47798a0583.png)
Riot Games Visual changes:
![Screenshot 2021-02-21 175421](https://user-images.githubusercontent.com/52106280/108632195-f116e980-746d-11eb-8a8f-d06097c48ae3.png)

2021-02-21 17:38 UTC, Bas950 approved these changes

2021-02-23 07:36 UTC, ririxidev approved these changes
looks fine for me

2021-02-23 07:36 UTC, merged