Added Buttons & small changes
PreMiD/Presences pull request #3063
Opened 2021-02-21 06:38 UTC by safan41

- Added "Spectate" button to Pokémon Showdown
- Added "Join Game" button to surviv.io
- Added "Episode" & "Series" buttons to 4anime
- Got rid of my locally defined `getTimestamps` in 4anime in favor of the `Presence` class one

![showdown](https://safan41.is-inside.me/gPxkTXhq.png)
![4anime](https://safan41.is-inside.me/lnlJOY9k.png)
![surviv.io](https://safan41.is-inside.me/Ec7669XZ.png)

2021-02-21 13:45 UTC, Bas950 requested changes

2021-02-21 13:45 UTC, Bas950 commented on websites/P/Pokémon Showdown/presence.ts
> +    delete data.buttons;
why deleting it when it aint set?

2021-02-21 15:37 UTC, ririxidev requested changes

2021-02-21 15:37 UTC, ririxidev commented on websites/0-9/4anime/presence.ts
> +    ];
This is supposed to direct to watch episode etc? So maybe describe it better like "Watch Episode", "View Series" or something

2021-02-21 17:52 UTC, Bas950 approved these changes

2021-02-23 07:35 UTC, ririxidev approved these changes
looks fine for me

2021-02-23 07:36 UTC, merged