Multporn Presence Update: 1.0.2 Basic "Read Along" Button
PreMiD/Presences pull request #3064
Opened 2021-02-21 06:50 UTC by SammCheese

- Added Button leading to whatever page you currently browse

- Bumped Ver Number to 1.0.2

![image](https://user-images.githubusercontent.com/52699291/108617789-62787d00-7419-11eb-81c4-300dd495c859.png)

2021-02-21 13:46 UTC, Bas950 submitted a review, later dismissed

2021-02-21 15:37 UTC, ririxidev requested changes

2021-02-21 15:37 UTC, ririxidev commented on websites/M/Multporn/presence.ts
> +      buttons: [{ label: "Read Along", url: document.location.href}]
maybe add setting for it ;p

2021-02-22 01:24 UTC, SammCheese commented on websites/M/Multporn/presence.ts
> +      buttons: [{ label: "Read Along", url: document.location.href}]
Done, Set to False by Default

2021-02-22 07:48 UTC, ririxidev approved these changes

2021-02-23 21:54 UTC, Bas950 approved these changes

2021-02-23 21:54 UTC, merged