Added toloka.to
PreMiD/Presences pull request #3066
Opened 2021-02-21 10:41 UTC by playday3008

2021-02-21 13:51 UTC, Bas950 requested changes

2021-02-21 13:51 UTC, Bas950 commented on websites/T/toloka.to/dist/metadata.json
> +  "logo": "https://toloka.to/favicon.png",
logo must be 512x512

2021-02-21 15:39 UTC, ririxidev requested changes

2021-02-21 15:39 UTC, ririxidev commented on websites/T/toloka.to/dist/metadata.json
> +  "logo": "https://toloka.to/favicon.png",
and on imgur lol

2021-02-21 15:39 UTC, ririxidev commented on websites/T/toloka.to/presence.ts
> +  else if (document.location.pathname.includes("/%D0%B0%D1%80%D1%85%D1%96%D0%B2.html")) {
what? XD

2021-02-22 11:32 UTC, playday3008 commented on websites/T/toloka.to/presence.ts
> +  else if (document.location.pathname.includes("/%D0%B0%D1%80%D1%85%D1%96%D0%B2.html")) {
https://toloka.to/фільми-українською.html
how to write unicode here?

2021-02-22 11:37 UTC, playday3008 commented on websites/T/toloka.to/presence.ts
> +  else if (document.location.pathname.includes("/%D0%B0%D1%80%D1%85%D1%96%D0%B2.html")) {
oh i forgot about 'encodeURIComponent'

2021-02-23 07:33 UTC, ririxidev requested changes
and after changes, we please you for another screenshots of working presence

2021-02-23 07:33 UTC, ririxidev commented on websites/T/toloka.to/presence.ts
> +  else if (document.location.pathname == ("/" + encodeURIComponent("новини.html"))) {
== -> ===

2021-02-23 07:33 UTC, ririxidev commented on websites/T/toloka.to/presence.ts
> +  else if (document.location.pathname == ("/" + encodeURIComponent("відео-гуртом.html"))) {
== -> ===

2021-02-23 07:33 UTC, ririxidev commented on websites/T/toloka.to/presence.ts
> +  else if (document.location.pathname == ("/" + encodeURIComponent("фільми-українською.html"))) {
== -> ===

2021-02-23 07:33 UTC, ririxidev commented on websites/T/toloka.to/presence.ts
> +  else if (document.location.pathname == ("/" + encodeURIComponent("українська-музика.html"))) {
== -> ===

2021-02-23 07:33 UTC, ririxidev commented on websites/T/toloka.to/presence.ts
> +  else if (document.location.pathname == ("/" + encodeURIComponent("література-українською.html"))) {
== -> ===

2021-02-23 07:33 UTC, ririxidev commented on websites/T/toloka.to/presence.ts
> +  else if (document.location.pathname == ("/" + encodeURIComponent("програми-українською.html"))) {
== -> ===

2021-02-23 07:33 UTC, ririxidev commented on websites/T/toloka.to/presence.ts
> +  else if (document.location.pathname == ("/" + encodeURIComponent("ігри-українською.html"))) {
== -> ===

2021-02-23 07:33 UTC, ririxidev commented on websites/T/toloka.to/presence.ts
> +  else if (document.location.pathname == ("/" + encodeURIComponent("архів.html"))) {
== -> ===

2021-02-23 07:59 UTC, playday3008 commented
> and after changes, we please you for another screenshots of working presence

https://ibb.co/dBF5W1c
https://ibb.co/NFnhxSW
https://ibb.co/10y2FCJ

also tested every url

2021-02-23 18:11 UTC, ririxidev approved these changes
cool, looks fine for me 👍 !

2021-02-23 22:22 UTC, Bas950 approved these changes

2021-02-23 22:22 UTC, merged