+ | Add StatifyBot Website to Presences
PreMiD/Presences pull request #3072
Opened 2021-02-21 18:42 UTC by tayron1

[1. Screenshot](https://why-do-you-look.nothing-to-see-he.re/3gbZAD)
[2. Screenshot](https://why-do-you-look.nothing-to-see-he.re/F5gpf8)

2021-02-21 21:02 UTC, Bas950 requested changes

2021-02-21 21:02 UTC, Bas950 commented on websites/S/StatifyBot/dist/metadata.json
> +    "thumbnail": "https://visionvenue.de/PicsVV/StatifyBanner.png",
upload to imgur

2021-02-21 21:02 UTC, Bas950 commented on websites/S/StatifyBot/presence.ts
> +
????

2021-02-21 21:02 UTC, Bas950 commented on websites/S/StatifyBot/presence.ts
> +  const path = window.location.pathname;
merge consts

2021-02-21 21:02 UTC, Bas950 commented on websites/S/StatifyBot/presence.ts
> +    }
that one aint allowed, as its an advertisement.

2021-02-21 21:02 UTC, Bas950 commented on websites/S/StatifyBot/presence.ts
> +    var url = new URL(url_string);
no var

2021-02-22 07:36 UTC, ririxidev commented
Sorry but this site is probably work-in-progress I guess so we are not going to accept it unfortunately.

2021-02-22 07:36 UTC, closed without merging

2021-02-22 08:19 UTC, tayron1 commented
> Sorry but this site is probably work-in-progress I guess so we are not going to accept it unfortunately.

The Site is getting Updates all the time

2021-02-22 08:20 UTC, tayron1 commented on websites/S/StatifyBot/dist/metadata.json
> +    "description": {
Do you mean the Description or what do you mean?

2021-02-22 10:26 UTC, tayron1 commented
Because its a always updating site it is always work-in-progress. The only thing that is a Placeholder is the Demo vid on the Main Page because our Trailer is still in progress