Add buttons for my presences
PreMiD/Presences pull request #3089
Opened 2021-02-22 13:37 UTC by fantomitechno

So I see that I can add buttons so I do it fastest I can !

> Proof it work : 
KaniShiel : 
![image](https://user-images.githubusercontent.com/67735304/108715513-4230e700-751b-11eb-989a-7c84de86aa1e.png)

Gunivers : 
![image](https://user-images.githubusercontent.com/67735304/108715525-48bf5e80-751b-11eb-9182-a0d0d0b738ab.png)

![image](https://user-images.githubusercontent.com/67735304/108715535-4b21b880-751b-11eb-9c9c-e90a4de9d7ce.png)

Altearn : 
![image](https://user-images.githubusercontent.com/67735304/108715564-5674e400-751b-11eb-9f78-7b62067d41ab.png)

BuildTheEarth : 
![image](https://user-images.githubusercontent.com/67735304/108715587-5d035b80-751b-11eb-9ced-9b77e65987fa.png)

![image](https://user-images.githubusercontent.com/67735304/108715590-5ecd1f00-751b-11eb-825f-2cc4d11add10.png)

FR-Minecraft : 
![image](https://user-images.githubusercontent.com/67735304/108715614-655b9680-751b-11eb-8a27-1fa193bd8dfc.png)

![image](https://user-images.githubusercontent.com/67735304/108715623-68568700-751b-11eb-886d-cbe98dd1df1d.png)

And that's it

2021-02-22 13:37 UTC, fantomitechno commented
And I forgot to bump version, I'm doing it

2021-02-22 17:51 UTC, StrikerFRFX requested changes
Resolve merging conflicts

2021-02-22 20:05 UTC, fantomitechno commented
Done, idk why when I tried to merge upstream/master into my master branch it, just don't do anything

2021-02-22 21:34 UTC, StrikerFRFX approved these changes

2021-02-23 07:21 UTC, ririxidev requested changes
fix deepscan issues too

2021-02-23 07:21 UTC, ririxidev commented on websites/A/Altearn/presence.ts
> +    ]
![image](https://user-images.githubusercontent.com/9348108/108812739-f54b2000-75af-11eb-9e8e-bdd12e3d2fa2.png)

2021-02-23 07:21 UTC, ririxidev commented on websites/B/BuildTheEarth/presence.ts
> +    ]
![image](https://user-images.githubusercontent.com/9348108/108812748-f8461080-75af-11eb-9466-bc7ba6543bdc.png)

2021-02-23 07:21 UTC, ririxidev commented on websites/G/Gunivers/presence.ts
> +    ]
![Uploading image.png…]()

2021-02-23 07:21 UTC, ririxidev commented on websites/G/Gunivers/presence.ts
> +    ]
![image](https://user-images.githubusercontent.com/9348108/108812770-009e4b80-75b0-11eb-816d-658dc1a5af00.png)
If you want to keep this button, change label for it

2021-02-23 07:21 UTC, ririxidev commented on websites/K/KaniShiel/presence.ts
> +    ]
![Uploading image.png…]()

2021-02-23 07:21 UTC, ririxidev commented on websites/F/FR-Minecraft/presence.ts
> +      ]
![image](https://user-images.githubusercontent.com/9348108/108812845-1dd31a00-75b0-11eb-8111-8fbab72eb0a5.png)

2021-02-23 10:03 UTC, fantomitechno commented
I didn't see that in the guidelines when I check but if you say it, I update ^^

2021-02-23 18:03 UTC, ririxidev approved these changes
Looks fine for me 👍 ! Don't worry because we updated guidelines yesterday so you couldn't check it before :D

2021-02-23 22:06 UTC, Bas950 approved these changes

2021-02-23 22:07 UTC, merged