✨ Update Discord Templates presence!
PreMiD/Presences pull request #3093
Opened 2021-02-22 20:58 UTC by eggsy

This update introduces:

- Buttons: View a template or a user profile with a single click (can be deactivated from presence settings).
- Privacy Settings: For those who don't like to show which template they're looking for (enabled by default).
- Fix the old logo and thumbnail.
- Add some alternative names.

![image](https://i.imgur.com/q5IzQlJ.png)

![image](https://i.imgur.com/chiFnsA.png)

![image](https://i.imgur.com/Dx7EXvK.png)

2021-02-23 07:14 UTC, ririxidev approved these changes

2021-02-23 21:57 UTC, Bas950 requested changes

2021-02-23 21:57 UTC, Bas950 commented on websites/D/Discord Templates/dist/metadata.json
> +  "version": "1.0.2",
v 1.1.0

2021-02-23 22:15 UTC, Bas950 approved these changes

2021-02-24 06:20 UTC, ririxidev approved these changes
ffs bas

2021-02-24 06:21 UTC, merged