dizay updated its website name
PreMiD/Presences pull request #3095
Opened 2021-02-23 01:37 UTC by emirkabal

2021-02-23 07:10 UTC, ririxidev requested changes
you should look at these things:

2021-02-23 07:10 UTC, ririxidev commented on websites/Y/YabancıDiziizlesene/presence.ts
> +presence.on("iFrameData", async (msg: any) => {
no any type

2021-02-23 07:10 UTC, ririxidev commented on websites/Y/YabancıDiziizlesene/dist/metadata.json
> +  "version": "1.1.5",
1.1.6

2021-02-23 07:10 UTC, ririxidev commented on websites/Y/YabancıDiziizlesene/dist/metadata.json
> +  "logo": "https://i.imgur.com/fTVFRFj.png",
can't you get better logo quality?

2021-02-23 17:50 UTC, ririxidev requested changes

2021-02-23 17:50 UTC, ririxidev commented on websites/Y/YabancıDiziizlesene/presence.ts
> +presence.on("iFrameData", async (msg: HTMLVideoElement) => {
You can't assign this type to this message lol, you are not sending video element, you are sending duration, currenttime and paused state, so do custom interface for it... and assign it.

2021-02-23 22:30 UTC, Bas950 requested changes

2021-02-23 22:30 UTC, Bas950 commented on websites/Y/YabancıDiziizlesene/iframe.ts
> +
no var

2021-02-24 14:02 UTC, Bas950 approved these changes

2021-02-25 20:15 UTC, ririxidev requested changes
![image](https://user-images.githubusercontent.com/9348108/109211461-8e478a00-77ae-11eb-9c08-712884b6a280.png)
![image](https://user-images.githubusercontent.com/9348108/109211469-91427a80-77ae-11eb-9439-001de71722ee.png)
![image](https://user-images.githubusercontent.com/9348108/109211477-94d60180-77ae-11eb-8b2b-2f21d87e203d.png)

2021-02-26 13:51 UTC, Bas950 approved these changes

2021-02-27 19:38 UTC, ririxidev approved these changes

2021-02-27 19:39 UTC, merged