Update presence.ts
PreMiD/Presences pull request #3096
Opened 2021-02-23 15:39 UTC by Isqneeh

I missed this page in my rich presence

2021-02-23 17:46 UTC, ririxidev requested changes
and bump version and upload proof of owrking presence on it

2021-02-23 17:46 UTC, ririxidev commented on websites/H/HackerRank/presence.ts
>    } else if (
um what?

2021-02-23 22:00 UTC, Bas950 requested changes
Bump version upload proof

2021-03-05 13:31 UTC, ririxidev commented
No response from pull request creator. Closing.

2021-03-05 13:31 UTC, closed without merging