:sparkles: Add presence: MALL.TV
PreMiD/Presences pull request #3103
Opened 2021-02-24 21:25 UTC by DanielKrasny

Presence for Czech/Slovak video service MALL.TV.

**Features:**
- Browsing (for homepage)
![browsing](https://user-images.githubusercontent.com/53856821/109067158-6d1f6480-76ee-11eb-85b5-645ad20aa634.png)
- Browsing (for channels, categories, search results)
![channel](https://user-images.githubusercontent.com/53856821/109067179-71e41880-76ee-11eb-89df-98b566992cd7.png)
- Playing video (with buttons)
![video](https://user-images.githubusercontent.com/53856821/109067194-74467280-76ee-11eb-9063-f533d5e80b2e.png)
- Playing live video
![video_live](https://user-images.githubusercontent.com/53856821/109067201-76103600-76ee-11eb-8035-e0113e416cf0.png)
- Paused video
![video_paused](https://user-images.githubusercontent.com/53856821/109067204-77d9f980-76ee-11eb-9855-c74c5ee30add.png)

**Note about localization:** Buttons are not localized to Czech/Slovak now as I use general strings and its translations are waiting for approval.

2021-02-25 12:21 UTC, Bas950 requested changes

2021-02-25 12:21 UTC, Bas950 commented on websites/M/MALL.TV/dist/metadata.json
> +    "logo": "https://i.imgur.com/NP66TFZ.png",
logo must be 512x512

2021-02-25 16:51 UTC, Bas950 requested changes

2021-02-25 16:51 UTC, Bas950 commented on websites/M/MALL.TV/presence.ts
> +            presenceData.smallImageText = strings.paused;
dont use the , use ;

2021-02-25 20:21 UTC, ririxidev approved these changes

2021-02-26 13:49 UTC, Bas950 approved these changes

2021-02-26 13:50 UTC, merged