Add kosmi.io Presence
PreMiD/Presences pull request #3110
Opened 2021-02-25 09:53 UTC by rndrmu

Home Page Status:
![image](https://user-images.githubusercontent.com/39674602/109135402-52350a80-7757-11eb-8c26-445c4aff4c40.png)

When the user is in a room:
![image](https://user-images.githubusercontent.com/39674602/109135535-78f34100-7757-11eb-851b-8694a1743aa2.png)

Browsing public rooms:
![image](https://user-images.githubusercontent.com/39674602/109135618-8d373e00-7757-11eb-9f5b-45d2283f06e5.png)

Browsing the Home page:
![image](https://user-images.githubusercontent.com/39674602/109135673-9e804a80-7757-11eb-946f-11a3abefc6e5.png)

2021-02-25 10:46 UTC, SlowLife1661 requested changes

2021-02-25 10:46 UTC, SlowLife1661 commented on websites/K/Kosmi/dist/metadata.json
> +    "version": "1.0",
1.0.0

2021-02-25 10:47 UTC, SlowLife1661 commented
Also why use function instead of putting them all in event *just a comment* xd

2021-02-25 10:50 UTC, rndrmu commented
> 
> 
> Also why use function instead of putting them all in event _just a comment_ xd
you're right actually, thats why i shouldnt do things late at night xd

2021-02-25 11:06 UTC, SlowLife1661 commented
Alright I will not go any further. And you might want to fix all deepscan errors.

2021-02-25 12:25 UTC, Bas950 requested changes

2021-02-25 12:25 UTC, Bas950 commented on websites/K/Kosmi/dist/metadata.json
> +    "logo": "https://i.imgur.com/v8b700V.png",
logo must be at least 512x512

2021-02-25 12:25 UTC, Bas950 commented on websites/K/Kosmi/dist/metadata.json
> +    "color": "#FF0000",
Thumbnail is a promotional banner or a screenshot of the website homepage.

2021-02-25 12:25 UTC, Bas950 commented on websites/K/Kosmi/presence.ts
> +    }
Currently a low quality presence, add some more statues or some interactive information (Like reading something of an element to display in status)

2021-02-25 17:30 UTC, rndrmu commented
should be good now :)

2021-02-25 20:22 UTC, ririxidev requested changes
jesus christ, make variables for these all things that you pass in smallImageText etc etc, this code is unreadable xDD

2021-02-27 10:54 UTC, Bas950 approved these changes

2021-02-27 10:55 UTC, Bas950 requested changes

2021-02-27 10:55 UTC, Bas950 commented on websites/K/Kosmi/dist/metadata.json
> +    "version": "1.0.1",
version 1.0.0 on release

2021-02-28 20:08 UTC, Bas950 approved these changes

2021-03-01 07:35 UTC, ririxidev approved these changes

2021-03-01 07:35 UTC, merged