Update for Vidstreaming
PreMiD/Presences pull request #3124
Opened 2021-02-26 20:13 UTC by Gurrman375

Fixed all variables and change domain name to its current one.

Proof:
image
image
image
image
image

Without video time:
image

Without time elapsed:
image

Notes:
I noticed that when I tried clicking the buttons I had to refresh or move to another page. Might be an issue with my system tho.
Last merge did something random to my code, so I had to completely refork the code.

2021-02-27 10:45 UTC, Bas950 approved these changes

2021-02-27 19:35 UTC, ririxidev requested changes

2021-02-27 19:35 UTC, ririxidev commented on websites/V/Vidstreaming/presence.ts
> +    presenceData.details = null;
``delete presenceData.details`` .-.

2021-02-27 19:35 UTC, ririxidev commented on websites/V/Vidstreaming/presence.ts
>    }
if you have this, don't set browsingStamp before then? and just don't set it to null

2021-02-28 08:14 UTC, Gurrman375 commented
My last commit fixed the error Codacy threw at me, but it failed to update that issue.
Last Github push:
![image](https://user-images.githubusercontent.com/25113575/109411874-cb9c4b00-7959-11eb-8b06-bc72a907b90f.png)

Codacy lastest review:
![image](https://user-images.githubusercontent.com/25113575/109411888-dfe04800-7959-11eb-8b3e-7a1e7078988b.png)

2021-02-28 20:17 UTC, Bas950 approved these changes

2021-03-01 07:38 UTC, merged