🎈Added Kijk (1.0.0)
PreMiD/Presences pull request #3133
Opened 2021-02-27 17:13 UTC by DarkVillager

Resolves #3047 
Added kijk basic functionality:
- Added Browsing
- Added Homepage
- Added Watching Tv Shows
- Added Watching Movies
- Added Watching Missed Tv Shows

![Screenshot_4](https://user-images.githubusercontent.com/42322979/109394445-531c9680-7927-11eb-8c5b-1b580f45383d.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/42322979/109394446-53b52d00-7927-11eb-83c2-1602886f4de8.jpg)
![Screenshot_6](https://user-images.githubusercontent.com/42322979/109394448-557ef080-7927-11eb-9fcf-69ba398fe352.jpg)
![Screenshot_7](https://user-images.githubusercontent.com/42322979/109394449-557ef080-7927-11eb-927e-cf8362597544.jpg)
![Screenshot_8](https://user-images.githubusercontent.com/42322979/109394450-56178700-7927-11eb-8127-1bcadc1331c7.jpg)
![Screenshot_9](https://user-images.githubusercontent.com/42322979/109394451-56178700-7927-11eb-95a6-ef63fd6b42fc.jpg)
![Screenshot_10](https://user-images.githubusercontent.com/42322979/109394452-56b01d80-7927-11eb-8640-73eebda8fa92.jpg)

2021-02-27 19:37 UTC, ririxidev requested changes

2021-02-27 19:37 UTC, ririxidev commented on websites/K/Kijk/dist/metadata.json
> +    "en": "Kijk opens your eyes."
is it really their desc?

2021-02-27 19:37 UTC, ririxidev commented on websites/K/Kijk/presence.ts
> +        presenceData.startTimestamp = browsingStamp;
why you set ``startTimestamp`` every time when you already set it before?

2021-02-27 19:37 UTC, ririxidev commented on websites/K/Kijk/presence.ts
> +      presenceData.startTimestamp = browsingStamp;
above ^

2021-02-27 21:14 UTC, DarkVillager commented on websites/K/Kijk/dist/metadata.json
> +    "en": "Kijk opens your eyes."
Yep sadly it is.

2021-02-28 20:18 UTC, Bas950 requested changes

2021-02-28 20:18 UTC, Bas950 commented on websites/K/Kijk/presence.ts
> +    if (host === "www.kijk.nl") {
this if is useless?

2021-03-01 11:58 UTC, DarkVillager commented on websites/K/Kijk/presence.ts
> +    if (host === "www.kijk.nl") {
For now yes.

2021-03-04 14:24 UTC, Bas950 requested changes
You should probs just use Dutch details, instead of Viewing like Bekijkt or something like that, since I am pretty sure this website is basically dutch only :/

2021-03-05 05:14 UTC, DarkVillager commented
> You should probs just use Dutch details, instead of Viewing like Bekijkt or something like that, since I am pretty sure this website is basically dutch only :/

Sure

2021-03-06 13:59 UTC, Bas950 approved these changes

2021-03-07 22:33 UTC, StrikerFRFX approved these changes

2021-03-07 22:34 UTC, merged