✨ Add presence: BetterAnime
PreMiD/Presences pull request #3135
Opened 2021-02-27 19:53 UTC by JetPlet

![image](https://user-images.githubusercontent.com/40843187/109398550-f663b080-7913-11eb-87b1-d5544e907019.png)

2021-02-28 20:10 UTC, Bas950 requested changes

2021-02-28 20:10 UTC, Bas950 commented on websites/B/BetterAnime/dist/metadata.json
> +  "logo": "https://i.imgur.com/c2w2I0m.png",
try to get a less blurry logo

2021-02-28 20:10 UTC, Bas950 commented on websites/B/BetterAnime/presence.ts
> +  const tempo = Math.floor(Date.now() / 1000),
merge consts

2021-03-05 13:36 UTC, ririxidev commented
No response from pull request creator regarding issues. Closing.

2021-03-05 13:36 UTC, closed without merging