Online Sequencer - Added buttons to listen to sequences or to view creator profile
PreMiD/Presences pull request #3141
Opened 2021-02-28 06:03 UTC by YJJcoolcool

2021-02-28 20:13 UTC, Bas950 requested changes
upload proof of it working

2021-03-01 01:52 UTC, YJJcoolcool commented
NOTE: The last update was to fix a bug for the "Time Elapsed" where the time was always 0:00

@Bas950 Here's the proof of it working:
![image](https://user-images.githubusercontent.com/39160923/109442653-ca5f4100-7a73-11eb-955d-ca354db496c6.png)

2021-03-01 07:42 UTC, ririxidev approved these changes

2021-03-04 14:17 UTC, Bas950 approved these changes

2021-03-04 14:18 UTC, merged