Merge pull request #5 from PreMiD/master
PreMiD/Presences pull request #3147
Opened 2021-02-28 20:34 UTC by Zerlingg

Search:
![Discord_9d8laikJQl](https://user-images.githubusercontent.com/38077912/109432686-ad435780-7a0c-11eb-83d5-594d76e587a3.png)

Pause:
![image](https://user-images.githubusercontent.com/38077912/109432695-bf24fa80-7a0c-11eb-8bcf-79559138fd68.png)

Play:
![image](https://user-images.githubusercontent.com/38077912/109432688-b3393880-7a0c-11eb-9986-9944a5fafd8a.png)

2021-02-28 20:45 UTC, Zerlingg commented
Idk what it failed at, and idk what i should be changing :-)

2021-03-01 07:46 UTC, ririxidev requested changes

2021-03-01 07:46 UTC, ririxidev commented on websites/T/TioAnime/dist/metadata.json
> +	"tio anime",
no spaces in tags

2021-03-01 07:46 UTC, ririxidev commented on websites/T/TioAnime/presence.ts
> +}
presence.getTimestamps()

2021-03-01 07:46 UTC, ririxidev commented on websites/T/TioAnime/presence.ts
> +let video = {
merge lets together

2021-03-01 07:46 UTC, ririxidev commented on websites/T/TioAnime/presence.ts
> +        const episode = videoTitle.textContent.split(/(\w+)$/);
merge consts

2021-03-03 08:02 UTC, Zerlingg commented
I fixed the codacy stuff and it still shows up :|

2021-03-04 14:32 UTC, Bas950 requested changes

2021-03-04 14:32 UTC, Bas950 commented on websites/T/TioAnime/dist/metadata.json
> +  "thumbnail": "https://i.imgur.com/9TgOPi4.png",
Try and get a less blurry logo and it doesnt look like the logo on the website...

2021-03-05 13:42 UTC, ririxidev commented
oh man, you literally fucked it up. Read docs then we can talk about this.

2021-03-05 13:42 UTC, closed without merging

2021-03-05 13:46 UTC, Zerlingg commented
Wdym i fucked it up? Also, what am i supposed to see at the docs? This response seems like i did something bad lol, it would be nice if i could be told what i "fucked up" or what did i do, i wasnt able to respond yesterday because i had exams and forgot, this is just confusing to me

2021-03-05 13:58 UTC, ririxidev commented
Look man, check deepscan and 
![image](https://user-images.githubusercontent.com/9348108/110125051-2bb04880-7dc3-11eb-8227-adccddbe3190.png)
what does that mean? Check this: https://docs.premid.app/en/dev/presence/class#gettimestampsnumber-number Reading docs is better thing.