Added POQ.gg
PreMiD/Presences pull request #3159
Opened 2021-03-02 17:47 UTC by Mystik01

- Added Homepage
- Account Settings, can be enabled/disabled in settings.
- Added prize store 
- Added accounts
- Added buttons to view tournaments
- Added ToS page

![image](https://user-images.githubusercontent.com/65687597/109663473-0f62a080-7b64-11eb-8691-9e76664989e6.png)
![image](https://user-images.githubusercontent.com/65687597/109663960-931c8d00-7b64-11eb-995e-96ae4d2bc5ca.png)
![image](https://user-images.githubusercontent.com/65687597/109664472-12aa5c00-7b65-11eb-862f-e0ce42b93cb2.png)
![image](https://user-images.githubusercontent.com/65687597/109664854-7f255b00-7b65-11eb-98e8-68aea6535473.png)

![image](https://user-images.githubusercontent.com/65687597/109665403-08d52880-7b66-11eb-9fdd-66dac1184a9a.png)
![image](https://user-images.githubusercontent.com/65687597/109665961-a4ff2f80-7b66-11eb-93d7-246608f6bf29.png)
![image](https://user-images.githubusercontent.com/65687597/109677359-7e92c180-7b71-11eb-8094-c943a79d21bb.png)
![image](https://user-images.githubusercontent.com/65687597/109688420-27461e80-7b7c-11eb-9842-f7c8a99314a9.png)

![image](https://user-images.githubusercontent.com/65687597/109666357-06bf9980-7b67-11eb-8615-8a085a374645.png)

2021-03-04 14:30 UTC, Bas950 requested changes
Maybe use `else if`

2021-03-04 14:30 UTC, Bas950 commented on package.json
> +  "dependencies": {}
undo

2021-03-04 14:30 UTC, Bas950 commented on websites/P/POQ/dist/metadata.json
> +  "thumbnail": "https://i.gyazo.com/7a15adb09474fd4103ac1a64fa5590cb.jpg",
upload to imgur

2021-03-04 14:30 UTC, Bas950 commented on websites/P/POQ/dist/metadata.json
> +      "title": "Show what item you're viewing in the prize store.",
make the title shorter

2021-03-04 14:30 UTC, Bas950 commented on websites/P/POQ/dist/metadata.json
> +      "title": "Show when you're editing you account info",
same here

2021-03-04 14:30 UTC, Bas950 commented on websites/P/POQ/presence.ts
> +  // converting first letter to uppercase
no need for the comment

2021-03-04 16:46 UTC, Mystik01 commented on package.json
> +  "dependencies": {}
Done ✔️

2021-03-04 16:56 UTC, Bas950 requested changes

2021-03-04 16:56 UTC, Bas950 commented on websites/P/POQ/dist/metadata.json
> +  "thumbnail": "https://i.imgur.com/rCJpho9.jpg",
logo must be 512x512 or bigger

2021-03-05 13:48 UTC, ririxidev commented
You literally bumped and add another eslint config to OUR deps so, you need to revert it obviously. Next thing, maybe read about this tho? [else if](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/if...else#description), next thing is you are setting NOTHING to state, this shouldn't happen never. If you will fix your code, you can come back with better pull request.

2021-03-05 13:48 UTC, closed without merging

2021-03-05 21:04 UTC, Mystik01 commented
Ok sorry