Repeat is back...
PreMiD/Presences pull request #3162
Opened 2021-03-03 20:54 UTC by callumok2004

works like a charm
https://i.callumdev.pw/e2f1y.png
https://i.callumdev.pw/8yxf8.png

2021-03-04 14:36 UTC, Bas950 submitted a review, later dismissed

2021-03-05 13:51 UTC, ririxidev requested changes

2021-03-05 13:51 UTC, ririxidev commented on websites/R/Repeat/dist/metadata.json
> +  "logo": "https://i.imgur.com/I5G1Lvn.png",
512x512

2021-03-05 13:51 UTC, ririxidev commented on websites/R/Repeat/presence.ts
> +  if(!data) return;
if data maybe show something like idk error?

2021-03-05 15:48 UTC, callumok2004 commented on websites/R/Repeat/dist/metadata.json
> +  "logo": "https://i.imgur.com/I5G1Lvn.png",
it is 512x512

2021-03-05 19:20 UTC, ririxidev commented on websites/R/Repeat/dist/metadata.json
> +  "logo": "https://i.imgur.com/I5G1Lvn.png",
It's 400x400

2021-03-05 19:49 UTC, Bas950 requested changes

2021-03-05 19:49 UTC, Bas950 commented on websites/R/Repeat/presence.ts
> +    timestamp: await presence.getSetting("timestamp")
why return? You have fallback strings anyway?

2021-03-06 13:56 UTC, Bas950 approved these changes

2021-03-06 22:57 UTC, callumok2004 commented
reeeeeeeeeeeee

2021-03-06 23:10 UTC, closed without merging