chore(metadata): change url
PreMiD/Presences pull request #3165
Opened 2021-03-04 01:28 UTC by KurokuTetsuya

2021-03-04 14:38 UTC, Bas950 requested changes
Bump version, upload proof of it working

2021-03-04 15:16 UTC, KurokuTetsuya commented
Proof it works:
![image](https://user-images.githubusercontent.com/45705890/109985337-39b88780-7d37-11eb-9b0f-1b0debbe9834.png)
![image](https://user-images.githubusercontent.com/45705890/109985343-3c1ae180-7d37-11eb-85a7-359b14a3545e.png)

2021-03-04 16:54 UTC, Bas950 requested changes
Bump version, upload proof of it working

2021-03-04 16:54 UTC, Bas950 commented on websites/O/Otakudesu/dist/metadata.json
> +  "version": "1.1.1",
1.1.0 or 1.0.2

2021-03-05 13:53 UTC, ririxidev approved these changes

2021-03-05 19:37 UTC, Bas950 approved these changes

2021-03-05 19:38 UTC, merged