Add Speedtest presence
PreMiD/Presences pull request #3178
Opened 2021-03-05 18:01 UTC by Nevylish

Hello, I made a presence for https://www.speedtest.net/

![Screenshot_2](https://user-images.githubusercontent.com/36775882/110154914-206e1480-7de5-11eb-81d1-4714cb620da8.png)
![Screenshot_3](https://user-images.githubusercontent.com/36775882/110154916-2106ab00-7de5-11eb-8edd-dc9aba383dee.png)
![Screenshot_4](https://user-images.githubusercontent.com/36775882/110154918-219f4180-7de5-11eb-8486-5fdb78634a8f.png)
![Screenshot_5](https://user-images.githubusercontent.com/36775882/110154921-2237d800-7de5-11eb-8f4c-71fd6c59aa14.png)
![Screenshot_6](https://user-images.githubusercontent.com/36775882/110154925-22d06e80-7de5-11eb-9a61-aa7bd84d866c.png)
![Screenshot_7](https://user-images.githubusercontent.com/36775882/110154927-22d06e80-7de5-11eb-99ab-e04c031e781e.png)
![Screenshot_9](https://user-images.githubusercontent.com/36775882/110154934-249a3200-7de5-11eb-857c-b50ba8c53b0f.png)

2021-03-05 19:27 UTC, ririxidev commented on websites/S/Speedtest/dist/metadata.json
> +  "thumbnail": "https://i.imgur.com/MdYNATM.png",
Pre``MID`` telecom yes.

2021-03-05 19:46 UTC, Bas950 requested changes

2021-03-05 19:46 UTC, Bas950 commented on websites/S/Speedtest/dist/metadata.json
> +  ]
probs better to set default to false

2021-03-06 21:40 UTC, ririxidev commented on websites/S/Speedtest/dist/metadata.json
> +  "thumbnail": "https://i.imgur.com/MdYNATM.png",
technically, fix it lol

2021-03-06 22:53 UTC, Bas950 approved these changes

2021-03-07 09:47 UTC, StrikerFRFX commented on websites/S/Speedtest/dist/metadata.json
> +  "thumbnail": "https://i.imgur.com/JXIDlOL.png",
While it's nice that the thumbnail is PreMiD Telecom and PreMiD.app as the URL, I'd just suggest changing it to different values (i.e a massive Telecom Provider), and then for the I.P just put 192.168.0.1 or 127.0.0.1 or localhost, just something not your IP obviously for privacy concerns.

2021-03-07 09:47 UTC, StrikerFRFX reviewed
While it's nice that the thumbnail is PreMiD Telecom and PreMiD.app as the URL, I'd just suggest changing it to different values (i.e a massive Telecom Provider), and then for the I.P just put 192.168.0.1 or 127.0.0.1 or localhost, just something not your IP obviously for privacy concerns.

2021-03-07 09:51 UTC, StrikerFRFX commented on websites/S/Speedtest/presence.ts
> +        presenceData.state = `ISP: ${isp} | Server: ${server}`;
could use a ternary operator for this to possibly make it show only `Server: {}` when their ISP is hidden.

2021-03-07 22:32 UTC, StrikerFRFX approved these changes

2021-03-07 22:33 UTC, merged