Add GenoPad presence
PreMiD/Presences pull request #3179
Opened 2021-03-05 19:26 UTC by EvilBrain

For https://pad.genoweb.xyz

![image](https://user-images.githubusercontent.com/49623340/110164004-14884f80-7df1-11eb-8dd4-45ece68c1e98.png)

2021-03-05 19:32 UTC, EvilBrain commented
What is the problem of Codacy Static Code Analysis ??

2021-03-05 19:52 UTC, Bas950 requested changes
dont upload js file

2021-03-05 19:52 UTC, Bas950 commented on websites/G/GenoPad/dist/metadata.json
> +  "color": "#0090ff",
version 1.0.0

2021-03-05 19:52 UTC, Bas950 commented on websites/G/GenoPad/dist/metadata.json
> +  "thumbnail": "https://i.imgur.com/Tp42TcS.png",
no sure if that thumbnail is really a "Promotional banner or a screenshot of the website homepage"

2021-03-05 19:52 UTC, Bas950 commented on websites/G/GenoPad/dist/presence.js
> +    if (document.location.hostname === "pad.genoweb.xyz") {
useless if case

2021-03-06 21:39 UTC, ririxidev commented
low quality site.

2021-03-06 21:39 UTC, closed without merging