Service name is edited
PreMiD/Presences pull request #3191
Opened 2021-03-06 22:29 UTC by berksmbl

2021-03-06 22:43 UTC, EncryptedDev requested changes
You didn't update the version to reflect the changes

2021-03-06 22:45 UTC, Bas950 requested changes
bump version

2021-03-07 16:26 UTC, StrikerFRFX commented
Why close...? I would have approved...

2021-03-07 16:30 UTC, berksmbl commented
> Why close...? I would have approved...
I apologize for not noticing.

2021-03-07 16:31 UTC, StrikerFRFX requested changes

2021-03-07 16:31 UTC, StrikerFRFX commented on websites/D/DLive/presence.ts
> +      "div.channel-header span.DLive-name span.overflow-ellipsis"
Upload proof of working

2021-03-07 16:58 UTC, StrikerFRFX commented
Oh man. Don't delete the presence.ts file, restore that. Undo the change on `Line 42` and make it back to what it was.

2021-03-07 17:28 UTC, closed without merging