repeat and bounce
PreMiD/Presences pull request #3193
Opened 2021-03-06 23:13 UTC by callumok2004

old prs show it working
idk why there are 500 other commits :D ignore them

2021-03-06 23:50 UTC, StrikerFRFX requested changes

2021-03-06 23:50 UTC, StrikerFRFX commented on websites/0-9/8muses/dist/metadata.json
> +
No newline at end of file, undo.

2021-03-06 23:56 UTC, callumok2004 commented on websites/0-9/8muses/dist/metadata.json
> +
lmfao what

2021-03-07 00:09 UTC, StrikerFRFX approved these changes

2021-03-07 13:57 UTC, Bas950 requested changes
Bump version on the ones with description changes

2021-03-07 13:57 UTC, Bas950 commented on websites/R/Repeat/dist/metadata.json
> +  "logo": "https://i.imgur.com/I5G1Lvn.png",
512x512

2021-03-07 13:57 UTC, Bas950 commented on websites/B/Bounce/dist/metadata.json
>    "color": "#32a852",
thats not really a promotion image or a screenshot of the website homepage... the colors are not even related to the logo...

2021-03-07 14:37 UTC, closed without merging