Changes | BBC iPlayer > BBC  |  Anime Planet
PreMiD/Presences pull request #3209
Opened 2021-03-08 13:22 UTC by SlowLife1661

# Info
- [x] Transfer `BBC iPlayer` to myself and changed the service name to `BBC`
    Includes `BBC iPlayer` and `BBC Sounds`

- [x] New Presence `Anime Planet`
    Resolves #3138

- [x] Small Changes
    Remove types

## Anime Planet
![image](https://cdn.discordapp.com/attachments/782936027257241603/818467528920530974/unknown.png)
![image](https://cdn.discordapp.com/attachments/782936027257241603/818467684160897054/unknown.png)
![image](https://cdn.discordapp.com/attachments/782936027257241603/818467569475911740/unknown.png)
* And many more...

## BBC
![image](https://cdn.discordapp.com/attachments/782936027257241603/818467588027318302/unknown.png)
![image](https://cdn.discordapp.com/attachments/782936027257241603/818467601289969694/unknown.png)
![image](https://cdn.discordapp.com/attachments/782936027257241603/818468528100212746/unknown.png)
![image](https://cdn.discordapp.com/attachments/782936027257241603/818468537274335302/unknown.png)
* Might as well add more pages if users were requested kek

2021-03-08 15:01 UTC, StrikerFRFX reviewed
I'm pretty sure that @trains2050 mentioned to me that there's not a presence for the BBC website... could add that as well as Player functionality since some articles have videos which is the same player as iPlayer afaik (or the BBC website has a link to iPlayer within it idk don't use BBC website kek).

2021-03-08 15:05 UTC, SlowLife1661 commented
👍

2021-03-08 15:06 UTC, SlowLife1661 commented
Closing this untill BBC is done

2021-03-08 15:24 UTC, trains2050 commented
@SlowLife1661 
these services should be added 
1. BBC news 
2. bbc sounds 
3. bbc iplayer 
4. the bbc home page 
5. weather 
6. sport

2021-03-08 15:35 UTC, SlowLife1661 commented
Alright thanks for those

2021-03-08 15:49 UTC, StrikerFRFX commented
Stop reopening and closing as if it's a draft, reopen once you've finished your changes and edit your screenshots.

2021-03-08 23:49 UTC, SlowLife1661 commented
I mean I missclick kek

2021-03-09 02:06 UTC, StrikerFRFX commented
> I mean I missclick kek

mkay couldn't be me kek

2021-03-09 15:51 UTC, SlowLife1661 commented
Sport and news is done sceenshots updated

2021-03-09 15:52 UTC, trains2050 commented
> Sport and news is done sceenshots updated, some pages may be missing because yes

Reopen when you are ready

2021-03-12 04:38 UTC, SlowLife1661 commented
I will get this done *by Sunday*, I was quite busy at the moment.

2021-03-12 20:31 UTC, Bas950 requested changes

2021-03-12 20:31 UTC, Bas950 commented on websites/A/Anime Planet/dist/metadata.json
> +    "$schema": "https://schemas.premid.app/metadata/1.0",
use latest schema (v1.3)

2021-03-12 20:31 UTC, Bas950 commented on websites/A/Anime Planet/presence.ts
> +          }
as unknown needed?

2021-03-12 20:31 UTC, Bas950 commented on websites/B/BBC/dist/metadata.json
> +  },
add the authors / contributors of the orginal bbc presence as contributor

2021-03-12 20:31 UTC, Bas950 commented on websites/B/BBC/presence.ts
> +        ];
Read? Do you mean Read Article?

2021-03-12 20:31 UTC, Bas950 commented on websites/B/BBC/presence.ts
> +          }
same here

2021-03-12 20:31 UTC, Bas950 commented on websites/B/BBC/presence.ts
> +            url: document.baseURI
here 2

2021-03-12 20:31 UTC, Bas950 commented on websites/B/BBC/presence.ts
> +          }
again

2021-03-12 20:31 UTC, Bas950 commented on websites/B/BBC/presence.ts
> +      }
more

2021-03-12 20:31 UTC, Bas950 commented on websites/B/BBC/presence.ts
> +        }
everywhere?

2021-03-12 20:31 UTC, Bas950 commented on websites/B/BBC/presence.ts
> +          url: document.baseURI
View what?

2021-03-12 20:31 UTC, Bas950 commented on websites/I/iQIYI/presence.ts
you could just set this as the largeImageKey, doesnt needs its own const

2021-03-13 13:43 UTC, Bas950 requested changes

2021-03-13 13:43 UTC, Bas950 commented on websites/D/DramaCool/dist/metadata.json
> +    "url": "dramacool.vc",
please use regex, since they change urls a lot

2021-03-13 14:37 UTC, Bas950 submitted a review, later dismissed

2021-03-16 13:53 UTC, Bas950 requested changes
upload new proof of these latest changes working

2021-03-16 13:55 UTC, SlowLife1661 commented
See above reee

2021-03-16 13:56 UTC, Bas950 approved these changes

2021-03-19 16:34 UTC, StrikerFRFX approved these changes

2021-03-19 16:34 UTC, merged