Added Buttons
PreMiD/Presences pull request #3216
Opened 2021-03-08 20:57 UTC by Gurrman375

![image](https://user-images.githubusercontent.com/25113575/110380766-6b6a7080-800d-11eb-96a2-332cf11115cf.png)
![image](https://user-images.githubusercontent.com/25113575/110380829-8210c780-800d-11eb-8736-b8b888ea11c0.png)

Added Buttons:
![image](https://user-images.githubusercontent.com/25113575/110380889-9359d400-800d-11eb-9bce-f515505d60be.png)
![image](https://user-images.githubusercontent.com/25113575/110380932-a79dd100-800d-11eb-8b5c-9cfa5e34c291.png)
![image](https://user-images.githubusercontent.com/25113575/110380948-aec4df00-800d-11eb-9c0b-7ab46ea82e7f.png)

Note: For some reason elapsed time doesn't work with buttons. I think I just have a bad installation of PreMiD.

2021-03-08 22:33 UTC, Bas950 requested changes
Enable the infos or remove the comments.

2021-03-08 22:55 UTC, Bas950 requested changes
bump version

2021-03-08 23:47 UTC, Bas950 approved these changes

2021-03-09 02:05 UTC, StrikerFRFX approved these changes

2021-03-09 02:19 UTC, merged