Updated Google Fonts presence
PreMiD/Presences pull request #3234
Opened 2021-03-11 22:03 UTC by peaillaud

Hi, I closed my previous PR because I messed up something but nevermind, merge conflicts should be fixed

![image](https://user-images.githubusercontent.com/36643560/110699695-6c5af800-81ef-11eb-8072-7ab56f31527f.png)
![image](https://user-images.githubusercontent.com/36643560/110699730-78df5080-81ef-11eb-8cd6-b8816a3d1576.png)
![image](https://user-images.githubusercontent.com/36643560/110699752-7da40480-81ef-11eb-8809-b3e7ec736840.png)

Thank you

2021-03-12 09:59 UTC, Bas950 requested changes

2021-03-12 09:59 UTC, Bas950 commented on websites/G/Google Fonts/dist/metadata.json
> +    "logo": "https://i.imgur.com/l1S996y.png",
you need to up the version.. not make it lower

2021-03-13 13:46 UTC, Bas950 approved these changes

2021-03-19 16:31 UTC, StrikerFRFX approved these changes

2021-03-19 16:31 UTC, merged