Modification of logos and other changes
PreMiD/Presences pull request #3242
Opened 2021-03-13 10:24 UTC by MaXfAa

Modification of logos (and colors), addition of descriptions in French and other small changes to the following presences :

1. Bing
2. Google Calendar
3. Google Docs
4. Dominos
5. Google Drive
6. Google Fonts
7. Gmail
8. Google Meet
9. (Facebook) Messenger
10. myCanal
11. ProBot
12. Rythm
13. Skype
14. Zalando

2021-03-13 13:32 UTC, Bas950 requested changes
Not enough to add you as contributor.
Upload to Imgur.
And the logos need to be changed in the Discord Application, and I bet you didnt contact the presence authors to update that... (Cause I am the author of a few of them and got no message)

2021-03-15 18:24 UTC, MaXfAa commented
> Not enough to add you as contributor.
> Upload to Imgur.
> And the logos need to be changed in the Discord Application, and I bet you didnt contact the presence authors to update that... (Cause I am the author of a few of them and got no message)
Ok, so:
1. I changed to Imgur
2. I withdrew from "contributor" (again sorry)
And tomorrow would do the following (contact the authors, etc...)

2021-03-16 01:01 UTC, SlowLife1661 commented on websites/P/ProBot/dist/metadata.json
> +  ],
👀

2021-03-16 01:04 UTC, SlowLife1661 requested changes

2021-03-16 01:04 UTC, SlowLife1661 commented on websites/G/Google Meet/dist/metadata.json
> +  ],
👀

2021-03-16 01:04 UTC, SlowLife1661 commented on websites/P/ProBot/dist/metadata.json
> +  ],
👀

2021-03-16 01:04 UTC, SlowLife1661 commented on websites/M/myCANAL/dist/metadata.json
> -  ],
👀

2021-03-16 01:04 UTC, SlowLife1661 commented on websites/R/Rythm/dist/metadata.json
> -}
🤷‍♂️

2021-03-16 01:06 UTC, SlowLife1661 commented on websites/R/Rythm/dist/metadata.json
> -}
Resolve the conflicts.

2021-03-16 08:52 UTC, MaXfAa commented on websites/G/Google Meet/dist/metadata.json
> +  ],
Wtf

2021-03-16 13:48 UTC, Bas950 commented
> > Not enough to add you as contributor.
> > Upload to Imgur.
> > And the logos need to be changed in the Discord Application, and I bet you didnt contact the presence authors to update that... (Cause I am the author of a few of them and got no message)
> > Ok, so:
> 
> 1. I changed to Imgur
> 2. I withdrew from "contributor" (again sorry)
>    And tomorrow would do the following (contact the authors, etc...)

What about 3.?

2021-03-19 17:01 UTC, ririxidev commented
Resolve conflicts, do everything that Bas said then open new pull request.

Thanks,
ririxi (Contact: mail@ririxi.dev, ririxi#2721)

2021-03-19 17:01 UTC, closed without merging