Added DiscordJS Guide & added Font Awesome
PreMiD/Presences pull request #3243
Opened 2021-03-13 17:13 UTC by OGMatrix

**Font Awesome on Main:**
![ss1](https://user-images.githubusercontent.com/49974161/111038063-59cb0380-8427-11eb-9060-371af929ab8a.PNG)

**Font Awesome on viewing a Icon:**
![ss2](https://user-images.githubusercontent.com/49974161/111038065-5afc3080-8427-11eb-8bfc-249ba425bf16.PNG)

**DiscordJS Guide on Page:**
![ss1](https://user-images.githubusercontent.com/49974161/111038136-a3b3e980-8427-11eb-929d-2547d58244d3.PNG)
![ss2](https://user-images.githubusercontent.com/49974161/111038139-a4e51680-8427-11eb-97d1-389635c9d5d3.PNG)

**If you need more Images just say it!**

2021-03-13 23:01 UTC, EncryptedDev commented
The Disocrd.js one literally just takes a H1... low quality presence?

2021-03-13 23:02 UTC, OGMatrix commented
> The Disocrd.js one literally just takes a H1... low quality presence?

But its a presence

2021-03-13 23:12 UTC, EncryptedDev commented
> > The Disocrd.js one literally just takes a H1... low quality presence?
> 
> But its a presence

Maybe instead support Discord.js' full website instead of just a niche part of the website

2021-03-14 10:34 UTC, OGMatrix commented
> It's all pretty low quality 🤷

It doesnt go on the Quality, it goes on the usages

2021-03-14 12:19 UTC, Bas950 requested changes

2021-03-14 12:19 UTC, Bas950 commented on websites/D/Discord BotList/dist/metadata.json
>    }
bump version

2021-03-14 12:19 UTC, Bas950 commented on websites/D/DiscordJS.guide/presence.ts
> +  if (pPage.includes("/")) {
always true

2021-03-14 12:19 UTC, Bas950 commented on websites/D/DiscordJS.guide/dist/metadata.json
> +    "thumbnail": "https://i.imgur.com/ojmsp7f.png",
logo needs to be at least 512x512

2021-03-14 12:19 UTC, Bas950 commented on websites/D/DiscordJS.guide/tsconfig.json
> +
remove extra line

2021-03-14 12:19 UTC, Bas950 commented on websites/F/Font Awesome/dist/metadata.json
> +    "thumbnail": "https://i.imgur.com/GJFmAgg.png",
logo needs to be at least 512x512

2021-03-14 12:19 UTC, Bas950 commented on websites/F/Font Awesome/presence.ts
> +        pData.state = icon;
Viewing icon not watching

2021-03-16 13:48 UTC, Bas950 requested changes
First of all fix:
![image](https://user-images.githubusercontent.com/34792838/111319721-99cbf980-8666-11eb-8124-c27f1bff8202.png)

2021-03-16 14:01 UTC, OGMatrix commented
> First of all fix:
> ![image](https://user-images.githubusercontent.com/34792838/111319721-99cbf980-8666-11eb-8124-c27f1bff8202.png)

@Bas950 I dont get whats wrong

2021-03-16 14:10 UTC, Bas950 commented
> > First of all fix:
> > ![image](https://user-images.githubusercontent.com/34792838/111319721-99cbf980-8666-11eb-8124-c27f1bff8202.png)
> 
> @Bas950 I dont get whats wrong

you probs just need to update your fork

2021-03-16 22:30 UTC, Bas950 commented
> > > > First of all fix:
> > > > ![image](https://user-images.githubusercontent.com/34792838/111319721-99cbf980-8666-11eb-8124-c27f1bff8202.png)
> > > 
> > > 
> > > @Bas950 I dont get whats wrong
> > 
> > 
> > you probs just need to update your fork
> 
> Did it doesnt work

![image](https://user-images.githubusercontent.com/34792838/111388467-9b6ddf80-86af-11eb-952d-176fc144a025.png)
you sure about that?

2021-03-17 22:05 UTC, callumok2004 commented on websites/D/DiscordJS.guide/dist/metadata.json
> +    "version": "1.0.1",
New presence, use version 1.0.0

2021-03-17 22:05 UTC, callumok2004 commented on websites/F/Font Awesome/dist/metadata.json
> +    "version": "1.0.1",
New presence, use version 1.0.0

2021-03-18 19:06 UTC, Bas950 commented
Fix merge conflicts

2021-03-19 15:34 UTC, OGMatrix commented
> Fix merge conflicts

how

2021-03-19 15:45 UTC, OGMatrix commented
new pr

2021-03-19 15:45 UTC, closed without merging