New Presence, Pilli Oyun (pillioyun)
PreMiD/Presences pull request #3245
Opened 2021-03-14 13:48 UTC by KeremWho

**Work Preview:** https://streamable.com/v4dk2t

2021-03-14 15:54 UTC, SlowLife1661 requested changes

2021-03-14 15:54 UTC, SlowLife1661 commented on websites/P/Pilli Oyun/dist/metadata.json
> +  "thumbnail": "https://pillioyun.com/premid-assets/screenshot.png",
Upload to imgur

2021-03-14 15:55 UTC, SlowLife1661 commented
Why not make a presenceData variable?

2021-03-14 16:03 UTC, KeremWho commented on websites/P/Pilli Oyun/dist/metadata.json
> +  "thumbnail": "https://pillioyun.com/premid-assets/screenshot.png",
I did.

2021-03-14 16:07 UTC, KeremWho commented
> Why not make a presenceData variable, and then use setActivity() once?

I took PlayerBros' presence as an example.

2021-03-15 06:40 UTC, SlowLife1661 requested changes

2021-03-16 13:37 UTC, Bas950 commented
The website/domain isnt old enough.

2021-03-16 13:37 UTC, closed without merging