OMG! Ubuntu! Presence
PreMiD/Presences pull request #3258
Opened 2021-03-15 23:29 UTC by v30xy

OMG! Ubuntu Presence. Here is some screenshot.
![Ekran görüntüsü 2021-03-16 02-23-21](https://user-images.githubusercontent.com/41836521/111234251-2e9b0c80-85ff-11eb-97b6-f981f0375623.png)
![Ekran görüntüsü 2021-03-16 02-23-40](https://user-images.githubusercontent.com/41836521/111234253-2fcc3980-85ff-11eb-8e1b-ec5a767c8f9b.png)
![Ekran görüntüsü 2021-03-16 02-24-07](https://user-images.githubusercontent.com/41836521/111234256-3064d000-85ff-11eb-8893-6d672b7f5f7f.png)
![Ekran görüntüsü 2021-03-16 02-28-10](https://user-images.githubusercontent.com/41836521/111234307-4e323500-85ff-11eb-9636-e8d1f4abd24c.png)

2021-03-16 00:23 UTC, SlowLife1661 commented on websites/O/OMG! Ubuntu!/presence.ts
> +    presenceData.details = "Looking articles";
This seems like a grammar error kekw

2021-03-16 06:03 UTC, SlowLife1661 commented on websites/O/OMG! Ubuntu!/presence.ts
> +    presenceData.details = "Looking a category:";
These 2 detail as well

2021-03-16 06:03 UTC, SlowLife1661 commented on websites/O/OMG! Ubuntu!/presence.ts
> +    presenceData.details = "Looking a page:";
^

2021-03-16 06:10 UTC, v30xy commented on websites/O/OMG! Ubuntu!/presence.ts
> +    presenceData.details = "Looking a page:";
:ok_hand: Thanks

2021-03-16 13:46 UTC, Bas950 requested changes

2021-03-16 13:46 UTC, Bas950 commented on websites/O/OMG! Ubuntu!/presence.ts
> +    OMGUbuntu.setActivity(presenceData);
just use setACtivity once at the end

2021-03-16 14:01 UTC, v30xy commented on websites/O/OMG! Ubuntu!/presence.ts
> +    OMGUbuntu.setActivity(presenceData);
:+1:

2021-03-16 21:23 UTC, Bas950 approved these changes

2021-03-18 18:58 UTC, Bas950 approved these changes

2021-03-19 16:55 UTC, ririxidev approved these changes
LGTM!

2021-03-19 16:55 UTC, merged