Small improvements to the atomicradio Presence
PreMiD/Presences pull request #3263
Opened 2021-03-16 21:05 UTC by VocalZero

2021-03-16 21:14 UTC, InstabilSpielt commented
We have made minor changes, including moving the status page so that information can still be given to our users in the event of an incident. In addition, the documentation for developers has been released and has been integrated and the logo is now delivered in the most optimal size.

2021-03-16 22:37 UTC, Bas950 requested changes
Upload proof of it working

2021-03-16 22:37 UTC, Bas950 commented on websites/A/atomicradio/dist/metadata.json
> +    "author": {
use latest schema (v1.3)

2021-03-16 22:37 UTC, Bas950 commented on websites/A/atomicradio/dist/metadata.json
> +    "version": "1.0.1",
bump version

2021-03-16 22:58 UTC, VocalZero commented
Changed schema version to 1.3 and updated presence version from 1.0.1 to 1.0.2

## Proof of work
![Screenshot 2021-03-16 235059](https://user-images.githubusercontent.com/20924469/111390580-40d68280-86b3-11eb-9c0e-1bb93e8b882b.png)
![Screenshot 2021-03-16 235146](https://user-images.githubusercontent.com/20924469/111390592-459b3680-86b3-11eb-8b23-19bf01db7974.png)
![Screenshot 2021-03-16 235205](https://user-images.githubusercontent.com/20924469/111390595-46cc6380-86b3-11eb-86d2-802c29cc6650.png)

2021-03-18 18:55 UTC, Bas950 approved these changes

2021-03-19 02:25 UTC, InstabilSpielt commented
Hello everyone, we sat down yesterday and thought about how we can ensure to avoid excessive requests even if no end timestamp of a song is available (For example, when we are currently live). Because we would normally trust socket.io, which unfortunately is not possible here, we decided to do it the oldschool way, with websockets.

2021-03-19 02:26 UTC, VocalZero commented
## Proof of work
![Screenshot 2021-03-19 025627](https://user-images.githubusercontent.com/20924469/111722795-d5331780-8862-11eb-9136-d31df3dbe7c9.png)

2021-03-19 16:52 UTC, ririxidev requested changes
You should check my requested changes

Thanks,
ririxi (Contact: mail@ririxi.dev, ririxi#2721)

2021-03-19 16:52 UTC, ririxidev commented on websites/A/atomicradio/dist/metadata.json
> +    "version": "1.0.2",
This update should be treated as 2.0.0

2021-03-19 16:52 UTC, ririxidev commented on websites/A/atomicradio/presence.ts
> +  }
I don't see sense in this if statement because you only have 2 subdomains and one main domain.

2021-03-19 16:52 UTC, ririxidev commented on websites/A/atomicradio/presence.ts
> +  if (window.location.origin === "https://docs.atomicradio.eu") {
Instead of checking origin you could just check subdomain by ``window.location.host.split('.')[0]`` it will be easier and cleaner.

2021-03-19 17:53 UTC, VocalZero commented
Implemented your suggested changes

2021-03-19 18:01 UTC, ririxidev submitted a review, later dismissed
LGTM!

2021-03-20 13:26 UTC, Bas950 requested changes

2021-03-20 13:26 UTC, Bas950 commented on websites/A/atomicradio/dist/metadata.json
> +    "category": "music"
```suggestion
    "category": "music",
    "button": false
```

2021-03-20 13:50 UTC, VocalZero commented
Changes to the `metadata.json` have been applied.

2021-03-20 14:01 UTC, ririxidev approved these changes
LGTM ~~(again)~~!

2021-03-20 15:26 UTC, Bas950 approved these changes
LGTM

2021-03-20 15:27 UTC, merged