Added Google Photos Presence!
PreMiD/Presences pull request #3264
Opened 2021-03-17 02:46 UTC by JohanRBX

![unknown](https://user-images.githubusercontent.com/80731951/111406852-fea44580-86a0-11eb-9ed6-fd4839ef3e94.png)
![unknown (2)](https://user-images.githubusercontent.com/80731951/111406856-ffd57280-86a0-11eb-9bb7-ed30c59d8342.png)

2021-03-17 05:26 UTC, SlowLife1661 commented
Use 3rd person instead of 1st person

2021-03-17 05:33 UTC, SlowLife1661 requested changes
*Just a suggestion* And you can just remove the comments and the code

2021-03-17 05:33 UTC, SlowLife1661 commented on presence.ts
> +    // Página de compartidos
Remove spaces

2021-03-17 05:33 UTC, SlowLife1661 commented on presence.ts
> +    // Explorar.
Same here

2021-03-17 05:33 UTC, SlowLife1661 commented on presence.ts
> +    // Fotos
Here

2021-03-17 05:33 UTC, SlowLife1661 commented on presence.ts
> +  const buttons = presence.getSetting("buttons")
No var, marge const

2021-03-17 05:33 UTC, SlowLife1661 commented on presence.ts
> +      };
Declare this outside scope and you can just reassign it's value

2021-03-17 05:33 UTC, SlowLife1661 commented on presence.ts
> +    // Página de compartidos
Spaces

2021-03-17 05:33 UTC, SlowLife1661 commented on presence.ts
> +    presence.setActivity(presenceData);
Use it once at the end

2021-03-17 05:33 UTC, SlowLife1661 commented on presence.ts
> +    // Configuración
Spaces

2021-03-17 05:33 UTC, SlowLife1661 commented on presence.ts
> +    // Papelera
Spaces

2021-03-17 05:33 UTC, SlowLife1661 commented on presence.ts
> +    // Archivo.
Spaces

2021-03-17 05:33 UTC, SlowLife1661 commented on presence.ts
> +    // Página de utilidades.
Spaces

2021-03-17 05:33 UTC, SlowLife1661 commented on presence.ts
> +    // Álbumes
Spaces

2021-03-17 05:36 UTC, SlowLife1661 commented on presence.ts
> +  const buttons = presence.getSetting("buttons")
And the settings what happens if they change it?

2021-03-18 19:17 UTC, Bas950 requested changes
first of all put it in the correct folder

2021-03-19 03:52 UTC, closed without merging