⚡ Fix keybr.com (implement)
PreMiD/Presences pull request #3270
Opened 2021-03-17 20:42 UTC by PiggyPlex

> Refactoring and fixed for CI/CD. Unsure about the initial bug.
> Please let me know if anyone experiences issues with the presence!

`Referencing` #3090 #2996 

**Screenshots**
![image](https://user-images.githubusercontent.com/15018948/111535679-48546500-8761-11eb-9c3c-62ed567dd138.png)
![image](https://user-images.githubusercontent.com/15018948/111535694-4be7ec00-8761-11eb-987e-ed76d3b9556a.png)
![image](https://user-images.githubusercontent.com/15018948/111535704-4d191900-8761-11eb-9bc6-b2d5026595bf.png)
![image](https://user-images.githubusercontent.com/15018948/111535707-4f7b7300-8761-11eb-9dbe-afa767376550.png)

2021-03-17 21:52 UTC, callumok2004 requested changes

2021-03-17 21:52 UTC, callumok2004 commented on websites/K/keybr.com/dist/metadata.json
> +    "thumbnail": "https://i.imgur.com/D6gTvpU.png",
Must be 512x512

2021-03-17 21:52 UTC, callumok2004 commented on websites/K/keybr.com/dist/metadata.json
> +    "version": "1.0.1",
Change to 1.0.0 since its new

2021-03-17 21:52 UTC, callumok2004 commented on websites/K/keybr.com/presence.ts
> +  presence.setTrayTitle();
Only set tray title of there is no presenceData to send (state/details)

2021-03-18 19:06 UTC, Bas950 requested changes
And all things callum said

2021-03-18 19:06 UTC, Bas950 commented on websites/K/keybr.com/presence.ts
> +      });
remove console log

2021-03-20 14:13 UTC, ririxidev requested changes
Heya @PiggyPlex!
You should check out thing(s) that I requested to change in my review and other changes requested by @Bas950 & @callumok2004. Please look at them!

P.S. Please don't make your code like it was taken from some minifier because for us, it only makes harder to read your code and it will take long to accept it. so please next time name these functions normally instead of ``d, a`` etc. and make less functions since they are not necessary. Thank youu!!!

Thanks,
**ririxi**. PreMiD Reviewer Team.
Contact: mail@ririxi.dev, ririxi#2721

2021-03-20 14:13 UTC, ririxidev commented on websites/K/keybr.com/presence.ts
> +}), startTime: number = new Date().getTime();
It should be
```javascript
startTime = Math.floor(Date.now() / 1000)
```

2021-03-20 14:13 UTC, ririxidev commented on websites/K/keybr.com/dist/metadata.json
> +            "placeholder": "Current Key: %currentkey%"
Actually, placeholder isn't necessary.

2021-03-20 14:13 UTC, ririxidev commented on websites/K/keybr.com/dist/metadata.json
> +            "placeholder": "WPM: %speed.wpm% | Score: %score%"
Actually, placeholder isn't necessary.

2021-03-24 14:27 UTC, ririxidev commented
Heya @PiggyPlex! We have some news for you that you should take look at:
We are so sorry but we need to deny your pull request regarding this presence due of:
 - No response since first review (7 days as specified in guidelines).
 
Thanks,
**ririxi**. PreMiD Reviewer Team.
Contact: mail@ririxi.dev, ririxi#2721

2021-03-24 14:27 UTC, closed without merging