✨ Added Kryptonia
PreMiD/Presences pull request #3272
Opened 2021-03-18 00:57 UTC by iAmaury

Added presence for kryptonia.fr, a French minecraft server.

https://i.imgur.com/yqkNyqc.png
https://i.imgur.com/gnwVs7C.png

2021-03-18 01:27 UTC, SlowLife1661 requested changes

2021-03-18 01:27 UTC, SlowLife1661 commented on websites/K/Kryptonia/presence.ts
> +      startTimestamp: Date.now()
It's second not millisecond

2021-03-18 01:30 UTC, SlowLife1661 commented
Also fix linebreaks

2021-03-18 01:37 UTC, SlowLife1661 requested changes

2021-03-18 01:37 UTC, SlowLife1661 commented on websites/K/Kryptonia/dist/metadata.json
> +    "logo": "https://i.imgur.com/wbPswzO.png",
Must at least be 512x512

2021-03-18 01:55 UTC, iAmaury commented
> Also fix linebreaks, don't ask whose screenshot 😸
> ![dontaskwhosesh](https://user-images.githubusercontent.com/34792838/110391061-3c80e880-8067-11eb-9511-1ab807555589.png)

Been trying for two hours

2021-03-18 02:04 UTC, SlowLife1661 commented
> > Also fix linebreaks, don't ask whose screenshot 😸
> > ![dontaskwhosesh](https://user-images.githubusercontent.com/34792838/110391061-3c80e880-8067-11eb-9511-1ab807555589.png)
> 
> Been trying for two hours

Maybe use Prettier or something

2021-03-18 02:07 UTC, iAmaury commented
> > > Also fix linebreaks, don't ask whose screenshot 😸
> > > ![dontaskwhosesh](https://user-images.githubusercontent.com/34792838/110391061-3c80e880-8067-11eb-9511-1ab807555589.png)
> > 
> > 
> > Been trying for two hours
> 
> Maybe use Prettier or something

Seems like it worked this time

2021-03-18 02:10 UTC, SlowLife1661 requested changes

2021-03-18 02:10 UTC, SlowLife1661 commented on websites/K/Kryptonia/presence.ts
> +      startTimestamp: Date.now()/1000
Math.floor it also

2021-03-18 12:26 UTC, iAmaury commented
It's broken, I just added three lines, there was no issue with CRLF to LF before the most recent commit, and now it's filled with that issue, but only three lines changed when checking the commit

2021-03-18 19:15 UTC, Bas950 requested changes

2021-03-18 19:15 UTC, Bas950 commented on websites/K/Kryptonia/dist/metadata.json
> +      "en": "Kryptonia is a French Minecraft PVP Factions server."
the descriptions dont seem to match

2021-03-18 19:23 UTC, Bas950 approved these changes

2021-03-19 16:31 UTC, ririxidev approved these changes
LGTM!
@SlowLife1661 minor things to you, cool that you are pointing out things but we are there and we don't really need any other pairs of hands to help. Another thing is CLRF or LF - it doesn't matter, just codacy checker for no reason wants everything in LF, it isn't big deal.

2021-03-19 16:31 UTC, merged