Disney+: fix button in Hotstar presence
PreMiD/Presences pull request #3287
Opened 2021-03-19 22:30 UTC by ThaTiemsz

The presence now works for Hotstar again since I was the big dumb.

2021-03-19 22:34 UTC, ririxidev requested changes
Heya @ThaTiemsz,

Could you upload screenshot of working button aka presence in time where it was happening.

Thanks,
ririxi (Contact: mail@ririxi.dev, ririxi#2721)

2021-03-19 22:41 UTC, ThaTiemsz commented
@ririxidev ![image](https://user-images.githubusercontent.com/18150845/111848903-98bbf600-890c-11eb-966d-d52edb0bf3d3.png)

2021-03-19 22:43 UTC, ririxidev approved these changes
LGTM!
*P.S. I more likely wanted screenshot when discord yells if you want to click this link but that's okay too so no worries!*

2021-03-20 13:32 UTC, Bas950 approved these changes

2021-03-20 13:33 UTC, merged