Update Anime Planet
PreMiD/Presences pull request #3296
Opened 2021-03-21 11:08 UTC by SlowLife1661

![image](https://user-images.githubusercontent.com/54318514/111901962-87d6c600-8a6d-11eb-9826-62eb853be109.png)
![image](https://user-images.githubusercontent.com/54318514/111901969-91602e00-8a6d-11eb-82e8-a8210f995cec.png)
![image](https://user-images.githubusercontent.com/54318514/111901905-4ba36580-8a6d-11eb-8837-885ca34d53d0.png)
![image](https://user-images.githubusercontent.com/54318514/111901909-4e05bf80-8a6d-11eb-9b93-863bead4adc6.png)
![image](https://user-images.githubusercontent.com/54318514/111902505-5ca1a600-8a70-11eb-8d13-d5b8016bd336.png)

2021-03-21 17:15 UTC, ririxidev requested changes
Heya @SlowLife1661!
You should check out thing(s) that I requested to change in my review. Please look at them!

Thanks,
**ririxi**. PreMiD Reviewer Team.
Contact: mail@ririxi.dev, ririxi#2721

2021-03-21 17:15 UTC, ririxidev commented on websites/A/Anime Planet/presence.ts
>  }
unecessary kinda. just do ``(document.querySelector('h2.sub > a') as HTMLElement).href``

2021-03-21 17:15 UTC, ririxidev commented on websites/A/Anime Planet/presence.ts
> +      presence.hideSetting(["AnimeDetails", "AnimeState", "MangaDetails", "MangaState"]);
Why you hide settings in this time. I don't understand it.

2021-03-21 17:52 UTC, Bas950 requested changes

2021-03-21 17:52 UTC, Bas950 commented on websites/A/Anime Planet/presence.ts
>            }
HTMLElement should work

2021-03-22 09:15 UTC, SlowLife1661 commented
Now I broke it again LOL I will refork

2021-03-22 09:15 UTC, closed without merging