feat(Prambors Radio): add button and support for the new streaming page
PreMiD/Presences pull request #3331
Opened 2021-03-23 14:18 UTC by Allvaa

![](https://cdn.discordapp.com/attachments/801586332777971742/823920906623647744/unknown.png)
![](https://cdn.discordapp.com/attachments/801586332777971742/823921006132854884/unknown.png)
![](https://cdn.discordapp.com/attachments/801586332777971742/823922674203754536/unknown.png)

2021-03-23 20:36 UTC, ririxidev requested changes
Heya @Allvaa!
You should check out thing(s) that I requested to change in my review. Please look at them!

Thanks,
**ririxi**. PreMiD Reviewer Team.
Contact: mail@ririxi.dev, ririxi#2721

2021-03-23 20:36 UTC, ririxidev commented on websites/P/Prambors Radio/presence.ts
>  const strings = presence.getStrings({
Merge const.

2021-03-23 20:36 UTC, ririxidev commented on websites/P/Prambors Radio/presence.ts
>  let presenceData: PresenceData = {
let -> const

2021-03-24 00:42 UTC, Allvaa commented
done

2021-03-24 07:52 UTC, ririxidev approved these changes
ok, lgtm

2021-03-25 12:54 UTC, Bas950 approved these changes
LGTM

2021-03-25 12:54 UTC, merged