🌎Added WorldHideaway Presence
PreMiD/Presences pull request #3411
Opened 2021-04-02 18:48 UTC by DarkVillager

Resolves #3101 
Added Full Page Functionality.
![wh1](https://user-images.githubusercontent.com/42322979/109419130-3c7c4b00-79cc-11eb-8ac4-68db2c1f8c26.jpg)
![wh2](https://user-images.githubusercontent.com/42322979/109419132-3d14e180-79cc-11eb-86a7-ff7a39f8d4f4.jpg)
![wh3](https://user-images.githubusercontent.com/42322979/109419134-3e460e80-79cc-11eb-9dd8-23a8269fe610.jpg)
![wh4](https://user-images.githubusercontent.com/42322979/109419136-3e460e80-79cc-11eb-802a-467a092ba5d2.jpg)
![wh5](https://user-images.githubusercontent.com/42322979/109419137-3edea500-79cc-11eb-8594-7c9eb868299d.jpg)
![wh6](https://user-images.githubusercontent.com/42322979/109419139-3f773b80-79cc-11eb-9bbf-5949dfb3fa9b.jpg)

2021-04-02 20:10 UTC, Bas950 requested changes

2021-04-02 20:10 UTC, Bas950 commented on websites/W/Worldhideaway/presence.ts
> +    if (host === "www.worldhideaway.com" || host === "worldhideaway.com") {
useless if

2021-04-04 10:25 UTC, Bas950 commented on websites/W/Worldhideaway/presence.ts
> +    presence.setTrayTitle();
should this be an else if?

2021-04-04 10:28 UTC, ririxidev requested changes
Heya @DarkVillager!
You should check out thing(s) that I requested to change in my review. Please look at them!

Thanks,
**ririxi**. PreMiD Reviewer Team.
Contact: mail@ririxi.dev, ririxi#2721

2021-04-04 10:28 UTC, ririxidev commented on websites/W/Worldhideaway/presence.ts
> +    presenceData.startTimestamp = browsingStamp;
```suggestion
  const presenceData: PresenceData = {
    largeImageKey: "logo",
    startTimestamp: browsingStamp
  },
  page = window.location.pathname,
  expage = window.location.href;
```

2021-04-04 10:28 UTC, ririxidev commented on websites/W/Worldhideaway/presence.ts
> +      }
what? XD
```suggestion
      if (!search || search.value === "") {
        presenceData.details = "Viendo Inicio";
      } else {
        presenceData.details = "Buscando:";
        presenceData.state = search.value;
        presenceData.smallImageKey = "searching";
```

2021-04-04 13:47 UTC, ririxidev commented
Lol i forgot ``}`` in last ``if`` fix it.

2021-04-05 08:59 UTC, ririxidev approved these changes
K

2021-04-06 14:57 UTC, StrikerFRFX approved these changes
lgtm

2021-04-06 16:37 UTC, merged