Update Stats Page.
PreMiD/Presences pull request #3417
Opened 2021-04-03 03:40 UTC by calensi

We changed our stats page from stats.boltfm.net > https://radio.boltfm.net/api/nowplaying/2

2021-04-03 10:40 UTC, SlowLife1661 requested changes
Proof of working, bump version

2021-04-04 06:58 UTC, ririxidev requested changes
Okay so what's the problem, you literally deleted live subdomain, button will not work in this presence - if you want you should restore it or I will just strictly delete it from code.

2021-04-04 16:54 UTC, calensi commented
i updated it to a different url, we changed the live.boltfm.net and stats.boltfm.net to a different stats/live url.

2021-04-04 20:46 UTC, ririxidev commented
idc like I said, ``if you want you should restore it or I will just strictly delete it from code.``

2021-04-04 20:57 UTC, calensi commented
as long as the presence still works and what not, its fine by me.

2021-04-04 22:09 UTC, ririxidev commented
It's not for me man. Are you going to argue or I will just close this pr and delete presence for not working properly 🤔

2021-04-04 22:56 UTC, calensi commented
Can my friend make a pr? he did before but he told me his got closed and I had ot type on mine or whatever? I'm new to this, apologies.

2021-04-05 08:59 UTC, closed without merging

2021-04-05 09:01 UTC, ririxidev commented
Obviously.