SyncTube presence
PreMiD/Presences pull request #3421
Opened 2021-04-03 14:05 UTC by N0chteil

Proof:
![Screenshot_293](https://user-images.githubusercontent.com/53608074/113480746-38918c00-9496-11eb-990e-da374e69f635.png)
![Screenshot_294](https://user-images.githubusercontent.com/53608074/113480747-392a2280-9496-11eb-93be-8fcb3b635ee3.png)

Request: #3158

2021-04-04 10:27 UTC, Bas950 requested changes

2021-04-04 10:27 UTC, Bas950 commented on websites/S/SyncTube/dist/metadata.json
> +}
please put privacy mode at the top

2021-04-04 10:27 UTC, Bas950 commented on websites/S/SyncTube/presence.ts
> +        }
remove comment (useless comment)

2021-04-04 10:34 UTC, ririxidev requested changes
Heya @N0chteil!
You should check out thing(s) that I requested to change in my review. Please look at them!

Thanks,
**ririxi**. PreMiD Reviewer Team.
Contact: mail@ririxi.dev, ririxi#2721

2021-04-04 10:34 UTC, ririxidev commented on websites/S/SyncTube/presence.ts
> +  presenceData.details = "Home";
You don't need brackets for one line code.

2021-04-04 10:34 UTC, ririxidev commented on websites/S/SyncTube/presence.ts
> +}
You don't need brackets for one line code.

2021-04-04 10:34 UTC, ririxidev commented on websites/S/SyncTube/presence.ts
> +    presenceData.state = (set_privacy) ? "" : document.querySelector("div.userCount.noselect").textContent;
Never set state/details whatever to "" nor null nor undefined.
```suggestion
    presenceData.details = (set_privacy) ? "In room" : document.querySelector("div.roomName.noselect").textContent;
    if (!set_privacy) presenceData.state = document.querySelector("div.userCount.noselect").textContent;
```

2021-04-04 15:27 UTC, N0chteil commented on websites/S/SyncTube/presence.ts
> +        }
https://github.com/PreMiD/Presences/pull/3412#discussion_r606606723

2021-04-04 20:47 UTC, ririxidev approved these changes
lgtm

2021-04-06 14:58 UTC, StrikerFRFX approved these changes
lgtm

2021-04-06 16:38 UTC, merged