Tesla Presence
PreMiD/Presences pull request #3448
Opened 2021-04-06 20:30 UTC by N0chteil

Proof:
![Screenshot_307](https://user-images.githubusercontent.com/53608074/113774500-ab656600-9727-11eb-9140-bff25440ecd7.png)
![Screenshot_308](https://user-images.githubusercontent.com/53608074/113774502-abfdfc80-9727-11eb-99d9-c67496f30386.png)
![Screenshot_309](https://user-images.githubusercontent.com/53608074/113774505-ac969300-9727-11eb-968c-915952b3e45d.png)

2021-04-06 23:38 UTC, N0chteil commented
Proof for store:
![Screenshot_310](https://user-images.githubusercontent.com/53608074/113790552-e96f8380-9741-11eb-9cff-91122acb017a.png)
![Screenshot_311](https://user-images.githubusercontent.com/53608074/113790558-eaa0b080-9741-11eb-8332-2ee5fcac0c98.png)

2021-04-07 03:58 UTC, Timeraa commented
Elon, where's my Tesla?

2021-04-07 11:06 UTC, Bas950 requested changes

2021-04-07 11:06 UTC, Bas950 commented on websites/T/Tesla/dist/metadata.json
> +  },
```suggestion
  "description": {
    "en": "Tesla is accelerating the world's transition to sustainable energy with electric cars, solar and integrated renewable energy solutions for homes and businesses.",
    "nl": "Tesla versnelt de wereldwijde transitie naar duurzame energie, met elektrische auto's, zonnepanelen en geïntegreerde duurzame energieoplossingen voor woningen en bedrijven."
  },
```

2021-04-07 17:02 UTC, ririxidev approved these changes
It's literally better than most of presences like this lol

2021-04-07 18:07 UTC, Bas950 approved these changes

2021-04-07 18:07 UTC, StrikerFRFX approved these changes
amazing presence

2021-04-07 18:08 UTC, merged