Changing repl.it to replit.com
PreMiD/Presences pull request #3466
Opened 2021-04-08 15:06 UTC by Ashutosh-3601

Recently repl.it changed to replit.com. Presence for repl.it already existed, just changed it to new domain name.

PS: First PR, if any issues pls let me know :)

2021-04-08 20:43 UTC, EncryptedDev requested changes
Hello, look at my review and provide proof of working

2021-04-08 20:43 UTC, EncryptedDev commented on websites/R/Replit/dist/metadata.json
> +  "version": "1.4.5",
bump version

2021-04-09 11:57 UTC, StrikerFRFX requested changes
Hi @Ashutosh-3601,

Unfortunately your changes have been denied with the reason(s) being:

 - In addition to my requested changes, the Presence simply does not work whilst only changing the domain. The DOMs have changed afaik too, so you would have to go through the process of testing and remaking this presence too.

Also, this one hasn't worked for a while. So, I wish you good luck if you're going to fix. Closing this for now.

Thanks, 
**Striker**, PreMiD Reviewer Team
Contact: me@strikerfrfx.dev, Striker#1337

2021-04-09 11:57 UTC, StrikerFRFX commented on websites/R/Replit/presence.ts
> +      largeImageKey: "replit"
If you've changed the `largeImageKey`, you need to change it in the application in the dev portal (which requires you to contact the owner of the presence, which I doubt you have done).

2021-04-09 11:57 UTC, StrikerFRFX commented on websites/R/Replit/dist/metadata.json
> +  "service": "Replit.com",
Service should be `Replit`

2021-04-09 11:57 UTC, closed without merging