:sparkles: Add Dev Community Presence
PreMiD/Presences pull request #3490
Opened 2021-04-10 14:44 UTC by TheGamerzs

![image](https://user-images.githubusercontent.com/44209534/114273660-e0690580-9a12-11eb-93a3-c86780ce82be.png)
![image](https://user-images.githubusercontent.com/44209534/114273679-f080e500-9a12-11eb-88e6-4104efe593c7.png)
![image](https://user-images.githubusercontent.com/44209534/114273847-a5b39d00-9a13-11eb-8707-d60da8e8949e.png)

2021-04-10 14:56 UTC, EncryptedDev commented on websites/D/Dev Community/dist/metadata.json
> +  "buttons": true,
not a thing?

2021-04-10 14:56 UTC, TheGamerzs commented on websites/D/Dev Community/dist/metadata.json
> +  "buttons": true,
Will update

2021-04-10 15:00 UTC, StrikerFRFX requested changes
Hi @TheGamerzs, 
I've requested changes below in my review which you should take a look at 😄 
 -  In addition to the changes requested, please change the folder name and such to match the service name of `DEV Community`

Thanks,
**Striker**, PreMiD Reviewer Team.
Contact: me@strikerfrfx.dev, Striker#1337

2021-04-10 15:07 UTC, TheGamerzs commented on websites/D/Dev Community/dist/metadata.json
> +  "buttons": true,
Read prevoius conversation

2021-04-11 15:28 UTC, StrikerFRFX requested changes
Hi @TheGamerzs, 
I've requested changes below in my review which you should take a look at 😄 
 -  In addition to the service name being changed, pleaee make sure you change the  Discord App name and post a screenshot as proof, thanks 👍 

Thanks,
**Striker**, PreMiD Reviewer Team.
Contact: me@strikerfrfx.dev, Striker#1337

2021-04-11 15:28 UTC, StrikerFRFX commented on websites/D/DEV Community/dist/metadata.json
> +  "service": "Dev Community",
Service name still not changed ._.

2021-04-12 07:32 UTC, ririxidev requested changes
Heya @TheGamerzs!
You should check out thing(s) that I requested to change in my review. Please look at them!

Regards,
**ririxi**. PreMiD Reviewer Team.
Contact: mail@ririxi.dev, ririxi#2721.

2021-04-12 07:32 UTC, ririxidev commented on websites/D/DEV Community/presence.ts
> +      break;
```suggestion
      if (contentStateKey === "play" && endTimestamp > 0)
        presenceData.endTimestamp = endTimestamp;
      else
        delete presenceData.endTimestamp;
      break;
```

2021-04-12 07:32 UTC, ririxidev commented on websites/D/DEV Community/presence.ts
> +      }
```suggestion
      if (contentStateKey === "play" && endTimestamp > 0)
        presenceData.endTimestamp = endTimestamp;
      else
        delete presenceData.endTimestamp;
```

2021-04-12 08:19 UTC, TheGamerzs commented
@StrikerFRFX 
![image](https://user-images.githubusercontent.com/44209534/114363323-30111380-9b70-11eb-83a0-3e9ef34eaf2d.png)

2021-04-12 08:21 UTC, TheGamerzs commented
Fixed
![image](https://user-images.githubusercontent.com/44209534/114363623-7bc3bd00-9b70-11eb-90e4-1338090578fb.png)

2021-04-12 08:33 UTC, ririxidev approved these changes
ok to me, check if it compiles too

2021-04-12 13:14 UTC, Bas950 approved these changes
LGTM

2021-04-12 13:16 UTC, merged

2021-04-12 17:03 UTC, dalhaqq commented
Woah, nice, thanks!