Disney+: add privacy mode
PreMiD/Presences pull request #3502
Opened 2021-04-11 20:12 UTC by ThaTiemsz

Added a privacy mode, also updated the thumbnail.

**Screenshots:**
![image](https://user-images.githubusercontent.com/18150845/114319703-dc241180-9b12-11eb-8afc-d3d8c1b6febe.png)
![image](https://user-images.githubusercontent.com/18150845/114319712-e8a86a00-9b12-11eb-8995-505ce38bc9d9.png)
![image](https://user-images.githubusercontent.com/18150845/114319683-c7e01480-9b12-11eb-9d5d-8e2a608880e3.png)
![image](https://user-images.githubusercontent.com/18150845/114319687-c9114180-9b12-11eb-9197-aa1e3142e8e6.png)
![image](https://user-images.githubusercontent.com/18150845/114319691-cb739b80-9b12-11eb-8344-f03e4eb0c0a0.png)
![image](https://user-images.githubusercontent.com/18150845/114319692-cc0c3200-9b12-11eb-8ef6-6a612d065694.png)
![image](https://user-images.githubusercontent.com/18150845/114319694-cca4c880-9b12-11eb-85d2-c2358cdb4c57.png)

2021-04-12 07:27 UTC, ririxidev requested changes
Heya @ThaTiemsz!
You should check out thing(s) that I requested to change in my review. Please look at them!

Regards,
**ririxi**. PreMiD Reviewer Team.
Contact: mail@ririxi.dev, ririxi#2721.

2021-04-12 07:27 UTC, ririxidev commented on websites/D/Disney+/presence.ts
> +      } else {
```suggestion
      if (privacy)
        data.state = subtitle ? strings.watchingSeries : strings.watchingMovie;
      else {
```

2021-04-12 07:27 UTC, ririxidev commented on websites/D/Disney+/presence.ts
> +        } else {
```suggestion
        if (privacy)
          data.state = subtitle ? strings.watchingSeries : strings.watchingMovie;
        else {
```

2021-04-13 05:14 UTC, ririxidev approved these changes
👍

2021-04-13 13:22 UTC, Bas950 approved these changes
LGTM

2021-04-13 13:23 UTC, merged