[Gogoanime presence] fixed subdomain issue
PreMiD/Presences pull request #3513
Opened 2021-04-12 16:17 UTC by PsychoPast

2021-04-12 18:47 UTC, EncryptedDev commented on websites/G/Gogoanime/presence.ts
> +    domainParts = document.location.hostname.split('.');
prettier?

2021-04-12 19:51 UTC, Bas950 approved these changes
LGTM

2021-04-12 19:51 UTC, Bas950 commented on websites/G/Gogoanime/presence.ts
> +    domainParts = document.location.hostname.split('.');
SeMiD will do it

2021-04-12 20:04 UTC, ririxidev commented
Screenshots pls

2021-04-13 20:52 UTC, PsychoPast commented
> Screenshots pls

sure sorry I forgot
![image](https://user-images.githubusercontent.com/33565739/114619230-f85eb480-9cb2-11eb-9bed-ea57b6aed669.png)
![image](https://user-images.githubusercontent.com/33565739/114619417-38be3280-9cb3-11eb-9558-6c9051d4f40f.png)
![image](https://user-images.githubusercontent.com/33565739/114619519-52f81080-9cb3-11eb-8601-dcb5fa4d9fd1.png)

2021-04-14 12:42 UTC, Bas950 requested changes

2021-04-14 12:42 UTC, Bas950 commented on websites/G/Gogoanime/dist/metadata.json
> +  "version": "2.0.5",
1 version bump is enough.

2021-04-14 20:14 UTC, PsychoPast commented on websites/G/Gogoanime/dist/metadata.json
> +  "version": "2.0.5",
done

2021-04-15 10:15 UTC, ririxidev approved these changes

2021-04-16 09:04 UTC, ririxidev commented
oops something broke with your fork, can you refork it with your changes and create new pull request ty

2021-04-16 09:04 UTC, closed without merging