New Presence "AniCloud"
PreMiD/Presences pull request #3525
Opened 2021-04-13 18:28 UTC by Emijor

![image](https://user-images.githubusercontent.com/55028218/114601633-06520c80-9c96-11eb-8c4f-ae9431f55600.png)

![image](https://user-images.githubusercontent.com/55028218/114601680-1538bf00-9c96-11eb-8f6e-adf426b0c433.png)

![image](https://user-images.githubusercontent.com/55028218/114601726-2386db00-9c96-11eb-933d-f905c205278e.png)

![image](https://user-images.githubusercontent.com/55028218/114602020-6fd21b00-9c96-11eb-9f6b-11b1b9234f1b.png)

![image](https://user-images.githubusercontent.com/55028218/114602060-7c567380-9c96-11eb-8aa0-2dc5453e004c.png)

2021-04-14 02:30 UTC, SlowLife1661 commented on websites/A/Anicloud/presence.ts
> +}
Use built-in method, Presence.getTimestamps()

2021-04-14 02:30 UTC, SlowLife1661 commented on websites/A/Anicloud/iframe.ts
> +});
Delete

2021-04-14 02:30 UTC, SlowLife1661 commented on websites/A/Anicloud/dist/metadata.json
> +    "iframe": true
Delete

2021-04-14 02:30 UTC, SlowLife1661 commented on websites/A/Anicloud/dist/metadata.json
> +    "version": "1.0.1",
1.0.0

2021-04-14 02:30 UTC, SlowLife1661 commented on websites/A/Anicloud/presence.ts
> +);
Delete, you aren't using iframe

2021-04-14 02:30 UTC, SlowLife1661 commented on websites/A/Anicloud/presence.ts
> +played: boolean;
Remove video you aren't using it, you declared it 2 times lol

2021-04-14 02:30 UTC, SlowLife1661 commented on websites/A/Anicloud/presence.ts
> +        label: "Current Anime",
Watch Episode?

2021-04-14 02:39 UTC, SlowLife1661 commented on websites/A/Anicloud/presence.ts
> +    }
```suggestion
  if (video) {
    if (!video.paused) {
      const timestamps = presence.getTimestamps(video.currentTime, video.duration);
      presenceData.endTimestamp = timestamps[1];
    }
```

2021-04-14 11:29 UTC, StrikerFRFX requested changes
Hi @Emijor, 
I've requested changes below in my review which you should take a look at 😄 
 -  In addition to changes that have been suggested by another user, fix Codacy.

Thanks,
**Striker**, PreMiD Reviewer Team.
Contact: me@strikerfrfx.dev, Striker#1337

2021-04-19 17:15 UTC, Emijor commented
wait... if I delete iframe then my presence no longer works. I dont get it

2021-04-19 18:22 UTC, SlowLife1661 commented on websites/A/Anicloud/presence.ts
> +    }
```suggestion
    video = document.querySelector(`video`);
  if (video != null) {
    played = video.currentTime != 0;
    duration = video.duration;
    current = video.currentTime;
    paused = video.paused;
  }
  if (played) {
    if (!paused) {
      const timestamps = presence.getTimestamps(current, duration);
      presenceData.endTimestamp = timestamps[1];
    }
```

2021-04-21 14:26 UTC, Bas950 approved these changes
Domain is just old enough lmao xD

2021-04-21 17:44 UTC, ririxidev requested changes

2021-04-21 17:44 UTC, ririxidev commented on websites/A/Anicloud/iframe.ts
> +    hostname == `playtube.ws`
```suggestion
    hostname === "voe.sx" ||
    hostname === "streamtape.com" ||
    hostname === "playtube.ws"
```

2021-04-21 17:44 UTC, ririxidev commented on websites/A/Anicloud/presence.ts
> +
dont need blank space here?

2021-04-21 19:23 UTC, Emijor commented
like this?

2021-04-21 20:59 UTC, ririxidev requested changes

2021-04-21 20:59 UTC, ririxidev commented on websites/A/Anicloud/presence.ts
> +});
```suggestion
const presence = new Presence({
  clientId: `830517484472762408`
}),
  strings = presence.getStrings({
  play: "presence.playback.playing",
  pause: "presence.playback.paused"
});
```

2021-04-21 21:35 UTC, Emijor commented on websites/A/Anicloud/presence.ts
> +});
oh my bad

2021-04-22 06:04 UTC, ririxidev approved these changes

2021-04-22 13:22 UTC, Bas950 approved these changes

2021-04-23 09:47 UTC, merged