Bunpro presence
PreMiD/Presences pull request #3557
Opened 2021-04-20 17:10 UTC by JulianCDC

## Dashboard
![Screenshot_20210420_190528](https://user-images.githubusercontent.com/32849409/115436527-62271300-a20b-11eb-9532-c19acedf6e6c.png)
![Screenshot_20210420_190407](https://user-images.githubusercontent.com/32849409/115436380-360b9200-a20b-11eb-9bdf-d6caa1b2107e.png)

## Lessons
![Screenshot_20210420_190619](https://user-images.githubusercontent.com/32849409/115436637-7ff47800-a20b-11eb-8e70-dc9ad9790cea.png)
![Screenshot_20210420_190706](https://user-images.githubusercontent.com/32849409/115436743-9c90b000-a20b-11eb-975d-d512c9f53248.png)

## Reviews
![Screenshot_20210420_190749](https://user-images.githubusercontent.com/32849409/115436833-b7fbbb00-a20b-11eb-9d50-efcc46bb1ac9.png)
![Screenshot_20210420_190806](https://user-images.githubusercontent.com/32849409/115436858-be8a3280-a20b-11eb-8b46-eded78418abc.png)

## Cram
![Screenshot_20210420_190858](https://user-images.githubusercontent.com/32849409/115436945-df528800-a20b-11eb-999d-5ab2c54791e4.png)
![Screenshot_20210420_190914](https://user-images.githubusercontent.com/32849409/115436977-e7122c80-a20b-11eb-9516-adea33d00073.png)

## Grammar
![Screenshot_20210420_190938](https://user-images.githubusercontent.com/32849409/115437024-f5f8df00-a20b-11eb-9193-9405b2ff06e4.png)
![Screenshot_20210420_190949](https://user-images.githubusercontent.com/32849409/115437047-fbeec000-a20b-11eb-8363-7e2255ffed0b.png)

2021-04-21 06:03 UTC, ririxidev requested changes

2021-04-21 06:03 UTC, ririxidev commented on websites/B/Bunpro/presence.ts
> +          }
```suggestion
          state = hintText ? `${hintText} (${SRSLevel})` : SRSLevel
```

2021-04-21 06:03 UTC, ririxidev commented on websites/B/Bunpro/presence.ts
> +  }
```suggestion
  if (details) data.details = details;
  if (state) data.state = state;
```

2021-04-21 06:03 UTC, ririxidev commented on websites/B/Bunpro/presence.ts
> +    }
```suggestion
    if (!smallImageText) smallImageText = `Level ${level}`
```

2021-04-21 06:03 UTC, ririxidev commented on websites/B/Bunpro/presence.ts
> +  }
```suggestion
  if (smallImageText) data.smallImageText = smallImageText;
```

2021-04-21 06:03 UTC, ririxidev commented on websites/B/Bunpro/presence.ts
> +  }
check my comment about it above.

2021-04-21 14:09 UTC, ririxidev requested changes

2021-04-21 14:09 UTC, ririxidev commented on websites/B/Bunpro/presence.ts
> +      this.elapsed = Date.now();
Huh? It was okay. I just meant that you don't need this timer function at all because you can just replace startTimestamp :///

2021-04-21 14:30 UTC, Bas950 requested changes

2021-04-21 14:30 UTC, Bas950 commented on websites/B/Bunpro/presence.ts
> +    };
```suggestion
    data: PresenceData = {
      largeImageKey
    };
```

2021-04-21 14:30 UTC, Bas950 commented on websites/B/Bunpro/presence.ts
> +    };
That should still work

2021-04-22 13:21 UTC, Bas950 requested changes

2021-04-22 13:21 UTC, Bas950 commented on websites/B/Bunpro/presence.ts
> +  const level: number = getLevelInHeader();
```suggestion
  const { pathname } = window.location,
    data: PresenceData = {
      largeImageKey
    },
    level: number = getLevelInHeader();
    
  let details: string,
    state: string,
    smallImageText: string,
    startTimestamp: number;
```

2021-04-22 20:50 UTC, Bas950 approved these changes

2021-04-23 23:07 UTC, ririxidev requested changes
Fix deepscan

2021-04-24 19:43 UTC, ririxidev approved these changes

2021-04-25 12:01 UTC, Bas950 approved these changes

2021-04-25 12:02 UTC, merged