🇳🇱 Translated All Descriptions to Dutch (Nederlands) 🇳🇱
PreMiD/Presences pull request #3570
Opened 2021-04-24 10:57 UTC by DarkVillager

🇳🇱 Translated All Descriptions to Dutch (Nederlands) 🇳🇱

2021-04-24 11:38 UTC, Bas950 requested changes

2021-04-24 11:38 UTC, ririxidev requested changes
squash commits

2021-04-24 11:38 UTC, Bas950 commented on websites/A/AnimeDao/dist/metadata.json
> +    "ga_IE": "Féach ",
Please delete that translation for us since that doesnt seem correct, I know its not related to the dutch one but thats not good..

2021-04-24 11:38 UTC, Bas950 commented on websites/A/atomicradio/dist/metadata.json
>      "atomicradio.eu",
bump version

2021-04-24 11:38 UTC, Bas950 commented on websites/F/Fandom/dist/metadata.json
> +}
bump version

2021-04-24 11:38 UTC, Bas950 commented on websites/G/Gamepedia/dist/metadata.json
> +
bump version, remove extra enter at the end

2021-04-24 11:38 UTC, Bas950 commented on websites/G/Glimesh/dist/metadata.json
>      {
bump version

2021-04-24 11:38 UTC, Bas950 commented on websites/J/JAVX/dist/metadata.json
> +  "iFrameRegExp": "([a-z0-9-]+[.])*ijav.tv/play/([a-z0-9-])+",
undo

2021-04-24 11:38 UTC, Bas950 commented on websites/M/MDN Web Docs/dist/metadata.json
>    },
```suggestion
    "nl": "De webdocumenten van MDN, hier vind je JS-documenten en meer..."
  },
```

2021-04-24 11:38 UTC, Bas950 commented on websites/M/MLPOL/dist/metadata.json
>    },
```suggestion
    "nl": "Welkom bij het Mongoolse politieke paardenfluisterenforum, ook bekend als /mlpol/"
  },
```

2021-04-24 11:38 UTC, Bas950 commented on websites/M/Meus Animes/dist/metadata.json
>    },
Wat? kijkanimaties?

2021-04-24 11:38 UTC, Bas950 commented on websites/T/Trackmania.io/dist/metadata.json
>  }
bump version

2021-04-25 11:51 UTC, Bas950 requested changes
Fix merge conflicts

2021-04-26 12:52 UTC, Bas950 requested changes
Just like @ririxidev said, please squash commits

2021-04-26 13:02 UTC, DarkVillager commented
> Just like @ririxidev said, please squash commits

HOW

2021-04-26 13:03 UTC, ririxidev commented
Internet?

2021-04-27 09:34 UTC, StrikerFRFX requested changes
Squash commits, use this as reference? https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

2021-04-27 13:54 UTC, ririxidev commented
another example: https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec

2021-05-03 10:35 UTC, ririxidev commented
No response from pull request author. Closing.

2021-05-03 10:35 UTC, closed without merging