Added Dsc Jobs
PreMiD/Presences pull request #3572
Opened 2021-04-24 13:30 UTC by AhmedSabry957

https://user-images.githubusercontent.com/63425800/115960247-8edf7100-a510-11eb-91e7-17484a673963.png
https://user-images.githubusercontent.com/63425800/115960230-7b340a80-a510-11eb-8837-a487824f9c7a.png

2021-04-24 16:29 UTC, ririxidev requested changes
also add all subpages on site.

2021-04-24 16:29 UTC, ririxidev commented on websites/D/Dscjobs.org/presence.ts
> +    presenceData.state = "FaQ Page";
there is nothing like `FaQ`. There is only `FAQ`

2021-04-24 16:29 UTC, ririxidev commented on websites/D/Dscjobs.org/presence.ts
> +      ];
Ehhh, kinda unnecessary

2021-04-24 16:29 UTC, ririxidev commented on websites/D/Dscjobs.org/presence.ts
> +    presenceData.state = `${username}`;
```suggestion
    presenceData.state = username;
```

2021-04-24 22:21 UTC, AhmedSabry957 commented
fixed

2021-04-24 23:20 UTC, ririxidev commented
If fixed why you close it? Lmfao.

2021-04-24 23:22 UTC, AhmedSabry957 commented
@ririxidev My friend will reopen it I have little exp in github, but I will try and reopen

2021-04-24 23:23 UTC, ririxidev commented
I mean if you want someone else to make a pull request, go ahead but close this one.

2021-04-24 23:25 UTC, AhmedSabry957 commented
> I mean if you want someone else to make a pull request, go ahead but close this one.

try and see if everything is really fixed, and if so approve it

2021-04-24 23:39 UTC, AhmedSabry957 commented
so?

2021-04-25 09:35 UTC, ririxidev requested changes
Add all subpages that you can find on website and 
![image](https://user-images.githubusercontent.com/9348108/115988480-42507000-a5ba-11eb-8ea9-5da296c0b176.png)
Also we are not reviewing 24/7 so please wait when we don't respond...

2021-04-25 12:04 UTC, Bas950 requested changes

2021-04-25 12:04 UTC, Bas950 commented on websites/D/Dscjobs.org/dist/metadata.json
> +    "service": "Dsc Jobs",
Folder name and service name must be the same

2021-04-25 12:59 UTC, AhmedSabry957 commented
fixed

2021-04-25 16:13 UTC, AhmedSabry957 commented
anything else?

2021-04-25 17:54 UTC, ririxidev commented
![image](https://user-images.githubusercontent.com/9348108/116003815-04763a80-a600-11eb-8b01-cd25cb1a6d0b.png)

2021-04-25 20:50 UTC, AhmedSabry957 commented
you mean I should remove?

2021-04-25 21:09 UTC, AhmedSabry957 reviewed
Fixed

2021-04-26 05:58 UTC, ririxidev commented
It's not fixed. Man. I think you still don't understand me. 
It's not only about this button. I said to add all subpages that are available on this site to your presence. If you will still not understand, unfortunately I will just close this pull request.

2021-04-26 12:55 UTC, Bas950 commented on websites/D/Dscjobs.org/dist/metadata.json
> +    "service": "Dscjobs.org",
You should just change the folder name and service to "DscJobs" as that's their official name

2021-04-26 15:49 UTC, closed without merging

2021-04-26 15:49 UTC, AhmedSabry957 commented
I will get someone expert do this