[Genius] fix: lyrics
PreMiD/Presences pull request #3573
Opened 2021-04-24 16:08 UTC by mlunax

#3185
![20210424_180736](https://user-images.githubusercontent.com/11018865/115965166-010f8000-a528-11eb-9249-f87a6c6d46f5.png)

2021-04-24 16:26 UTC, ririxidev submitted a review, later dismissed

2021-04-25 11:56 UTC, Bas950 requested changes
For me the old ones worked, some regions have different elements...

2021-04-25 11:56 UTC, Bas950 commented on websites/G/Genius/presence.ts
> +  } else if (document.querySelector("div[class*='SongPageGrid'") !== null) {
```suggestion
  } else if (document.querySelector("div[class*='SongPageGrid'") !== null || document.querySelector(".song_body-lyrics") !== null) {
```

2021-04-25 11:56 UTC, Bas950 commented on websites/G/Genius/presence.ts
>          .textContent.trim(),
```suggestion
        .querySelector("h1[class*='SongHeader__Title-sc'")
        ?.textContent.trim() || document
        .querySelector("h1.header_with_cover_art-primary_info-title")
        ?.textContent.trim(),
```

2021-04-25 11:56 UTC, Bas950 commented on websites/G/Genius/presence.ts
>          .textContent.trim();
```suggestion
        .querySelector("a[class*='SongHeader__Artist'")
        ?.textContent.trim() || document
        .querySelector("a.header_with_cover_art-primary_info-primary_artist")
        ?.textContent.trim();
```

2021-04-26 09:56 UTC, ririxidev approved these changes

2021-04-26 12:56 UTC, Bas950 approved these changes

2021-04-26 12:56 UTC, merged