[KissAsian] fix and small refactor
PreMiD/Presences pull request #3580
Opened 2021-04-25 04:46 UTC by mlunax

![1](https://chibi.lunarcloud.xyz/qcolkr.png)
![2](https://chibi.lunarcloud.xyz/1na0sl.png)
![3](https://chibi.lunarcloud.xyz/ii8o0z.png)
![4](https://chibi.lunarcloud.xyz/qcolkr.png)

2021-04-25 09:31 UTC, ririxidev requested changes
also move `startTimestamp` to `presenceData` object

2021-04-25 09:31 UTC, ririxidev commented on websites/K/KissAsian/presence.ts
>  }
yeah use `getTimestamps` function that is inside `Presence` class.

2021-04-25 09:31 UTC, ririxidev commented on websites/K/KissAsian/presence.ts
> +      const timestamps = getTimestamps(Math.floor(currentTime), Math.floor(duration));
like above

2021-04-25 09:31 UTC, ririxidev commented on websites/K/KissAsian/presence.ts
>          presenceData.startTimestamp = timestamps[0];
don't need to set startTimestamp

2021-04-25 12:04 UTC, Bas950 requested changes
And changes Ririxi mentioned

2021-04-25 12:04 UTC, Bas950 commented on websites/K/KissAsian/dist/metadata.json
> +  "url": "kissasian.la",
```suggestion
  "url": ["kissasian.la", "kissasian.li"],
```

2021-04-25 17:55 UTC, ririxidev approved these changes

2021-04-26 12:54 UTC, Bas950 requested changes
And changes Ririxi mentioned

2021-04-26 12:54 UTC, Bas950 commented on websites/K/KissAsian/presence.ts
> +  if (document.location.hostname == "kissasian.la") {
Remove this "if" case or make it work for both domains.

2021-04-28 05:21 UTC, ririxidev approved these changes

2021-04-28 12:31 UTC, Bas950 approved these changes

2021-04-28 12:31 UTC, merged