New Presence Score Saber
PreMiD/Presences pull request #3596
Opened 2021-04-27 10:38 UTC by joerkig

New Presence for [Scoresaber.com](https://Scoresaber.com) Please let me know of any issues
![lxdvbb](https://user-images.githubusercontent.com/44418429/116228002-0867a100-a755-11eb-8154-3a9f9b0fefcb.png)
![0a4r95](https://user-images.githubusercontent.com/44418429/116228003-09003780-a755-11eb-8921-ea0d8505ffca.png)
![pu0zv6](https://user-images.githubusercontent.com/44418429/116228004-09003780-a755-11eb-8d32-f32ad00adfa5.png)
![mrjs09](https://user-images.githubusercontent.com/44418429/116228005-0998ce00-a755-11eb-8b9f-d731949897f8.png)

2021-04-27 11:35 UTC, joerkig commented
Sorry about closing and reopening I kinda panicked for no reason ;-;

2021-04-27 13:38 UTC, ririxidev requested changes
could you add what difficulty user is watching currently?

2021-04-27 13:38 UTC, ririxidev commented on websites/S/Score Saber/presence.ts
> +  }
you don't need brackets here
```suggestion
  if (!time) delete presenceData.startTimestamp;

  if (!buttons) delete presenceData.buttons;
```

2021-04-27 14:58 UTC, Bas950 requested changes

2021-04-27 14:58 UTC, Bas950 commented on websites/S/Score Saber/dist/metadata.json
> +    "readLogs": false,
```suggestion
```
It's false by default

2021-04-27 14:58 UTC, Bas950 commented on websites/S/Score Saber/presence.ts
> +    else if (document.location.href.includes("?country="))
```suggestion
    if (document.location.href.includes("?search=")) {
      presenceData.details = "Searching Users";
      presenceData.state = document
      .querySelector("input.input")
      .getAttribute("value");
    } else if (document.location.href.includes("?country="))
```

2021-04-27 14:58 UTC, Bas950 commented on websites/S/Score Saber/presence.ts
> +    else
```suggestion
    if (document.location.pathname.includes("/leaderboard/")) {
      presenceData.details = "Viewing Leaderboard";
      presenceData.state = document
      .querySelector("h4 > a")
      .textContent;  
      presenceData.smallImageKey = document
      .querySelector("li.is-active > a > span")
      .textContent.toLowerCase().replace("+","_");
      presenceData.smallImageText = document
      .querySelector("li.is-active > a > span")
      .textContent;
      presenceData.buttons = [
          {
            label: "View Page",
            url: document.location.href
          }
        ];
    } else
```

2021-04-27 14:58 UTC, Bas950 commented on websites/S/Score Saber/presence.ts
> +  else if (document.location.pathname.includes("/u/"))
```suggestion
  else if (document.location.pathname.includes("/ranking/request")) {
    presenceData.details = "Viewing Rank Request";
    presenceData.state = document
    .querySelector("h4.title.is-5.songInfos > a")
    .textContent;
    presenceData.smallImageKey = document
    .querySelector("li.is-active > a > span")
    .textContent.toLowerCase().replace("+","_");
    presenceData.smallImageText = document
    .querySelector("li.is-active > a > span")
    .textContent;
    presenceData.buttons = [
      {
        label: "View Page",
        url: document.location.href
      }
    ];
  } else if (document.location.pathname.includes("/u/")) {
```

2021-04-27 14:58 UTC, Bas950 commented on websites/S/Score Saber/presence.ts
> +      presenceData.details = "Browsing Leaderboards";
```suggestion
    presenceData.details = "Viewing User";
    presenceData.state = document
    .querySelector("h5.title.is-5 > a")
    .textContent;
    presenceData.buttons = [
      {
        label: "View Page",
        url: document.location.href
      }
    ];
  } else if (document.location.pathname == ("/")) {
    if (document.location.href.includes("?search=")) {
      presenceData.details = "Searching Leaderboards";
      presenceData.state = document
      .querySelector("input.input")
      .getAttribute("value");
    } else presenceData.details = "Browsing Leaderboards";
  }
```

2021-04-27 15:49 UTC, ririxidev approved these changes
i guess lgtm

2021-04-28 12:30 UTC, Bas950 approved these changes

2021-04-28 12:30 UTC, merged