Support for Snipes Belgium & Switzerland | SNIPES presence
PreMiD/Presences pull request #3599
Opened 2021-04-27 15:20 UTC by N0chteil

Proof:
![Screenshot_345](https://user-images.githubusercontent.com/53608074/116266464-d6b60080-a77b-11eb-9b9e-bb87ca020e01.png)
![Screenshot_347](https://user-images.githubusercontent.com/53608074/116266482-d74e9700-a77b-11eb-9e37-5d27e665fe98.png)
![Screenshot_346](https://user-images.githubusercontent.com/53608074/116266475-d74e9700-a77b-11eb-85a3-6ac70870c3e3.png)

2021-04-28 05:30 UTC, ririxidev requested changes
use regex in metadata and why you broke this prettified code 😩

2021-04-28 05:30 UTC, ririxidev commented on websites/S/Snipes/presence.ts
> +      }
```suggestion
      smallimage = document.location.hostname === "www.snipesusa.com" ? "usa" : "de"
```

2021-04-28 12:40 UTC, Bas950 approved these changes
Should probs just use a regex...

2021-04-28 13:52 UTC, ririxidev requested changes
use regex like i said.

2021-04-28 14:33 UTC, SlowLife1661 commented on websites/S/Snipes/dist/metadata.json
> +  "regExp": "REGEXP",
Make it yourself if you don't want to use this

```suggestion
  "regExp": "www[.]snipes[.]([a-z]+)",
```

2021-04-28 20:22 UTC, Bas950 requested changes
Should probs just use a regex...

2021-04-28 20:22 UTC, Bas950 commented on websites/S/Snipes/dist/metadata.json
> +  "regExp": "www[.]snipes[.]([a-z]+)",
```suggestion
  "regExp": "www[.]snipes(usa)?[.]([a-z]+)",
```

2021-04-28 20:34 UTC, Bas950 approved these changes

2021-04-29 06:08 UTC, ririxidev approved these changes

2021-04-29 06:09 UTC, merged