[Odysee] Create presence for odysee.com
PreMiD/Presences pull request #3620
Opened 2021-04-30 19:37 UTC by mlunax

![1](https://chibi.lunarcloud.xyz/yokf72.jpg)
![2](https://chibi.lunarcloud.xyz/qia7c4.jpg)
![3](https://chibi.lunarcloud.xyz/2my8ci.jpg)

2021-05-01 01:45 UTC, SlowLife1661 commented on websites/O/Odysee/presence.ts
> +    }
Never null

2021-05-01 01:47 UTC, SlowLife1661 commented on websites/O/Odysee/dist/metadata.json
> +  "thumbnail": "https://odysee.com/public/img/odysee.png",
Upload to imgur

2021-05-01 01:47 UTC, SlowLife1661 commented on websites/O/Odysee/presence.ts
> +  };
You can just put this inside so you don't have to bother `delete x`

2021-05-01 12:01 UTC, ririxidev requested changes

2021-05-01 12:01 UTC, ririxidev commented on websites/O/Odysee/presence.ts
> +      delete presenceData.state;
oh man what is this?

2021-05-01 12:01 UTC, ririxidev commented on websites/O/Odysee/presence.ts
> +  if (document.location.hostname === "odysee.com") {
dont need this check

2021-05-01 16:14 UTC, ririxidev requested changes

2021-05-01 16:14 UTC, ririxidev commented on websites/O/Odysee/presence.ts
> +            delete presenceData.startTimestamp;
You don't set `startTimestamp` anywhere so you don't need to delete it.

2021-05-01 16:14 UTC, ririxidev commented on websites/O/Odysee/presence.ts
> +              label: "Watch video",
```suggestion
              label: "Watch Video",
```

2021-05-01 16:14 UTC, ririxidev commented on websites/O/Odysee/presence.ts
> +              label: "View author's channel",
```suggestion
              label: "View Channel",
```

2021-05-01 16:27 UTC, ririxidev approved these changes

2021-05-02 12:23 UTC, Bas950 requested changes

2021-05-02 12:23 UTC, Bas950 commented on websites/O/Odysee/dist/metadata.json
> +  "thumbnail": "https://i.imgur.com/NQjEv5C.png",
thumbnail should be a promotional banner or a screenshot of the website homepage.

2021-05-02 15:44 UTC, ririxidev approved these changes

2021-05-02 19:41 UTC, Bas950 approved these changes

2021-05-02 19:41 UTC, merged