:sparkles: Dice Presence
PreMiD/Presences pull request #3621
Opened 2021-04-30 20:35 UTC by TheGamerzs

![image](https://user-images.githubusercontent.com/44209534/116751311-bdbb8280-a9fb-11eb-93dc-631079144896.png)
![image](https://user-images.githubusercontent.com/44209534/116751355-d035bc00-a9fb-11eb-9c79-c003032aab6d.png)
![image](https://user-images.githubusercontent.com/44209534/116751422-e80d4000-a9fb-11eb-8401-426dd46f3dc4.png)

Will comment when logo is fixed

2021-04-30 20:58 UTC, TheGamerzs commented
![image](https://user-images.githubusercontent.com/44209534/116753452-04f74280-a9ff-11eb-87cd-bf581ae51e62.png)
![image](https://user-images.githubusercontent.com/44209534/116753527-20624d80-a9ff-11eb-826f-c0f8cb3877e6.png)

2021-05-01 01:53 UTC, SlowLife1661 commented on websites/D/Dice Sweden/presence.ts
> +      presenceData.buttons = [{ label: "Home", url: "https://www.dice.se" }];
Not allowed ( buttons )

2021-05-01 01:53 UTC, SlowLife1661 commented on websites/D/Dice Sweden/presence.ts
> +  }
Never null?

2021-05-01 11:42 UTC, TheGamerzs commented on websites/D/Dice Sweden/presence.ts
> +  }
Removed defualt

2021-05-01 11:43 UTC, TheGamerzs commented on websites/D/Dice Sweden/presence.ts
> +      presenceData.buttons = [{ label: "Home", url: "https://www.dice.se" }];
Removed

2021-05-01 16:16 UTC, Bas950 requested changes

2021-05-01 16:16 UTC, Bas950 commented on websites/D/Dice Sweden/presence.ts
> +}
you dont need functions for this if its only used once...

2021-05-02 09:05 UTC, ririxidev requested changes
move `startTimestamp` to `presenceData` object.

2021-05-02 09:45 UTC, ririxidev requested changes

2021-05-02 09:45 UTC, ririxidev commented on websites/D/Dice Sweden/dist/metadata.json
> +      "title": "Show Time Elapsed",
```suggestion
      "title": "Show Elapsed Time",
```
😉

2021-05-02 12:05 UTC, ririxidev approved these changes

2021-05-02 12:30 UTC, Bas950 approved these changes

2021-05-02 12:31 UTC, merged