Added Dutch Translations For Every Presence
PreMiD/Presences pull request #3656
Opened 2021-05-04 10:17 UTC by DarkVillager

I hope its good this time :)

2021-05-04 17:10 UTC, Bas950 requested changes

2021-05-04 17:10 UTC, Bas950 commented on websites/S/Scantrad/dist/metadata.json
>    "version": "1.0.2",
bump version

2021-05-04 17:10 UTC, Bas950 commented on websites/S/Scantrad/presence.ts
>      presenceData.smallImageKey = "reading";
??

2021-05-04 17:10 UTC, Bas950 commented on websites/S/Snipes/dist/metadata.json
>      }
??

2021-05-04 17:10 UTC, Bas950 commented on websites/S/Snipes/dist/metadata.json
> +  "version": "1.0.2",
??

2021-05-04 17:10 UTC, Bas950 commented on websites/T/Trackmania.io/dist/metadata.json
> +  "version": "1.0.3",
??

2021-05-04 17:10 UTC, Bas950 commented on websites/T/TuMangaOnline/dist/metadata.json
>    "color": "#3366cc",
???

2021-05-04 17:10 UTC, Bas950 commented on websites/T/TugaStrikes/dist/metadata.json
> +    "nl": "TugaStrikes is een gamingcommunity die is opgericht in 2017 en zich richt op CS: GO"
```suggestion
    "nl": "TugaStrikes is een gamingcommunity die is opgericht in 2017 en zich richt op CS:GO"
```

2021-05-04 17:10 UTC, Bas950 commented on websites/V/Viki/dist/metadata.json
> +  "version": "1.3.7",
?

2021-05-04 17:10 UTC, Bas950 commented on websites/W/WoolyPooly/dist/metadata.json
>    "version": "1.1.2",
bump version

2021-05-04 17:10 UTC, Bas950 commented on websites/Y/YouTube/dist/metadata.json
>    "logo": "https://i.imgur.com/C9ZEmge.png",
?

2021-05-04 17:49 UTC, ririxidev commented
also resolve conflicts

2021-05-05 10:25 UTC, ririxidev commented
and I wanna tell you that by this you lost 8 files because of updating your fork.

2021-05-05 12:37 UTC, DarkVillager commented
> and I wanna tell you that by this you lost 8 files because of updating your fork.

wdym?

2021-05-05 14:29 UTC, ririxidev commented
Your first commit:
![image](https://user-images.githubusercontent.com/9348108/117157572-fc1bbd80-adbe-11eb-8b98-3b72978c9010.png)
Now: 
![image](https://user-images.githubusercontent.com/9348108/117157601-00e07180-adbf-11eb-8dc9-e766fa374281.png)

2021-05-05 14:35 UTC, DarkVillager commented
> Your first commit:
> ![image](https://user-images.githubusercontent.com/9348108/117157572-fc1bbd80-adbe-11eb-8b98-3b72978c9010.png)
> Now:
> ![image](https://user-images.githubusercontent.com/9348108/117157601-00e07180-adbf-11eb-8dc9-e766fa374281.png)
> Well it is not 629 but still 2 files.

Thats intentional. Some presences were already translated and I by accident added them.

2021-05-06 11:52 UTC, ririxidev commented
You are missing 16 translations in your fork:
![image](https://user-images.githubusercontent.com/9348108/117293873-3e520700-ae72-11eb-9022-bf0b1518db59.png) - it's screenshot from me running translator on your fork

2021-05-07 20:04 UTC, DarkVillager commented
oh will fix asap

2021-05-08 11:31 UTC, ririxidev commented
![image](https://user-images.githubusercontent.com/9348108/117537512-b6026c00-b001-11eb-801f-dcade4fde81e.png)

2021-05-08 17:12 UTC, Bas950 requested changes

2021-05-08 17:12 UTC, Bas950 commented on websites/S/Scantrad/presence.ts
> -});
???????????????

2021-05-08 17:12 UTC, Bas950 commented on websites/S/Snipes/dist/metadata.json
>    "regExp": "www[.]snipes(usa)?[.]([a-z]+)",
bump version

2021-05-08 17:12 UTC, Bas950 commented on websites/T/TuMangaOnline/dist/metadata.json
>    "thumbnail": "https://i.imgur.com/SKXMHAG.png",
undo

2021-05-08 17:12 UTC, Bas950 commented on websites/V/Viki/dist/metadata.json
> +  "version": "1.3.10",
undo

2021-05-08 17:12 UTC, Bas950 commented on websites/Y/YouTube/dist/metadata.json
> +}
undo

2021-05-11 10:41 UTC, ririxidev reviewed
waiting till bas will check it again XD
Also next time do it faster and you are still missing translations but do them later
![image](https://user-images.githubusercontent.com/9348108/117802922-5355de00-b256-11eb-981b-551945b66eb1.png)

2021-05-11 14:02 UTC, Bas950 commented on websites/Y/YouTube/dist/metadata.json
> +}
did not solve the issue...

2021-05-11 14:17 UTC, Bas950 approved these changes

2021-05-11 14:17 UTC, merged