Added Read Manga Online | readm.org Presence
PreMiD/Presences pull request #3663
Opened 2021-05-05 13:06 UTC by MareGraphics

resolve #3424 
Screenshots:
![image](https://user-images.githubusercontent.com/13592797/117145456-79413580-adb3-11eb-80cf-a3a628e68d99.png)
![image](https://user-images.githubusercontent.com/13592797/117145460-7b0af900-adb3-11eb-8181-42e2d8a3a793.png)
![image](https://user-images.githubusercontent.com/13592797/117145468-7c3c2600-adb3-11eb-9a79-cf2b5bbec73f.png)
![image](https://user-images.githubusercontent.com/13592797/117145474-7d6d5300-adb3-11eb-9452-5545c6d287ea.png)

2021-05-05 19:13 UTC, Bas950 submitted a review, later dismissed

2021-05-06 11:41 UTC, ririxidev requested changes

2021-05-06 11:41 UTC, ririxidev commented on websites/R/Read Manga Online/presence.ts
> +      data.details = "Viewing: ";
```suggestion
      data.details = "Looking at";
```

2021-05-06 11:41 UTC, ririxidev commented on websites/R/Read Manga Online/presence.ts
> +      data.details = "Viewing: ";
```suggestion
      data.details = "Viewing:";
```

2021-05-06 11:41 UTC, ririxidev commented on websites/R/Read Manga Online/presence.ts
> +      data.details = "Viewing: ";
```suggestion
      data.details = "Looking at";
```

2021-05-06 11:41 UTC, ririxidev commented on websites/R/Read Manga Online/presence.ts
> +      data.details = "Viewing: ";
```suggestion
      data.details = "Looking at";
```

2021-05-06 11:41 UTC, ririxidev commented on websites/R/Read Manga Online/presence.ts
> +      data.details = "Viewing: ";
```suggestion
      data.details = "Viewing:";
```

2021-05-06 11:41 UTC, ririxidev commented on websites/R/Read Manga Online/presence.ts
> +      data.details = "Viewing: ";
```suggestion
      data.details = "Looking at";
```

2021-05-06 11:41 UTC, ririxidev commented on websites/R/Read Manga Online/presence.ts
> +      data.state = "Ongoing Manga";
```suggestion
      data.state = "Ongoing Manga List";
```

2021-05-06 11:41 UTC, ririxidev commented on websites/R/Read Manga Online/presence.ts
> +      data.details = "Viewing: ";
```suggestion
      data.details = "Looking at";
```

2021-05-06 11:41 UTC, ririxidev commented on websites/R/Read Manga Online/presence.ts
> +      data.state = "Completed Manga";
```suggestion
      data.state = "Completed Manga List";
```

2021-05-06 11:41 UTC, ririxidev commented on websites/R/Read Manga Online/presence.ts
> +      data.details = "Viewing: ";
```suggestion
      data.details = "Viewing:";
```

2021-05-06 11:41 UTC, ririxidev commented on websites/R/Read Manga Online/presence.ts
> +      data.details = "Viewing: ";
```suggestion
      data.details = "Viewing:";
```

2021-05-06 11:41 UTC, ririxidev commented on websites/R/Read Manga Online/presence.ts
> +      data.details = "Viewing collection: ";
```suggestion
      data.details = "Viewing collection:";
```

2021-05-06 11:41 UTC, ririxidev commented on websites/R/Read Manga Online/presence.ts
> +      data.details = "Searching: ";
```suggestion
      data.details = "Searching for:";
```

2021-05-06 11:41 UTC, ririxidev commented on websites/R/Read Manga Online/presence.ts
> +      data.details = "Browsing category: ";
```suggestion
      data.details = "Browsing category:";
```

2021-05-06 11:41 UTC, ririxidev commented on websites/R/Read Manga Online/presence.ts
> +      data.details = "Viewing: ";
```suggestion
      data.details = "Reading:";
```

2021-05-06 11:41 UTC, ririxidev commented on websites/R/Read Manga Online/presence.ts
> +      data.details = "Viewing their: ";
```suggestion
      data.details = "Viewing their:";
```

2021-05-12 17:24 UTC, Bas950 approved these changes

2021-05-12 20:47 UTC, ririxidev approved these changes

2021-05-12 20:47 UTC, merged