Added CNN presence
PreMiD/Presences pull request #3665
Opened 2021-05-05 18:39 UTC by N0chteil

Proof:
![Screenshot_366](https://user-images.githubusercontent.com/53608074/117192281-cf2cd200-ade1-11eb-99c0-b840b5bc419f.png)
![Screenshot_367](https://user-images.githubusercontent.com/53608074/117192284-cfc56880-ade1-11eb-94c1-d5e457f9b65b.png)
![Screenshot_368](https://user-images.githubusercontent.com/53608074/117192286-d05dff00-ade1-11eb-9906-a6da0dca0612.png)
![Screenshot_369](https://user-images.githubusercontent.com/53608074/117192287-d05dff00-ade1-11eb-93be-b985fd10eae7.png)

2021-05-06 11:43 UTC, ririxidev requested changes

2021-05-06 11:43 UTC, ririxidev commented on websites/C/CNN/presence.ts
> +          label: `View Category`,
```suggestion
          label: "View Category",
```

2021-05-06 11:43 UTC, ririxidev commented on websites/C/CNN/presence.ts
> +          label: `View Article`,
```suggestion
          label: "View Article",
```

2021-05-06 11:43 UTC, ririxidev commented on websites/C/CNN/presence.ts
> +          label: `View Profile`,
```suggestion
          label: "View Profile",
```

2021-05-06 11:43 UTC, ririxidev commented on websites/C/CNN/presence.ts
> +            label: `View Special`,
```suggestion
            label: "View Special",
```

2021-05-06 11:43 UTC, ririxidev commented on websites/C/CNN/presence.ts
> +            label: `View Results`,
```suggestion
            label: "View Results",
```

2021-05-08 09:00 UTC, ririxidev approved these changes

2021-05-08 16:02 UTC, Bas950 approved these changes

2021-05-08 16:04 UTC, merged