Fixed Anime Digital Network Presence
PreMiD/Presences pull request #3669
Opened 2021-05-06 10:01 UTC by DarkVillager

Resolves #3622
![image](https://user-images.githubusercontent.com/42322979/117280220-aac50a00-ae62-11eb-9d3f-701c91bbced0.png)

2021-05-06 11:49 UTC, ririxidev requested changes
if you are making changes already please delete on line `30`, `startTimestamp: timestamps[0]`.

2021-05-06 11:49 UTC, ririxidev commented on websites/A/AnimeDigitalNetwork/presence.ts
>          details: "Browsing...",
well I think it should be:
```suggestion
        details: "Looking at",
```

2021-05-06 12:17 UTC, ririxidev commented on websites/A/AnimeDigitalNetwork/presence.ts
> +        details: "Looking at...",
well I literally requested changes without these 3 dots. Remove them.
and im not `riri` ty

2021-05-07 08:52 UTC, ririxidev approved these changes

2021-05-08 15:57 UTC, Bas950 approved these changes

2021-05-08 16:08 UTC, merged