update neontv.co.nz
PreMiD/Presences pull request #3673
Opened 2021-05-07 01:24 UTC by kety-folf

fix code so it gets name when viewing show info page

2021-05-07 08:53 UTC, ririxidev requested changes
please upload screenshots of working presence

2021-05-07 10:26 UTC, kety-folf commented
![image](https://user-images.githubusercontent.com/48892500/117436491-261ddd00-af83-11eb-95ab-d408bba0803e.png)
![Capture](https://user-images.githubusercontent.com/48892500/117436514-2c13be00-af83-11eb-8118-e32c5335070a.PNG)
images of bot working

2021-05-07 14:42 UTC, ririxidev approved these changes

2021-05-08 15:58 UTC, Bas950 approved these changes

2021-05-08 16:02 UTC, ririxidev commented
@Mergifyio update

2021-05-08 16:03 UTC, merged