Updated Scantrad presence
PreMiD/Presences pull request #3684
Opened 2021-05-08 16:31 UTC by Kozou4ever

Hey! I edited the Scantrad presence since they changed their DOM
I took the opportunity to add some features: 
-Buttons added to read the chapter the user is reading
-Forum pages added

I also write the presence in french since it is a french website and most of the users are french. 
Let me know if there are some changes to make.

2021-05-08 16:43 UTC, ririxidev requested changes

2021-05-08 16:43 UTC, ririxidev commented on websites/S/Scantrad/presence.ts
> +        };
```javascript
string.charAt(0).toUpperCase() + string.slice(1);
```
?

2021-05-08 16:47 UTC, ririxidev commented
and resolve conflicts

2021-05-10 09:38 UTC, ririxidev commented
conflicts again xD

2021-05-10 09:46 UTC, ririxidev commented
![image](https://user-images.githubusercontent.com/9348108/117640419-4f0dc000-b185-11eb-99a8-c396fcc2db03.png)
bc semid was probably doing stuff again

2021-05-10 09:56 UTC, ririxidev commented
Okay do this; Close this pull request - do re-fork so you will have all up-to-date and then do changes to your presence 👍

2021-05-10 10:01 UTC, Kozou4ever commented
Ok I google what were those conflicts and how to resolve them, and I think it's good

2021-05-10 10:21 UTC, ririxidev approved these changes

2021-05-12 12:32 UTC, Bas950 requested changes
Fix merging conflicts

2021-05-12 17:04 UTC, Bas950 approved these changes

2021-05-12 17:04 UTC, merged