WidgetStyle Presence.
PreMiD/Presences pull request #3686
Opened 2021-05-08 22:07 UTC by DiscordAnaxes

Here

2021-05-09 08:57 UTC, SlowLife1661 commented on websites/W/WidgetStyle/dist/metadata.json
> +    "thumbnail": "https://cdn.tixte.com/uploads/cdn.anaxes.xyz/kof75u24d9a.png",
Upload to imgur

2021-05-09 09:03 UTC, SlowLife1661 commented on websites/W/WidgetStyle/presence.ts
> +  };
put `startTimestamp` here and remove others

2021-05-09 09:09 UTC, SlowLife1661 commented on websites/W/WidgetStyle/dist/metadata.json
> +    "service": "Widgetstyle",
Must be same as folder name

2021-05-09 09:28 UTC, SlowLife1661 commented on websites/W/WidgetStyle/presence.ts
> +presenceData.startTimestamp = browsingStamp;
```suggestion
  const presenceData: PresenceData = {
    largeImageKey: "logo",
    startTimestamp: browsingStamp
  }; 
```

2021-05-09 10:30 UTC, ririxidev commented
Yeah um, for now - presence is qualified as low quality becuase of very low amount of DOM Readings etc - technically this presence  is static.

2021-05-09 11:00 UTC, DiscordAnaxes commented
> Yeah um, for now - presence is qualified as low quality becuase of very low amount of DOM Readings etc - technically this presence is static.

Oh alright.

2021-05-10 09:39 UTC, ririxidev requested changes

2021-05-10 09:39 UTC, ririxidev commented on websites/W/WidgetStyle/dist/metadata.json
> +    ],
```suggestion
    "tags": [
      "discord",
      "widgetstyle",
      "widget"
    ],
```

2021-05-10 09:39 UTC, ririxidev commented on websites/W/WidgetStyle/presence.ts
> +          label: "🌐 View Page",
```suggestion
          label: "View Page",
```

2021-05-10 09:39 UTC, ririxidev commented on websites/W/WidgetStyle/presence.ts
> +          label: "🌐 View Page",
```suggestion
          label: "View Page",
```

2021-05-10 09:39 UTC, ririxidev commented on websites/W/WidgetStyle/presence.ts
> +          label: `🌐 View ${user.innerText}'s Page`,
```suggestion
          label: `View ${user.innerText}'s Page`,
```

2021-05-10 10:13 UTC, ririxidev commented on websites/W/WidgetStyle/presence.ts
> +    if (document.location.pathname == "/") {
```suggestion
    if (document.location.pathname === "/") {
```

2021-05-10 10:18 UTC, ririxidev approved these changes

2021-05-12 12:29 UTC, Bas950 requested changes

2021-05-12 12:29 UTC, Bas950 commented on websites/W/WidgetStyle/presence.ts
> +      ];
buttons to the homepage are not allowed.

2021-05-12 12:29 UTC, Bas950 commented on websites/W/WidgetStyle/tsconfig.json
> +
```suggestion
  }
```

2021-05-12 12:29 UTC, Bas950 commented on websites/W/WidgetStyle/dist/metadata.json
> +    }
```suggestion
    "description": {
      "nl": "Een moderne blik op verouderde Discord Widgets.",
      "fr": "Un look moderne sur les widgets Discord obsolètes.",
      "tr": "Güncelliğini yitirmiş Discord widget'larına modern bir görünüm.",
      "ja_JP": "古いDiscordウィジェットのモダンな外観。",
      "zh_CN": "过时的Discord小部件的现代外观。",
      "en": "A modern look on outdated Discord Widgets."
    }
```

2021-05-12 12:29 UTC, Bas950 commented on websites/W/WidgetStyle/dist/metadata.json
> +    "logo": "https://i.imgur.com/5nAdPH8.png",
514x512 xD please just make it square...

2021-05-13 08:08 UTC, ririxidev approved these changes

2021-05-13 10:59 UTC, Bas950 approved these changes

2021-05-13 10:59 UTC, merged