Upgrade Emby presence & fix #3703
PreMiD/Presences pull request #3704
Opened 2021-05-10 17:28 UTC by alexbcberio

Synced Emby presence with latest Jellyfin features:

- Added TS types
- Fixed media medadata obtention
- Migrated to Presence helpers to get timestamps and display logs
- Added settings to show and hide timestamps, both general and for media playback

Screenshot proofs:

![at home](https://user-images.githubusercontent.com/22194879/117698890-7fc11a00-b1c4-11eb-97a1-f70bf50a40eb.png)
![browsing movie details](https://user-images.githubusercontent.com/22194879/117698932-8b144580-b1c4-11eb-982d-964344e9313f.png)
![playing back movie](https://user-images.githubusercontent.com/22194879/117698980-98313480-b1c4-11eb-809d-edfc7729b022.png)
![playing back song](https://user-images.githubusercontent.com/22194879/117699220-daf30c80-b1c4-11eb-9ca2-8c3838c45907.png)

![presence settings](https://user-images.githubusercontent.com/22194879/117699040-a7b07d80-b1c4-11eb-9bd7-9104a3221caa.png)
Disabled media timestamps
![playing back movie](https://user-images.githubusercontent.com/22194879/117699082-b434d600-b1c4-11eb-814b-456767cf1cad.png)
![playing back song](https://user-images.githubusercontent.com/22194879/117699182-d2023b00-b1c4-11eb-9ba3-9776e3eeddb3.png)

2021-05-10 19:47 UTC, ririxidev requested changes

2021-05-10 19:47 UTC, ririxidev commented on websites/E/Emby/presence.ts
> +      }
```suggestion
      } else delete presenceData.endTimestamp;
```

2021-05-10 19:47 UTC, ririxidev commented on websites/E/Emby/presence.ts
>    } else {
```suggestion
  } else if (typeof data === "string") return;
    else {
```

2021-05-10 21:17 UTC, alexbcberio commented
I've force pushed as I made a commit by mistake by pressing on the "Commit suggestion", I'm not very used to GitHub web

2021-05-10 22:21 UTC, ririxidev approved these changes

2021-05-12 12:36 UTC, Bas950 approved these changes

2021-05-12 12:36 UTC, merged