Updated Apple Music presence
PreMiD/Presences pull request #3718
Opened 2021-05-12 19:05 UTC by N0chteil

Proof:
![Screenshot_384](https://user-images.githubusercontent.com/53608074/118030379-80dd7d00-b365-11eb-925d-00377478fbcf.png)

(changed old logo to new logo https://github.com/PreMiD/Presences/issues/3060)

2021-05-13 08:11 UTC, ririxidev requested changes

2021-05-13 08:11 UTC, ririxidev commented on websites/A/Apple Music/presence.ts
> +    clientId: "842112189618978897"
Did you even ask creator of this presence that you can change this ID?

2021-05-14 13:27 UTC, ririxidev submitted a review, later dismissed

2021-05-14 16:57 UTC, Bas950 requested changes

2021-05-14 16:57 UTC, Bas950 commented on websites/A/Apple Music/dist/metadata.json
> +  "logo": "https://i.imgur.com/qDEpPUg.png",
logo needs to be at least 512x512

2021-05-14 17:47 UTC, ririxidev approved these changes

2021-05-15 20:19 UTC, Bas950 approved these changes

2021-05-15 20:19 UTC, merged