Added German Translation
PreMiD/Presences pull request #3723
Opened 2021-05-12 23:59 UTC by InfoBlock

2021-05-13 08:11 UTC, ririxidev requested changes

2021-05-13 08:11 UTC, ririxidev commented on websites/U/UpBeatRadio/dist/metadata.json
> +    "de": "UpBeat ist ein werbefreies, Community betriebenes online radio.
```suggestion
    "de": "UpBeat ist ein werbefreies, Community betriebenes online radio."
```

2021-05-14 13:23 UTC, N0chteil commented on websites/U/UpBeatRadio/dist/metadata.json
> +    "de": "UpBeat ist ein werbefreies, Community betriebenes online radio.
```suggestion
    "de": "UpBeat ist ein werbefreies, Community betriebenes online Radio."
```
Radio = noun = capitalize

2021-05-17 13:24 UTC, ririxidev commented
No response from pull request author.

2021-05-17 13:24 UTC, closed without merging