Add AnimeJunkies Presence
PreMiD/Presences pull request #3732
Opened 2021-05-14 15:19 UTC by RedstoneZockt

Hey, i reviewed my Code and It should be a better code quality now.

2021-05-14 17:03 UTC, Bas950 requested changes

2021-05-14 17:03 UTC, Bas950 commented on websites/A/AnimeJunkies/dist/metadata.json
> +    },
```suggestion
    "description": {
      "en": "The community website about anime!",
      "de": "Die Communitywebseite über Anime!",
      "nl": "De communitywebsite over anime!"
    },
```
Official description

2021-05-14 17:03 UTC, Bas950 commented on websites/A/AnimeJunkies/dist/metadata.json
> +    "readLogs": false
```suggestion
    "category": "anime"
```

2021-05-14 17:03 UTC, Bas950 commented on websites/A/AnimeJunkies/presence.ts
> +  };
dont set it to "", just dont set it at all at start...

2021-05-14 17:03 UTC, Bas950 commented on websites/A/AnimeJunkies/presence.ts
> +  };
just use 1 PresenceData object...

2021-05-15 20:21 UTC, Bas950 requested changes
Add some more things to the presence...

2021-05-15 20:21 UTC, Bas950 commented on websites/A/AnimeJunkies/presence.ts
> +      presenceData.state = "";
Dont set empty state

2021-05-15 20:47 UTC, RedstoneZockt commented
The main of the website are news posts (over 400), They where automaticly displayed by the title.
There are other thinks to display in the future, but the sub domain website is not finished yet and is in closed beta. so i can't add them now to the presence.

If it finished, il add more thinks.

2021-05-17 13:25 UTC, ririxidev commented
For now; this presence is not qualified since it doesn't do a lot. Sorry.

2021-05-17 13:25 UTC, closed without merging

2021-05-17 18:41 UTC, RedstoneZockt commented
Okay I will work on it.