Add "Listen Now" button to YouTube Music Presence
PreMiD/Presences pull request #3733
Opened 2021-05-14 17:03 UTC by Atharv-Attri

This PR seeks to add a "Listen Now" Button in the Youtube Music presence. 

Before:
![image](https://user-images.githubusercontent.com/48738128/118303475-58a36a80-b49a-11eb-9f9e-40260137142d.png)

After:
![image](https://user-images.githubusercontent.com/48738128/118303403-41fd1380-b49a-11eb-8785-dcb236a89a56.png)

The button will take you the song that the person is currently listening to. 

This PR was co-authored by @plskz.

2021-05-14 17:05 UTC, Bas950 requested changes
bump version

2021-05-14 17:05 UTC, Bas950 commented on websites/Y/YouTube Music/dist/metadata.json
> +  ],
this is not enough to add yourself as contributor, and not your friend either..

2021-05-14 17:05 UTC, Bas950 commented on websites/Y/YouTube Music/presence.ts
> +            label: "Listen now",
```suggestion
            label: "Listen along!",
```

2021-05-14 17:24 UTC, Atharv-Attri commented
What should I bump the version to? I'm not entirely sure how big of a change this would count as

2021-05-15 11:25 UTC, Bas950 commented
> What should I bump the version to? I'm not entirely sure how big of a change this would count as

Just bump the last number once

2021-05-15 18:49 UTC, Atharv-Attri commented
Done!

2021-05-15 20:28 UTC, Bas950 submitted a review, later dismissed

2021-05-15 20:28 UTC, ririxidev commented on websites/Y/YouTube Music/presence.ts
> +            label: "Listen along!",
```suggestion
            label: "Listen Along",
```
looks better :////

2021-05-15 20:29 UTC, ririxidev approved these changes

2021-05-15 20:29 UTC, Bas950 approved these changes

2021-05-15 20:30 UTC, merged