Added Wizarding World presence
PreMiD/Presences pull request #3754
Opened 2021-05-17 07:00 UTC by N0chteil

Proof:
![Screenshot_391](https://user-images.githubusercontent.com/53608074/118445131-5a656c00-b6ee-11eb-8ba8-5be15e64bd68.png)
![Screenshot_392](https://user-images.githubusercontent.com/53608074/118445137-5afe0280-b6ee-11eb-98cb-3ec1b2a2a93b.png)
![Screenshot_393](https://user-images.githubusercontent.com/53608074/118445138-5b969900-b6ee-11eb-8697-1f085302bd6a.png)
![Screenshot_394](https://user-images.githubusercontent.com/53608074/118445140-5b969900-b6ee-11eb-9e37-5cb96bedc77a.png)
![Screenshot_395](https://user-images.githubusercontent.com/53608074/118445143-5b969900-b6ee-11eb-9219-06fad163cff3.png)

2021-05-17 13:27 UTC, ririxidev requested changes

2021-05-17 13:27 UTC, ririxidev commented on websites/W/Wizarding World/presence.ts
> +              label: `View Collection`,
```suggestion
              label: "View Collection",
```

2021-05-17 16:59 UTC, ririxidev submitted a review, later dismissed

2021-05-17 19:07 UTC, Bas950 requested changes

2021-05-17 19:07 UTC, Bas950 commented on websites/W/Wizarding World/dist/metadata.json
> +  ],
Add some better tags? 
Just "potter"?

2021-05-17 19:07 UTC, Bas950 commented on websites/W/Wizarding World/dist/metadata.json
> +  },
```suggestion
  "description": {
    "en": "The Wizarding World is a fantasy media franchise and shared fictional universe centred on a series of films, based on the Harry Potter novel series by J. K. Rowling.",
    "nl": "The Wizarding World is een fantasy-mediafranchise en gedeeld fictief universum rond een reeks films, gebaseerd op de Harry Potter-serie van J. K. Rowling."
  },
```

2021-05-18 08:39 UTC, ririxidev approved these changes

2021-05-18 18:30 UTC, Bas950 approved these changes

2021-05-18 18:30 UTC, merged