Added dsc.gg presence.
PreMiD/Presences pull request #3755
Opened 2021-05-17 08:24 UTC by DiscordAnaxes

2021-05-17 11:42 UTC, N0chteil requested changes
---

2021-05-17 11:45 UTC, N0chteil requested changes
Some suggestions

2021-05-17 11:45 UTC, N0chteil commented on websites/D/Dsc.gg/presence.ts
> +      presenceData.details = `Viewing 👤 dashboard`;
Use **"** instead of **`**

2021-05-17 11:45 UTC, N0chteil commented on websites/D/Dsc.gg/presence.ts
> +    } else if (document.location.pathname === ("/dashboard")) {
```code
document.location.pathname === "/dashboard"
```
You don't need the brackets

2021-05-17 11:45 UTC, N0chteil commented on websites/D/Dsc.gg/presence.ts
> +      presenceData.details = `Viewing 💻 developer page`;
Use **"** instead of **`**

2021-05-17 11:45 UTC, N0chteil commented on websites/D/Dsc.gg/presence.ts
> +    } else if (document.location.pathname === ("/developers/about")) {
```code
document.location.pathname === "/developers/about"
```
You don't need the brackets

2021-05-17 11:45 UTC, N0chteil commented on websites/D/Dsc.gg/presence.ts
> +      presenceData.details = `Viewing ✨ about page`;
Use **"** instead of **`**

2021-05-17 11:45 UTC, N0chteil commented on websites/D/Dsc.gg/presence.ts
> +      presenceData.details = `Viewing 💎 premium page`;
Use **"** instead of **`**

2021-05-17 11:45 UTC, N0chteil commented on websites/D/Dsc.gg/presence.ts
> +    } else if (document.location.pathname === ("/about")) {
```code
document.location.pathname === "/about"
```
You don't need the brackets

2021-05-17 19:05 UTC, Bas950 commented on websites/D/Dsc.gg/dist/metadata.json
> +    }
```suggestion
    "description": {
      "en": "Free vanity links for you discord servers, bots and templates!",
      "nl": "Gratis vanity-links voor je Discord servers, bots en templates!"
    }
```

2021-05-17 19:05 UTC, Bas950 commented on websites/D/Dsc.gg/presence.ts
> +          url: `https://dsc.gg/${link[1]}`
```suggestion
          label: "Visit Link",
          url: `https://dsc.gg/${link[1]}`
```

2021-05-18 11:41 UTC, ririxidev commented
Sorry but: 
![image](https://user-images.githubusercontent.com/9348108/118645094-ca531f80-b7de-11eb-8457-c49011054a63.png)

2021-05-18 11:41 UTC, closed without merging

2021-05-18 11:55 UTC, DiscordAnaxes commented
> Sorry but:
> ![image](https://user-images.githubusercontent.com/9348108/118645094-ca531f80-b7de-11eb-8457-c49011054a63.png)

Like the discords.com presence, would you like me to talk with the owner, regarding when the domain was bought and how many visitors they receive?

2021-05-18 11:56 UTC, ririxidev commented
I mean domain is 1 year old so i dont think they bought it but ye :/

2021-05-18 12:01 UTC, DiscordAnaxes commented
> I mean domain is 1 year old so i dont think they bought it but ye :/

I can confirm that the domain is more than a year old and owned by the service:
[!image](https://cdn.anaxes.xyz/kotzjj5299a)

2021-05-18 12:02 UTC, ririxidev commented
You didnt have to, I already told you that I know that this domain is 1 year old...

2021-05-18 12:03 UTC, DiscordAnaxes commented
> You didnt have to, I already told you that I know that this domain is 1 year old...

However, you stated, "I don't think they bought it".

2021-05-18 12:04 UTC, ririxidev commented
I meant that I didn't think that they bought it from someone else

2021-05-18 12:04 UTC, DiscordAnaxes commented
> I meant that I didn't think that they bought it from someone else

Oh ok. My bad.