Added Daily Wire presence
PreMiD/Presences pull request #3758
Opened 2021-05-17 09:48 UTC by N0chteil

Proof:
![Screenshot_397](https://user-images.githubusercontent.com/53608074/118469115-b5568d80-b705-11eb-960c-5bf943785ff1.png)
![Screenshot_398](https://user-images.githubusercontent.com/53608074/118469121-b5ef2400-b705-11eb-8bce-8a684c9c92fa.png)
![Screenshot_399](https://user-images.githubusercontent.com/53608074/118469123-b5ef2400-b705-11eb-820c-a48a9a5f5c0e.png)
![Screenshot_400](https://user-images.githubusercontent.com/53608074/118469124-b5ef2400-b705-11eb-8d7f-6d220723b9b9.png)

https://github.com/PreMiD/Presences/issues/3743

2021-05-17 13:30 UTC, ririxidev requested changes
support for watching episodes etc?

2021-05-17 14:26 UTC, N0chteil commented
> support for watching episodes etc?

I have no subscription

2021-05-17 17:02 UTC, ririxidev approved these changes
Well, fine.

2021-05-17 19:11 UTC, Bas950 requested changes

2021-05-17 19:11 UTC, Bas950 commented on websites/D/Daily Wire/dist/metadata.json
> +  ],
Add some more tags not just "cars"

2021-05-17 19:11 UTC, Bas950 commented on websites/D/Daily Wire/dist/metadata.json
> +  "version": "1.0.6",
```suggestion
  "version": "1.0.0",
```

2021-05-17 19:11 UTC, Bas950 commented on websites/D/Daily Wire/dist/metadata.json
> +  },
```suggestion
  "description": {
    "en": "The Daily Wire is an American conservative news website and media company founded in 2015 by political commentator Ben Shapiro and director Jeremy Boreing. The site has been criticised for promoting misinformation.",
    "nl": "The Daily Wire is een Amerikaanse conservatieve nieuwswebsite en mediabedrijf opgericht in 2015 door politiek commentator Ben Shapiro en regisseur Jeremy Boreing. De site is gekritiseerd vanwege het promoten van valse informatie."
  },
```

2021-05-17 19:11 UTC, Bas950 commented on websites/D/Daily Wire/presence.ts
> +          url: window.location.href
```suggestion
          label: "Watch Show",
          url: window.location.href
```

2021-05-17 19:11 UTC, Bas950 commented on websites/D/Daily Wire/presence.ts
> +          url: window.location.href
```suggestion
          label: "Watch Episode",
          url: window.location.href
```

2021-05-17 19:11 UTC, Bas950 commented on websites/D/Daily Wire/presence.ts
> +          url: window.location.href
```suggestion
          label: "Read Article",
          url: window.location.href
```

2021-05-18 08:38 UTC, ririxidev approved these changes

2021-05-18 18:30 UTC, Bas950 approved these changes

2021-05-18 18:30 UTC, merged