Fixed URL problems for Overleaf Presence
PreMiD/Presences pull request #3779
Opened 2021-05-20 12:29 UTC by Enevevet

The language is not that important in the Presence since the language is just the display language for Overleaf and doesn't change the rest. The Presence just needed to be triggered on some specific subdomains.

2021-05-20 12:30 UTC, ririxidev commented on websites/O/Overleaf/dist/metadata.json
> +  ],
Just make regexp 🤦

2021-05-21 22:19 UTC, Bas950 requested changes

2021-05-21 22:19 UTC, Bas950 commented on websites/O/Overleaf/dist/metadata.json
> +  ],
```suggestion
  "url": "www.overleaf.com",
  "regExp": "([a-z0-9-]+[.])*overleaf[.]com[/]",
```

2021-05-22 10:31 UTC, ririxidev approved these changes

2021-05-23 00:33 UTC, Bas950 approved these changes

2021-05-23 00:33 UTC, merged