New Presence: ZombsRoyale.io
PreMiD/Presences pull request #3786
Opened 2021-05-21 19:09 UTC by MrBartusek

![image](https://user-images.githubusercontent.com/23432278/119186670-b62a4f00-ba78-11eb-8200-33b87eafa062.png)
![image](https://user-images.githubusercontent.com/23432278/119186688-bb879980-ba78-11eb-96d7-26e99e151148.png)
![image](https://user-images.githubusercontent.com/23432278/119186727-c6422e80-ba78-11eb-8d01-2bffdeb9b952.png)

2021-05-21 19:58 UTC, MrBartusek commented
False-positive from codacy

2021-05-21 19:59 UTC, ririxidev commented on websites/Z/ZombsRoyale.io/presence.ts
> +  currentGameState = await this.getPageletiable("game.currentGameState");
yeah well it isn't loool. it should be
```suggestion
  currentGameState = await getPageletiable("game.currentGameState");
```

2021-05-21 22:24 UTC, Bas950 submitted a review, later dismissed

2021-05-22 09:14 UTC, ririxidev requested changes
isn't there more to show instead of only `viewing, buying` etc? also check type in ifs too
`==` -> `===`

2021-05-22 11:09 UTC, MrBartusek commented
> isn't there more to show instead of only `viewing, buying` etc? also check type in ifs too
> `==` -> `===`

I searched a bit but it seems like there isn't anything else that `game.currentGameState`

2021-05-22 11:16 UTC, ririxidev requested changes
and run prettier over it

2021-05-22 11:16 UTC, ririxidev commented on websites/Z/ZombsRoyale.io/presence.ts
> +  }
[Start a Codeblock's Curly Braces on the Same Line](https://github.com/goldbergyoni/nodebestpractices#-33-start-a-codeblocks-curly-braces-on-the-same-line)

2021-05-22 11:16 UTC, ririxidev commented on websites/Z/ZombsRoyale.io/presence.ts
> +  }
```suggestion
  } else presence.error("Unknown state: " + currentGameState);
```

2021-05-22 11:16 UTC, ririxidev commented on websites/Z/ZombsRoyale.io/presence.ts
> +  } else if (currentGameState === "Countdown" || currentGameState === "Lobby") {
```suggestion
  if (currentGameState === "loading" || currentGameState === "UiLoadingOverlay")
    presenceData.details = "Loading...";
  else if (currentGameState === "MainMenu")
    presenceData.details = "Lurking in main menu";
  else if (currentGameState === "Cosmetics" || currentGameState === "UiCosmeticSelectorOverlay")
    presenceData.details = "Viewing cosmetics";
  else if (currentGameState === "Profile")
    presenceData.details = "Viewing their profile";
  else if (currentGameState === "Shop" || currentGameState === "UiPreviewPackOverlay")
    presenceData.details = "Browsing Shop";
  else if (currentGameState === "Friends" || currentGameState === "UiFriendAddOverlay")
    presenceData.details = "Viewing their friends";
  else if (currentGameState === "Leaderboards")
    presenceData.details = "Browsing leaderboards";
  else if (currentGameState === "UiLoginOverlay")
    presenceData.details = "Loging in";
  else if (currentGameState === "UiSettingsOverlay")
    presenceData.details = "Changing settings";
  else if (currentGameState === "UiSeasonPurchaseOverlay")
    presenceData.details = "Buying a Battle Pass";
  else if (currentGameState.startsWith("UiSeason") || currentGameState === "UiPreviewItemOverlay")
    presenceData.details = "Viewing Battle Pass";
  else if (currentGameState === "UiChallengesOverlay")
    presenceData.details = "Viewing challenges";
  else if (currentGameState === "UiBuyGemsOverlay")
    presenceData.details = "Buying gems";
  else if (currentGameState === "VideoAd")
    presenceData.details = "Watching video ad";
  else if (currentGameState === "Countdown" || currentGameState === "Lobby") {
```

2021-05-22 11:41 UTC, MrBartusek commented on websites/Z/ZombsRoyale.io/presence.ts
> +  } else if (currentGameState === "Countdown" || currentGameState === "Lobby") {
Not sure what changed?

2021-05-22 11:42 UTC, ririxidev commented on websites/Z/ZombsRoyale.io/presence.ts
> +  } else if (currentGameState === "Countdown" || currentGameState === "Lobby") {
nothing. code style 😛

2021-05-22 11:44 UTC, MrBartusek commented on websites/Z/ZombsRoyale.io/presence.ts
> +  }
`presence.error` is doubled now?

2021-05-22 11:44 UTC, ririxidev commented on websites/Z/ZombsRoyale.io/presence.ts
> +  }
how that's doubled

2021-05-23 00:33 UTC, Bas950 approved these changes

2021-05-23 07:55 UTC, ririxidev approved these changes

2021-05-23 07:55 UTC, merged