Update metadata.json
PreMiD/Presences pull request #3826
Opened 2021-05-26 04:57 UTC by GreenScreen410

Change old messenger logo

2021-05-26 06:10 UTC, ririxidev requested changes
version must be bumped - logo must be updated on discord developers portal.

2021-05-26 09:16 UTC, Bas950 commented on websites/M/Messenger/dist/metadata.json
>    "version": "1.1.5",
```suggestion
  "version": "1.1.6",
```

2021-05-26 09:17 UTC, Bas950 commented
> version must be bumped - logo must be updated on discord developers portal.

![image](https://user-images.githubusercontent.com/34792838/119635363-e6287800-be13-11eb-8628-0cde8cec1e7d.png)
Done on dev portal.

2021-05-30 00:19 UTC, ririxidev commented
No response from pull request author :/

2021-05-30 00:19 UTC, closed without merging