Add CodeChef presences
PreMiD/Presences pull request #3828
Opened 2021-05-26 18:20 UTC by AvinashDhillor

Proof:

<details>
  <summary> </summary>
</details>
<details>
  <summary> </summary>
</details>
<details>
  <summary> </summary>
</details>
<details>
  <summary> </summary>
</details>
<details>
  <summary> </summary>
</details>
<details>
  <summary> </summary>
</details>
<details>
  <summary> </summary>
</details>
<details>
  <summary> </summary>
</details>
<details>
  <summary> </summary>
</details>
<details>
  <summary> </summary>
</details>
<details>
  <summary> </summary>
</details>

2021-05-27 15:52 UTC, ririxidev requested changes
Please check my review 😃

2021-05-27 15:52 UTC, ririxidev commented on websites/C/CodeChef/presence.ts
> +    domain = location.host;
```suggestion
    domain = location.host.split(".");
```

2021-05-27 15:52 UTC, ririxidev commented on websites/C/CodeChef/presence.ts
> +  if (domain.includes("blog")) {
``switch(domain[0])`` :)
please change it to this

2021-05-27 15:52 UTC, ririxidev commented on websites/C/CodeChef/presence.ts
> +    presenceData.smallImageText = "coding";
```suggestion
```

2021-05-27 15:52 UTC, ririxidev commented on websites/C/CodeChef/presence.ts
> +      presenceData.smallImageText = "Reading";
```suggestion
```

2021-05-27 15:52 UTC, ririxidev commented on websites/C/CodeChef/presence.ts
> +      presenceData.smallImageText = "Reading";
```suggestion
```

2021-05-27 15:52 UTC, ririxidev commented on websites/C/CodeChef/presence.ts
> +    presenceData.smallImageText = "Reading";
```suggestion
```

2021-05-27 15:52 UTC, ririxidev commented on websites/C/CodeChef/presence.ts
> +        presenceData.smallImageText = "coding";
```suggestion
```

2021-05-27 15:52 UTC, ririxidev commented on websites/C/CodeChef/dist/metadata.json
> +    "$schema": "https://schemas.premid.app/metadata/1.3",
```suggestion
    "$schema": "https://schemas.premid.app/metadata/1.4",
```

2021-05-27 19:59 UTC, ririxidev commented
umm sorry for that but could you update your fork because when I was doing pr I broke something 😓

2021-05-28 13:00 UTC, AvinashDhillor commented
okay

2021-05-28 15:45 UTC, ririxidev approved these changes
thanks :)

2021-05-28 16:11 UTC, Bas950 approved these changes

2021-05-28 17:47 UTC, merged