Added discord.style presence.
PreMiD/Presences pull request #3831
Opened 2021-05-27 11:43 UTC by DiscordAnaxes

2021-05-28 16:06 UTC, Bas950 submitted a review, later dismissed

2021-05-28 17:46 UTC, ririxidev commented
Mr. @DiscordAnaxes,
please update your fork and update your presence regarding new ESLint rules.

Regards,
ririxi, mail@ririxi.dev

2021-05-28 21:59 UTC, ririxidev requested changes

2021-05-28 21:59 UTC, ririxidev commented on websites/D/Discord.style/presence.ts
> +  const tag = document.location.href.split("tag=")[1].split("&")[0],
```suggestion
const [tag] = document.location.href.split("tag=")[1].split("&"),
```

2021-05-29 12:19 UTC, Bas950 approved these changes

2021-05-29 12:27 UTC, ririxidev approved these changes

2021-05-29 12:29 UTC, Bas950 approved these changes

2021-05-29 12:30 UTC, merged