Presence for Westmanga
PreMiD/Presences pull request #3846
Opened 2021-05-30 09:02 UTC by mhazm

Continuing from #3840 

I am fix no imgur link in both `logo` & `thumbnail` and trying fix [ESLint issues](https://i.imgur.com/d5k1C7V.png)
I am trying pull this presence again..

Please help me with an explanation

I added a few things to my presence this time:
- Presence on searching by Genre
- Presence will change depending on the type of manga type being viewed
Like a `Manga`, `Manhua`, `Manhwa`
- Change state presence data on reading manga with `Chapter on reading` of `Chapter end`

_In discussions with the Westmanga community we don't need presence when doing searches_

_Preview :_
[Example for search by genres](https://i.imgur.com/RcLzr1D.png)
[View Manga](https://i.imgur.com/XvxNXPg.png)
[View Manhua](https://i.imgur.com/O59Ky8D.png)
[View Manhwa](https://i.imgur.com/g7eLAKb.png)
[Presence on Reading](https://i.imgur.com/HVmSRY6.png)

2021-05-30 09:26 UTC, SlowLife1661 requested changes

2021-05-30 09:26 UTC, SlowLife1661 commented on websites/W/Westmanga/dist/metadata.json
> +  "version": "1.0.1",
```suggestion
  "version": "1.0.0",
```

2021-05-30 11:08 UTC, Bas950 submitted a review, later dismissed
LGTM

2021-05-30 11:30 UTC, ririxidev requested changes

2021-05-30 11:30 UTC, ririxidev commented on websites/W/Westmanga/tsconfig.json
> +
```suggestion
```

2021-05-30 11:46 UTC, SlowLife1661 approved these changes

2021-05-31 08:19 UTC, mhazm commented
Its okey or not?

2021-05-31 12:21 UTC, ririxidev approved these changes
Yup! Everythins is correct, thank you for contributing to PreMiD!

2021-05-31 12:21 UTC, merged