Presences of Nekopost
PreMiD/Presences pull request #3852
Opened 2021-05-30 15:03 UTC by boon14872

Presences of Nekopost

2021-05-30 18:25 UTC, SlowLife1661 requested changes
Remove the `.js` file and fix EsLint issues ( check DeepScan )

2021-05-30 18:25 UTC, SlowLife1661 commented on websites/N/Nekopost/dist/metadata.json
> +    },
It's not service name, and this username name is invalid

2021-05-30 18:25 UTC, SlowLife1661 commented on websites/N/Nekopost/dist/metadata.json
> +    "logo": "https://www.nekopost.net/demo/nekopost_logo.png",
Find the new logo that is at least 512x512 and upload to imgur

2021-05-30 18:25 UTC, SlowLife1661 commented on websites/N/Nekopost/dist/metadata.json
> +    "thumbnail": "https://www.nekopost.net/demo/nekopost_logo.png",
Find the actual thumbnail, use the screenshot of home page if you can't find one, and upload to imgur

2021-05-30 18:25 UTC, SlowLife1661 commented on websites/N/Nekopost/dist/metadata.json
> +      "en": "Nekopost"
Find the actual description

2021-05-31 08:47 UTC, SlowLife1661 requested changes

2021-05-31 08:47 UTC, SlowLife1661 commented on websites/N/Nekopost/dist/metadata.json
> +    "thumbnail": "https://imgur.com/iZcmtnY",
```suggestion
    "logo": "https://i.imgur.com/uoFY9IP.png",
    "thumbnail": "https://i.imgur.com/iZcmtnY.png",
```

2021-05-31 08:47 UTC, SlowLife1661 commented on websites/N/Nekopost/presence.ts
> +  presenceData.startTimestamp = browsingStamp;
```suggestion
  const presenceData: PresenceData = {
    largeImageKey: "nekopost_logo",
    startTimestamp: browsingStamp
  };
```

2021-05-31 08:47 UTC, SlowLife1661 commented on websites/N/Nekopost/presence.ts
> +  if (document.location.host === "www.nekopost.net") {
Remove this statement

2021-05-31 09:01 UTC, boon14872 commented
![image](https://user-images.githubusercontent.com/74981284/120168791-778b5600-c229-11eb-9fdb-a3c54e27f989.png)

2021-05-31 09:25 UTC, SlowLife1661 requested changes

2021-05-31 09:25 UTC, SlowLife1661 commented on websites/N/Nekopost/presence.ts
> +      presenceData.details = "กำลังเลือก Project ";
```suggestion
      presenceData.details = "กำลังเลือก Project";
```

2021-05-31 09:26 UTC, SlowLife1661 commented on websites/N/Nekopost/dist/metadata.json
> +    "$schema": "https://schemas.premid.app/metadata/1.3",
```suggestion
    "$schema": "https://schemas.premid.app/metadata/1.4",
```

2021-05-31 09:54 UTC, SlowLife1661 approved these changes
Looks good to me

2021-06-01 00:15 UTC, Bas950 approved these changes
LGTM

2021-06-01 00:15 UTC, merged