Color-hex.com presence
PreMiD/Presences pull request #3856
Opened 2021-05-30 19:29 UTC by MiepHD

![1](https://user-images.githubusercontent.com/63968466/120117484-b23fb080-c18d-11eb-9f70-fe365ba877de.PNG)
I have revised my presence and open a request again for color-hex.com.

2021-05-30 20:07 UTC, br1ss commented on websites/C/color-hex/dist/metadata.json
> +  "version": "0.1",
only 1.0.0 version

2021-05-30 20:19 UTC, MiepHD commented on websites/C/color-hex/dist/metadata.json
> +  "version": "0.1",
I changed it.

2021-05-31 13:11 UTC, ririxidev requested changes
![image](https://user-images.githubusercontent.com/9348108/120198481-6ab73400-c222-11eb-8fb6-b6681a3714ab.png)
it's still a thing.

2021-05-31 13:24 UTC, MiepHD commented
Am I only allowed to do one DOM reading?

2021-05-31 13:30 UTC, ririxidev commented
> Am I only allowed to do one DOM reading?

You NEED to do more DOM readings or provide more functionality.

2021-05-31 14:24 UTC, MiepHD commented
I have several dom readings and cover nearly all of the funtionalities of the website. I had asked only because i was worried that i am not allowed to have more than one reading.

2021-05-31 14:53 UTC, ririxidev commented
You only do that 2 times

2021-05-31 16:18 UTC, MiepHD commented
Yes for two pages it made sense to get infos from within the pages but for most pages it is enough to read the url or the title

2021-05-31 16:19 UTC, ririxidev commented
So this presence will not be accepted until you will not get more DOM readings or so 😃

2021-05-31 16:28 UTC, MiepHD commented
Should I use DOM readings instead of using title and path to make the code more complicated?

2021-05-31 16:50 UTC, MiepHD commented
I can't find a rule in the Guidelines which says that I must have a certain number of DOM Readings. Could you please tell me where I can see this rule? Why do I have to have a certain amount of DOM Readings?

2021-05-31 16:52 UTC, ririxidev commented
This presence is just qualified for low quality at this point since presence is more likely "static". And I'm not going to continue this conversation anymore since I already told you what to do.

2021-05-31 16:58 UTC, MiepHD commented
Did you visit the site at any time?? There are no more functions on the site! Because there are no more functions I can't add functions to the presence.

2021-05-31 17:00 UTC, MiepHD commented
> This presence is just qualified for low quality at this point since presence is more likely "static". And I'm not going to continue this conversation anymore since I already told you what to do.

It's a mostly static site. So isn't it logically that the presence is also like that?

2021-05-31 17:13 UTC, MiepHD commented
@br1ss What do you think about this presence? Has it enough functionality?

2021-05-31 17:16 UTC, ririxidev commented
Sorry but `br1ss` is not Presence Reviewer. If you can't provide more functionality it means that site is not qualified. I'm sorry but we are accepting only "good" presences, not presences like yours rn.
If you want to report my actions, please do to Staff Coordinator (Bas950), his discord is Bas950#0950.

2021-05-31 17:16 UTC, closed without merging