Instagram presence
PreMiD/Presences pull request #3867
Opened 2021-05-31 07:19 UTC by MiepHD

I added details for the nametag site, changed it so that it doesn't create a new presenceData everytime and fixed ESLint issues.
![1](https://user-images.githubusercontent.com/63968466/120155602-4bec7980-c1f1-11eb-8997-de75c6fb45ee.PNG)

2021-05-31 13:07 UTC, ririxidev requested changes
Fix DeepScan & Codacy issues

2021-05-31 13:07 UTC, ririxidev commented on websites/I/Instagram/presence.ts
> +	if (presenceData.details === null) {
from what I see - details is always a thing so maybe remove this if and leave only function from else :/

2021-05-31 17:24 UTC, MiepHD commented
I've fixed the issues except of "Use array destructuring" because I don't know how to fix it.

2021-05-31 17:25 UTC, ririxidev commented
Instead of for example:
`const f = variable[0]`
you do:
`const [f] = variable`

if it's second or more you do:
`const [, f] = variable`

2021-05-31 17:29 UTC, MiepHD commented
Like that?

2021-05-31 17:31 UTC, ririxidev requested changes
like this

2021-05-31 17:31 UTC, ririxidev commented on websites/I/Instagram/presence.ts
> +      presenceData.state = document.location.pathname.split("/")[, 1];
```suggestion
      const [, pathName] = document.location.pathname.split("/")
      presenceData.details = "Viewing a profile";
      presenceData.state = pathName;
```

2021-05-31 17:31 UTC, ririxidev commented on websites/I/Instagram/presence.ts
> +      presenceData.state = document.location.pathname.split("/")[, , 2];
```suggestion
      const [, , pathName] = document.location.pathname.split("/")
      presenceData.details = "Viewing a story";
      presenceData.state = pathName;
```

2021-05-31 17:34 UTC, MiepHD commented on websites/I/Instagram/presence.ts
> +      presenceData.state = document.location.pathname.split("/")[, , 2];
Thanks now I understand how to solve it

2021-06-01 14:21 UTC, ririxidev requested changes

2021-06-01 14:21 UTC, ririxidev commented on websites/I/Instagram/dist/metadata.json
>    "thumbnail": "https://crugg.de/premid/igbanner.png",
upload to imgur

2021-06-01 14:21 UTC, ririxidev commented on websites/I/Instagram/presence.ts
> +      const [, , pathName] = document.location.pathname.split("/")
```suggestion
      const [, , pathName] = document.location.pathname.split("/");
```

2021-06-01 14:21 UTC, ririxidev commented on websites/I/Instagram/presence.ts
> +      const [, pathName] = document.location.pathname.split("/")
```suggestion
      const [, pathName] = document.location.pathname.split("/");
```

2021-06-02 17:56 UTC, Bas950 approved these changes
LGTM

2021-06-02 19:12 UTC, ririxidev approved these changes

2021-06-02 19:12 UTC, merged