Hide private groups/projects
PreMiD/Presences pull request #3891
Opened 2021-06-05 23:58 UTC by Gurrman375

Now hides private and group presences:
Shown:
![image](https://user-images.githubusercontent.com/25113575/120908429-02e85b00-c61f-11eb-95f5-5b480702a092.png)
![image](https://user-images.githubusercontent.com/25113575/120908439-2c08eb80-c61f-11eb-831c-70af04713459.png)

Hidden:
![image](https://user-images.githubusercontent.com/25113575/120908432-13003a80-c61f-11eb-9bda-f48d5636f44c.png)

2021-06-06 00:00 UTC, ririxidev commented
That was fast response to my comment! Thanks!
But please fix ESLint issues.

2021-06-06 02:28 UTC, SlowLife1661 requested changes
EsLint issues

2021-06-06 09:41 UTC, ririxidev requested changes

2021-06-06 09:41 UTC, ririxidev commented on websites/G/GitLab/presence.ts
> +    else if (document.location.pathname === "/dashboard/groups") presenceData.details = "Viewing Groups";
```suggestion
    } else if (document.location.pathname === "/dashboard/groups") presenceData.details = "Viewing Groups";
```

2021-06-06 09:41 UTC, ririxidev commented on websites/G/GitLab/presence.ts
> +
```suggestion
```

2021-06-06 09:41 UTC, ririxidev commented on websites/G/GitLab/presence.ts
> +      else{
```suggestion
      } else {
```

2021-06-07 10:43 UTC, ririxidev approved these changes

2021-06-07 10:48 UTC, SlowLife1661 approved these changes

2021-06-07 10:48 UTC, merged