[Update] AnimeFever: fix for new search page, removed old code
PreMiD/Presences pull request #3893
Opened 2021-06-06 16:19 UTC by Venipa

Browsing Default:
![image](https://user-images.githubusercontent.com/17952364/120931762-51672980-c6f3-11eb-8438-e1b607ad25f3.png)
View Anime:
![image](https://user-images.githubusercontent.com/17952364/120931771-5e841880-c6f3-11eb-89c6-984dedff327c.png)
Viewing Episode:
Paused:
![image](https://user-images.githubusercontent.com/17952364/120931783-6ba10780-c6f3-11eb-9df2-69da0e3aafab.png)
Play:
![image](https://user-images.githubusercontent.com/17952364/120931788-7196e880-c6f3-11eb-9bdd-db870f6990d7.png)
Schedule and other pages:
![image](https://user-images.githubusercontent.com/17952364/120931809-87a4a900-c6f3-11eb-9ef6-9ab8e46f1eb2.png)
(New) Search Page (was broken before due to new ui):
![image](https://user-images.githubusercontent.com/17952364/120931845-9be8a600-c6f3-11eb-880d-ee2c5d7fd3a5.png)
![image](https://user-images.githubusercontent.com/17952364/120931858-a4d97780-c6f3-11eb-9d70-006693547f50.png)

2021-06-07 10:46 UTC, ririxidev requested changes

2021-06-07 10:46 UTC, ririxidev commented on websites/A/AnimeFever/presence.ts
> +    document.querySelectorAll("script[type=\"application/ld+json\"]")
escaping. 
```suggestion
    document.querySelectorAll('script[type="application/ld+json"]')
```

2021-06-07 10:46 UTC, ririxidev commented on websites/A/AnimeFever/presence.ts
> +      x.textContent.indexOf("\"@type\":\"TVSeries\"") !== -1
```suggestion
      x.textContent.indexOf('"@type":"TVSeries"') !== -1
```

2021-06-07 10:46 UTC, ririxidev commented on websites/A/AnimeFever/presence.ts
> +    document.querySelectorAll("script[type=\"application/ld+json\"]")
```suggestion
    document.querySelectorAll('script[type="application/ld+json"]')
```

2021-06-07 10:46 UTC, ririxidev commented on websites/A/AnimeFever/presence.ts
> +      x.textContent.indexOf("\"@type\":\"TVEpisode\"") !== -1
```suggestion
      x.textContent.indexOf('"@type":"TVEpisode"') !== -1
```

2021-06-07 10:46 UTC, ririxidev commented on websites/A/AnimeFever/presence.ts
> +            data.endTimestamp = endTimestamp;
you don't need startTimestamp :P

2021-06-07 10:46 UTC, ririxidev commented on websites/A/AnimeFever/presence.ts
> +            ".shows-content input[type=\"text\"]"
```suggestion
            '.shows-content input[type="text"]'
```

2021-06-10 18:04 UTC, ririxidev approved these changes

2021-06-11 14:31 UTC, SlowLife1661 approved these changes

2021-06-11 16:00 UTC, merged