Add www.presencedb.com support
PreMiD/Presences pull request #3897
Opened 2021-06-06 23:39 UTC by vascYT

2021-06-06 23:43 UTC, EncryptedDev requested changes
Look at my review

2021-06-06 23:43 UTC, EncryptedDev commented on websites/P/Plex/dist/metadata.json
> +  "thumbnail": "https://files.vasc.dev/source/DU7ayUCih.png",
Must be on Imgur

2021-06-06 23:43 UTC, EncryptedDev commented on websites/P/PresenceDB/dist/metadata.json
> +    "logo": "https://www.presencedb.com/logo.png",
Must be on imgur

2021-06-07 05:40 UTC, ririxidev commented
Site not 2 months old.

2021-06-07 05:40 UTC, closed without merging

2021-06-07 08:06 UTC, vascYT commented
See you in 2 Months then 👋