Added presence AnimeUltima
PreMiD/Presences pull request #3914
Opened 2021-06-09 19:09 UTC by VocalZero

I implemented the presence request from coolads934. #3872

## Proof of work
https://www1.animeultima.to/
![Screenshot 2021-06-09 205959](https://user-images.githubusercontent.com/20924469/121413957-816a3300-c966-11eb-88a1-38d9ceb1d2e8.png)

https://www1.animeultima.to/search?search=pokemon
![Screenshot 2021-06-09 210103](https://user-images.githubusercontent.com/20924469/121414048-92b33f80-c966-11eb-8c0c-30e9f79380cc.png)

https://www1.animeultima.to/a/pokemon-2019_281673
![Screenshot 2021-06-09 210126](https://user-images.githubusercontent.com/20924469/121414089-9cd53e00-c966-11eb-906c-72b20c042c52.png)

https://www1.animeultima.to/a/kyuukyoku-shinka-shita-full-dive-rpg-ga-genjitsu-yori-mo-kusoge-dattara_290916/episode-1_858541-dub
![Screenshot 2021-06-09 210154](https://user-images.githubusercontent.com/20924469/121414130-a8286980-c966-11eb-98d7-0c38ac22d40d.png)

2021-06-10 18:01 UTC, rxri requested changes
also isn't there more subpages to support :/
and support player too :////

2021-06-10 18:01 UTC, ririxidev commented on websites/A/AnimeUltima/presence.ts
> +  presenceData.startTimestamp = browsingTimestamp;
delete it please... and use presenceData inside event and add `startTimestamp` to presenceData object

2021-06-10 18:01 UTC, ririxidev commented on websites/A/AnimeUltima/presence.ts
> +    presence.setActivity(presenceData, true);
```suggestion
    presence.setActivity(presenceData);
```

2021-06-10 18:01 UTC, ririxidev commented on websites/A/AnimeUltima/presence.ts
> +    presenceData.buttons = [ { label: "Watch Anime", url: document.location.toString() } ];
```suggestion
    presenceData.buttons = [ { label: "View Anime", url: document.location.toString() } ];
```

2021-06-10 18:01 UTC, ririxidev commented on websites/A/AnimeUltima/presence.ts
> +browsingTimestamp = Date.now(),
```suggestion
browsingTimestamp = ~~(Date.now() / 1000),
```

2021-06-11 16:39 UTC, VocalZero commented
I could add a few more subpages. That's not a big problem but with the support of the player I don't get further at the moment. When I try to view the page, the player stops and is paused by Chrome Debug. I have tried a few methods but have not been able to access the video object. Would anyone have an idea how I could implement this?

2021-06-11 16:52 UTC, ririxidev commented
https://greasyfork.org/en/scripts/32015-anti-anti-debugger/code

2021-06-11 17:19 UTC, VocalZero commented
I'm now trying to get to the stuff in the iFrame with "document.querySelector("iframe").contentWindow.document" but I'm getting a cross-origin frame error. Somehow I don't like the page and the page doesn't like me :/

2021-06-12 13:46 UTC, VocalZero commented
I have now tried again but without success. The Cross-Origin Frame error blocks me from accessing the iFrame. Does anyone know a fix? Otherwise I leave the player away from the presence.

2021-06-12 17:31 UTC, ririxidev commented
```document.querySelector("#app > section.section.dark-container.is-paddingless > div > div.player-container.player-container-16x9 > iframe")```
and no draft prs.

2021-06-12 17:58 UTC, VocalZero commented
Sorry about the pr draft. Again to the iFrame I'm already so far. I try from the iFrame to get the video to take some data from it but somehow I can't get any further because of the error I mentioned earlier.

```typescript
const iframe = document.querySelector("#app > section.section.dark-container.is-paddingless > div > div.player container.player-container-16x9 > iframe"),
   video = iframe.contentWindow.document.querySelector("video");
console.log(video); // returns null because of error Blocked a frame with origin "https://www1.animeultima.to" from accessing a cross-origin frame.
```

2021-06-15 12:10 UTC, ririxidev approved these changes
ehh okay then for now

2021-06-18 03:11 UTC, SlowLife1661 approved these changes

2021-06-18 08:31 UTC, merged