update: TürkAnimeTV presence
PreMiD/Presences pull request #3923
Opened 2021-06-12 01:47 UTC by emirkabal

* Added presence buttons
* Added a few strings
* Added a few pages
* Fix episode matching

2021-06-13 20:50 UTC, Bas950 requested changes
Upload proof of it working

2021-06-14 09:32 UTC, emirkabal commented
> Upload proof of it working

![1](https://kabal.is-inside.me/wvjtTkR8.png)
![2](https://kabal.is-inside.me/SQDtdaUc.png)

2021-06-15 12:11 UTC, ririxidev requested changes
(fix eslint issues)

2021-06-15 12:11 UTC, ririxidev commented on websites/T/TürkAnimeTV/presence.ts
> +      const timestamps = presence.getTimestamps(
use array deconstructing

2021-06-15 15:03 UTC, emirkabal commented on websites/T/TürkAnimeTV/presence.ts
> +      const timestamps = presence.getTimestamps(
oh sorry

2021-06-17 09:22 UTC, ririxidev requested changes

2021-06-17 09:22 UTC, ririxidev commented on websites/T/TürkAnimeTV/presence.ts
> +      presenceData.startTimestamp = currentTime;
```suggestion
```

2021-06-17 09:22 UTC, ririxidev commented on websites/T/TürkAnimeTV/presence.ts
> +      const [currentTime, duration] = presence.getTimestamps(
```suggestion
      const [, duration] = presence.getTimestamps(
```

2021-06-18 03:16 UTC, SlowLife1661 approved these changes

2021-06-18 08:30 UTC, ririxidev approved these changes

2021-06-18 08:30 UTC, merged