Added ARD Mediathek presence
PreMiD/Presences pull request #3950
Opened 2021-06-15 08:14 UTC by Reichmann-M

# Proof of work
[www.ardmediathek.de](https://www.ardmediathek.de/) - Mainpage of German Television Streaming portal
![screen1](https://user-images.githubusercontent.com/46574997/122015722-a32d4500-cdc0-11eb-9184-4e800915598c.jpg) 

[Das Erste Livestream](https://www.ardmediathek.de/live/Y3JpZDovL2Rhc2Vyc3RlLmRlL0xpdmVzdHJlYW0tRGFzRXJzdGU/?toolbarType=default) - German Television Livestream
![screen2](https://user-images.githubusercontent.com/46574997/122016398-5007c200-cdc1-11eb-9005-e4d6f86e4946.jpg)

[ARD Video-on-demand](https://www.ardmediathek.de/video/agatha-christie-partners-in-crime/folge-1-der-auftrag-s01-e01/one/Y3JpZDovL3dkci5kZS9CZWl0cmFnLWI1MzBjYzgyLTc1NjgtNDdjYi1hMjRjLWIyZTJmZGZlOTlmNQ/) - Normal show & movie streaming
![screen3](https://user-images.githubusercontent.com/46574997/122017148-01a6f300-cdc2-11eb-8a5e-2b3cf8e4a235.jpg)

2021-06-15 12:16 UTC, ririxidev requested changes

2021-06-15 12:16 UTC, ririxidev commented on websites/A/ARD Mediathek/presence.ts
> +  const path = location.pathname.replace(/\/?$/, "/");
```suggestion
  }, path = location.pathname.replace(/\/?$/, "/");


  if (document.location.href !== prevUrl) {
    prevUrl = document.location.href;
    elapsed = Math.floor(Date.now() / 1000);
  }
```

2021-06-15 12:16 UTC, ririxidev commented on websites/A/ARD Mediathek/dist/metadata.json
> +    "thumbnail": "https://www.daserste.de/unterhaltung/service-unterhaltung/ard-mediathek-das-erste-100~_v-standard644_d3b97e.jpg",
use direct imgur links

2021-06-15 12:16 UTC, ririxidev commented on websites/A/ARD Mediathek/presence.ts
> +        );
presence.getTimestamps ?

2021-06-15 12:37 UTC, Reichmann-M commented on websites/A/ARD Mediathek/dist/metadata.json
> +    "thumbnail": "https://www.daserste.de/unterhaltung/service-unterhaltung/ard-mediathek-das-erste-100~_v-standard644_d3b97e.jpg",
```suggestion
    "logo": "https://i.imgur.com/baUokNs.png",
    "thumbnail": "https://i.imgur.com/mix2mJC.jpg",
```

2021-06-15 13:23 UTC, Reichmann-M commented on websites/A/ARD Mediathek/presence.ts
> +        );
```suggestion
const video: HTMLVideoElement = document.querySelector('.ardplayer-mediacanvas'),
    timestamps = presence.getTimestamps(Math.floor(video.currentTime),Math.floor(video.duration));

presenceData.startTimestamp = timestamps[0];
presenceData.endTimestamp = timestamps[1];
```

2021-06-15 13:40 UTC, Reichmann-M commented
Every change suggestion should be done by now ^^

2021-06-17 09:19 UTC, ririxidev requested changes
please run prettier over it :^)

2021-06-17 09:19 UTC, ririxidev commented on websites/A/ARD Mediathek/presence.ts
> +      [presenceData.startTimestamp, presenceData.endTimestamp] = timestamps;
```suggestion
      [, presenceData.endTimestamp] = timestamps;
```

2021-06-17 16:27 UTC, ririxidev approved these changes

2021-06-18 03:27 UTC, SlowLife1661 approved these changes

2021-06-18 03:27 UTC, merged