update Dizilla presence domain URL
PreMiD/Presences pull request #3970
Opened 2021-06-18 16:57 UTC by eggsy

it's working now

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/13917975/122594084-39869280-d06f-11eb-93db-77a914d79d70.png">

2021-06-18 17:00 UTC, ririxidev requested changes
first;
all of `object.startTimestamp` move to `object` object and value should be `~~(Date.now() / 1000)` or `Math.floor(Date.now() / 1000)`
second;
don't set startTimestamp in videos.

2021-06-18 17:00 UTC, ririxidev commented on websites/D/Dizilla/presence.ts
> +    const timestamps = dizilla.getTimestamps(
use array deconstructing

2021-06-18 18:51 UTC, ririxidev approved these changes

2021-06-20 07:34 UTC, SlowLife1661 approved these changes

2021-06-20 07:34 UTC, merged

2021-06-23 09:23 UTC, AlperSal commented
Now, on Udemy presence at least, lesson name shows up but course name is still "Unknown Course". Photo;
![image](https://user-images.githubusercontent.com/34231577/123071784-9f7f6b00-d41d-11eb-9cfb-2d80366499a9.png)

2021-07-20 11:22 UTC, AlperSal commented
> 
> 
> Now, on Udemy presence at least, lesson name shows up but course name is still "Unknown Course". Photo;
> ![image](https://user-images.githubusercontent.com/34231577/123071784-9f7f6b00-d41d-11eb-9cfb-2d80366499a9.png)

Any fix?