Adding FLO Presence
PreMiD/Presences pull request #3995
Opened 2021-06-25 18:16 UTC by gunyu1019

**FLO is a South Korean music streaming service operated by SK Telecom. I am leaving Pull Requests to add this Presence.**

![image](https://user-images.githubusercontent.com/16767890/123467530-92d06200-d62b-11eb-8ddc-747a395a5863.png)
![image](https://user-images.githubusercontent.com/16767890/123467539-949a2580-d62b-11eb-95b2-755cc0509763.png)
![image](https://user-images.githubusercontent.com/16767890/123467547-96fc7f80-d62b-11eb-9c52-386340d22372.png)
![image](https://user-images.githubusercontent.com/16767890/123467558-995ed980-d62b-11eb-9ace-a7a8c669bbc5.png)

2021-06-27 14:32 UTC, ririxidev requested changes
Please run prettier over it too.

2021-06-27 14:32 UTC, ririxidev commented on websites/F/FLO/presence.ts
> +      ]
![image](https://user-images.githubusercontent.com/9348108/123548361-c7940480-d764-11eb-90c5-a6a6fdea3223.png)

2021-06-27 14:32 UTC, ririxidev commented on websites/F/FLO/dist/metadata.json
> +    "nl": "Koreaanse muziekstreamingservice (FLO)"
I don't think that is their official description.

2021-06-27 14:32 UTC, ririxidev commented on websites/F/FLO/presence.ts
> +      presenceData.smallImageText = title;
```suggestion
```

2021-06-27 14:32 UTC, ririxidev commented on websites/F/FLO/presence.ts
> +      presenceData.smallImageText = "앨범";
```suggestion
```

2021-06-27 14:32 UTC, ririxidev commented on websites/F/FLO/presence.ts
> +      presenceData.smallImageText = "테마리스트";
```suggestion
```

2021-06-27 14:32 UTC, ririxidev commented on websites/F/FLO/presence.ts
> +      presenceData.smallImageText = "최근 발매 음악";
```suggestion
```

2021-06-27 14:32 UTC, ririxidev commented on websites/F/FLO/presence.ts
> +        presenceData.smallImageText = "검색";
```suggestion
```

2021-06-27 14:32 UTC, ririxidev commented on websites/F/FLO/presence.ts
> +      currentDate = getTimestamp(currentTime, currentHiddenTime);
Isn't time in unix timestamp or hh:mm:ss format? If yes, use our functions (`presence.getTimestamps()`, `presence.timestampFromFormat()`)

2021-06-27 14:47 UTC, Bas950 commented on websites/F/FLO/dist/metadata.json
> +    "nl": "Koreaanse muziekstreamingservice (FLO)"
I think it's "음악을 들을수록 나를 더 닮아가는 나만의 FLO. 지금, 당신의 음악"

2021-06-27 16:38 UTC, ririxidev requested changes
and prettier 😄

2021-06-27 16:38 UTC, ririxidev commented on websites/F/FLO/presence.ts
> +    [ presenceData.startTimestamp, presenceData.endTimestamp ] = presence.getTimestamps(currentDate, allDate);
```suggestion
    [, presenceData.endTimestamp] = presence.getTimestamps(currentDate, allDate);
```

2021-06-27 19:33 UTC, ririxidev requested changes
still waiting for your prettified code with [prettier](https://prettier.io)

2021-06-28 03:18 UTC, SlowLife1661 approved these changes

2021-06-28 06:55 UTC, ririxidev approved these changes

2021-06-28 06:55 UTC, merged