Added World Romance Translation presence
PreMiD/Presences pull request #4007
Opened 2021-06-26 06:59 UTC by vahya

Proof of work
![Screenshot 2021-06-25 164938](https://user-images.githubusercontent.com/85792429/123504936-e8cbf680-d679-11eb-8ac8-7257cd1765aa.png)
![Screenshot 2021-06-26 122357](https://user-images.githubusercontent.com/85792429/123504946-f97c6c80-d679-11eb-92f8-71f04ceb7d68.png)
![Screenshot 2021-06-26 122428](https://user-images.githubusercontent.com/85792429/123504951-00a37a80-d67a-11eb-9697-ee356a291535.png)
![Screenshot 2021-06-26 122510](https://user-images.githubusercontent.com/85792429/123504962-12851d80-d67a-11eb-90c4-4fa3945b8ec3.png)
![Screenshot 2021-06-26 122559](https://user-images.githubusercontent.com/85792429/123504976-1c0e8580-d67a-11eb-9e21-aad3389886ed.png)

2021-06-26 07:00 UTC, vahya commented
#3922

2021-06-27 14:28 UTC, ririxidev requested changes

2021-06-27 14:28 UTC, ririxidev commented on websites/W/World Romance Translation/dist/metadata.json
> +  "logo": "https://i.imgur.com/06NCGow.png",
Better quality logo please?

2021-06-27 14:48 UTC, SlowLife1661 commented on websites/W/World Romance Translation/presence.ts
> +    presenceData.state = mangaName !== null ? mangaName.innerText : "";
```suggestion
    if (mangaName) presenceData.state = mangaName.innerText;
```

2021-06-29 23:38 UTC, SlowLife1661 approved these changes

2021-06-30 18:10 UTC, ririxidev approved these changes

2021-06-30 18:10 UTC, merged