Update Nightwave plaza
PreMiD/Presences pull request #4015
Opened 2021-06-29 09:21 UTC by vahya

Closes PreMiD/Presences#3998

![nightwave](https://user-images.githubusercontent.com/85792429/123772230-503bad80-d8e9-11eb-86a1-1995d5334872.png)

2021-06-30 18:09 UTC, ririxidev requested changes
pls support `play history` & `ratings`

2021-06-30 18:09 UTC, ririxidev commented on websites/N/Nightwave Plaza/dist/metadata.json
> +  "version": "2.0.0,
```suggestion
  "version": "2.0.0",
```

2021-06-30 18:27 UTC, vahya commented
> pls support `play history` & `ratings`

Ok

2021-07-01 01:00 UTC, SlowLife1661 commented on websites/N/Nightwave Plaza/presence.ts
> +  if (presenceData.details === null) {
```suggestion
  if (!presenceData.details) {
```

2021-07-02 03:17 UTC, SlowLife1661 submitted a review, later dismissed

2021-07-03 19:25 UTC, ririxidev requested changes

2021-07-03 19:25 UTC, ririxidev commented on websites/N/Nightwave Plaza/presence.ts
> +  ];
```suggestion
```

2021-07-03 19:25 UTC, ririxidev approved these changes

2021-07-03 19:47 UTC, vahya commented on websites/N/Nightwave Plaza/presence.ts
> +  ];
Why remove this?

2021-07-03 19:51 UTC, ririxidev commented on websites/N/Nightwave Plaza/presence.ts
> +  ];
It's against our guidelines

2021-07-05 13:07 UTC, SlowLife1661 approved these changes

2021-07-05 13:07 UTC, merged