Add MyAnimeList.Vip presence
PreMiD/Presences pull request #4063
Opened 2021-07-05 12:30 UTC by vahya

![Screenshot 2021-07-05 175428](https://user-images.githubusercontent.com/85792429/124471709-d3ae4080-ddba-11eb-93a3-4c7457f00751.png)
![Screenshot 2021-07-05 175509](https://user-images.githubusercontent.com/85792429/124471720-d6109a80-ddba-11eb-8a49-9e7dce0b6392.png)
![Screenshot 2021-07-05 175643](https://user-images.githubusercontent.com/85792429/124471721-d6a93100-ddba-11eb-9ebf-745f1e7f1c8d.png)
![Screenshot 2021-07-05 175701](https://user-images.githubusercontent.com/85792429/124471724-d741c780-ddba-11eb-8b17-3b6ada126621.png)
![Screenshot 2021-07-05 175722](https://user-images.githubusercontent.com/85792429/124471726-d7da5e00-ddba-11eb-86ac-bf0c688970cb.png)

2021-07-05 17:22 UTC, ririxidev requested changes
support every subpage

2021-07-05 17:22 UTC, ririxidev commented on websites/M/MyAnimeList.Vip/dist/metadata.json
> +  "logo": "https://i.imgur.com/Refe3ci.png",
low quality logo

2021-07-08 20:56 UTC, ririxidev approved these changes

2021-07-08 20:56 UTC, ririxidev requested changes
and prettify it yonk xd

2021-07-08 20:56 UTC, ririxidev commented on websites/M/MyAnimeList.Vip/presence.ts
> +    } else presenceData.details = "Explorando MyAnimeList.vip";
wait actually you can make it simplier
```suggestion
      presenceData.details = document.location.search ? `Procurando por ${document.location.search.substring(
        3
      )}` : "Explorando MyAnimeList.vip";
```

2021-07-11 09:35 UTC, Bas950 commented on websites/M/MyAnimeList.Vip/dist/metadata.json
> +  "service": "MyAnimeList.Vip",
```suggestion
  "service": "MyAnimeList.vip",
```
I would do lowercase "v"...

2021-07-11 13:14 UTC, ririxidev approved these changes, later dismissed

2021-07-11 13:14 UTC, ririxidev commented
aaaa lol, change folder name regarding Bas' review lmaaooo

2021-07-12 10:23 UTC, ririxidev approved these changes

2021-07-13 01:37 UTC, SlowLife1661 approved these changes

2021-07-13 11:20 UTC, Bas950 approved these changes

2021-07-13 11:20 UTC, merged