Update Brick-Hill to 1.0.3
PreMiD/Presences pull request #4069
Opened 2021-07-06 23:39 UTC by dragonismcode

I made this before but I totally forgot about it so I'm making another one :) 

Previous One: https://github.com/PreMiD/Presences/pull/2793

- Redid how it looks on your profile (Viewing Page: | Dashboard)
- Added preciese info (game name, clan name, user name)
- Added blog & API presence
- Added promocodes (secret/new page)

![image](https://user-images.githubusercontent.com/76412158/124679040-5e5d7100-de89-11eb-905c-a2b5b5ead565.png)
![image](https://user-images.githubusercontent.com/76412158/124679090-6fa67d80-de89-11eb-8258-5a2b69670dd6.png)
![image](https://user-images.githubusercontent.com/76412158/124679114-7af9a900-de89-11eb-99d6-1d1b53afe5b9.png)

2021-07-07 10:56 UTC, ririxidev requested changes
Fix codefactor and move all `presenceData.startTimestamp = browsingStamp` lines to just `presenceData` object

2021-07-09 02:57 UTC, SlowLife1661 commented on websites/B/Brick Hill/presence.ts
>    if (presenceData.details == null) {
```suggestion
  if (!presenceData.details) {
```

2021-07-09 03:00 UTC, SlowLife1661 commented on websites/B/Brick Hill/presence.ts
> +    startTimestamp: Math.floor(Date.now() / 1000)
```suggestion
    startTimestamp: browsingStamp
```

2021-07-11 09:37 UTC, Bas950 approved these changes, later dismissed

2021-07-11 13:12 UTC, ririxidev requested changes

2021-07-11 13:12 UTC, ririxidev commented on websites/B/Brick Hill/presence.ts
> +
```suggestion
```

2021-07-11 13:12 UTC, ririxidev commented on websites/B/Brick Hill/presence.ts
> -
add blank line here?

2021-07-12 10:23 UTC, ririxidev approved these changes

2021-07-13 01:34 UTC, SlowLife1661 approved these changes

2021-07-13 11:18 UTC, Bas950 approved these changes

2021-07-13 11:18 UTC, merged