Gamejolt | Add Fireside Support
PreMiD/Presences pull request #4074
Opened 2021-07-07 13:59 UTC by MMDDKK6500

### Added Fireside Support for the Gamejolt presence
![ezgif com-gif-maker](https://user-images.githubusercontent.com/34542949/124771953-f3a44800-df11-11eb-9a25-4514a731f363.gif)

fixed some spacing issues too, and the "pages" const had no type, that's it.

2021-07-09 02:44 UTC, SlowLife1661 approved these changes, later dismissed

2021-07-09 13:45 UTC, ririxidev requested changes

2021-07-09 13:45 UTC, ririxidev commented on websites/G/Game Jolt/presence.ts
> +          .replace("\n\t\t\t\t", "")
umm, please use regex here :)

2021-07-09 13:45 UTC, ririxidev commented on websites/G/Game Jolt/presence.ts
> +    data: { [k: string]: string | number } = {
```suggestion
    data: PresenceData = {
```

2021-07-09 13:45 UTC, ririxidev commented on websites/G/Game Jolt/dist/metadata.json
> +  "version": "1.3.0",
```suggestion
  "version": "1.2.8",
```

2021-07-09 13:45 UTC, ririxidev commented on websites/G/Game Jolt/presence.ts
> +
why space here?

2021-07-11 09:34 UTC, Bas950 approved these changes

2021-07-11 13:09 UTC, ririxidev approved these changes

2021-07-11 13:09 UTC, merged