Adding GMANGA Presence ✨
PreMiD/Presences pull request #4079
Opened 2021-07-09 01:55 UTC by GhaithAlHallak8

# First
![image](https://user-images.githubusercontent.com/59054736/125010718-c372bb80-e06f-11eb-93b3-78e17a17578f.png)

# Second
![image](https://user-images.githubusercontent.com/59054736/125010813-eef5a600-e06f-11eb-9ac1-39d611d1b9b2.png)

# Third
![image](https://user-images.githubusercontent.com/59054736/125010888-18163680-e070-11eb-9ce0-4355c328aa69.png)

# Fourth
![image](https://user-images.githubusercontent.com/59054736/125010950-31b77e00-e070-11eb-9776-03518bd64ceb.png)

# Fifth (With dark icon setting enabled)
![image](https://user-images.githubusercontent.com/59054736/125010988-4c89f280-e070-11eb-93e4-2acc6f927dd4.png)

2021-07-11 09:31 UTC, Bas950 requested changes

2021-07-11 09:31 UTC, Bas950 commented on websites/G/GMANGA/dist/metadata.json
> +    "en": "GMANGA - An interactive site that aims to provide more options for translating manga chapters to arabic."
```suggestion
    "en": "GMANGA - An interactive site that aims to provide more options for translating manga chapters to Arabic."
```

2021-07-11 13:05 UTC, ririxidev requested changes
plz prettier

2021-07-12 10:24 UTC, ririxidev approved these changes

2021-07-13 01:33 UTC, SlowLife1661 approved these changes

2021-07-13 11:17 UTC, Bas950 approved these changes

2021-07-13 11:18 UTC, merged