Add LPG Presence
PreMiD/Presences pull request #4085
Opened 2021-07-10 10:23 UTC by TheGamerzs

![image](https://user-images.githubusercontent.com/44209534/125159605-5b57ce80-e170-11eb-99b2-30f851c2bf57.png)
![image](https://user-images.githubusercontent.com/44209534/125159736-1c764880-e171-11eb-83eb-7f5d4f14c73d.png)
![image](https://user-images.githubusercontent.com/44209534/125159750-39128080-e171-11eb-88dc-4ffdeb731cc1.png)

2021-07-10 10:31 UTC, EncryptedDev requested changes
Beep boop

2021-07-10 10:31 UTC, EncryptedDev commented on websites/L/Lime Pro Gaming/dist/metadata.json
> +
Empty line

2021-07-11 09:44 UTC, Bas950 requested changes

2021-07-11 09:44 UTC, Bas950 commented on websites/L/Lime Pro Gaming/dist/metadata.json
> +  "altnames": ["LPG", "Lime | Pro Gaming"],
```suggestion
  "altnames": ["LPG"],
```

2021-07-11 09:50 UTC, Bas950 approved these changes, later dismissed

2021-07-11 13:05 UTC, ririxidev commented
ngl but, I don't really think that some x shop needs presence. sorry but rejecting.

2021-07-11 16:24 UTC, ririxidev requested changes
Use prettier again and fix things from my review.

2021-07-11 16:24 UTC, ririxidev commented on websites/L/Lime Pro Gaming/presence.ts
> +  presenceData.startTimestamp = browsingStamp;
```suggestion
    largeImageKey: "logo",
    startTimestamp: browsingStamp
  };
```

2021-07-11 16:24 UTC, ririxidev commented on websites/L/Lime Pro Gaming/presence.ts
> +const browsingStamp = Math.floor(Date.now() / 1000);
```suggestion
const presence = new Presence({
  clientId: "863173597941727282"
}), browsingStamp = Math.floor(Date.now() / 1000);

let productName, productBrand, blogTitle, blogAuthor;
```

2021-07-11 16:24 UTC, ririxidev commented on websites/L/Lime Pro Gaming/dist/metadata.json
> +  "tags": ["gaming", "retail", "drinks", "distributor", "lpg"],
```suggestion
  "tags": ["gaming", "retail", "drinks", "distributor"],
```

2021-07-11 16:24 UTC, ririxidev commented on websites/L/Lime Pro Gaming/presence.ts
> +    presenceData.smallImageKey = blogAuthor ? "reading" : null;
Hmm. No `null` values.
```suggestion
    if(blogAuthor) presenceData.smallImageKey = "reading"
```

2021-07-11 16:24 UTC, ririxidev commented on websites/L/Lime Pro Gaming/presence.ts
> +    presenceData.state = blogAuthor;
```suggestion
    if(blogAuthor) presenceData.state = blogAuthor;
```

2021-07-11 16:24 UTC, ririxidev commented on websites/L/Lime Pro Gaming/presence.ts
> +          label: "View Brand/Category",
```suggestion
          label: "View Brand",
```

2021-07-11 16:24 UTC, ririxidev commented on websites/L/Lime Pro Gaming/presence.ts
> +      window.location.search.replace("?q=", "").split("&")[0]
Use array deconstructing.

2021-07-12 11:56 UTC, TheGamerzs commented
Will prettier later

2021-07-18 12:32 UTC, SlowLife1661 approved these changes

2021-07-18 13:00 UTC, TheGamerzs commented
@Bas950 slowlife suggests that prettier is not needed, so if you can approve or suggest what exactly needs prettier

2021-07-18 13:45 UTC, Bas950 approved these changes

2021-07-18 13:45 UTC, merged