Add 'Pony Town' and 'Ashes Town' presence
PreMiD/Presences pull request #4093
Opened 2021-07-12 16:34 UTC by Ponfertato

<img width="449" alt="Снимок экрана 2021-07-12 190123" src="https://user-images.githubusercontent.com/24917461/125323955-0c649180-e348-11eb-8d76-c5e5e28594a2.png">
<img width="449" alt="Снимок экрана 2021-07-12 190058" src="https://user-images.githubusercontent.com/24917461/125323951-0b336480-e348-11eb-9fee-797d3838f7e3.png">
Pony Town Official Server

<img width="449" alt="Снимок экрана 2021-07-12 193109" src="https://user-images.githubusercontent.com/24917461/125324036-28683300-e348-11eb-82ed-bf2db7f78cf8.png">
<img width="450" alt="Снимок экрана 2021-07-12 193151" src="https://user-images.githubusercontent.com/24917461/125324033-27cf9c80-e348-11eb-8e95-4707cb137a29.png">
Ashes Town Custom Server

2021-07-13 11:08 UTC, Bas950 requested changes
Fix codefactor and schema errors.

2021-07-13 13:11 UTC, Bas950 requested changes
There is not a lot to these presences, try adding some more stuff if possible.

2021-07-13 13:11 UTC, Bas950 commented on websites/P/Pony Town/dist/metadata.json
> +  "thumbnail": "https://pony.town/assets/images/logo-large-57d9b1947a.png",
upload to imgur

2021-07-13 13:11 UTC, Bas950 commented on websites/A/Ashes Town/dist/metadata.json
> +  "thumbnail": "https://ashes.town/assets/images/logo-large-a04e72411e.png",
upload to imgur

2021-07-13 13:11 UTC, Bas950 commented on websites/A/Ashes Town/dist/metadata.json
> +  "version": "0.0.1",
```suggestion
  "version": "1.0.0",
```

2021-07-13 13:11 UTC, Bas950 commented on websites/P/Pony Town/dist/metadata.json
> +  "version": "0.0.1",
```suggestion
  "version": "1.0.0",
```

2021-07-13 13:41 UTC, Ponfertato commented
All Done, Problems solved

2021-07-14 04:01 UTC, SlowLife1661 commented
Hey @Ponfertato,
Unfortunately, your pull request has been **denied**, due to the following reason(s):
* **Low quality** presence
  * Not reading any DOMs
  * Only tell which page user is viewing and nothing more

2021-07-14 04:01 UTC, closed without merging