Animesuge.io | Add Anime Suge Presence
PreMiD/Presences pull request #4099
Opened 2021-07-13 14:15 UTC by MMDDKK6500

Closes #3368 
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/34542949/125466900-6ed44fe2-7e2d-46a3-bb73-a3fc01aa75d9.gif)
AnimeSuge is a free streaming anime website that allows you to watch anime online in English subbed and dubbed.
First time i do a presence, i hope i did everything right.
_There may be some typos, I'm Brazillian and I have a limited knowledge of English_
also, I don't watch anime

2021-07-14 04:07 UTC, SlowLife1661 commented
Add timestamp for video

2021-07-14 17:59 UTC, Bas950 requested changes

2021-07-14 17:59 UTC, Bas950 commented on websites/A/Animesuge/presence.ts
> +}
there is a presence. function for this

2021-07-14 18:00 UTC, Bas950 requested changes

2021-07-14 18:00 UTC, Bas950 commented on websites/A/Animesuge/presence.ts
> +    data.startTimestamp = Math.floor(Date.now() / 1000);
you can just make 1 timestamp and set it at the start, this is overkill doing it 9000+ times

2021-07-18 12:34 UTC, SlowLife1661 requested changes
Show new proof of working

2021-07-18 21:52 UTC, MMDDKK6500 commented
> Show new proof of working

![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/34542949/126083189-604bf677-4eea-4fea-bd1b-f40ae10c4773.gif)

2021-07-19 04:04 UTC, SlowLife1661 commented
Ah what about what it's pauses

2021-07-19 10:46 UTC, MMDDKK6500 commented
> Ah what about when it pauses

![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/34542949/126148556-b61e0b1e-945c-48d0-aa3d-6801f7b74999.gif)

2021-07-21 13:37 UTC, Bas950 commented
> > Ah what about when it pauses
> 
> I used Opera GX Picture In Picture to help me record it
> 
> ![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/34542949/126148556-b61e0b1e-945c-48d0-aa3d-6801f7b74999.gif)

Maybe show a play/pause icon and remove timestamp when paused.

2021-07-21 13:56 UTC, MMDDKK6500 commented
> Maybe show a play/pause icon and remove timestamp when paused.
I am on vacation right now so I won't be able to code in the next 3 days, sorry

2021-07-25 16:12 UTC, MMDDKK6500 commented
proof that it's working
![ezgif com-gif-maker (6)](https://user-images.githubusercontent.com/34542949/126905860-e2b877ea-95e3-42ca-a8de-5da4c3437068.gif)

2021-07-25 18:56 UTC, Bas950 requested changes

2021-07-25 18:56 UTC, Bas950 commented on websites/A/Animesuge/presence.ts
> +      [data.startTimestamp, data.endTimestamp] = [undefined, undefined];
```suggestion
      delete data.startTimestamp;
      delete data.endTimestamp;
```

2021-07-26 15:52 UTC, Bas950 requested changes

2021-07-26 15:52 UTC, Bas950 commented on websites/A/Animesuge/dist/metadata.json
> +    "altnames": ["Animesuge","Anime Suge"],
```suggestion
```

2021-07-26 15:52 UTC, Bas950 commented on websites/A/Animesuge/dist/metadata.json
> +    "logo": "https://i.imgur.com/iQWi18m.png",
logo must be 512x512

2021-07-28 14:34 UTC, Bas950 commented on websites/A/Animesuge/presence.ts
> +        label: "Watch it too!",
```suggestion
        label: "Watch Episode",
```

2021-07-28 14:34 UTC, Bas950 commented on websites/A/Animesuge/presence.ts
> +    data.state = `Watching ${animeName.textContent}`;
maybe do
details = title
state = episode etc.?

2021-07-29 15:33 UTC, MMDDKK6500 commented
proof that it works
![ezgif com-gif-maker (7)](https://user-images.githubusercontent.com/34542949/127521108-80093b18-86a2-40da-81b5-86f88f7e0879.gif)

2021-07-29 17:00 UTC, Bas950 approved these changes

2021-07-29 17:14 UTC, SlowLife1661 approved these changes

2021-07-29 17:14 UTC, merged

2021-08-03 20:31 UTC, tatsumioga1 commented
Is it possible to change the "Playing a game" to "watching" or something? I was wondering since an extension on chromium allows us to do that (tho you need to be using discord on browser to use it unlike premid and its all manual)

2021-08-03 22:19 UTC, MMDDKK6500 commented
> Is it possible to change the "Playing a game" to "watching" or something? I was wondering since an extension on chromium allows us to do that (tho you need to be using discord on browser to use it unlike premid and its all manual)

Thanks for your suggestion, but unfortunately PreMiD is only able to use "Playing a game" because PreMiD uses Discord's Rich Presence feature that was made for games, the only exception is Spotify and Twitch(I think).
Next time you want to suggest something, please use the [Issues](https://github.com/PreMiD/Presences/issues) tab on the PreMiD Presences github repo, not the pull request for the presence, thank you