Add GeForce NOW Presence
PreMiD/Presences pull request #4104
Opened 2021-07-14 00:53 UTC by Pepijn98

<details>
<summary>Screenshots</summary>
<br>

![browsing](https://user-images.githubusercontent.com/14877471/125543073-664faab6-ccf8-430a-92a6-c7f58e62e63c.png)

![game](https://user-images.githubusercontent.com/14877471/125543091-e87510f8-89c1-4db3-a47b-da60728c5bf3.png)

![playing](https://user-images.githubusercontent.com/14877471/125543110-6db2ee59-dc85-4a90-9481-a3bcebf9b604.png)
</details>

2021-07-14 09:46 UTC, Bas950 requested changes
Add more to the presence, right now it's too low quality to be accepted.

2021-07-14 09:46 UTC, Bas950 commented on websites/G/GeForce NOW/dist/metadata.json
> +  "readLogs": false
```suggestion
  "category": "games"
```

2021-07-14 09:49 UTC, Pepijn98 commented
> Add more to the presence, right now it's too low quality to be accepted.

What else is there to add? You play games on GeForce NOW that's it.

2021-07-14 09:55 UTC, Bas950 commented
> > Add more to the presence, right now it's too low quality to be accepted.
> 
> What else is there to add? You play games on GeForce NOW that's it.

hmm yea I can't look at the website myself since I use edge which isn't supported xD

2021-07-17 16:43 UTC, Bas950 commented on websites/G/GeForce NOW/presence.ts
> +  else delete presenceData.startTimestamp;
```suggestion
    showTimestamp: boolean = await presence.getSetting("timestamp"),
    presenceData: PresenceData = {
      largeImageKey: "logo",
      smallImageKey: "small",
      startTimestamp: browsingStamp
    };

  if (!showTimestamp) delete presenceData.startTimestamp;
```

2021-07-18 12:41 UTC, SlowLife1661 approved these changes

2021-07-18 20:24 UTC, Bas950 approved these changes

2021-07-18 20:24 UTC, merged