Add GoFundMe presence
PreMiD/Presences pull request #4116
Opened 2021-07-16 16:03 UTC by jaydenkoh

<details>
<summary>Proof (expand):</summary>

<br>

Homepage
![wdPmh19wWc](https://user-images.githubusercontent.com/66878523/125975506-22d28b97-bf7e-4feb-a91e-3f4782edc78d.png)

Search
![KsM0tN3pvY](https://user-images.githubusercontent.com/66878523/125975610-f340f617-227d-4adb-a4f9-648e7c3ed8e3.png)

Viewing at a fundraiser
![r9P1lD7oXh](https://user-images.githubusercontent.com/66878523/125976087-104daf00-6e51-4fda-aa2a-5c9e745362cf.png)

</details>

2021-07-17 01:10 UTC, jaydenkoh commented
#3816

2021-07-17 16:45 UTC, Bas950 requested changes

2021-07-17 16:45 UTC, Bas950 commented on websites/G/GoFundMe/presence.ts
> +    data.details = "Viewing at a fundraiser:";
```suggestion
    data.details = "Viewing fundraiser:";
```

2021-07-17 16:45 UTC, Bas950 commented on websites/G/GoFundMe/presence.ts
> +        label: "Visit fundraiser",
```suggestion
        label: "View fundraiser",
```

2021-07-18 20:12 UTC, Bas950 submitted a review, later dismissed

2021-07-20 02:21 UTC, SlowLife1661 approved these changes

2021-07-20 13:24 UTC, jaydenkoh commented
Closes #3816

2021-07-21 13:45 UTC, Bas950 approved these changes

2021-07-21 13:45 UTC, merged