Add megastudy presence
PreMiD/Presences pull request #4121
Opened 2021-07-18 19:53 UTC by 1LUXION

> **megastudy** is the largest Internet lecture service in South Korea.
> I made the presence of megastudy in order to motivate students of Korea,
> so it may be difficult to review my code since it is made for Korean Site and Korean Students.
> I'm sorry for the inconvenience, and I appreciate reviewers' hard work.

### Home Screen
![home](https://user-images.githubusercontent.com/32902575/126079806-a5d76b8c-9fc7-4919-9c67-cbd2ed176b18.png)

###  Lecture Room
![lecture](https://user-images.githubusercontent.com/32902575/126079815-1c02eb95-1581-48e9-b983-e4e91118e660.png)

###  Lecture Paused
![lecture paused](https://user-images.githubusercontent.com/32902575/126079812-7e62a38e-8b52-4708-9d25-963452c529b7.png)

###  Lecture Playing
![lecture playing](https://user-images.githubusercontent.com/32902575/126079813-6ae1989c-57ed-4da0-9333-08a34c93bd74.png)

2021-07-19 04:00 UTC, SlowLife1661 reviewed
Add support for all sub-pages?

2021-07-19 10:09 UTC, Bas950 requested changes
Fix codacy issues

2021-07-19 10:09 UTC, Bas950 commented on websites/M/megastudy/dist/metadata.json
> +  "service": "megastudy",
```suggestion
  "service": "megastudy",
  "altnames": ["메가스터디"],
```

2021-07-19 11:34 UTC, 1LUXION commented
> Fix codacy issues

@Bas950 all fixed, thanks for adding alternative service name

2021-07-19 17:10 UTC, 1LUXION commented
> Add support for all sub-pages?

@SlowLife1661 Added support for most of sub pages as long as I can, but its technically hard to add all sub pages since megastudy changes Sub Page Structure every time they recruit a new teacher or offer a new course.

2021-07-20 02:25 UTC, SlowLife1661 approved these changes, later dismissed

2021-07-21 13:44 UTC, Bas950 requested changes
Set browsingstamp once at the start, instead of in every if case.

2021-07-21 15:33 UTC, 1LUXION commented
> Set browsingstamp once at the start, instead of in every if case.

@Bas950 Simplified all statements and assignments

2021-07-21 15:52 UTC, Bas950 approved these changes

2021-07-22 06:06 UTC, SlowLife1661 approved these changes

2021-07-22 06:06 UTC, merged