Add Hachisuka Scans presence
PreMiD/Presences pull request #4123
Opened 2021-07-19 07:14 UTC by Yuujet

Home page print
![image](https://user-images.githubusercontent.com/42509424/126118073-1eabbbc0-e720-4713-980f-cc1d99e4c1a2.png)

Manga Page Print
![image](https://user-images.githubusercontent.com/42509424/126118095-608017b1-6964-4de0-b9cb-33077450f176.png)

Read Page Print
![image](https://user-images.githubusercontent.com/42509424/126118101-7aa32749-7ef4-4e80-af77-2a6e17247561.png)

2021-07-19 07:58 UTC, Yuujet commented
Lol CodeFactor hates me, it's not possible kekw

2021-07-19 10:05 UTC, Bas950 commented on websites/H/Hachisuka Scans/dist/metadata.json
> +  "version": "1.0.8",
```suggestion
  "version": "1.0.0",
```

2021-07-21 13:43 UTC, Bas950 requested changes
Use classnames in querySelector to get the text you want, right now it's just so unreadable

2021-07-21 13:43 UTC, Bas950 commented on websites/H/Hachisuka Scans/presence.ts
> +      presenceData.buttons = [{label: "Hachisuka Scans",url: document.URL}];
buttons are not allowed to direct to the homepage

2021-07-21 13:43 UTC, Bas950 commented on websites/H/Hachisuka Scans/presence.ts
> +      presenceData.state = null;
never set null, use 
delete presenceData.details

2021-07-26 15:54 UTC, Bas950 requested changes
Please run prettier

2021-08-03 04:15 UTC, SlowLife1661 commented
Hi, I'm closing this as it has been inactive over 7 days

2021-08-03 04:15 UTC, closed without merging