AniCloud 1.0.4
PreMiD/Presences pull request #4126
Opened 2021-07-20 00:42 UTC by Emijor

I have changed a few things

2021-07-20 02:32 UTC, SlowLife1661 commented on websites/A/Anicloud/presence.ts
> +      currentTime = video.currentTime;
```suggestion
      timeEnd = video.duration;
      ({currentTime} = video);
```

2021-07-20 02:32 UTC, SlowLife1661 commented on websites/A/Anicloud/presence.ts
> +        data.endTimestamp = timestamps[1];
```suggestion
        [, data.endTimestamp] = timestamps;
```

2021-07-20 02:34 UTC, SlowLife1661 requested changes
bump version and would be good if you run prettier on your code

2021-07-20 17:28 UTC, SlowLife1661 approved these changes, later dismissed

2021-07-21 13:47 UTC, Bas950 requested changes
Upload proof of it working

2021-07-21 13:53 UTC, Emijor commented
![image](https://user-images.githubusercontent.com/55028218/126499891-68ffca1f-e7ad-4560-94e4-50ee0f5247f7.png)


![image](https://user-images.githubusercontent.com/55028218/126500129-8933e7e1-ee06-4465-ba16-9e1d14668ace.png)

![image](https://user-images.githubusercontent.com/55028218/126500208-bc2601d8-55af-4895-b648-50886dd48833.png)

2021-07-21 13:58 UTC, Emijor commented
![image](https://user-images.githubusercontent.com/55028218/126500928-1e04b33b-8570-4c31-a607-1f572cef7dc4.png)

![image](https://user-images.githubusercontent.com/55028218/126501016-65c76013-f4fc-4f8c-a778-6efc28619886.png)

2021-07-21 15:50 UTC, Bas950 approved these changes

2021-07-22 06:07 UTC, SlowLife1661 approved these changes

2021-07-22 06:07 UTC, merged