Update MangaWorld presence
PreMiD/Presences pull request #4130
Opened 2021-07-21 13:00 UTC by TheTecnoKing

Remade the MangaWorld presence to support their new website.
### Screenshots:
<details>
<summary>Homepage</summary>

![homepage](https://i.imgur.com/7Bik4Yc.png)
</details>

<details>
<summary>Bookmarks</summary>

*   Main ![bookmarks](https://i.imgur.com/6zVbMQ5.png)
*   Reading ![bookmarks_reading](https://i.imgur.com/Sy64xAO.png)
*   Completed ![bookmarks_completed](https://i.imgur.com/SdFGDy6.png)
*   Paused ![bookmarks_paused](https://i.imgur.com/nd8MQKy.png)
*   Plan to read ![bookmarks_plantoread](https://i.imgur.com/Bi8P5bW.png)
*   Dropped ![bookmarks_dropped](https://i.imgur.com/FHdKZSY.png)
*   Re-reading ![bookmarks_rereading](https://i.imgur.com/s2puB8u.png)
</details>

<details>
<summary>Archive</summary>

*   Main ![archive](https://i.imgur.com/Zm1rYmw.png)
*   Search ![archive_search](https://i.imgur.com/5fpecRV.png)
*   Sort by artist ![archive_artist](https://i.imgur.com/1AzVCpw.png)
*   Sort by author ![archive_author](https://i.imgur.com/WvkYE7M.png)
*   Sort by genre ![archive_genre](https://i.imgur.com/vNsxN7e.png)
*   Sort by type ![archive_type](https://i.imgur.com/6M9yZ8m.png)
*   Sort by status ![archive_status](https://i.imgur.com/ypTyAXh.png)
*   Sort by year ![archive_year](https://i.imgur.com/1Ol82RH.png)
*   Order by ![archive_orderby](https://i.imgur.com/kTlrt5h.png)
</details>

<details>
<summary>Reading</summary>

*   Main ![reading](https://i.imgur.com/NCwfNgh.png)
*   In the e-reader ![reading_ereader](https://i.imgur.com/UtSyJi7.gif) *Broken embed due to "Content length exceeded", please click [this](https://i.imgur.com/UtSyJi7.gif) instead.*
*   "Read along!" button ![reading_readalong](https://i.imgur.com/YcylRXx.gif)
</details>

<details>
<summary>Other pages</summary>

![otherpages](https://i.imgur.com/OUtVZWo.png)
</details>

2021-07-21 13:50 UTC, Bas950 requested changes
Fix errors reported by the bots

2021-07-21 13:50 UTC, Bas950 commented on websites/M/MangaWorld/dist/metadata.json
> +  "version": "3.0.6",
```suggestion
  "version": "3.0.0",
```

2021-07-21 14:33 UTC, TheTecnoKing commented
Do I have to fix all the indentation and curly brace warnings as well?
I left the braces not on the same line with the next block on purpose, so I could write comments for each section.

2021-07-21 15:51 UTC, Bas950 commented
> Do I have to fix all the indentation and curly brace warnings as well?
> I left the braces not on the same line with the next block on purpose, so I could write comments for each section.
> @Bas950

Yes, please use our prettier settings etc.
You can also put the comment in the first line after the if case

2021-07-22 12:35 UTC, Bas950 commented on websites/M/MangaWorld/presence.ts
> +  if (data.details !== null) {
```suggestion
  if (data.details) {
```

2021-07-23 17:55 UTC, SlowLife1661 approved these changes

2021-07-24 15:39 UTC, Bas950 approved these changes

2021-07-24 15:43 UTC, merged