Add LABY.net
PreMiD/Presences pull request #4133
Opened 2021-07-21 17:49 UTC by Northernside

LABY.net is a web-based lookup tool for Minecraft accounts & capes; LabyMod cloaks & statistics; and even more!

2021-07-21 17:53 UTC, Bas950 requested changes

2021-07-21 17:53 UTC, Bas950 commented on websites/L/LABY.net/dist/metadata.json
> +    "thumbnail": "https://cdn.discordapp.com/attachments/260475731182616576/862003257693175808/labynet_announcement.png",
upload to imgur

2021-07-21 17:53 UTC, Bas950 commented on websites/L/LABY.net/dist/metadata.json
> +      "en": "LABY.net is a web-based lookup tool for Minecraft accounts & capes; LabyMod cloaks & statistics; and even more!"
```suggestion
      "en": "A modern & fast Minecraft profile search. Find skins, capes, servers, statistics and more on LABY.net"
```

2021-07-21 17:58 UTC, Northernside commented on websites/L/LABY.net/dist/metadata.json
> +    "thumbnail": "https://cdn.discordapp.com/attachments/260475731182616576/862003257693175808/labynet_announcement.png",
Done

2021-07-21 18:07 UTC, Bas950 commented
Upload proof of the presence working

2021-07-21 18:09 UTC, Northernside commented
> Upload proof of the presence working

Should I send screenshots of every presence state or just one?

2021-07-21 18:09 UTC, Bas950 commented
> > Upload proof of the presence working
> 
> Should I send screenshots of every presence state or just one?

At least 2 or 3

2021-07-21 18:13 UTC, Northernside commented
> > > Upload proof of the presence working
> > 
> > 
> > Should I send screenshots of every presence state or just one?
> 
> At least 2 or 3

https://imgur.com/a/AwH91E7 there are 3 screenshots uploaded

2021-07-21 18:14 UTC, Bas950 submitted a review, later dismissed

2021-07-22 06:05 UTC, SlowLife1661 requested changes

2021-07-22 06:05 UTC, SlowLife1661 commented on websites/L/LABY.net/presence.ts
> +  if(presenceData.details === null) {
```suggestion
  if(!presenceData.details) {
```

2021-07-22 12:36 UTC, Bas950 commented on websites/L/LABY.net/presence.ts
> +  // I just did what Codacy told me even though it looks weird lol
```suggestion
  }),
  browsingStamp = Math.floor(Date.now() / 1000);
```
Just ignore it if it errors about it again.

2021-07-22 12:42 UTC, Bas950 approved these changes

2021-07-22 13:15 UTC, SlowLife1661 approved these changes

2021-07-22 13:15 UTC, merged