Add 대성마이맥(mimacstudy) Presence
PreMiD/Presences pull request #4141
Opened 2021-07-23 02:13 UTC by 1LUXION

> **대성마이맥(mimacstudy)** is the Internet lecture service in South Korea.
> I made the presence of 대성마이맥(mimacstudy) in order to motivate students of Korea,
> so it may be difficult to review my code since it contains several strings written in Korean.
> I'm sorry for the inconvenience, and I appreciate reviewers' hard work.

### Home Screen
![home](https://user-images.githubusercontent.com/32902575/126730022-b260113c-bd6b-4ab2-ac9e-10a67be01754.png)

###  Lecture Room
![lecture](https://user-images.githubusercontent.com/32902575/126730030-65d203b6-1458-4e62-841c-829931652fc4.png)

###  Teacher Room
![teacher](https://user-images.githubusercontent.com/32902575/126730034-fd8be1f5-98ca-4fb8-8e33-207f9e9ad927.png)

###  Lecture Paused
![lecture paused](https://user-images.githubusercontent.com/32902575/126730027-491b1497-76ec-489a-9705-64b3e0719947.png)

###  Lecture Playing
![lecture playing](https://user-images.githubusercontent.com/32902575/126730028-74e57f56-08ea-4117-a41e-65b57332745e.png)

2021-07-23 07:05 UTC, SlowLife1661 approved these changes

2021-07-23 07:05 UTC, SlowLife1661 commented on websites/#/대성마이맥/presence.ts
> +  if (presenceData.details === null) {
```suggestion
  if (!presenceData.details) {
```

2021-07-23 07:07 UTC, SlowLife1661 requested changes

2021-07-23 07:07 UTC, SlowLife1661 commented on websites/#/대성마이맥/presence.ts
> +  if (presenceData.details === null) {
```suggestion
  if (!presenceData.details) {
```

2021-07-23 07:15 UTC, 1LUXION commented
@SlowLife1661 Committed Requested Change

2021-07-23 07:17 UTC, SlowLife1661 approved these changes

2021-07-24 15:31 UTC, Bas950 approved these changes
LGTM

2021-07-24 15:31 UTC, merged