Add ReadComicsOnline Presence
PreMiD/Presences pull request #4145
Opened 2021-07-24 14:59 UTC by vahya

Closes #4143 

![Screenshot 2021-07-24 202230](https://user-images.githubusercontent.com/85792429/126872390-67f94c7c-af6e-42e9-945d-705115ac9444.png)
![Screenshot 2021-07-24 202259](https://user-images.githubusercontent.com/85792429/126872392-ee9a3a71-9599-4e2e-a574-d8da919d120d.png)
![Screenshot 2021-07-24 202324](https://user-images.githubusercontent.com/85792429/126872393-12fb9e6f-7c1e-48c4-9e89-f51320c8a17d.png)
![Screenshot 2021-07-24 202354](https://user-images.githubusercontent.com/85792429/126872397-be20098e-bcf8-40d2-8170-50dd80efb175.png)
![Screenshot 2021-07-24 202445](https://user-images.githubusercontent.com/85792429/126872398-4c8bb927-7e73-4da4-8c76-d1d8807da9da.png)
![Screenshot 2021-07-24 202512](https://user-images.githubusercontent.com/85792429/126872399-21d45893-892e-4eba-bebd-686b0b164540.png)
![Screenshot 2021-07-24 202530](https://user-images.githubusercontent.com/85792429/126872400-5c0a68f2-3474-4e5c-9386-493732169dcf.png)

2021-07-24 15:51 UTC, Bas950 requested changes
Please make sure the cookies meet our requirements and explain why they are needed and how they kinda work lmao

2021-07-24 15:51 UTC, Bas950 commented on websites/R/ReadComicsOnline/dist/metadata.json
> +    "en": "ReadComicsOnline - Read High Quality Comics Online"
```suggestion
    "en": "Read comics online in high quality. Free download high quality comics."
```

2021-07-24 16:08 UTC, vahya commented
>Please make sure the cookies meet our requirements

Keys prefixed with ``PMD_`` 👍 

>explain why they are needed and how they kinda work

The site doesn't show what the user searched for when showing results, so whatever the user is searching for is stored in a cookie beforehand so it can be shown in the presence afterwards, when the results are shown on the website.

2021-07-25 14:24 UTC, SlowLife1661 commented on websites/R/ReadComicsOnline/presence.ts
> +                url: location.href
Why is the one above "Read" but the one buttom "Check" xd

2021-07-25 14:25 UTC, SlowLife1661 commented
As for cookies fine by me of maybe add some sort of setting

2021-07-25 18:55 UTC, Bas950 commented
> As for cookies fine by me or maybe add some sort of setting

yea fine by me too, just fix the error mentioned above

2021-07-26 07:58 UTC, vahya commented
I've added settings for disabling cookies.

2021-07-26 15:56 UTC, Bas950 approved these changes

2021-07-27 01:29 UTC, SlowLife1661 approved these changes

2021-07-27 01:29 UTC, merged