Autocode.com | New Presence
PreMiD/Presences pull request #4146
Opened 2021-07-24 17:07 UTC by CTK-WARRIOR

**Website** : https://autocode.com

**About** : Autocode is an API-native re-imagining of the software delivery process.
It's a web editor, runtime for apps, and hosting platform that treats the API as the foundational primitive of web development. It comes packaged with its very own Standard Library that anybody can contribute to.

**Screen Shots**
![](https://cdn.discordapp.com/attachments/864317795805954059/868539506964434994/unknown.png)

![](https://cdn.discordapp.com/attachments/864317795805954059/868539735411408966/unknown.png)

2021-07-25 16:52 UTC, SlowLife1661 commented on websites/A/Autocode/presence.ts
> +}), supportedLanguages: Array<string> = [ "js", "md", "json", "gitignore", "txt", "html", "css"];
You don't really have to give it a type here, just a comment no change is required

2021-07-25 16:52 UTC, SlowLife1661 approved these changes

2021-07-25 16:55 UTC, SlowLife1661 requested changes

2021-07-25 16:55 UTC, SlowLife1661 commented on websites/A/Autocode/dist/metadata.json
> +  "tags": ["code", "IDE", "editor"],
```suggestion
  "tags": ["code", "ide", "editor"],
```

2021-07-25 17:01 UTC, SlowLife1661 approved these changes, later dismissed

2021-07-25 18:59 UTC, Bas950 requested changes

2021-07-25 18:59 UTC, Bas950 commented on websites/A/Autocode/dist/metadata.json
> +  "altnames": ["standard library", "stdlib", "acode"],
```suggestion
```

2021-07-25 18:59 UTC, Bas950 commented on websites/A/Autocode/dist/metadata.json
> +  "altnames": ["standard library", "stdlib", "acode"],
you can add those as tags

2021-07-26 15:51 UTC, Bas950 approved these changes

2021-07-27 01:28 UTC, SlowLife1661 approved these changes

2021-07-27 01:28 UTC, merged