Hypixel API • Reborn docs is moved to new domain.
PreMiD/Presences pull request #4152
Opened 2021-07-26 07:17 UTC by StavZ

2021-07-26 15:55 UTC, Bas950 requested changes
upload proof of it working

2021-07-26 15:55 UTC, Bas950 commented on websites/H/Hypixel API Reborn/dist/metadata.json
> +    "en": "Hypixel API • Reborn is feature-rich Hypixel API wrapper for Node.js.",
```suggestion
    "en": "Hypixel API • Reborn is a feature-rich Hypixel API wrapper for Node.js.",
```

2021-07-27 04:10 UTC, StavZ commented
![image](https://user-images.githubusercontent.com/36641973/127094000-647422e7-b7ea-48f3-9c4b-6cef6e5ac6f8.png)

2021-07-27 05:23 UTC, SlowLife1661 commented
Nope we need you to show that Presence is still working on these new domains

2021-07-27 06:48 UTC, StavZ commented
![image](https://user-images.githubusercontent.com/36641973/127108653-a11b637b-e254-4c92-8d74-748e911dd48e.png)

2021-07-27 07:21 UTC, SlowLife1661 approved these changes

2021-07-28 14:29 UTC, Bas950 approved these changes

2021-07-28 14:29 UTC, merged