Add Goodreads presence!
PreMiD/Presences pull request #4155
Opened 2021-07-26 18:54 UTC by ThiaudioTT

Heyo.

I made a Goodreads presence 👍

<details>
  <summary>Screenshots</summary>

![Screenshot_1](https://user-images.githubusercontent.com/43919529/127041331-1251cfe9-1d46-4ab0-a410-2fdfa461d842.png)

![Screenshot_2](https://user-images.githubusercontent.com/43919529/127041337-e95d8deb-bf16-4f79-9412-8acee31a0dff.png)

![Screenshot_3](https://user-images.githubusercontent.com/43919529/127041340-e0858835-893d-4fad-8544-08e884e59c4d.png)

![Screenshot_4](https://user-images.githubusercontent.com/43919529/127041341-8113c12b-73c7-483f-809b-54efb721362f.png)

![Screenshot_5](https://user-images.githubusercontent.com/43919529/127041343-e1d2c626-31ed-4283-a8a2-2b106319ac49.png)

![Screenshot_6](https://user-images.githubusercontent.com/43919529/127041345-51b50a04-bfd3-4ac4-8267-dda053ebb482.png)

![Screenshot_7](https://user-images.githubusercontent.com/43919529/127041347-bf53e608-a4b3-4f2a-87e5-2f20161a012f.png)

![Screenshot_8](https://user-images.githubusercontent.com/43919529/127041349-39786c36-6a3f-4723-8b9b-817866d8196d.png)

![Screenshot_9](https://user-images.githubusercontent.com/43919529/127041351-4d35ea0d-0891-4e44-aa8a-b531017eef8f.png)

![Screenshot_10](https://user-images.githubusercontent.com/43919529/127041354-16b742ba-0ca3-4509-925d-b9ee02a49e4a.png)

![Screenshot_11](https://user-images.githubusercontent.com/43919529/127041357-ca6a39c3-a821-40ee-adfb-37b8550fa0ec.png)

![Screenshot_12](https://user-images.githubusercontent.com/43919529/127041360-b9e0b766-af09-42c1-b35d-47fba3d636c5.png)

![Screenshot_13](https://user-images.githubusercontent.com/43919529/127041362-6bf4b481-3af1-4cae-b5f5-5a75aee4a283.png)

![Screenshot_14](https://user-images.githubusercontent.com/43919529/127041364-1bb37ec0-eb32-4184-ada3-a6417d2d718b.png)

![Screenshot_15](https://user-images.githubusercontent.com/43919529/127041366-8e170d44-3674-4c49-bad2-87c881ab1944.png)

![Screenshot_16](https://user-images.githubusercontent.com/43919529/127041370-1d2fa759-a9dc-497e-99c4-33e9562f6b3a.png)

![Screenshot_17](https://user-images.githubusercontent.com/43919529/127041371-b4b9375e-43da-47e5-8476-bb9cdbca4da0.png)

![Screenshot_18](https://user-images.githubusercontent.com/43919529/127042065-a7786611-d09b-4e51-b07b-6af25bad2aa4.png)

</details>

2021-07-27 15:59 UTC, ThiaudioTT commented
35bc1b96d81a13860d8e57436274ba6f3cbee5b0

i forgor about private profiles, but now are solved:
<details>
<summary>Print</summary>

![Screenshot_20](https://user-images.githubusercontent.com/43919529/127185509-227df4df-186d-4755-b01d-e10363715f27.png)

</details>

2021-07-28 12:31 UTC, SlowLife1661 commented on websites/G/Goodreads/presence.ts
> +    presenceData.details = "Browsing a book:";
```suggestion
    presenceData.details = "Viewing a book:";
```

2021-07-28 12:31 UTC, SlowLife1661 commented on websites/G/Goodreads/dist/metadata.json
> +  "thumbnail": "https://s.gr-assets.com/assets/facebook/goodreads_wide-e23f6858b6bf20dcaf8493237a214a0e.png",
Upload to imgur

2021-07-28 12:32 UTC, SlowLife1661 commented on websites/G/Goodreads/presence.ts
> +    presenceData.details = "Browsing a profile:";
```suggestion
    presenceData.details = "Viewing a profile:";
```

2021-07-28 12:34 UTC, SlowLife1661 commented on websites/G/Goodreads/presence.ts
> +  };
```suggestion
let book: string,
  author: string,
  timeElapsed = Math.floor(Date.now() / 1000);
 
presence.on("UpdateData", async () => {

  const presenceData: PresenceData = {
    largeImageKey: "goodreads",
    details: "Browsing Goodreads",
    startTimestamp: timeElapsed
  };
```

2021-07-28 14:03 UTC, ThiaudioTT commented on websites/G/Goodreads/presence.ts
> +    presenceData.details = "Browsing a book:";
Thanks!

2021-07-28 14:31 UTC, SlowLife1661 commented on websites/G/Goodreads/presence.ts
> +  timeElapsed: number = Math.floor(Date.now() / 1000);
```suggestion
const presence = new Presence({clientId: "867525909204566056"}),
  timeElapsed: number = Math.floor(Date.now() / 1000);

let book: string,
  author: string;
```

2021-07-28 14:35 UTC, Bas950 requested changes
use .textContent instead of .innerText

2021-07-28 15:19 UTC, Isa27-0 commented
Presence Request that must be linked: #2247

2021-07-28 16:11 UTC, ThiaudioTT commented
https://github.com/PreMiD/Presences/pull/4155#issuecomment-888397267
> Presence Request that must be linked: #2247


Thanks!
fix #2247

2021-07-29 16:57 UTC, Bas950 approved these changes

2021-07-29 17:14 UTC, SlowLife1661 approved these changes

2021-07-29 17:15 UTC, merged