✨ Subso
PreMiD/Presences pull request #4170
Opened 2021-07-30 18:58 UTC by callumok2004

![image](https://user-images.githubusercontent.com/35779365/127699385-8314a94b-f2ed-4f28-b21d-83e6ea224960.png)
![image](https://user-images.githubusercontent.com/35779365/127699425-f37a26b7-e201-4fe2-9f07-e70ac2584ba2.png)
![image](https://user-images.githubusercontent.com/35779365/127699471-99cfdf9c-15e5-4be6-9385-666c7d2a2ab8.png)
![image](https://user-images.githubusercontent.com/35779365/127699472-974a9ec2-4fb2-4cc3-8e84-1d22c9237ec9.png)

2021-07-31 12:24 UTC, Bas950 requested changes

2021-07-31 12:24 UTC, Bas950 commented on websites/S/Subso/presence.ts
> +
```suggestion
```

2021-07-31 17:51 UTC, Bas950 approved these changes

2021-08-01 00:48 UTC, SlowLife1661 approved these changes

2021-08-01 00:48 UTC, merged