Created Animekimi presence
PreMiD/Presences pull request #4172
Opened 2021-07-31 05:30 UTC by Faelayis

2021-07-31 08:36 UTC, Faelayis commented
Use array destructuring bug ?

2021-07-31 08:51 UTC, SlowLife1661 commented
ไม่ใช่บัคมันคือ code style

2021-07-31 08:58 UTC, Faelayis commented
> ไม่ใช่บัคมันคือ code style

จำเป็นต้องแก้ไหมอะมันจะผ่านหรือเปล่า

2021-07-31 09:02 UTC, SlowLife1661 requested changes

2021-07-31 09:02 UTC, SlowLife1661 commented on websites/A/Animekimi/presence.ts
> +
```ts
  const presenceData: PresenceData = {
    largeImageKey: "site",
    startTimestamp: browsingStamp
  };
```

Just delete this function and use `presenceData.details = "something";`

2021-07-31 09:40 UTC, Faelayis commented
ขอบคุณครับ @SlowLife1661 <3

2021-07-31 09:47 UTC, SlowLife1661 commented on websites/A/Animekimi/dist/metadata.json
> +  "thumbnail": "https://imgur.com/eeLOziv",
```suggestion
  "logo": "https://i.imgur.com/tSmgmK1.jpg",
  "thumbnail": "https://i.imgur.com/eeLOziv.jpg",
```

2021-07-31 09:48 UTC, SlowLife1661 requested changes

2021-07-31 09:48 UTC, SlowLife1661 commented on websites/A/Animekimi/presence.ts
> +      presenceData.details = ("ประเภท ");
ลบวงเล็บออกให้หมด

2021-08-01 04:20 UTC, SlowLife1661 commented on websites/A/Animekimi/presence.ts
> +  if (path.hostname === "animekimi.com" || path.hostname.includes("www.")) {
Not necessary

2021-08-01 17:17 UTC, SlowLife1661 approved these changes

2021-08-01 21:50 UTC, Bas950 approved these changes

2021-08-01 21:50 UTC, merged