Update Animekimi presence
PreMiD/Presences pull request #4192
Opened 2021-08-02 05:24 UTC by Faelayis

- Added setting Privacy Mod
- Added setting Show timestamps
- Fixed wrong github source page not found
![Animation](https://user-images.githubusercontent.com/48393914/127808169-5580dee6-da48-4950-9abc-6b4723159997.gif)

2021-08-02 12:04 UTC, Bas950 requested changes

2021-08-02 12:04 UTC, Bas950 commented on websites/A/Animekimi/presence.ts
> +  if (time) presenceData.startTimestamp = browsingStamp;
```suggestion
```
unneeded, set at line 45 and removed if !time at line 144

2021-08-03 03:54 UTC, SlowLife1661 commented on websites/A/Animekimi/presence.ts
> +  }
Buttons are not allowed in home page

2021-08-03 03:56 UTC, SlowLife1661 commented on websites/A/Animekimi/presence.ts
> +  }
Basically show nothing? I wouldn't want it to show nothing even If I want privacy

2021-08-03 16:36 UTC, SlowLife1661 approved these changes

2021-08-05 18:46 UTC, Bas950 requested changes

2021-08-05 18:46 UTC, Bas950 commented on websites/A/Animekimi/presence.ts
> +  }
???, privacy mode = disable presence?

2021-08-05 18:55 UTC, Bas950 commented on websites/A/Animekimi/presence.ts
> +  }
I am dome I read it as details, ignore me

2021-08-05 18:55 UTC, Bas950 approved these changes

2021-08-05 18:55 UTC, merged