Add Red Bull TV Presence
PreMiD/Presences pull request #4209
Opened 2021-08-05 07:47 UTC by vahya

![Screenshot 2021-08-05 131159](https://user-images.githubusercontent.com/85792429/128311916-488e1610-2a92-4145-8e79-3eb645d3f50e.png)
![Screenshot 2021-08-05 131231](https://user-images.githubusercontent.com/85792429/128311925-58db6ace-60cd-4612-b5f6-ae85b274fbda.png)
![Screenshot 2021-08-05 131256](https://user-images.githubusercontent.com/85792429/128311929-024b7483-7baf-4569-9df4-b6b96f0302aa.png)
![Screenshot 2021-08-05 131325](https://user-images.githubusercontent.com/85792429/128311933-43725e8a-5ffc-4199-a904-d85130c64805.png)
![Screenshot 2021-08-05 131351](https://user-images.githubusercontent.com/85792429/128311937-5f773895-7eac-4211-83d1-3521f215844e.png)
![Screenshot 2021-08-05 131432](https://user-images.githubusercontent.com/85792429/128311940-83d921b6-2792-476d-a8a0-786f5576be0e.png)

Closes #4206

2021-08-05 08:05 UTC, kkrypt0nn commented
Thanks!
Looked at the code and have seen that you have "Looking at article {article}" when you're _reading_ an article, would be nice to have "Reading article {article}" instead :)

2021-08-05 18:49 UTC, Bas950 requested changes
Support all pages not just red bull tv? Since its all on the same domain as the drink etc. (no <tv>.redbull.com).

2021-08-08 06:17 UTC, vahya commented
> Support all pages not just red bull tv? Since its all on the same domain as the drink etc. (no .redbull.com).

All the pages are supported 😅

2021-08-08 16:04 UTC, Bas950 commented
> > Support all pages not just red bull tv? Since its all on the same domain as the drink etc. (no .redbull.com).
> 
> All the pages are supported 😅

https://www.redbull.com/nl-nl/energydrink
https://www.redbull.com/nl-nl/energydrink/red-bull-red-edition
https://www.redbull.com/nl-nl/energydrink/red-bull-red-edition-ingredienten

dont think these pages are supported, and rename it to just Redbull, like I said support the whole redbull website, not just the TV section.

2021-08-09 13:52 UTC, Bas950 requested changes

2021-08-09 13:52 UTC, Bas950 commented on websites/R/Red Bull/dist/metadata.json
> +  "logo": "https://i.imgur.com/sAxySI0.png",
update logo so it isnt only for redbulltv

2021-08-09 13:52 UTC, Bas950 commented on websites/R/Red Bull/dist/metadata.json
> +  "logo": "https://i.imgur.com/sAxySI0.png",
Same with banner and presence assets

2021-08-10 13:09 UTC, Bas950 approved these changes

2021-08-10 13:20 UTC, Slowlife01 approved these changes

2021-08-10 13:20 UTC, merged