More permanent fix AnimeDigitalNetwork
PreMiD/Presences pull request #4212
Opened 2021-08-05 11:45 UTC by DarkVillager

Resolves #3832
Metadata.json:
- Bumped version (big fix).
- Added new tag.
Presence.ts:
- Added new way to get title.
- Added that it shows the title & episode number even if it isnt playing
- Fixed all bugs

![image](https://user-images.githubusercontent.com/42322979/128344510-373393fa-f6f8-49da-8e58-07e65acc4c94.png)
![image](https://user-images.githubusercontent.com/42322979/128344548-ccdb3185-5144-4585-9748-8e160bd5b74c.png)
![image](https://user-images.githubusercontent.com/42322979/128344569-5582ad51-d1c9-4337-be7f-721effad6984.png)
![image](https://user-images.githubusercontent.com/42322979/128344594-385fd759-167b-48e1-b8e7-0f7f15e578eb.png)
![image](https://user-images.githubusercontent.com/42322979/128344613-109a6d4d-fbd5-4eb3-9134-4b408805a2be.png)

2021-08-05 13:06 UTC, SlowLife1661 commented
fix indent

2021-08-05 13:41 UTC, SlowLife1661 approved these changes, later dismissed

2021-08-05 13:42 UTC, SlowLife1661 commented on websites/A/AnimeDigitalNetwork/presence.ts
>    if (presenceData.details === null) {
```suggestion
  if (!presenceData.details) {
```

2021-08-05 13:43 UTC, SlowLife1661 submitted a review, later dismissed

2021-08-05 18:52 UTC, Bas950 requested changes

2021-08-05 18:52 UTC, Bas950 commented on websites/A/AnimeDigitalNetwork/presence.ts
>          );
might as well use presence.getMediaTimestamps or it's called something like that.

2021-08-08 16:06 UTC, Bas950 requested changes
Add a setting to toggle buttons

2021-08-08 16:06 UTC, Bas950 commented on websites/A/AnimeDigitalNetwork/presence.ts
> +          label: "Watch",
```suggestion
          label: "Watch Episode",
```

2021-08-08 16:06 UTC, Bas950 commented on websites/A/AnimeDigitalNetwork/presence.ts
> +          label: "Check Out",
```suggestion
          label: "View Page",
```

2021-08-08 16:06 UTC, Bas950 commented on websites/A/AnimeDigitalNetwork/presence.ts
> +      ];
```suggestion
```

2021-08-08 16:06 UTC, Bas950 commented on websites/A/AnimeDigitalNetwork/presence.ts
> +          label: "Check Out",
```suggestion
          label: "View Page",
```

2021-08-08 16:06 UTC, Bas950 commented on websites/A/AnimeDigitalNetwork/presence.ts
> +    ];
```suggestion
```

2021-08-09 15:44 UTC, Bas950 commented on websites/A/AnimeDigitalNetwork/presence.ts
>    }
are you sure this should be in an else?

2021-08-10 12:57 UTC, Bas950 commented
Upload new proof because of last commit.

2021-08-10 13:05 UTC, DarkVillager commented
![image](https://user-images.githubusercontent.com/42322979/128871873-93684e0a-987f-4190-a1a5-5843c67aa9f1.png)

2021-08-10 13:24 UTC, Bas950 commented
One that doesn't just say browsing...

2021-08-11 11:10 UTC, Slowlife01 commented on websites/A/AnimeDigitalNetwork/presence.ts
> +        "#root > div > div > div.sc-pkSvE.kPCOPp > div > div:nth-child(1) > script"
How about using instead? And there are many more other ways to get this JSON
```js
document.querySelector('[type="application/ld+json"]')
```

2021-08-11 11:10 UTC, Slowlife01 commented on websites/A/AnimeDigitalNetwork/presence.ts
> +          "#root > div > div > div.sc-qPmLO.gspUft > div > div > div.sc-qXiOn.iVbXhX > script"
Same with above

2021-08-11 11:10 UTC, Bas950 commented on websites/A/AnimeDigitalNetwork/presence.ts
> +          "#root > div > div > div.sc-qPmLO.gspUft > div > div > div.sc-qXiOn.iVbXhX > script"
Shouldnt you use nth:child or something that is more against the class name changes.

2021-08-13 07:43 UTC, DarkVillager commented
I can’t work on this till Monday just to let the mods know.

2021-08-16 17:06 UTC, Bas950 approved these changes

2021-08-16 17:09 UTC, Slowlife01 approved these changes

2021-08-16 17:09 UTC, merged