Created BetterDiscord presence
PreMiD/Presences pull request #4214
Opened 2021-08-06 05:02 UTC by Faelayis

- Added setting buttons
- Added setting Show timestamps

<details>
<summary>
Preview
</summary>
<br>

![image](https://user-images.githubusercontent.com/48393914/128458315-8beb9b3f-e189-4ac3-9853-32167eb0b3b6.png)![image](https://user-images.githubusercontent.com/48393914/128458344-74a694e2-b41e-49df-ad33-0faf07449ad2.png)![image](https://user-images.githubusercontent.com/48393914/128458356-e250c7d0-15dd-4a21-bcc7-1f8bffad982e.png)![image](https://user-images.githubusercontent.com/48393914/128458370-d34d16e5-e2f4-43ce-a982-6719ec5072fe.png)![image](https://user-images.githubusercontent.com/48393914/128458392-ae7896f1-da4d-40dd-873d-e243e4f6b5bd.png)![image](https://user-images.githubusercontent.com/48393914/128458433-3d8cde76-2eb5-41e9-98bc-6f135d242c24.png)![image](https://user-images.githubusercontent.com/48393914/128458399-4dc33890-ff50-4cd1-becd-ce9cf84f3b33.png)

</details>

2021-08-07 21:09 UTC, Bas950 requested changes

2021-08-07 21:09 UTC, Bas950 commented on websites/B/BetterDiscord/dist/metadata.json
> +  "iframe": false,
```suggestion
```

2021-08-07 21:09 UTC, Bas950 commented on websites/B/BetterDiscord/presence.ts
> +  // Const thing
```suggestion
```

2021-08-08 16:01 UTC, Bas950 approved these changes

2021-08-08 16:56 UTC, SlowLife1661 approved these changes

2021-08-08 16:56 UTC, merged

2021-08-10 01:42 UTC, Isa27-0 commented
Can the site be accepted by PreMiD? Because the BD is against Discord rules (TOS)

2021-08-10 03:03 UTC, Faelayis commented
> Can the site be accepted by PreMiD? Because the BD is against Discord rules (TOS), and there are even warnings that the PreMiD application does not work on modifiers, on the Discord server.

oh yeah I didn't think about that🤔

2021-08-10 12:54 UTC, Slowlife01 commented
With the current guidelines it's totally fine