Created KickAssFingers presence
PreMiD/Presences pull request #4219
Opened 2021-08-07 17:05 UTC by eBeckrs

Created the first version of kickassfingers.com presence.

Screenshots showing a side-by-side comparison of my profile and the website:
![screenshot](https://user-images.githubusercontent.com/88587278/128607929-305626d9-c3a1-44a0-8dc2-917526329dd8.png)

2021-08-07 21:19 UTC, Bas950 requested changes
run prettier with our settings.

2021-08-07 21:19 UTC, Bas950 commented on websites/K/KickAssFingers/dist/metadata.json
> +  "altnames": ["KAF"],
```suggestion
```

2021-08-07 21:19 UTC, Bas950 commented on websites/K/KickAssFingers/dist/metadata.json
> +    "it": "Un sito di test di battitura con una moderna interfaccia e una esperienza utente personalizzabile. Testa tua velocità di battitura in diversi tipi di test, guadagna punti, vinci medaglie e
```suggestion
    "en": "Test your typing speed on a different typing tests, earn points, win medals and climb the rankings.",
    "it": "Needs updating..."
```

2021-08-07 21:19 UTC, Bas950 commented on websites/K/KickAssFingers/presence.ts
> +   presenceData.startTimestamp = time;
```suggestion
   const presenceData: PresenceData = {
      largeImageKey: "logo",
      startTimestamp: time
   };
```

2021-08-07 21:19 UTC, Bas950 commented on websites/K/KickAssFingers/presence.ts
> +   if(presenceData.details === null) {
```suggestion
   if(!presenceData.details) {
```

2021-08-08 16:03 UTC, Bas950 requested changes

2021-08-08 16:03 UTC, Bas950 commented on websites/K/KickAssFingers/dist/metadata.json
> +  "service": "KickassFingers",
Service and folder name must be 100% the same (caps included)

2021-08-08 16:03 UTC, Bas950 commented on websites/K/KickAssFingers/presence.ts
> +    live = JSON.parse(data.getAttribute("liveScores"));
```suggestion
    data = document.querySelector("#premIdVars"),
    vars = JSON.parse(data.getAttribute("vars")),
    live = JSON.parse(data.getAttribute("liveScores"));
```

2021-08-09 13:39 UTC, Bas950 approved these changes

2021-08-09 14:48 UTC, Slowlife01 approved these changes

2021-08-09 14:49 UTC, merged