Updated Maki.gg
PreMiD/Presences pull request #4222
Opened 2021-08-08 12:39 UTC by M5rian

Added missing pages & Made presence more detailed

2021-08-08 16:09 UTC, Bas950 requested changes
Fix errors, bump version, make sure the presence follows all guidelines, upload proof of it working

2021-08-08 16:58 UTC, SlowLife1661 commented
Buttons are not allowed on home page

2021-08-08 17:00 UTC, M5rian commented
Can I add them everywhere except the homepage?

2021-08-08 17:05 UTC, SlowLife1661 commented
Yes, *read the guidelines*

2021-08-08 17:07 UTC, SlowLife1661 commented on websites/M/Maki.gg/dist/metadata.json
>    "logo": "https://i.imgur.com/xzx4dEZ.gif",
```suggestion
  "logo": "https://i.imgur.com/xzx4dEZ.png",
```

2021-08-08 17:14 UTC, M5rian commented
Oh, sorry I didn't read the guildlines carefully

2021-08-08 17:20 UTC, M5rian commented
Can somebody help me with the CodeFactor? It says Autofix available, but I can't find out how to autofix my issues.

2021-08-09 02:54 UTC, SlowLife1661 commented
again read the guidelines promote the site with buttons is not allowed either

2021-08-09 02:57 UTC, SlowLife1661 commented
> Can somebody help me with the CodeFactor? It says Autofix available, but I can't find out how to autofix my issues.

just check on Codacy

2021-08-09 09:43 UTC, M5rian commented
I’ll send a proof of it working later

2021-08-09 13:44 UTC, Bas950 requested changes

2021-08-09 13:44 UTC, Bas950 commented on websites/M/Maki.gg/presence.ts
> +    const [ButtonData, ButtonData] = {
yea that wont work...

2021-08-09 16:30 UTC, M5rian commented
Here is a proof it it working. Do you guys need more than one image? I fixed the final things I saw and in my browser everything seems to work without errors. I'm sorry that acted a bit dumb, never made a pull request before and it was a bit confusing that I seem to miss a few things.

![image](https://user-images.githubusercontent.com/69646823/128740671-84673801-dc21-499c-806f-eac535c802b5.png)

I hope you all are having a great day.
Thanks

2021-08-10 12:27 UTC, Quintenvw commented
Original author and developer of Maki.gg here, I asked Marian to update this presence. It all seems to work and all web pages have been added to the presence.

2021-08-10 13:22 UTC, Slowlife01 commented on websites/M/Maki.gg/presence.ts
> +  if (presenceData.details === null) {
```suggestion
  if (!presenceData.details) {
```

2021-08-11 10:09 UTC, Slowlife01 approved these changes

2021-08-11 10:46 UTC, M5rian commented
Doesn't mean approved, that you accepted the changes? Oh no what have I done

2021-08-11 10:47 UTC, Bas950 commented
> Doesn't mean approved, that you accepted the changes? Oh no what have I done

Yea SlowLife accepted it, but you need 2 accepts to get it merged.

2021-08-11 10:48 UTC, M5rian commented
oh, I see. I think I reopened it. I'm sorry

2021-08-11 10:49 UTC, Bas950 approved these changes

2021-08-11 10:49 UTC, merged

2021-08-11 10:49 UTC, M5rian commented
😮 First pull request. Thank you guys.