Deezer - Own mp3s now work for the presence.
PreMiD/Presences pull request #4223
Opened 2021-08-08 12:46 UTC by DarkVillager

Resolves #3906
- Added check to see if the link for the song exists, if it doesnt then it shows a playbutton with a link for local uploaded songs.
![image](https://user-images.githubusercontent.com/42322979/128632438-115e3b84-eed6-4bb3-a625-c448a4f424af.png)

2021-08-08 16:11 UTC, Bas950 requested changes
that should work the same?

2021-08-08 16:11 UTC, Bas950 commented on websites/D/Deezer/presence.ts
> +      if (!showLink) showLink = null;
```suggestion
```

2021-08-08 16:11 UTC, Bas950 commented on websites/D/Deezer/presence.ts
> +      if (showLink !== null) {
```suggestion
      if (showLink) {
```

2021-08-09 15:42 UTC, Bas950 approved these changes

2021-08-10 13:29 UTC, Slowlife01 approved these changes

2021-08-10 13:29 UTC, merged