Created AnimesOnline presence
PreMiD/Presences pull request #4231
Opened 2021-08-09 10:04 UTC by Faelayis

Created AnimesOnline presence
- Added setting buttons
- Added setting Show timestamps

2021-08-09 13:50 UTC, Bas950 requested changes
Please make your code a bit cleaner, it looks like it uses a lot of useless variables.

2021-08-09 13:50 UTC, Bas950 commented on websites/A/AnimesOnline/dist/metadata.json
> +    "pt_BR": "Site de animes legendado em português. Assista em FULLHD, HD e SD.!"
```suggestion
    "pt_BR": "Animes Online em FULLHD, HD e SD, escolha o anime de sua preferencia e assista legendado ou dublado! Acesse agora é gratuito!"
```

2021-08-09 13:50 UTC, Bas950 commented on websites/A/AnimesOnline/iframe.ts
> +    video = document.querySelector(".html5-video-container > video");
```suggestion
  const video: HTMLVideoElement = document.querySelector(".jw-video") || document.querySelector(".html5-video-container");
```
This should work but test if it actually does!

2021-08-09 13:50 UTC, Bas950 commented on websites/A/AnimesOnline/presence.ts
> +      presenceData.state = episode;
info is not set?

2021-08-09 13:50 UTC, Bas950 commented on websites/A/AnimesOnline/presence.ts
> +      filmes = titlemovie;
seems like a useless extra const?

2021-08-09 13:50 UTC, Bas950 commented on websites/A/AnimesOnline/presence.ts
> +      presenceData.state = episode;
```suggestion
      [presenceData.details] = info;
      presenceData.state = `Episódio ${info.pop()}`;
```

2021-08-09 14:52 UTC, Faelayis commented
> Please make your code a bit cleaner, it looks like it uses a lot of useless variables.
Sorry, I tested so much that I forgot to pay attention.

2021-08-09 15:58 UTC, Bas950 requested changes

2021-08-09 15:58 UTC, Bas950 commented on websites/A/AnimesOnline/presence.ts
> +  path = document.location;
there should be inside updatedata

2021-08-09 15:58 UTC, Bas950 commented on websites/A/AnimesOnline/dist/metadata.json
> +    "pt_BR": "Animes Online em FULLHD, HD e SD, escolha o anime de sua preferencia e assista legendado ou dublado! Acesse agora é gratuito!!"
```suggestion
    "pt_BR": "Animes Online em FULLHD, HD e SD, escolha o anime de sua preferencia e assista legendado ou dublado! Acesse agora é gratuito!"
```

2021-08-10 13:18 UTC, Slowlife01 reviewed
~~Are you sure there's no grammar error on those strings~~

2021-08-10 13:18 UTC, Slowlife01 commented on websites/A/AnimesOnline/presence.ts
> +    browsingStamp = Math.floor(Date.now() / 1000),
Move it outside

2021-08-10 13:25 UTC, Bas950 commented on websites/A/AnimesOnline/presence.ts
> +    browsingStamp = Math.floor(Date.now() / 1000),
Yea browsing stamp should stay outside.

2021-08-10 13:28 UTC, Faelayis commented on websites/A/AnimesOnline/presence.ts
> +    browsingStamp = Math.floor(Date.now() / 1000),
What should I do 😅😅

2021-08-10 13:30 UTC, Bas950 requested changes
Afterwards upload new proof

2021-08-10 13:30 UTC, Bas950 commented on websites/A/AnimesOnline/presence.ts
> +  });
```suggestion
  }),
  browsingStamp = Math.floor(Date.now() / 1000);
```

2021-08-10 13:30 UTC, Bas950 commented on websites/A/AnimesOnline/presence.ts
> +    browsingStamp = Math.floor(Date.now() / 1000),
```suggestion
```

2021-08-14 05:55 UTC, Faelayis commented
> Afterwards upload new proof

![image](https://user-images.githubusercontent.com/48393914/129435643-fabd302c-8456-4823-8efb-f64774383d4a.png)
![image](https://user-images.githubusercontent.com/48393914/129435657-82b8d1a4-48ee-4dcd-9571-f4eeacf6f5d7.png)
![image](https://user-images.githubusercontent.com/48393914/129435644-6e484061-3b42-48d9-986b-151d94b0cbd9.png)
![image](https://user-images.githubusercontent.com/48393914/129435649-56f8030e-ff50-4fa4-8cea-bfa002c635d9.png)
![image](https://user-images.githubusercontent.com/48393914/129435666-dfee1f14-ef9e-41d7-b860-5a811f2a51be.png)
![image](https://user-images.githubusercontent.com/48393914/129435654-d0e1aee0-c023-40be-a270-59aa96393aa8.png)

2021-08-14 06:03 UTC, Slowlife01 approved these changes

2021-08-14 13:19 UTC, Bas950 approved these changes

2021-08-14 13:19 UTC, merged