✨ Added Hiven Presence
PreMiD/Presences pull request #4258
Opened 2021-08-16 15:00 UTC by OfficialCRUGG

This PR adds a Presence for Chat Platform Hiven.

Screenshots:
![image](https://user-images.githubusercontent.com/25248999/129584714-60b57ea3-18ba-4e0c-a15e-3243a2596f51.png)
![image](https://user-images.githubusercontent.com/25248999/129584751-48fba14e-6d6e-4d04-a149-2406980597af.png)
![image](https://user-images.githubusercontent.com/25248999/129584775-c021623f-50f4-4946-bf8d-2a8825aceef6.png)

2021-08-16 17:10 UTC, Bas950 requested changes
kinda low quality presence, can you add more to it?

2021-08-16 17:10 UTC, Bas950 commented on websites/H/Hiven/dist/metadata.json
> +    "logo": "https://i.imgur.com/uwQcgk5.jpg",
logo must be at least 512x512

2021-08-16 17:16 UTC, OfficialCRUGG commented
Will update the logo for this one in a bit too.
As for content: I don't know what else there'd be to add. Except maybe show whether the user is in a voice call or not, but I currently have nobody to test this with. But once I'd have someone to test this with, I'd have added it anyways.

2021-08-16 17:37 UTC, OfficialCRUGG commented
Just noticed there might be some more things I could add, though. Will do another commit shortly.

2021-08-17 06:39 UTC, Slowlife01 commented on websites/H/Hiven/presence.ts
> +        presenceData.state = undefined;
```suggestion
        delete presenceData.state;
```

2021-08-18 20:21 UTC, Bas950 requested changes
format it a bit too many empty lines...

2021-08-19 00:27 UTC, Slowlife01 commented on websites/H/Hiven/presence.ts
> +
```suggestion
```

2021-08-19 00:27 UTC, Slowlife01 commented on websites/H/Hiven/presence.ts
> +
```suggestion
```

2021-08-19 09:58 UTC, Slowlife01 approved these changes

2021-08-19 13:47 UTC, Bas950 approved these changes

2021-08-19 13:47 UTC, merged