Harmony
PreMiD/Presences pull request #4265
Opened 2021-08-17 14:23 UTC by mrmaxmysterious

2021-08-17 18:01 UTC, EncryptedDev requested changes
Quite a poor presence, look on my suggested changes and think about redoing said sections

2021-08-19 14:39 UTC, Slowlife01 commented
Add support for audio (timestamp etc), and for sub-pages too

2021-08-20 22:06 UTC, EncryptedDev requested changes

2021-08-20 22:06 UTC, EncryptedDev commented on websites/H/HarmonyRadio/dist/metadata.json
> +    ],
Only one URL so this will do: 
```suggestion
    "url":
      "weareharmony.net"
```

2021-08-20 22:26 UTC, EncryptedDev commented on websites/H/HarmonyRadio/presence.ts
> +        presenceData.details = "Harmony - Maintenance";
Remove and add to the `presenceData` object

2021-08-20 22:26 UTC, EncryptedDev commented on websites/H/HarmonyRadio/presence.ts
> +        presenceData.largeImageKey = "default";
Remove and add to the presenceData object

2021-08-24 06:08 UTC, Slowlife01 commented
No activity

2021-08-24 06:08 UTC, closed without merging