Backpack.tf (with huge changes and improvements)
PreMiD/Presences pull request #4274
Opened 2021-08-19 14:17 UTC by Ali-Joon

So I had worked on this long time ago but after some time I was busy with my exams and left this off and the pull request has been rejected then I completely forgot about it. Basically, this Presence is for the website backpack.tf, the biggest trading and price listing website for the game tf2.
It's been months since I left this presence development. until a few days ago which I went back. I've been working on it again and now this time, It works.
I'll send some proof images too. Hope everything is enough and good to go.
![pre1](https://user-images.githubusercontent.com/48525075/130084561-9bb34b5f-7425-4d93-b1e9-65241b871b1f.PNG)
![pre2](https://user-images.githubusercontent.com/48525075/130084639-edcd9cf5-6897-4e81-8ad5-b8bf12850cb4.PNG)

2021-08-19 14:27 UTC, EncryptedDev requested changes
You need to fix all those CodeFactor notices too!

2021-08-19 14:27 UTC, EncryptedDev commented on websites/B/backpack.tf/dist/metadata.json
> +  "version": "1.0.1",
Why are you starting on 1.0.1?
```suggestion
  "version": "1.0.0",
```

2021-08-19 17:26 UTC, Slowlife01 commented on websites/B/backpack.tf/presence.ts
> +    sec: any;
No any

2021-08-19 17:26 UTC, Slowlife01 commented on websites/B/backpack.tf/presence.ts
> +  if (document.location.hostname === "backpack.tf") {
You don't need this

2021-08-19 17:26 UTC, Slowlife01 commented on websites/B/backpack.tf/presence.ts
> +  if (presenceData.details === null) {
```suggestion
  if (!presenceData.details) {
```

2021-08-20 06:27 UTC, Slowlife01 approved these changes

2021-08-20 17:00 UTC, Bas950 approved these changes

2021-08-20 17:00 UTC, merged