Add Toonily Presence
PreMiD/Presences pull request #4278
Opened 2021-08-20 11:06 UTC by vahya

Closes #4253

![Screenshot 2021-08-20 162945](https://user-images.githubusercontent.com/85792429/130224353-8b8dda37-03f3-4560-b4e3-b29bde0efec9.png)
![Screenshot 2021-08-20 163026](https://user-images.githubusercontent.com/85792429/130224361-0fa02daa-9b53-4dd1-8f1a-700e4a400b60.png)
![Screenshot 2021-08-20 163054](https://user-images.githubusercontent.com/85792429/130224363-65576e1c-0cfe-4403-8079-b7ea2122e70e.png)
![Screenshot 2021-08-20 163120](https://user-images.githubusercontent.com/85792429/130224365-5568f9b2-782e-4140-b59b-3eef99060224.png)
![Screenshot 2021-08-20 163144](https://user-images.githubusercontent.com/85792429/130224368-7e70b21f-b79a-4458-8825-b0d29355778c.png)
![Screenshot 2021-08-20 163206](https://user-images.githubusercontent.com/85792429/130224373-0a8911c2-9e36-44b5-b762-f8119dbf6b0f.png)
![Screenshot 2021-08-20 163246](https://user-images.githubusercontent.com/85792429/130224375-e97a00cc-53a4-4a7f-9183-1ac494087775.png)
![Screenshot 2021-08-20 163313](https://user-images.githubusercontent.com/85792429/130224376-dc12c50d-7d84-4b55-9b5b-c7ec3c266c73.png)
![Screenshot 2021-08-20 163352](https://user-images.githubusercontent.com/85792429/130224378-d704af82-2fad-404f-8793-f073de8c2558.png)

2021-08-20 17:02 UTC, Bas950 requested changes, later dismissed

2021-08-20 17:02 UTC, Bas950 commented on websites/T/Toonily/dist/metadata.json
> +    "en": "Read English Translated Manga For Free For The Fans"
```suggestion
    "en": "Read your favorite Manhua and Manhwa translated to english for free. Read Manga, Manhua, Manhwa Online, Free webtoon Online, Updated Daily!"
```

2021-08-21 04:17 UTC, Slowlife01 reviewed
"Read Summary" sounds better to me

2021-08-21 08:12 UTC, Slowlife01 approved these changes

2021-08-21 08:27 UTC, Bas950 approved these changes

2021-08-21 08:27 UTC, merged