Some changes to my Presences
PreMiD/Presences pull request #4279
Opened 2021-08-20 18:40 UTC by OfficialCRUGG

This PR simply just deletes the TordorAPI Presence (the website doesn't exist anymore) and changes the URLs of all images that were still hosted on crugg.de to Imgur.

The images themselves should not have changed (as long as I haven't mixed up any links)

2021-08-20 20:12 UTC, EncryptedDev submitted a review, later dismissed
lgtm

2021-08-20 20:25 UTC, StrikerFRFX submitted a review, later dismissed

2021-08-20 21:48 UTC, Bas950 requested changes
bump version

2021-08-20 21:53 UTC, OfficialCRUGG commented
@Bas950 Was planning to do that but seems like I kinda forgot. Is this fine now? :)

2021-08-20 21:53 UTC, Bas950 approved these changes

2021-08-21 03:54 UTC, Slowlife01 approved these changes

2021-08-21 03:54 UTC, merged