Rockstar Games Files Added
PreMiD/Presences pull request #4282
Opened 2021-08-21 14:34 UTC by bobsterjsdev

This is for the rockstar games website (https://www.rockstargames.com) and for subdomains like storerockstargames.com

2021-08-21 14:55 UTC, EncryptedDev requested changes

2021-08-21 14:55 UTC, EncryptedDev commented on websites/R/Rockstar Games/presence.ts
> +  //});
```suggestion
```

2021-08-21 14:55 UTC, EncryptedDev commented on websites/R/Rockstar Games/presence.ts
> +     {hostname} = document.location;
```suggestion
  const presenceData: PresenceData = {
    largeImageKey: "rockstargameshome",
    startTimestamp: browsingTimestamp
  },
     {pathname, hostname} = document.location;
```

2021-08-21 14:55 UTC, EncryptedDev commented on websites/R/Rockstar Games/presence.ts
> +      presenceData.largeImageKey = "rockstargameshome";
There's no need in this if you have defined it on line 13 already
```suggestion
```

2021-08-21 14:55 UTC, EncryptedDev commented on websites/R/Rockstar Games/presence.ts
> +
Remove empty line

2021-08-21 14:55 UTC, EncryptedDev commented on websites/R/Rockstar Games/presence.ts
> +  if (presenceData.details === null) {
```suggestion
  if (!presenceData.details) {
```

2021-08-21 14:55 UTC, EncryptedDev commented on websites/R/Rockstar Games/presence.ts
> +
```suggestion
```

2021-08-21 18:42 UTC, Bas950 requested changes
upload proof of it working

2021-08-21 18:47 UTC, bobsterjsdev commented
![image](https://user-images.githubusercontent.com/73130406/130332011-59f76b49-6ff7-4efe-9d33-aea651e9e178.png)
![image](https://user-images.githubusercontent.com/73130406/130332013-ca26e270-7871-4558-b03b-8d3ba68e2921.png)
![image](https://user-images.githubusercontent.com/73130406/130332015-89c74488-b5ab-429a-90bd-49ebce30f4be.png)

2021-08-21 18:48 UTC, bobsterjsdev commented
This shows the presence of two different sites and shows when viewing a certain page

2021-08-21 18:49 UTC, Slowlife01 commented on websites/R/Rockstar Games/dist/metadata.json
> +  }
`tags` is required

2021-08-21 18:53 UTC, EncryptedDev requested changes
Minor refactoring issues, but otherwise seems fine for me

2021-08-21 18:53 UTC, EncryptedDev commented on websites/R/Rockstar Games/presence.ts
> +
Empty lines
```suggestion
```

2021-08-21 18:53 UTC, EncryptedDev commented on websites/R/Rockstar Games/presence.ts
> +
Empty lines
```suggestion
```

2021-08-21 18:54 UTC, bobsterjsdev commented on websites/R/Rockstar Games/presence.ts
> +
Ok, ill sort these issues out now

2021-08-21 18:59 UTC, Slowlife01 commented on websites/R/Rockstar Games/dist/metadata.json
> +    "thumbnail": "https://i.imgur.com/areSsgy.png",
Better logo? And use the site screenshot instead

2021-08-21 19:09 UTC, bobsterjsdev commented
I tried with a different logo and changed the thumbnail

2021-08-22 00:56 UTC, EncryptedDev commented on websites/R/Rockstar Games/presence.ts
> +    presence.setActivity(presenceData);
```suggestion
  } else presence.setActivity(presenceData);
```

2021-08-22 11:08 UTC, Slowlife01 approved these changes

2021-08-22 14:13 UTC, Bas950 approved these changes

2021-08-22 14:13 UTC, merged