New Presence: AMC+
PreMiD/Presences pull request #4285
Opened 2021-08-22 10:13 UTC by kagbogre

New Presence for the AMC streaming service.

Handles 3 states: browsing catalogue, watching series and watching a movie.

Browsing catalogue:
![image](https://user-images.githubusercontent.com/4789757/130351381-2f2b8a2f-c0d3-4dea-94f7-b576033f84f8.png)

Watching Series:
![image](https://user-images.githubusercontent.com/4789757/130351301-988ae02a-8fbf-4984-9131-b64982a77037.png)

Watching a movie:
![image](https://user-images.githubusercontent.com/4789757/130351329-a145e50b-d9e1-49b6-8bec-09dfa3980d3f.png)

Watching a movie (paused):
![image](https://user-images.githubusercontent.com/4789757/130351342-9660605e-a0ea-47ba-bb27-580099b90fce.png)

Might add buttons in a posterior version.

2021-08-22 11:21 UTC, Slowlife01 commented on websites/A/AMCPlus/presence.ts
> +    startTimestamp = live ? elapsed : timestamps[0];
```suggestion
    if (live) startTimestamp = elapsed;
```

2021-08-22 11:21 UTC, Slowlife01 commented on websites/A/AMCPlus/presence.ts
> +}
Use Presence.getTimestamps() instead

2021-08-22 11:21 UTC, Slowlife01 commented on websites/A/AMCPlus/presence.ts
> +  presence.setActivity(data, video ? !video.paused : true);
```suggestion
  presence.setActivity(data);
```

2021-08-22 14:15 UTC, Bas950 requested changes

2021-08-22 14:15 UTC, Bas950 commented on websites/A/AMCPlus/presence.ts
> +      ),
just use getMediaTimestamps

2021-08-22 16:00 UTC, Slowlife01 approved these changes

2021-08-23 18:49 UTC, Bas950 approved these changes

2021-08-23 18:49 UTC, merged