AnimesGG | Add Presence
PreMiD/Presences pull request #4287
Opened 2021-08-22 15:58 UTC by MMDDKK6500

**This is an Brazilian website, so the presence is in Brazilian Portuguese.**
This is my second presence for PreMiD, I hope I did everything right.

(The website is kind of slow, so it takes a few seconds for the presence to appear)
Proof that it works:
![ezgif com-gif-maker (8)](https://user-images.githubusercontent.com/34542949/130361723-863b6482-c9f6-4c6a-97a1-afe6c9b1d2fe.gif)

2021-08-22 16:15 UTC, Slowlife01 requested changes

2021-08-22 16:15 UTC, Slowlife01 commented on websites/A/AnimesGG/presence.ts
> +    startTimestamp: Math.floor(Date.now() / 1000)
Make a timestamp variable and put it outside then use it here

2021-08-22 16:15 UTC, Slowlife01 commented on websites/A/AnimesGG/presence.ts
> +      [data.startTimestamp, data.endTimestamp] = timestamps;
```suggestion
      [, data.endTimestamp] = timestamps;
```

2021-08-22 16:15 UTC, Slowlife01 commented on websites/A/AnimesGG/presence.ts
> +    [data.startTimestamp, data.endTimestamp] = timestamps;
```suggestion
    [, data.endTimestamp] = timestamps;
```

2021-08-22 16:15 UTC, Slowlife01 commented on websites/A/AnimesGG/presence.ts
> +    const isEpisode = page.includes("/episodio");
You use it only once, I don't get why you have to make it a variable. To make it more readability? If that's the case then sure I guess

2021-08-22 16:15 UTC, Slowlife01 commented on websites/A/AnimesGG/presence.ts
> +      if (showFullName === true && animeTitleFull !== undefined && animeTitleFull !== null && animeTitleFull !== "")
```suggestion
      if (showFullName && animeTitleFull) 
```

2021-08-22 16:15 UTC, Slowlife01 commented on websites/A/AnimesGG/presence.ts
> +    if (showFullName === true && animeTitleFull !== undefined && animeTitleFull !== null && animeTitleFull !== "")
```suggestion
    if (showFullName && animeTitleFull) 
```

2021-08-22 16:15 UTC, Slowlife01 commented on websites/A/AnimesGG/presence.ts
> +    presence.setActivity(data);
```suggestion
  if (data.details && data.state) presence.setActivity(data);
  else presence.setActivity();
```

Set the app icon too if you haven't already

2021-08-22 17:40 UTC, Slowlife01 approved these changes

2021-08-23 18:50 UTC, Bas950 approved these changes

2021-08-23 18:50 UTC, merged