AutoHotkey v2 Documentation Presence
PreMiD/Presences pull request #4296
Opened 2021-08-24 15:15 UTC by KliqxTV

Dunno what to put in here soooooo, uh...
_Should_ technically, hopefully, all be fine. As mentioned in the Contributing guide, will of course fix any mistakes that are pointed out, etc.

2021-08-24 16:04 UTC, EncryptedDev requested changes
pls check my review and check all the codefactor notices, then i'll check again (:

2021-08-24 16:04 UTC, EncryptedDev commented on websites/A/AutoHotkey Documentation/presence.ts
> +        var subMatch = document.location.href.match(new RegExp("#.*"))[0];
array destructing and const instead of var
```suggestion
        const [subMatch] = document.location.href.match(new RegExp("#.*"));
```

2021-08-24 19:06 UTC, KliqxTV commented
Are you for real!? The god-damn indentation?!?!?!

2021-08-24 22:42 UTC, EncryptedDev requested changes
the comments man

2021-08-24 22:42 UTC, EncryptedDev commented on websites/A/AutoHotkey Documentation/presence.ts
> +   This is such basic text retrieval that using the iframe data retrieval method from the documentation would be overkill... */
useless comments

2021-08-24 22:42 UTC, EncryptedDev commented on websites/A/AutoHotkey Documentation/presence.ts
> +  /* Define the "unwanted character" regex here, cause we need that more than once XD */
useless comments

2021-08-24 22:42 UTC, EncryptedDev commented on websites/A/AutoHotkey Documentation/presence.ts
> +    Some headings, such as the one at "Hotkeys.htm", have extra info, like "(Mouse, Joystick and Keyboard Shortcuts)". My initial clean-up method for this was just removing everything from the first
useless comments
```suggestion
```

2021-08-24 22:42 UTC, EncryptedDev commented on websites/A/AutoHotkey Documentation/presence.ts
> +  // Finish piecing the parts of presenceData.state together
same here

2021-08-24 22:42 UTC, EncryptedDev commented on websites/A/AutoHotkey Documentation/presence.ts
> +      // Get the <tr>'s first child node's textContent (which is <td>), then clean it up and trim
same here

2021-08-24 22:42 UTC, EncryptedDev commented on websites/A/AutoHotkey Documentation/presence.ts
> +      // Get a child node of the <div> which's class name contains "head" and retrieve its textContent (this should always be a heading, no clean-up or ellipsis needed)
same here

2021-08-24 22:42 UTC, EncryptedDev commented on websites/A/AutoHotkey Documentation/presence.ts
> +      // Retrieve part of the textContent of the <p> element, truncate at 50 chars and ellipsize
same here

2021-08-24 22:46 UTC, EncryptedDev requested changes
sorry and this

2021-08-24 22:46 UTC, EncryptedDev commented on websites/A/AutoHotkey Documentation/presence.ts
> +   iframeObj = document.querySelector('iframe').contentDocument;
Sorry, forgot this too, you should use this: https://docs.premid.app/en/dev/presence/iframe

2021-08-25 13:04 UTC, Bas950 requested changes

2021-08-25 13:04 UTC, Bas950 commented on websites/A/AutoHotkey Documentation/dist/metadata.json
> +    ],
```suggestion
```

2021-08-25 13:04 UTC, Bas950 commented on websites/A/AutoHotkey Documentation/dist/metadata.json
> +    "service": "AHK v2 Documentation",
```suggestion
    "service": "AutoHotkey Documentation",
```

2021-08-25 13:30 UTC, Slowlife01 commented
Hi, unfortunately your Pull Request have been denied due to following reason
* Unqualified site
   * Uses `.github.io` domain which isn't allowed

2021-08-25 13:30 UTC, closed without merging