fix(Jellyfin)
PreMiD/Presences pull request #4302
Opened 2021-08-25 11:41 UTC by Slowlife01

# Jellyfin
![image](https://user-images.githubusercontent.com/54318514/130784386-9336e741-4748-4734-91ee-d24f98467bc9.png)

2021-08-25 11:43 UTC, EncryptedDev requested changes

2021-08-25 11:43 UTC, EncryptedDev commented on websites/J/Jellyfin/presence.ts
>      if (presenceData.details == null) {
```suggestion
    if (!presenceData.details) {
```

2021-08-25 13:07 UTC, Bas950 approved these changes

2021-08-27 10:39 UTC, StrikerFRFX approved these changes

2021-08-27 10:39 UTC, merged