Add Harmony Presence
PreMiD/Presences pull request #4310
Opened 2021-08-30 22:28 UTC by marinofranz

![image](https://user-images.githubusercontent.com/48334228/131413988-dbc7e83a-57e3-4597-8661-06165cc66db0.png)

2021-08-30 22:32 UTC, EncryptedDev requested changes

2021-08-30 22:32 UTC, EncryptedDev commented on websites/H/Harmony/dist/metadata.json
> +    "thumbnail": "https://talk.weareharmony.net/branding/background-nologo.png",
logo and thumbnail must be on imgur, read the guidelines

2021-08-30 22:32 UTC, EncryptedDev commented on websites/H/Harmony/presence.ts
> +  ) {
handled automatically, not needed
```suggestion
  if(document.location.hash.startsWith("#/")) {
```

2021-08-30 22:32 UTC, EncryptedDev commented on websites/H/Harmony/presence.ts
> +  npListeners = 0;
What's the point of pre-assigning this?

2021-08-30 22:32 UTC, EncryptedDev commented on websites/H/Harmony/presence.ts
> +
empty line
```suggestion
```

2021-08-30 22:32 UTC, EncryptedDev commented on websites/H/Harmony/presence.ts
> +
```suggestion
    presence.setActivity(presenceData);
```

2021-08-30 22:38 UTC, EncryptedDev requested changes
prettify your code too

2021-08-30 22:46 UTC, marinofranz commented
I've turned off my computer right now, so at the moment I am unable to

2021-08-31 05:15 UTC, Slowlife01 submitted a review, later dismissed

2021-08-31 08:32 UTC, Bas950 requested changes
> Presences for online radios are only allowed if the radio has at least 100 weekly listeners and 15 concurrent

Upload proof of Harmony meeting this requirement.

2021-08-31 08:32 UTC, Bas950 commented on websites/H/Harmony/dist/metadata.json
> +    "thumbnail": "https://i.imgur.com/7nZITkG.png",
must be a promotional banner or a screenshot of the website homepage.

2021-08-31 15:09 UTC, marinofranz commented
> > Presences for online radios are only allowed if the radio has at least 100 weekly listeners and 15 concurrent
> 
> Upload proof of Harmony meeting this requirement.

https://i.imgur.com/Y4uOnmH.png
I was hoping, since we are very under the limit, you could make a small exception? During the most popular times when DJs are on air, we gain around 13-17 listeners.

2021-09-04 23:36 UTC, EncryptedDev commented
I've checked every day over the last three days and can confirm Harmony does not reach the concurrent listener count

Try again once Harmony has surpassed the requirements as it is not evident Harmony does currently

2021-09-05 00:46 UTC, marinofranz commented
> I've checked every day over the last three days and can confirm Harmony does not reach the concurrent listener count
> 
> Try again once Harmony has surpassed the requirements as it is not evident Harmony does currently

Alright, my apologies
I'll just mark this as a draft and mark it ready for review when we reach the listener count

Thanks

2021-09-05 06:28 UTC, Slowlife01 commented
No draft just open another pull request when it's met the requirements

2021-09-05 06:28 UTC, closed without merging