updated a few pointers to addresses
PreMiD/Presences pull request #4315
Opened 2021-08-31 19:28 UTC by dana0404

the site has some added addresses

2021-09-02 05:14 UTC, Slowlife01 submitted a review, later dismissed
Bump version and show proof of it working

2021-09-02 13:07 UTC, EncryptedDev requested changes

2021-09-02 13:07 UTC, EncryptedDev commented on websites/A/Anime Soul/presence.ts
>    }
```suggestion
presence.setActivity(data)
```

2021-09-05 08:17 UTC, dana0404 commented
![Screenshot from 2021-09-05 03-13-24](https://user-images.githubusercontent.com/55861950/132120299-2ce4df0c-452e-4d47-a5d1-ba58f8ab011a.png)

This is display for a newly added address

2021-09-05 20:57 UTC, EncryptedDev commented
Look back at my review

2021-09-05 21:44 UTC, dana0404 commented
why is it this passes the first time

2021-09-05 21:58 UTC, EncryptedDev requested changes

2021-09-05 21:58 UTC, EncryptedDev commented on websites/A/Anime Soul/presence.ts
> +let presence = new Presence({
```suggestion
const presence = new Presence({
```

2021-09-05 21:58 UTC, EncryptedDev commented on websites/A/Anime Soul/presence.ts
>    }
```suggestion
    presence.setActivity(data);
```

2021-09-06 03:29 UTC, Slowlife01 commented on websites/A/Anime Soul/dist/metadata.json
>    "logo": "https://i.imgur.com/OhVpByX.png",
Must be at least 512x512

2021-09-06 16:07 UTC, Bas950 requested changes

2021-09-06 16:07 UTC, Bas950 commented on websites/A/Anime Soul/presence.ts
> +    data.details = "Viewing Keys Giveaway";
just set startTimestamp at the start

2021-09-06 21:00 UTC, EncryptedDev commented on websites/A/Anime Soul/presence.ts
> +    data.details = "Viewing Keys Giveaway";
then remove curlies

2021-09-14 18:16 UTC, EncryptedDev commented
inactivity?

2021-09-14 18:24 UTC, closed without merging