Add Cosmote TV
PreMiD/Presences pull request #4346
Opened 2021-09-11 00:00 UTC by down-bad

Cosmote TV is a Greek pay television service. This presence should support all functionality of the website, such as watching live TV, replay TV, streaming movies, series, and all the pages of the site.

Home page
![Screenshot 2021-09-11 022045](https://user-images.githubusercontent.com/19146783/132928602-4c28e6c2-a53c-4b74-a582-b178cde743bd.png)
Live TV
![Screenshot 2021-09-11 022340](https://user-images.githubusercontent.com/19146783/132928616-63c15f50-8406-4398-a7a6-ce85fd89538c.png)
Replay TV
![Screenshot 2021-09-11 022501](https://user-images.githubusercontent.com/19146783/132928629-4915f1db-17dd-4960-8634-69dcff682c18.png)
Movie/Series/etc
![Screenshot 2021-09-11 022747](https://user-images.githubusercontent.com/19146783/132928633-aad8370b-59a0-490e-88ef-ee1062f76d6e.png)

2021-09-11 11:53 UTC, down-bad commented
Changes image based on the channel (supports all available channels)

Examples:
![Screenshot 2021-09-11 144757](https://user-images.githubusercontent.com/19146783/132947047-ecfe456b-62c1-49ab-82c3-5d3f3ee8818e.png)
![Screenshot 2021-09-11 144614](https://user-images.githubusercontent.com/19146783/132947049-f84d2d59-3341-421c-a5fd-baf2a9be1e76.png)

2021-09-11 12:01 UTC, EncryptedDev requested changes

2021-09-11 12:01 UTC, EncryptedDev commented on websites/C/Cosmote TV/presence.ts
> +      var series = document.querySelector(
```suggestion
      const series = document.querySelector(
```

2021-09-11 12:01 UTC, EncryptedDev commented on websites/C/Cosmote TV/presence.ts
> +     timestamps = getTimestamps(Math.floor(currentTime), Math.floor(duration)),
```suggestion
     timestamps = presence.getTimestamps(Math.floor(currentTime), Math.floor(duration)),
```

2021-09-11 12:01 UTC, EncryptedDev commented on websites/C/Cosmote TV/presence.ts
> +     {duration} = video,
```suggestion
     { paused, currentTime, duration } = video,
```

2021-09-11 12:01 UTC, EncryptedDev commented on websites/C/Cosmote TV/presence.ts
> +}
```suggestion
```

2021-09-11 21:41 UTC, EncryptedDev requested changes

2021-09-11 21:41 UTC, EncryptedDev commented on websites/C/Cosmote TV/presence.ts
> +
```suggestion
```

2021-09-11 21:41 UTC, EncryptedDev commented on websites/C/Cosmote TV/presence.ts
> +  data.startTimestamp = Math.floor(Date.now() / 1000);
```suggestion
```

2021-09-11 21:41 UTC, EncryptedDev commented on websites/C/Cosmote TV/presence.ts
> +    largeImageKey: "tv"
```suggestion
    largeImageKey: "tv",
    startTimestamp = Math.floor(Date.now() / 1000)
```

2021-09-11 21:41 UTC, EncryptedDev commented on websites/C/Cosmote TV/presence.ts
> +
```suggestion
```

2021-09-11 21:41 UTC, EncryptedDev commented on websites/C/Cosmote TV/presence.ts
> +
```suggestion
```

2021-09-11 21:41 UTC, EncryptedDev commented on websites/C/Cosmote TV/presence.ts
> +    if (live === false) {
```suggestion
    if (!live) {
```

2021-09-11 21:41 UTC, EncryptedDev commented on websites/C/Cosmote TV/presence.ts
> +
```suggestion
```

2021-09-11 21:41 UTC, EncryptedDev commented on websites/C/Cosmote TV/presence.ts
> +    if (channel !== '') {
```suggestion
    if (channel.length === 0) {
```

2021-09-11 21:41 UTC, EncryptedDev commented on websites/C/Cosmote TV/presence.ts
> +      if (live === false)
```suggestion
      if (!live)
```

2021-09-12 09:19 UTC, EncryptedDev commented
Upload further proof of working please

2021-09-12 09:42 UTC, down-bad commented
Home
![Screenshot 2021-09-12 122105](https://user-images.githubusercontent.com/19146783/132982614-7b001153-5276-4622-abed-53326e15ce9b.png)
![Screenshot 2021-09-12 122132](https://user-images.githubusercontent.com/19146783/132982615-d851dae0-3e42-44f7-892f-60b3d774ae18.png)

Channels
![Screenshot 2021-09-12 122154](https://user-images.githubusercontent.com/19146783/132982625-c1ab0e56-89e5-46ca-8858-dd412437c697.png)
![Screenshot 2021-09-12 123623](https://user-images.githubusercontent.com/19146783/132982673-d1b52ce4-a57f-4293-9ff6-9e3085252442.png)

Series
![Screenshot 2021-09-12 123206](https://user-images.githubusercontent.com/19146783/132982688-5f6a2c1e-fea8-4014-a85a-3e43e3de1e15.png)
![Screenshot 2021-09-12 123219](https://user-images.githubusercontent.com/19146783/132982694-8b82fe1a-c31c-4cb1-b6b5-f80dd7227521.png)
etc...

Live TV
![Screenshot 2021-09-12 122344](https://user-images.githubusercontent.com/19146783/132982707-1803ebff-84e2-4f8c-8f1c-23e8bdcfb267.png)
![Screenshot 2021-09-12 123558](https://user-images.githubusercontent.com/19146783/132982710-561c5e3b-fea8-4c43-bcac-01d9327b7411.png)

Replay TV
![Screenshot 2021-09-12 122523](https://user-images.githubusercontent.com/19146783/132982719-f209080c-bf17-4205-8344-975755f242df.png)
![Screenshot 2021-09-12 122538](https://user-images.githubusercontent.com/19146783/132982723-ded1a000-7311-417b-a325-2d46ac9c4c7c.png)

Movie/Series/other
![Screenshot 2021-09-12 123117](https://user-images.githubusercontent.com/19146783/132982740-ad4987bb-b753-41c8-8d35-79f960ee2f0b.png)
![Screenshot 2021-09-12 123043](https://user-images.githubusercontent.com/19146783/132982748-68c2283e-5fc0-481a-a1ff-fcd9d3b4f42c.png)

Paused
![Screenshot 2021-09-12 123954](https://user-images.githubusercontent.com/19146783/132982813-88016aab-a1ad-42df-a2a5-f21247ec594b.png)
![Screenshot 2021-09-12 124009](https://user-images.githubusercontent.com/19146783/132982819-e49542a7-08d6-4609-97ee-8f4a792636eb.png)

2021-09-12 10:52 UTC, EncryptedDev submitted a review, later dismissed
Seems cool with me, await proper approval from maintainers shortly.

2021-09-12 11:54 UTC, Slowlife01 requested changes

2021-09-12 11:54 UTC, Slowlife01 commented on websites/C/Cosmote TV/presence.ts
> +    data.smallImageText = await (await strings).search;
```suggestion
    data.smallImageText = (await strings).search;
```

2021-09-12 11:54 UTC, Slowlife01 commented on websites/C/Cosmote TV/presence.ts
> +  };
```suggestion
  }),
  startedTime = Math.floor(Date.now() / 1000);

presence.on("UpdateData", async () => {
  const data: PresenceData = {
    largeImageKey: "tv",
    startTimestamp: startedTime
  };
```

2021-09-12 11:54 UTC, Slowlife01 commented on websites/C/Cosmote TV/presence.ts
> +          : (await strings).play);
```suggestion
      data.smallImageKey = paused ? "pause" : "play";
      data.smallImageText = paused
          ? (await strings).pause
          : (await strings).play;
```

2021-09-12 11:54 UTC, Slowlife01 commented on websites/C/Cosmote TV/presence.ts
> +        (data.endTimestamp = timestamps[1]);
```suggestion
      data.endTimestamp = timestamps.pop();
```

2021-09-12 11:54 UTC, Slowlife01 commented on websites/C/Cosmote TV/presence.ts
> +          : (await strings).live);
```suggestion
      data.smallImageKey = paused ? "pause" : "live";
      data.smallImageText = paused
          ? (await strings).pause
          : (await strings).live;
```

2021-09-12 11:54 UTC, Slowlife01 commented on websites/C/Cosmote TV/presence.ts
> +    if (channel.length !== 0) {
```suggestion
    if (channel?.length !== 0) {
```

2021-09-12 12:19 UTC, Slowlife01 approved these changes

2021-09-13 16:22 UTC, Bas950 approved these changes

2021-09-18 17:21 UTC, merged