Added Picrew.me support
PreMiD/Presences pull request #4351
Opened 2021-09-12 01:41 UTC by upsetdog

Support for Picrew.me, with a French description as well.

2021-09-12 01:42 UTC, upsetdog commented
Linked to issue #4301

2021-09-12 09:17 UTC, EncryptedDev requested changes

2021-09-12 09:17 UTC, EncryptedDev commented on websites/P/Picrew/presence.ts
> +  data.largeImageKey = "logo";
Move this to the data object on L9
```suggestion
```

2021-09-12 09:17 UTC, EncryptedDev commented on websites/P/Picrew/presence.ts
> +   data: PresenceData = {};
Fix indentation here, but this is better

```suggestion
   data: PresenceData = {
     data.largeImageKey = "logo";
};
```

2021-09-12 09:17 UTC, EncryptedDev commented on websites/P/Picrew/presence.ts
> +  data.startTimestamp = Math.round(startTimestamp / 1000);
Move this to the data object on L9 as well
```suggestion
```

2021-09-12 11:56 UTC, Slowlife01 commented on websites/P/Picrew/presence.ts
> +        const picrewId = pathname.match(/\/image_maker\/([0-9]{0,8})/)[1],
```suggestion
        const [, picrewId] = pathname.match(/\/image_maker\/([0-9]{0,8})/),
```

2021-09-12 12:04 UTC, Slowlife01 requested changes
add support for [support.picrew.me](https://support.picrew.me) too

2021-09-12 12:24 UTC, Slowlife01 commented on websites/P/Picrew/presence.ts
> +    startTimestamp: Math.round(new Date().getTime() / 1000)
No, I meant only startTimestamp

2021-09-15 07:45 UTC, Bas950 requested changes
Upload proof of it working and add more to the presence if possible.

2021-09-15 08:10 UTC, upsetdog commented
> 
> 
> Upload proof of it working and add more to the presence if possible.

it works:
![image](https://user-images.githubusercontent.com/69658702/133394549-bc15ea9d-ec31-484a-a346-f2cbd883cf7e.png)
![image](https://user-images.githubusercontent.com/69658702/133394994-c1b63470-10cc-4028-a2f1-f52c6ef5b355.png)
![image](https://user-images.githubusercontent.com/69658702/133395005-a34e588d-02f8-43b5-9057-abde96f787cc.png)
![image](https://user-images.githubusercontent.com/69658702/133395043-18c2e77b-b9cf-42f0-bbc4-cdb311599825.png)

there's not really much more to add for functionalliy, it has enough at the moment. maybe in the future.
--

and i don't see a reason to add support.picrew.me, because users don't do anything on that sub-domain, but i added it anyway.

2021-09-18 05:39 UTC, upsetdog commented on websites/P/Picrew/presence.ts
> +      details = "searching";
added
![image](https://user-images.githubusercontent.com/69658702/133875820-b8a3cb8d-da39-4815-9012-433ff87a64ed.png)

2021-09-18 14:14 UTC, EncryptedDev requested changes
Fix codefactor issue

2021-09-18 16:31 UTC, closed without merging