Recode bilibili
PreMiD/Presences pull request #4352
Opened 2021-09-12 06:20 UTC by Kotoki1337

solved #2666 

Only important functions are implemented, in order to allow people who download presences in the presences store to use presence again.
I will add other pages later (in other pull requests).

![image](https://user-images.githubusercontent.com/35394151/132974330-f060d9e9-c023-4ccc-9a12-0d5ddbbe0827.png)

2021-09-12 09:12 UTC, EncryptedDev requested changes
Seems like a lot of functionality has been removed, why is this?

2021-09-12 09:12 UTC, EncryptedDev commented on websites/B/bilibili/presence.ts
> +    // presenceData.smallImageText = videoPaused ? (await strings).pause : (await strings).play; Not working due language issues, this issue should fix in extension
Remove comment 
```suggestion
```

2021-09-12 09:12 UTC, EncryptedDev commented on websites/B/bilibili/presence.ts
> +        case "": {
Change this to the default on the switch

2021-09-12 09:12 UTC, EncryptedDev commented on websites/B/bilibili/presence.ts
> +  } else presence.setActivity(presenceData);
```suggestion presence.setActivity(presenceData);
```

2021-09-12 09:12 UTC, EncryptedDev commented on websites/B/bilibili/presence.ts
>      presence.setActivity();
Remove this and just have presence.setActivity(presenceData)

2021-09-12 09:12 UTC, EncryptedDev commented on websites/B/bilibili/dist/metadata.json
> -    "id": "241278257335500811"
Move Bas to contributor

2021-09-12 09:12 UTC, EncryptedDev commented on websites/B/bilibili/presence.ts
>  const presence = new Presence({ clientId: "639591760791732224" }),
If you're now the author, you own the clientId

2021-09-12 09:12 UTC, EncryptedDev commented on websites/B/bilibili/dist/metadata.json
>    },
Have you checked with Bas about the author change?

2021-09-12 09:12 UTC, EncryptedDev commented on websites/B/bilibili/presence.ts
> +    if (video === null) {
```suggestion
    if (!video) {
```

2021-09-12 10:10 UTC, Kotoki1337 commented
> Seems like a lot of functionality has been removed, why is this?

The previous code was too messy, and the bilibili webpage also changed a lot, needed to be recode

2021-09-12 10:48 UTC, EncryptedDev commented
> > Seems like a lot of functionality has been removed, why is this?
> 
> The previous code was too messy, and the bilibili webpage also changed a lot, needed to be recode

I totally understand that, but it seems like you removed a tonne of functionality on top of that? Did the service deprecate most functionality or does the presence support less functionality? 

If you want to recode any presence, you cannot reduce the amount of pages/functions said service supports, you must still support everything. You just need to improve code quality without reducing functionality.

2021-09-12 10:54 UTC, Kotoki1337 commented
> > > Seems like a lot of functionality has been removed, why is this?
> 
> > 
> 
> > The previous code was too messy, and the bilibili webpage also changed a lot, needed to be recode
> 
> 
> 
> I totally understand that, but it seems like you removed a tonne of functionality on top of that? Did the service deprecate most functionality or does the presence support less functionality? 
> 
> 
> 
> If you want to recode any presence, you cannot reduce the amount of pages/functions said service supports, you must still support everything. You just need to improve code quality without reducing functionality. 

I understand what u thought, I want to merge the basic features first. Too many people are coming to me and asking me to fix the presence. If I want to support everything, I'll probably need a few weeks or even a month. So let them use the simplest available one first, and then i gonna add the rest of the features later.

2021-09-12 10:59 UTC, EncryptedDev commented
> > > > Seems like a lot of functionality has been removed, why is this?
> > 
> > 
> > > 
> > 
> > 
> > > The previous code was too messy, and the bilibili webpage also changed a lot, needed to be recode
> > 
> > 
> > I totally understand that, but it seems like you removed a tonne of functionality on top of that? Did the service deprecate most functionality or does the presence support less functionality?
> > If you want to recode any presence, you cannot reduce the amount of pages/functions said service supports, you must still support everything. You just need to improve code quality without reducing functionality.
> 
> I understand what u thought, I want to merge the basic features first. Too many people are coming to me and asking me to fix the presence. If I want to support everything, I'll probably need a few weeks or even a month. So let them use the simplest available one first, and then i gonna add the rest of the features later.

Ah, I see, makes more sense. Let's see what a maintainer would do here though

2021-09-12 12:15 UTC, Slowlife01 commented
No draft, if you are going to add it in this pull request please do it within 7 days if not the current code is fine by me just have to address Rhys's requests

2021-09-12 12:18 UTC, Kotoki1337 commented
> No draft, if you are going to add it in this pull request please do it within 7 days if not the current code is fine by me just have to address Rhys's requests

I'm draft because I'm not at home at the moment to deal with Rhys's review, because I was afraid that someone else would continue to review and cause Rhys's review to be outdated, but I'm home now and I'll be able to finish this pull request soon

2021-09-15 07:47 UTC, Bas950 requested changes

2021-09-15 07:47 UTC, Bas950 commented on websites/B/bilibili/presence.ts
> +      timestamps = presence.getTimestamps(video.currentTime, video.duration);
use getmediatimestamps

2021-09-18 17:12 UTC, Slowlife01 approved these changes

2021-09-18 17:13 UTC, Bas950 approved these changes

2021-09-18 17:14 UTC, merged