EternalNetwork TM Presence
PreMiD/Presences pull request #4353
Opened 2021-09-12 13:57 UTC by TheDjRider

### Tracking for using websites of EternalNetwork TM.
With settings for what part to show and **_multilanguage_** support.

In the next updates probably will be adding buttons to open currently viewed pages and more custom messages for specific places/actions.

![Main](https://i.imgur.com/NMJe67u.png)

Avaiable translaions & changed main logo:
![Main](https://i.imgur.com/xyj7nrj.png)

![Main](https://i.imgur.com/2udRbtg.png)

### **Website:**
![Website](https://i.imgur.com/2kTwXVa.png)

![Website](https://i.imgur.com/GsmG92l.png)

### **Forum:**
![Forum](https://i.imgur.com/Tr0uhT1.png)

![Forum](https://i.imgur.com/3q2gt1s.png)

![Forum](https://i.imgur.com/QAKUG4D.png)

### **Radio**
![Radio](https://i.imgur.com/AWTJq6J.png)

### **Status:**
![Status](https://i.imgur.com/eTCLs8N.png)

2021-09-12 18:00 UTC, EncryptedDev requested changes

2021-09-12 18:00 UTC, EncryptedDev commented on websites/E/EternalNetwork TM/presence.ts
> +      presence.setActivity(presenceData);
```suggestion
      presence.setActivity(presenceData);
```

2021-09-12 18:00 UTC, EncryptedDev commented on websites/E/EternalNetwork TM/presence.ts
> +
```suggestion
```

2021-09-14 18:17 UTC, EncryptedDev commented on websites/E/EternalNetwork TM/presence.ts
> +
```suggestion
```

2021-09-15 07:50 UTC, Bas950 requested changes
Fix errors.

2021-09-16 20:02 UTC, Bas950 requested changes

2021-09-16 20:02 UTC, Bas950 commented on websites/E/EternalNetwork TM/dist/metadata.json
> +  "version": "1.0.1",
```suggestion
  "version": "1.0.0",
```

2021-09-16 20:14 UTC, TheDjRider commented on websites/E/EternalNetwork TM/dist/metadata.json
> +  "version": "1.0.1",
Done.

2021-09-16 20:15 UTC, TheDjRider reviewed
Changes are applied

2021-09-17 12:48 UTC, Bas950 requested changes

2021-09-17 12:48 UTC, Bas950 commented on websites/E/EternalNetwork TM/dist/metadata.json
> +  "service": "EternalNetworkTM",
```suggestion
  "service": "EternalNetwork TM",
```

2021-09-17 13:36 UTC, TheDjRider commented
@Bas950 so what should be the name in **metadata.json** when I check other Presence it has many different variations. 

Mine was **_EternalNetwork TM_**, and the verifier found an error, now is **_EternalNetworkTM_** (without space) and has a problem again.

For example: "_Edge Me Please_" is not a problem and it has spaces and bug letters. 
Where is the problem with mine?

2021-09-17 13:43 UTC, TheDjRider commented on websites/E/EternalNetwork TM/dist/metadata.json
> +  "service": "EternalNetworkTM",
Done

2021-09-18 17:12 UTC, Slowlife01 submitted a review, later dismissed

2021-09-18 17:14 UTC, Bas950 approved these changes

2021-09-18 17:15 UTC, Bas950 requested changes

2021-09-18 17:15 UTC, Bas950 commented on websites/E/EternalNetwork TM/dist/metadata.json
> +    "Forum"
```suggestion
    "community",
    "network",
    "gaming",
    "news",
    "radio",
    "forum"
```

2021-09-18 17:16 UTC, Bas950 approved these changes

2021-09-18 17:16 UTC, Slowlife01 approved these changes

2021-09-18 17:18 UTC, merged