Fixed a type
PreMiD/Presences pull request #4357
Opened 2021-09-13 11:05 UTC by vahya

somthing -> something

2021-09-13 11:06 UTC, vahya commented
I am so sorry for this

2021-09-13 15:12 UTC, plskz commented
bump version

2021-09-13 16:24 UTC, Bas950 requested changes
Bump version

2021-09-14 18:20 UTC, Slowlife01 approved these changes

2021-09-15 07:47 UTC, Bas950 approved these changes

2021-09-15 07:47 UTC, merged