Fix updated selectors
PreMiD/Presences pull request #4360
Opened 2021-09-14 01:30 UTC by dalhaqq

Some pages didnt show the details because Quora made changes to the site so I fix the code to match the new selectors.
![image](https://user-images.githubusercontent.com/63442570/133179657-6a6c5527-fbb7-42b3-8f73-61d924153301.png)
![image](https://user-images.githubusercontent.com/63442570/133179671-d7a6b94b-9f0c-40c4-ab3f-5099c16955ca.png)

2021-09-14 05:31 UTC, Slowlife01 requested changes
and bump version

2021-09-14 05:31 UTC, Slowlife01 commented on websites/Q/Quora/presence.ts
> +    } else if (document.location.pathname == "/") {
```suggestion
    } else if (document.location.pathname === "/") {
```

2021-09-14 18:20 UTC, Slowlife01 approved these changes

2021-09-15 07:47 UTC, Bas950 approved these changes

2021-09-15 07:47 UTC, merged