Desmos Rich Presence
PreMiD/Presences pull request #4363
Opened 2021-09-14 19:21 UTC by Anshroid

Desmos is an online graphing calculator with many other functions, such as a geometry designer and a scientific calculator: desmos.com. This presence is designed to provide information about all functions of the app.

**Screenshots of the Presence in operation:**
![1](https://user-images.githubusercontent.com/29677325/133315157-86555991-8f92-418c-81ec-3c93e373a1c2.png)
![2](https://user-images.githubusercontent.com/29677325/133315158-69beb03a-a419-48c2-b539-8ea55ebdafe2.png)
![3](https://user-images.githubusercontent.com/29677325/133315149-54c68c89-39c0-4478-a0f1-c99b7117acaf.png)
![4](https://user-images.githubusercontent.com/29677325/133315151-2e28c7f0-c278-420b-877f-f6e2cd042add.png)
![5](https://user-images.githubusercontent.com/29677325/133315154-8d290e0a-646b-41f8-8bdb-af3e0c15b097.png)

2021-09-14 19:54 UTC, EncryptedDev requested changes
I can clearly tell you're new to programming and this is very low quality code. Look at my review, fix the things I've pointed out and there is more to look at, just getting too messy and not understandable with so many comments on your code.

_God knows how this passed Codacy, DeepScan and CodeFactor_

2021-09-14 19:54 UTC, EncryptedDev commented on websites/D/Desmos/dist/metadata.json
> +  "$schema": "https://schemas.premid.app/metadata/1.3",
```suggestion
  "$schema": "https://schemas.premid.app/metadata/1.4",
```

2021-09-14 19:54 UTC, EncryptedDev commented on websites/D/Desmos/dist/metadata.json
> +  "thumbnail": "https://i.imgur.com/XzSfNJ3.png",
Thumbnail should be a promotional banner or screenshot of the homepage

2021-09-14 19:54 UTC, EncryptedDev commented on websites/D/Desmos/presence.ts
> +  });*/
Remove comments 
```suggestion
	clientId: "886254740399349852"
  }),
```

2021-09-14 19:54 UTC, EncryptedDev commented on websites/D/Desmos/presence.ts
> +var numEquations: number = 0
Why are you assigning this all to 0 and empty strings?
```suggestion
let url: string, graphing: number, pageType: string, title: string, numEquations: number
```

2021-09-14 19:54 UTC, EncryptedDev commented on websites/D/Desmos/presence.ts
> +    //You can use this to get translated strings in their browser language
```suggestion
```

2021-09-14 19:54 UTC, EncryptedDev commented on websites/D/Desmos/presence.ts
> + numEquations = 0,
What's the point of reassigning them again? 
```suggestion
```

2021-09-14 19:54 UTC, EncryptedDev commented on websites/D/Desmos/presence.ts
> + startTime: number = Date.now();
startTime never changes, using `const` is more conventional
```suggestion
 const startTime: number = Date.now();
```

2021-09-14 19:54 UTC, EncryptedDev commented on websites/D/Desmos/presence.ts
> +
Remove comments
```suggestion
```

2021-09-14 19:54 UTC, EncryptedDev commented on websites/D/Desmos/presence.ts
> +	url = url.substring(0, url.length-1)
Fix indentation

2021-09-14 19:54 UTC, EncryptedDev commented on websites/D/Desmos/presence.ts
> +  var urlPage = splitUrl[splitUrl.length-1]
```suggestion
  let splitUrl = url.split("/"),
   urlPage = splitUrl[splitUrl.length-1];
```

2021-09-14 19:54 UTC, EncryptedDev commented on websites/D/Desmos/presence.ts
> +  }
Fix indenation here, but curlies are not needed as you're just doing one thing
```suggestion
  if (urlPage === "www.desmos.com") pageType = "Home Page" 
  else  pageType = urlPage[0].toUpperCase() + urlPage.substring(1) 
```

2021-09-14 19:54 UTC, EncryptedDev commented on websites/D/Desmos/presence.ts
> +   urlPage = splitUrl[splitUrl.length - 1];
Why have you used the same variable name many times?

2021-09-14 19:54 UTC, EncryptedDev commented on websites/D/Desmos/presence.ts
> +  	pageType = urlPage[0].toUpperCase() + urlPage.substring(1);
I'm getting some crazy deja vu here, why is this the same as L42 - L46

2021-09-14 19:54 UTC, EncryptedDev commented on websites/D/Desmos/presence.ts
> +	numEquations = document.getElementsByClassName("dcg-template-expressioneach")[0].childElementCount;
Fix indentation

2021-09-14 19:54 UTC, EncryptedDev commented on websites/D/Desmos/presence.ts
> +	numEquations = 0
Fix indentation

2021-09-14 19:54 UTC, EncryptedDev commented on websites/D/Desmos/presence.ts
> +  }
Remove curly brackets here where not appropriate

2021-09-14 19:54 UTC, EncryptedDev commented on websites/D/Desmos/presence.ts
> +  };
Move this to the top of the UpdateData event for convention across the repo
```suggestion
  const presenceData: PresenceData = {
	largeImageKey:
	  "logo",
	startTimestamp: startTime
  };
```

2021-09-14 19:54 UTC, EncryptedDev commented on websites/D/Desmos/presence.ts
> +	presenceData.smallImageKey = "logo"
As you've defined this in the presenceData object, you do not have to again
```suggestion
```

2021-09-14 19:54 UTC, EncryptedDev commented on websites/D/Desmos/presence.ts
> +  };
Deja vu, again...

2021-09-14 19:54 UTC, EncryptedDev commented on websites/D/Desmos/presence.ts
> +
Remove empty line

2021-09-14 19:54 UTC, EncryptedDev commented on websites/D/Desmos/presence.ts
> +
Remove empty line

2021-09-14 19:54 UTC, EncryptedDev commented on websites/D/Desmos/presence.ts
> +	presenceData.smallImageKey = "logo";
As you've defined this in the presenceData object, you do not have to again

2021-09-14 19:54 UTC, EncryptedDev commented on websites/D/Desmos/presence.ts
> +
Remove empty line

2021-09-14 19:54 UTC, EncryptedDev commented on websites/D/Desmos/presence.ts
> +
Remove empty line

2021-09-14 19:54 UTC, EncryptedDev commented on websites/D/Desmos/presence.ts
> +  }
```suggestion
	desmosPresence.setActivity(presenceData);
```

2021-09-14 20:09 UTC, Anshroid commented
I think that CodeFactor editing the file itself confused me, so I tried to edit the changes myself as well, and then I ended up with duplicates of everything

2021-09-14 20:35 UTC, EncryptedDev requested changes

2021-09-14 20:35 UTC, EncryptedDev commented on websites/D/Desmos/presence.ts
> +
```suggestion
    presence.setActivity(presenceData);
```

2021-09-14 20:35 UTC, EncryptedDev commented on websites/D/Desmos/presence.ts
> +
Remove empty line

2021-09-15 16:51 UTC, EncryptedDev requested changes

2021-09-15 16:51 UTC, EncryptedDev commented on websites/D/Desmos/dist/metadata.json
> +  "version": "1.0.1",
```suggestion
  "version": "1.0.0",
```

2021-09-15 16:51 UTC, EncryptedDev commented on websites/D/Desmos/presence.ts
> +
empty line

2021-09-15 16:51 UTC, EncryptedDev commented on websites/D/Desmos/presence.ts
> +  };
move this to the top of the UpdateData event

2021-09-16 19:58 UTC, Bas950 approved these changes

2021-09-17 03:09 UTC, Slowlife01 approved these changes

2021-09-17 03:09 UTC, merged