These are the presence files for the website "pronote"
PreMiD/Presences pull request #4383
Opened 2021-09-19 20:48 UTC by Noctuuu

pronote is the n1 website for school informations like grades classes homeworks messages etc...
here you can find a link of all schools in "Lille", a region in france https://www.index-education.com/fr/clients-pronote-12.php#liste
for example here is my school pronote : https://3510001u.index-education.net/pronote/eleve.html
here is a screenshot of most of the functionalities https://i.imgur.com/5fuLKMP.png
it also works with the parent, teachers, administrators sections but i don't have a teacher/admin account so i couldn't take a screenshot.
it's my first time on github so let me know if i have to do something else to publish it.

2021-09-19 20:56 UTC, EncryptedDev requested changes
- Remove the `presence.js` file
- Fix CodeFactor issues

2021-09-19 20:56 UTC, EncryptedDev commented on websites/P/Pronote/dist/metadata.json
> +  "category": "socials & stream",
Invalid category
```suggestion
  "category": "socials",
```

2021-09-19 21:21 UTC, EncryptedDev requested changes
- What is the service actually called? `Pronote` or `Index-education`
- Look at the rest of my review

2021-09-19 21:21 UTC, EncryptedDev commented on websites/P/Pronote/presence.ts
> +}
Camel case; not snake case
```suggestion
function getUrlExtension( url ) {
  return url.split(/[#?]/)[0].split('.').pop().trim();
}

```

2021-09-19 21:21 UTC, EncryptedDev commented on websites/P/Pronote/presence.ts
> +  };
Move this to the top of the UpdateData event so you can do presenceData.smallImageText instead of what you're doing currently

2021-09-19 21:21 UTC, EncryptedDev commented on websites/P/Pronote/presence.ts
> +
You never set the tray title so this check isn't needed
```suggestion
    presence.setActivity(presenceData);
```

2021-09-19 21:56 UTC, Noctuuu commented
The service is called Pronote

2021-09-19 22:29 UTC, Noctuuu commented
The line that resolve the codefactor issue is making a deepscan issue.

2021-09-19 22:34 UTC, EncryptedDev requested changes

2021-09-19 22:34 UTC, EncryptedDev commented on websites/P/Pronote/presence.ts
> +    smallImageText: null,
No need to set these to null as they're already null

2021-09-21 11:28 UTC, Bas950 requested changes

2021-09-21 11:59 UTC, Slowlife01 reviewed
This presence is overall low quality so is there something more you can add

2021-09-22 18:24 UTC, EncryptedDev requested changes

2021-09-22 18:24 UTC, EncryptedDev commented on websites/P/Pronote/presence.ts
> +const LeTimeMicieu = Math.floor(Date.now() / 1000);
Merge this const with the const on like 1

2021-09-23 17:54 UTC, Bas950 requested changes

2021-09-23 17:54 UTC, Bas950 commented on websites/P/Pronote/presence.ts
>      buttons: [
That is not merging the const...

2021-09-23 18:04 UTC, EncryptedDev requested changes

2021-09-23 18:04 UTC, EncryptedDev commented on websites/P/Pronote/presence.ts
> +  if (document.getElementById('breadcrumbBandeau') !== null)
```suggestion
  if (document.getElementById('breadcrumbBandeau')) 
```

2021-09-23 18:04 UTC, EncryptedDev commented on websites/P/Pronote/presence.ts
> +             url: "https://www.index-education.com/fr/logiciel-gestion-vie-scolaire.php"
A very strange URL to link to, but okay

2021-09-23 20:19 UTC, EncryptedDev submitted a review, later dismissed

2021-09-23 21:19 UTC, Kozou4ever commented
Hey! If I may, I don't approve to merge this presence to the official premid store.
The reasons to that decission from mine are simple: 
-First, the presence has not much to offer, the presence is "poor"
-Secondly, it's not really a pronote presence as the presence isn't grabbing pronote feature (it's a js app)
-Finally, each highschool in France has a different pronote app as the sub domain differ for each highschool

2021-09-23 21:50 UTC, EncryptedDev commented
Hello there, 
Unfortunately we will be denying your PR. For the following reasons: 
> -First, the presence has not much to offer, the presence is "poor"
-Secondly, it's not really a pronote presence as the presence isn't grabbing pronote feature (it's a js app)
-Finally, each highschool in France has a different pronote app as the sub domain differ for each highschool

Encrypted

2021-09-23 21:50 UTC, closed without merging

2021-09-25 21:20 UTC, Noctuuu commented
What do you mean ? what can i change ? And about the last part index-education.com says that they host 8000 out of 10000 pronote websites so it should work on 80% of pronote websites.