add support for tweakers
PreMiD/Presences pull request #4385
Opened 2021-09-20 12:49 UTC by bakzkndd

2021-09-20 17:51 UTC, Slowlife01 requested changes
Please run prettier as well

2021-09-20 17:51 UTC, Slowlife01 commented on websites/T/tweakers/presence.ts
> +    } else if(document.location.pathname.split("/")[2] && document.location.pathname.split("/")[2] == "reviews") {
```suggestion
    } else if (document.location.pathname.split("/")[2] && document.location.pathname.split("/")[2] === "reviews") {
```

2021-09-20 17:51 UTC, Slowlife01 commented on websites/T/tweakers/presence.ts
> +
```suggestion
  if (!presenceData.details) {
    presence.setTrayTitle();
    presence.setActivity();
  } else presence.setActivity(presenceData);
```

2021-09-20 17:51 UTC, Slowlife01 commented on websites/T/tweakers/dist/metadata.json
> +
```suggestion
```

2021-09-20 17:51 UTC, Slowlife01 commented on websites/T/tweakers/dist/metadata.json
> +      "name": "bakzkndd#2819",
```suggestion
      "name": "bakzkndd",
```

2021-09-20 17:51 UTC, Slowlife01 commented on websites/T/tweakers/presence.ts
> +
```suggestion
  } else presenceData.details = "Bezoekt de tweakers pagina...";
```

2021-09-20 18:06 UTC, Slowlife01 reviewed
Proof of it working

2021-09-20 18:12 UTC, bakzkndd commented
![image](https://user-images.githubusercontent.com/50497725/134052813-948fbfa4-4059-498d-8256-90afe8b96ebc.png)
![image](https://user-images.githubusercontent.com/50497725/134052839-d7dee8f8-90f4-4f9b-9192-b3590db624f4.png)
![image](https://user-images.githubusercontent.com/50497725/134052886-91319c19-9c7d-47a9-bd62-a3fa90942ea0.png)

a few screenshots showing it in action

2021-09-21 02:02 UTC, Slowlife01 approved these changes

2021-09-21 06:23 UTC, EncryptedDev approved these changes

2021-09-21 06:24 UTC, merged