Add Padlet
PreMiD/Presences pull request #4386
Opened 2021-09-20 21:02 UTC by TheGamerzs

2021-09-20 21:03 UTC, Bas950 requested changes

2021-09-20 21:03 UTC, Bas950 commented on websites/P/Padlet/dist/metadata.json
> +    }
icon?

2021-09-20 21:04 UTC, TheGamerzs commented on websites/P/Padlet/dist/metadata.json
> +    }
icon you?

2021-09-20 21:27 UTC, EncryptedDev requested changes

2021-09-20 21:27 UTC, EncryptedDev commented on websites/P/Padlet/dist/metadata.json
> +  "thumbnail": "https://i.imgur.com/9nXPXZh.png",
Thumbnail should be a screenshot of the homepage or a promotional banner, neither of which this meets

2021-09-20 21:27 UTC, EncryptedDev commented on websites/P/Padlet/presence.ts
> +        presenceData.state = null;
no null, use delete

2021-09-20 21:27 UTC, EncryptedDev commented on websites/P/Padlet/presence.ts
> +  } else presence.setActivity(presenceData);
```suggestion
  if (!presenceData.details) {
    presence.setTrayTitle();
    presence.setActivity();
  } else presence.setActivity(presenceData);
```
or
```suggestion
presence.setActivity(presenceData);
```

2021-09-20 21:52 UTC, TheGamerzs commented
![image](https://user-images.githubusercontent.com/44209534/134080760-d493b99c-3657-4b8a-83dd-542d7b24dc14.png)
![image](https://user-images.githubusercontent.com/44209534/134080805-edf26066-7862-4541-b98d-7d753457301b.png)

2021-09-21 02:01 UTC, Slowlife01 approved these changes

2021-09-21 06:25 UTC, EncryptedDev approved these changes

2021-09-21 11:33 UTC, merged