Wick Bot dashboard
PreMiD/Presences pull request #4393
Opened 2021-09-22 11:27 UTC by BeeXD

Many of wick configuration are done in dashboard

2021-09-22 15:33 UTC, EncryptedDev requested changes

2021-09-22 15:33 UTC, EncryptedDev commented on websites/W/Wick Dashboard/presence.ts
> +    presence.setActivity(presenceData);
```suggestion
presence.setActivity(presenceData);
```

2021-09-22 15:33 UTC, EncryptedDev commented on websites/W/Wick Dashboard/presence.ts
> +  if (document.location.hostname == "wickbot.com") {
Not needed

2021-09-22 15:33 UTC, EncryptedDev commented on websites/W/Wick Dashboard/dist/metadata.json
> +    "logo": "https://wickbot.com/wick.png",
Must be on imgur

2021-09-22 15:33 UTC, EncryptedDev commented on websites/W/Wick Dashboard/dist/metadata.json
> +      "en": "Wick Bot Dashboard"
Don't think this is the correct description 🤷‍♂️

2021-09-23 08:42 UTC, BeeXD commented on websites/W/Wick Dashboard/presence.ts
> +  if (document.location.hostname == "wickbot.com") {
what should i change it to?

2021-09-23 17:49 UTC, EncryptedDev requested changes
Fix CodeFactor issues

2021-09-23 18:05 UTC, Bas950 commented on websites/W/Wick Dashboard/presence.ts
> +  if (document.location.hostname == "wickbot.com") {
just remove

2021-09-24 00:46 UTC, BeeXD commented on websites/W/Wick Dashboard/presence.ts
> +  if (document.location.hostname == "wickbot.com") {
K

2021-09-24 09:29 UTC, closed without merging