Add Floatplane Presnce
PreMiD/Presences pull request #4397
Opened 2021-09-22 14:49 UTC by TheGamerzs

Fixes #1185
![image](https://user-images.githubusercontent.com/44209534/134366076-3ec32b2f-2329-4537-b4da-4f9120b6efe0.png)
![image](https://user-images.githubusercontent.com/44209534/134366630-f69a8656-4b27-4384-a924-ac42e3e4b2ef.png)
![image](https://user-images.githubusercontent.com/44209534/134365917-3240a059-5f14-4004-bc7f-2cbef8db4cd3.png)

2021-09-22 15:39 UTC, EncryptedDev requested changes

2021-09-22 21:01 UTC, TheGamerzs commented
![image](https://user-images.githubusercontent.com/44209534/134421298-38f9a9be-405c-42cb-8b9d-47afbfec2a9a.png)
Stream tested

2021-09-23 18:12 UTC, EncryptedDev requested changes
remove empty lines

2021-09-23 18:12 UTC, EncryptedDev commented on websites/F/Floatplane/presence.ts
> +  if (pathnames[1] === "") {
Probably a better check
```suggestion
  if (pathnames[1].length >= 0) {
```

2021-09-23 18:12 UTC, EncryptedDev commented on websites/F/Floatplane/presence.ts
> +
remove empty line

2021-09-23 18:12 UTC, EncryptedDev commented on websites/F/Floatplane/presence.ts
> +
ditto

2021-09-23 18:12 UTC, EncryptedDev commented on websites/F/Floatplane/presence.ts
> +
ditto

2021-09-23 18:12 UTC, EncryptedDev commented on websites/F/Floatplane/presence.ts
> +
Makes more sense to do it this way as you're assigning values on the line below
```suggestion
      delete presenceData.startTimestamp;
      presenceData.details = title;
```

2021-09-23 18:12 UTC, EncryptedDev commented on websites/F/Floatplane/presence.ts
> +
ditto

2021-09-23 18:12 UTC, EncryptedDev commented on websites/F/Floatplane/presence.ts
> +
ditto

2021-09-23 18:12 UTC, EncryptedDev commented on websites/F/Floatplane/presence.ts
> +
ditto

2021-09-23 18:12 UTC, EncryptedDev commented on websites/F/Floatplane/presence.ts
> +
ditto

2021-09-23 18:12 UTC, EncryptedDev commented on websites/F/Floatplane/presence.ts
> +
ditto

2021-09-23 18:12 UTC, EncryptedDev commented on websites/F/Floatplane/presence.ts
> +
ditto

2021-09-24 23:04 UTC, EncryptedDev requested changes
upload proof once more, a lot of changes have happened since

2021-09-25 15:32 UTC, TheGamerzs commented
![image](https://user-images.githubusercontent.com/44209534/134776943-b1556f00-bd53-41b6-8689-6195c6f80e34.png)
![image](https://user-images.githubusercontent.com/44209534/134776952-665de6ee-dca4-4c97-9c39-5aa5a29e02ca.png)
![image](https://user-images.githubusercontent.com/44209534/134776965-7412ee23-d07e-43a3-8da0-9bd6fe4ab8bb.png)

2021-09-25 17:28 UTC, EncryptedDev submitted a review, later dismissed

2021-09-27 19:14 UTC, Bas950 requested changes

2021-09-27 19:14 UTC, Bas950 commented on websites/F/Floatplane/dist/metadata.json
> +  "url": "www.floatplane.com",
```suggestion
  },
  "url": "www.floatplane.com",
```

2021-09-27 19:17 UTC, Bas950 approved these changes

2021-09-27 19:43 UTC, EncryptedDev approved these changes

2021-09-28 10:10 UTC, merged