EternalNetwork TM update
PreMiD/Presences pull request #4399
Opened 2021-09-22 21:59 UTC by TheDjRider

Added new futures:
- minor fixes
- new tracking for more specific pages
- button to open current url
- button to open YT video when is watched inside our forum

2021-09-22 22:15 UTC, EncryptedDev requested changes
upload proof

2021-09-23 05:59 UTC, TheDjRider commented
**Button settings and itself**

![Btn Settings](https://user-images.githubusercontent.com/12405637/134345417-31f05b53-280e-42e9-9ba6-bb37409aeb40.png)

![Btn Settings](https://user-images.githubusercontent.com/12405637/134345442-0dc8f3c3-e55a-4084-ae9b-cbacc3a0ed96.png)


**Added missing tracking for some pages:**
![New tracking](https://user-images.githubusercontent.com/12405637/134345432-e76efef2-e869-4852-b3f8-1d1546cc3f84.png)

2021-09-23 18:03 UTC, Bas950 approved these changes

2021-09-23 18:04 UTC, EncryptedDev approved these changes

2021-09-23 18:04 UTC, merged