Wick
PreMiD/Presences pull request #4403
Opened 2021-09-24 11:37 UTC by BeeXD

2021-09-24 15:06 UTC, EncryptedDev requested changes
Not much to the presence, please support more pages (if applicable) and use more DOM selectors

2021-09-24 15:06 UTC, EncryptedDev commented on websites/W/Wick/dist/metadata.json
> +    "logo": "https://wickbot.com/wick.png",
Imgur only please

2021-09-24 15:06 UTC, EncryptedDev commented on websites/W/Wick/dist/metadata.json
> +      "en": "Wick Bot Dashboard"
I doubt that is the proper description

2021-09-24 15:06 UTC, EncryptedDev commented on websites/W/Wick/presence.ts
> +
Remove line

2021-09-24 15:06 UTC, EncryptedDev commented on websites/W/Wick/presence.ts
> +  if (document.location.hostname === "wickbot.com") {
Not needed

2021-09-24 15:06 UTC, EncryptedDev commented on websites/W/Wick/presence.ts
> +  if (presenceData.details === null) {
```suggestion
  if (!presenceData.details) {
```

2021-09-25 01:10 UTC, BeeXD commented
The wick bot dash board doesnt have much pages .

2021-09-25 08:24 UTC, EncryptedDev commented
> The wick bot dash board doesnt have much pages .
Unfortunately that isn't good enough, the presence is low quality and cannot be merged.

2021-09-25 08:24 UTC, closed without merging