Recode TikTok presence
PreMiD/Presences pull request #4675
Opened 2021-09-30 22:51 UTC by TheGamerzs

![image](https://user-images.githubusercontent.com/44209534/135540061-c335fa3f-5d80-45f6-8893-62b55aa8beb0.png)
![image](https://user-images.githubusercontent.com/44209534/135540086-abd3dc83-981c-48d5-bd91-e9cc37e87e3e.png)
![image](https://user-images.githubusercontent.com/44209534/135540110-349795ee-6c63-4cfb-9fe8-968fe83137b4.png)

2021-09-30 23:55 UTC, Bas950 requested changes

2021-09-30 23:55 UTC, Bas950 commented on websites/T/TikTok/presence.ts
> +    clientId: "893257746877644830"
???

2021-09-30 23:55 UTC, Bas950 commented on websites/T/TikTok/presence.ts
> +  }),
not using the language from the settings?

2021-10-01 11:20 UTC, TheGamerzs commented on websites/T/TikTok/presence.ts
> +    clientId: "893257746877644830"
Needed more assets

2021-10-01 14:08 UTC, Bas950 commented on websites/T/TikTok/presence.ts
> +    clientId: "893257746877644830"
then just ask me to add them to it?

2021-10-01 15:09 UTC, TheGamerzs commented on websites/T/TikTok/presence.ts
> +    clientId: "893257746877644830"
Turns out the asset is already there

2021-10-02 04:09 UTC, Slowlife01 approved these changes

2021-10-02 09:51 UTC, EncryptedDev approved these changes

2021-10-02 10:45 UTC, Bas950 approved these changes

2021-10-02 10:45 UTC, merged