Refactor
PreMiD/Presences pull request #4710
Opened 2021-10-03 22:04 UTC by EncryptedDev

2021-10-03 22:10 UTC, ImRodry commented
pain

2021-10-04 08:44 UTC, TheGamerzs commented on package.json
> +    "eslint-plugin-eqeqeq-fix": "^1.0.3"
Should this be apart of dev-deps

2021-10-04 20:59 UTC, EncryptedDev commented
deleted flareradio, radio nintendo, the vibe radio, express radio, its pulse, beastfm, tuneradio, madnessfm, boltfm, highlowradio, complexr, curvefm, fiplay, tuga.tv, google play music, RealLifeGTAV, RL.Deals, Ro the Bot

2021-10-04 23:14 UTC, EncryptedDev commented
delete fiplay

2021-10-04 23:14 UTC, EncryptedDev commented
delete plug.dj

2021-10-05 12:41 UTC, ImRodry commented
Deleted discordtrlist.xyz and some presences will still fail SV. This is because their links are correct, but the metadata schema must be updated: https://github.com/PreMiD/Schemas/pull/41

2021-10-05 18:03 UTC, ImRodry submitted a review, later dismissed

2021-10-06 12:00 UTC, Bas950 commented on websites/T/ThreeNow/iframe.ts
> +  if (video !== undefined) {
```suggestion
  if (video) {
```

2021-10-14 12:03 UTC, Slowlife01 requested changes

2021-10-15 04:35 UTC, Slowlife01 approved these changes

2021-10-15 18:41 UTC, Bas950 approved these changes

2021-10-15 18:42 UTC, merged