animefillerlist presence add by ! Yelo
PreMiD/Presences pull request #4714
Opened 2021-10-04 18:17 UTC by u0f

2021-10-04 23:19 UTC, EncryptedDev requested changes

2021-10-04 23:19 UTC, EncryptedDev commented on websites/A/AnimeFillerList/presence.ts
> + */
remove
```suggestion
```

2021-10-04 23:19 UTC, EncryptedDev commented on websites/A/AnimeFillerList/presence.ts
> +  if (document.location.hostname === "www.animefillerlist.com") {
not needed if

2021-10-04 23:19 UTC, EncryptedDev commented on websites/A/AnimeFillerList/presence.ts
> +  if (presenceData.details === null) {
```suggestion
  if (!presenceData.details) {
```

2021-10-04 23:19 UTC, EncryptedDev commented on websites/A/AnimeFillerList/presence.ts
> +      presenceData.startTimestamp = browsingStamp;
define once, not every if

2021-10-04 23:19 UTC, EncryptedDev commented on websites/A/AnimeFillerList/presence.ts
> +      presenceData.startTimestamp = browsingStamp;
ditto

2021-10-04 23:19 UTC, EncryptedDev commented on websites/A/AnimeFillerList/presence.ts
> +      presenceData.startTimestamp = browsingStamp;
ditto

2021-10-04 23:19 UTC, EncryptedDev commented on websites/A/AnimeFillerList/presence.ts
> +      presenceData.startTimestamp = browsingStamp;
ditto

2021-10-04 23:19 UTC, EncryptedDev commented on websites/A/AnimeFillerList/presence.ts
> +      presenceData.startTimestamp = browsingStamp;
ditto

2021-10-04 23:19 UTC, EncryptedDev commented on websites/A/AnimeFillerList/presence.ts
> +      presenceData.startTimestamp = browsingStamp;
ditto

2021-10-04 23:19 UTC, EncryptedDev commented on websites/A/AnimeFillerList/presence.ts
> +      presenceData.startTimestamp = browsingStamp;
ditto

2021-10-04 23:19 UTC, EncryptedDev commented on websites/A/AnimeFillerList/presence.ts
> +      presenceData.startTimestamp = browsingStamp;
ditto

2021-10-04 23:19 UTC, EncryptedDev commented on websites/A/AnimeFillerList/presence.ts
> +      presenceData.startTimestamp = browsingStamp;
ditto

2021-10-04 23:19 UTC, EncryptedDev commented on websites/A/AnimeFillerList/presence.ts
> +      presenceData.startTimestamp = browsingStamp;
ditto

2021-10-04 23:19 UTC, EncryptedDev commented on websites/A/AnimeFillerList/presence.ts
> +      presenceData.startTimestamp = browsingStamp;
ditto

2021-10-04 23:19 UTC, EncryptedDev commented on websites/A/AnimeFillerList/presence.ts
> +      presenceData.startTimestamp = browsingStamp;
ditto

2021-10-05 11:30 UTC, u0f commented on websites/A/AnimeFillerList/presence.ts
> +  if (document.location.hostname === "www.animefillerlist.com") {
Fixed

2021-10-05 11:57 UTC, u0f commented
12 minor errores, but everything is okay.

2021-10-05 20:05 UTC, EncryptedDev commented
> 12 minor errores, but everything is okay.

You need to the majority of them

2021-10-05 22:21 UTC, u0f commented
What can I do now?

El mar, 5 oct 2021 a las 22:05, Rhys ***@***.***>) escribió:

> 12 minor errores, but everything is okay.
>
> You need to the majority of them
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/PreMiD/Presences/pull/4714#issuecomment-934751603>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKZXSCXFNTWOEHPRAY6ZPYTUFNK77ANCNFSM5FJ6ZT4Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-06 11:49 UTC, u0f commented
Yarn preatty executed.

2021-10-06 13:43 UTC, EncryptedDev commented
Run `eslint --fix` in your presence folder to fix issues

2021-10-06 21:26 UTC, closed without merging