Localization for Apple presence
PreMiD/Presences pull request #4727
Opened 2021-10-07 16:04 UTC by 7loud

https://github.com/PreMiD/Localization/pull/6813

2021-10-07 16:29 UTC, EncryptedDev requested changes
Version bump

2021-10-08 19:45 UTC, EncryptedDev submitted a review, later dismissed

2021-10-09 10:29 UTC, Slowlife01 approved these changes

2021-10-09 11:20 UTC, EncryptedDev approved these changes

2021-10-09 11:20 UTC, merged

2021-10-09 11:24 UTC, EncryptedDev commented
don't worry about that, misclick xD 

bas will merge the localisation repo PR when he can