Fixed Tubi
PreMiD/Presences pull request #4743
Opened 2021-10-10 16:56 UTC by puppyonline

![image](https://user-images.githubusercontent.com/56901798/136705735-a937c4fa-87ce-44b4-bd5b-c2c4c2620a66.png)
![image](https://user-images.githubusercontent.com/56901798/136705739-5d2aafc7-92d6-4c32-83aa-ead2ce4aecab.png)
![image](https://user-images.githubusercontent.com/56901798/136705745-016aadc6-1173-46d1-b5ca-e4e8b79b7690.png)

2021-10-10 18:04 UTC, EncryptedDev commented
fix your branch, old commits :/

2021-10-10 18:08 UTC, EncryptedDev requested changes

2021-10-10 18:30 UTC, EncryptedDev commented
> > fix your branch, old commits :/
> 
> how would I fix that, not contributed in a while so not sure how stuff works for the most part now

by using git rebase

2021-10-10 21:32 UTC, EncryptedDev requested changes

2021-10-11 19:49 UTC, EncryptedDev requested changes

2021-10-16 04:32 UTC, Slowlife01 commented
Resolve conflicts

2021-10-17 22:35 UTC, closed without merging