Nanahen Presence
PreMiD/Presences pull request #4755
Opened 2021-10-14 15:07 UTC by mhazm

# Presence for [Nanahen](https://nanahen.com)
Nanahen is a manga and doujinshi scanlation website that has been translated into Indonesian language.

## Example of working:
![on searching](https://i.imgur.com/4lamf91.png)
![Viewing on author list](https://i.imgur.com/qpHl9Cv.png)
![Viewing archive author](https://i.imgur.com/7cA43re.png)
![Parody archive](https://i.imgur.com/iUJbxip.png)
![View manga page](https://i.imgur.com/TFkEbBZ.png)
![On reading](https://i.imgur.com/ajkp2qK.png)

2021-10-14 15:28 UTC, Slowlife01 requested changes
and why unnecessary template strings

2021-10-14 17:38 UTC, Bas950 requested changes

2021-10-14 22:16 UTC, EncryptedDev requested changes
In regards to assigning data to presenceData.state to the latter half, you could also assign it by using the querySelector

2021-10-16 07:14 UTC, Slowlife01 commented
update your folk

2021-10-23 07:43 UTC, Slowlife01 submitted a review, later dismissed

2021-10-23 09:47 UTC, EncryptedDev submitted a review, later dismissed

2021-10-24 01:11 UTC, Bas950 approved these changes

2021-10-24 11:05 UTC, EncryptedDev approved these changes

2021-10-24 11:21 UTC, merged