Rebrand
PreMiD/Presences pull request #4769
Opened 2021-10-17 23:00 UTC by callumok2004

2021-10-17 23:03 UTC, EncryptedDev requested changes
Why have to created a new metadata, but renamed the other files?

2021-10-17 23:04 UTC, callumok2004 commented
> Why have to created a new metadata, but renamed the other files?

I didn't, github did that itself its weird idk

2021-10-17 23:11 UTC, callumok2004 commented
![image](https://user-images.githubusercontent.com/35779365/137648377-34cc4adc-0aee-464e-af51-bb161847caef.png)
Final fix working, let me just push local changes

2021-10-18 21:44 UTC, ImRodry requested changes

2021-10-18 22:06 UTC, ImRodry approved these changes

2021-10-18 22:08 UTC, EncryptedDev approved these changes

2021-10-18 22:08 UTC, Bas950 approved these changes

2021-10-18 22:09 UTC, merged