feat: add dsc.gg presence.
PreMiD/Presences pull request #4781
Opened 2021-10-20 01:41 UTC by DiscordAnaxes

Proof of presence working:
![Discord_bbPzNyWIYD](https://user-images.githubusercontent.com/68460474/138013811-d0625955-17b8-4931-9306-64a445b2092b.png)
![Discord_uJ1EfrHniG](https://user-images.githubusercontent.com/68460474/138013816-00997e93-a830-4da8-832d-9d7fed874026.png)
![Discord_Zlojp5PLUF](https://user-images.githubusercontent.com/68460474/138013818-95782b16-55c7-48fc-8d05-6206d2650090.png)
![Discord_1WPayBoRIE](https://user-images.githubusercontent.com/68460474/138013822-54d2d0cc-3563-41fe-bb91-23ae6fdb59b6.png)
![Discord_nCgsFepVll](https://user-images.githubusercontent.com/68460474/138015824-c1ee570b-1f35-429f-92e6-c3e2bae12f59.png)
![Discord_pTkJQGotXz](https://user-images.githubusercontent.com/68460474/138015826-36fbe30f-8ab1-4ba7-b690-6ed151686229.png)

2021-10-20 10:33 UTC, EncryptedDev requested changes
Prettify your code (`prettier --write .`)

2021-10-22 03:05 UTC, Slowlife01 requested changes

2021-10-22 22:57 UTC, EncryptedDev approved these changes
lgtm

2021-10-23 04:55 UTC, Slowlife01 approved these changes

2021-10-23 04:56 UTC, merged