Updated Dumpert
PreMiD/Presences pull request #4783
Opened 2021-10-20 11:59 UTC by DarkVillager

- Fixed bug were only homepage worked;
- Added Buttons;
- Added two new settings:
                                          1. Show Buttons;
                                          2. Privacy Mode;

Proof with privacy mode enabled:
![dumpert3-mp](https://user-images.githubusercontent.com/42322979/138088359-66bf7710-6651-49dd-8a56-07c7f44fd911.jpg)
![dumpert1-mp](https://user-images.githubusercontent.com/42322979/138088363-57feb458-3db8-4c89-9a57-b491d3955dc1.jpg)
![dumpert2-mp](https://user-images.githubusercontent.com/42322979/138088364-86be7391-b6b6-42c1-9234-8d6405c97023.jpg)

Proof with privacy mode disabled:
![dumpert3-zp](https://user-images.githubusercontent.com/42322979/138088407-72eae34b-dfda-4e6c-a737-bdc0194fea0e.jpg)
![dumpert2-zp](https://user-images.githubusercontent.com/42322979/138088400-26e1f6a3-3d24-4b8f-b917-ff9e82982f71.jpg)
![dumpert1-zp](https://user-images.githubusercontent.com/42322979/138088410-c5d9b9ce-d796-49a2-90bc-2420284a9ec8.jpg)
:

2021-10-21 14:29 UTC, EncryptedDev reviewed
From what I can see, you’ve prettified the metadata file, but why have you reorganised it, just seems like you’ve made useless changes imo

2021-10-24 01:09 UTC, Bas950 requested changes

2021-10-26 07:02 UTC, Slowlife01 approved these changes

2021-10-26 10:40 UTC, Bas950 approved these changes

2021-10-26 10:40 UTC, merged