Added Khan Academy presence.
PreMiD/Presences pull request #4797
Opened 2021-10-22 12:47 UTC by AlvinIsCrack

Working presence:
![imagen](https://user-images.githubusercontent.com/87828455/138454584-0054d5d0-2370-463d-8e9b-a4b6dc07478b.png)
![imagen](https://user-images.githubusercontent.com/87828455/138454645-ed7970cc-b788-476f-9d5e-65da9de2c30d.png)
![imagen](https://user-images.githubusercontent.com/87828455/138454674-fce7bb0a-fb99-494b-ad12-786cd7d42bcf.png)
![imagen](https://user-images.githubusercontent.com/87828455/138454801-3e8c217f-2505-4961-907c-6187136c55c9.png)
![imagen](https://user-images.githubusercontent.com/87828455/138454850-cfd337e0-7537-4535-a2ad-65ad5addc143.png)
![imagen](https://user-images.githubusercontent.com/87828455/138454910-5e62bc99-3be5-4701-a685-1c1b57303957.png)
![imagen](https://user-images.githubusercontent.com/87828455/138455604-cf1cb932-4a32-44bc-bfe6-9746de89e381.png)
![imagen](https://user-images.githubusercontent.com/87828455/138455668-4871cbad-16f2-4a0d-a8ae-8c1085ed4b49.png)
![imagen](https://user-images.githubusercontent.com/87828455/138493327-9808b6b7-e41d-4853-bf92-f6209604339a.png)
![imagen](https://user-images.githubusercontent.com/87828455/138493433-c32bc6a4-bef4-4aa1-86da-5260095f13be.png)

2021-10-22 22:54 UTC, EncryptedDev requested changes

2021-10-23 00:09 UTC, AlvinIsCrack commented
Metadata.json fixed! Hope it looks good now...

2021-10-23 08:28 UTC, Slowlife01 approved these changes

2021-10-23 09:46 UTC, EncryptedDev approved these changes

2021-10-23 09:46 UTC, merged