Adding tioanime.com Presence
PreMiD/Presences pull request #4829
Opened 2021-10-27 16:10 UTC by u0f

![imagen](https://user-images.githubusercontent.com/45316362/139102895-ab4dc5f2-c914-46b4-87af-48211a6d8277.png)
![imagen](https://user-images.githubusercontent.com/45316362/139102933-0963da01-d7a7-4406-bf57-704a9d704ef4.png)

Paused chapter
![imagen](https://user-images.githubusercontent.com/45316362/139103052-41675659-e762-4d60-886c-7847a330a6ea.png)
Playing chapter
![imagen](https://user-images.githubusercontent.com/45316362/139103101-45ebbc44-2435-4054-8534-61f3f61872ed.png)

2021-10-27 16:51 UTC, EncryptedDev requested changes

2021-10-29 19:27 UTC, u0f commented
> 
> 
> Add more features to the presence (e.g. settings, multiLang, buttons, etc)

Add for adding? You don't really need to put any of that in.
Mutlilang for what? The website is only in spanish.
Settings for what? I don't need it, is a really normal presence 
Buttons? Idk i'll add some

2021-10-30 03:48 UTC, Slowlife01 requested changes

2021-10-30 03:48 UTC, Slowlife01 commented on websites/T/Tio Anime/presence.ts
> +}
Again

2021-10-30 03:48 UTC, Slowlife01 commented on websites/T/Tio Anime/dist/metadata.json
> +    "en": "Watch any anime in spanish!",
*And you changed it back.*

2021-10-30 03:53 UTC, Slowlife01 commented
Also update your fork

2021-10-30 08:30 UTC, u0f commented
idk why schema validation check is failing

2021-10-30 08:31 UTC, Slowlife01 commented on websites/T/Tio Anime/presence.ts
> +}
No. Use `Presence.getTimestanps()`

2021-10-30 08:33 UTC, u0f commented on websites/T/Tio Anime/presence.ts
> +}
OOH, okay tysm ^^

2021-10-30 08:35 UTC, Slowlife01 commented on websites/T/Tio Anime/presence.ts
> +}*/
Remove it

2021-10-30 08:36 UTC, u0f commented on websites/T/Tio Anime/presence.ts
> +}*/
My bad

2021-10-30 11:47 UTC, Slowlife01 approved these changes

2021-10-30 12:42 UTC, EncryptedDev approved these changes

2021-10-30 12:42 UTC, merged