SV Fix
PreMiD/Presences pull request #4844
Opened 2021-10-29 22:15 UTC by TheGamerzs

2021-10-29 22:29 UTC, ImRodry requested changes

2021-10-29 22:29 UTC, ImRodry commented on util/tools/auto/schemaValidator.ts
> +      ).data.langFiles.map((l: { lang: string }) => l.lang),
If you added the type above this is not needed

2021-10-29 22:29 UTC, ImRodry commented on util/tools/auto/schemaValidator.ts
> +interface langFiles {
Interface names usually follow the PascalCase naming convention in TypeScript

2021-10-30 00:16 UTC, Bas950 approved these changes

2021-10-30 01:29 UTC, EncryptedDev approved these changes

2021-10-30 01:36 UTC, merged