Add emoji.gg presence
PreMiD/Presences pull request #4874
Opened 2021-11-05 22:03 UTC by dtmcl

Adds an emoji.gg presence

![image](https://user-images.githubusercontent.com/68128382/140583257-9a2da773-12cb-4ca3-aa73-184683fb900b.png)
![image](https://user-images.githubusercontent.com/68128382/140583266-ac6e8996-9311-4a49-951e-6be01f599075.png)
![image](https://user-images.githubusercontent.com/68128382/140583284-dbd6c727-9c8f-4364-8c3f-94003fc5176f.png)
![image](https://user-images.githubusercontent.com/68128382/140583440-13b1d80a-05df-4ec6-a2fb-79562ba22fce.png)
![image](https://user-images.githubusercontent.com/68128382/140583467-1b49ae64-2726-4e77-9ca0-e88e308000da.png)

2021-11-05 22:08 UTC, EncryptedDev requested changes
fix indentation too

2021-11-05 22:08 UTC, EncryptedDev commented on websites/E/Emoji.gg/dist/metadata.json
> +  "$schema": "https://schemas.premid.app/metadata/1.3",
Outdated schema
```suggestion
  "$schema": "https://schemas.premid.app/metadata/1.5",
```

2021-11-05 22:08 UTC, EncryptedDev commented on websites/E/Emoji.gg/dist/metadata.json
> +  "logo": "https://i.imgur.com/dDhx5sD.png",
Not 512x

2021-11-05 22:08 UTC, EncryptedDev commented on websites/E/Emoji.gg/dist/metadata.json
> +  "tags": [
add a `nsfw` tag for the nsfw category

2021-11-05 22:08 UTC, EncryptedDev commented on websites/E/Emoji.gg/presence.ts
> +  if (document.location.hostname === "emoji.gg") {
Remove this if statement

2021-11-05 22:08 UTC, EncryptedDev commented on websites/E/Emoji.gg/presence.ts
> +      presenceData.startTimestamp = browsingStamp;
set startTimestamp in the PresenceData object

2021-11-06 10:43 UTC, EncryptedDev commented on websites/E/Emoji.gg/presence.ts
> +  search: HTMLElement;
Why do you have these variables when they're never used?

2021-11-06 23:19 UTC, EncryptedDev commented on websites/E/Emoji.gg/presence.ts
> +    presenceData.state = "by " + user.innerText;
Use proper string contactination

2021-11-13 08:01 UTC, Slowlife01 commented
Inactive

2021-11-13 08:01 UTC, closed without merging