lint:*
PreMiD/Presences pull request #4884
Opened 2021-11-09 17:02 UTC by EncryptedDev

2021-11-09 19:15 UTC, Bas950 submitted a review, later dismissed

2021-11-10 02:27 UTC, Slowlife01 commented
Needs rebase

2021-11-10 15:51 UTC, Slowlife01 submitted a review, later dismissed

2021-11-10 18:30 UTC, Bas950 requested changes
Facebook needs version bump

2021-11-10 18:56 UTC, Slowlife01 approved these changes

2021-11-10 20:30 UTC, Bas950 approved these changes

2021-11-10 20:30 UTC, merged