Change Apple TV to Apple TV+
PreMiD/Presences pull request #4894
Opened 2021-11-11 19:13 UTC by N0chteil

Apple TV is the media player and Apple TV+ is the streaming service.

> https://www.coolblue.nl/en/advice/difference-between-apple-tv-apple-tv+-and-the-apple-tv-app.html
> or
> ![image](https://user-images.githubusercontent.com/53608074/141354302-c5c85df8-55fd-45b4-8fb8-6e1ce0b40de5.png)

@Slowlife01 could you please also change the name of the Discord app?

2021-11-11 19:19 UTC, EncryptedDev requested changes

2021-11-11 19:19 UTC, EncryptedDev commented on websites/A/Apple TV+/dist/metadata.json
> +  "version": "1.0.4",
Bump minor or major; not patch

2021-11-11 19:26 UTC, EncryptedDev commented on websites/A/Apple TV+/dist/metadata.json
> +  "version": "1.1.0",
```suggestion
  "version": "1.0.0",
```

2021-11-11 19:30 UTC, EncryptedDev approved these changes

2021-11-12 02:35 UTC, Slowlife01 approved these changes

2021-11-12 02:35 UTC, merged