Add Personality Database Presence
PreMiD/Presences pull request #4902
Opened 2021-11-14 17:38 UTC by justarya

website: https://www.personality-database.com/
Personality Database is the most popular site for discovering someone's personality type.

Website preview:
![Screen Shot 2021-11-14 at 17 58 31](https://user-images.githubusercontent.com/26767753/141691905-21795e34-954e-4340-a74e-4fc4ae8ea03d.png)

![photo_2021-11-15 00 34 12](https://user-images.githubusercontent.com/26767753/141691806-fe5961a4-cc96-4762-b477-91d65e8d2b75.jpeg)

2021-11-14 19:17 UTC, EncryptedDev commented
Why have you used setTrayTitle as the function is now deprecated? If you are wanting to still use it, please provide proof it works.

Also I suspect that you ran the linter on the entire presence folder, hence why you have the change for the other website, but if you are wanting to PR the change on 000webhost bump the version of it.

2021-11-15 01:11 UTC, justarya commented
Here's proof of it. So far, works on my mac.

![Screen Shot 2021-11-15 at 08 01 28](https://user-images.githubusercontent.com/26767753/141706775-5e01e66d-fecf-457b-b58a-de08a6c7fa93.png)

I have been scrolling through documentation and didn't find any other supported tray function.
Is there any function that can replace it?

2021-11-15 21:43 UTC, EncryptedDev commented
> I have been scrolling through documentation and didn't find any other supported tray function.
Is there any function that can replace it?

No, the function was only intended for the purpose it was never used for, hence why it was deprecated

2021-11-19 04:47 UTC, Slowlife01 requested changes
Add few more things

2021-11-19 14:59 UTC, justarya commented
## What's new
- Added new page support & Added new icon support

### Profile
![Screen Shot 2021-11-19 at 21 53 40](https://user-images.githubusercontent.com/26767753/142642838-c77cab90-ece4-42aa-9798-7a1f52ebeb28.png)
![Screen Shot 2021-11-19 at 21 48 23](https://user-images.githubusercontent.com/26767753/142641945-02c3ffb0-c83a-42f9-a1b8-f132d6a9f10f.png)

### Searching
![Screen Shot 2021-11-19 at 21 54 29](https://user-images.githubusercontent.com/26767753/142642952-67238a30-e6d9-49b0-a431-80c8d5c8b738.png)
![Screen Shot 2021-11-19 at 21 50 08](https://user-images.githubusercontent.com/26767753/142642244-0ff2b955-7b98-4516-94e1-25536216405d.png)

### Category
![Screen Shot 2021-11-19 at 21 55 44](https://user-images.githubusercontent.com/26767753/142643157-da964f7c-75ec-4e7d-8afc-dcd37d6c66aa.png)
![Screen Shot 2021-11-19 at 21 50 42](https://user-images.githubusercontent.com/26767753/142642342-f933df8b-44f5-45f9-9197-797622ccd3ac.png)

### Community Feed

![Screen Shot 2021-11-19 at 21 56 26](https://user-images.githubusercontent.com/26767753/142643253-e7c232d2-7095-409c-bc64-0a412b238ee4.png)
![Screen Shot 2021-11-19 at 21 50 59](https://user-images.githubusercontent.com/26767753/142642391-c9c07165-575c-4485-a5bb-3b0c0d988d5a.png)

### Notification
![Screen Shot 2021-11-19 at 21 56 55](https://user-images.githubusercontent.com/26767753/142643331-a34798fd-6d86-40b0-827d-a110af9575db.png)
![Screen Shot 2021-11-19 at 21 51 16](https://user-images.githubusercontent.com/26767753/142642425-9474b0e9-7c68-4b99-8e74-5146db3cfad0.png)

### User's profile
![Screen Shot 2021-11-19 at 21 58 03](https://user-images.githubusercontent.com/26767753/142643507-a7b001d0-b60f-4702-a44a-91f22a0e7d82.png)

![Screen Shot 2021-11-19 at 21 52 22](https://user-images.githubusercontent.com/26767753/142642613-8d31951c-a159-4172-8e16-072a197f6338.png)
![Screen Shot 2021-11-19 at 21 51 37](https://user-images.githubusercontent.com/26767753/142642501-939936e9-8930-4608-8a0a-e128eb6e3a64.png)

2021-11-19 20:41 UTC, EncryptedDev requested changes
Could you also explain your rationale behind the exessive amounts of comments?

2021-11-19 20:41 UTC, EncryptedDev commented on websites/P/Personality Database/presence.ts
> +  }
```suggestion
  else presence.setActivity(presenceData);
```

2021-11-19 20:41 UTC, EncryptedDev commented on websites/P/Personality Database/presence.ts
> +  presenceData.startTimestamp = browsingStamp;
Set this in the PresenceData object

2021-11-19 20:41 UTC, EncryptedDev commented on websites/P/Personality Database/presence.ts
> +    const title: string = document.title?.split(" | ")[0];
Don't use a variable once #4893

2021-11-20 01:41 UTC, justarya commented
The comments are for context mostly, if others want to continue to develop this presence.

2021-11-20 12:47 UTC, Slowlife01 approved these changes

2021-11-20 13:47 UTC, EncryptedDev approved these changes

2021-11-20 13:47 UTC, merged