Dribbble Presence
PreMiD/Presences pull request #4926
Opened 2021-11-16 20:36 UTC by Vimeux

Hi there,

I have created a presence for the [Dribbble](https://dribbble.com/) site.
This is my first commit here, I tested it on Chrome, Safari and Firefox, and it works perfectly.
If there are things to review, let me know, I'll take care of it.

See you soon.

2021-11-16 21:13 UTC, EncryptedDev commented
Please format your code by running `yarn lint` (you will need both `eslint` and `prettier` installed globally for this to work)

2021-11-16 21:49 UTC, EncryptedDev requested changes

2021-11-16 21:49 UTC, EncryptedDev commented on websites/D/Dribbble/dist/metadata.json
> +  "$schema": "https://schemas.premid.app/metadata/1.3",
Outdated schema version
```suggestion
  "$schema": "https://schemas.premid.app/metadata/1.5",
```

2021-11-16 21:58 UTC, Vimeux commented on websites/D/Dribbble/presence.ts
> +    presenceData.state = `- ${profileName} -`;
These lines allow me to get the name of the user in the URL to display it in the presence.

2021-11-17 21:48 UTC, EncryptedDev commented on websites/D/Dribbble/presence.ts
> +    presenceData.state = `- ${profileName} -`;
I understand that, but you are just adding it to a string so the outcome would be `- Encrypted -`

2021-11-17 21:48 UTC, EncryptedDev commented
Upload proof of the presence working

2021-11-18 17:23 UTC, Vimeux commented
<img width="1920" alt="Capture d’écran 2021-11-18 à 18 15 27" src="https://user-images.githubusercontent.com/55838254/142465055-c923b6bb-0d37-4f19-92b8-10e041d0209b.png">

<img width="1920" alt="Capture d’écran 2021-11-18 à 18 16 40" src="https://user-images.githubusercontent.com/55838254/142465120-f8dde575-f55c-4002-a547-c1c9dd05eebf.png">

<img width="1920" alt="Capture d’écran 2021-11-18 à 18 17 40" src="https://user-images.githubusercontent.com/55838254/142465154-58f5e91d-92bf-430a-9f32-18193bafbe07.png">

<img width="1920" alt="Capture d’écran 2021-11-18 à 18 18 04" src="https://user-images.githubusercontent.com/55838254/142465170-a7fbbee4-30af-4413-a74c-9c2d64907a2d.png">

2021-11-18 17:26 UTC, EncryptedDev approved these changes

2021-11-19 04:43 UTC, Slowlife01 approved these changes

2021-11-19 04:43 UTC, merged