New Presence | Harmony
PreMiD/Presences pull request #4931
Opened 2021-11-17 22:40 UTC by marinofranz

https://images-ext-2.discordapp.net/external/s9Gsdr74bXcFNX1_jHCqqfL7OKOJ9KAp_lMN6maagbA/https/i.imgur.com/WupF6CZ.png

Proof of listeners; https://weareharmony.net/#/Info

2021-11-17 22:44 UTC, EncryptedDev requested changes
Remove your one-time-vars, otherwise they will be removed in #4893

2021-11-18 17:32 UTC, marinofranz commented
I'm honestly not sure by what you mean? The code looks readable, what do you want me to change exactly?

2021-11-23 21:27 UTC, EncryptedDev approved these changes
lgtm

2021-11-24 22:29 UTC, Bas950 approved these changes

2021-11-24 22:29 UTC, merged