Update Oculus presence
PreMiD/Presences pull request #4949
Opened 2021-11-23 21:49 UTC by N0chteil

<details>
<summary>Proof:</summary>
<br>
<img src="https://user-images.githubusercontent.com/53608074/143129475-e6a7a9ec-f047-454b-b380-1deb5bcf5798.png">
<img src="https://user-images.githubusercontent.com/53608074/143129492-3a946f20-2119-4c76-93c4-d89b7456d143.png">
<img src="https://user-images.githubusercontent.com/53608074/143129508-48c172c3-e25d-406c-9792-7132235496a9.png">
<img src="https://user-images.githubusercontent.com/53608074/143129499-6802ffd5-6f91-4eb5-9edf-796ec6beab15.png">
</details>

2021-11-23 21:52 UTC, EncryptedDev requested changes
Bump version

2021-11-23 21:54 UTC, N0chteil commented
> Bump version

I always forget that 😑

**1.1.0** or **2.0.0**?

2021-11-23 21:55 UTC, EncryptedDev commented
> > Bump version
> 
> I always forget that 😑
> 
> **1.1.0** or **2.0.0**?

minor

2021-11-24 22:30 UTC, Bas950 approved these changes

2021-11-24 22:55 UTC, EncryptedDev approved these changes

2021-11-24 22:55 UTC, merged