Created TrueID presence
PreMiD/Presences pull request #4951
Opened 2021-11-24 01:08 UTC by Faelayis

Created AnimesOnline presence

<details>
<summary>
Preview
</summary>
<br>

![image](https://user-images.githubusercontent.com/48393914/143152694-b00bda44-f180-470a-b67c-6b37fefbe555.png)
![image](https://user-images.githubusercontent.com/48393914/143152758-6aa4720d-a2bd-493d-88ed-b9e3c2366e16.png)
![image](https://user-images.githubusercontent.com/48393914/143152727-75c01c08-778b-455a-b519-15deb8b1a477.png)
![image](https://user-images.githubusercontent.com/48393914/143152876-5526205e-b73a-4704-b815-417e7ce422f5.png)
![image](https://user-images.githubusercontent.com/48393914/143152991-93499dec-6b8c-4f3e-a76e-a21e8fbce232.png)

</details>

2021-11-27 11:00 UTC, Slowlife01 requested changes

2021-11-27 11:00 UTC, Slowlife01 commented on websites/T/TrueID/presence.ts
> +  } else presence.setActivity(presenceData);
```suggestion
  if (!presenceData.details) presence.setActivity();
  else presence.setActivity(presenceData);
```

2021-11-27 11:00 UTC, Slowlife01 commented on websites/T/TrueID/dist/metadata.json
> +  "iframe": false,
```suggestion
```

2021-11-27 12:25 UTC, Slowlife01 submitted a review, later dismissed

2021-11-27 12:35 UTC, EncryptedDev requested changes

2021-11-27 12:35 UTC, EncryptedDev commented on websites/T/TrueID/presence.ts
> +  else presence.setActivity(presenceData);
#4946 will enforce all presences to use this format
```suggestion
  if (presenceData.details) presence.setActivity(presenceData);
  else presence.setActivity();
```

2021-11-27 12:35 UTC, EncryptedDev commented on websites/T/TrueID/presence.ts
> +  browsingStamp = Math.floor(Date.now() / 1000);
```suggestion
  browsingTimestamp = Math.floor(Date.now() / 1000);
```

2021-11-27 12:35 UTC, EncryptedDev commented on websites/T/TrueID/presence.ts
> +      startTimestamp: browsingStamp
```suggestion
      startTimestamp: browsingTimestamp
```

2021-11-27 13:28 UTC, EncryptedDev approved these changes

2021-11-28 03:31 UTC, Slowlife01 approved these changes

2021-11-28 03:33 UTC, merged