Added Novelfull Presence
PreMiD/Presences pull request #4964
Opened 2021-11-27 15:56 UTC by DarkVillager

Resolves #4962
Added Novelfull Presence.
![n5](https://user-images.githubusercontent.com/42322979/143688198-2eb62c92-b2aa-4073-82c8-4bbbbb392557.jpg)
![n1](https://user-images.githubusercontent.com/42322979/143688200-3eec2587-d8ee-4dd3-abed-47320aa4f91d.jpg)
![n2](https://user-images.githubusercontent.com/42322979/143688201-c19686de-06f9-4e49-8732-628052c711e8.jpg)
![n3](https://user-images.githubusercontent.com/42322979/143688202-5bad40cf-cd69-4d85-ba49-e6617a9c2380.jpg)
![n4](https://user-images.githubusercontent.com/42322979/143688203-59424eae-a570-4d88-988f-32689826e3cd.jpg)

2021-11-28 03:41 UTC, Slowlife01 submitted a review, later dismissed

2021-11-28 03:41 UTC, Slowlife01 commented on websites/N/Novelfull/presence.ts
> +  presenceData.startTimestamp = browsingStamp;
move startTimestamp to the init object

2021-11-28 03:41 UTC, Slowlife01 commented on websites/N/Novelfull/presence.ts
> +  search = document.querySelector("#search-input");
why does this variable have to be outside scope if you always reassign it

2021-11-28 03:41 UTC, Slowlife01 commented on websites/N/Novelfull/presence.ts
> +    presenceData.startTimestamp;
```suggestion
```

2021-11-28 03:41 UTC, Slowlife01 commented on websites/N/Novelfull/presence.ts
> +    presenceData.startTimestamp;
```suggestion
```

2021-11-28 14:00 UTC, EncryptedDev commented on websites/N/Novelfull/presence.ts
> +  browsingStamp = Math.floor(Date.now() / 1000);
```suggestion
  browsingTimestamp = Math.floor(Date.now() / 1000);
```

2021-11-28 14:01 UTC, EncryptedDev requested changes

2021-11-28 14:01 UTC, EncryptedDev commented on websites/N/Novelfull/presence.ts
> +  else presence.setActivity(presenceData);
```suggestion
  if (presenceData.details) presence.setActivity(presenceData);
  else presence.setActivity();
```

2021-11-28 14:55 UTC, EncryptedDev requested changes

2021-11-28 14:55 UTC, EncryptedDev commented on websites/N/Novelfull/presence.ts
> +      startTimestamp: browsingStamp
```suggestion
      startTimestamp: browsingTimestamp
```

2021-11-30 20:17 UTC, Bas950 commented on websites/N/Novelfull/dist/metadata.json
> +    "nl": "Lees Online Gratis Boeken"
```suggestion
    "nl": "Lees Boeken Gratis Online"
```

2021-12-02 21:58 UTC, EncryptedDev submitted a review, later dismissed

2021-12-02 22:00 UTC, EncryptedDev approved these changes

2021-12-03 02:52 UTC, Bas950 approved these changes

2021-12-03 04:57 UTC, merged