Fixed TuneIn (Long time fix)
PreMiD/Presences pull request #4973
Opened 2021-11-30 13:15 UTC by DarkVillager

Fixed TuneIn.
![t4](https://user-images.githubusercontent.com/42322979/144054027-9743d6dd-3628-4872-a0c0-d2e595e33723.jpg)
![t3](https://user-images.githubusercontent.com/42322979/144054036-d548c9ba-e49f-46e5-b62e-fc138ab46715.jpg)
![t1](https://user-images.githubusercontent.com/42322979/144054030-3cdf65c1-80bc-4a67-9f22-ef5abe540b3f.jpg)
![t2](https://user-images.githubusercontent.com/42322979/144054034-54e1e8ca-62d0-4da4-8eaa-df168b339a16.jpg)

2021-11-30 13:24 UTC, ImRodry requested changes

2021-11-30 13:24 UTC, ImRodry commented on websites/T/TuneIn/presence.ts
> +        : false;
Please don’t do this

2021-11-30 13:24 UTC, ImRodry commented on websites/T/TuneIn/presence.ts
>        : false;
Please don’t

2021-11-30 13:24 UTC, ImRodry commented on websites/T/TuneIn/presence.ts
> +          : false;
Please don’t

2021-11-30 13:24 UTC, ImRodry commented on websites/T/TuneIn/presence.ts
> +        timestamps = presence.getTimestamps(timestamp1, timestamp2),
Please don’t declare variables that are only used once

2021-12-01 13:36 UTC, DarkVillager commented on websites/T/TuneIn/presence.ts
> +        : false;
Okay? What to do then instead of this?

2021-12-01 14:17 UTC, ImRodry commented on websites/T/TuneIn/presence.ts
> +        : false;
Remove the ternary operator simply

2021-12-04 08:16 UTC, DarkVillager commented
Currently dont have access to a pc will fix asap

2021-12-07 03:57 UTC, EncryptedDev commented
Inactive - reopen later

2021-12-07 03:57 UTC, closed without merging