Publish Presences - NiceHash & BetterHash
PreMiD/Presences pull request #4993
Opened 2021-12-05 05:27 UTC by rhys19

Hello, I have made some simple presences this is my first time, I have created Nicehash & Betterhash presences.

none of these extensions release PRIVATE information they only say what the page name is your viewing and a small description of it ex: Viewing exchange prices.

I hope this gets published as I think there's a few people out there that would use these :)

Please let me know if there is anything to change on it and I gladly will!

2021-12-05 15:23 UTC, ImRodry commented
Idk how you did that but don’t upload the presence.js file

2021-12-05 15:27 UTC, EncryptedDev commented
You also have a few too many `metadata.json`s

2021-12-06 21:41 UTC, rhys19 commented
oh I didn't know, there was no instructions I could find on submitting pr so just the presence.ts then? as for the manifest do I'm not sure where to put it. do I put in /dist or the main folder

2021-12-06 21:43 UTC, ImRodry commented
There are [docs](https://docs.premid.app/en/dev/presence) on how to create a presence and git itself shouldn't ever allow you to publish the .js file, which is why I'm surprised as to how you did that, but please delete multiple files in one commit

2021-12-06 21:44 UTC, rhys19 commented
Ok. sorry, I deleted them via github not via local files so that's why it deleted it in multiples. so I deleted the manifest.json in the main and kept it in dist and deleted the .js is there anything else?

2021-12-06 21:47 UTC, EncryptedDev requested changes

2021-12-06 21:47 UTC, EncryptedDev commented on websites/B/BetterHash/presence.ts
> +  time = Math.floor(Date.now() / 1000);
```suggestion
  browsingTimestamp = Math.floor(Date.now() / 1000);
```

2021-12-06 21:47 UTC, EncryptedDev commented on websites/B/BetterHash/presence.ts
> +    startTimestamp: time
```suggestion
    startTimestamp: browsingTimestamp
```

2021-12-06 21:47 UTC, EncryptedDev commented on websites/N/NiceHash/dist/metadata.json
> +  "version": "1.0.3",
```suggestion
  "version": "1.0.0",
```

2021-12-06 21:47 UTC, EncryptedDev commented on websites/N/NiceHash/presence.ts
> +  time = Math.floor(Date.now() / 1000);
```suggestion
  browsingTImestamp = Math.floor(Date.now() / 1000);
```

2021-12-06 21:47 UTC, EncryptedDev commented on websites/N/NiceHash/presence.ts
> +    startTimestamp: time
```suggestion
    startTimestamp: browsingTImestamp
```

2021-12-06 22:29 UTC, ImRodry requested changes
Please batch these suggestions into one commit and use vscode, not github

2021-12-06 22:29 UTC, ImRodry commented on websites/B/BetterHash/presence.ts
> +  presence.on("UpdateData", async () => {
fix indentation (run prettier + eslint)

2021-12-06 22:29 UTC, ImRodry commented on websites/N/NiceHash/presence.ts
> +  presence.on("UpdateData", async () => {
ditto

2021-12-06 22:29 UTC, ImRodry commented on websites/N/NiceHash/presence.ts
> +    startTimestamp: browsingTImestamp
that's not how you camelcase
```suggestion
    startTimestamp: browsingTimestamp
```

2021-12-06 22:29 UTC, ImRodry commented on websites/N/NiceHash/presence.ts
> +  browsingTImestamp = Math.floor(Date.now() / 1000);
```suggestion
  browsingTimestamp = Math.floor(Date.now() / 1000);
```

2021-12-07 00:49 UTC, rhys19 commented
> Please batch these suggestions into one commit and use vscode, not github

ok, sorry my internet was out for like 2 hours doing it via vscode now and then uploading with the git client.

2021-12-07 02:02 UTC, rhys19 commented
I tried using eslint & prettier but in vscode it doesn't do any changes. it had me remove variable that wasn't used but that was it, I'm fairly new to typescript I've only coded javascript and other languages but this is my first for typescript

2021-12-07 02:19 UTC, rhys19 commented
ESlint & Prettier did do some indentation and spaces I uploaded them via git (Used VSCode).

2021-12-09 19:49 UTC, Bas950 requested changes

2021-12-09 19:49 UTC, Bas950 commented on package.json
> +    "@typescript-eslint/parser": "^5.0.0",
undo

2021-12-10 23:41 UTC, rhys19 commented on package.json
> +    "@typescript-eslint/parser": "^5.0.0",
fixed

2021-12-12 00:12 UTC, EncryptedDev commented
Fix this PR and reopen

2021-12-12 00:12 UTC, closed without merging

2021-12-12 21:09 UTC, rhys19 commented
> Fix this PR and reopen

my question is how come the coinbase extension was merged, when mine isn't that different???

it's my first time doing typescript I don't understand what's wrong with it...
been trying to understand what was wrong but if someone could just point me in the right direction it'd be nice.

2021-12-15 21:34 UTC, EncryptedDev commented
Only commit the files you want to change, nothing more. You have commited random files such as: `package.json.bak` and deleted `yarn.lock`