Fixed issue #4998 and refactored, removed deprecated code
PreMiD/Presences pull request #5003
Opened 2021-12-07 12:54 UTC by Pjoottr

If you entered the site being a second user the URL structure would switch, from `stadia.com/home` to `stadia.com/u/1/home`, fixed by checking if the URL included home, then expect the user was at the home page, rather than looking for an exact URL match.

Before:
![image](https://user-images.githubusercontent.com/93800318/145031698-3b4cf55f-2ef2-43c2-adae-4eea28add64c.png)

After:
![image](https://user-images.githubusercontent.com/93800318/145031752-9412506a-630d-49f1-bfcd-364df33b8785.png)

2021-12-07 17:18 UTC, EncryptedDev commented
Fixes #4998

2021-12-07 17:19 UTC, EncryptedDev commented on websites/S/Stadia/presence.ts
> +    startTimestamp: browsingStamp,
Revert this change

2021-12-07 17:19 UTC, EncryptedDev requested changes
bump version

2021-12-07 21:22 UTC, Pjoottr commented on websites/S/Stadia/presence.ts
> +    startTimestamp: browsingStamp,
All done 👍

2021-12-07 21:23 UTC, EncryptedDev reviewed
You still need to bump the version in `metadata.json`

2021-12-07 21:24 UTC, Pjoottr commented
Oh yes, I'm sorry forgot about that. It would be 1.0.10 right?

2021-12-08 08:27 UTC, Slowlife01 commented on websites/S/Stadia/dist/metadata.json
> +  ],
![image](https://user-images.githubusercontent.com/54318514/145173549-92854670-ccc6-42e7-a905-a99d91129331.png)
Not exactly a quarter yet if you add support for library path then sure

2021-12-08 12:31 UTC, Slowlife01 approved these changes

2021-12-08 18:15 UTC, EncryptedDev approved these changes

2021-12-08 18:15 UTC, merged