Fixed Typos.
PreMiD/Presences pull request #5006
Opened 2021-12-07 21:59 UTC by TeiV2

2021-12-07 22:00 UTC, EncryptedDev requested changes
Bump version

2021-12-14 12:17 UTC, alexbcberio submitted a review, later dismissed
Spellings are fixed, there are no errors anymore

2021-12-14 18:39 UTC, EncryptedDev approved these changes

2021-12-15 03:33 UTC, Slowlife01 approved these changes

2021-12-15 03:34 UTC, merged