Add Фугапедия presence
PreMiD/Presences pull request #5014
Opened 2021-12-08 06:27 UTC by Syjalo

The presence for the [Fugapedia](https://fugapedia.xyz)
![preview1](https://user-images.githubusercontent.com/62868468/145159209-68196545-2c50-4a6d-b0ed-ed3112d50349.png)
![preview2](https://user-images.githubusercontent.com/62868468/145159213-4b906937-264e-4e50-b231-833a60116242.png)

2021-12-08 07:44 UTC, EncryptedDev requested changes

2021-12-08 07:44 UTC, EncryptedDev commented on websites/#/Фугапедия/dist/metadata.json
> +  "$schema": "https://schemas.premid.app/metadata/1.3",
Outdated Schema 
```suggestion
  "$schema": "https://schemas.premid.app/metadata/1.5",
```

2021-12-08 07:44 UTC, EncryptedDev commented on websites/#/Фугапедия/presence.ts
> +  startTimestamp = Math.floor(Date.now() / 1000);
```suggestion
  browsingTimestamp = Math.floor(Date.now() / 1000);
```

2021-12-08 07:44 UTC, EncryptedDev commented on websites/#/Фугапедия/presence.ts
> +    startTimestamp
```suggestion
    startTimestamp: browsingTimestamp
```

2021-12-08 12:51 UTC, Slowlife01 requested changes, later dismissed

2021-12-08 12:51 UTC, Slowlife01 commented on websites/#/Фугапедия/presence.ts
> +  }
Remove curly brackets

2021-12-08 12:51 UTC, Slowlife01 commented on websites/#/Фугапедия/presence.ts
> +  }
This too and so on

2021-12-08 13:00 UTC, Syjalo commented
Why not add ESLint to the project?

2021-12-09 19:56 UTC, Bas950 requested changes

2021-12-09 19:56 UTC, Bas950 commented on websites/#/Фугапедия/dist/metadata.json
> +    "ru": "Дайте знать пользователям Discord о том, что вы читаете на Фугапедии!"
Should be a description of the website not the presence.

2021-12-12 00:09 UTC, Bas950 approved these changes

2021-12-12 00:11 UTC, EncryptedDev approved these changes

2021-12-12 00:14 UTC, merged