Added bilibili.tv presence
PreMiD/Presences pull request #5015
Opened 2021-12-08 08:19 UTC by easonuwu

Images:
![video](https://user-images.githubusercontent.com/71189551/145173250-89143070-fea7-4b18-b8e4-0a3ce5609789.png)
![anime](https://user-images.githubusercontent.com/71189551/145173256-8a26512c-2b75-4ac2-8d76-4560bf7d7894.png)

2021-12-08 18:13 UTC, EncryptedDev commented on websites/B/bilibilitv/presence.ts
> +  } else presence.setActivity(presenceData);
```suggestion
if (presenceData.details) presence.setActivity(presenceData);
else presence.setActivity();
```

2021-12-09 19:51 UTC, Bas950 requested changes
Should be added / fixed in https://github.com/PreMiD/Presences/tree/master/websites/B/bilibili

2021-12-10 03:53 UTC, easonuwu commented
Its a different site so, i dont think it should be merged together

2021-12-12 00:08 UTC, Bas950 approved these changes, later dismissed

2021-12-12 00:11 UTC, EncryptedDev commented on websites/B/bilibilitv/presence.ts
> +  } else presence.setActivity(presenceData);
```suggestion
if (presenceData.details) presence.setActivity(presenceData);
  else presence.setActivity();
```

2021-12-12 12:48 UTC, EncryptedDev approved these changes

2021-12-13 07:32 UTC, Slowlife01 approved these changes

2021-12-13 07:32 UTC, merged