Update SiriusXM presence to fix channel name
PreMiD/Presences pull request #5017
Opened 2021-12-08 16:15 UTC by AirborneRadio

After the SiriusXM site updated, they moved channel name to a separate line.
This changed the channel name in Discord to the channel number which isn't very helpful.

Changing the target to ".channel-name" corrects this issue.

2021-12-08 16:54 UTC, EncryptedDev requested changes
Bump version

2021-12-08 18:11 UTC, EncryptedDev submitted a review, later dismissed

2021-12-08 18:12 UTC, EncryptedDev commented
Upload proof of the bug fixed

2021-12-08 20:34 UTC, AirborneRadio commented
![Screenshot 2021-12-08 143405](https://user-images.githubusercontent.com/6321849/145280311-318d1709-97f1-4407-a3bc-6e19c4357a66.png)
![image](https://user-images.githubusercontent.com/6321849/145280351-dedf8436-8d6c-4a59-b442-0b5f9e6b23f3.png)

2021-12-08 21:17 UTC, EncryptedDev approved these changes

2021-12-09 02:13 UTC, Slowlife01 approved these changes

2021-12-09 02:13 UTC, merged