Add presence for Vukkybox (vukkybox.com)
PreMiD/Presences pull request #5019
Opened 2021-12-08 22:02 UTC by memedmusic

2021-12-08 22:05 UTC, EncryptedDev commented
I think you got that metadata file type wrong..

2021-12-08 22:05 UTC, EncryptedDev commented
I think you got that metadata file type wrong..

2021-12-08 22:08 UTC, memedmusic commented
aaaa why did the rename not work properly

2021-12-08 22:08 UTC, ImRodry requested changes
Please install the eslint extension on vscode and fix all the eslint errors, as well as prettier errors

2021-12-08 22:08 UTC, ImRodry commented on websites/V/Vukkybox/presence.ts
> +	  state: "",
This is useless
```suggestion
```

2021-12-08 22:08 UTC, ImRodry commented on websites/V/Vukkybox/dist/metadata.json
> +  "$schema": "https://schemas.premid.app/metadata/1.3",
```suggestion
  "$schema": "https://schemas.premid.app/metadata/1.5",
```

2021-12-08 22:08 UTC, ImRodry commented on websites/V/Vukkybox/dist/metadata.json
> +  "thumbnail": "https://raw.githubusercontent.com/memedmusic/images/main/vukkybox.png",
These must be imgur links

2021-12-08 22:29 UTC, memedmusic commented
I believe that should be everything

2021-12-08 22:29 UTC, ImRodry commented
Resolve the conversations

2021-12-08 22:30 UTC, ImRodry requested changes

2021-12-08 22:30 UTC, ImRodry commented on websites/V/Vukkybox/dist/metadata.json
> +    "thumbnail": "https://imgur.com/uS5AFMi",
these are not image links
```suggestion
    "logo": "https://i.imgur.com/dIpE7wX.png",
    "thumbnail": "https://i.imgur.com/uS5AFMi.png",
```

2021-12-09 19:53 UTC, Bas950 requested changes
Upload proof of it working

2021-12-12 00:07 UTC, Bas950 approved these changes

2021-12-12 00:09 UTC, EncryptedDev approved these changes

2021-12-12 00:09 UTC, merged