Add Danbooru presence
PreMiD/Presences pull request #5031
Opened 2021-12-11 05:37 UTC by kyrie25

Few examples of how the presence works:
* Home page:
![image](https://user-images.githubusercontent.com/77577746/145665332-682697e0-cd8b-4077-a608-fcc445cb8336.png)
* Viewing artwork:
![image](https://user-images.githubusercontent.com/77577746/145665353-9170f1c1-db37-4ceb-b1e0-689e8bca5c78.png)
* Viewing user/artist:
![image](https://user-images.githubusercontent.com/77577746/145665374-58060a38-7fce-4df2-9ec4-07e319db3b8b.png)
![image](https://user-images.githubusercontent.com/77577746/145665389-d7d12a90-269f-405f-81bb-e593e1d224ab.png)
![image](https://user-images.githubusercontent.com/77577746/145665402-b260f39f-841c-45bb-97bc-69b076af343a.png)
* Other miscellaneous presences:
![image](https://user-images.githubusercontent.com/77577746/145665413-1b51d5d1-b4db-4c2a-9f13-4c44ee92c65f.png)
![image](https://user-images.githubusercontent.com/77577746/145665418-659366e6-efb4-41a0-b9a7-b4695e171b7a.png)

2021-12-13 08:39 UTC, Slowlife01 requested changes

2021-12-13 08:39 UTC, Slowlife01 commented on websites/D/Danbooru/dist/metadata.json
> +  "thumbnail": "https://i.imgur.com/h5Whlkk.png",
Please do censor the photos

2021-12-13 09:16 UTC, kyrie25 commented on websites/D/Danbooru/dist/metadata.json
> +  "thumbnail": "https://i.imgur.com/h5Whlkk.png",
Done. Hopefully I didn't miss any.

2021-12-13 09:20 UTC, Slowlife01 approved these changes, later dismissed

2021-12-13 22:30 UTC, ImRodry commented
Please format your file using prettier + eslint (recommended extensions)

2021-12-13 23:32 UTC, kyrie25 commented
> Please format your file using prettier + eslint (recommended extensions)

I did and ESLint showed up with no errors at the time this pull request was made. Prettier was functional also.

2021-12-13 23:44 UTC, ImRodry commented
Nope, I am sure you did not format with prettier, check again

2021-12-14 00:04 UTC, kyrie25 commented
> Nope, I am sure you did not format with prettier, check again

@ImRodry Indeed it wasn't, just ran Prettier again, thanks for the head up!

2021-12-14 18:35 UTC, EncryptedDev commented on websites/D/Danbooru/presence.ts
> +    shortTitle = document.title.split(/[|]/, 1)[0],
Use array deconstructing here
```suggestion
    [shortTitle] = document.title.split(/[|]/, 1),
```

2021-12-14 23:54 UTC, kyrie25 commented on websites/D/Danbooru/presence.ts
> +    shortTitle = document.title.split(/[|]/, 1)[0],
Done.

2021-12-15 03:34 UTC, Slowlife01 approved these changes

2021-12-15 21:13 UTC, EncryptedDev approved these changes

2021-12-15 21:13 UTC, merged