workflows: add lint
PreMiD/Presences pull request #5035
Opened 2021-12-12 23:41 UTC by EncryptedDev

Co-Authored-By: Rodry <38259440+ImRodry@users.noreply.github.com>

2021-12-13 07:34 UTC, Slowlife01 commented on package.json
> +    "lint:ci": "eslint . && prettier **/*.ts **/{metadata,tsconfig}.json",
Is prettier necessary 🤔

2021-12-13 16:53 UTC, ImRodry commented on .github/workflows/SE.yml
> -          cache: "yarn"
this can be undone

2021-12-13 16:53 UTC, ImRodry commented on .github/workflows/SV.yml
> -          cache: "yarn"
this can be undone

2021-12-13 16:54 UTC, EncryptedDev commented on .github/workflows/SE.yml
> -          cache: "yarn"
Boi

2021-12-13 16:54 UTC, ImRodry requested changes

2021-12-13 16:54 UTC, ImRodry commented on package.json
> +    "lint:ci": "eslint .",
rhys do you ever listen to me
```suggestion
    "lint:ci": "eslint . && prettier **/*.ts **/{metadata,tsconfig}.json",
```

2021-12-13 16:56 UTC, ImRodry commented on .github/workflows/SE.yml
> -          cache: "yarn"
what boi

2021-12-13 16:56 UTC, ImRodry commented on package.json
> +    "lint:ci": "eslint . && prettier **/*.ts **/{metadata,tsconfig}.json",
what

2021-12-13 22:20 UTC, Bas950 commented on .github/workflows/SE.yml
> -          cache: "yarn"
can be undone

2021-12-13 22:20 UTC, Bas950 commented on .github/workflows/SV.yml
> -          cache: "yarn"
can be undone

2021-12-14 22:23 UTC, ImRodry commented on .github/workflows/lint.yml
> +          node-version: 16
https://github.com/actions/cache/issues/698
```suggestion
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"
```

2021-12-15 03:44 UTC, Slowlife01 approved these changes

2021-12-16 19:03 UTC, Bas950 approved these changes

2021-12-16 19:26 UTC, merged