Adding New Presence for KaryaKarsa
PreMiD/Presences pull request #5043
Opened 2021-12-14 11:47 UTC by QkieMauln

This is how the presence work.

- At Feeds / HomePage
![DiscordPTB_hcWdCYE1RF](https://user-images.githubusercontent.com/43922147/145991443-9bf65835-56a7-4d87-9349-ad48ab638011.png)

- At Discover
![DiscordPTB_rX0ABSuMP9](https://user-images.githubusercontent.com/43922147/145991598-325eeec0-6227-4a9d-b423-3f962996d950.png)

- At Discover > Search
![DiscordPTB_k6BfSsqXhH](https://user-images.githubusercontent.com/43922147/145991685-2aae463e-4b00-45d8-b8bd-b6321c93c029.png)

- At Dashboard (The state will change depend on subpages)
![DiscordPTB_YNh2UA6jI4](https://user-images.githubusercontent.com/43922147/145991784-6364ae3c-9864-4132-994b-e2f7b7b1c5e7.png)

- At User Profile
![0WimZ4CJBt](https://user-images.githubusercontent.com/43922147/145992061-5324d2ca-8958-44b9-bc53-fb05c6694e65.png)

- At Someone Page
![DiscordPTB_4cfQCGZzVh](https://user-images.githubusercontent.com/43922147/145992238-423e92c6-a0e2-481c-868b-56c8521e3662.png)

- At Someone Post
![DiscordPTB_gDA4nwShFF](https://user-images.githubusercontent.com/43922147/145992329-27ce2211-3c87-421b-826c-531637505c5b.png)

- Default
![DiscordPTB_SEWGy47ApZ](https://user-images.githubusercontent.com/43922147/145992388-328026b5-e2e1-47ed-95cb-0690c4d4336c.png)

2021-12-15 03:36 UTC, Slowlife01 requested changes
Revert your change to yarn.lock and format your code with prettier

2021-12-15 05:38 UTC, QkieMauln commented
> Revert your change to yarn.lock and format your code with prettier

hmm ok, i just hard reset-ed the stuff

2021-12-15 06:28 UTC, Slowlife01 submitted a review, later dismissed

2021-12-15 06:28 UTC, Slowlife01 commented on websites/K/KaryaKarsa/presence.ts
> +presenceData.startTimestamp = timestamp;
```suggestion
const presenceData: PresenceData = {
  largeImageKey: "main",
  startTimestamp: timestamp
};
```

And merge the consts

2021-12-15 06:28 UTC, Slowlife01 commented on websites/K/KaryaKarsa/presence.ts
> +  clientId: "920135248006754394",
No trailing comma

2021-12-15 07:20 UTC, QkieMauln commented on websites/K/KaryaKarsa/presence.ts
> +presenceData.startTimestamp = timestamp;
alright

2021-12-15 07:20 UTC, QkieMauln commented on websites/K/KaryaKarsa/presence.ts
> +  clientId: "920135248006754394",
got it

2021-12-16 21:14 UTC, EncryptedDev requested changes

2021-12-16 21:14 UTC, EncryptedDev commented on websites/K/KaryaKarsa/presence.ts
> +  timestamp = Math.floor(Date.now() / 1000),
```suggestion
  browsingTimestamp = Math.floor(Date.now() / 1000),
```

2021-12-17 00:02 UTC, QkieMauln commented on websites/K/KaryaKarsa/presence.ts
> +  timestamp = Math.floor(Date.now() / 1000),
alrighty

2021-12-17 02:54 UTC, Slowlife01 commented on websites/K/KaryaKarsa/presence.ts
> +      break;
```suggestion
    case "about":
    case "terms":
      presenceData.details = "Looking at Terms of Service";
      break;
```

2021-12-17 06:39 UTC, QkieMauln commented on websites/K/KaryaKarsa/presence.ts
> +      break;
i see, alright

2021-12-17 22:22 UTC, EncryptedDev requested changes

2021-12-17 22:22 UTC, EncryptedDev commented on websites/K/KaryaKarsa/presence.ts
> +  const paths: string[] = window.location.pathname.split("/").splice(1);
Resolve Lint annotation here

2021-12-18 04:34 UTC, QkieMauln commented on websites/K/KaryaKarsa/presence.ts
> +  const paths: string[] = window.location.pathname.split("/").splice(1);
uhh, you mean combine the const?

2021-12-18 14:38 UTC, ImRodry requested changes

2021-12-18 14:38 UTC, ImRodry commented on websites/K/KaryaKarsa/presence.ts
> +      }>;
```suggestion
    arrayPath: {
      name: string;
      state?: string;
      paths?: Array<{
        name?: string;
        state?: string;
      }[];
```

2021-12-18 14:38 UTC, ImRodry commented on websites/K/KaryaKarsa/presence.ts
> +            name: "",
Can't this be removed if it's only an empty string?

2021-12-18 14:38 UTC, ImRodry commented on websites/K/KaryaKarsa/presence.ts
> +    }).state;
Use nullish coalescing and avoid unnecessary type assertions
```suggestion
    const result = arrayPath.find((p) => p.name === (paths[1] ?? ""));
    return result.state ?? result.paths.find(p => {
      const b = p.name === (paths[2] ?? "");
      if (!b && paths[2]) return p.name === "*";
      return b;
    }).state;
```

2021-12-18 14:38 UTC, ImRodry commented on websites/K/KaryaKarsa/presence.ts
> +      presenceData.details = "Looking at HomePage";
Won't suggest on all lines but please avoid unnecessary capitalization in the middle of the sentence
```suggestion
      presenceData.details = "Looking at the home page";
```

2021-12-18 14:38 UTC, ImRodry commented on websites/K/KaryaKarsa/presence.ts
> +  paths: string[] = window.location.pathname.split("/").splice(1);
```suggestion
  paths = window.location.pathname.split("/").splice(1);
```

2021-12-18 14:38 UTC, ImRodry commented on websites/K/KaryaKarsa/presence.ts
> +      );
```suggestion
      const searchBar = document.querySelector<HTMLInputElement>(
          ".q-field.q-input.q-field--filled.q-field--square.q-field--float.q-validation-component input.q-field__native.q-placeholder"
        );
```

2021-12-18 14:38 UTC, ImRodry commented on websites/K/KaryaKarsa/presence.ts
> +      presenceData.details = "Browsing Pages";
If you wanna do what the comment above says (replace if not set), you should be doing this
```suggestion
      presenceData.details ??= "Browsing Pages";
```

2021-12-18 14:38 UTC, ImRodry commented on websites/K/KaryaKarsa/presence.ts
> +      // if no path detected, mean it on homepage
Please either improve the phrasing on these comments or remove them entirely

2021-12-18 14:38 UTC, ImRodry commented on websites/K/KaryaKarsa/presence.ts
> +          );
```suggestion
        const titleUser = document.querySelector<HTMLElement>(
        `${getUserHeader} .q-px-md.q-py-md div`),
          roleUser = document.querySelector<HTMLElement>(
              `${getUserHeader} .q-px-md.q-py-md .text-caption.text-grey-7`);
```

2021-12-18 14:38 UTC, ImRodry commented on websites/K/KaryaKarsa/presence.ts
> +          );
```suggestion
        const titleUser = document.querySelector<HTMLElement>(getUserHeaderHome),
          tagUser = document.querySelector<HTMLElement>(
              "#q-app > div > div > div.q-page-container.main.q-pb-xl.bordered-desktop.post-page > div.post-date.text-body2.q-px-md.q-pt-md.q-pb-sm.post-content > a"
          ),
          postTitle = document.querySelector<HTMLElement>(
              "#q-app > div > div > div.q-page-container.main.q-pb-xl.bordered-desktop.post-page > h1"
          );
```

2021-12-19 01:07 UTC, QkieMauln commented on websites/K/KaryaKarsa/presence.ts
> +          );
Alright, got it

2021-12-19 01:09 UTC, ImRodry commented
Please mark conversations as resolved if you have addressed them

2021-12-22 00:25 UTC, EncryptedDev requested changes

2021-12-22 00:25 UTC, EncryptedDev commented on websites/K/KaryaKarsa/presence.ts
> +          presenceData.state = roleUser.innerText;
```suggestion
          presenceData.details = titleUser.textContent;
          presenceData.state = roleUser.textContent;
```

2021-12-22 00:25 UTC, EncryptedDev commented on websites/K/KaryaKarsa/presence.ts
> +          presenceData.state = postTitle.innerText;
```suggestion
          presenceData.details = `${titleUser.textContent} (${tagUser.textContent})`;
          presenceData.state = postTitle.textContent;
```

2021-12-22 05:49 UTC, QkieMauln commented on websites/K/KaryaKarsa/presence.ts
> +          presenceData.state = postTitle.innerText;
ahh ok

2021-12-23 19:11 UTC, EncryptedDev approved these changes, later dismissed

2021-12-23 19:53 UTC, Bas950 approved these changes

2021-12-23 20:01 UTC, EncryptedDev approved these changes

2021-12-23 20:07 UTC, merged