Update Oculus presence
PreMiD/Presences pull request #5044
Opened 2021-12-15 22:06 UTC by N0chteil

Proof:

<details>
<summary>Comparing Headsets</summary>
<br>
<a href="https://www.oculus.com/compare/">Example</a>
<hr width="25%">
<img src="https://user-images.githubusercontent.com/53608074/146271366-909860cc-8049-466a-a03e-c54bde304617.png">
<img src="https://user-images.githubusercontent.com/53608074/146271373-a27c8968-1040-4c9f-b4ad-02e7b568d1dc.png">
</details>

<details>
<summary>Product</summary>
<br>
<a href="https://www.oculus.com/quest-2/removable-facial-interface-alert/">Example</a>
<hr width="25%">
<img src="https://user-images.githubusercontent.com/53608074/146271574-0af1d0bd-25df-467f-98a6-ab784f7d4d2f.png">
<img src="https://user-images.githubusercontent.com/53608074/146271435-42568f6a-a8bd-4f49-9239-0faf859a5423.png">
</details>

<details>
<summary>VR for Good - Story</summary>
<br>
<a href="https://www.oculus.com/vr-for-good/stories/traveling-while-black-explores-black-america-past-and-present/">Example</a>
<hr width="25%">
<img src="https://user-images.githubusercontent.com/53608074/146271681-15d2076b-e9fa-4833-8082-15060e90e240.jpg">
<img src="https://user-images.githubusercontent.com/53608074/146271666-7085f82c-cf83-4755-b7fc-941407c2a898.png">
</details>

2021-12-15 22:08 UTC, EncryptedDev requested changes

2021-12-15 22:08 UTC, EncryptedDev commented on websites/O/Oculus/dist/metadata.json
> +  "version": "1.2.0",
Bump major

2021-12-15 22:08 UTC, EncryptedDev submitted a review, later dismissed

2021-12-15 22:11 UTC, EncryptedDev commented
Contrary to my previous review, could you bump the version to `1.2.0`? My fault

2021-12-15 22:56 UTC, EncryptedDev approved these changes
lgtm

2021-12-16 01:11 UTC, Bas950 approved these changes

2021-12-16 01:11 UTC, merged