chore(bug_report): improve template
PreMiD/Presences pull request #5069
Opened 2021-12-19 21:00 UTC by ImRodry

This PR improves the bug report template by replacing the steps to reproduce preset value with a placeholder (grey text that disappears once you start writing), makes the "Expected behavior" section an input instead of textarea, adds "Actual behavior" and moves "Screenshots" above these two

2021-12-19 21:58 UTC, EncryptedDev commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        4. see this incorrect behavior
Sounds like some child nursery book

2021-12-19 21:59 UTC, ImRodry commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        4. see this incorrect behavior
Got any better ideas?

2021-12-19 21:59 UTC, EncryptedDev requested changes

2021-12-19 21:59 UTC, EncryptedDev commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      description: Describe what you expected to happen
Debatable

2021-12-19 21:59 UTC, EncryptedDev commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      description: Describe what actually happened
No screenshots are preferable too

2021-12-20 00:43 UTC, EncryptedDev commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        4. see this incorrect behavior
What it was previously

2021-12-22 00:34 UTC, EncryptedDev approved these changes

2021-12-22 01:48 UTC, Slowlife01 approved these changes

2021-12-22 01:48 UTC, merged