feat(EZPPFarm): Add Presence
PreMiD/Presences pull request #5119
Opened 2021-12-25 01:54 UTC by ThomasCatlow

**Describe the changes in this pull request:**

Add presence for EZPPFarm, an osu! private server.

<details>
<summary> Proof to proving the creation/modification working </summary>
<br>

![0aEiAOi](https://user-images.githubusercontent.com/74877901/147375659-8c9c095b-73f8-4957-be12-9bf934dea2ac.png)
![SvuQ6tA](https://user-images.githubusercontent.com/74877901/147375687-87c814fd-aff2-4fce-864c-a1d96e2987be.png)
![V1HjRxU](https://user-images.githubusercontent.com/74877901/147375689-0afa6bfb-adec-43b0-92a5-fb247a4bd384.png)
![KqTKBsG](https://user-images.githubusercontent.com/74877901/147375690-9006c284-d034-44d2-8d61-5354fb5914bf.png)
![tbKpI0X](https://user-images.githubusercontent.com/74877901/147375691-37cdd281-95dd-4493-8e53-981303d04af9.png)
![wSqw5LT](https://user-images.githubusercontent.com/74877901/147375697-eb3f457f-6519-47a8-b646-75e743a677d6.png)

</details>

2021-12-26 06:02 UTC, Slowlife01 submitted a review, later dismissed
Run prettier on your code

2021-12-30 13:43 UTC, Bas950 requested changes

2021-12-30 13:43 UTC, Bas950 commented on websites/E/EZPPFarm/dist/metadata.json
> +  "altnames": ["EZPP"],
Unneeded altname

2021-12-31 18:30 UTC, Bas950 submitted a review, later dismissed

2021-12-31 18:30 UTC, Bas950 commented on websites/E/EZPPFarm/dist/metadata.json
> +  "$schema": "https://schemas.premid.app/metadata/1.5",
```suggestion
  "$schema": "https://schemas.premid.app/metadata/1.6",
```

2022-01-01 18:09 UTC, EncryptedDev requested changes

2022-01-01 18:09 UTC, EncryptedDev commented on websites/E/EZPPFarm/dist/metadata.json
> +  "logo": "https://i.imgur.com/PeNWQYB.png",
Not 512x512

2022-01-01 18:09 UTC, EncryptedDev commented on websites/E/EZPPFarm/dist/metadata.json
> +  ],
Use RegEx?

2022-01-01 18:09 UTC, EncryptedDev commented on websites/E/EZPPFarm/presence.ts
> +  idURL: string;
Do not let values which don't change, use constants where the value is assigned

2022-01-08 16:55 UTC, Slowlife01 commented
Inactive

2022-01-08 16:55 UTC, closed without merging