Trackmania.io 1.2.0
PreMiD/Presences pull request #5135
Opened 2021-12-26 14:20 UTC by GreepTheSheep

**Describe the changes in this pull request:**

<details>
<summary> Added largeImageKey with URLs and add support on new pages </summary>
<br>

Add largeImageKey on several pages:
![image](https://user-images.githubusercontent.com/42576124/147410868-342366f0-0802-4ec1-91ab-a09b9d619c07.png)
![image](https://user-images.githubusercontent.com/42576124/147410876-95ef1cdd-7755-4bc4-aeb2-fa22ce0e86e3.png)
![image](https://user-images.githubusercontent.com/42576124/147410905-5b083c0d-f381-48c5-8735-b168b6fa630b.png)
![image](https://user-images.githubusercontent.com/42576124/147410920-4658e10a-4250-460d-bbe0-a690a9257029.png)

Newest page added:
![image](https://user-images.githubusercontent.com/42576124/147410933-75c84996-8f59-4d44-8258-52b28c3500f4.png)

</details>

2021-12-26 17:52 UTC, Bas950 submitted a review, later dismissed

2021-12-26 18:10 UTC, EncryptedDev requested changes

2021-12-26 18:10 UTC, EncryptedDev commented on websites/T/Trackmania.io/presence.ts
> +          presenceData.largeImageKey = clubImagesArray[0];
```suggestion
          [presenceData.largeImageKey] = clubImagesArray;
```

2021-12-27 04:51 UTC, Slowlife01 approved these changes

2021-12-27 11:33 UTC, EncryptedDev approved these changes

2021-12-27 11:33 UTC, merged