feat(My Nintendo): Complete recode
PreMiD/Presences pull request #5139
Opened 2021-12-26 15:40 UTC by ACertainCoder

**Describe the changes in this pull request:**
Completely recoded the My Nintendo presence.

<details>
<summary> Proof to proving the creation/modification working </summary>
<br>
![My Nintendo](https://user-images.githubusercontent.com/47316898/147413049-e94a768c-1d3a-4f7f-aaad-1c8dc6e5cba0.png)

</details>

2021-12-26 18:02 UTC, Bas950 requested changes

2021-12-26 18:02 UTC, Bas950 commented on websites/M/My Nintendo/presence.ts
>    });
use general strings

2021-12-26 18:08 UTC, EncryptedDev requested changes
- Why did you decide to recode this? 
- Why don't you use a Record instead of the extensive switch-case statement?
- How is the multiLang change handled?

Please remove the exessive:
- Obvious comments, keep them where appropriate, not everywhere 
- `presence.setActivity()`s

2021-12-26 23:24 UTC, EncryptedDev requested changes

2021-12-26 23:24 UTC, EncryptedDev commented on websites/M/My Nintendo/presence.ts
> +}
```suggestion
```

2021-12-26 23:24 UTC, EncryptedDev commented on websites/M/My Nintendo/presence.ts
> +async function getStrings(): Promise<LangStrings> {
```suggestion
async function getStrings() {
```

2021-12-26 23:24 UTC, EncryptedDev commented on websites/M/My Nintendo/presence.ts
> +async function handlePoints(path: string[]): Promise<void> {
Why is this async?

2021-12-26 23:45 UTC, ACertainCoder commented on websites/M/My Nintendo/presence.ts
> +async function handlePoints(path: string[]): Promise<void> {
Consistency

2021-12-27 01:36 UTC, EncryptedDev requested changes

2021-12-28 19:33 UTC, Bas950 requested changes

2021-12-28 19:33 UTC, Bas950 commented on websites/M/My Nintendo/presence.ts
> +  strings = await getStrings();
only fetch on start of when changed

2021-12-28 21:17 UTC, EncryptedDev requested changes

2021-12-28 21:17 UTC, EncryptedDev commented on websites/M/My Nintendo/presence.ts
> +      presenceData.largeImageKey = "logo_big";
Set this in the PresenceData object on L9

2021-12-31 18:32 UTC, Bas950 approved these changes

2021-12-31 19:01 UTC, EncryptedDev approved these changes

2021-12-31 19:01 UTC, merged