Vukkybox 1.1
PreMiD/Presences pull request #5162
Opened 2021-12-27 20:20 UTC by Vukkyy

**Describe the changes in this pull request:** The presence now no longer displays the user's balance in places where it wouldn't be relevant to do so. This also fixes a bug where the presence breaks if you aren't logged in, as your balance now only appears on pages you need to be logged in to use. In addition, support for guest galleries and the login page has been added.

<details>
<summary> Proof to proving the creation/modification working </summary>
<br>

![image](https://user-images.githubusercontent.com/46850780/147504534-4d90358e-6bd3-4684-a8e8-57a4060aa8c0.png)
![image](https://user-images.githubusercontent.com/46850780/147504571-32341d0f-e597-41ef-9c0a-af6be6214dde.png)

</details>

2021-12-27 20:55 UTC, EncryptedDev requested changes
Resolve Lint warns too

2021-12-27 20:55 UTC, EncryptedDev commented on websites/V/Vukkybox/presence.ts
> +    startTimestamp: Date.now()
You should make `Date.now()` a varaible

2021-12-27 20:55 UTC, EncryptedDev commented on websites/V/Vukkybox/presence.ts
> -    presenceData.state = `${
Why did you remove this?

2021-12-27 20:55 UTC, EncryptedDev commented on websites/V/Vukkybox/presence.ts
> +    } lVukkybux left!`;
Typo?

2021-12-27 21:24 UTC, Vukkyy commented on websites/V/Vukkybox/presence.ts
> -    presenceData.state = `${
Sorry, added back now.

2021-12-28 00:28 UTC, EncryptedDev requested changes

2021-12-28 00:28 UTC, EncryptedDev commented on websites/V/Vukkybox/dist/metadata.json
> +    }
Surely not 
![image](https://user-images.githubusercontent.com/64903135/147515399-63b9267b-3c83-4880-8ce1-07c06d8ce1f4.png)

2021-12-28 13:39 UTC, EncryptedDev approved these changes

2021-12-28 14:06 UTC, Slowlife01 approved these changes

2021-12-28 14:06 UTC, merged