feat(PayPal): add presence
PreMiD/Presences pull request #5173
Opened 2021-12-28 14:27 UTC by CrypticXT

**Describe the changes in this pull request:**
Added PayPal Presence

Images:
 ![Discord_DzDrD6pO3t](https://user-images.githubusercontent.com/18153513/147505221-927d7e78-ca8e-4ab6-a4db-f1f927b5d6e9.png)
![Discord_PeNt9spzcx](https://user-images.githubusercontent.com/18153513/147505355-31686e6c-9963-43fd-8118-aec5c89f7d09.png)
![Discord_yBlcEIJ2fx](https://user-images.githubusercontent.com/18153513/147505362-b4c04580-272a-47fc-a8b2-beb157af04ab.png)

2021-12-28 20:00 UTC, Bas950 requested changes, later dismissed

2021-12-28 20:00 UTC, Bas950 commented on websites/W/Wakanim/dist/metadata.json
> +  "version": "1.2.11",
??

2021-12-28 20:13 UTC, CrypticXT commented on websites/W/Wakanim/dist/metadata.json
> +  "version": "1.2.11",
Commited to wrong branch

2021-12-29 20:32 UTC, EncryptedDev requested changes

2021-12-29 20:32 UTC, EncryptedDev commented on websites/P/PayPal/dist/metadata.json
> +  ],
How can a presence have contributors prior to it even being added to the store?
![image](https://user-images.githubusercontent.com/64903135/147700980-c811f2aa-42a5-41c7-aab2-73628a55e708.png)

2021-12-29 20:32 UTC, EncryptedDev commented on websites/P/PayPal/dist/metadata.json
> +  "url": "www.paypal.com",
PayPal use many more URLs than just this, think about supporting a wider range of (sub)domains

2021-12-29 20:32 UTC, EncryptedDev commented on websites/P/PayPal/dist/metadata.json
> +    "en": "PayPal is a online payment service."
This isn't the official description of PayPal

2021-12-29 20:32 UTC, EncryptedDev commented on websites/P/PayPal/dist/metadata.json
> +  "logo": "https://i.imgur.com/3Wg0uLc.png",
Logo must be 512 x 512

2021-12-29 20:32 UTC, EncryptedDev commented on websites/P/PayPal/presence.ts
> +    presenceData.details = "Viewing:";
pref: remove colons in strings

2022-01-01 18:12 UTC, EncryptedDev requested changes, later dismissed

2022-01-01 18:12 UTC, EncryptedDev commented on websites/P/PayPal/presence.ts
> +    presenceData.state = "Dashboard";
For all your `details` and `state`s, only use two lines where the text will be truncated. Otherwise, just use `details

2022-01-01 23:17 UTC, CrypticXT commented
What did I wrong?

```
/home/runner/work/Presences/Presences/websites/G/GAİN/presence.ts
Error:   64:7  error  Expected { after 'if' condition  curly
```

2022-01-01 23:18 UTC, EncryptedDev commented
> What did I wrong?
> 
> ```
> /home/runner/work/Presences/Presences/websites/G/GAİN/presence.ts
> Error:   64:7  error  Expected { after 'if' condition  curly
> ```

Unrelated to your changes and your PR, ignore it

2022-01-03 20:52 UTC, AngeloCore commented
Hey, can you use the newer logo of paypal?
<br>
<img src="https://user-images.githubusercontent.com/62988428/147979105-67c19c74-d064-41ee-b4d3-85f50c773772.png" height="420" ></img>

2022-01-04 01:47 UTC, CrypticXT commented
> Hey, can you use the newer logo of paypal? <img alt="" height="420" src="https://user-images.githubusercontent.com/62988428/147979105-67c19c74-d064-41ee-b4d3-85f50c773772.png">
How about this?
![paypal](https://user-images.githubusercontent.com/18153513/147998967-538079f7-d2ed-4b28-9906-93164980dedf.png)

2022-01-04 12:23 UTC, AngeloCore commented
I don't know, but i prefer the one with text!

2022-01-05 11:24 UTC, AngeloCore commented
Thanks!

2022-01-06 02:03 UTC, CrypticXT commented
> Thanks!

You are welcome!

2022-01-11 16:03 UTC, Slowlife01 requested changes
No please 
![image](https://user-images.githubusercontent.com/54318514/148977546-6d471214-ed09-4ebc-b46e-66a8d80a2c10.png)
![image](https://user-images.githubusercontent.com/54318514/148977827-261cfa3c-555d-46fd-b8b6-5204b424aaa7.png)

2022-01-17 21:20 UTC, EncryptedDev commented
Inactive

2022-01-17 21:20 UTC, closed without merging