feat(Outlook): add presence
PreMiD/Presences pull request #5181
Opened 2021-12-29 07:57 UTC by kyrie25

#### Resolves discussion #5179 

<details>
<summary> Proof of the creation working: </summary>
<br>

![image](https://user-images.githubusercontent.com/77577746/147639437-044d55d1-16e4-47e4-ae5c-012f94cdd5c1.png)
![image](https://user-images.githubusercontent.com/77577746/147639486-b9d967b5-e00c-4e9f-b015-070ce4bf0dd9.png)
![image](https://user-images.githubusercontent.com/77577746/147639536-161bc3d1-dc63-406a-ac64-d040b9fffd6b.png)
![image](https://user-images.githubusercontent.com/77577746/147639598-5819134b-d323-48fa-b95d-e1aa910796b3.png)
![image](https://user-images.githubusercontent.com/77577746/147639637-6175e1ac-3361-4bf4-a1ae-de786d4470bd.png)
![image](https://user-images.githubusercontent.com/77577746/147639807-e94c63f8-76c6-4328-a088-1b6ec89ce95b.png)
![image](https://user-images.githubusercontent.com/77577746/147639664-997b6042-134b-4c97-ad7d-db6a080ed717.png)

</details>

2021-12-29 13:40 UTC, EncryptedDev requested changes

2021-12-29 13:40 UTC, EncryptedDev commented on websites/O/Outlook/presence.ts
> +      if (await presence.getSetting("title")) {
Missing type 
```suggestion
      if (await presence.getSetting<boolean>("title")) {
```

2021-12-29 13:44 UTC, kyrie25 commented on websites/O/Outlook/presence.ts
> +      if (await presence.getSetting("title")) {
done

2021-12-29 15:17 UTC, EncryptedDev requested changes
Use `email` instead of `mail` in the strings. 

```diff
- Viewing sent mails
- Viewing junk mails
+ Viewing sent emails
+ Viewing junk emails
```

2021-12-29 15:20 UTC, kyrie25 commented
Oh I used the `Gmail` presence as reference for the `.details` so thought those were appropriate. Should I continue changing them @EncryptedDev

2021-12-29 15:27 UTC, EncryptedDev commented
> Oh I used the `Gmail` presence as reference for the `.details` so thought those were appropriate. Should I continue changing them @EncryptedDev

I figured. I was actually in the process of rewriting the Gmail presence xD

2021-12-29 20:20 UTC, EncryptedDev reviewed
pref: assign types to querySelectors? you do it in all your other presences

2021-12-29 20:50 UTC, EncryptedDev requested changes

2021-12-29 20:50 UTC, EncryptedDev commented on websites/O/Outlook/presence.ts
> +      } else presenceData.state;
This is useless 
```suggestion
      }
```

2021-12-29 20:50 UTC, EncryptedDev commented on websites/O/Outlook/presence.ts
> +  else presenceData;
```suggestion
```

2021-12-29 23:33 UTC, kyrie25 commented
> pref: assign types to querySelectors? you do it in all your other presences

Oh yeah I forgot about that, will do ASAP

2021-12-30 00:11 UTC, EncryptedDev approved these changes
lgtm

2021-12-30 02:04 UTC, Slowlife01 approved these changes

2021-12-30 02:04 UTC, merged