get settings seperately instead of using map
PreMiD/Presences pull request #5184
Opened 2021-12-29 17:09 UTC by p0lygun

**Describe the changes in this pull request:**

<details>
<summary> Modified getSettings block so that its separate for each setting  </summary>
</details>

2021-12-29 20:17 UTC, EncryptedDev requested changes

2021-12-29 20:17 UTC, EncryptedDev commented on websites/B/Battlefield Portal/presence.ts
> +    description = await presence.getSetting<boolean>("desc"),
Keep the Promise.all, just assign types like this
```suggestion
    [block, time, buttons, name, description] = await Promise.all([
			presence.getSetting<boolean>("block"),
    	presence.getSetting<boolean>("time"),
    	presence.getSetting<boolean>("buttons"),
    	presence.getSetting<boolean>("name"),
    	presence.getSetting<boolean>("desc")
]),
    
```

2021-12-30 15:50 UTC, p0lygun reviewed
updated

2021-12-31 01:37 UTC, EncryptedDev approved these changes

2021-12-31 02:10 UTC, Slowlife01 approved these changes

2021-12-31 02:10 UTC, merged