feat(scrap.tf): add presence
PreMiD/Presences pull request #5190
Opened 2021-12-30 07:11 UTC by Ali-Joon

![sc4](https://user-images.githubusercontent.com/48525075/147729542-c34540eb-b08c-457e-9c89-43039cab301f.PNG)
![sc2](https://user-images.githubusercontent.com/48525075/147729545-c1f3a3ed-5c98-4dfa-8804-6e98196630a5.PNG)
I think I should make some changes after this...

2021-12-30 09:43 UTC, Ali-Joon commented
Is it really necessary to mess with some empty spaces?

2021-12-31 18:41 UTC, Bas950 requested changes, later dismissed

2021-12-31 18:41 UTC, Bas950 commented on websites/S/scrap.tf/dist/metadata.json
> +    "en": "The PriMiD Presence for Scrap.tf! Scrap.tf is one of the best trading websited related to Team Fortress 2"
```suggestion
    "en": "ScrapTF is the largest bot-based TF2 item trading, raffle, and auction website. Buy and sell hats, keys, unusuals, stranges, skins, and more."
```

2022-01-06 16:29 UTC, EncryptedDev approved these changes

2022-01-07 05:04 UTC, Slowlife01 approved these changes

2022-01-07 05:04 UTC, merged