fix(Kickassanime): Add new domain
PreMiD/Presences pull request #5194
Opened 2021-12-30 18:52 UTC by CrypticXT

**Describe the changes in this pull request:**
Added new domain

resolves #5191 

Presence showed nothing before!
Proof that it works:
![Discord_JzYUbf0UC5](https://user-images.githubusercontent.com/18153513/147780111-ed0983b9-aaa1-4e44-84ff-997ce922432c.png)
![Discord_n7gkLhizJm](https://user-images.githubusercontent.com/18153513/147780125-b81dd153-6fb4-4f80-a67b-82ca69f5db2c.png)
![Discord_FHy9dVLRun](https://user-images.githubusercontent.com/18153513/147780133-b9605d5b-a52f-461d-893d-ce12dca613df.png)

2021-12-30 21:22 UTC, EncryptedDev submitted a review, later dismissed

2021-12-30 22:15 UTC, StrikerFRFX requested changes
Was working fine for me whilst updating to show covers, weird.

Suggestion:

2021-12-30 22:15 UTC, StrikerFRFX commented on websites/K/KickAssAnime/dist/metadata.json
>      "kickassanime.rs",
```suggestion
```

2021-12-31 18:44 UTC, Bas950 approved these changes

2021-12-31 19:03 UTC, EncryptedDev approved these changes

2021-12-31 19:03 UTC, merged