feat(Notion): add presence
PreMiD/Presences pull request #5203
Opened 2021-12-31 09:06 UTC by kyrie25

#### Resolves discussion #4538 

<details>
<summary> Proof of the presence working: </summary>
<br>

![image](https://user-images.githubusercontent.com/77577746/147814015-afb89a1e-1b71-437d-b6da-c6cfa1adcc1a.png)
![image](https://user-images.githubusercontent.com/77577746/147814024-547e4cfb-2590-4446-af48-cc94618965e0.png)
![image](https://user-images.githubusercontent.com/77577746/147814049-4476311a-a205-4bc0-9661-be3fe611adab.png)
![image](https://user-images.githubusercontent.com/77577746/147814058-0ee3abe9-472d-4bba-80fd-aec6ef7e1ff2.png)
![image](https://user-images.githubusercontent.com/77577746/147814122-40490216-9257-4ce2-a9c7-6cfd3aaeb914.png)

</details>

2021-12-31 11:02 UTC, kyrie25 commented
Grabs overlay title as `.state`, otherwise return `document.title`
![image](https://user-images.githubusercontent.com/77577746/147819853-2f2f2082-c23e-40a6-a7c8-03160cb6752b.png)

2022-01-01 15:05 UTC, EncryptedDev reviewed
What `overlayTitle`? Is it some sort of privacy filter?

2022-01-01 15:10 UTC, kyrie25 commented
> What `overlayTitle`? Is it some sort of privacy filter?

It's the title of the pop-up on the second screenshot but I had a brainfart and forgot what it's actually called 💀

2022-01-01 15:12 UTC, EncryptedDev commented
> > What `overlayTitle`? Is it some sort of privacy filter?
> 
> It's the title of the pop-up on the second comment's screenshot but I had a brainfart and forgot what it's actually called 💀

In that case, I would add a privacy setting to prevent users stalking my document name

2022-01-01 15:13 UTC, kyrie25 commented
Gonna add it ASAP then

2022-01-01 15:26 UTC, kyrie25 commented
#### Added Settings tab for `Show Document Title`
<details>
<summary> Proof of the modification working: </summary>
<br>

![kFomiAdmR0](https://user-images.githubusercontent.com/77577746/147853946-f0e910e3-1af6-44b2-876e-e58a42f3bb18.png)
![Discord_9zbe9pOYFV](https://user-images.githubusercontent.com/77577746/147853948-d51d7683-c674-4cd1-9ed8-cf357201cdd0.png)
![Discord_I3NZ1Brxkm](https://user-images.githubusercontent.com/77577746/147853951-bb2a5a7c-baa6-447f-a1b9-a82f1a01a885.png)
![Discord_IAgBQ0THSk](https://user-images.githubusercontent.com/77577746/147853953-2b4a51cf-0493-4c93-92c2-62f1a8bef2f8.png)

</details>

2022-01-01 18:06 UTC, EncryptedDev requested changes

2022-01-01 18:06 UTC, EncryptedDev commented on websites/N/Notion/dist/metadata.json
> +      "title": "Show Document Name",
```suggestion
      "title": "Show document Nname",
```

2022-01-03 15:36 UTC, EncryptedDev approved these changes

2022-01-03 15:44 UTC, Slowlife01 approved these changes

2022-01-03 15:44 UTC, merged