fix
PreMiD/Presences pull request #5218
Opened 2022-01-01 19:32 UTC by down-bad

**Describe the changes in this pull request:**

<details>
<summary> Proof to proving the creation/modification working </summary>
<br>

</details>

2022-01-03 15:29 UTC, EncryptedDev requested changes

2022-01-03 15:29 UTC, EncryptedDev commented on websites/G/Google Keep/presence.ts
> +    [, , , , LorLNorId] = location.href.split("/"),
It is silly to use array destructuring here

2022-01-04 18:53 UTC, down-bad commented
Since the original dev is not responding and I want to update the logo, should I change the client id or use an image url?

2022-01-04 22:14 UTC, EncryptedDev commented
> Since the original dev is not responding and I want to update the logo, should I change the client id or use an image url?

I've seen your attempts contacting the presence developer in many different ways - feel free to add yourself as presence author & create a new `clientId`

2022-01-06 16:38 UTC, EncryptedDev approved these changes

2022-01-07 05:05 UTC, Slowlife01 approved these changes

2022-01-07 05:06 UTC, merged