feat(SyncTube): iFrame
PreMiD/Presences pull request #5404
Opened 2022-01-03 05:15 UTC by N0chteil

**Describe the changes in this pull request:**

<details>
<summary> Proof to proving the creation/modification working </summary>
<br>
<img src="https://user-images.githubusercontent.com/53608074/147901185-c2d3b4ce-1b77-4330-b4d2-b17dbd1fc1ae.png">
<img src="https://user-images.githubusercontent.com/53608074/147901186-657bb6dd-3f60-4710-a2a7-03683528c5fa.png">
</details>

2022-01-03 15:16 UTC, EncryptedDev requested changes

2022-01-03 15:16 UTC, EncryptedDev commented on websites/S/SyncTube/iframe.ts
> +  const video: HTMLVideoElement = document.querySelector("video");
```suggestion
  const video = document.querySelector<HTMLVideoElement>("video");
```

2022-01-03 15:16 UTC, EncryptedDev commented on websites/S/SyncTube/iframe.ts
> +  if (video && !isNaN(video.duration)) {
```suggestion
  if (!isNaN(video?.duration)) {
```

2022-01-03 15:16 UTC, EncryptedDev commented on websites/S/SyncTube/presence.ts
> +      logo: await presence.getSetting<number>("logo")
Promise.all

2022-01-05 12:51 UTC, Bas950 approved these changes

2022-01-06 17:07 UTC, EncryptedDev approved these changes

2022-01-06 17:07 UTC, merged