Fixed wrong cap
PreMiD/Presences pull request #5501
Opened 2022-01-05 09:42 UTC by u0f

**Describe the changes in this pull request:**

<details>
<summary> Proof to proving the creation/modification working </summary>
<br>

</details>

2022-01-05 11:34 UTC, down-bad commented on websites/T/Tio Anime/presence.ts
> -    privacy = await presence.getSetting<boolean>("privacy"),
Why'd you remove the type?

2022-01-05 11:34 UTC, down-bad commented on websites/T/Tio Anime/presence.ts
> -    buttons = await presence.getSetting<boolean>("buttons");
Why'd you remove the type?

2022-01-05 11:35 UTC, u0f commented on websites/T/Tio Anime/presence.ts
> -    buttons = await presence.getSetting<boolean>("buttons");
oh, mb

2022-01-05 12:56 UTC, Bas950 requested changes, later dismissed
bump version

2022-01-08 12:39 UTC, ImRodry commented
Title doesn't follow commitlint @EncryptedDev

2022-01-11 17:23 UTC, EncryptedDev approved these changes

2022-01-13 02:13 UTC, Slowlife01 approved these changes

2022-01-13 02:13 UTC, merged