refactor(Stan)
PreMiD/Presences pull request #5504
Opened 2022-01-05 11:41 UTC by Slowlife01

**Describe the changes in this pull request:**
Fixes, refactors, and adds cover image support.

<details>
<summary> Proof to proving the creation/modification working </summary>
<br>

![image](https://user-images.githubusercontent.com/54318514/148211904-6552b512-bac0-4c2b-bd97-96e47c729f9c.png)
</details>

2022-01-05 12:03 UTC, ImRodry requested changes

2022-01-05 12:03 UTC, ImRodry commented on websites/S/Stan/presence.ts
> +    if (value === "undefined") delete presenceData[key as keyof PresenceData];
pretty sure this can never be true and it also seems quite useless

2022-01-05 12:03 UTC, ImRodry commented on websites/S/Stan/presence.ts
> +                : "Watch Video",
use general.buttonWatchVideo instead

2022-01-05 12:10 UTC, ImRodry commented on websites/S/Stan/presence.ts
>      startedSince: ~~(Date.now() / 1000),
I know this PR didn't touch this line but using the bitwise NOT operator yields a slightly misleading value as opposed to Math.round (1 unit smaller)
```suggestion
    startedSince: Math.round(Date.now() / 1000),
```

2022-01-05 12:29 UTC, ImRodry commented on websites/S/Stan/presence.ts
>        delete?: boolean;
Again, up to you if you wanna fix this in this PR but you should probably not use reserved keywords as setting names or properties

2022-01-05 12:45 UTC, ImRodry approved these changes

2022-01-05 12:58 UTC, Bas950 approved these changes

2022-01-06 16:40 UTC, EncryptedDev approved these changes

2022-01-06 16:40 UTC, merged