Feat(EA Origin): Add Presence
PreMiD/Presences pull request #5505
Opened 2022-01-05 12:07 UTC by joerkig

**Describe the changes in this pull request:**
No

<details>
<summary> Proof to proving the creation/modification working </summary>
<br>

![image](https://user-images.githubusercontent.com/44418429/148214536-4db9ab3b-85e3-425f-9fd0-b8bf0d94c473.png)
![image](https://user-images.githubusercontent.com/44418429/148214582-ac3af04d-3d80-4ebc-bd0a-aef04e7f8add.png)
![image](https://user-images.githubusercontent.com/44418429/148214612-43f9ae10-6e64-4bbd-9ca4-f564568e919e.png)
![image](https://user-images.githubusercontent.com/44418429/148214639-6afa99d4-6259-48e5-919d-a33de53b9ba3.png)
![image](https://user-images.githubusercontent.com/44418429/148214675-90870067-ba24-4d0b-83b8-eac64358afbf.png)
![image](https://user-images.githubusercontent.com/44418429/148214730-e56a8f5c-4592-489a-b324-94760d591a3b.png)
![image](https://user-images.githubusercontent.com/44418429/148214760-0d7c2404-395c-487b-8761-a61423fd73c5.png)
![image](https://user-images.githubusercontent.com/44418429/148214791-2be3d86e-0c3a-4982-b6ae-4df5a6aae0ed.png)
![image](https://user-images.githubusercontent.com/44418429/148214825-3a64ef04-8a39-492e-9400-0fea410e0265.png)
![image](https://user-images.githubusercontent.com/44418429/148214851-bdd511e6-5a1c-499c-9a87-48fb5916a77b.png)
![image](https://user-images.githubusercontent.com/44418429/148214866-566d06b9-e551-4f50-8116-a7b4e242f6e4.png)
![image](https://user-images.githubusercontent.com/44418429/148214940-6a9b50c4-5f3f-48f5-a0af-c9aea39eab27.png)

</details>

2022-01-05 12:57 UTC, Bas950 requested changes

2022-01-05 12:57 UTC, Bas950 commented on websites/E/EA Origin/presence.ts
> +    welcome = await presence.getSetting("welcome"),
promise.all and add the types via `getSetting<type>("")`

2022-01-07 11:58 UTC, Slowlife01 approved these changes

2022-01-10 12:50 UTC, Bas950 approved these changes

2022-01-10 12:50 UTC, Bas950 commented on websites/E/EA Origin/presence.ts
> +          ).src;
https://discord.com/channels/493130730549805057/607524579874832446/928096461994987540

2022-01-10 12:50 UTC, merged