chore: enforce commitlint
PreMiD/Presences pull request #5509
Opened 2022-01-05 18:14 UTC by ImRodry

**Describe the changes in this pull request:**

This PR adds husky and pre-commit hooks to the repo in order to enforce the use of commitlint. This is being done in order for us to be able to generate presence changelogs in the future, which is a planned feature for PreMiD v3. All documentation and known issues were also documented on this PR

2022-01-05 18:16 UTC, EncryptedDev requested changes

2022-01-05 18:16 UTC, EncryptedDev commented on .github/COMMIT_CONVENTION.md
> +husky hooks are currently not compatible with GitHub Desktop's commit tool on Node 16+. There is an [open issue](https://github.com/desktop/desktop/issues/12562) about this on their repo, so, unfortu
```suggestion
husky hooks are currently not compatible with GitHub Desktop's commit tool on Node 16+. There is an [open issue](https://github.com/desktop/desktop/issues/12562) about this on their repo, therefore, there is nothing we can do about this. We recommend either committing through the command line, or using VSCode's source control.
```

2022-01-05 18:20 UTC, EncryptedDev submitted a review, later dismissed
seems good mate!

2022-01-08 12:39 UTC, Bas950 approved these changes
big yikes for me

2022-01-08 12:40 UTC, Slowlife01 approved these changes

2022-01-08 12:59 UTC, merged