feat(Danbooru): add settings
PreMiD/Presences pull request #5513
Opened 2022-01-06 01:54 UTC by kyrie25

**Describe the changes in this pull request:**
Added settings to the Danbooru presence
<details>
<summary> Proof of the modification working: </summary>
<br>

![ba9Xe3s5wP](https://user-images.githubusercontent.com/77577746/148315443-15380eaf-95a0-4b5d-892d-8aa24582fd5d.png)
![hAv1kBegs3](https://user-images.githubusercontent.com/77577746/148315447-d2b2ecaa-6ba0-4e73-baed-909c2cc5f1ca.png)
![Discord_FY3Qx3ZB9I](https://user-images.githubusercontent.com/77577746/148315460-5ff7bdec-17e6-45a7-8791-cfa0e9665d90.png)
![Discord_Y2kPKloB4Z](https://user-images.githubusercontent.com/77577746/148315471-dc539fe2-94fe-486a-a0e1-41d7e479d438.png)
![msedge_anUaHRgpFE](https://user-images.githubusercontent.com/77577746/148315486-b608db0a-4151-4b24-ba98-7ef8e8e47876.png)
</details>

2022-01-06 16:43 UTC, EncryptedDev requested changes

2022-01-06 16:43 UTC, EncryptedDev commented on websites/D/Danbooru/presence.ts
> +    presenceData.state = "Browsing...";
this?
```suggestion
    presenceData.details = "Browsing...";
```

2022-01-06 23:37 UTC, kyrie25 commented on websites/D/Danbooru/presence.ts
> +    presenceData.state = "Browsing...";
Yeah that's the one, will fix ASAP

2022-01-07 05:56 UTC, kyrie25 commented
Changed how `Privacy Mode` works to just omitting crucial imfomation
![image](https://user-images.githubusercontent.com/77577746/148498858-6a871edb-7de5-4a75-8a1e-2fa43b58bf76.png)

2022-01-07 07:28 UTC, Slowlife01 approved these changes

2022-01-07 22:38 UTC, EncryptedDev approved these changes

2022-01-07 22:38 UTC, merged