UPDATES logo
PreMiD/Presences pull request #5525
Opened 2022-01-07 08:11 UTC by Makogai

Updated logo

2022-01-07 08:41 UTC, Makogai commented
Bruh what

2022-01-07 09:03 UTC, kyrie25 commented
> Bruh what

You need to bump version + run your codes through Prettier

2022-01-07 09:13 UTC, Slowlife01 commented
Provide proof

2022-01-08 13:55 UTC, Makogai commented
PROOF: 
![image](https://user-images.githubusercontent.com/13592797/148646841-e847258a-3487-478d-a940-1e4d22dd31f8.png)
![image](https://user-images.githubusercontent.com/13592797/148646849-a75bf682-54c5-4b3f-8e24-6e352abb0904.png)

2022-01-10 12:32 UTC, Bas950 approved these changes

2022-01-10 12:32 UTC, Bas950 commented on websites/P/PodcastAddict/presence.ts
> +    ).src;
https://discord.com/channels/493130730549805057/607524579874832446/928096461994987540

2022-01-11 10:56 UTC, Slowlife01 requested changes
Update your fork

2022-01-11 11:06 UTC, Makogai commented
> Update your fork

Will be done soon

2022-01-11 17:33 UTC, EncryptedDev approved these changes

2022-01-17 21:19 UTC, EncryptedDev commented
Inactive

2022-01-17 21:19 UTC, closed without merging