Tracker.gg
PreMiD/Presences pull request #5543
Opened 2022-01-08 14:39 UTC by OGMatrix

Hello!
Another Presence from my side, this Presence is for the Website [Tracker.gg](https://tracker.gg) where gamers can see their Stats in many Games. Currently the Presence supports only the Homepage and the Valorant Game Pages as you can see in the Code. I will make many updates that will always add one more Game Page to the Presence. Later you can also choose wich you want to show and wich not in the Settings. So here are **some** pictures!

**Tracker.gg Homepage**
![image](https://user-images.githubusercontent.com/49974161/148648085-b984079b-be6f-47dc-977d-4588c08e7100.png)

**Tracker.gg Developer Homepage**
![image](https://user-images.githubusercontent.com/49974161/148648147-e5d1e29f-8e8e-40e5-9f4e-125edcbd4c8a.png)

**Tracker.gg Dev Documentation**
![image](https://user-images.githubusercontent.com/49974161/148648172-f51282e0-10e9-4b66-a2a3-a76310626c81.png)

**Tracker.gg Dev APIs**
![image](https://user-images.githubusercontent.com/49974161/148648187-d3b4f336-0607-4062-a50d-87fa92f240eb.png)

**Tracker.gg Valorant Profile Page**
![image](https://user-images.githubusercontent.com/49974161/148648208-d7af53ff-554f-4cdc-a603-74e2d53e973b.png)

**Watching Valorant Lineup Clip**
![image](https://user-images.githubusercontent.com/49974161/148648236-5ad0a49a-f3c8-4821-8e7c-425e1849558b.png)

**Watching Agents**
![image](https://user-images.githubusercontent.com/49974161/148648250-a3a86bcc-6e80-4ba9-b1d2-7d5ca4b0ae15.png)

This were all interesting screenshots!

Have a nice day and im happy to see your Feedback!

2022-01-08 15:59 UTC, OGMatrix commented
Hello, is it okey when the Lint Check isn't successful? Thanks!

2022-01-08 16:04 UTC, EncryptedDev commented
> Hello, is it okey when the Lint Check isn't successful? Thanks!

We wouldn’t have it if it was optional.

2022-01-08 16:06 UTC, OGMatrix commented
> > Hello, is it okey when the Lint Check isn't successful? Thanks!
> 
> We wouldn’t have it if it was optional.

But I don't understand what the errors mean. He tells me to do a line break, but there is already one.

2022-01-08 18:13 UTC, OGMatrix commented
Hello! I have a Question, how should I name the File when I have to URLs added? Thanks!

2022-01-08 19:38 UTC, EncryptedDev requested changes

2022-01-08 19:38 UTC, EncryptedDev commented on websites/T/Tracker.gg/dist/metadata.json
> +    "name": "OGMatrix#8818",
The author name does not include the discriminator
```suggestion
    "name": "OGMatrix",
```

2022-01-08 19:38 UTC, EncryptedDev commented on websites/T/Tracker.gg/dist/metadata.json
> +  "version": "1.0.1",
```suggestion
  "version": "1.0.0",
```

2022-01-08 19:38 UTC, EncryptedDev commented on websites/T/Tracker.gg/presence.ts
> +const trackerPresence = new Presence({ clientId: "929349462365704222" }),
use `presence` instead

2022-01-08 19:38 UTC, EncryptedDev commented on websites/T/Tracker.gg/presence.ts
> +    trackerPage = window.location.pathname,
```suggestion
    { pathname } = window.location,
```

2022-01-08 19:38 UTC, EncryptedDev commented on websites/T/Tracker.gg/presence.ts
> +  trackerBrowsing = Math.floor(Date.now() / 1000);
```suggestion
  browsingTimestamp = Math.floor(Date.now() / 1000);
```

2022-01-08 19:38 UTC, EncryptedDev commented on websites/T/Tracker.gg/presence.ts
> +          .textContent.replace("Dashboard", "");
```suggestion
        const appName = document
          .querySelector<HTMLDivElement>(
            "#app > div.trn-wrapper > div.trn-container > div > main > div.apps > div.content-container > div > div > div > div > div.dashboard__analytics.card.bordered.responsive > header > div > div.left > div:nth-child(2) > div.title"
          )
          .textContent.replace("Dashboard", "");
```

2022-01-08 19:38 UTC, EncryptedDev commented on websites/T/Tracker.gg/presence.ts
> +        trackerPreData.details = "Editing App:";
```suggestion
        trackerPreData.details = "Editing App";
```

2022-01-08 19:38 UTC, EncryptedDev commented on websites/T/Tracker.gg/presence.ts
> +        trackerPreData.smallImageText = appName;
Not needed

2022-01-08 19:38 UTC, EncryptedDev commented on websites/T/Tracker.gg/presence.ts
> +          .toString();
How can't it be a string prior to the string conversion?

2022-01-08 19:38 UTC, EncryptedDev commented on websites/T/Tracker.gg/presence.ts
> +          .querySelector(
```suggestion
          .querySelector<HTMLImageElement>(
```

2022-01-08 19:38 UTC, EncryptedDev commented on websites/T/Tracker.gg/presence.ts
> +          .getAttribute("src")
Could just use the `.src` property

2022-01-08 19:57 UTC, OGMatrix commented on websites/T/Tracker.gg/presence.ts
> +          .getAttribute("src")
Fixed!

2022-01-08 22:11 UTC, ImRodry requested changes
Also title does not follow commitlint

2022-01-08 22:11 UTC, ImRodry commented on websites/T/Tracker.gg/presence.ts
> +  const trackerPreData: PresenceData = {
Consistency
```suggestion
  const presenceData: PresenceData = {
```

2022-01-08 22:14 UTC, OGMatrix commented on websites/T/Tracker.gg/dist/metadata.json
> +  "url": ["tracker.gg", "fortnitetracker.com"],
There are not totally different they are from the same author and the same company, just another website for extra tools.

2022-01-08 22:45 UTC, ImRodry commented on websites/T/Tracker.gg/dist/metadata.json
> +  "url": ["tracker.gg", "fortnitetracker.com"],
The websites appear totally different and none of the code is shared, you should make two different presences

2022-01-11 17:31 UTC, EncryptedDev requested changes
check if your variables are only being used once, seems quite repetitve

2022-01-11 17:31 UTC, EncryptedDev commented on websites/T/Tracker.gg/presence.ts
> +        presenceData.smallImageText = appName;
You do not need to repeat the smallImageKey, it is already set in the state

2022-01-11 17:31 UTC, EncryptedDev commented on websites/T/Tracker.gg/presence.ts
> +        presenceData.state = title;
Copy this throughout your code, L51

```suggestion
        presenceData.details = "Viewing Docs";
        presenceData.state = document.querySelector<HTMLHeadingElement>(
          "#app > div.trn-wrapper > div.trn-container > div > main > div.docs > div.content-container > div > div > h1"
        ).textContent;
```

2022-01-11 17:31 UTC, EncryptedDev commented on websites/T/Tracker.gg/presence.ts
> +      presenceData.smallImageText = playerName;
Repetition

2022-01-11 17:31 UTC, EncryptedDev commented on websites/T/Tracker.gg/presence.ts
> +          .getAttribute("href");
Variables are only used once, you should rebase.

2022-01-11 17:31 UTC, EncryptedDev commented on websites/T/Tracker.gg/presence.ts
> +          .getAttribute("href");
href might exist on HTMLImageElement

2022-01-11 17:31 UTC, EncryptedDev commented on websites/T/Tracker.gg/presence.ts
> +            ).textContent;
Variables are only used once

2022-01-11 17:31 UTC, EncryptedDev commented on websites/T/Tracker.gg/dist/metadata.json
> +  "logo": "https://i.imgur.com/YkjUiwX.png",
Not 512x512

2022-01-11 19:29 UTC, OGMatrix commented on websites/T/Tracker.gg/presence.ts
> +          .getAttribute("href");
Doesn't exist on HTMLImageElement

2022-01-11 20:19 UTC, OGMatrix commented
How can I resolve the conflict?

2022-01-11 21:08 UTC, ImRodry commented
Rebase your branch

2022-01-11 21:26 UTC, EncryptedDev commented
you definitely didn't rebase properly

2022-01-11 23:41 UTC, OGMatrix commented
> Rebase your branch

So delete the Repository and fork it again, right?

2022-01-11 23:57 UTC, ImRodry commented
Wrong, google how to rebase or fix the merge conflicts here on the github website

2022-01-12 14:38 UTC, OGMatrix commented
> Wrong, google how to rebase or fix the merge conflicts here on the github website

It doesn't work, it says everything is up to date.

2022-01-12 14:41 UTC, ImRodry commented
I’m sure it doesn’t. Use the presence-dev channel on Discord if you need help

2022-01-12 14:43 UTC, OGMatrix commented
> I’m sure it doesn’t. Use the presence-dev channel on Discord if you need help

What should I write in the Channel?

2022-01-12 17:03 UTC, OGMatrix commented
Opened a new Pull Request for the Tracker Presence, this will be closed!
You can review it here: https://github.com/PreMiD/Presences/pull/5573

2022-01-12 17:03 UTC, closed without merging