feat(Creepypasta): add presence
PreMiD/Presences pull request #5555
Opened 2022-01-09 21:42 UTC by joerkig

**Describe the changes in this pull request:**
add the creepypasta presence

<details>
<summary> Proof to proving the creation/modification working </summary>
<br>

![image](https://user-images.githubusercontent.com/44418429/148701853-0d5af934-8f9f-46ef-b525-e2ffcc03a6cf.png)
![image](https://user-images.githubusercontent.com/44418429/148701863-31f91767-5c5e-4ce2-8286-33710a1c6568.png)
![image](https://user-images.githubusercontent.com/44418429/148701875-ca8bc931-4842-4d8f-b8a3-4127b93fff47.png)
![image](https://user-images.githubusercontent.com/44418429/148701880-a0278f2d-150a-460d-9975-a0e2e4553dc5.png)
![image](https://user-images.githubusercontent.com/44418429/148701915-1a242c82-3770-4194-b5ad-c8580eea4354.png)
![image](https://user-images.githubusercontent.com/44418429/148701928-5d32ca4d-06ab-4218-835c-e119f80a99a1.png)
![image](https://user-images.githubusercontent.com/44418429/148701955-99bb82bc-dbea-4605-a83f-58df1e422d5c.png)
![image](https://user-images.githubusercontent.com/44418429/148701970-10a075dc-e3fc-46e9-bd5d-9aa2f83353ff.png)
![image](https://user-images.githubusercontent.com/44418429/148701983-58228357-bd2d-4d29-9a6a-af4cda37766b.png)
![image](https://user-images.githubusercontent.com/44418429/148701989-b757618b-7b4e-430e-86ae-3addb0618046.png)
![image](https://user-images.githubusercontent.com/44418429/148701993-cae399b3-6bde-4531-965a-bf17ab9172ff.png)
![image](https://user-images.githubusercontent.com/44418429/148702003-a041a4bf-560b-4e2c-a493-fd16ebfa473c.png)

</details>

2022-01-09 21:48 UTC, EncryptedDev requested changes
Can you not use genertic type casting instead?

2022-01-09 21:51 UTC, joerkig commented
> Can you not use genertic type casting instead?

![image](https://user-images.githubusercontent.com/44418429/148702461-9b90f404-8a47-4031-acfe-6e79a31f3d51.png)

2022-01-09 22:03 UTC, joerkig commented
> > Can you not use genertic type casting instead?
> 
> ![image](https://user-images.githubusercontent.com/44418429/148702461-9b90f404-8a47-4031-acfe-6e79a31f3d51.png)

@EncryptedDev  would you prefer if I did querySelector with generic type casting?

2022-01-11 16:34 UTC, Slowlife01 commented on websites/C/Creepypasta/presence.ts
> +        (document.getElementsByName("_orderby")[0] as HTMLSelectElement)
Can you make it a variable instead?

2022-01-13 02:27 UTC, Slowlife01 approved these changes

2022-01-14 15:45 UTC, EncryptedDev approved these changes

2022-01-14 15:45 UTC, merged