fix(HentaiZ): change domain & fix iframe
PreMiD/Presences pull request #5580
Opened 2022-01-13 10:26 UTC by kyrie25

**Describe the changes in this pull request:**
Resolves #4879 

~~I don't know why and don't want to know why but 450 people are using this presence so~~

<details>
<summary> Proof of the modification working: </summary>
<br>

![image](https://user-images.githubusercontent.com/77577746/149312477-a5b3879d-8182-4bee-bd29-3f84071901cb.png)
![image](https://user-images.githubusercontent.com/77577746/149312489-53d22751-5fc7-4c0f-8254-92fa6a0289da.png)

</details>

2022-01-13 11:11 UTC, Slowlife01 submitted a review, later dismissed

2022-01-14 03:28 UTC, kyrie25 commented
I misunderstood the presence owner's intention

- Fixed the presence so that it'd detect pages:
![image](https://user-images.githubusercontent.com/77577746/149446619-55a9166f-acb1-4acf-bdb2-b80842478e22.png)
- Changes how the movies are displayed:
![Discord_bViRlzC5nC](https://user-images.githubusercontent.com/77577746/149446707-b1096ba2-e75c-4783-9124-9fc4b5c21768.png)

2022-01-14 03:51 UTC, Slowlife01 commented on websites/H/HentaiZ/presence.ts
> +  if (!document.getElementsByClassName("mr-1")[0].querySelector("h2")) {
Is this basically just

```suggestion
  if (!document.querySelector(".mr-1 h2")) {
```

2022-01-14 03:53 UTC, kyrie25 commented on websites/H/HentaiZ/presence.ts
> +  if (!document.getElementsByClassName("mr-1")[0].querySelector("h2")) {
Will test ASAP

2022-01-14 03:55 UTC, kyrie25 commented on websites/H/HentaiZ/presence.ts
> +  if (!document.getElementsByClassName("mr-1")[0].querySelector("h2")) {
Yes it is

2022-01-14 04:10 UTC, kyrie25 commented on websites/H/HentaiZ/presence.ts
> +  if (!document.getElementsByClassName("mr-1")[0].querySelector("h2")) {
Yes it is, will fix ASAP

2022-01-14 23:43 UTC, EncryptedDev requested changes

2022-01-14 23:43 UTC, EncryptedDev commented on websites/H/HentaiZ/presence.ts
> +    playback = video !== null && !isNaN(video.duration),
```suggestion
    playback = !isNaN(video?.duration),
```

2022-01-15 05:19 UTC, Slowlife01 approved these changes

2022-01-15 10:09 UTC, EncryptedDev approved these changes

2022-01-15 10:09 UTC, merged