LABY.net - v1.1.0
PreMiD/Presences pull request #5616
Opened 2022-01-18 20:32 UTC by Northernside

**Describe the changes in this pull request:**
```diff
+ /badges is now displaying an own presence detail (Screenshot 1)
+ /cloak is now displaying an own presence detail (Screenshot 2)
+ Added buttons for certain links (Screenshot 3 - 8)

*** Fixed an issue where PreMiD can't display the viewed username
*** Fixed an issue where the LABY.net Presence freezes when viewing/searching for an invalid username/UUID
*** Changed some weird unlogical code (lmao)
```

<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

![image](https://user-images.githubusercontent.com/60970791/150013549-b6fdd57d-78b6-422c-b208-90070cbc4274.png)
![image](https://user-images.githubusercontent.com/60970791/150013600-e2df7988-4481-4a53-bf70-e55dd1532bd3.png)
![image](https://user-images.githubusercontent.com/60970791/150013642-fe9bbdfb-3ee0-40c7-966f-1a4952370208.png)
![image](https://user-images.githubusercontent.com/60970791/150013667-f4cf4397-9fde-4c59-8de3-f3fdddfb7deb.png)
![image](https://user-images.githubusercontent.com/60970791/150013683-1162d44d-54f4-420c-8e37-14a15d515527.png)
![image](https://user-images.githubusercontent.com/60970791/150013711-d58e0d1b-442f-4ad1-a54e-f0912ca81b89.png)

</details>

2022-01-18 20:52 UTC, N0chteil reviewed
Some suggestions

2022-01-18 20:52 UTC, N0chteil commented on websites/L/LABY.net/presence.ts
> +          document.querySelector("div.col-12>h1")?.textContent
```suggestion
          document.querySelector("div.col-12>h1")?.textContent ?? "Unknown"
```

2022-01-18 20:52 UTC, N0chteil commented on websites/L/LABY.net/presence.ts
> +    presenceData.state = document.querySelector("div.mb-1>h1").textContent;
```suggestion
    presenceData.state = document.querySelector("div.mb-1>h1")?.textContent ?? "Unknown";
```

2022-01-18 20:52 UTC, N0chteil commented on websites/L/LABY.net/presence.ts
> +          document.querySelector("div.mb-1>h1")?.textContent
```suggestion
          document.querySelector("div.mb-1>h1")?.textContent ?? "Unknown"
```

2022-01-18 20:52 UTC, N0chteil commented on websites/L/LABY.net/presence.ts
> +    presenceData.state = document.querySelector("div.mb-1>h1").textContent;
```suggestion
    presenceData.state = document.querySelector("div.mb-1>h1")?.textContent ?? "Unknown Badge";
```

2022-01-18 20:52 UTC, N0chteil commented on websites/L/LABY.net/presence.ts
> +          document.querySelector("div.mb-1>h1")?.textContent
```suggestion
          document.querySelector("div.mb-1>h1")?.textContent ?? "Unknown Badge"
```

2022-01-18 20:52 UTC, N0chteil commented on websites/L/LABY.net/presence.ts
> +          document.querySelector("div.server-info-wrapper>h1")?.textContent
```suggestion
          document.querySelector("div.server-info-wrapper>h1")?.textContent ?? "Unknown Cape"
```

2022-01-18 20:52 UTC, N0chteil commented on websites/L/LABY.net/presence.ts
> +        label: "View this cloak",
```suggestion
        label: "View this Cloak",
```

2022-01-18 20:52 UTC, N0chteil commented on websites/L/LABY.net/presence.ts
> +    presenceData.details = "Viewing a LabyMod cloak";
```suggestion
    presenceData.details = "Viewing a LabyMod Cloak";
```

2022-01-18 20:52 UTC, N0chteil commented on websites/L/LABY.net/presence.ts
> +    presenceData.details = "Viewing cape:";
```suggestion
    presenceData.details = "Viewing Cape:";
```

2022-01-18 20:52 UTC, N0chteil commented on websites/L/LABY.net/presence.ts
>      presenceData.details = "Viewing profile of:";
```suggestion
    presenceData.details = "Viewing Profile of:";
```

2022-01-18 20:52 UTC, N0chteil commented on websites/L/LABY.net/presence.ts
>      presenceData.details = "Viewing skins";
```suggestion
    presenceData.details = "Viewing Skins";
```

2022-01-18 20:52 UTC, N0chteil commented on websites/L/LABY.net/presence.ts
>      presenceData.details = "Viewing Minecraft capes";
```suggestion
    presenceData.details = "Viewing Minecraft Capes";
```

2022-01-18 20:52 UTC, N0chteil commented on websites/L/LABY.net/presence.ts
> +    presenceData.details = "Viewing LabyMod cloaks";
```suggestion
    presenceData.details = "Viewing LabyMod Cloaks";
```

2022-01-18 20:52 UTC, N0chteil commented on websites/L/LABY.net/presence.ts
> +    presenceData.details = "Viewing LABY.net badges";
```suggestion
    presenceData.details = "Viewing LABY.net Badges";
```

2022-01-18 20:52 UTC, N0chteil commented on websites/L/LABY.net/presence.ts
> +    presenceData.details = "Viewing profile settings";
```suggestion
    presenceData.details = "Viewing Profile Settings";
```

2022-01-18 20:52 UTC, N0chteil commented on websites/L/LABY.net/presence.ts
> +    presenceData.details = "Viewing a Minecraft skin";
```suggestion
    presenceData.details = "Viewing a Minecraft Skin";
```

2022-01-18 20:52 UTC, N0chteil commented on websites/L/LABY.net/presence.ts
> +        label: "View this Minecraft skin",
```suggestion
        label: "View this Minecraft Skin",
```

2022-01-18 20:52 UTC, N0chteil commented on websites/L/LABY.net/presence.ts
>      presenceData.details = "Viewing server:";
```suggestion
    presenceData.details = "Viewing Server:";
```

2022-01-18 21:08 UTC, Northernside commented
I'm rerunning Lint again tomorrow. Got no time today anymore

2022-01-19 08:42 UTC, Northernside commented
Oh my god, me the idiot forgot to change branches. Imma try to undo this

2022-01-19 22:30 UTC, ImRodry commented
This needs a rebase

2022-01-20 09:52 UTC, Northernside commented
> This needs a rebase

Hey there,
I'm not that familiar with Git yet - so my question is: how do I rebase? Via the CLI, right? But how? I tried using [this](https://gist.github.com/nnja/a1888523ec851c6b94b2647956d5c3b4) tutorial but I don't know how many commits I need to rebase nor how to check for how many I need. Also if I do the alternate way with `git merge-base patch-2 master`, it says following: `fatal: Not a valid object name patch-2`. And yes, I CD'ed into the local repository directory.

2022-01-21 15:15 UTC, Bas950 approved these changes

2022-01-21 15:16 UTC, Bas950 requested changes

2022-01-21 15:16 UTC, Bas950 commented on websites/H/HBO GO/dist/metadata.json
> +	"service": "HBO GO",
undo changes to hbo file

2022-01-21 18:05 UTC, Bas950 approved these changes

2022-01-21 21:49 UTC, EncryptedDev approved these changes

2022-01-21 21:49 UTC, merged