chore: enforce the use of tabs
PreMiD/Presences pull request #5623
Opened 2022-01-19 23:13 UTC by EncryptedDev

Co-Authored-By: Rodry <38259440+ImRodry@users.noreply.github.com>

**Describe the changes in this pull request:**
@ImRodry messed this up so I fixed it

2022-01-19 23:37 UTC, ImRodry requested changes

2022-01-19 23:37 UTC, ImRodry commented on @types/premid/index.d.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
we should probably not do this and disable it per line

2022-01-19 23:56 UTC, Bas950 approved these changes

2022-01-20 01:52 UTC, Slowlife01 approved these changes

2022-01-20 16:49 UTC, merged