feat(Granblue Fantasy): add several features
PreMiD/Presences pull request #5627
Opened 2022-01-20 01:41 UTC by kyrie25

**Describe the changes in this pull request:**
Add specific boss HP as `.state` & Add option to `Show main character` as `.largeImageKey`
<details>
<summary> Proof of the modification working: </summary>
<br>

![image](https://user-images.githubusercontent.com/77577746/149046948-d1872ede-57c4-4b97-8d9e-1a977224c895.png)
![image](https://user-images.githubusercontent.com/77577746/149046967-08f2b67f-4f65-4df5-8218-6199c882b0fd.png)
![image](https://user-images.githubusercontent.com/77577746/149047013-403942e0-39fa-478b-989f-8eee582c6d47.png)
![image](https://user-images.githubusercontent.com/77577746/149156634-7053ec92-15dd-4280-915a-75e4fa58fa4d.png)
![image](https://user-images.githubusercontent.com/77577746/149156728-65c97dde-b04f-43f5-b028-73df3245d8fb.png)
![image](https://user-images.githubusercontent.com/77577746/149161642-151c8214-1054-4474-be41-ef16ff423299.png)
![image](https://user-images.githubusercontent.com/77577746/149167217-59a3f999-65fc-4226-a857-1a4f54bf9476.png)
</details>

2022-01-21 15:14 UTC, Bas950 requested changes
rebase / solve conflicts

2022-01-22 00:18 UTC, kyrie25 commented
> rebase / solve conflicts

Done

2022-01-22 10:52 UTC, Bas950 approved these changes

2022-01-22 10:52 UTC, EncryptedDev approved these changes

2022-01-22 10:53 UTC, merged