fix(Chia Sẻ Nhạc): delete `.startTimestamp`
PreMiD/Presences pull request #5628
Opened 2022-01-20 05:04 UTC by kyrie25

**Describe the changes in this pull request:**
Delete `.startTimestamp` that would show up _even when_ the player is paused so as to not create confusion with the media player's time
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

- Before:
![image](https://user-images.githubusercontent.com/77577746/150276745-47603395-b6a8-4f4b-b30a-d4a05143160e.png)
- After:
![image](https://user-images.githubusercontent.com/77577746/150276757-5aa8c99d-9b7b-4996-bd85-598d75ad4280.png)

</details>

2022-01-21 15:15 UTC, Bas950 requested changes
rebase / solve conflicts

2022-01-22 00:17 UTC, kyrie25 commented
> rebase / solve conflicts

Done

2022-01-22 10:46 UTC, EncryptedDev approved these changes

2022-01-22 10:53 UTC, Bas950 approved these changes

2022-01-22 10:53 UTC, merged