feat(The New York Times): add features, edit code
PreMiD/Presences pull request #5632
Opened 2022-01-20 22:47 UTC by N0chteil

**Describe the changes in this pull request:**

- Added "myaccount.nytimes.com"
- Added some features
- Updated code

<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>
<img src="https://user-images.githubusercontent.com/53608074/150431642-3e78519c-4724-4bed-b17b-70615dd762e5.png">
<img src="https://user-images.githubusercontent.com/53608074/150431767-1624b946-6260-48e6-bcc4-507e92bf091e.png">
<img src="https://user-images.githubusercontent.com/53608074/150432151-5f76c28a-7965-42af-8403-0b23133186d9.png">
<img src="https://user-images.githubusercontent.com/53608074/150434254-debe7661-472c-4db9-9779-2dc6b8b8eefa.png">
</details>

_Waiting for "John Smith"'s approval_

2022-01-21 15:21 UTC, Bas950 requested changes
use tabs

2022-01-22 10:50 UTC, Bas950 submitted a review, later dismissed

2022-01-22 10:50 UTC, Bas950 commented on websites/T/The New York Times/presence.ts
> +			moreDetails: await presence.getSetting("moreDetails")
cant you like promise.all this?

2022-01-22 10:51 UTC, EncryptedDev commented on websites/T/The New York Times/presence.ts
> +			moreDetails: await presence.getSetting("moreDetails")
and add types

2022-01-22 11:03 UTC, Slowlife01 commented on websites/T/The New York Times/presence.ts
> +	const { title } = document,
```suggestion
	const title = document.title.replace(" - The New York Times", ""),
```

2022-01-23 15:07 UTC, Slowlife01 commented on websites/T/The New York Times/presence.ts
> +				)}`;
```suggestion
				presenceData.state = `${podcast.textContent}: ${title}`;
```

2022-01-23 15:14 UTC, Slowlife01 approved these changes

2022-01-23 17:35 UTC, EncryptedDev approved these changes

2022-01-23 17:35 UTC, merged