LookMovie Fixed
PreMiD/Presences pull request #5646
Opened 2022-01-23 13:32 UTC by DarkVillager

**Describe the changes in this pull request:**
- New application, old one didnt work anymore.
- Fixed LookMovie's Browse
- Added new url (for watching)
- Fixed Timestamps
- Fixed Browsing String

<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

<img src="https://user-images.githubusercontent.com/42322979/150680895-589448d8-1c21-4ba2-ace0-9850a684c974.jpg">
<img src="https://user-images.githubusercontent.com/42322979/150680896-1a21b850-e05e-461f-a8e1-73e3fcf86879.jpg">
<img src="https://user-images.githubusercontent.com/42322979/150680895-589448d8-1c21-4ba2-ace0-9850a684c974.jpg">
</details>

2022-01-23 17:34 UTC, EncryptedDev commented
Presence contains pirated content which is illegal. 

Reference: [Article](https://techyjungle.com/lookmovie-ag-guide/#:~:text=By%20reading%20the%20description%2C%20we%20can%20conclude%20that%20any%20movie%20or%20TV%20show%20not%20streamed%20directly%20by%20the%20production%20house%20is%20illegal%20and%20cannot%20be%20legally%20accessed.%20In%20the%20same%20way%2C%20Lookmovie%20is%20an%20illicit%20piracy%20website) & [Quora](https://www.quora.com/Why-is-Lookmovie-ag-not-working)

2022-01-23 21:27 UTC, EncryptedDev commented
Draft until discussed further

2022-02-03 07:56 UTC, EncryptedDev requested changes

2022-02-03 07:56 UTC, EncryptedDev commented on websites/L/LookMovie/dist/metadata.json
> +			"name": "PreMiD",
Remove this

2022-02-03 07:56 UTC, EncryptedDev commented on websites/L/LookMovie/presence.ts
> +		video: HTMLVideoElement = document.querySelector("#video_player"),
```suggestion
		video = document.querySelector<HTMLVideoElement>("#video_player"),
```

2022-02-03 07:56 UTC, EncryptedDev commented on websites/L/LookMovie/presence.ts
> +	if (video !== null && videoDur !== null) {
```suggestion
	if (video && videoDur) {
```

2022-02-03 07:56 UTC, EncryptedDev commented on websites/L/LookMovie/presence.ts
> +		const titles = document.querySelector(
Use generic types here too

2022-02-09 13:24 UTC, Slowlife01 commented on websites/L/LookMovie/presence.ts
> +			) as HTMLMetaElement,
```suggestion
		const titles = document.querySelector<HTMLMetaElement>(
				'meta[property="og:title"]'
			),
```

2022-02-11 20:20 UTC, Bas950 requested changes

2022-02-11 20:20 UTC, Bas950 commented on websites/L/LookMovie/presence.ts
>  		pause: "presence.playback.paused",
use general strings

2022-02-12 10:06 UTC, Bas950 approved these changes

2022-02-12 10:43 UTC, EncryptedDev approved these changes

2022-02-12 10:43 UTC, merged

2022-02-12 14:26 UTC, evilstriker commented
The function of displaying movies and series in the Discord presence is not functional.

2022-02-13 13:57 UTC, DarkVillager commented
> The function of displaying movies and series in the Discord presence is not functional.

will check out. Seems like only the url changed