Init
PreMiD/Presences pull request #5664
Opened 2022-01-25 17:22 UTC by alex-ench

2022-01-26 22:06 UTC, EncryptedDev reviewed
Upload proof of workign

2022-01-26 22:13 UTC, alex-ench commented
> Upload proof of the presence working

https://i.imgur.com/gpi5wbw.png

2022-01-27 02:43 UTC, Syjalo requested changes

2022-01-27 02:43 UTC, Syjalo commented on websites/S/Shikimori/dist/metadata.json
> +    "en": "Online encyclopedia of anime and manga. Full list of manga in Russian. Shikimori.one is the best anime chat forum.",
```suggestion
    "en": "Shikimori is online encyclopedia of anime and manga. The full list of popular manga in Russian. Shikimori.one is the best anime forum to communicate in.",
```

2022-01-27 02:55 UTC, Syjalo requested changes

2022-01-27 02:55 UTC, Syjalo commented on websites/S/Shikimori/dist/metadata.json
> +    "ru": "Шикимори - онлайн энциклопедия аниме и манги. Полный список популярной манги на русском. Shikimori.one - лучший аниме-форум для общения."
```suggestion
    "ru": "Шикимори — онлайн энциклопедия аниме и манги. Полный список популярной манги на русском. Shikimori.one — лучший аниме-форум для общения."
```
To comply with the Russian language rules

2022-01-27 13:04 UTC, ImRodry commented on websites/S/Shikimori/dist/metadata.json
> +    "en": "Online encyclopedia of anime and manga. Full list of manga in Russian. Shikimori.one is the best anime chat forum.",
First sentence has grammar incoherencies

2022-02-03 22:40 UTC, EncryptedDev approved these changes

2022-02-09 12:46 UTC, Bas950 approved these changes

2022-02-09 12:46 UTC, merged