feat(AnimeDigitalNetwork): Added cover art
PreMiD/Presences pull request #5690
Opened 2022-01-30 11:42 UTC by DarkVillager

**Describe the changes in this pull request:**
- Added cover art

<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

<img src="https://user-images.githubusercontent.com/42322979/151698143-d83089da-eed9-40ab-a2fa-fdfc1edb73ed.png">
<img src="https://user-images.githubusercontent.com/42322979/151698170-ec874782-692f-483f-94bd-d02fee86a50c.png">
</details>

2022-01-31 06:00 UTC, Slowlife01 requested changes, later dismissed

2022-02-03 13:00 UTC, Bas950 requested changes

2022-02-03 13:00 UTC, Bas950 commented on websites/A/AnimeDigitalNetwork/presence.ts
> +			titles.content.replace(/\/web\/.*/, "/web/affiche_370x0.jpg") ?? "logo";
```suggestion
		const titles = document.querySelector<HTMLMetaElement>(
			'meta[property="og:image"]'
		);
		presenceData.largeImageKey =
			titles?.content?.replace(/\/web\/.*/, "/web/affiche_370x0.jpg") ?? "logo";
```

2022-02-03 13:17 UTC, Bas950 approved these changes

2022-02-03 16:53 UTC, EncryptedDev approved these changes

2022-02-03 16:54 UTC, merged