feat(Brainly): add presence
PreMiD/Presences pull request #5696
Opened 2022-01-31 06:33 UTC by suryomujahid

**Describe the changes in this pull request:**
Resolves #5439 
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>
<img src="https://user-images.githubusercontent.com/55552003/151747268-f325fa7c-df5d-4b6f-b459-67760631205a.png">
<br>
<img src="https://user-images.githubusercontent.com/55552003/151748836-9965c897-ee7b-4987-9586-77d34c3a7c06.png">
<img src="https://user-images.githubusercontent.com/55552003/151748628-52f3e0b5-6e28-4411-b5da-b64395090e2d.png">
<img src="https://user-images.githubusercontent.com/55552003/151747297-2b59cdfa-05fe-4cfa-bde7-4c4a6701dbef.png">
<img src="https://user-images.githubusercontent.com/55552003/151747309-33894543-b374-411c-a853-f075ffc6c9e9.png">
<img src="https://user-images.githubusercontent.com/55552003/151747314-0995603f-21d2-4aba-8a2b-76d558f065cf.png">
<img src="https://user-images.githubusercontent.com/55552003/151747322-cb368991-8a55-433a-883c-192242e3b947.png">
<img src="https://user-images.githubusercontent.com/55552003/151747329-32d25e54-806a-4d9d-90fa-e262150a352b.png">
</details>

2022-02-01 02:51 UTC, xn-oah commented
https://i.imgur.com/fP9yIAo.png
I think a logo like this might look better tbh, but idk.

Also, shouldn't the color of the presence be #000000 since the majority of the logo uses that color?

2022-02-03 12:58 UTC, Bas950 approved these changes, later dismissed

2022-02-03 16:58 UTC, EncryptedDev approved these changes
Use type generic for all your querySelectors. For example `document.querySelector<HTMLInputElement>("foo bar")

2022-02-03 16:58 UTC, EncryptedDev commented on websites/B/Brainly/presence.ts
> +			) as HTMLInputElement
```suggestion
			document.querySelector<HTMLInputElement>(
				"div.brn-attachment-grabber-container > textarea"
			) 
```

2022-02-03 16:59 UTC, EncryptedDev requested changes

2022-02-03 16:59 UTC, EncryptedDev commented on websites/B/Brainly/presence.ts
> +			) as HTMLInputElement
This change please

2022-02-04 00:05 UTC, suryomujahid commented on websites/B/Brainly/presence.ts
> +			) as HTMLInputElement
Done, I use HTMLTextAreaElement instead

2022-02-04 07:44 UTC, EncryptedDev approved these changes

2022-02-07 15:50 UTC, Slowlife01 approved these changes

2022-02-07 15:51 UTC, merged