feat(E621): add privacy mode
PreMiD/Presences pull request #5706
Opened 2022-02-01 14:46 UTC by DarkVillager

Resolves #5328
**Describe the changes in this pull request:**
- Added Privacy Mode
- Changed Buttons not to show when Privacy mode is enabled
- Added Check to use the right button text
- Changed buttons text

<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

<img src="https://user-images.githubusercontent.com/42322979/151989926-fc2205da-f614-4b6d-adb3-d0a98934dbb1.jpg">
<img src="https://user-images.githubusercontent.com/42322979/151989932-a5673d9a-c01e-4d77-bda8-63c039a2b442.jpg">
<img src="https://user-images.githubusercontent.com/42322979/151989935-cef06944-2f86-42f7-afeb-e00209bb5011.jpg">
<img src="https://user-images.githubusercontent.com/42322979/151989939-8a2d0472-8941-42a4-b135-d4a28c0c9609.jpg">
<img src="https://user-images.githubusercontent.com/42322979/151989940-c470010d-1d45-4b12-92ad-36626da8d167.jpg">

</details>

2022-02-03 13:00 UTC, Bas950 requested changes

2022-02-03 13:00 UTC, Bas950 commented on websites/E/e621/presence.ts
> +		privacy = await presence.getSetting<boolean>("privacy"),
promise.all

2022-02-03 13:17 UTC, Bas950 submitted a review, later dismissed
empty strings are falsy on their own

2022-02-03 13:17 UTC, Bas950 commented on websites/E/e621/presence.ts
> +			if (search.value !== "") {
```suggestion
			if (search.value) {
```

2022-02-03 13:17 UTC, Bas950 commented on websites/E/e621/presence.ts
> +				search.value !== "" &&
```suggestion
				search.value &&
```

2022-02-03 13:17 UTC, Bas950 commented on websites/E/e621/presence.ts
> +					(search.value !== "" &&
```suggestion
					(search.value &&
```

2022-02-03 13:17 UTC, Bas950 commented on websites/E/e621/presence.ts
> +			if (search.value !== "") {
```suggestion
			if (search.value) {
```

2022-02-03 13:17 UTC, Bas950 commented on websites/E/e621/presence.ts
> +			if (search.value !== "") {
```suggestion
			if (search.value) {
```

2022-02-03 13:17 UTC, Bas950 commented on websites/E/e621/presence.ts
> +			if (search.value !== "") {
```suggestion
			if (search.value) {
```

2022-02-03 13:17 UTC, Bas950 commented on websites/E/e621/presence.ts
> +			if (search.value !== "") {
```suggestion
			if (search.value) {
```

2022-02-09 13:28 UTC, Slowlife01 approved these changes

2022-02-09 19:37 UTC, EncryptedDev approved these changes

2022-02-09 19:37 UTC, merged