feat(Funimation): poster and patch
PreMiD/Presences pull request #5713
Opened 2022-02-02 08:55 UTC by Slowlife01

**Describe the changes in this pull request:**
Fixes #5575

<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

![image](https://user-images.githubusercontent.com/54318514/152122570-cc77a3d6-5626-41a3-b120-df39d9a8a5ed.png)

</details>

2022-02-03 13:04 UTC, Bas950 requested changes

2022-02-03 13:04 UTC, Bas950 commented on websites/F/Funimation/presence.ts
> +			: (await strings).play;
maybe do the await strings that we have in other presences

2022-02-04 17:12 UTC, EncryptedDev approved these changes

2022-02-09 12:44 UTC, Bas950 approved these changes

2022-02-09 12:44 UTC, merged