refactor(CSGO Stash): improve everything?
PreMiD/Presences pull request #5729
Opened 2022-02-04 16:11 UTC by kyrie25

**Describe the changes in this pull request:**
~~I hate myself, if I don't do this my conscience will eat away at me~~
(Almost) complete rewrite
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

![image](https://user-images.githubusercontent.com/77577746/152563034-76dbceae-ab5e-47af-b642-ed00fb0e6c75.png)
![image](https://user-images.githubusercontent.com/77577746/152563038-93556a7d-1db7-430a-ba24-e1e3bd483249.png)

</details>

2022-02-04 22:14 UTC, EncryptedDev requested changes, later dismissed

2022-02-04 22:14 UTC, EncryptedDev commented on websites/C/CSGO Stash/presence.ts
> +		),
Use types here too
```suggestion
		priceLeft = document.querySelector<HTMLSpanElement>(
			"#prices > div:nth-child(2) > a > span.pull-left"
		),
		priceRight = document.querySelector<HTMLSpanElement>(
			"#prices > div:nth-child(2) > a > span.pull-right"
		),
		priceMiddle = document.querySelector<HTMLAnchorElement>(
			"a.btn.btn-default.market-button-item"
		),
		steamPrice = document.querySelector<HTMLSpanElement>(
			"div.col-md-6.col-md-6-collapse-top-margin > div:nth-child(2) > a > span.pull-right"
		),
```

2022-02-07 15:30 UTC, Slowlife01 commented on websites/C/CSGO Stash/presence.ts
>  	} else if (path.indexOf("google-search") > -1) {
```suggestion
	} else if (path.includes("google-search")) {
```

2022-02-09 12:54 UTC, Bas950 approved these changes

2022-02-09 13:21 UTC, Slowlife01 approved these changes

2022-02-09 13:22 UTC, merged