feat(Animekimi): Update Presence
PreMiD/Presences pull request #5755
Opened 2022-02-08 16:42 UTC by Faelayis

**Describe the changes in this pull request: improve presence details**

<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

![image](https://user-images.githubusercontent.com/48393914/153033540-8b87939e-69da-4f31-a6ea-197ae2970f10.png)
![image](https://user-images.githubusercontent.com/48393914/153033696-64fb74da-268d-414f-bf65-b6cecc30205b.png)
</details>

2022-02-09 13:52 UTC, Slowlife01 requested changes

2022-02-09 13:52 UTC, Slowlife01 commented on websites/A/Animekimi/dist/metadata.json
> +	"version": "1.1.9",
```suggestion
	"version": "1.2.0",
```

2022-02-09 13:52 UTC, Slowlife01 commented on websites/A/Animekimi/presence.ts
> +		case pathArray[3] === "movies":
Would be better if you use switch on `pathArray[3]` instead

2022-02-14 00:54 UTC, Slowlife01 approved these changes

2022-02-14 00:56 UTC, EncryptedDev approved these changes

2022-02-14 00:56 UTC, merged