feat(CDKeys): added presence
PreMiD/Presences pull request #5758
Opened 2022-02-09 09:24 UTC by DarkVillager

**Describe the changes in this pull request:**
- Added CDKeys

<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

<img src="https://user-images.githubusercontent.com/42322979/153164898-871b5a49-5731-4ee7-b631-291b5bee210b.png">
<img src="https://user-images.githubusercontent.com/42322979/153164927-ab6821dc-06ad-4acc-bef4-f1c0a48f1e52.png">
<img src="https://user-images.githubusercontent.com/42322979/153164932-f138470f-d0fe-41b2-943e-daab183ef16d.png">
<img src="https://user-images.githubusercontent.com/42322979/153164937-af666cf0-d0cf-4deb-87a9-3fa9077bb459.png">
<img src="https://user-images.githubusercontent.com/42322979/153164939-6ac0d01c-1908-41d5-96e6-ff43134b8ca5.png">
<img src="https://user-images.githubusercontent.com/42322979/153164974-26c31d5d-028a-46fd-9d90-20bf994dddc3.png">

</details>

2022-02-09 13:04 UTC, Bas950 commented
lint

2022-02-11 20:19 UTC, Bas950 requested changes
Looking at:
Xbox Games

Maybe like that?
Just Xbox games doesnt say anything

2022-02-12 10:07 UTC, Bas950 approved these changes

2022-02-12 10:43 UTC, EncryptedDev approved these changes

2022-02-12 10:43 UTC, merged