feat(ArchLinux): add presence
PreMiD/Presences pull request #5762
Opened 2022-02-09 22:32 UTC by critamine

**Describe the changes in this pull request:**

- First coding project and PR!
- Added basic presence support for ArchLinux.org

<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![archLinux](https://user-images.githubusercontent.com/67632697/153301224-5b5a6efa-5413-4e4c-8c6f-50c566ace77d.gif)

</details>

2022-02-09 22:35 UTC, critamine reviewed
Corrected version in metadata.json

2022-02-11 20:17 UTC, Bas950 requested changes

2022-02-11 20:17 UTC, Bas950 commented on websites/A/ArchLinux/presence.ts
> +presence.on("UpdateData", async () => {
```suggestion
	path1 = webPath.split("/")[1];

presence.on("UpdateData", async () => {
```

2022-02-11 20:17 UTC, Bas950 commented on websites/A/ArchLinux/presence.ts
> +	const archData: dt = {
```suggestion
	const archData: {
		[hostName: string]: {
			[webPath: string]: {
				[data: string]: string;
			}
		}
	} = {
```

2022-02-11 20:36 UTC, critamine reviewed
Thank you for taking the time to review this and offer feedback.

2022-02-11 20:37 UTC, critamine reviewed
Changes reviewed

2022-02-11 21:01 UTC, critamine reviewed
I think I unviewed/un-reviewed a file here. Fixing that. Apologies for cluttering up the PR! New to this.

2022-02-12 19:13 UTC, EncryptedDev requested changes

2022-02-12 19:13 UTC, EncryptedDev commented on websites/A/ArchLinux/presence.ts
> +	webPath = location.pathname,
```suggestion
	{ pathname, hostname } = document.location,
```

2022-02-14 00:31 UTC, critamine commented on websites/A/ArchLinux/presence.ts
> +	webPath = location.pathname,
Ohhh! Cool! Thank you!

2022-02-14 00:37 UTC, critamine reviewed
Changes reviewed. Thank you so much for looking!

2022-02-16 12:45 UTC, Bas950 approved these changes

2022-02-16 13:36 UTC, EncryptedDev approved these changes

2022-02-16 13:36 UTC, merged