feat(lolz.guru): new presence
PreMiD/Presences pull request #5764
Opened 2022-02-09 23:40 UTC by MrLivixx

**Describe the changes in this pull request:**
 - New website [lolz.guru](https://lolz.guru)
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>
<img src="https://user-images.githubusercontent.com/54632865/152891248-6e62d900-673e-4ca9-8f89-f9de112b4f9d.png">
<img src="https://user-images.githubusercontent.com/54632865/152891278-089e9d45-171f-4172-ac74-1b79f6187ab1.png">
<img src="https://user-images.githubusercontent.com/54632865/152891325-6e03fa17-8742-4b36-baaf-9426b990b31c.png">
<img src="https://user-images.githubusercontent.com/54632865/152891455-9422e7fe-cef1-4a9f-9490-85831f9b8a72.png">
<img src="https://user-images.githubusercontent.com/54632865/152891573-8e0334f9-f197-45df-9b83-6ff1eda92e33.png">
<img src="https://user-images.githubusercontent.com/54632865/152891634-17a291b3-e670-4fd6-8e9d-28485e9528f8.png">
<img src="https://user-images.githubusercontent.com/54632865/152891690-f9739ac4-d8bd-4a44-8eaa-7c62788ac5e4.png">

</details>

2022-02-12 19:12 UTC, EncryptedDev requested changes
Use tabs on metadata

2022-02-12 22:35 UTC, Bas950 approved these changes

2022-02-14 00:47 UTC, EncryptedDev approved these changes

2022-02-14 00:47 UTC, merged

2022-02-14 00:48 UTC, EncryptedDev commented
Thank you for your contribution!