feat(WayBackMachine): new presence
PreMiD/Presences pull request #5769
Opened 2022-02-10 12:25 UTC by DarkVillager

**Describe the changes in this pull request:**
- Added waybackmachine presence

<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

<img src="https://user-images.githubusercontent.com/42322979/153408148-6d020ab3-5144-4d47-ba1a-89fb46345d69.png">
<img src="https://user-images.githubusercontent.com/42322979/153408151-7063d22b-e858-4481-8a4f-e329bfaa349a.png">
<img src="https://user-images.githubusercontent.com/42322979/153408155-3bc36ed8-4f6f-4e5a-82b1-049d13607d76.png">
<img src="https://user-images.githubusercontent.com/42322979/153408159-7f7a3aca-65ed-4d42-b88e-4d73217a60bf.png">

</details>

2022-02-11 20:23 UTC, Bas950 requested changes

2022-02-11 20:23 UTC, Bas950 commented on websites/W/WayBack Machine/presence.ts
> +let search: HTMLInputElement, title: HTMLElement, title2: HTMLElement;
title defined but not used?

2022-02-12 10:08 UTC, Bas950 approved these changes

2022-02-12 10:44 UTC, EncryptedDev approved these changes

2022-02-12 10:44 UTC, merged