fix(bilibilitv): Episode undefined
PreMiD/Presences pull request #5775
Opened 2022-02-11 12:40 UTC by Loneth

**Describe the changes in this pull request:**

<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

**Before:**
![Screenshot_177](https://user-images.githubusercontent.com/54299183/153592817-da45ba67-2696-4603-bbc5-0cb57b7e2964.png)

**After:**
![Screenshot_178](https://user-images.githubusercontent.com/54299183/153592847-dfbb4b89-9069-46a6-ade2-3e41ea2d3a2f.png)

</details>

2022-02-11 20:24 UTC, Bas950 requested changes
Please run prettier

2022-02-12 05:47 UTC, Loneth commented
i'm sorry, my prettier isn't working i will try it again

2022-02-12 09:59 UTC, EncryptedDev approved these changes

2022-02-12 10:09 UTC, Bas950 approved these changes

2022-02-12 10:09 UTC, merged