feat(FMovies): add presence
PreMiD/Presences pull request #5823
Opened 2022-02-16 23:21 UTC by kyrie25

**Describe the changes in this pull request:**
Resolves #5254 
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

![image](https://user-images.githubusercontent.com/77577746/154374100-d3d68d6c-b86d-4a73-83a0-99ed09107872.png)
![image](https://user-images.githubusercontent.com/77577746/154374108-88d70a07-eeef-4819-96cb-f1e6b4ea2070.png)
![image](https://user-images.githubusercontent.com/77577746/154374112-310222c6-872c-4a77-ab3e-fdec26932a4f.png)
![image](https://user-images.githubusercontent.com/77577746/154374114-287ec1df-584e-4cff-b936-fea9c8f2d1ce.png)

</details>

2022-02-16 23:23 UTC, EncryptedDev requested changes

2022-02-16 23:23 UTC, EncryptedDev commented on websites/F/FMovies/iframe.ts
> +	const video: HTMLVideoElement = document.querySelector("video");
```suggestion
	const video = document.querySelector<HTMLVideoElement>("video");
```

2022-02-16 23:23 UTC, EncryptedDev commented on websites/F/FMovies/iframe.ts
> +	if (video && !isNaN(video.duration)) {
```suggestion
	if (!isNaN(video?.duration)) {
```

2022-02-16 23:49 UTC, EncryptedDev requested changes, later dismissed

2022-02-16 23:49 UTC, EncryptedDev commented on websites/F/FMovies/presence.ts
> +		if (iFrameData && !iFrameData.paused) {
```suggestion
		if (!iFrameData?.paused) {
```

2022-02-17 04:35 UTC, Slowlife01 approved these changes
lgtm

2022-02-17 21:34 UTC, EncryptedDev approved these changes

2022-02-17 21:34 UTC, merged