fix(YouTube): use regex for image rescaling
PreMiD/Presences pull request #5824
Opened 2022-02-17 08:18 UTC by down-bad

Fix for upcoming youtube layout, and futureproofing in general

2022-02-17 08:37 UTC, EncryptedDev requested changes

2022-02-17 08:37 UTC, EncryptedDev commented on websites/Y/YouTube/dist/metadata.json
> +	"version": "5.1.22",
```suggestion
	"version": "5.2.0",
```

2022-02-17 21:36 UTC, EncryptedDev approved these changes

2022-02-18 10:25 UTC, Slowlife01 approved these changes

2022-02-18 10:25 UTC, merged