feat(ComicK): fix presence & add features
PreMiD/Presences pull request #5877
Opened 2022-02-27 03:52 UTC by kyrie25

**Describe the changes in this pull request:**
Fix presence malfunctioning, add Settings option to show/hide Cover Image & Buttons, add support for Manga List
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

![image](https://user-images.githubusercontent.com/77577746/155867446-81ba5266-d133-461e-97b8-397a3fe1a27d.png)
![image](https://user-images.githubusercontent.com/77577746/155867447-a4d956eb-ff44-4164-9b37-a3ae149434df.png)
![image](https://user-images.githubusercontent.com/77577746/155867450-b93f0dd7-cdf9-46ec-bd87-0b7bd8ccf339.png)
![image](https://user-images.githubusercontent.com/77577746/155867453-b0e42f6f-36f6-43ed-b526-e6cd83bc04ad.png)

</details>

2022-02-27 11:06 UTC, EncryptedDev requested changes

2022-02-27 11:06 UTC, EncryptedDev commented on websites/C/ComicK/presence.ts
> +					label: "Check Description",
```suggestion
					label: "Read Description",
```

2022-02-27 11:45 UTC, EncryptedDev approved these changes

2022-02-28 08:47 UTC, Slowlife01 approved these changes

2022-02-28 08:47 UTC, merged