fix(Discord): Added Korean language
PreMiD/Presences pull request #5896
Opened 2022-03-03 14:03 UTC by GreenScreen410

**Describe the changes in this pull request:**
Added Korean language in metadata.json
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>
**Added by using translator tool**
</details>

2022-03-03 14:44 UTC, Slowlife01 requested changes
Bump version.

2022-03-04 11:24 UTC, GreenScreen410 reviewed
Changed version 3.0.13 to 3.0.14.

2022-03-04 15:54 UTC, EncryptedDev commented
On hold, waiting approval of a proofreader

2022-03-04 16:00 UTC, EncryptedDev approved these changes

2022-03-04 16:24 UTC, Slowlife01 approved these changes

2022-03-04 16:24 UTC, merged