feat(BeatSaver): add watching preview
PreMiD/Presences pull request #5902
Opened 2022-03-05 23:00 UTC by joerkig

**Describe the changes in this pull request:**

add watching preview
fix made by bot icon

<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

![NVIDIA_Share_Z2mhNfka5g](https://user-images.githubusercontent.com/44418429/156901679-b8855919-0f1a-4bd1-b948-01991a8193ca.png)
![NVIDIA_Share_9TNqqV7wtJ](https://user-images.githubusercontent.com/44418429/156901680-663c38a8-1301-434a-ab7a-9e5f3c11d69e.png)
![NVIDIA_Share_rZlWvbztbc](https://user-images.githubusercontent.com/44418429/156901681-7e4a12da-67c3-49a3-89d1-63d15ec7f080.png)

</details>

2022-03-06 07:35 UTC, Slowlife01 requested changes

2022-03-06 07:35 UTC, Slowlife01 commented on websites/B/BeatSaver/dist/metadata.json
> +	"version": "2.2.6",
```suggestion
	"version": "2.2.0",
```

2022-03-07 11:58 UTC, Slowlife01 approved these changes

2022-03-07 17:57 UTC, EncryptedDev approved these changes

2022-03-07 17:57 UTC, merged