chore(Otakudesu): update website domain
PreMiD/Presences pull request #5904
Opened 2022-03-06 02:32 UTC by ZenShibata

**Describe the changes in this pull request:**

<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

![](https://user-images.githubusercontent.com/45705890/151114385-60b7e7f2-56cd-4994-ab56-6bc8c14129e9.png)
</details>

2022-03-06 09:17 UTC, EncryptedDev requested changes

2022-03-06 09:17 UTC, EncryptedDev commented on websites/O/Otakudesu/dist/metadata.json
> +	"version": "1.0.16",
```suggestion
	"version": "2.0.0",
```

2022-03-06 10:25 UTC, EncryptedDev approved these changes

2022-03-07 11:32 UTC, Slowlife01 approved these changes

2022-03-07 11:32 UTC, merged