feat(Showtime): added other domain
PreMiD/Presences pull request #5905
Opened 2022-03-06 07:51 UTC by DarkVillager

**Describe the changes in this pull request:**
- Added official domain to the presence

<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

<img src="https://user-images.githubusercontent.com/42322979/156914171-253af077-5ed9-4a12-b794-6dda74e9cd7f.jpg">

</details>

2022-03-07 17:59 UTC, EncryptedDev requested changes

2022-03-07 17:59 UTC, EncryptedDev commented on websites/S/Showtime/dist/metadata.json
> +	"version": "1.2.15",
```suggestion
	"version": "1.3.0",
```

2022-03-10 17:12 UTC, Bas950 approved these changes

2022-03-10 23:10 UTC, EncryptedDev approved these changes

2022-03-10 23:11 UTC, merged