feat(Apple Music): video support, settings
PreMiD/Presences pull request #5910
Opened 2022-03-07 18:01 UTC by down-bad

![image](https://user-images.githubusercontent.com/19146783/157091349-9117fc00-8c15-4d26-bb1f-9404a5219962.png)

2022-03-07 18:02 UTC, EncryptedDev requested changes

2022-03-07 18:02 UTC, EncryptedDev commented on websites/A/Apple Music/presence.ts
> +			presenceData.smallImageKey = "https://i.imgur.com/Es4p1V5.png";
Upload this asset to the ddevs app

2022-03-10 17:09 UTC, Bas950 approved these changes

2022-03-10 23:10 UTC, EncryptedDev approved these changes

2022-03-10 23:11 UTC, merged