feat(TwitCasting): add presence
PreMiD/Presences pull request #5927
Opened 2022-03-11 08:30 UTC by kyrie25

**Describe the changes in this pull request:**
Resolves #5922 
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

![image](https://user-images.githubusercontent.com/77577746/157830302-5595e50c-e5bc-425a-9bca-9c3fdbf3b49e.png)
![image](https://user-images.githubusercontent.com/77577746/157830312-506acb7c-4970-4fac-9da5-27064c364366.png)
![image](https://user-images.githubusercontent.com/77577746/157830320-2c077626-34db-4c46-beef-2919a1bed43c.png)
![image](https://user-images.githubusercontent.com/77577746/157830330-8dbe510f-1464-4669-aa5b-b7569e1dfdab.png)
![image](https://user-images.githubusercontent.com/77577746/157830346-b2110e30-329e-46a0-af96-03a9042fd18c.png)
![image](https://user-images.githubusercontent.com/77577746/157830351-6c67d163-35cd-4dd6-908f-b28555e6a896.png)
![image](https://user-images.githubusercontent.com/77577746/157830414-fccce0fa-b03b-4929-af18-77495d7952f2.png)
![image](https://user-images.githubusercontent.com/77577746/157830793-97c134bc-278f-4bff-ba40-c12efb706b49.png)
![image](https://user-images.githubusercontent.com/77577746/157830447-31c8ecc4-1972-4c2f-bceb-49361fb98ca8.png)

</details>

2022-03-12 23:42 UTC, EncryptedDev requested changes
Hello! Please take a look at my requested changes. Do not commit as you will have to update references

2022-03-12 23:42 UTC, EncryptedDev commented on websites/T/TwitCasting/presence.ts
> +				watchVideo: "general.buttonWatchVideo"
Best for consistency
```suggestion
				playing: "general.playing",
				paused: "general.paused",
				live: "general.live",
				viewHome: "general.viewHome",
				viewProfile: "general.viewProfile",
				buttonViewProfile: "general.buttonViewProfile",
				browsing: "general.browsing",
				watchingLive: "general.watchingLive",
				watchingVid: "general.watchingVid",
				viewCategory: "general.viewCategory",
				viewTheir: "twitch.viewTheir",
				followList: "twitch.followList",
				dashboardManage: "twitch.dashboardManage",
				subs: "twitch.subs",
				browsingVideos: "youtube.browsingVideos",
				ofChannel: "youtube.ofChannel",
				searchFor: "general.searchFor",
				searchSomething: "general.searchSomething",
				search: "general.search",
				buttonWatchStream: "general.buttonWatchStream",
				buttonWatchVideo: "general.buttonWatchVideo"
```

2022-03-13 02:13 UTC, kyrie25 commented on websites/T/TwitCasting/presence.ts
> +				watchVideo: "general.buttonWatchVideo"
Done

2022-03-18 22:21 UTC, EncryptedDev approved these changes

2022-03-19 06:26 UTC, Slowlife01 approved these changes

2022-03-19 06:26 UTC, merged