feat(Q-dance): add cover
PreMiD/Presences pull request #5928
Opened 2022-03-11 15:08 UTC by DarkVillager

**Describe the changes in this pull request:**
- Added cover for q-dance & volume meter in precentage as small image key
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

<img src="https://user-images.githubusercontent.com/42322979/157893678-e4f3b8a6-bfb6-4183-8c3b-2514a5e2af87.png">

</details>

2022-03-18 22:26 UTC, EncryptedDev requested changes
After a discussion with my team, we have determined that having the volume displaying is unnecessary. Please remove this

2022-04-25 16:12 UTC, Slowlife01 commented on websites/Q/Q-dance/presence.ts
> +				?.getAttribute("src") ?? "logo";
```suggestion
			document
				.querySelector<HTMLImageElement>(
					"div.audioplayer-nowplaying__image > img"
				)
				?.src ?? "logo";
```

2022-04-26 16:52 UTC, Bas950 commented on websites/Q/Q-dance/presence.ts
> -			(presenceData.smallImageText = (await strings).live);
why text being removed?

2022-04-29 15:54 UTC, EncryptedDev commented on websites/Q/Q-dance/presence.ts
> -			(presenceData.smallImageText = (await strings).live);
Unresolved

2022-05-01 19:04 UTC, EncryptedDev commented on websites/Q/Q-dance/presence.ts
> -			(presenceData.smallImageText = (await strings).live);
Still unresolved?

2022-05-02 11:34 UTC, DarkVillager commented on websites/Q/Q-dance/presence.ts
> -			(presenceData.smallImageText = (await strings).live);
check line 17

2022-05-02 17:22 UTC, ImRodry approved these changes, later dismissed

2022-05-02 17:46 UTC, EncryptedDev submitted a review, later dismissed

2022-05-07 11:21 UTC, ImRodry approved these changes

2022-05-12 06:22 UTC, Slowlife01 approved these changes

2022-05-12 06:22 UTC, merged