PHP.net presence
PreMiD/Presences pull request #5936
Opened 2022-03-13 16:07 UTC by iLazlow

**Describe the changes in this pull request:**
This pull requests adds a presence for the php.net website
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

![poc_php_docs_1](https://user-images.githubusercontent.com/3432412/158068344-3633bae1-ddfa-4092-8c4e-953f5a1f7239.png)
![poc_php_docs_2](https://user-images.githubusercontent.com/3432412/158068337-11d14196-97c2-4a36-9b15-adac467b3648.png)
![poc_php_docs_3](https://user-images.githubusercontent.com/3432412/158068338-8d95e620-fa96-41d3-a573-ebefd343583f.png)
![poc_php_docs_4](https://user-images.githubusercontent.com/3432412/158068339-69ac19e8-998c-4fa0-98fa-32c2ab6dede9.png)
![poc_php_docs_5](https://user-images.githubusercontent.com/3432412/158068340-e65734d1-b993-4469-8c8a-5ce40028f6cc.png)
![poc_php_docs_6](https://user-images.githubusercontent.com/3432412/158068341-bc52e60a-7cca-4f69-8224-ffb68bca0ecf.png)
![poc_php_docs_7](https://user-images.githubusercontent.com/3432412/158068343-14082111-dc80-4c9e-8fd9-abf274806d48.png)
</details>

2022-03-13 18:23 UTC, DarkVillager commented
**Instead of:**
![poc_php_docs_1](https://user-images.githubusercontent.com/3432412/158068344-3633bae1-ddfa-4092-8c4e-953f5a1f7239.png) 
**use:**
<img src=“https://user-images.githubusercontent.com/3432412/158068344-3633bae1-ddfa-4092-8c4e-953f5a1f7239.png”>

2022-03-14 22:06 UTC, EncryptedDev requested changes
Hi, thank you for opening this pull request. I have requested some changes found below: 

Reach out to me on Discord if you need any further help

2022-03-14 22:06 UTC, EncryptedDev commented on websites/P/PHP.net/dist/metadata.json
> +	"thumbnail": "https://i.imgur.com/O0eMrCB.png",
This is not big enough to be a thumbnail

2022-03-14 22:06 UTC, EncryptedDev commented on websites/P/PHP.net/dist/metadata.json
> +		"en": "The official website and documentation for PHP."
Not the official description for php

2022-03-14 22:06 UTC, EncryptedDev commented on websites/P/PHP.net/dist/metadata.json
> +		"other",
I don't see the point in this

2022-03-14 22:06 UTC, EncryptedDev commented on websites/P/PHP.net/dist/metadata.json
> +		"php",
Irrelevant tags too

2022-03-14 22:06 UTC, EncryptedDev commented on websites/P/PHP.net/presence.ts
> +	browsingStamp = Math.floor(Date.now() / 1000);
```suggestion
	browsingTimestamp = Math.floor(Date.now() / 1000);
```

2022-03-14 22:06 UTC, EncryptedDev commented on websites/P/PHP.net/presence.ts
> +	const data: PresenceData = {
use `presenceData` instead

2022-03-14 22:06 UTC, EncryptedDev commented on websites/P/PHP.net/tsconfig.json
> +}
You should format with tabs

2022-03-17 13:19 UTC, iLazlow reviewed
I've changed the requested files in my last commit. Please let me know if there is anything wrong.

2022-03-18 22:23 UTC, EncryptedDev submitted a review, later dismissed

2022-03-24 03:23 UTC, Slowlife01 requested changes

2022-03-24 03:23 UTC, Slowlife01 commented on websites/P/PHP.net/presence.ts
> +	];
Remove button on the main page

2022-03-24 05:05 UTC, Slowlife01 approved these changes

2022-03-24 07:13 UTC, EncryptedDev approved these changes

2022-03-24 07:13 UTC, merged