feat(Explain xkcd): add presence
PreMiD/Presences pull request #5969
Opened 2022-03-24 05:02 UTC by theusaf

**Describe the changes in this pull request:**
Adds a presence for the explainxkcd.com website.

<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

<img width="224" alt="2022-03-23 21_38_49-meme - Discord" src="https://user-images.githubusercontent.com/32113157/159845640-77a326d2-4f79-4ad6-ab05-bac784681012.png">
<img width="224" alt="2022-03-23 21_39_08-meme - Discord" src="https://user-images.githubusercontent.com/32113157/159845641-4d726bf3-11f0-4ee5-ada7-03b2539f90a2.png">
<img width="227" alt="2022-03-23 21_39_29-meme - Discord" src="https://user-images.githubusercontent.com/32113157/159845642-9d3a16e1-74da-4ae0-b39d-ff1f4d4e8fa6.png">
<img width="223" alt="2022-03-23 21_39_37-meme - Discord" src="https://user-images.githubusercontent.com/32113157/159845643-798fe6c4-c47f-41f2-b55a-f07ded5fe063.png">
<img width="227" alt="2022-03-23 21_39_48-meme - Discord" src="https://user-images.githubusercontent.com/32113157/159845645-98425acb-1b14-46d5-82b4-22ad14183ec6.png">
<img width="233" alt="2022-03-23 21_39_57-meme - Discord" src="https://user-images.githubusercontent.com/32113157/159845646-c6f0821e-46a8-4a6b-b98e-41e8035cdfb8.png">
<img width="229" alt="2022-03-23 21_40_30-meme - Discord" src="https://user-images.githubusercontent.com/32113157/159845648-161ccb55-1896-4029-aefa-059c5649bc65.png">
<img width="224" alt="2022-03-23 21_40_48-meme - Discord" src="https://user-images.githubusercontent.com/32113157/159845650-069bb2d7-239b-4016-be28-2f285b045870.png">
<img width="225" alt="2022-03-23 21_40_56-meme - Discord" src="https://user-images.githubusercontent.com/32113157/159845651-51a0e1cf-56a2-402d-946a-a84b001dbe21.png">
<img width="225" alt="2022-03-23 21_41_49-meme - Discord" src="https://user-images.githubusercontent.com/32113157/159845653-8c17257b-480d-4746-ab12-1bac261d2a06.png">
</details>

2022-03-24 22:09 UTC, EncryptedDev requested changes, later dismissed

2022-03-24 22:09 UTC, EncryptedDev commented on websites/E/Explain xkcd/presence.ts
> +	startTimestamp = Math.floor(Date.now() / 1000);
```suggestion
	browsingTimestamp = Math.floor(Date.now() / 1000);
```

2022-03-24 22:09 UTC, EncryptedDev commented on websites/E/Explain xkcd/presence.ts
> +			document.querySelector("#searchText > input") as HTMLInputElement
Use type generic

2022-03-25 14:55 UTC, Slowlife01 approved these changes

2022-03-25 18:45 UTC, Bas950 approved these changes

2022-03-25 18:51 UTC, merged