fix(SteamDB): fix broken pages
PreMiD/Presences pull request #5970
Opened 2022-03-24 14:37 UTC by joerkig

**Describe the changes in this pull request:**

<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

![NVIDIA_Share_xtuHzZ8vwi](https://user-images.githubusercontent.com/44418429/159940298-005ef2cb-3bf1-41db-b613-3181dd29a8a9.png)

</details>

2022-03-24 22:04 UTC, EncryptedDev requested changes
Hello, thank you for opening a pull request. 

Please use Type Generic instead of using the `as` keyword to assign types - we prefer type generic

2022-03-24 22:04 UTC, EncryptedDev commented on websites/S/SteamDB/presence.ts
> +								) as HTMLInputElement
```suggestion
								document.querySelector<HTMLInputElement>(
									"input[type='search'][class='']"
								)
```

2022-03-31 16:57 UTC, EncryptedDev commented
Hello @joerkig. Please resolve conflicts!

2022-03-31 20:35 UTC, EncryptedDev approved these changes

2022-04-01 09:11 UTC, Slowlife01 approved these changes

2022-04-01 09:11 UTC, merged