fix(XKCD): Fix issues with title text
PreMiD/Presences pull request #5978
Opened 2022-03-26 16:51 UTC by theusaf

**Describe the changes in this pull request:**
Fixes an issue preventing the presence from appearing when the title text is too long.

<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

<img width="216" alt="2022-03-26 09_51_08 - Discord" src="https://user-images.githubusercontent.com/32113157/160249464-1091d6e1-0215-4b8c-b395-f4f087865e9b.png">
</details>

2022-03-26 23:35 UTC, EncryptedDev requested changes

2022-03-26 23:35 UTC, EncryptedDev commented on websites/X/XKCD/presence.ts
> +				label: "View comic"
EITHER
```suggestion
				label: "View Comic"
```
OR
```suggestion
				label: "Read Comic"
```

2022-03-27 03:50 UTC, Slowlife01 approved these changes

2022-03-27 09:36 UTC, EncryptedDev approved these changes

2022-03-27 09:36 UTC, merged