feat(Apple): more Mail Details, iCloud Services Icons
PreMiD/Presences pull request #6001
Opened 2022-03-29 17:21 UTC by N0chteil

<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

![Screenshot_124](https://user-images.githubusercontent.com/53608074/160669249-2307c6da-ddd5-4434-a772-484a6fc3113d.png)
![Screenshot_125](https://user-images.githubusercontent.com/53608074/160669253-a314eda1-bb7a-4c44-bdc5-9c11aaf4f8de.png)
![Screenshot_127](https://user-images.githubusercontent.com/53608074/160669255-558b0854-82ce-4724-81ee-d5cb41d0bcc3.png)
![Screenshot_128](https://user-images.githubusercontent.com/53608074/160669257-83d9919a-e92f-40be-a2ff-19b6381a7041.png)
![Screenshot_129](https://user-images.githubusercontent.com/53608074/160669259-e83b640f-ad1f-4c6c-a704-151f82313132.png)
![Screenshot_130](https://user-images.githubusercontent.com/53608074/160669260-12104e5a-2f32-48fd-8718-18b876655886.png)
</details>

2022-03-29 17:29 UTC, N0chteil commented
💀
![image](https://user-images.githubusercontent.com/53608074/160670694-0e43cb57-4e36-4104-9e07-3a747617151c.png)

2022-03-29 21:27 UTC, EncryptedDev commented
> 💀 ![image](https://user-images.githubusercontent.com/53608074/160670694-0e43cb57-4e36-4104-9e07-3a747617151c.png)

This was down to an API issue which should have been resolved now. Please resolve conflicts and rebase your branch!

2022-03-30 01:28 UTC, Slowlife01 requested changes, later dismissed

2022-03-30 01:28 UTC, Slowlife01 commented on websites/A/Apple/dist/metadata.json
> +			"icon": "fad fa-user-secret",
These should be off by default

2022-03-31 17:06 UTC, Bas950 approved these changes

2022-03-31 20:31 UTC, EncryptedDev approved these changes

2022-04-01 02:44 UTC, merged