fix(Cuevana3): Domain fix
PreMiD/Presences pull request #6005
Opened 2022-03-31 03:29 UTC by magumboi

**Describe the changes in this pull request:**
Website changed its domain, so this the fix.

<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>
![Screenshot_4](https://user-images.githubusercontent.com/27692047/160970676-df45a42c-d53c-4cda-bcf8-dbf452207a64.png)
</details>

2022-03-31 17:00 UTC, EncryptedDev requested changes
Changing the domain could break something, hence why major should be bumped

2022-03-31 17:00 UTC, EncryptedDev commented on websites/C/Cuevana 3/dist/metadata.json
> +	"version": "1.2.0",
```suggestion
	"version": "2.0.0",
```

2022-04-01 11:07 UTC, EncryptedDev approved these changes
LGTM

2022-04-01 15:02 UTC, Slowlife01 approved these changes

2022-04-01 15:02 UTC, merged