feat(Wolvesville): more statuses, improvements
PreMiD/Presences pull request #6079
Opened 2022-04-13 16:22 UTC by down-bad

Fixed bugs from new game updates and from having the game in light mode (gotta love react native web), improved and added statues, some refactoring.

2022-04-13 16:33 UTC, EncryptedDev requested changes

2022-04-13 16:33 UTC, EncryptedDev commented on websites/W/Wolvesville/dist/metadata.json
> +        "White",
Unformatted or broken diff?

2022-04-13 16:38 UTC, down-bad commented on websites/W/Wolvesville/dist/metadata.json
> +        "White",
it had spaces instead of tabs, fixed

2022-04-14 22:42 UTC, down-bad commented
Unfortunately no matter the ~2 weeks of testing, I'll have to fix something tomorrow cuz React is full of surprises, in case u were planning on merging. ty 👍

2022-04-16 02:07 UTC, down-bad commented
all done

2022-04-18 00:50 UTC, EncryptedDev approved these changes

2022-04-19 08:24 UTC, Slowlife01 approved these changes

2022-04-19 08:25 UTC, merged