filman.cc richpresence
PreMiD/Presences pull request #6104
Opened 2022-04-20 20:21 UTC by xKubsoneQ

**Describe the changes in this pull request:**
added `filman.cc` richpresence

<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>
https://i.imgur.com/xs9lDYM.png
https://i.imgur.com/9lJhKm6.png
https://i.imgur.com/hYfdIFS.png
https://i.imgur.com/8FKDZ73.png
and more!
</details>

2022-04-21 11:27 UTC, Slowlife01 requested changes
Revert the changes to yarn.lock file

2022-04-21 12:19 UTC, xKubsoneQ commented
updated

2022-04-21 14:15 UTC, Slowlife01 requested changes

2022-04-21 14:15 UTC, Slowlife01 commented on websites/F/filman.cc/presence.ts
> +}
```suggestion
}),
browsingTimestamp = Math.floor(Date.now() / 1000);
```

2022-04-21 14:22 UTC, Slowlife01 commented on websites/F/filman.cc/presence.ts
> +}
You have to edit the line 8th too

2022-04-21 22:11 UTC, EncryptedDev commented
Revert the changes to `yarn.lock`

2022-04-22 16:59 UTC, xKubsoneQ commented
but how i can do it? only commit it to my repo with copied yarn.lock file from this repo?

2022-04-22 17:36 UTC, xKubsoneQ commented
nvm, edited

2022-04-23 07:29 UTC, Slowlife01 approved these changes

2022-04-23 10:11 UTC, EncryptedDev approved these changes

2022-04-23 10:12 UTC, merged

2022-04-23 10:12 UTC, EncryptedDev commented
Thank you for your PR! 🎉