Added Waze Map Editor features
PreMiD/Presences pull request #6106
Opened 2022-04-21 18:16 UTC by Lulucmy

Hi,

**Describe the changes in this pull request:**

- Added Waze Map Editor informations (where the user edits, the road name, location...).

<details>
<summary> Proof showing the creation/modification is working as expected </summary>
![image](https://user-images.githubusercontent.com/20552095/164526726-e56086ec-83af-43d9-bf5e-04e8a3171f28.png)
![image](https://user-images.githubusercontent.com/20552095/164526784-2db58faf-4054-47c4-a6be-435d3ef7caf4.png)

<br>

</details>

2022-04-21 22:12 UTC, EncryptedDev requested changes
Use previous format

2022-04-22 14:01 UTC, Lulucmy commented
Hi,
It shoul be good now

2022-04-23 07:32 UTC, Slowlife01 requested changes

2022-04-23 07:32 UTC, Slowlife01 commented on websites/W/Waze/presence.ts
> +let path: string, start: string, end: string, mapelem: string, maploc: string;
Use camelCase.

2022-04-23 07:32 UTC, Slowlife01 commented on websites/W/Waze/dist/metadata.json
> +	"version": "1.1.3",
```suggestion
	"version": "1.2.0",
```

2022-04-23 11:06 UTC, Lulucmy commented on websites/W/Waze/presence.ts
> +let path: string, start: string, end: string, mapelem: string, maploc: string;
Done

2022-04-27 04:08 UTC, Slowlife01 approved these changes
Assuming you tested the recent change

2022-04-27 07:17 UTC, EncryptedDev approved these changes

2022-04-27 07:17 UTC, merged