feat(Free Web Novel): New presence
PreMiD/Presences pull request #6125
Opened 2022-04-25 05:06 UTC by BigBoi-TM

**Describe the changes in this pull request:**
#
# (Feature) New presence for Free Web Novel.
Resolves #6035  
Features:
- Detects pages from the novel list along with pages for different genres
- Detects a when a novel is being viewed and/or read
    -  Displays the novel being viewed and the chapter when being read
- Includes multiple settings to go incognito, and to disable/enable certain things to display
#
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

<details>
<summary>Screenshots</summary>

### - Homepage
![image](https://user-images.githubusercontent.com/96930330/165002447-bb933208-5650-4e4c-a4a2-a39e16fd7e9b.png)

### - Author Page
![image](https://user-images.githubusercontent.com/96930330/165005274-83c5e3fa-9f96-4e94-9eb7-65e51d7756c1.png)

### - Page Detection
![image](https://user-images.githubusercontent.com/96930330/165005325-bd0f20b5-8c06-4141-8400-054066d59f91.png)

### - Reading a Novel
![image](https://user-images.githubusercontent.com/96930330/165005368-5b537683-117a-4015-bc53-98a5d1fcdc6c.png)

### - Reading Detection
![image](https://user-images.githubusercontent.com/96930330/165005685-9f8c6702-bbeb-4a45-82eb-dc705c74897a.png)
![image](https://user-images.githubusercontent.com/96930330/165005725-b21e21d5-032d-49af-a798-0d48719e10f2.png)

### - Settings
![image](https://user-images.githubusercontent.com/96930330/165005559-453b5f59-94c2-4c20-9d6f-a2b37bb87b71.png)

</details>

2022-04-25 05:29 UTC, Slowlife01 commented on websites/F/Free Web Novel/presence.ts
> +	} else presenceData.buttons = null;
No buttons on homepage
```suggestion
```

2022-04-25 05:29 UTC, Slowlife01 commented on websites/F/Free Web Novel/presence.ts
> +			presenceData.state = null;
```suggestion
```
Unnecessary

2022-04-25 05:29 UTC, Slowlife01 commented on websites/F/Free Web Novel/presence.ts
> +			}
Just add showReading into the if statement

2022-04-25 05:29 UTC, Slowlife01 commented on websites/F/Free Web Novel/presence.ts
> +			presenceData.state = null;
```suggestion
			presenceData.largeImageKey = "fwn_1024";
			delete presenceData.smallImageKey;
```

2022-04-26 03:20 UTC, BigBoi-TM commented
Note: May or may not contain nsfw. Dunno, bunch of suggestive stuff on there

2022-04-26 17:14 UTC, EncryptedDev requested changes

2022-04-26 17:14 UTC, EncryptedDev commented on websites/F/Free Web Novel/dist/metadata.json
> +	],
Mix of tabs an sapces, format the file properly using CLI

2022-04-29 15:53 UTC, EncryptedDev commented
Resolve Slowlife's requested changes once handled please

2022-04-29 15:55 UTC, BigBoi-TM commented
> Resolve Slowlife's requested changes once handled please

I got no reply on two requests, do I still have to change them?

2022-04-30 15:22 UTC, BigBoi-TM commented
@EncryptedDev I miss anything?

2022-05-01 13:30 UTC, Slowlife01 commented on websites/F/Free Web Novel/presence.ts
> +			}
```ts
			if (document.querySelector('[title="Read Next chapter"]') && showReading) {
				presenceData.details = "Reading...";
				presenceData.smallImageKey = "opem";
			}
```

2022-05-01 13:52 UTC, BigBoi-TM commented
Copied an old version, tryna fix it

2022-05-01 19:01 UTC, EncryptedDev requested changes
Quality code, just way too much detail for a presence really

2022-05-01 19:01 UTC, EncryptedDev commented on websites/F/Free Web Novel/presence.ts
> +			presenceData.state = "Page: Contact";
This is a given as the details above says the same thing

2022-05-02 10:48 UTC, EncryptedDev requested changes

2022-05-02 10:48 UTC, EncryptedDev commented on websites/F/Free Web Novel/presence.ts
> +	if (showTimestamp) presenceData.startTimestamp = browsingTimestamp;
If you are using a ternary in the presenceData object for the other values, you might as well include this too

2022-05-02 10:48 UTC, EncryptedDev commented on websites/F/Free Web Novel/presence.ts
> +			presenceData.state = `Genre: ${genre}`;
This is repeated?

2022-05-02 10:48 UTC, EncryptedDev commented on websites/F/Free Web Novel/presence.ts
> +			presenceData.details = "Veiwing the contact page";
Unresolved

2022-05-02 10:48 UTC, EncryptedDev commented on websites/F/Free Web Novel/presence.ts
> +			presenceData.details = "Looking through the privacy & terms of use";
Very long

2022-05-02 18:16 UTC, ImRodry requested changes

2022-05-02 18:16 UTC, ImRodry commented on websites/F/Free Web Novel/dist/metadata.json
> +		"name": "BigBoi©",
you're not copyrighted
```suggestion
		"name": "BigBoi",
```

2022-05-02 18:16 UTC, ImRodry commented on websites/F/Free Web Novel/dist/metadata.json
> +
please remove the extra empty lines in these settings

2022-05-02 18:16 UTC, ImRodry commented on websites/F/Free Web Novel/dist/metadata.json
> +				"showReading": true
were all of these tested to their full extent?

2022-05-02 18:16 UTC, ImRodry commented on websites/F/Free Web Novel/presence.ts
> +	browsingTimestamp = Math.floor(Date.now());
what
```suggestion
	browsingTimestamp = Math.round(Date.now() / 1000);
```

2022-05-02 18:16 UTC, ImRodry commented on websites/F/Free Web Novel/presence.ts
> +			delete presenceData.buttons;
this needs to be ran at the end of the file I believe

2022-05-07 11:32 UTC, ImRodry commented
@BigBoi-TM please don't resolve conversations without addressing them in some way

2022-05-07 22:03 UTC, BigBoi-TM commented
> @BigBoi-TM please don't resolve conversations without addressing them in some way

Im waiting on a reply for two comments.

2022-05-08 11:19 UTC, ImRodry commented
@BigBoi-TM I don't see any questions you asked, only some unresolved reviews

2022-05-08 15:31 UTC, BigBoi-TM commented
@ImRodry 
![image](https://user-images.githubusercontent.com/96930330/167303396-2f4ea471-4b4a-4ba4-b3ee-22e73db055a4.png)

2022-05-09 17:31 UTC, ImRodry commented
It says pending. I can't see your comments if they're pending because you didn't send them...

2022-05-11 21:49 UTC, ImRodry commented
Hey! Thank you for making this PR. Unfortunately, I will be closing this after multiple unsuccessful attempts at getting reviews addressed by you and a lack of communication in the last few days. Should you wish to continue working on this, please address the reviews and notify a member of the reviewer team.

2022-05-11 21:49 UTC, closed without merging

2022-05-11 22:30 UTC, BigBoi-TM commented
Bruh I've been sending comments left and right none of them want to go through 😭