fix(Instagram): unknown username
PreMiD/Presences pull request #6170
Opened 2022-05-04 08:27 UTC by DarkVillager

**Describe the changes in this pull request:**
Fixed unknown username being displayed.
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

<img src="https://user-images.githubusercontent.com/42322979/166646505-d001c115-f3c7-41e5-8766-08988e6935c2.jpg">
<img src="https://user-images.githubusercontent.com/42322979/166646517-168cb9da-f1ad-48e3-a270-cf7af08ca76f.jpg">

</details>

2022-05-06 21:06 UTC, EncryptedDev submitted a review, later dismissed

2022-05-07 12:16 UTC, ImRodry requested changes

2022-05-07 12:16 UTC, ImRodry commented on websites/I/Instagram/presence.ts
> +			document.querySelector("head > title")?.textContent.split("(")[0] ??
this will have a trailing space
```suggestion
			document.querySelector("head > title")?.textContent.split("(")[0].trim() ??
```

2022-05-07 16:35 UTC, ImRodry submitted a review, later dismissed

2022-05-11 22:11 UTC, ImRodry approved these changes

2022-05-11 22:16 UTC, EncryptedDev approved these changes

2022-05-11 22:16 UTC, merged