feat(Bilibilitv): support web multiLanguage & more
PreMiD/Presences pull request #6179
Opened 2022-05-07 14:22 UTC by Faelayis

**Describe the changes in this pull request:**

- Add cover ,multiLanguage
- Support all language in web (Previously english support only)

Add rich presence assets I need to change new clientId
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

![image](https://user-images.githubusercontent.com/48393914/167257560-66cbcf64-0fdc-44fd-b0e9-d344e62a5b1a.png)
![image](https://user-images.githubusercontent.com/48393914/167257896-6a40879e-21f7-40e7-88f3-d3fe91798e63.png)
![image](https://user-images.githubusercontent.com/48393914/167257769-fa845607-e7c1-4fd9-9e11-25c64116ec59.png)
![image](https://user-images.githubusercontent.com/48393914/167257967-dc6087ff-f032-47cf-a593-43dabe94b21a.png)
![image](https://user-images.githubusercontent.com/48393914/167257913-36dc1fb2-cc10-421b-98bb-ed45758bc984.png)
![image](https://user-images.githubusercontent.com/48393914/167257826-c4eb493f-bef1-4ee8-a1fa-3345d566d0bc.png)

</details>

2022-05-07 15:05 UTC, ImRodry requested changes

2022-05-07 15:05 UTC, ImRodry commented on websites/B/bilibilitv/presence.ts
> +		switch (document.location.pathname.toString().toLowerCase().split("/")[2]) {
you're stringifying a string?
```suggestion
		switch (document.location.pathname.toLowerCase().split("/")[2]) {
```

2022-05-07 15:05 UTC, ImRodry commented on websites/B/bilibilitv/presence.ts
> +				presenceData.startTimestamp = browsingStamp;
this has already been set, no need to set it twice

2022-05-07 15:05 UTC, ImRodry commented on websites/B/bilibilitv/presence.ts
> +				presenceData.state = `${ep}`;
no need to stringify strings
```suggestion
				presenceData.state = ep;
```

2022-05-07 15:05 UTC, ImRodry commented on websites/B/bilibilitv/presence.ts
> +				presenceData.smallImageKey = playing ? "pause" : "play";
if playing is true the key is pause? Sure?

2022-05-07 15:05 UTC, ImRodry commented on websites/B/bilibilitv/presence.ts
> +		if (document.location.pathname.toString().toLowerCase().split("/")[1]) {
```suggestion
		if (document.location.pathname.toLowerCase().split("/")[1]) {
```

2022-05-07 15:05 UTC, ImRodry commented on websites/B/bilibilitv/presence.ts
> +				document.querySelector(".is-active")?.textContent ?? "?";
you're setting the details to "?" if that query selector is null?

2022-05-07 20:56 UTC, ImRodry commented on websites/B/bilibilitv/presence.ts
> +				presenceData.smallImageKey = playing ? "pause" : "play";
Don't resolve conversations without addressing them in some form.

2022-05-07 21:49 UTC, Faelayis commented on websites/B/bilibilitv/presence.ts
> +		{
Lint will not pass

2022-05-07 23:48 UTC, ImRodry requested changes
Seems like I missed two

2022-05-07 23:48 UTC, ImRodry commented on websites/B/bilibilitv/presence.ts
> +				}`;
```suggestion
				presenceData.state =
					document.querySelector(".space-info__name")?.textContent ??
					strings.searchSomething;
```

2022-05-07 23:48 UTC, ImRodry commented on websites/B/bilibilitv/presence.ts
> +				}`;
```suggestion
				presenceData.details =
					document.querySelector("div.video-info__title-wrap > h1 > a")
						.textContent;
```

2022-05-07 23:55 UTC, ImRodry approved these changes, later dismissed

2022-05-08 00:09 UTC, ImRodry commented
Make sure to fix the CI issue

2022-05-10 10:24 UTC, Slowlife01 commented on websites/B/bilibilitv/presence.ts
> +					.split("@")[0];
```suggestion
					.querySelector<HTMLMetaElement>('meta[name="og:image"]')
					.content.split("@")[0];
```

2022-05-10 10:24 UTC, Slowlife01 commented on websites/B/bilibilitv/presence.ts
> +							.getAttribute("content")
Can't you use just location.href?

2022-05-10 10:24 UTC, Slowlife01 commented on websites/B/bilibilitv/presence.ts
> +					.split("@")[0];
```suggestion
				presenceData.largeImageKey = document
					.querySelector<HTMLMetaElement>('meta[name="og:image"]')
					.content.split("@")[0];
```

2022-05-10 21:33 UTC, ImRodry approved these changes

2022-05-10 22:04 UTC, EncryptedDev approved these changes

2022-05-10 22:04 UTC, merged