feat(Minecraft Menu): add presence
PreMiD/Presences pull request #6192
Opened 2022-05-10 07:16 UTC by DarkVillager

**Describe the changes in this pull request:**
- Added Full Site Support
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

<img src="https://user-images.githubusercontent.com/42322979/167570783-b658564c-9a1e-40c8-a6a4-107d499375d4.jpg">
<img src="https://user-images.githubusercontent.com/42322979/167570794-e4a757a2-5f97-4725-a688-c71e5f7210db.jpg">
<img src="https://user-images.githubusercontent.com/42322979/167570796-f2179be9-a8e9-475a-9cc7-f5435293dc87.jpg">
<img src="https://user-images.githubusercontent.com/42322979/167570798-1c39cae8-3812-4e26-8750-d4afaa95880d.jpg">
<img src="https://user-images.githubusercontent.com/42322979/167570799-2562e942-d2ac-46ea-a476-eaf73febd5fc.jpg">
<img src="https://user-images.githubusercontent.com/42322979/167570800-f201a2ba-f981-4a1e-a0dd-5c36de9da10d.jpg">
<img src="https://user-images.githubusercontent.com/42322979/167570802-fed9ea2f-db90-4d72-ab32-66eeac0cd7e2.jpg">
<img src="https://user-images.githubusercontent.com/42322979/167570806-146d455d-70ea-4308-ba6d-b5db6d64ba3e.jpg">
<img src="https://user-images.githubusercontent.com/42322979/167570809-eea64e82-38a4-45b8-8bef-1816d7e3d5f0.jpg">
<img src="https://user-images.githubusercontent.com/42322979/167570811-740278d5-89e6-46d7-aaf2-2f4263038779.jpg">
<img src="https://user-images.githubusercontent.com/42322979/167570813-10865437-d960-43e5-a6e4-1f380384dd3c.jpg">
<img src="https://user-images.githubusercontent.com/42322979/167570814-ad729723-08e4-4c70-9f40-9efbc782f0ca.jpg">
<img src="https://user-images.githubusercontent.com/42322979/167570816-ca96d54b-5245-4b33-8a56-28ef1bfe75b9.jpg">

</details>

2022-05-10 09:43 UTC, Slowlife01 commented
The domain must be at least 2 months old.

2022-05-10 11:26 UTC, DarkVillager commented
> The domain must be at least 2 months old.

Lemme see what the owner of the site has to say, I think ur right tho.

2022-07-13 09:44 UTC, DarkVillager commented
@EncryptedDev @Bas950 could u reopen this please?

2022-07-14 01:05 UTC, EncryptedDev requested changes
Hiya - please update the button changes for all buttons

2022-07-14 01:05 UTC, EncryptedDev commented on websites/M/Minecraft Menu/dist/metadata.json
> +		"nl": "Minecraft Menu is een plek om de Beste Minecraft Server te vinden in 2022 voor Minecraft.",
@Bas950

2022-07-14 01:05 UTC, EncryptedDev commented on websites/M/Minecraft Menu/dist/metadata.json
> +	"logo": "https://i.imgur.com/BlAb5Pg.png",
This scales poorly on the website, resize the image to be as close to 512x512 without messing up the quality

2022-07-14 01:05 UTC, EncryptedDev commented on websites/M/Minecraft Menu/presence.ts
> +				label: "View server",
Use [Title Case](https://titlecaseconverter.com/rules/#NYT)
```suggestion
				label: "View Server",
```

2022-07-14 01:05 UTC, EncryptedDev commented on websites/M/Minecraft Menu/presence.ts
> +				url: document.location.href,
```suggestion
				url: href,
```

2022-07-15 10:53 UTC, EncryptedDev reviewed
Two final things from me

2022-07-15 10:53 UTC, EncryptedDev commented on websites/M/Minecraft Menu/dist/metadata.json
> +		"nl": "Minecraft Menu is in 2022 een plek om de Beste Minecraft Servers te vinden.",
@Bas950

2022-07-15 10:53 UTC, EncryptedDev commented on websites/M/Minecraft Menu/presence.ts
> +	if (privacy) presenceData.details = "Browsing...";
```suggestion
	if (privacy) presenceData.details = "Browsing";
```

2022-07-15 10:53 UTC, EncryptedDev commented on websites/M/Minecraft Menu/presence.ts
> +		presenceData.details = "Searching for:";
```suggestion
		presenceData.details = "Searching for";
```

2022-07-15 12:56 UTC, Bas950 requested changes

2022-07-15 12:56 UTC, Bas950 commented on websites/M/Minecraft Menu/dist/metadata.json
> +		"nl": "Minecraft Menu is in 2022 een plek om de Beste Minecraft Servers te vinden.",
```suggestion
		"nl": "Minecraft Menu is de beste plek in 2022 om Minecraft-servers te vinden.",
```

2022-07-19 16:32 UTC, EncryptedDev approved these changes

2022-07-20 14:06 UTC, Bas950 approved these changes

2022-07-20 14:06 UTC, merged