change website domain
PreMiD/Presences pull request #6201
Opened 2022-05-12 00:34 UTC by yeetbruhoo

it changed again 💀

2022-05-12 05:09 UTC, Slowlife01 requested changes
Might want to use RegExp at some point

2022-05-12 05:09 UTC, Slowlife01 commented on websites/N/Nettruyen/dist/metadata.json
> +		"nettruyenco.com"
This redirect to `www.nettruyenco.com`? If so there's no need to include this

2022-05-17 17:01 UTC, ImRodry commented
Please address the review in the coming days or this PR will be closed

2022-05-20 23:16 UTC, EncryptedDev commented
Closing due to inactivity

2022-05-20 23:16 UTC, closed without merging