feat(e621): added small image key
PreMiD/Presences pull request #6211
Opened 2022-05-13 10:16 UTC by DarkVillager

**Describe the changes in this pull request:**
- Made small improvements to e621
- Added small image keys

<details>
<summary> Proof showing the creation/modification is working as expected  E621:</summary>
<br>

<img src="https://user-images.githubusercontent.com/42322979/167627055-ce057bec-e1f9-435b-8347-cc6a7cbfa564.jpg">
<img src="https://user-images.githubusercontent.com/42322979/167627058-a8fb2c5b-4338-4d01-a334-b5bcbf3f8e96.jpg">
<img src="https://user-images.githubusercontent.com/42322979/167627061-846f4555-017c-43e3-b4b9-c0f56aafb7e9.jpg">
<img src="https://user-images.githubusercontent.com/42322979/167627062-8e44ccd9-aff1-4747-a7f0-f40214264e3b.jpg">

</details>

2022-05-13 17:11 UTC, ImRodry requested changes

2022-05-13 17:11 UTC, ImRodry commented on websites/E/e621/presence.ts
> +			if (!search.value) {
That's not what the old if was checking
```suggestion
			if (search.value) {
```

2022-05-13 17:11 UTC, ImRodry commented on websites/E/e621/presence.ts
> +				.replace(" ", "_");
you're replacing every space with a _ just to split with a string with spaces later, didn't you mean to do it the other way around?

2022-05-13 17:11 UTC, ImRodry commented on websites/E/e621/presence.ts
> +					label: `View Comment Page ${title.textContent}`,
buttons should not include dynamic data
```suggestion
					label: "View Comment Page",
```

2022-05-14 14:02 UTC, ImRodry approved these changes

2022-05-14 17:13 UTC, Slowlife01 approved these changes

2022-05-14 17:13 UTC, merged