fix(Apple TV+): wrong show/movie name, not detecting playback
PreMiD/Presences pull request #6260
Opened 2022-05-22 17:48 UTC by N0chteil

## Description 
* _Screenshot titles_

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] I bumped the version of the presence in accordance with [Semver](https://devhints.io/semver)

## Screenshots
<details>
<summary>Wrong show/movie name</summary>

![Screenshot_144](https://user-images.githubusercontent.com/53608074/169706938-0069d470-3b66-481e-95ce-e7aa9f75c82a.png)
![Screenshot_145](https://user-images.githubusercontent.com/53608074/169706940-9e310d01-80dd-4d84-87b9-64f86390a3bf.png)
</details>

<details>
<summary>Not detecting playback</summary>

Before:
![image](https://user-images.githubusercontent.com/53608074/169707871-1e6bf26b-743d-479b-b6b7-0bbf5bb19782.png)

After:
![Screenshot_146](https://user-images.githubusercontent.com/53608074/169707840-f1bd1abd-396d-4ba0-ab92-6f434c09aba3.png)
</details>

2022-05-27 22:04 UTC, EncryptedDev requested changes

2022-05-27 22:04 UTC, EncryptedDev commented on websites/A/Apple TV+/presence.ts
> +					presenceData.details = "Viewing Show:";
Show should be lowercase

2022-05-27 22:04 UTC, EncryptedDev commented on websites/A/Apple TV+/presence.ts
> +					presenceData.details = "Viewing Movie:";
Here

2022-05-27 22:04 UTC, EncryptedDev commented on websites/A/Apple TV+/presence.ts
> +				presenceData.details = "Viewing Person:";
Ditto

2022-05-27 22:04 UTC, EncryptedDev commented on websites/A/Apple TV+/presence.ts
> +				presenceData.details = "Viewing their Settings";
And here

2022-05-28 18:01 UTC, ImRodry requested changes

2022-05-28 18:01 UTC, ImRodry commented on websites/A/Apple TV+/presence.ts
> +		if (document.location.pathname.match(pathname)) {
```suggestion
		if (new RegExp(pathname).test(document.location.pathname)) {
```

2022-05-28 23:31 UTC, ImRodry requested changes
This presence is so weird it needs an entire overhaul but LGTM

2022-05-28 23:31 UTC, ImRodry approved these changes
Wrong button

2022-05-29 10:22 UTC, EncryptedDev approved these changes

2022-05-29 10:22 UTC, merged

2022-05-29 10:23 UTC, EncryptedDev commented
Thank you for your contribution! 🎉 @N0chteil