feat(Animeler.net): New presence
PreMiD/Presences pull request #6261
Opened 2022-05-22 20:08 UTC by Chasology

## Description 
Animeler.net is a turkish anime news website.

* Detects homepage.
* Detects article headline.
* Detects user profile.
* Detects article tags.

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
![Proof 1](https://i.imgur.com/I2kCfuZ.png)
![Proof 2](https://i.imgur.com/FpxCpjH.png)
</details>

2022-05-22 20:11 UTC, EncryptedDev requested changes
Please run `yarn format` and resolve SV CI

2022-05-22 20:37 UTC, EncryptedDev requested changes

2022-05-22 20:37 UTC, EncryptedDev commented on websites/A/Animeler.net/dist/metadata.json
> +		"tr": "Animeler.net, anime haberlerini size en hızlı şekilde sunan sitedir. Türk Anime TV iştirakidir.",
This is the official description in Turkish

```suggestion
		"tr": "En iyi, en güncel, en çok konuşulan içerikler ve farklı kaynaklardan tamamen tarafsız içerikleri okuyun. Türk Anime TV iştirakidir.",
```

2022-05-22 20:39 UTC, EncryptedDev requested changes
Sorry, this was suppose to be bundled with the other review

2022-05-22 20:39 UTC, EncryptedDev commented on websites/A/Animeler.net/dist/metadata.json
> +	"logo": "https://i.imgur.com/9JPsUmz.png",
Not 512 x 512

2022-05-22 20:47 UTC, Chasology commented on websites/A/Animeler.net/dist/metadata.json
> +	"logo": "https://i.imgur.com/9JPsUmz.png",
fixed

2022-05-29 00:00 UTC, EncryptedDev requested changes

2022-05-29 00:00 UTC, EncryptedDev commented on websites/A/Animeler.net/presence.ts
> +				url: document.location.href.toString()
```suggestion
				url: document.location.href
```

2022-05-29 00:00 UTC, EncryptedDev commented on websites/A/Animeler.net/presence.ts
> +			} as ButtonData
```suggestion
			}
```

2022-05-29 10:28 UTC, eggsy requested changes
Everything @EncryptedDev mentioned.

2022-05-29 10:35 UTC, eggsy approved these changes

2022-06-02 20:47 UTC, EncryptedDev commented
This pull request will be closed in the next few days if the my review isn't addressed fully

2022-06-05 21:01 UTC, EncryptedDev commented
Inactive

2022-06-05 21:01 UTC, closed without merging