feat(Geotastic): new presence
PreMiD/Presences pull request #6265
Opened 2022-05-24 19:10 UTC by AzNate

## Description 
A new presence for the geography location guessing game, Geotastic. Detects all pages and displays info for all game modes.

## Acknowledgements
✓ I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
✓ I linted the code by running `yarn format`

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
![image](https://user-images.githubusercontent.com/47200527/170112606-aad1b45a-c115-4c08-80e2-71e8a5786101.png)
![image](https://user-images.githubusercontent.com/47200527/170112718-91eba2cf-20c1-4d21-9cdf-d9860fe76293.png)
</details>

2022-05-29 00:06 UTC, EncryptedDev requested changes

2022-05-29 00:06 UTC, EncryptedDev commented on websites/G/Geotastic/presence.ts
> +											// No default
```suggestion
```

2022-05-29 00:06 UTC, EncryptedDev commented
Awaiting @Kozou4ever approval

2022-05-29 00:22 UTC, Kozou4ever requested changes

2022-05-29 00:22 UTC, Kozou4ever commented on websites/G/Geotastic/dist/metadata.json
> +		"fr": "Geotastic est un jeu de devinette de emplacement géographique créé par Eduard But de Edutastic Games."
This translation would be the most appropriate in my opinion 
```suggestion
		"fr": "Geotastic est un jeu de devinette de localisation géographique créé par Eduard But de Edutastic Games."
```

2022-06-05 21:29 UTC, ImRodry requested changes

2022-06-05 21:29 UTC, ImRodry commented on websites/G/Geotastic/presence.ts
> +		switch (document.location.pathname) {
why can't this start at the top?

2022-06-05 21:29 UTC, ImRodry commented on websites/G/Geotastic/presence.ts
> +					switch (document.location.pathname) {
a switch inside a switch for the same thing? Come on

2022-06-05 21:29 UTC, ImRodry commented on websites/G/Geotastic/presence.ts
> +								switch (document.location.pathname) {
again... let's not do this please

2022-06-05 21:29 UTC, ImRodry commented on websites/G/Geotastic/presence.ts
> +										break;
why did this one decide to be the quirky young sibling

2022-06-08 13:30 UTC, EncryptedDev requested changes

2022-06-08 13:30 UTC, EncryptedDev commented on websites/G/Geotastic/presence.ts
> +		}
Please use a Record for this instead as shown below. Much shorter and more maintainable 
https://github.com/PreMiD/Presences/blob/113adabd2296ec1be22122ccc3ec2deff1c399ed/websites/T/TruckersMP/presence.ts#L15-L41

2022-06-20 22:03 UTC, EncryptedDev approved these changes

2022-06-20 22:11 UTC, Kozou4ever approved these changes

2022-06-20 22:23 UTC, ImRodry approved these changes

2022-06-20 22:24 UTC, merged