feat(OpenStreetMap): new presence
PreMiD/Presences pull request #6305
Opened 2022-06-07 07:46 UTC by Lulucmy

## Description 
Adding the presence of OpenStreetMap, a collaborative mapping project.
Huge thanks to @DarkVillager and @kyrie25 for their help!

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![Uploading DiscordPTB_Z7BKMNqMGO.png…](https://i.imgur.com/oBoUVk3.png)
![Uploading DiscordPTB_wTUj4lSDOU.png…](https://i.imgur.com/f6mRzwL.png)
![Uploading DiscordPTB_wTUj4lSDOU.png…](https://i.imgur.com/l53ORGY.png)

</details>

2022-06-07 17:42 UTC, EncryptedDev commented on websites/O/OpenStreetMap/dist/metadata.json
> +		"fr": "OpenStreetMap est un projet de cartographie collaboratif en ligne où chaque utilisateur peut contribuer à la carte."
@Kozou4ever

2022-06-08 13:57 UTC, EncryptedDev requested changes

2022-06-08 13:57 UTC, EncryptedDev commented on websites/O/OpenStreetMap/presence.ts
> +				if (!locationcity) locationcity = res.address.town;
Use [nullish coalescing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator)

2022-06-08 13:57 UTC, EncryptedDev commented on websites/O/OpenStreetMap/presence.ts
> +		presenceData.state = document.title.split(" -")[0];
Use the Record method here as shown below instead
https://github.com/PreMiD/Presences/blob/113adabd2296ec1be22122ccc3ec2deff1c399ed/websites/T/TruckersMP/presence.ts#L15-L41

2022-06-08 14:01 UTC, EncryptedDev requested changes
This presence is quite privacy invasive. I would add a privacy setting and implement this through the code too. Maybe display country only and buttons with the privacy setting true

2022-06-11 16:39 UTC, Kozou4ever approved these changes

2022-06-12 00:45 UTC, ImRodry requested changes

2022-06-12 00:45 UTC, ImRodry commented on websites/O/OpenStreetMap/dist/metadata.json
> +	"thumbnail": "https://i.imgur.com/uXANhtt.png",
why paris? Couldn't you put a picture of the entire world

2022-06-12 00:45 UTC, ImRodry commented on websites/O/OpenStreetMap/presence.ts
> +				locationcountry = res.address.country;
use object destructuring

2022-06-12 00:45 UTC, ImRodry commented on websites/O/OpenStreetMap/presence.ts
> +			.then(res => {
you can keep the .then above this line but for this callback please use async/await instead

2022-06-12 00:45 UTC, ImRodry commented on websites/O/OpenStreetMap/presence.ts
> +		details: "Current page:"
you shouldn't do this. Just display each page's data in the details, maybe change the strings a little to say "Viewing" or whatever you'd like but don't do this

2022-06-12 00:45 UTC, ImRodry commented on websites/O/OpenStreetMap/presence.ts
> +		presenceData.state = "Write new diary entry";
```suggestion
		presenceData.state = "Writing a new diary entry";
```

2022-06-12 00:45 UTC, ImRodry commented on websites/O/OpenStreetMap/presence.ts
> +		presenceData.state = "Public GPS tracks";
what's a GPS track?

2022-06-12 00:45 UTC, ImRodry commented on websites/O/OpenStreetMap/presence.ts
> +		presenceData.state = document.title.split(" |")[0];
I know it works the same, but why the space
```suggestion
		presenceData.state = document.title.split("|")[0];
```

2022-06-12 00:45 UTC, ImRodry commented on websites/O/OpenStreetMap/presence.ts
> +		presenceData.state = document.title.split(" /")[0];
```suggestion
		presenceData.state = document.title.split("/")[0];
```

2022-06-12 00:45 UTC, ImRodry commented on websites/O/OpenStreetMap/presence.ts
> +		presenceData.state = document.title.split(" -")[0];
```suggestion
		presenceData.state = document.title.split("-")[0];
```

2022-06-12 00:45 UTC, ImRodry commented on websites/O/OpenStreetMap/presence.ts
> +		presenceData.details = `On ${document.title.split("|")[0]} profile :`;
```suggestion
		presenceData.details = `On ${document.title.split("|")[0]}'s profile:`;
```

2022-06-12 00:45 UTC, ImRodry commented on websites/O/OpenStreetMap/presence.ts
> +		presenceData.state = `"${document.title.split(" —")[0]}"`;
```suggestion
		presenceData.state = `"${document.title.split("—")[0]}"`;
```

2022-06-14 11:54 UTC, ImRodry commented
Rebased to apply the latest changes in the prettier configuration. If you need help with your local branch, please ping me on the #presence-dev channel on Discord.

2022-06-14 17:44 UTC, Lulucmy reviewed
Sorry for the delay, I'm busy IRL but I'll keep working on it

2022-06-17 23:00 UTC, ImRodry commented
Please address the unresolved conversations in a timely manner, otherwise this PR will be closed

2022-06-20 21:58 UTC, EncryptedDev commented
Inactive

2022-07-06 21:46 UTC, EncryptedDev commented
Resolve CI

2022-07-06 22:13 UTC, Lulucmy commented
Should be good now 👍

2022-07-09 00:10 UTC, EncryptedDev requested changes
This is still unresolved https://github.com/PreMiD/Presences/pull/6305/files#r895082509

2022-07-11 14:40 UTC, EncryptedDev approved these changes

2022-07-14 11:37 UTC, Bas950 approved these changes

2022-07-14 11:37 UTC, merged