fix(Apple Music): broken on beta website
PreMiD/Presences pull request #6307
Opened 2022-06-07 22:38 UTC by down-bad

## Description 

Fix songs not showing

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://user-images.githubusercontent.com/19146783/172494284-8cda0dc2-0a5b-4049-8a71-dc638f603462.png"/>
<img src="https://user-images.githubusercontent.com/19146783/172493818-b9118c77-c111-4cbb-af56-6c6ad24e5c74.png"/>
</details>

2022-06-07 22:52 UTC, ImRodry commented
Can we get a before and after?

2022-06-07 22:54 UTC, down-bad commented
![image](https://user-images.githubusercontent.com/19146783/172496327-f3ab8eb6-d59a-4eee-b3da-c75a79f08894.png)
if you're on premid 2.2.3 or lower, otherwise nothing

2022-06-07 22:59 UTC, ImRodry requested changes

2022-06-07 22:59 UTC, ImRodry commented on websites/A/Apple Music/presence.ts
> +				) ||
```suggestion
				) ??
```

2022-06-07 23:07 UTC, ImRodry approved these changes

2022-06-07 23:22 UTC, down-bad commented
Apparently the progress bar doesn't update if the website is in the background, so when the song changes it keeps the timestamp from the previous one. That's awesome...

2022-06-07 23:35 UTC, ImRodry commented
Not much you can do about that then

2022-06-07 23:38 UTC, down-bad commented
We can get the timestamp from the audio element

2022-06-08 13:56 UTC, ImRodry approved these changes

2022-06-08 14:03 UTC, EncryptedDev approved these changes

2022-06-08 14:03 UTC, merged