feat(Cda): presence rewrite
PreMiD/Presences pull request #6326
Opened 2022-06-13 19:35 UTC by xKubsoneQ

## Description 
cda.pl presence rewrite: fixed presence with features (buttons etc.)

## Acknowledgements
- [ ] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ ] I linted the code by running `yarn format`
- [ ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
https://imgur.com/a/9vZ0cDz

</details>

2022-06-13 20:00 UTC, EncryptedDev commented on websites/C/cda.pl/presence.ts
> +		path = document.location.pathname.toLowerCase();
Please keep the variable named `pathname` instead 
```suggestion
		pathname = document.location.pathname.toLowerCase();
```

2022-06-13 20:08 UTC, ImRodry commented
@marzeq

2022-06-13 20:30 UTC, marzeq commented on websites/C/cda.pl/presence.ts
> +		presenceData.details = "Przeglądanie powiązanych kont";
This should be "Przegląda powiązane konta" to be consistent with the other presences.

2022-06-13 20:38 UTC, marzeq requested changes

2022-06-13 20:38 UTC, marzeq commented on websites/C/cda.pl/presence.ts
> +		presenceData.details = "Przeglądanie powiązanych kont";
This should be "Przegląda powiązane konta" to be consistent with the other presences.

2022-06-13 20:38 UTC, marzeq commented on websites/C/cda.pl/presence.ts
> +		presenceData.details = "Przeglądanie historii oglądania";
Same as previous one.

2022-06-13 20:38 UTC, marzeq commented on websites/C/cda.pl/presence.ts
> +		presenceData.details = 'Przeglądanie "Obejrzyj później"';
Same here.

2022-06-13 20:38 UTC, marzeq commented on websites/C/cda.pl/presence.ts
> +			presenceData.details = "Przegląda wideo użytkowników";
In my opinion this should be changed to "Przegląda stronę głowną wideo", as `/video` with no query string is the de-facto home page for videos.

2022-06-13 20:38 UTC, marzeq commented on websites/C/cda.pl/presence.ts
> +			presenceData.details = "Przegląda wideo użytkowników";
Why is this plural here?

2022-06-13 20:38 UTC, marzeq commented on websites/C/cda.pl/presence.ts
> +			presenceData.buttons = [{ label: "Przejdź do filmu", url: document.URL }];
A better fitting label would be "Obejrzyj film".

2022-06-14 05:13 UTC, marzeq commented
Strings are all good now.

2022-06-14 11:31 UTC, ImRodry commented
The commit history of this branch is a mess, I'll be squashing every commit in order to fix conflicts

2022-06-21 21:32 UTC, EncryptedDev approved these changes, later dismissed

2022-06-21 22:15 UTC, ImRodry commented
Please resolve the CI issues

2022-06-22 13:36 UTC, ImRodry requested changes

2022-06-22 13:36 UTC, ImRodry commented on websites/C/cda.pl/dist/metadata.json
> +	"logo": "https://i.imgur.com/AD1naGM.png",
don't know where you got this logo from but according to [this page](https://www.cda.pl/logotyp) the old one is correct

2022-06-22 13:36 UTC, ImRodry commented on websites/C/cda.pl/presence.ts
> +			largeImageKey: "https://i.imgur.com/AD1naGM.png",
same as above, please keep the old logo

2022-06-22 13:36 UTC, ImRodry commented on websites/C/cda.pl/presence.ts
> +		presenceData.buttons = [{ label: "Przejdź do folderu", url: document.URL }];
```suggestion
		presenceData.buttons = [{ label: "Przejdź do folderu", url: document.location.href }];
```

2022-07-02 23:50 UTC, ImRodry approved these changes
Approving but pls address the review

2022-07-02 23:50 UTC, ImRodry commented on websites/C/cda.pl/dist/metadata.json
> +}
do me a favor and remove this line pls :P

2022-07-06 00:19 UTC, EncryptedDev approved these changes

2022-07-06 00:19 UTC, merged

2022-07-06 00:19 UTC, EncryptedDev commented
Cheers for the PR 🎉