feat(Discord Türkiye): new presence
PreMiD/Presences pull request #6332
Opened 2022-06-17 12:16 UTC by nowongame

## Description 
Discord Türkiye, güncellemeler, haberler, sunucular, botlar, ticaretler ve birçok kategoriyi içerisinde barındıran Turkiye'nin en büyük Forum/Discord topluluğudur. 

## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://user-images.githubusercontent.com/67613805/174296231-1b5b52f4-d6c6-4fee-aff1-4535694c24e9.png)

![image](https://user-images.githubusercontent.com/67613805/174296252-25b40c46-ed22-4d39-9c10-e3b7f2900c19.png)

![image](https://user-images.githubusercontent.com/67613805/174296261-2d1b37bc-df19-472f-a094-c7f0f8658a8d.png)

</details>

2022-06-17 12:30 UTC, ImRodry requested changes
Didn't comment on all but you should never use lazy comparisons and you should use else if instead of if whenever possible

2022-06-17 12:30 UTC, ImRodry commented on websites/D/Discord Türkiye/dist/metadata.json
> +	"service": "Discord Türkiye",
the website spells this differently
```suggestion
	"service": "Discord Turkiye",
```

2022-06-17 12:30 UTC, ImRodry commented on websites/D/Discord Türkiye/dist/metadata.json
> +		"tr": "Discord Türkiye, güncellemeler, haberler, sunucular, botlar, ticaretler ve birçok kategoriyi içerisinde barındıran Turkiye'nin en büyük Forum/Discord topluluğudur."
```suggestion
		"tr": "Discord Turkiye, güncellemeler, haberler, sunucular, botlar, ticaretler ve birçok kategoriyi içerisinde barındıran Turkiye'nin en büyük Forum/Discord topluluğudur."
```

2022-06-17 12:30 UTC, ImRodry commented on websites/D/Discord Türkiye/dist/metadata.json
> +	"logo": "https://i.imgur.com/LW8xjEU.png",
logo must be 512x512

2022-06-17 12:30 UTC, ImRodry commented on websites/D/Discord Türkiye/presence.ts
> +			startTimestamp: Math.floor(Date.now() / 1000),
this needs to be declared outside the scope otherwise it won't work

2022-06-17 12:30 UTC, ImRodry commented on websites/D/Discord Türkiye/presence.ts
> +			state: "",
remove this, it's useless

2022-06-17 12:30 UTC, ImRodry commented on websites/D/Discord Türkiye/presence.ts
> +			smallImageKey: "",
remove this, it's useless

2022-06-17 12:30 UTC, ImRodry commented on websites/D/Discord Türkiye/presence.ts
> +	const presenceData = {
```suggestion
	const presenceData: PresenceData = {
```

2022-06-17 12:30 UTC, ImRodry commented on websites/D/Discord Türkiye/presence.ts
> +		});
this isn't what you wanna do
```suggestion
		privacyMode = await presence.getSetting("privacy_mode").catch(() =>	false);
```

2022-06-17 12:30 UTC, ImRodry commented on websites/D/Discord Türkiye/presence.ts
> +	if (document.querySelector('[href="/login/"]') != null) {
```suggestion
	if (document.querySelector('[href="/login/"]')) {
```

2022-06-17 12:30 UTC, ImRodry commented on websites/D/Discord Türkiye/presence.ts
> +		page = document.location.pathname,
change the variable name accordingly
```suggestion
		{ pathname } = document.location,
```

2022-06-17 12:30 UTC, ImRodry commented on websites/D/Discord Türkiye/presence.ts
> +	if (page == "/") presenceData.details = "Anasayfayı görüntülüyor";
don't use lazy comparisons 
```suggestion
	if (page === "/") presenceData.details = "Anasayfayı görüntülüyor";
```

2022-06-17 12:30 UTC, ImRodry commented on websites/D/Discord Türkiye/presence.ts
> +	}
these brackets shouldn't be needed

2022-06-17 12:30 UTC, ImRodry commented on websites/D/Discord Türkiye/presence.ts
> +			(<HTMLElement>document.querySelector("div.fr-element.fr-view > p"))
why
```suggestion
			(document.querySelector<HTMLElement>("div.fr-element.fr-view > p"))
				?.innerText &&
			(document.querySelector<HTMLElement>("div.fr-element.fr-view > p"))
```

2022-06-17 12:30 UTC, ImRodry commented on websites/D/Discord Türkiye/presence.ts
> +		} else if (
brackets arent needed

2022-06-17 12:31 UTC, ImRodry commented on websites/D/Discord Türkiye/presence.ts
> +	if (presenceData.details) presence.setActivity(presenceData);
oh and this will never be false

2022-06-17 13:04 UTC, ImRodry requested changes

2022-06-17 13:04 UTC, ImRodry commented on websites/D/Discord Turkiye/dist/metadata.json
> +	],
Why did you set yourself as a contributor and not the author? What did the other user do?

2022-06-17 22:43 UTC, ImRodry commented on websites/D/Discord Turkiye/dist/metadata.json
> +	],
If they made the code they should be the ones making this PR. If not then you should be the author. Regardless, I see no reason to do this

2022-06-20 21:57 UTC, EncryptedDev commented
Please take a check of the strings here please @eggsy

2022-06-20 22:03 UTC, eggsy commented on websites/D/Discord Turkiye/dist/metadata.json
> +		"tr": "Discord Turkiye, güncellemeler, haberler, sunucular, botlar, ticaretler ve birçok kategoriyi içerisinde barındıran Turkiye'nin en büyük Forum/Discord topluluğudur."
There's no plural of the word "ticaret" so the use of "ticaretler" is not correct. Just call it "ticaret", which will basically get you the same meaning.

Replace "Turkiye" with "Türkiye" in the following string:
> barındıran Turkiye'nin...

Make "Forum" lowercase, initial letter shouldn't be uppercase.

2022-06-20 22:03 UTC, eggsy commented on websites/D/Discord Turkiye/dist/metadata.json
> +	"tags": ["discord", "kod-paylaşım", "raven-code"],
Why is there `raven-code` here?

2022-06-20 22:04 UTC, eggsy requested changes
Everything is fine, except some grammatical and vocabulary issues, it would be good if you could fix all of them as well.

2022-06-22 08:24 UTC, eggsy approved these changes
Looking good now.

2022-06-29 12:46 UTC, Bas950 approved these changes
LGTM

2022-06-29 13:14 UTC, ImRodry requested changes

2022-06-29 13:14 UTC, ImRodry commented on websites/D/Discord Turkiye/presence.ts
> +				?.textContent !== "\n"
make this a constant to avoid computing it twice

2022-06-29 13:14 UTC, ImRodry commented on websites/D/Discord Turkiye/presence.ts
> +			)).textContent;
ditto

2022-06-29 13:14 UTC, ImRodry commented on websites/D/Discord Turkiye/presence.ts
> +			)).style.backgroundImage
ditto

2022-06-29 13:14 UTC, ImRodry commented on websites/D/Discord Turkiye/presence.ts
> +	} else if ((<HTMLElement>document.querySelector("div.tag")).textContent) {
ditto

2022-06-29 13:14 UTC, ImRodry commented on websites/D/Discord Turkiye/presence.ts
> +			(<HTMLElement>document.querySelector("div.tag > div.discriminator"))
ditto

2022-06-29 13:14 UTC, ImRodry commented on websites/D/Discord Turkiye/presence.ts
> +		presenceData.largeImageKey = (<HTMLElement>(
ditto

2022-06-29 13:14 UTC, ImRodry commented on websites/D/Discord Turkiye/presence.ts
> +	return presence.setActivity(presenceData);
don't return
```suggestion
	presence.setActivity(presenceData);
```

2022-06-29 21:17 UTC, nowongame commented on websites/D/Discord Turkiye/presence.ts
> +	}
I can use a switch?

2022-06-29 21:31 UTC, ImRodry commented on websites/D/Discord Turkiye/presence.ts
> +	}
You can but you don’t have to

2022-06-29 21:31 UTC, ImRodry commented
Please resolve the conversations you address…

2022-06-29 23:33 UTC, nowongame commented on websites/D/Discord Turkiye/presence.ts
> +	}
So you think I should add else ifs?

2022-06-30 06:31 UTC, ImRodry commented on websites/D/Discord Turkiye/presence.ts
> +	}
That seems to be what I said indeed

2022-07-02 23:43 UTC, ImRodry requested changes
Will merge after this

2022-07-02 23:43 UTC, ImRodry commented on websites/D/Discord Turkiye/presence.ts
> +					?.textContent !== "\n"
You had a truthy check before, this is safer
```suggestion
					?.textContent.trim()
```

2022-07-03 08:53 UTC, ImRodry approved these changes

2022-07-03 08:53 UTC, merged