feat(GitHub) add privacy mode
PreMiD/Presences pull request #6367
Opened 2022-06-27 18:35 UTC by realtofuine

## Description 
add privacy mode to the GitHub Presence

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://user-images.githubusercontent.com/73127480/175982941-7aab13d4-00f2-4ada-8cd9-a0a757ce4f42.png)

![image](https://user-images.githubusercontent.com/73127480/175983421-906af137-cabf-42c4-ac82-df0fa7de6b9a.png)

![image](https://user-images.githubusercontent.com/73127480/175983536-bee775e5-bdee-4d97-88fa-07e983b65ff2.png)

![image](https://user-images.githubusercontent.com/73127480/175984132-3651efe9-da49-4e92-afae-7669079b8c88.png)

</details>

2022-06-27 21:02 UTC, EncryptedDev requested changes
If you are going to add a privacy filter, you should add it to all pages which display private information. For example, you should add this to organization pages, pull requests etc.

2022-06-27 21:02 UTC, EncryptedDev commented on websites/G/GitHub/dist/metadata.json
> +	"version": "2.10.9",
This should be minor

2022-06-27 22:34 UTC, realtofuine commented
closes #6357

2022-06-28 02:48 UTC, realtofuine commented
closes #6355

2022-06-28 03:22 UTC, realtofuine commented
resolves #6346

2022-07-06 00:08 UTC, EncryptedDev approved these changes, later dismissed

2022-07-06 00:21 UTC, ImRodry requested changes, later dismissed

2022-07-06 00:21 UTC, ImRodry commented on websites/G/GitHub/presence.ts
> +			} else presenceData.largeImageKey = "lg";
this value is already set, this line is useless

2022-07-06 00:21 UTC, ImRodry commented on websites/G/GitHub/presence.ts
> +			}
why set it just to delete it right after?

2022-07-06 00:21 UTC, ImRodry commented on websites/G/GitHub/presence.ts
> +		presenceData.startTimestamp = Math.floor(Date.now() / 1000);
this doesn't work.

2022-07-06 00:21 UTC, ImRodry commented on websites/G/GitHub/presence.ts
> +				presenceData.details = "Viewing an organization's people";
what is this english

2022-07-06 00:23 UTC, ImRodry requested changes
Wrong button

2022-07-06 21:48 UTC, EncryptedDev commented
Please attach proof individually of each issue linked being resolved.

2022-07-06 23:01 UTC, realtofuine commented
> Please attach proof individually of each issue linked being resolved.

ok i did it

its under the screenshots now

2022-07-14 11:46 UTC, Bas950 approved these changes

2022-07-15 01:44 UTC, EncryptedDev approved these changes

2022-07-15 01:44 UTC, EncryptedDev commented
Thank you for the PR 🎉

2022-07-15 01:44 UTC, merged