fix(Pocket Casts): make presence work again
PreMiD/Presences pull request #6377
Opened 2022-06-29 05:23 UTC by realtofuine

## Description 
make Pocket Casts Rich Presence work again

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://user-images.githubusercontent.com/73127480/176355624-b4968d1c-b49c-41e5-9ebc-37ad15b9e3fd.png)

![image](https://user-images.githubusercontent.com/73127480/176355643-5f0187ad-3ef9-41f5-844f-5c80322833eb.png)

![image](https://user-images.githubusercontent.com/73127480/176357833-3c650977-fd01-4e41-b8d6-6d382f75b164.png)

![image](https://user-images.githubusercontent.com/73127480/176357852-59d9b9c9-f757-4436-b4e6-945fafc2adbd.png)

</details>

2022-06-29 05:24 UTC, realtofuine commented
fixes #2696

2022-06-29 08:36 UTC, ImRodry commented
Please use a proper title (say what was actually wring and what you fixed)

2022-07-02 23:02 UTC, ImRodry requested changes

2022-07-02 23:02 UTC, ImRodry commented on websites/P/Pocket Casts/presence.ts
> +	// const el = document.querySelector(".controls");
why

2022-07-02 23:02 UTC, ImRodry commented on websites/P/Pocket Casts/presence.ts
> +			.map(n => Number(n));
```suggestion
			.map(Number);
```

2022-07-03 00:40 UTC, realtofuine commented on websites/P/Pocket Casts/presence.ts
> +	// const el = document.querySelector(".controls");
oops lol
i was testing

2022-07-03 00:49 UTC, ImRodry approved these changes

2022-07-06 00:18 UTC, EncryptedDev approved these changes

2022-07-06 00:18 UTC, merged

2022-07-06 00:18 UTC, EncryptedDev commented
Thanks for the PR