feat(Audible): new presence
PreMiD/Presences pull request #6381
Opened 2022-06-30 13:46 UTC by realtofuine

## Description 
add a new presence for Audible (audible.com)

closes #5479 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://user-images.githubusercontent.com/73127480/176693262-d8e0d122-e2f3-4f6e-85ce-93fffaeb4fb4.png)

![image](https://user-images.githubusercontent.com/73127480/176693299-7ad1ac41-4829-48e6-9e47-f5714c46eee3.png)

![image](https://user-images.githubusercontent.com/73127480/176693361-af1abafe-6037-42b1-87de-d839abe03f91.png)

![image](https://user-images.githubusercontent.com/73127480/176693427-dfce9adc-fef7-4396-9acf-d1b2770bab3b.png)

</details>

2022-07-02 22:34 UTC, ImRodry reviewed
Apply that suggestion to all the cases
Also are you sure you're supporting every page on the website?

2022-07-02 22:34 UTC, ImRodry commented on websites/A/Audible/presence.ts
> +		delete presenceData.state;
state wasn't assigned a value prior to this, this isn't needed

2022-07-02 22:34 UTC, ImRodry commented on websites/A/Audible/presence.ts
> +		presenceData.startTimestamp = browsingTimestamp;
just assign this at the object declaration

2022-07-02 22:34 UTC, ImRodry requested changes
Oopsies

2022-07-06 16:44 UTC, EncryptedDev requested changes

2022-07-06 16:44 UTC, EncryptedDev commented on websites/A/Audible/presence.ts
> +	presenceData.startTimestamp = browsingTimestamp;
```suggestion
presence.on("UpdateData", async () => {
	const presenceData: PresenceData = {
		largeImageKey: "logo",
		startTimestamp: browsingTimestamp
	};
```

2022-07-10 01:15 UTC, EncryptedDev requested changes

2022-07-10 01:15 UTC, EncryptedDev commented on websites/A/Audible/presence.ts
> +		presenceData.largeImageKey = cover;
Apply the same logic from here https://github.com/PreMiD/Presences/pull/6408/files#r917325055

2022-07-14 00:42 UTC, EncryptedDev approved these changes

2022-07-14 11:53 UTC, Bas950 approved these changes

2022-07-14 11:53 UTC, merged