feat(Airbnb): new presence
PreMiD/Presences pull request #6408
Opened 2022-07-03 14:55 UTC by realtofuine

## Description 
add Airbnb Presence

closes #6300 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://user-images.githubusercontent.com/73127480/177045293-5f1a7336-6c1c-48d8-bdb6-5f327adcfcaa.png)

![image](https://user-images.githubusercontent.com/73127480/177045300-06d2f1df-aee1-4ddd-8e37-341267b7f042.png)

![image](https://user-images.githubusercontent.com/73127480/177045314-16d6361b-bbd0-4c11-8708-f4497be9c17e.png)

![image](https://user-images.githubusercontent.com/73127480/177045329-bcdaee10-36c2-443a-96dd-a006fb036809.png)

</details>

2022-07-10 01:13 UTC, EncryptedDev requested changes
Sorry for the inactivity on my behalf, managed to miss this PR 🙏🏼

2022-07-10 01:13 UTC, EncryptedDev commented on websites/A/Airbnb/dist/metadata.json
> +	"logo": "https://i.imgur.com/UnBuyQM.png",
This is absolutely huge, could you get something smaller?

2022-07-10 01:13 UTC, EncryptedDev commented on websites/A/Airbnb/presence.ts
> +	presenceData.startTimestamp = browsingTimestamp;
Assign the value within the PresenceDate object above

2022-07-10 01:13 UTC, EncryptedDev commented on websites/A/Airbnb/presence.ts
> +		presenceData.state = room;
```suggestion
		presenceData.state = document.querySelector(
			"#site-content > div > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div > div > div > div > section > div._b8stb0 > span > h1"
		).textContent;
```

2022-07-10 01:13 UTC, EncryptedDev commented on websites/A/Airbnb/presence.ts
> +		presenceData.state = `From ${dates} for ${guests}`;
Apply the same logic here too

2022-07-14 00:41 UTC, EncryptedDev requested changes
Hello 👋

There isn't a lot of depth to this presence, but it still has a strong possibility in being merged. Please try to include some more features - I have included a suggest below which may help: 
- Add a "privacy" setting to hide personal details (place names, location etc)

2022-07-14 00:41 UTC, EncryptedDev commented on websites/A/Airbnb/dist/metadata.json
> +	"logo": "https://i.imgur.com/DyWMYDn.png",
Must be 512x512

2022-07-14 00:41 UTC, EncryptedDev commented on websites/A/Airbnb/presence.ts
> +		presenceData.details = "Viewing rooms";
This suggests that the user is viewing multiple rooms, whereas the button contradicts this and implies that the user is viewing a singular room.

2022-07-19 16:15 UTC, EncryptedDev requested changes

2022-07-19 16:15 UTC, EncryptedDev commented on websites/A/Airbnb/presence.ts
> +			delete presenceData.buttons;
Neither state or buttons are set before this point so this is not needed.

2022-07-19 16:15 UTC, EncryptedDev commented on websites/A/Airbnb/presence.ts
> +
`document.location.pathname` is repeated many times so you should deconstruct it and reference `pathname instead`

`{ pathname } = document.location`

2022-07-20 14:28 UTC, EncryptedDev approved these changes

2022-07-20 14:38 UTC, Bas950 approved these changes

2022-07-20 14:38 UTC, merged