feat(Google Maps): new presence
PreMiD/Presences pull request #6414
Opened 2022-07-04 18:24 UTC by realtofuine

## Description 

add presence for google maps

closes #5372

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://user-images.githubusercontent.com/73127480/177203464-7b5f6a10-1f59-45f4-b137-9996276b0132.png)

![image](https://user-images.githubusercontent.com/73127480/177203497-f5e94c99-c3f9-47af-9eff-87e862001f18.png)

![image](https://user-images.githubusercontent.com/73127480/177203562-f573e508-fb97-403a-9dbe-606cd620f0a6.png)

</details>

2022-07-06 16:30 UTC, EncryptedDev requested changes
Add a privacy filter too please

2022-07-06 16:30 UTC, EncryptedDev commented on websites/G/Google Maps/presence.ts
> +	// if (document.location.pathname.includes("/maps")) {
Remove this comment

2022-07-06 16:30 UTC, EncryptedDev commented on websites/G/Google Maps/dist/metadata.json
> +	"url": "www.google.com",
Would this not interfere with the other Google presences? Sure you can just use `maps.google.com` instead

2022-07-06 16:30 UTC, EncryptedDev commented on websites/G/Google Maps/presence.ts
> +	presenceData.startTimestamp = browsingTimestamp;
```suggestion
	const presenceData: PresenceData = {
		largeImageKey: "logo",
		startTimestamp: browsingTimestamp
	};
```

2022-07-06 16:46 UTC, realtofuine commented
WAIT DONT REVIEW IT YET I FORGOT PRIVACY MODE

2022-07-09 00:24 UTC, EncryptedDev commented on websites/G/Google Maps/dist/metadata.json
> +	"url": "www.google.com",
Lol, it does that for me sometimes and on some devices not everything xD

2022-07-09 00:26 UTC, EncryptedDev requested changes

2022-07-09 00:26 UTC, EncryptedDev commented on websites/G/Google Maps/presence.ts
> +			presenceData.details = "Viewing directions from one place to another";
Sounds rather conversation
```suggestion
			presenceData.details = "Viewing directions to a location";
```

2022-07-09 00:26 UTC, EncryptedDev commented on websites/G/Google Maps/presence.ts
> +			if (document.querySelector("#sb_ifc50 > input") === null) {
```suggestion
			if (!document.querySelector("#sb_ifc50 > input")) {
```

2022-07-14 00:34 UTC, EncryptedDev approved these changes
Looks fine

2022-07-14 11:35 UTC, Bas950 requested changes

2022-07-14 11:35 UTC, Bas950 commented on websites/G/Google Maps/presence.ts
> +						.getAttribute("aria-label"));
```suggestion
				from = document
					.querySelector("#sb_ifc51 > input")
					.getAttribute("aria-label");
					destination = document
						.querySelector("#sb_ifc52 > input")
						.getAttribute("aria-label");
```

2022-07-15 01:48 UTC, EncryptedDev commented
Revert the last two commits; Prettier requires this

2022-07-15 10:38 UTC, EncryptedDev commented
@realtofuine Run `yarn format` please

2022-07-15 12:13 UTC, realtofuine commented
prettier's love for parentheses is unmatched

2022-07-15 12:57 UTC, Bas950 approved these changes

2022-07-15 12:57 UTC, merged