Add files via upload
PreMiD/Presences pull request #6424
Opened 2022-07-08 07:21 UTC by impsyutgard

## Description 
Hello this is my first time coding something, I had help from Kyrie on discord to help me make this rich presence for one of my favorite online games dungeon crawl stone soup.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format` - i believe i did this correctly? I used ESLint extension with Visual Studio Code
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> i have attached three images of the rich presence working, if your on the home screens of the different servers it shows browing lobby, otherwise it will show when various information when you are spectating a player or playing yourself with a spectate button so people can instantly launch the page in their browser to watch you play. </summary>

</details>
![working1](https://user-images.githubusercontent.com/13695229/177937474-5846c460-6762-4c8d-bfda-bb83d57d3a09.png)
![working2](https://user-images.githubusercontent.com/13695229/177937477-9524f230-09a5-4f96-b0cc-344bb88920df.png)
![working3](https://user-images.githubusercontent.com/13695229/177937481-59737ce2-5aee-4b45-bc6a-60139c6d003f.png)

2022-07-08 10:28 UTC, EncryptedDev requested changes

2022-07-08 10:28 UTC, EncryptedDev commented on websites/D/Dungeon Crawl Stone Soup/presence.ts
> +		presenceData.details = "Browsing lobby..";
```suggestion
		presenceData.details = "Browsing lobby";
```

2022-07-09 00:36 UTC, EncryptedDev approved these changes

2022-07-10 08:50 UTC, Bas950 approved these changes
Not a whole lot to it, but LGTM

2022-07-10 08:50 UTC, merged