feat(Cytoid): new presence
PreMiD/Presences pull request #6434
Opened 2022-07-10 11:08 UTC by joerkig

## Description 

Add new presence for [Cytoid](https://cytoid.io)
Resolves #5987 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![Discord_WzUpZhYnxC](https://user-images.githubusercontent.com/44418429/178142283-04ddc47f-0076-40f6-8993-3065b65f9b25.png)
![rK9TVK832D](https://user-images.githubusercontent.com/44418429/178142285-a5f420e5-c272-4c41-8be4-66a3dfab499f.png)
![Discord_2DQdmAxxBG](https://user-images.githubusercontent.com/44418429/178142287-1f94dd3a-da5f-4ba4-b49c-4104cf4a9ac0.png)
![Discord_57Fxg0VsDd](https://user-images.githubusercontent.com/44418429/178142288-35f83080-41a7-4583-9b0d-bee50f72fda1.png)
![Discord_61Kif2ndBe](https://user-images.githubusercontent.com/44418429/178142290-4f235192-6143-475f-b7db-9b6700cb9a15.png)
![Discord_bpMCRKrvpp](https://user-images.githubusercontent.com/44418429/178142291-ff458b25-0e85-4270-84d9-a7668b57052b.png)
![Discord_En9MtQgXcD](https://user-images.githubusercontent.com/44418429/178142292-440b31fe-004f-4815-89f2-e159ae15b890.png)
![Discord_GIq5GSkdM7](https://user-images.githubusercontent.com/44418429/178142294-2bd0ada0-7e8f-4f86-898a-5052be8dbb46.png)
![Discord_qxPiw7RLRk](https://user-images.githubusercontent.com/44418429/178142295-88045bab-0df0-4b3d-850e-944a779ab81a.png)
![Discord_SbnoENvkVa](https://user-images.githubusercontent.com/44418429/178142296-201fb515-1a3c-4e1c-a406-a846d2b66a2b.png)
![Discord_sEY0d0Yxiy](https://user-images.githubusercontent.com/44418429/178142297-e374fe6c-15e6-4626-bf0d-51c5720f746d.png)
![Discord_UCG3ufydGB](https://user-images.githubusercontent.com/44418429/178142298-68a847d9-1760-41c6-bd33-88f79356569e.png)

</details>

2022-07-11 17:27 UTC, EncryptedDev requested changes

2022-07-11 17:27 UTC, EncryptedDev commented on websites/C/Cytoid/dist/metadata.json
> +			"id": "time",
I think this would be more consistent with the repo
```suggestion
			"id": "timestamps",
```

2022-07-11 17:27 UTC, EncryptedDev commented on websites/C/Cytoid/presence.ts
> +				element => element.paused === false
```suggestion
				element => !element.paused
```

2022-07-11 17:42 UTC, joerkig commented on websites/C/Cytoid/presence.ts
> +	if (!time) {
```suggestion
	if (!timestamps) {
```

2022-07-11 17:42 UTC, joerkig commented on websites/C/Cytoid/presence.ts
> +			presence.getSetting<boolean>("time"),
```suggestion
	const [timestamps, buttons, cover] = await Promise.all([
			presence.getSetting<boolean>("timestamps"),
```

2022-07-11 18:00 UTC, EncryptedDev approved these changes
Thank you for your speedy respond. LGTM

2022-07-14 11:44 UTC, Bas950 approved these changes

2022-07-14 11:44 UTC, merged