feat(Jellyfin): support local images
PreMiD/Presences pull request #6437
Opened 2022-07-11 14:05 UTC by Slowlife01

## Description 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://user-images.githubusercontent.com/54318514/178282754-2d269f1a-2fdb-4c6c-9845-dcce0e241622.png)

</details>

2022-07-11 14:53 UTC, EncryptedDev approved these changes

2022-07-14 11:43 UTC, Bas950 requested changes

2022-07-14 11:43 UTC, Bas950 commented on websites/J/Jellyfin/presence.ts
> +	return (uploadedImages[url] = outputUrl);
```suggestion
        uploadedImages[url] = outputUrl;
	return outputUrl;
```

2022-07-15 12:55 UTC, Bas950 approved these changes

2022-07-15 12:55 UTC, merged