feat(Plex): support local images
PreMiD/Presences pull request #6438
Opened 2022-07-11 14:06 UTC by Slowlife01

## Description 

Fixes #6277

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://user-images.githubusercontent.com/54318514/178283073-52992db8-8973-407b-9701-5229dcc1b202.png)
![image](https://user-images.githubusercontent.com/54318514/178283092-1cb23b3f-967b-4a45-aebc-1bc4aff7b398.png)

</details>

2022-07-14 00:43 UTC, EncryptedDev approved these changes

2022-07-14 11:48 UTC, Bas950 requested changes

2022-07-14 11:48 UTC, Bas950 commented on websites/P/Plex/presence.ts
> +	return (uploadedImages[url] = outputUrl);
```suggestion
	uploadedImages[url] = outputUrl;
	return outputUrl;
```

2022-07-15 12:53 UTC, Bas950 approved these changes

2022-07-15 12:53 UTC, merged