feat(Reddit): add privacy mode
PreMiD/Presences pull request #6442
Opened 2022-07-12 15:14 UTC by realtofuine

## Description 

add privacy mode to reddit rich presence

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://user-images.githubusercontent.com/73127480/178524100-785e6fb0-f53a-427c-865f-fab647590f65.png)

![image](https://user-images.githubusercontent.com/73127480/178524131-745ecf06-d4c2-47c5-870e-79222bc0cd61.png)

![image](https://user-images.githubusercontent.com/73127480/178524167-0d81d66a-65fc-4a0b-ba4c-3c9381466868.png)

</details>

2022-07-14 00:57 UTC, EncryptedDev requested changes
Hello 👋

Please remove the comments, they explain exactly what a boolean expression is and are not needed.

2022-07-14 00:57 UTC, EncryptedDev commented on websites/R/Reddit/presence.ts
> +		privacy = await presence.getSetting<boolean>("privacy");
Use [Promise.all()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all). 
Extensive reference: https://github.com/PreMiD/Presences/blob/5ccc89aca1c18bb5e8de37dca18f3e659e134b7b/websites/A/Apple/presence.ts#L96-L113

2022-07-14 00:57 UTC, EncryptedDev commented on websites/R/Reddit/presence.ts
> +						: "In a subreddit" // if privacy mode is enabled
This should be localised

2022-07-14 00:57 UTC, EncryptedDev commented on websites/R/Reddit/presence.ts
> +				username = document.querySelector(".titlebox > h1").textContent;
```suggestion
				presenceData.state = document.querySelector(".titlebox > h1").textContent;
```

2022-07-14 00:57 UTC, EncryptedDev commented on websites/R/Reddit/presence.ts
> +				presenceData.state = username;
```suggestion
```

2022-07-15 01:43 UTC, EncryptedDev commented
Format with `yarn format`

2022-07-19 16:20 UTC, EncryptedDev requested changes

2022-07-19 16:20 UTC, EncryptedDev commented on websites/R/Reddit/presence.ts
> +		if (sub === null) {
```suggestion
		if (!sub) {
```

2022-07-19 16:20 UTC, EncryptedDev commented on websites/R/Reddit/presence.ts
>  	presence.setActivity(presenceData, true);
```suggestion
	presence.setActivity(presenceData);
```

2022-07-20 01:43 UTC, EncryptedDev approved these changes

2022-07-20 13:58 UTC, Bas950 approved these changes

2022-07-20 13:58 UTC, merged