refactor(Mediafire): improved code
PreMiD/Presences pull request #6449
Opened 2022-07-14 11:32 UTC by DarkVillager

## Description 

Improved the code to match current code quality guideliness.

## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://user-images.githubusercontent.com/42322979/178972982-21df10db-f7a9-4efd-9814-7886ba72a867.png">

<img src="https://user-images.githubusercontent.com/42322979/178972989-e7c536e0-58f1-4564-ab7e-0126dc5cfe67.png">

<img src="https://user-images.githubusercontent.com/42322979/178972991-dfabfced-cc3c-401a-bc87-56cc5e2ed3cd.png">

<img src="https://user-images.githubusercontent.com/42322979/178972993-78a94abb-9236-4a09-8c99-00795c24482a.png">

</details>

2022-07-19 16:10 UTC, EncryptedDev requested changes

2022-07-19 16:10 UTC, EncryptedDev commented on websites/M/Mediafire/presence.ts
> +			if (pathname === "/") presenceData.details = "Viewing the homepage";
```suggestion
			if (pathname === "/") presenceData.details = "Viewing the home page";
```

2022-07-19 16:10 UTC, EncryptedDev commented on websites/M/Mediafire/presence.ts
> +			else presenceData.details = "My Files";
All the strings here sound weird standalone. Add a verb before it - "Viewing their files" etc

2022-07-20 14:30 UTC, EncryptedDev approved these changes

2022-07-20 14:37 UTC, Bas950 approved these changes

2022-07-20 14:37 UTC, merged