feat(Alura): new presence
PreMiD/Presences pull request #6452
Opened 2022-07-14 22:09 UTC by MadsonMendes

## Description 

Created a presence for Alura as a request in student's server. Added some dynamic elements as well. Planning to translate everything to Portuguese later. 
## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://user-images.githubusercontent.com/50425778/179096407-5162b0a6-bc60-42da-8e70-1b705e15e13e.png)
![image](https://user-images.githubusercontent.com/50425778/179096600-890ccb09-ccff-4f2b-810d-1377f2898439.png)
![image](https://user-images.githubusercontent.com/50425778/179096738-c28f5135-e58b-4db6-823b-20b843c7815e.png)
![image](https://user-images.githubusercontent.com/50425778/179096783-b36d819f-aaa8-471e-8885-fcc8d9624d1f.png)
![image](https://user-images.githubusercontent.com/50425778/179096845-3a9af28a-6971-428f-a708-6da414e191b9.png)
![image](https://user-images.githubusercontent.com/50425778/179096904-cf958f68-531e-4664-a510-a3ef13ed2abe.png)

</details>

2022-07-15 00:10 UTC, ImRodry commented
The website is in portuguese so the presence should be too. I don’t think you should have multilang

2022-07-15 10:48 UTC, EncryptedDev requested changes
Hello! I've noticed the following imperfections with your PR, please address them :+1:

2022-07-15 10:48 UTC, EncryptedDev commented on websites/A/Alura/presence.ts
> +			presenceData.state = title.textContent;
```suggestion
			presenceData.state = document.querySelector("section.task-menu-header > div > a > h2").textContent;
```

2022-07-15 10:48 UTC, EncryptedDev commented on websites/A/Alura/presence.ts
> +			presenceData.state = title.textContent;
```suggestion
			presenceData.state = document.querySelector(
				"div.container.course-header-banner-content > div > div.hreview-aggregate > h1 > strong"
			).textContent;
```

2022-07-15 10:48 UTC, EncryptedDev commented on websites/A/Alura/presence.ts
> +			document.querySelector(".--margin-left-image") === null
Update this on future references of `!== null` and `=== null`
```suggestion
			document.querySelector(".podcast-header-title") &&
			!document.querySelector(".--margin-left-image")
```

2022-07-19 16:21 UTC, EncryptedDev reviewed
Hello 👋

- Run `yarn format` as the metadata file is not formatted with tabs

2022-07-21 02:38 UTC, fr0r approved these changes

2022-07-21 02:38 UTC, fr0r commented on websites/A/Alura/dist/metadata.json
> +		"pt_BR": "A maior escola online de tecnologia do Brasil."
👍

2022-07-21 09:15 UTC, ImRodry reviewed
Here’s a proper review of the strings + code. I didn’t comment on all lines but there is a lot of unnecessary computation being done that should be avoided

2022-07-21 09:15 UTC, ImRodry commented on websites/A/Alura/presence.ts
> +				.getAttribute("aria-label") === "Inovação & Gestão"
This should only be computed once so you should make it into a constant

2022-07-21 09:15 UTC, ImRodry commented on websites/A/Alura/presence.ts
> +			document.querySelector("div.formacao__info-categoria > a").textContent ===
Ditto

2022-07-21 09:15 UTC, ImRodry commented on websites/A/Alura/presence.ts
> +			presenceData.details = strings.user;
Why are strings being used here? That makes no sense

2022-07-21 09:15 UTC, ImRodry commented on websites/A/Alura/presence.ts
> +				presenceData.details = "Vendo pegamentos";
Pegamentos é noutro lado…

2022-07-21 09:15 UTC, ImRodry commented on websites/A/Alura/presence.ts
> +			presenceData.details = "Vendo o ranking";
De quê?

2022-07-21 09:15 UTC, ImRodry commented on websites/A/Alura/presence.ts
> +				document.querySelector(".podcast-header-title").textContent
Don’t compute this twice

2022-07-21 09:15 UTC, ImRodry commented on websites/A/Alura/presence.ts
> +		presenceData.details = "Assistindo um Case";
Case não deve estar em maiúscula

2022-07-21 09:15 UTC, ImRodry commented on websites/A/Alura/presence.ts
> +				document.querySelector(".intro__title").textContent
Don’t compute this twice

2022-07-21 09:15 UTC, ImRodry commented on websites/A/Alura/presence.ts
> +		presenceData.details = 'Ouvindo o "Hipsters.tech"';
O outro tinha T maiúsculo e este já não?

2022-07-24 09:51 UTC, EncryptedDev approved these changes

2022-07-24 09:52 UTC, EncryptedDev commented
Ignore the comments, my apologies

2022-07-28 17:06 UTC, Bas950 approved these changes

2022-07-28 17:06 UTC, merged