feat(Serializd): new presence
PreMiD/Presences pull request #6457
Opened 2022-07-15 14:55 UTC by Lavenderleaff

## Description 

This is a presence for Serializd, I tried my best to fit the description of [this](https://github.com/PreMiD/Presences/issues/6432) so it may be closed.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://user-images.githubusercontent.com/107295665/179249091-aa0f267f-ae9f-49d7-a522-950161f3acdb.png)
![image](https://user-images.githubusercontent.com/107295665/179249199-10cc8055-b067-47dc-862e-d4fdcf28f3df.png)
![image](https://user-images.githubusercontent.com/107295665/179249256-1710d3c4-0867-45e8-9171-39bc535bf2eb.png)

</details>

2022-07-15 15:11 UTC, kyrie25 requested changes

2022-07-15 15:11 UTC, kyrie25 commented on websites/S/Serializd/presence.ts
> +			}`;
```suggestion
		else {
			presenceData.details = `Viewing reviews of ${
				document.querySelector(".subheading").textContent
			}`;
		}
```

2022-07-15 15:11 UTC, kyrie25 commented on websites/S/Serializd/presence.ts
> +		}`;
```suggestion
	} else if (document.location.pathname.includes("review")) {
		presenceData.details = `Viewing a review for ${
			document.querySelector(".subheading").textContent
		}`;
	}
```

2022-07-19 16:31 UTC, EncryptedDev approved these changes

2022-07-20 14:06 UTC, Bas950 approved these changes

2022-07-20 14:06 UTC, merged