feat(vscode.dev): add presence
PreMiD/Presences pull request #6461
Opened 2022-07-16 07:38 UTC by Faelayis

## Description 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://user-images.githubusercontent.com/48393914/179345227-b42f5d81-f748-4457-99a3-00c4bd092632.png)
![image](https://user-images.githubusercontent.com/48393914/179344596-dcfd9ce2-1d63-47a6-a8c0-e2a4284ecef5.png)
![image](https://user-images.githubusercontent.com/48393914/179345171-3583f59e-8da3-4f5e-a60b-f822265f63a9.png)
![image](https://user-images.githubusercontent.com/48393914/179344481-7dd3cd94-a40a-49e6-8a20-3976ff2009a1.png)
![image](https://user-images.githubusercontent.com/48393914/179344615-c0a3fd4d-f430-4d46-aa5a-863ba4c7c4fd.png)

</details>

2022-07-19 16:36 UTC, EncryptedDev requested changes

2022-07-19 16:36 UTC, EncryptedDev commented on websites/V/vscode.dev/presence.ts
> + */
You can create a README.md file like Custom Status presence and add these customisations there

2022-07-20 14:57 UTC, EncryptedDev requested changes

2022-07-20 14:57 UTC, EncryptedDev commented on websites/V/vscode.dev/README.md
> +- `%selection%` will be replaced with the current line.
I would use a [markdown table](https://www.tablesgenerator.com/markdown_tables) for this with the headers "Parameter", "Description" and "Example"

2022-07-20 14:57 UTC, EncryptedDev commented on websites/V/vscode.dev/README.md
> +# How to custom string
```suggestion
# Presence Parameters for Customisation
```

2022-07-20 14:57 UTC, EncryptedDev commented on websites/V/vscode.dev/presence.ts
> +				"https://raw.githubusercontent.com/leonardssh/vscord/main/assets/icons/vscode.png",
Ditto

2022-07-20 14:57 UTC, EncryptedDev commented on websites/V/vscode.dev/presence.ts
> +		filename = status.file,
Update referencds too
```suggestion
		{ file } = status,
```

2022-07-20 14:57 UTC, EncryptedDev commented on websites/V/vscode.dev/presence.ts
> +		Replace = function (value: string) {
Create a proper [function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions)

2022-07-20 14:57 UTC, EncryptedDev commented on websites/V/vscode.dev/presence.ts
> +			"https://raw.githubusercontent.com/leonardssh/vscord/main/assets/icons/idle-vscode.png";
Ditto

2022-07-20 14:57 UTC, EncryptedDev commented on websites/V/vscode.dev/presence.ts
> +		presenceData.largeImageKey = `https://raw.githubusercontent.com/leonardssh/vscord/main/assets/icons/${
Ditto

2022-07-21 06:27 UTC, Faelayis commented on websites/V/vscode.dev/presence.ts
> +				"https://raw.githubusercontent.com/leonardssh/vscord/main/assets/icons/idle-vscode.png",
I moved assets to discord art assets

2022-07-21 12:16 UTC, EncryptedDev approved these changes

2022-07-21 16:16 UTC, Bas950 approved these changes

2022-07-21 16:16 UTC, merged