feat(KickAssAnime): added support for search page & replaced strings with multilingual versions
PreMiD/Presences pull request #6462
Opened 2022-07-16 12:05 UTC by StrikerFRFX

## Description 

Title

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![Discord_aJxT4BhbHP](https://user-images.githubusercontent.com/34070194/179354187-6d5ecaa8-85d2-4aa0-85af-13112f8a98cf.png)
![Discord_NxBWz3OtFb](https://user-images.githubusercontent.com/34070194/179354189-c758cafb-2d6e-41f9-b97e-053e62249923.png)
![Discord_Z0w2nAVTMx](https://user-images.githubusercontent.com/34070194/179354190-7614f9f9-a0ce-4529-bba9-488ade8c91e4.png)

</details>

2022-07-16 12:26 UTC, EncryptedDev requested changes

2022-07-16 12:26 UTC, EncryptedDev commented on websites/K/KickAssAnime/dist/metadata.json
> +		"nl": "KickAssAnime is een streamingwebsite waar u tv-series, films en eicellen kunt bekijken in nagesynchroniseerde en subbedformaten.",
@Bas950

2022-07-16 12:26 UTC, EncryptedDev commented on websites/K/KickAssAnime/dist/metadata.json
> +		"ga_IE": "Is suíomh Gréasáin sruthaithe é KickAssAnime inar féidir leat féachaint ar Shraith Teilifíse, ar Scannáin & OVA i bhformáidí a bhfuil dubáil agus fo-leagan orthu."
@callumok2004

2022-07-16 13:13 UTC, StrikerFRFX commented on websites/K/KickAssAnime/dist/metadata.json
> +		"nl": "KickAssAnime is een streamingwebsite waar u tv-series, films en eicellen kunt bekijken in nagesynchroniseerde en subbedformaten.",
translation is unchanged.

2022-07-16 13:30 UTC, joerkig commented on websites/K/KickAssAnime/dist/metadata.json
> +		"nl": "KickAssAnime is een streamingwebsite waar u tv-series, films en eicellen kunt bekijken in nagesynchroniseerde en subbedformaten.",
```suggestion
		"nl": "KickAssAnime is een streamingwebsite waar u tv-series, films en OVA kunt bekijken in nagesynchroniseerde en ondertitelde vorm.",
```

2022-07-16 16:02 UTC, callumok2004 approved these changes

2022-07-18 14:05 UTC, EncryptedDev approved these changes

2022-07-18 14:08 UTC, EncryptedDev requested changes

2022-07-18 14:08 UTC, EncryptedDev commented on websites/K/KickAssAnime/dist/metadata.json
> +	"version": "1.0.22",
Actually should be as below as you added support, hence minor bump
```suggestion
	"version": "1.1.0",
```

2022-07-19 16:38 UTC, EncryptedDev approved these changes

2022-07-20 14:07 UTC, Bas950 approved these changes

2022-07-20 14:07 UTC, merged