feat(Hitbloq): new presence
PreMiD/Presences pull request #6468
Opened 2022-07-19 10:39 UTC by joerkig

## Description 

Added a presence for [Hitbloq](https://hitbloq.com)

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![Discord_P1LdXePUEs](https://user-images.githubusercontent.com/44418429/179730522-2e551dd6-f33d-4718-9e54-7466ce12032c.png)
![Discord_nvLEcQkH4Y](https://user-images.githubusercontent.com/44418429/179730527-a19f3c7d-38da-486c-94b9-92267a48e946.png)
![Discord_67Zv2l73E7](https://user-images.githubusercontent.com/44418429/179730530-065f1e38-60d8-4c52-a7ce-7c69f70e34b8.png)
![Discord_Qf0BXCaxYR](https://user-images.githubusercontent.com/44418429/179730531-40c2667c-6644-49f3-affc-857dfc193265.png)
![Discord_9jk9dzIHiF](https://user-images.githubusercontent.com/44418429/179730532-99553cbe-a5db-444b-a2c5-762700ba5741.png)
![Discord_6ZJPtDHzlu](https://user-images.githubusercontent.com/44418429/179730534-d71f4428-6aa9-4553-82b1-5a3d7ddcaf1a.png)
![Discord_XysCwoCzBe](https://user-images.githubusercontent.com/44418429/179730536-dc85de43-2a71-4bd7-80ef-78eb909bdd06.png)
![JU9MZOsQaF](https://user-images.githubusercontent.com/44418429/179730626-21325eca-0bdf-4b11-b21a-6cafa368e21d.png)
![Discord_wtBSQRAk0d](https://user-images.githubusercontent.com/44418429/179730946-4775ffef-2cb2-4e23-90d3-df210c933151.png)
![Discord_JIu4vD42a7](https://user-images.githubusercontent.com/44418429/179730989-5af6d83e-fd2a-472a-b385-43bdd8849f9a.png)

</details>

2022-07-20 15:02 UTC, EncryptedDev requested changes

2022-07-20 15:02 UTC, EncryptedDev commented on websites/H/Hitbloq/presence.ts
> +			presenceData.details = "Viewing About Us";
```suggestion
			presenceData.details = "Viewing the about us page";
```

2022-07-20 15:10 UTC, joerkig commented on websites/H/Hitbloq/dist/metadata.json
> +	"logo": "https://i.imgur.com/BtSGm7r.png",
Can it not be bigger than 512x512?

2022-07-20 15:53 UTC, joerkig commented on websites/H/Hitbloq/presence.ts
> +			presenceData.details = "Viewing Homepage";
I'll put a space there and change capitalization but I disagree with putting "the" there. There is no "the" anywhere in the general localization file src with 2 minor exceptions, "the" will only cause the line to be longer than they have to be and should not be required, and if the localization file is wrong it should probably be fixed. This same critique also applies to the other suggestions in this PR where "the" was added.

2022-07-23 15:35 UTC, EncryptedDev commented on websites/H/Hitbloq/dist/metadata.json
> +	"logo": "https://i.imgur.com/BtSGm7r.png",
Yikes, misread the size.

2022-07-23 16:07 UTC, EncryptedDev commented on websites/H/Hitbloq/presence.ts
> +			presenceData.details = "Viewing Homepage";
The use of "the" is still preferable here

2022-07-23 16:19 UTC, joerkig commented on websites/H/Hitbloq/presence.ts
> +			presenceData.details = "Viewing Homepage";
😔

2022-07-23 16:56 UTC, joerkig commented on websites/H/Hitbloq/presence.ts
> +			presenceData.details = "Viewing Homepage";
Done 😞

2022-07-24 09:47 UTC, EncryptedDev approved these changes

2022-07-24 10:01 UTC, Bas950 requested changes

2022-07-24 10:01 UTC, Bas950 commented on websites/H/Hitbloq/presence.ts
> +	cover;
just random cover?

2022-07-24 10:03 UTC, joerkig commented on websites/H/Hitbloq/presence.ts
> +	cover;
Oof, left over dev thing

2022-07-24 10:05 UTC, Bas950 approved these changes

2022-07-24 10:05 UTC, merged