refactor(Mega): rewrite & fixes
PreMiD/Presences pull request #6493
Opened 2022-07-22 15:02 UTC by DarkVillager

## Description 

Rewrite the presence for better quality & fix for it to work for everything once again.

## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://user-images.githubusercontent.com/42322979/180467530-7ff0e9a3-37f4-4afd-90df-03f6fb9bbeac.jpg">
<img src="https://user-images.githubusercontent.com/42322979/180467532-65ebdb24-4090-4caa-b282-d93c1e239ca2.jpg">\n<img src="https://user-images.githubusercontent.com/42322979/180467534-a545068a-efdb-41c0-8e55-fec35ee4ab32.jpg">\n<img src="https://user-images.githubusercontent.com/42322979/180467536-88d3f88b-e335-45c9-be3f-34af3cc655f9.jpg">\n<img src="https://user-images.githubusercontent.com/42322979/180467540-bbc98c11-5568-4dfc-8049-d58b47f99f70.jpg">\n<img src="https://user-images.githubusercontent.com/42322979/180467542-31507333-2c20-4cdf-984c-5ed9380ee988.jpg">\n<img src="https://user-images.githubusercontent.com/42322979/180467546-bcd2387c-3b46-4d87-968e-74c32f499ba2.jpg">

</details>

2022-07-23 15:01 UTC, EncryptedDev requested changes
Good PR, just one thing:

2022-07-23 15:01 UTC, EncryptedDev commented on websites/M/MEGA/dist/metadata.json
> +			},
This is a bit of preference, but put this after the value of the setting (L46)

2022-07-26 06:54 UTC, EncryptedDev approved these changes

2022-07-27 14:19 UTC, Bas950 approved these changes

2022-07-27 14:19 UTC, merged

2022-07-27 15:56 UTC, EncryptedDev commented
Cheers for the PR ❤️