chore(HentaiVN): change domain
PreMiD/Presences pull request #6513
Opened 2022-07-26 17:22 UTC by ndbiaw

## Description 

## Acknowledgements
- [ ] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ ] I linted the code by running `yarn format`
- [ ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

2022-07-27 06:35 UTC, EncryptedDev requested changes

2022-07-27 06:35 UTC, EncryptedDev commented on websites/H/HentaiVN/dist/metadata.json
> +	"version": "1.0.4",
```suggestion
	"version": "2.0.0",
```

2022-07-27 16:10 UTC, EncryptedDev approved these changes

2022-07-28 16:56 UTC, Bas950 approved these changes

2022-07-28 16:56 UTC, merged

2022-07-28 21:24 UTC, EncryptedDev commented
Thank you for your contribution 
🚀