feat(Crave): add presence crave
PreMiD/Presences pull request #6551
Opened 2022-07-30 01:00 UTC by Averyyyyyyyy

## Description 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![Presence while on homepage](https://i.imgur.com/ilVIKBI.png)
![Presence while watching The King's Man](https://i.imgur.com/Kg50ZnY.png)
![Presence while watching Euphoria](https://i.imgur.com/wOh7Q1p.png)

</details>

2022-08-02 04:25 UTC, Averyyyyyyyy commented
so is this going to get reviewed 🥺

2022-08-02 21:46 UTC, EncryptedDev reviewed
Hiya 👋🏼

Thank you for contributing to the presence store. I've just noticed a few things found below
- Please use JSDoc where needed and not on simple functions as you've done here
- We would much prefer if you were to create the presences by using if statements and elongate your code (use fewer functions) as currently it is very messy and hard to understand

Drop me a DM if you need some assistance fulfilling this.

2022-08-02 21:46 UTC, EncryptedDev commented on websites/C/Crave/presence.ts
> +						url: document.URL,
```suggestion
						url: document.location.href,
```

2022-08-02 21:46 UTC, EncryptedDev commented on websites/C/Crave/presence.ts
> +	//The client ID of the Application created at https://discordapp.com/developers/applications
```suggestion
```

2022-08-02 21:46 UTC, EncryptedDev commented on websites/C/Crave/presence.ts
> +// Presence
```suggestion
```

2022-08-03 09:42 UTC, Averyyyyyyyy commented
also you might want to label the PR with paid service

2022-08-03 10:02 UTC, Averyyyyyyyy commented
#5284

2022-08-03 11:13 UTC, EncryptedDev requested changes

2022-08-03 11:13 UTC, EncryptedDev commented on websites/C/Crave/presence.ts
> +	if ($(".jw-video") !== null) {
```suggestion
	if ($(".jw-video")) {
```

2022-08-03 11:13 UTC, EncryptedDev commented on websites/C/Crave/presence.ts
> +}
Please do not use a sudo function like so, you can just explicitly write the querySelector at each reference

2022-08-03 11:13 UTC, EncryptedDev commented on websites/C/Crave/presence.ts
> +					$(".jw-text-elapsed").innerHTML
This is preferable
```suggestion
					$(".jw-text-elapsed").textContent
```

2022-08-03 11:13 UTC, EncryptedDev commented on websites/C/Crave/presence.ts
> +		if ($(".bm-icon-episode-list") !== null) {
```suggestion
		if ($(".bm-icon-episode-list")) {
```

2022-08-03 23:49 UTC, EncryptedDev approved these changes

2022-08-06 06:48 UTC, Bas950 approved these changes

2022-08-06 06:49 UTC, merged