feat(Lookmovies): domains and cover
PreMiD/Presences pull request #6553
Opened 2022-07-30 07:34 UTC by DarkVillager

## Description 

Changed the domains and added an extra one due to the old one not working anymore

## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://user-images.githubusercontent.com/42322979/181880153-81e775fa-1935-480a-9f98-784704cc04a0.png">
<img src="https://user-images.githubusercontent.com/42322979/181880154-1c7675e7-1ce6-4517-8b47-72a6c0de4c80.png">
<img src="https://user-images.githubusercontent.com/42322979/181880156-a17dd67e-5ae3-4d8b-9807-5c09f52e2248.png">
<img src="https://user-images.githubusercontent.com/42322979/181880157-56374ad8-a4c2-4b50-a7cc-4bfeeabaaefc.png">
<img src="https://user-images.githubusercontent.com/42322979/181880160-845d3ee9-6476-4fef-9243-7bbc70c8e5d8.png">
<img src="https://user-images.githubusercontent.com/42322979/181880148-80b4c5ca-d206-457a-991c-1b444e41263e.png">

</details>

2022-07-30 22:51 UTC, EncryptedDev requested changes

2022-07-30 22:51 UTC, EncryptedDev commented on websites/L/LookMovie/presence.ts
> +	if (video && video.duration) {
```suggestion
	if (video?.duration) {
```

2022-07-30 22:51 UTC, EncryptedDev commented on websites/L/LookMovie/presence.ts
> +		presenceData.details = titles;
```suggestion
		presenceData.details =
			document.querySelector('[class="bd-hd"]')?.textContent ??
			document.querySelector<HTMLMetaElement>('meta[property="og:title"]')
				?.content ??
			document
				.querySelector("head > title")
				?.textContent.replace(" | LookMovie", "");
```

2022-08-02 21:48 UTC, EncryptedDev approved these changes

2022-08-06 06:45 UTC, Bas950 approved these changes

2022-08-06 06:45 UTC, merged