feat(Discord ID): add presence
PreMiD/Presences pull request #6563
Opened 2022-07-31 07:51 UTC by DarkVillager

## Description 

Added presence for Discord.id

## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://user-images.githubusercontent.com/42322979/182015718-ad19e767-3f97-4c2a-8207-b8c6cf9f3e2c.png">
<img src="https://user-images.githubusercontent.com/42322979/182015719-a9999c99-da7b-471f-a936-da8f1332fb60.png">
<img src="https://user-images.githubusercontent.com/42322979/182015721-fa8f35bd-e7a2-470d-aade-3c85517259dd.png">
<img src="https://user-images.githubusercontent.com/42322979/182015722-3779afa5-8048-4586-b45f-88027f5e8832.png">

</details>

2022-07-31 08:06 UTC, nerrixDE commented
privacy concerns
~ Owner of discord.id

2022-07-31 13:08 UTC, DarkVillager commented
> privacy concerns ~ Owner of discord.id
New default:
![image](https://user-images.githubusercontent.com/42322979/182027949-7b86c1d6-3e2b-47f3-8395-322d6ef2e9c8.png)

2022-07-31 18:26 UTC, nerrixDE commented
good

2022-07-31 19:47 UTC, EncryptedDev requested changes

2022-07-31 19:47 UTC, EncryptedDev commented on websites/D/Discord ID/dist/metadata.json
> +		"en": "Lookup for all type of discord ids."
```suggestion
		"en": "Lookup a Discord User or Bot ID."
```

2022-08-01 21:01 UTC, EncryptedDev approved these changes

2022-08-02 11:43 UTC, Bas950 approved these changes

2022-08-02 11:43 UTC, merged