feat(CDKeys): buttons, cover & refactor
PreMiD/Presences pull request #6568
Opened 2022-07-31 13:53 UTC by DarkVillager

## Description 

Added buttons, cover & refactored

## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://user-images.githubusercontent.com/42322979/182029521-6d228a98-d388-42e2-a04b-3e78fd74c8e1.png">
<img src="https://user-images.githubusercontent.com/42322979/182029524-b0504023-6312-4cb4-82af-50e7659bbdf9.png">
<img src="https://user-images.githubusercontent.com/42322979/182029526-074a385c-14d6-4b5a-b141-5a1ce9513f19.png">
<img src="https://user-images.githubusercontent.com/42322979/182029527-f9dd5241-21e8-47e3-bcc5-44c823237088.png">

</details>

2022-07-31 19:49 UTC, EncryptedDev requested changes

2022-07-31 19:49 UTC, EncryptedDev commented on websites/C/CDKeys/presence.ts
> +				label: "View procuct series",
Typo

2022-07-31 19:49 UTC, EncryptedDev commented on websites/C/CDKeys/presence.ts
> +				label: "View game",
Buttons should use Title Case

2022-08-01 21:10 UTC, EncryptedDev commented on websites/C/CDKeys/presence.ts
> +				label: "View game",
This has not been resolved fully

2022-08-02 07:37 UTC, DarkVillager commented on websites/C/CDKeys/presence.ts
> +				label: "View game",
> This has not been resolved fully

Oh i see

2022-08-02 09:42 UTC, EncryptedDev approved these changes

2022-08-02 11:51 UTC, Bas950 approved these changes

2022-08-02 11:51 UTC, merged