fix(jut.su): change app id
PreMiD/Presences pull request #6576
Opened 2022-08-01 09:11 UTC by DarkVillager

## Description 

Resolves #6569
## Acknowledgements
- [ ] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ ] I linted the code by running `yarn format`
- [ ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://user-images.githubusercontent.com/42322979/182114852-7d6676a3-dcfb-4bba-a2b6-5fcbbc2700d3.png">

</details>

2022-08-01 09:48 UTC, RisingSunLight42 commented
Well, okay xD
I should use draft PR mord often when I plan doing something after few days if someone doesn't respond lol

2022-08-01 20:23 UTC, EncryptedDev requested changes

2022-08-01 20:23 UTC, EncryptedDev commented on websites/J/jut.su/dist/metadata.json
> +	"version": "1.1.0",
Should be a major bump as you changed the Client ID 
```suggestion
	"version": "2.0.0",
```

2022-08-01 20:25 UTC, EncryptedDev commented
As the issue was opened fairly recently and the GitHub user still exists, there is still a chance to recieve a response from the OP. This should be kept as a draft for at least a week to make sure of this.

2022-08-02 10:59 UTC, Syjalo requested changes

2022-08-02 10:59 UTC, Syjalo commented on websites/J/jut.su/dist/metadata.json
>  	"description": {
```json
"ru": "Jut.su — это русский сайт аниме"
```

2022-08-02 10:59 UTC, Syjalo commented on websites/J/jut.su/presence.ts
> +			presenceData.smallImageText = "Игра";
```suggestion
			presenceData.smallImageText = "Воспроизводится";
```

2022-08-02 10:59 UTC, Syjalo commented on websites/J/jut.su/presence.ts
> +	} else if (title) presenceData.details = `Просмотр ${title.textContent}`;
```suggestion
	} else if (title) presenceData.details = `Смотрит «${title.textContent}»`;
```

2022-08-02 10:59 UTC, Syjalo commented on websites/J/jut.su/presence.ts
> +		presenceData.state = search.value;
```suggestion
		presenceData.details = "Ищет по запросу";
		presenceData.state = `«${search.value}»`;
```

2022-08-02 14:20 UTC, Syjalo approved these changes

2022-08-02 14:25 UTC, EncryptedDev approved these changes

2022-08-02 14:26 UTC, Bas950 approved these changes

2022-08-02 14:26 UTC, merged