feat(000webhost): add privacy & perf
PreMiD/Presences pull request #6582
Opened 2022-08-02 11:55 UTC by DarkVillager

## Description 

Added privacy mode & did some small style changes

## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://user-images.githubusercontent.com/42322979/182368486-c19c9b9a-9da3-442e-ba93-a522b6ebfe89.jpg">
<img src="https://user-images.githubusercontent.com/42322979/182368490-06eaf227-c788-4a08-b418-5e66baf7c5c8.jpg">

</details>

2022-08-02 21:39 UTC, EncryptedDev requested changes

2022-08-02 21:39 UTC, EncryptedDev commented on websites/0-9/000webhost/presence.ts
> +			"#nav-container > div > div.sidebar__header.flex.flex-col > a.sidebar-header__app-link.text-color-white.text-bold.disabled-link.sidebar-header__app-link--disabled > span"
Any possibility to shorten this?

2022-08-02 21:39 UTC, EncryptedDev commented on websites/0-9/000webhost/presence.ts
> +		presenceData.details = "Viewing cheap webhosting";
```suggestion
		presenceData.details = "Viewing webhosting";
```

2022-08-03 23:50 UTC, EncryptedDev approved these changes

2022-08-06 06:49 UTC, Bas950 approved these changes

2022-08-06 06:49 UTC, merged