fix(animepahe): fix getStrings constantly call
PreMiD/Presences pull request #6586
Opened 2022-08-02 20:13 UTC by RisingSunLight42

## Description 

Resolves #6584 by redoing the getStrings() function in the presence file, the check to avoid useless calls to it was missing.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![animepahe_proof_1](https://user-images.githubusercontent.com/85577959/182464465-84e8fb3e-384f-4168-8a31-e53787d266b6.PNG)

![animepahe_proof_3](https://user-images.githubusercontent.com/85577959/182464507-e59aafad-77d4-43a8-b95f-b413f54b3431.PNG)

![animepahe_proof_2](https://user-images.githubusercontent.com/85577959/182464543-d773be7d-a91c-4453-85de-b3ffdb8c57f2.PNG)

</details>

2022-08-02 20:16 UTC, RisingSunLight42 commented
I've just edited the presence to fix this problem, but I think the code is a bit messy and not really maintanable/maybe too much complicated. Maybe someone should do a recoding of it.

2022-08-02 21:23 UTC, EncryptedDev requested changes

2022-08-02 21:23 UTC, EncryptedDev commented on websites/A/animepahe/presence.ts
> +	clientId: "629355416714739732", // Contact if you want me to edit the discord assets/keys/whatever
```suggestion
	clientId: "629355416714739732",
```

2022-08-02 21:38 UTC, EncryptedDev approved these changes

2022-08-03 07:56 UTC, DarkVillager approved these changes

2022-08-06 06:46 UTC, Bas950 approved these changes

2022-08-06 06:46 UTC, merged