feat(Yahoo Mail): add privacy mode & more details
PreMiD/Presences pull request #6598
Opened 2022-08-05 09:41 UTC by DarkVillager

## Description 

 Ddd privacy mode & more details even when using privacy mode
 
## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://user-images.githubusercontent.com/42322979/183050329-0c82640d-70bd-43f0-ac57-56a94d75d86b.jpg">
<img src="https://user-images.githubusercontent.com/42322979/183050334-3cd7c076-f6c4-4827-b3f2-6cf505ee1081.jpg"><img src="https://user-images.githubusercontent.com/42322979/183050336-19ece097-16a4-4460-b197-05138e0ae2f7.jpg"><img src="https://user-images.githubusercontent.com/42322979/183050337-bdd5e828-e36f-4fbe-a7da-a590f7f79c14.jpg"><img src="https://user-images.githubusercontent.com/42322979/183050338-d4251681-79d5-43e0-9eea-1386cbc04c23.jpg">

</details>

2022-08-06 12:15 UTC, EncryptedDev requested changes

2022-08-06 12:15 UTC, EncryptedDev commented on websites/Y/Yahoo Mail/presence.ts
> +				presenceData.details = "Viewing an Email";
```suggestion
				presenceData.details = "Viewing an email";
```

2022-08-06 12:15 UTC, EncryptedDev commented on websites/Y/Yahoo Mail/presence.ts
> +			else presenceData.details = "Viewing Mail";
```suggestion
			else presenceData.details = "Viewing mail";
```

2022-08-07 22:09 UTC, EncryptedDev approved these changes

2022-08-09 14:36 UTC, Bas950 approved these changes

2022-08-09 14:36 UTC, merged