feat(Videoland): buttons, cover & privacy settings
PreMiD/Presences pull request #6621
Opened 2022-08-08 12:40 UTC by DarkVillager

## Description 

Added buttons, cover & privacy settings & refactor of the old code

## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://user-images.githubusercontent.com/42322979/183420217-061c7b10-9cb8-4f03-9bb9-27f69d3942b7.jpg">
<img src="https://user-images.githubusercontent.com/42322979/183420225-09b9c16f-5c93-4014-9706-34fa7a2f6930.jpg"><img src="https://user-images.githubusercontent.com/42322979/183420228-bda406a5-c7a5-4876-9149-23a9770026cc.jpg">

</details>

2022-08-10 21:15 UTC, EncryptedDev approved these changes

2022-08-10 21:15 UTC, EncryptedDev commented
@Bas950 also check for lang strings

2022-08-11 06:52 UTC, Bas950 requested changes

2022-08-11 06:52 UTC, Bas950 commented on websites/V/Videoland/presence.ts
> +				presenceData.details = "Bekijkt Tv Programma's";
Doe gewoon de t en p in kleine letters

2022-08-11 06:52 UTC, Bas950 commented on websites/V/Videoland/presence.ts
> +						label: "Bekijk Tv Programma's",
Hier ook

2022-08-11 06:52 UTC, Bas950 commented on websites/V/Videoland/presence.ts
> +						label: "Bekijk Video",
Kleine v

2022-08-11 06:52 UTC, Bas950 commented on websites/V/Videoland/presence.ts
> +						label: "Bekijk Series",
Kleine s

2022-08-11 06:52 UTC, Bas950 commented on websites/V/Videoland/presence.ts
> +						label: "Bekijk Serie",
Hier ook kleine s

2022-08-11 06:52 UTC, Bas950 commented on websites/V/Videoland/presence.ts
> +						label: "Bekijk Film",
Kleine f

2022-08-11 08:21 UTC, DarkVillager commented on websites/V/Videoland/presence.ts
> +						label: "Bekijk Video",
Nee title case?

2022-08-11 08:21 UTC, DarkVillager commented on websites/V/Videoland/presence.ts
> +						label: "Bekijk Series",
Title case?

2022-08-11 08:21 UTC, DarkVillager commented on websites/V/Videoland/presence.ts
> +						label: "Bekijk Serie",
Title case?

2022-08-11 08:21 UTC, DarkVillager commented on websites/V/Videoland/presence.ts
> +						label: "Bekijk Film",
Title case?

2022-08-11 08:21 UTC, DarkVillager commented on websites/V/Videoland/presence.ts
> +						label: "Bekijk Tv Programma's",
Title case?

2022-08-11 13:31 UTC, Bas950 approved these changes

2022-08-11 13:32 UTC, merged