feat(Dutch Descriptions): translate the new presence descriptions
PreMiD/Presences pull request #6637
Opened 2022-08-11 11:34 UTC by DarkVillager

## Description 

Adding the rest of the dutch description as of now.

## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

Does not apply in this context

</details>

2022-08-13 07:48 UTC, Bas950 requested changes
Denk dat @QkeleQ10 hier beter naar kan kijken lol

2022-08-13 07:48 UTC, Bas950 commented on websites/#/Фугапедия/dist/metadata.json
> +		"nl": "Encyclopedie over de League van Cubism en de server van het universum van SC. Lees veel coole artikelen en schrijf je eigen artikelen, als aanvulling op de meest giftige encyclopedie."
Weet niet of "giftige" het beste is... @QkeleQ10

2022-08-13 07:48 UTC, Bas950 commented on websites/#/대성마이맥/dist/metadata.json
> +		"nl": "Digital Daesung is het vooraanstaande Koreaanse onderwijsbedrijf dat onderwijsinhoud van de hoogste kwaliteit levert. Het bedrijf biedt totale onderwijsdiensten aan basisschool-, middelbare
`basisschool-, middelbare school- en universiteitstudenten,`
basisschool en middelbare ben je niet echt student maar scholier.

en `van online en offline colleges tot toetsen,`
colleges is volgens mij niet het beste heirvoor... @QkeleQ10

2022-08-13 07:48 UTC, Bas950 commented on websites/0-9/10fastfingers/dist/metadata.json
> +		"nl": "Test & Verbeter uw typesnelheid met onze gratis Typespellen"
```suggestion
		"nl": "Test en verbeter uw typsnelheid met onze gratis typspellen"
```

2022-08-13 07:48 UTC, Bas950 commented on websites/A/AMC+/dist/metadata.json
> +		"nl": "Award winnende shows en fan favoriete films - AMC+ is uw bestemming voor genre-bepalende verhaal vertelling. Zonder advertenties en On Demand met elke week nieuwe shows en films."
`Award winnende shows en fan favoriete films - AMC+ is uw bestemming voor genre-bepalende verhaal vertelling.`
@QkeleQ10 Hier zitten denk ik meerdere fouten in.

`Zonder advertenties en On Demand met elke week nieuwe shows en films.`
Misschien is dit beter:
`Advertentievrij en on-demand met elke week nieuwe shows en films.`

2022-08-13 07:48 UTC, Bas950 commented on websites/A/ARD Mediathek/dist/metadata.json
> +		"nl": "ARD Mediathek is een gedeelde video-on-demand streamingdienst die door de Duitse openbare omroep sector van ARD wordt aangeboden."
```suggestion
		"nl": "ARD Mediathek is een gedeelde video-on-demand streamingdienst die door de Duitse publieke omroep van ARD wordt aangeboden."
```

2022-08-15 12:43 UTC, QkeleQ10 requested changes
Didn't correct every single thing, as it just was way too much to look over. Looks fine

wat een kutklus

2022-08-15 12:43 UTC, QkeleQ10 commented on websites/D/Discord Resources/dist/metadata.json
> +		"nl": "Een lijst van tonnen nuttige Discord bronnen en hulpprogramma's voor alle soorten gebruikers, van beginners tot power users."
```suggestion
		"nl": "Een grote lijst van nuttige Discord-bronnen en -hulpprogramma's voor alle soorten gebruikers: van beginners tot powerusers."
```

2022-08-15 12:43 UTC, QkeleQ10 commented on websites/F/Flightradar24/dist/metadata.json
> +		"nl": "'S werelds meest populaire vlucht tracker. Volg vliegtuigen in real-time op onze vlucht tracker kaart en krijg up-to-date vluchtstatusen & luchthaveninformatie."
```suggestion
		"nl": "'s Werelds meest populaire vluchttracker. Volg vliegtuigen in real-time op onze vluchtenkaart en krijg up-to-date vluchtstatussen & luchthaveninformatie."
```

2022-08-15 12:43 UTC, QkeleQ10 commented on websites/G/GAMEE/dist/metadata.json
> +		"nl": "Speel spelletjes, krijg tickets en WIN $$$. Hoe meer tickets, meer kansen om te WINNEN!\""
```suggestion
		"nl": "Speel spelletjes, krijg tickets en WIN $$$. Hoe meer tickets, meer kansen om te WINNEN!"
```

2022-08-15 12:43 UTC, QkeleQ10 commented on websites/G/Genshin Impact Map/dist/metadata.json
> +		"nl": "Genshin Impact Interactieve kaart van alle locaties, locaties beschrijvingen gidsen en meer."
```suggestion
		"nl": "Genshin Impact's interactieve kaart met alle locaties, locatiebeschrijvingen, gidsen en meer."
```
This English description is a mess

2022-08-15 12:43 UTC, QkeleQ10 commented on websites/G/Google Play/dist/metadata.json
> +		"nl": "Geniet van miljoenen van de nieuwste Android apps, games, muziek, films, TV, boeken, tijdschriften & meer."
```suggestion
		"nl": "Geniet van miljoenen Android-apps, games, muziek, films, TV, boeken, tijdschriften & meer."
```

2022-08-15 12:43 UTC, QkeleQ10 commented on websites/G/Google's Coding Competitions/dist/metadata.json
> +		"nl": "Google's codeerwedstrijden (Code Jam, Hash Code en Kick Start) boeien, dagen uit en testen programmeurs van over de hele wereld. Probeer er een te spelen, of alle drie."
```suggestion
		"nl": "Google's codeerwedstrijden (Code Jam, Hash Code en Kick Start) boeien en testen programmeurs van over de hele wereld en dagen ze uit. Probeer er een te spelen, of alle drie."
```

2022-08-15 12:51 UTC, DarkVillager commented
> Didn't correct every single thing, as it just was way too much.
> 
> wat een kutklus

Je mag ooi deze pr overnemen

2022-08-17 12:13 UTC, DarkVillager commented on websites/A/Animekimi/dist/metadata.json
> -		"vi_VN": "Xem những anime mới nhất trực tuyến có phụ đề và thuyết minh Tiếng Thái."
Not sure if this is accurate anymore due to changing the English one.

2022-08-17 12:14 UTC, DarkVillager commented on websites/K/Kayoanime/dist/metadata.json
> +		"en": "Kayoanime is a website where you can download anime in 1080p with dual audio through Google drive.",
Grammar sounded off

2022-08-17 12:16 UTC, QkeleQ10 approved these changes

2022-08-18 11:40 UTC, DarkVillager commented on websites/N/namu.wiki/dist/metadata.json
> +		"en": "\"namuwiki, The tree of knowledge that nurtures you.\" namuwiki(나무위키) is a Korean language wiki based on \"the seed\" engine.",
typo fixed

2022-08-18 11:40 UTC, DarkVillager commented on websites/N/Notion/dist/metadata.json
> +		"en": "Notion software are used for note-taking, task management, project management, knowledge management, and personal knowledge management. The app uses databases and markdown pages for use in p
Old one seemed weird

2022-08-25 11:15 UTC, DarkVillager commented on websites/P/padlet/dist/metadata.json
> +		"nl": "Van je hobby tot je carrière, van je aantekeningen tot je eindexamen, van je stemmingsbord tot je catwalkshow, padlets helpen je je leven te organiseren."
@QkeleQ10

2022-08-25 11:16 UTC, DarkVillager commented on websites/P/paimon.moe/dist/metadata.json
> +		"en": "Your best Genshin Impact companion! Help you plan what to farm with ascension calculator, also track your progress with a todo and wish counter.",
Sounded off without the a

2022-09-03 09:02 UTC, EncryptedDev commented
Any update here or should I close the PR until you're done?

2022-09-03 09:27 UTC, DarkVillager commented
> Any update here or should I close the PR until you're done?

I’ll be pushing a commit today

2022-09-08 12:22 UTC, closed without merging

2022-09-08 12:22 UTC, DarkVillager commented
I will come back to this when I can.