feat(JoJo's Bizarre Encyclopedia): add new presence
PreMiD/Presences pull request #6652
Opened 2022-08-12 23:26 UTC by wavpro

## Description 
Added new presence for JoJo's Bizarre Encyclopedia (jojowiki.com and jojo-news.com). It displays activity on the mentioned sites.

## Acknowledgements
- [X ] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X ] I linted the code by running `yarn format`
- [X ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![Screenshot](https://user-images.githubusercontent.com/31097540/184456148-6a188669-d767-403e-8e16-bf780e4fb1d2.jpg)  
![Screenshot](https://user-images.githubusercontent.com/31097540/184456168-25bd57b7-7175-485d-9706-7217737be872.png)  
![Screenshot](https://user-images.githubusercontent.com/31097540/184456302-9130f3ee-c66e-4b9f-b320-a4ebd0a734e1.jpg)  
![Screenshot](https://user-images.githubusercontent.com/31097540/184456383-f771ed09-f1f9-43b7-87a2-478e07f26bf5.jpg)  

</details>

2022-08-12 23:29 UTC, wavpro commented
It seems to fail checks because of other presences, not mine. Github says my fork was fully up to date, can someone check this out?

2022-08-12 23:33 UTC, EncryptedDev commented
CI failed on your PR because you edited the presence. Delete the changes

2022-08-12 23:55 UTC, wavpro commented
> CI failed on your PR because you edited the presence. Delete the changes

How do I remove it from the pull request? It doesn't help editing since nothing has changed from the old version, just that there's a commit that says it's changed. I don't know why this happened, I didn't see these files included when committing.

2022-08-13 01:05 UTC, RisingSunLight42 commented
> > CI failed on your PR because you edited the presence. Delete the changes
> 
> How do I remove it from the pull request? It doesn't help editing since nothing has changed from the old version, just that there's a commit that says it's changed. I don't know why this happened, I didn't see these files included when committing.

Those files are from your yarn format, those two files has a little format errors that make them change when you run the commande.
Rollback you commits to fix that

2022-08-13 09:12 UTC, wavpro commented
I've fixed the formatting error

2022-08-13 10:09 UTC, Bas950 commented
Undo the packagejson and yarnlock too

2022-08-13 11:53 UTC, wavpro commented
> Undo the packagejson and yarnlock too

Done

2022-08-13 23:22 UTC, EncryptedDev commented
> > Undo the packagejson and yarnlock too
> 
> Done

Nope, `package.lock` and `yarn.lock` are still on this PR

2022-08-13 23:23 UTC, wavpro commented
How would I remove them completely from the PR? I have made sure they're
exactly the same as currently in the repo.

On Sun, Aug 14, 2022, 1:22 AM Rhys Rakoff ***@***.***> wrote:

> Undo the packagejson and yarnlock too
>
> Done
>
> Nope, package.lock and yarn.lock are still on this PR
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/PreMiD/Presences/pull/6652#issuecomment-1214245328>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHNIFRBGU64D4IC75R3Y4DLVZAU4HANCNFSM56NEC26Q>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-08-14 07:57 UTC, Bas950 requested changes

2022-08-14 07:57 UTC, Bas950 commented on websites/J/JoJo's Bizarre Encyclopedia/presence.ts
> +			smallImageKey: "wiki_icon",
please use imgur links

2022-08-14 07:57 UTC, Bas950 commented on websites/J/JoJo's Bizarre Encyclopedia/presence.ts
> +			smallImageKey: "news_icon_bordered",
same here

2022-08-14 13:40 UTC, Bas950 approved these changes

2022-08-16 02:01 UTC, EncryptedDev approved these changes

2022-08-16 02:01 UTC, merged