feat(Mystera Legacy): add presence
PreMiD/Presences pull request #6682
Opened 2022-08-21 15:45 UTC by luckycdev

## Description 

New Presence for [Mystera Legacy](https://mysteralegacy.com)
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![Image 1](http://cdn.e-z.host/e-zimagehosting/3dc483d6-0f73-445d-bc8a-0f7e441dac0b/lzzht5es.png)

![Image 2](https://cdn.e-z.host/e-zimagehosting/3dc483d6-0f73-445d-bc8a-0f7e441dac0b/iuks86wg.png)

</details>

2022-08-21 15:52 UTC, RisingSunLight42 requested changes
logo and thumbnail links are not imgur links. Should be imgur.

2022-08-21 15:56 UTC, luckycdev commented
> logo and thumbnail links are not imgur links. Should be imgur.

fixed

2022-08-21 15:58 UTC, RisingSunLight42 reviewed
Seems a bit low quality for me. There's not dynamic feature used.

2022-08-21 15:58 UTC, RisingSunLight42 commented on websites/M/Mystera Legacy/presence.ts
> +			"https://play-lh.googleusercontent.com/zS3Zi_4PltspasItG2tP2pQujLW6PcR_hGYUy8uMzOEbiWOkS_vlewFcHrn4gVtawCM",
```suggestion
			"https://i.imgur.com/XBaHzfF.png",
```

2022-08-21 16:13 UTC, RisingSunLight42 commented
Don't forget to run prettier.

2022-08-22 08:42 UTC, DarkVillager requested changes

2022-08-22 08:42 UTC, DarkVillager commented on websites/M/Mystera Legacy/presence.ts
> +		presenceData.details = "Becoming a Supporter";
maybe use a variable like this and you could use a switch statement

`const { pathname } = document.location`

2022-08-22 08:45 UTC, DarkVillager requested changes

2022-08-22 08:45 UTC, DarkVillager commented on websites/M/Mystera Legacy/presence.ts
> +	//Update the presence with no data, therefore clearing it and making the large image the Discord Application icon, and the text the Discord Application name
This comment is unnecesary, it's already clear enough without it.
```suggestion
```

2022-08-25 21:12 UTC, closed without merging