feat(Deno): rewrite & more functions with settings
PreMiD/Presences pull request #6685
Opened 2022-08-22 11:23 UTC by DarkVillager

## Description 

Rewrote the presence: 
- Added more domains
- Added settings
- Easier maintainability
## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://user-images.githubusercontent.com/42322979/185909888-589222dc-cedd-43c1-8774-448f4f422591.jpg">
<img src="https://user-images.githubusercontent.com/42322979/185909893-caee19de-d1f5-4ac7-9325-3bf271b26c1e.jpg"><img src="https://user-images.githubusercontent.com/42322979/185909894-3af10dbe-c54c-411b-a895-40d07cd155e0.jpg"><img src="https://user-images.githubusercontent.com/42322979/185909898-a3fef27a-900f-45e2-b084-189522ca1a41.jpg"><img src="https://user-images.githubusercontent.com/42322979/185909901-53952700-d1e0-413a-a9f6-560048bb2060.jpg"><img src="https://user-images.githubusercontent.com/42322979/185909903-1932eaa9-1bab-42da-a299-ac86d659d500.jpg"><img src="https://user-images.githubusercontent.com/42322979/185909906-9de900ba-429a-4345-b824-799d2a62e625.jpg">

</details>

2022-08-22 21:56 UTC, EncryptedDev requested changes

2022-08-22 21:56 UTC, EncryptedDev commented on websites/D/Deno/presence.ts
> +					label: "Read The Docs",
```suggestion
					label: "View Docs",
```

2022-08-22 21:56 UTC, EncryptedDev commented on websites/D/Deno/presence.ts
> +							label: "Read Blog",
```suggestion
							label: "View Blog",
```

2022-08-24 11:11 UTC, Bas950 requested changes

2022-08-24 11:11 UTC, Bas950 commented on websites/D/Deno/presence.ts
> +		return;
You probs want to call set activity tho

2022-08-24 12:02 UTC, RisingSunLight42 requested changes

2022-08-24 12:02 UTC, RisingSunLight42 commented on websites/D/Deno/presence.ts
> +		if (presenceData.details) presence.setActivity(presenceData);
```suggestion
		presence.setActivity(presenceData);
```
Useless if since you're setting a string just before, so the if is always true.

2022-08-25 11:52 UTC, Bas950 approved these changes

2022-08-25 12:11 UTC, RisingSunLight42 approved these changes

2022-08-25 21:22 UTC, EncryptedDev approved these changes

2022-08-25 21:22 UTC, merged