fix(Discord): dm username
PreMiD/Presences pull request #6686
Opened 2022-08-22 13:41 UTC by DarkVillager

## Description 

Resolves #6684
## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://user-images.githubusercontent.com/42322979/185935306-744b104e-4f08-4ca3-a12b-fdf58b8638bf.jpg">
<img src="https://user-images.githubusercontent.com/42322979/185935312-4a62d4a6-2582-4681-b49c-66b298a46030.jpg"><img src="https://user-images.githubusercontent.com/42322979/185935316-d0647344-bf94-4e8f-8619-9a3ec3ebaa27.jpg">

</details>

2022-08-22 14:44 UTC, RisingSunLight42 requested changes
Replace every `(await strings)` by `strings`, since the function getString() is already awaited.

2022-08-22 21:53 UTC, EncryptedDev reviewed
Seems a little strange to have the change you staged. In my eyes, if it is `undefined` it shouldn't be displayed until the username exists - just add an if to see if the value equal to `undefined` instead

2022-08-23 09:11 UTC, DarkVillager commented
> Seems a little strange to have the change you staged. In my eyes, if it is `undefined` it shouldn't be displayed until the username exists - just add an if to see if the value equal to `undefined` instead

Will fix

2022-08-25 21:13 UTC, EncryptedDev approved these changes

2022-08-26 05:02 UTC, Bas950 approved these changes

2022-08-26 05:02 UTC, merged