Cortex Duo - Premid
PreMiD/Presences pull request #6702
Opened 2022-08-27 20:51 UTC by Roxza

## Description 
A service that lets you talk to AI and others anonymously.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![Ekran Resmi 2022-08-27 23 44 30](https://user-images.githubusercontent.com/39166624/187047427-dc84415a-62d6-4ede-900e-43f9fad34e6e.png)
![Ekran Resmi 2022-08-27 23 46 39](https://user-images.githubusercontent.com/39166624/187047449-f0cf0ca9-bcf8-4bed-8adf-0fe0fb10c8b1.png)

</details>

2022-08-27 21:21 UTC, RisingSunLight42 requested changes
Remove duplicate version in metadata, resolve checks, remove the js file and make a better presence. The current one is really poor.

2022-08-28 08:01 UTC, DarkVillager commented on websites/C/Cortex Duo/dist/metadata.json
> +	"version": "25.08.22",
what

2022-08-28 08:02 UTC, DarkVillager requested changes

2022-08-28 08:02 UTC, DarkVillager commented on websites/C/Cortex Duo/dist/presence.js
> +});
Dont include this

2022-08-28 08:02 UTC, DarkVillager commented on websites/C/Cortex Duo/presence.ts
> +	}
More pages otherwise the presence is too low quality.

2022-08-29 16:01 UTC, DarkVillager commented
@Roxza Maybe acutally use visual studio code so you can format the code?

2022-08-31 09:28 UTC, DarkVillager requested changes

2022-08-31 09:28 UTC, DarkVillager commented on websites/C/Cortex Duo/presence.ts
> +  if (window.location.pathname.toLowerCase() === "/") {
```suggestion
  if (pathname === "/") {
```

2022-08-31 09:28 UTC, DarkVillager commented on websites/C/Cortex Duo/presence.ts
> +      presenceData.state = "cortexduo.com";
If you want them to go the site just add a button.
```suggestion
```

2022-08-31 09:28 UTC, DarkVillager commented on websites/C/Cortex Duo/presence.ts
> +      presenceData.state = "cortexduo.com";
Same as above
```suggestion
```

2022-08-31 09:28 UTC, DarkVillager commented on websites/C/Cortex Duo/presence.ts
> +      presenceData.state = "cortexduo.com";
Same as above
```suggestion
```

2022-08-31 09:28 UTC, DarkVillager commented on websites/C/Cortex Duo/presence.ts
> +      presenceData.state = "cortexduo.com";
Same as above
```suggestion
```

2022-08-31 09:28 UTC, DarkVillager commented on websites/C/Cortex Duo/presence.ts
> +    presenceData.state = "cortexduo.com";
Same as above
```suggestion
```

2022-08-31 09:28 UTC, DarkVillager commented on websites/C/Cortex Duo/presence.ts
> +    largeImageKey: "logo",
```suggestion
    largeImageKey: "https://i.imgur.com/iTS3Dcq.png",
```

2022-08-31 09:36 UTC, EncryptedDev commented
Mark conversations as resolved as you've completed them

2022-09-03 08:28 UTC, EncryptedDev commented
Hello 👋🏼 

Unfortunately, I believe this PR is low quality as it doesn't offer many features/functions on the presence itself. You could think about adding dynamic features and a more hollistic website-compatability

2022-09-03 08:28 UTC, closed without merging