feat(MarineTraffic): add presence
PreMiD/Presences pull request #6708
Opened 2022-08-28 13:38 UTC by Lulucmy

## Description 
Adding presence for MarineTraffic.com

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![DiscordPTB_guMD7GMHbj](https://user-images.githubusercontent.com/20552095/187076704-e5d76bea-0c35-435f-9513-23c2b0edd7b2.png)

![DiscordPTB_agth2saRRy](https://user-images.githubusercontent.com/20552095/187076707-cf7cfe78-2cee-407c-bee6-0fe97c9613fa.png)
</details>

2022-08-30 11:34 UTC, DarkVillager requested changes

2022-08-30 11:34 UTC, DarkVillager commented on websites/M/MarineTraffic/dist/metadata.json
> +		"marinetraffic.com",
It redirects to the www one
```suggestion
```

2022-08-30 16:34 UTC, EncryptedDev commented on websites/M/MarineTraffic/presence.ts
> +	(s && s[0].toUpperCase() + s.slice(1)) || "";
Use `charAt()` instead of using indexes
```suggestion
const capitalize = (s: string) =>
	(s && s[0].toUpperCase() + s.slice(1)) || "";
```

2022-08-31 09:14 UTC, DarkVillager commented on websites/M/MarineTraffic/presence.ts
> +		details: "Viewing:",
@EncryptedDev no **:** right?

2022-08-31 09:14 UTC, DarkVillager commented on websites/M/MarineTraffic/presence.ts
> +		presenceData.details = "Reading a blog post:";
Same here right @EncryptedDev

2022-08-31 09:22 UTC, DarkVillager commented on websites/M/MarineTraffic/presence.ts
> +				)
Try to get shorter selectors like this one:
![image](https://user-images.githubusercontent.com/42322979/187644710-4de11c0d-0e81-4294-87d9-48be3c77cbf4.png)
```suggestion
			document
				.querySelector(
					'[href*="/en/ais/details/ships/shipid:"]'
				)
```

2022-08-31 09:22 UTC, DarkVillager commented on websites/M/MarineTraffic/presence.ts
> +			"#infosnippet_container > div > div > div > div:nth-child(2) > div > div:nth-child(1) > div > strong"
![image](https://user-images.githubusercontent.com/42322979/187644665-cec56221-059f-4d38-b56d-e01623acb6ca.png)
```suggestion
			'[class="infowin-genericinfo1-cell"]'
```

2022-08-31 09:22 UTC, DarkVillager commented on websites/M/MarineTraffic/presence.ts
> +						"#infosnippet_container > div > div > div > div:nth-child(2) > div > div > div.d-flex.align-items-center.justify-content-start.flex-wrap.flex-1-1-auto > div:nth-child(1) > div > span > a"
![image](https://user-images.githubusercontent.com/42322979/187645296-40a53d65-546a-46ff-b330-2f57efed7056.png)
```suggestion
						'[class="departure-arrival-label"]'
```

2022-08-31 09:24 UTC, DarkVillager requested changes

2022-08-31 09:24 UTC, DarkVillager commented on websites/M/MarineTraffic/presence.ts
> +		).innerHTML;
![image](https://user-images.githubusercontent.com/42322979/187645820-42c63a7c-3478-4438-bc70-57cee2955a23.png)
```suggestion
		shipStatus = document.querySelector(
			'[class="infowin-genericinfo1-cell"]'
		).firstElementChild.textContent;
```

2022-08-31 09:33 UTC, DarkVillager requested changes

2022-08-31 09:33 UTC, DarkVillager commented on websites/M/MarineTraffic/presence.ts
> +				.innerHTML.toLowerCase()
Try to get shorter selectors like this one:
![image](https://user-images.githubusercontent.com/42322979/187644710-4de11c0d-0e81-4294-87d9-48be3c77cbf4.png)
```suggestion
			document
				.querySelector(
					'[href*="/en/ais/details/ships/shipid:"]'
				).textContent.toLowerCase()
```

2022-08-31 09:38 UTC, DarkVillager requested changes

2022-08-31 09:38 UTC, DarkVillager commented on websites/M/MarineTraffic/presence.ts
> +					.split("&country=")[0]
```suggestion
				document
					.querySelector<HTMLAnchorElement>(
						'[href*="/en/ais/details/ports/"]'
					)
					.href.split("?name=")[1]
					.split("&country=")[0]
```

2022-08-31 09:40 UTC, DarkVillager requested changes

2022-08-31 09:40 UTC, DarkVillager commented on websites/M/MarineTraffic/presence.ts
> +			"#app > div > div.jss2 > div.d-flex.align-items-start.justify-content-start.flex-1-1-auto.home-layout > div.d-flex.flexcol.align-items-start.justify-content-start.flex-wrap.flex-1-1-auto > div > d
```suggestion
			'[src*="https://photos.marinetraffic.com/ais/showphoto.aspx?"]'
```

2022-08-31 09:43 UTC, DarkVillager commented on websites/M/MarineTraffic/presence.ts
> +		largeImageKey: "logo",
We prefer imgur links for maintainablity
```suggestion
		largeImageKey: "https://i.imgur.com/u2NmdZX.png",
```

2022-09-02 16:34 UTC, RisingSunLight42 commented on websites/M/MarineTraffic/presence.ts
> +		details: "Viewing:",
Since Encrypted just thumbsuped x')
```suggestion
		details: "Viewing",
```

2022-09-02 16:35 UTC, RisingSunLight42 commented on websites/M/MarineTraffic/presence.ts
> +		presenceData.details = "Reading a blog post:";
Same, Encrypted thumbsup
```suggestion
		presenceData.details = "Reading a blog post";
```

2022-09-03 08:43 UTC, EncryptedDev reviewed
Please shorten all the query selectors where possible, but I'm sure they can all be shorter

2022-09-03 13:30 UTC, Kozou4ever commented on websites/M/MarineTraffic/dist/metadata.json
> +		"fr": "MarineTraffic est un site web permettant de suivre en temps réel le trafic maritime mondial."
All good here

2022-09-04 09:03 UTC, RisingSunLight42 requested changes
I've didn't check all the queries, but I can confirm all of them can be shortened if you dig a bit.
Also, I suggest you to create a variable `href` to avoid multiple repetitions of `document.location.href`. You can also do this for pathname, hostname, and all stuff you use from `document.location`.

2022-09-04 23:57 UTC, EncryptedDev commented
Resolve CI

2022-09-08 04:27 UTC, Kaushik9371 approved these changes
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "http://www.wapforum.org/DTD/xhtml-mobile10.dtd"><html lang="en" xmlns="http://www.w3.org/1999/xhtml"><head><title>Page Not Found</title><meta name="referrer" content="default" id="meta_referrer" /><style type="text/css" nonce="uYgsfXPn">/*<![CDATA[*/.r{background-color:#fff;border-bottom:1px solid;border-color:#ebedf0;padding:5px 8px 23px 8px;text-align:center;}.s{padding:20px;}.t{text-align:center;}.v{appearance:none;background:none;display:inline-block;font-size:12px;height:28px;line-height:28px;margin:0;overflow:visible;padding:0 9px;text-align:center;vertical-align:top;white-space:nowrap;}.b .v{border-radius:2px;}.z,.bk,a.z,a.bk,html .b a.z,html .b a.bk{color:#fff;}.b .bk{background-color:#4080ff;border:1px solid #4476e8;}.b a.bk:hover,.b .bk:hover{background-color:#4580ef;}.b .z{background-color:#4267b2;border:1px solid #365899;}.b a.z:hover,.b .z:hover{background-color:#465e91;}.z[disabled]{color:#899bc1;}.bk[disabled]{color:#91b4fd;}.b .z[disabled]:hover{background-color:#4267b2;}.b .bk[disabled]:hover{background-color:#4080ff;}.v .bb{display:inline-block;}.b .v .bb{display:inline-block;margin-top:0;vertical-align:middle;}.b a.v::after{content:"";display:inline-block;height:100%;vertical-align:middle;}.v .bb{line-height:20px;margin-top:4px;}.b .v{padding:0 8px;}.b a.v{height:26px;line-height:26px;}.bb{pointer-events:none;}.b a,.b a:visited{color:#3b5998;text-decoration:none;}.b .inv,.b .inv:visited{color:#fff;}.b a:focus,.b a:hover{background-color:#3b5998;color:#fff;}.b .inv:focus,.b .inv:hover{background-color:#fff;color:#3b5998;}.ba{font-weight:normal;}.bd{height:20px;}.be{border-bottom:1px solid #ccd0d5;height:10px;text-align:center;width:100%;}.bf{color:#4b4f56;font-size:12px;line-height:20px;padding:0 10px;}.bg{background-color:#fff;}body{text-align:left;direction:ltr;}body,tr,input,textarea,button{font-family:sans-serif;}body,p,figure,h1,h2,h3,h4,h5,h6,ul,ol,li,dl,dd,dt{margin:0;padding:0;}h1,h2,h3,h4,h5,h6{font-size:1em;font-weight:bold;}ul,ol{list-style:none;}article,aside,figcaption,figure,footer,header,nav,section{display:block;}.d{background:#f5f6f7;}#page{position:relative;}.h{background-color:#3b5998;color:#fff;}.h ._4-i4{font-size:small;font-weight:normal;}.n{display:block;padding:5px;}._2xzg{background:#6d84b4;display:inline-block;font-size:14px;font-weight:normal;margin:4px 0;padding:2px 8px;}.b .i{border:0;border-collapse:collapse;margin:0;padding:0;width:100%;}.b .i tbody{vertical-align:top;}.b .j>tr>td,.b .j>tbody>tr>td,.b .i td.j{vertical-align:middle;}.b .i td{padding:0;}.b .q{width:100%;}.o,.o.p{display:block;}.l{display:block;}.m{height:20px;width:20px;}.p{border:0;display:inline-block;vertical-align:top;}i.p u{position:absolute;width:0;height:0;overflow:hidden;}body,tr,input,textarea,.e{font-size:medium;}/*]]>*/</style><meta property="og:title" content="Log in or sign up to view" /><meta property="og:description" content="See posts, photos and more on Facebook." /><link rel="manifest" id="MANIFEST_LINK" href="/data/manifest/" crossorigin="use-credentials" /></head><body tabindex="0" class="b c d"><div class="e"><div id="viewport"><div class="f g" id="MChromeHeader"><a href="/a/preferences.php?basic_site_devices=m_basic&sr_link=1&uri=https%3A%2F%2Fm.facebook.com%2Fhome.php&gfid=AQCAynpBKmWC4_yoa5w" tabindex="-1" style="clip: rect(1px, 1px, 1px, 1px);height: 1px;overflow: hidden;position: absolute;white-space: nowrap;width: 1px;"> </a><div class="h" id="header"><table class="i j" align="center"><tbody><tr><td class="k"><a class="l m n" href="/home.php?ref_component=mbasic_home_logo&ref_page=%2Fflib%2Finit%2Fzeusgodofthunder%2F__entrypoint.php"><img src="https://static.xx.fbcdn.net/rsrc.php/v3/yt/r/9ZKKP6NpzIr.png" width="20" height="20" class="o p" alt="Facebook logo" /></a></td><td class="q"><span>...<h1 class="_4-i4"><a href="/home.php" class="_2xzg inv">Go To Home</a></h1></span></td></tr></tbody></table></div></div><div id="objects_container"><div class="d" id="root"><div class="r"><div class="s">Join Facebook or log in to continue.</div><div class="t"><a href="/r.php?next=https%3A%2F%2Fm.facebook.com%2Flogin%2Fsonakshi.ahlawat.58&cid=104" class="u v w x y z ba" id="u_0_0_xW"><span class="bb">Join</span></a><div class="bc"><div class="bd"><div class="be"><span class="bf bg">or</span></div></div></div><a href="https://m.facebook.com/login.php?next=https%3A%2F%2Fm.facebook.com%2Flogin%2Fsonakshi.ahlawat.58&ref=104&refsrc=deprecated" class="u v bh bi bj bk ba" id="u_0_1_YM"><span class="bb">Log In</span></a></div></div><div style="display:none"></div><span><img src="https://facebook.com/security/hsts-pixel.gif?c=3.2" width="0" height="0" style="display:none" /></span></div></div></div></div></body></html>

2022-09-10 22:52 UTC, closed without merging