feat(War Thunder): add presence
PreMiD/Presences pull request #6746
Opened 2022-09-02 19:48 UTC by theusaf

## Description 
Creates a new presence for War Thunder websites (wiki, tournaments, mods, etc.)

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<img width="227" alt="2022-09-02 12_44_47" src="https://user-images.githubusercontent.com/32113157/188226330-41359712-f3ce-4031-8429-b5e8743cface.png">
<img width="224" alt="2022-09-02 12_34_24" src="https://user-images.githubusercontent.com/32113157/188226334-47743ccf-9368-4530-9d32-a2de689c901e.png">
<img width="225" alt="2022-09-02 12_34_35" src="https://user-images.githubusercontent.com/32113157/188226336-e06c025a-180b-4584-ad76-adbdd1303dcb.png">
<img width="230" alt="2022-09-02 12_38_11" src="https://user-images.githubusercontent.com/32113157/188226339-fcfadbb9-b286-43c0-ac1a-590906507712.png">
<img width="228" alt="2022-09-02 12_38_24" src="https://user-images.githubusercontent.com/32113157/188226342-ed229646-1304-4f33-9bfb-babaf708d9b6.png">
<img width="225" alt="2022-09-02 12_38_34" src="https://user-images.githubusercontent.com/32113157/188226343-43ba34fe-7b4e-4bcf-8a93-2e9c28df1083.png">
<img width="229" alt="2022-09-02 12_39_24" src="https://user-images.githubusercontent.com/32113157/188226345-0fce4d61-7a7b-4e07-9db0-c79d2b12067a.png">
<img width="229" alt="2022-09-02 12_39_51" src="https://user-images.githubusercontent.com/32113157/188226346-9484a430-8157-4663-8055-3e1fe3bc6c07.png">
<img width="225" alt="2022-09-02 12_40_11" src="https://user-images.githubusercontent.com/32113157/188226347-a48928e4-3558-4adc-b38e-e486a07b8731.png">
<img width="227" alt="2022-09-02 12_40_33" src="https://user-images.githubusercontent.com/32113157/188226349-dae85072-27ea-4cbe-9673-b084f83c2e3c.png">
<img width="227" alt="2022-09-02 12_40_57" src="https://user-images.githubusercontent.com/32113157/188226351-636a17eb-fdba-4320-865f-54222c3e9904.png">
<img width="222" alt="2022-09-02 12_41_55" src="https://user-images.githubusercontent.com/32113157/188226352-9f316459-556a-4daa-bd7e-6212748d0a65.png">
<img width="229" alt="2022-09-02 12_42_11" src="https://user-images.githubusercontent.com/32113157/188226354-fa0288d1-9b04-4546-8e83-d5f30852b4c1.png">
<img width="228" alt="2022-09-02 12_42_18" src="https://user-images.githubusercontent.com/32113157/188226357-8912ac2e-4872-4441-a044-749098b7ff63.png">
<img width="228" alt="2022-09-02 12_42_43" src="https://user-images.githubusercontent.com/32113157/188226359-5123eda5-1624-427f-9786-454a432103c4.png">
<img width="225" alt="2022-09-02 12_43_10" src="https://user-images.githubusercontent.com/32113157/188226361-b34afa7f-82cd-4369-8c21-a6a89ffda851.png">
<img width="228" alt="2022-09-02 12_43_24" src="https://user-images.githubusercontent.com/32113157/188226363-4e2365ce-a283-4532-8b14-79271e000d4d.png">
<img width="225" alt="2022-09-02 12_43_46" src="https://user-images.githubusercontent.com/32113157/188226367-67b75001-5e5d-4dfb-a65e-2afa215a5c27.png">
<img width="239" alt="2022-09-02 12_43_53" src="https://user-images.githubusercontent.com/32113157/188226370-9010435f-8f52-4168-bc8d-11d7c0aa44bb.png">
<img width="226" alt="2022-09-02 12_44_31" src="https://user-images.githubusercontent.com/32113157/188226372-3a709f43-1d55-4a15-8c15-3281174ad2fb.png">
<img width="230" alt="2022-09-02 12_44_40" src="https://user-images.githubusercontent.com/32113157/188226373-2bfe837c-dee5-46e5-80e2-ad13c1898f2b.png">
</details>

2022-09-03 07:53 UTC, DarkVillager commented on websites/W/War Thunder/presence.ts
> +						url: `https://${hostname}${pathname}`,
user href

2022-09-03 07:54 UTC, DarkVillager commented on websites/W/War Thunder/presence.ts
> +							url: `https://${hostname}${pathname}${search}`,
Use href

2022-09-03 07:55 UTC, DarkVillager requested changes
href?

2022-09-03 07:59 UTC, DarkVillager requested changes

2022-09-03 07:59 UTC, DarkVillager commented on websites/W/War Thunder/presence.ts
> +	if (presenceData.details) presence.setActivity(presenceData);
```suggestion
	if (presenceData.details) presence.setActivity(presenceData);
	else presence.setActivity();
```

2022-09-03 08:15 UTC, DarkVillager requested changes

2022-09-03 08:15 UTC, DarkVillager commented on websites/W/War Thunder/dist/metadata.json
> +		"en": "Next-Gen MMO Combat Game for PC, Mac, Linux and PlayStation®4"
![image](https://user-images.githubusercontent.com/42322979/188262269-54da0802-729e-423c-94a0-0c23ebd9d690.png)
```suggestion
		"en": "War Thunder is a free-to-play vehicular combat multiplayer video game developed and published by Gaijin Entertainment."
```

2022-09-07 20:28 UTC, EncryptedDev approved these changes

2022-09-08 17:27 UTC, Bas950 approved these changes

2022-09-08 17:27 UTC, merged