fix(Instagram): profile element changed
PreMiD/Presences pull request #6749
Opened 2022-09-03 12:03 UTC by DarkVillager

## Description 

Changed the profile element and changed the way it's used due to different formats
## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://user-images.githubusercontent.com/42322979/188269622-6c0ca240-fb74-4269-ba97-f5ec08ad6437.jpg">
<img src="https://user-images.githubusercontent.com/42322979/188269624-1a8e3a53-6b64-4a43-8458-55417ed9f0a4.jpg">

</details>

2022-09-03 19:40 UTC, EncryptedDev commented on websites/I/Instagram/presence.ts
> +		} (${profileName[1].split(")")[0]})`;
Why remove the `@`

2022-09-03 19:45 UTC, DarkVillager commented on websites/I/Instagram/presence.ts
> +		} (${profileName[1].split(")")[0]})`;
its already present in the new element

2022-09-04 09:19 UTC, EncryptedDev approved these changes

2022-09-04 09:25 UTC, Bas950 requested changes

2022-09-04 09:25 UTC, Bas950 commented on websites/I/Instagram/presence.ts
> +		profileName = document.title.split("(");
```suggestion
		[,profileName] = document.title.split("(");
```

2022-09-04 09:25 UTC, Bas950 commented on websites/I/Instagram/presence.ts
> +	else if (profileName[1].split(")")[0].replace("@", "") === path[1]) {
```suggestion
	else if (profileName.split(")")[0].replace("@", "") === path[1]) {
```

2022-09-04 09:25 UTC, Bas950 commented on websites/I/Instagram/presence.ts
> +		} (${profileName[1].split(")")[0]})`;
```suggestion
		} (${profileName.split(")")[0]})`;
```

2022-09-04 16:31 UTC, Bas950 approved these changes

2022-09-04 16:31 UTC, merged