feat(Toyhouse): add presence
PreMiD/Presences pull request #6752
Opened 2022-09-03 16:04 UTC by RisingSunLight42

## Description 

Add a new presence for the website "Toyhouse".

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![toyhouse_proof_1](https://user-images.githubusercontent.com/85577959/188278800-4bf929fa-bb03-4d0a-b7e1-ad4c15b58371.PNG)

![toyhouse_proof_2](https://user-images.githubusercontent.com/85577959/188278802-f5f9fedd-a3ef-4ad8-af58-a0d5a885d212.PNG)

![toyhouse_proof_3](https://user-images.githubusercontent.com/85577959/188278799-d4d1b143-5a2d-4b60-bccc-ecee6874561c.PNG)
</details>

2022-09-03 19:45 UTC, EncryptedDev approved these changes

2022-09-03 19:45 UTC, EncryptedDev requested changes

2022-09-03 19:45 UTC, EncryptedDev commented on websites/T/Toyhouse/presence.ts
> +		"~account": "Managing its account",
```suggestion
		"~account": "Managing their account",
```

2022-09-04 23:52 UTC, EncryptedDev approved these changes

2022-09-05 18:07 UTC, Bas950 approved these changes

2022-09-05 18:07 UTC, merged