feat(Anime Sama): add presence
PreMiD/Presences pull request #6766
Opened 2022-09-07 20:27 UTC by RisingSunLight42

## Description 

Add new presence

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![animesama_proof_7](https://user-images.githubusercontent.com/85577959/188970656-31c80c34-2458-4a3d-b12b-7c489636f207.PNG)

![animesama_proof_6](https://user-images.githubusercontent.com/85577959/188970657-40dfc3be-e463-4f1b-8ba9-a2b5e7fcbba2.PNG)

![animesama_proof_5](https://user-images.githubusercontent.com/85577959/188970662-83d04961-6cf6-4951-b1c2-8f57cbaa4115.PNG)

![animesama_proof_4](https://user-images.githubusercontent.com/85577959/188970665-ccec7d31-fa04-4056-9447-7ca9cf9f35e9.PNG)

![animesama_proof_3](https://user-images.githubusercontent.com/85577959/188970666-6b520fd1-060b-4c80-91ba-5021a866f00c.PNG)

![animesama_proof_2](https://user-images.githubusercontent.com/85577959/188970668-29a88bf1-9a42-4b7c-8292-7140c94bb9b7.PNG)

![animesama_proof_1](https://user-images.githubusercontent.com/85577959/188970648-0fa7eea9-8434-445e-9a5e-087fd4a36843.PNG)
</details>

2022-09-08 21:25 UTC, EncryptedDev requested changes

2022-09-08 21:25 UTC, EncryptedDev commented on websites/A/Anime Sama/iframe.ts
> +	if (video && !isNaN(video.duration)) {
```suggestion
	if (!isNaN(video?.duration)) {
```

2022-09-09 16:34 UTC, Kozou4ever requested changes
Hi, you made a small spelling mistake that I pointed it out in the thread ;)

2022-09-09 16:34 UTC, Kozou4ever commented on websites/A/Anime Sama/presence.ts
> +		planning: "Regarde le planing des sorties",
```suggestion
		planning: "Regarde le planning des sorties",
```

2022-09-10 10:53 UTC, Kozou4ever approved these changes

2022-09-10 23:06 UTC, EncryptedDev approved these changes

2022-09-11 11:38 UTC, Bas950 approved these changes

2022-09-11 11:38 UTC, merged