feat(CritiqueBrainz): add presence
PreMiD/Presences pull request #6776
Opened 2022-09-09 16:57 UTC by theusaf

## Description 
Adds a presence for CritiqueBrainz.
This PR is a part of #5460

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img width="226" alt="2022-09-09 09_52_21" src="https://user-images.githubusercontent.com/32113157/189402129-aa08dae0-10b4-4fa5-bd71-5f4e0fda24f1.png">
<img width="225" alt="2022-09-09 09_53_47" src="https://user-images.githubusercontent.com/32113157/189402133-1a414169-4b74-4d27-b40e-c55a383ca310.png">
<img width="230" alt="2022-09-09 09_44_58" src="https://user-images.githubusercontent.com/32113157/189402135-610a69ba-9448-4f1d-9a88-cc65f076517b.png">
<img width="230" alt="2022-09-09 09_45_10" src="https://user-images.githubusercontent.com/32113157/189402136-c2174140-32d8-4ab6-8955-2bdf083b3a06.png">
<img width="221" alt="2022-09-09 09_45_23" src="https://user-images.githubusercontent.com/32113157/189402137-132fb3d2-76ac-47f3-8066-1d28789c70de.png">
<img width="227" alt="2022-09-09 09_45_40" src="https://user-images.githubusercontent.com/32113157/189402138-496acd39-77f5-494a-920c-9a4e9cd55bd4.png">
<img width="231" alt="2022-09-09 09_46_24" src="https://user-images.githubusercontent.com/32113157/189402142-d328edf3-0365-44b3-9dce-056b4b3baa5a.png">
<img width="225" alt="2022-09-09 09_46_45" src="https://user-images.githubusercontent.com/32113157/189402143-940bcb49-782e-4dba-a807-85a69b26f443.png">
<img width="227" alt="2022-09-09 09_49_15" src="https://user-images.githubusercontent.com/32113157/189402144-0d4328d0-8347-42bc-ad64-d8345a59a91c.png">
<img width="219" alt="2022-09-09 09_50_12" src="https://user-images.githubusercontent.com/32113157/189402148-24cb8f71-37ac-4f50-91d6-779fffd3e5a5.png">
<img width="221" alt="2022-09-09 09_50_20" src="https://user-images.githubusercontent.com/32113157/189402149-bc2e22e3-4c11-4ee8-a16d-aebd48b9e2da.png">
<img width="222" alt="2022-09-09 09_50_26" src="https://user-images.githubusercontent.com/32113157/189402154-43141375-759e-43b8-8b7c-42296420137a.png">
<img width="225" alt="2022-09-09 09_50_36" src="https://user-images.githubusercontent.com/32113157/189402155-b5d7f9cd-e2a4-4a7e-bc92-bcd32c4e4c2d.png">
<img width="222" alt="2022-09-09 09_51_04" src="https://user-images.githubusercontent.com/32113157/189402158-77731a96-2c40-498a-8a14-b581f3854baa.png">
<img width="227" alt="2022-09-09 09_51_13" src="https://user-images.githubusercontent.com/32113157/189402160-35ceaee3-6857-4b9b-be32-95a97d333594.png">
<img width="226" alt="2022-09-09 09_51_37" src="https://user-images.githubusercontent.com/32113157/189402161-d34bbe1a-d377-4c0e-9867-ed05eb41f7c1.png">
<img width="223" alt="2022-09-09 09_51_44" src="https://user-images.githubusercontent.com/32113157/189402163-525990e2-b681-49ac-8ffd-9b106da6d75c.png">

</details>

2022-09-10 23:09 UTC, EncryptedDev approved these changes

2022-09-11 11:17 UTC, DarkVillager requested changes

2022-09-11 11:17 UTC, DarkVillager commented on websites/C/CritiqueBrainz/presence.ts
> +						if (image) presenceData.largeImageKey = image.src;
```suggestion
presenceData.largeImageKey = document.querySelector<HTMLImageElement>(".cover-art")?.src ?? Assets.Logo;
```

2022-09-11 11:17 UTC, DarkVillager commented on websites/C/CritiqueBrainz/presence.ts
> +
```suggestion
enum Assets {
	Logo = "https://i.imgur.com/LG31f5s.png",
}

```

2022-09-11 11:17 UTC, DarkVillager commented on websites/C/CritiqueBrainz/presence.ts
> +			largeImageKey: "https://i.imgur.com/LG31f5s.png",
```suggestion
			largeImageKey: "Assets.Logo",
```

2022-09-11 17:35 UTC, EncryptedDev commented on websites/C/CritiqueBrainz/presence.ts
> +
Not needed for one asset

2022-09-12 13:34 UTC, EncryptedDev requested changes

2022-09-13 05:25 UTC, DarkVillager commented on websites/C/CritiqueBrainz/presence.ts
> +						if (image) presenceData.largeImageKey = image.src;
@theusaf unresolved.

2022-09-15 21:07 UTC, EncryptedDev approved these changes

2022-09-16 13:20 UTC, Bas950 approved these changes

2022-09-16 13:20 UTC, merged