feat(e-z): add presence
PreMiD/Presences pull request #6782
Opened 2022-09-11 20:59 UTC by tsoxas

## Description 
Adding presence for e-z.host and e-z.bio

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
![image](https://user-images.githubusercontent.com/78205449/189548582-35274089-c0ef-40bf-96ce-d9b8b37784ed.png)
![image](https://user-images.githubusercontent.com/78205449/189548592-0252cbd7-b9a7-41a8-ab8c-cd33a992fca5.png)
![image](https://user-images.githubusercontent.com/78205449/189548603-f87de748-f193-4273-b267-c635c6325506.png)

</details>

2022-09-11 22:34 UTC, theusaf requested changes

2022-09-11 22:34 UTC, theusaf commented on websites/E/e-z/presence.ts
> +			];
buttons to homepages are [not allowed](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#presencets).
```suggestion
```

2022-09-11 22:34 UTC, theusaf commented on websites/E/e-z/presence.ts
> +				];
buttons to homepages are [not allowed](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#presencets).
```suggestion
```

2022-09-11 22:34 UTC, theusaf commented on websites/E/e-z/presence.ts
> +					},
buttons to homepages are [not allowed](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#presencets).
```suggestion
```

2022-09-11 22:34 UTC, theusaf commented on websites/E/e-z/dist/metadata.json
> +	"service": "E-Z",
Rename the folder. Helpful [Stackoverflow question](https://stackoverflow.com/questions/6899582/i-change-the-capitalization-of-a-directory-and-git-doesnt-seem-to-pick-up-on-it).

2022-09-11 22:34 UTC, theusaf commented on websites/E/e-z/dist/metadata.json
> +	"thumbnail": "https://cdn.e-z.host/e-zimagehosting/e-z_host_banner.png",
Use Imgur. Also, logos must have a [minimum resolution of 512x512px](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#logo).

2022-09-12 13:29 UTC, DarkVillager requested changes

2022-09-12 13:29 UTC, DarkVillager commented on websites/E/e-z/presence.ts
> +						url: `https://e-z.bio${document.location.pathname}`,
```suggestion
						url: document.location.href,
```

2022-09-12 13:31 UTC, DarkVillager requested changes

2022-09-12 13:31 UTC, DarkVillager commented on websites/E/e-z/presence.ts
> +	switch (document.location.hostname) {
Use variables for this.
[Example of the right variables.](https://github.com/PreMiD/Presences/commit/958d5b80733887427f412471048b9614390e1fb7#diff-adb2cc91e493add5ee896439dcca4f8073c1cda9b686816134ca8910eba6c8acR24)

2022-09-13 05:27 UTC, DarkVillager commented
@tsoxas mark changes as resolved when you’ve done them

2022-09-13 05:49 UTC, tsoxas commented
> @tsoxas mark changes as resolved when you’ve done them 

Done. Let me know if there are any more changes needed

2022-09-13 09:33 UTC, DarkVillager requested changes

2022-09-13 09:33 UTC, DarkVillager commented on websites/E/e-z/presence.ts
> +			largeImageKey: "https://cdn.e-z.host/e-zimagehosting/ez256.png",
```suggestion
			largeImageKey: "https://i.imgur.com/Crfg6sn.png",
```

2022-09-15 21:10 UTC, EncryptedDev requested changes

2022-09-15 21:10 UTC, EncryptedDev commented on websites/E/e-z/presence.ts
> +					];
This is forbidden 
![image](https://user-images.githubusercontent.com/64903135/190509072-6f679009-e659-423f-ac06-f9a9bb65ae20.png)

2022-09-15 21:10 UTC, EncryptedDev commented on websites/E/e-z/presence.ts
> +			if (typeof username !== "undefined" && typeof uid !== "undefined") {
```suggestion
			if (username && uid) {
```

2022-09-16 04:51 UTC, ignSKRRRTT commented
"1 review requesting changes by reviewers with write access" but it doesn't say which check it is. All the checks have been resolved

2022-09-16 20:14 UTC, EncryptedDev approved these changes

2022-09-22 18:30 UTC, Bas950 approved these changes

2022-09-22 20:10 UTC, EncryptedDev commented
Resolve CI so this can be merged

2022-09-24 09:35 UTC, tsoxas commented
@EncryptedDev I fixed the checks failing

2022-09-24 10:13 UTC, merged