feat(FreeWater): add presence
PreMiD/Presences pull request #6785
Opened 2022-09-14 09:26 UTC by CodesWithJames

## Description 

## Acknowledgements
- [✓] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [✓] I linted the code by running `yarn format`
- [✓] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots

![image](https://user-images.githubusercontent.com/71551059/190115760-52fee3f2-75c1-42fa-b68d-80ecc207f8a3.png)
![image](https://user-images.githubusercontent.com/71551059/190115813-55fbe7c3-f88a-464c-bd54-5223ad7bcbfa.png)
![image](https://user-images.githubusercontent.com/71551059/190115968-95de33cb-3caf-4621-9362-3eb82af26aba.png)

2022-09-15 13:37 UTC, DarkVillager commented
> * [✓] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
> * [✓] I linted the code by running `yarn format`
> * [✓] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)
Just change the checkmars to the letter X

2022-09-15 15:06 UTC, CodesWithJames commented
Thank you

2022-09-15 16:46 UTC, theusaf requested changes
Also, resolve CI.

2022-09-15 16:46 UTC, theusaf commented on websites/F/FreeWater/dist/metadata.json
> +	"version": "0.0.1",
```suggestion
	"version": "1.0.0",
```

2022-09-15 21:33 UTC, CodesWithJames commented on websites/F/FreeWater/dist/metadata.json
> +	  "sv": "FreeWater är en markandsförings plattform som använder premium källvatten som en ny marknadsföringsmedium."
I checked the docs, and they are.

2022-09-16 11:06 UTC, CodesWithJames commented on websites/F/FreeWater/presence.ts
> +        smallImageKey: "reading",
Okay

2022-09-16 11:58 UTC, RisingSunLight42 commented
Fix errors : 
Images links are supposed to be imgur links. Plus, a language given doesn't exist, please check those errors.

2022-09-16 20:16 UTC, EncryptedDev commented
Low quality presence

2022-09-16 20:16 UTC, closed without merging