feat(5Mods): recoded presence with settings
PreMiD/Presences pull request #6793
Opened 2022-09-16 12:06 UTC by DarkVillager

## Description 

Recoded the whole presence & added new features with their respective settings
## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://user-images.githubusercontent.com/42322979/190635126-fad0cb51-e4b3-4786-b9c6-e1fd630d05a0.jpg">
<img src="https://user-images.githubusercontent.com/42322979/190635131-f3d3f483-bf01-4545-ac12-4f074027ce37.jpg"><img src="https://user-images.githubusercontent.com/42322979/190635133-be5dfb8a-6429-4716-98d8-345f4f83491e.jpg"><img src="https://user-images.githubusercontent.com/42322979/190635135-32491e43-9ea1-4306-b999-87793936e1ca.jpg"><img src="https://user-images.githubusercontent.com/42322979/190635137-5836d15a-49f3-4331-98c3-7111673ee9be.jpg"><img src="https://user-images.githubusercontent.com/42322979/190635139-bb730c48-d119-4bd4-b210-fba5c4b25408.jpg"><img src="https://user-images.githubusercontent.com/42322979/190635140-0a17b3e8-b321-4646-bf50-a82ae1318baf.jpg"><img src="https://user-images.githubusercontent.com/42322979/190635141-0b4784fe-3f59-4d84-98ea-afb221751963.jpg"><img src="https://user-images.githubusercontent.com/42322979/190635143-e854f8b5-7c66-4544-adef-bb4d17102193.jpg"><img src="https://user-images.githubusercontent.com/42322979/190635144-40cc6389-4f5d-4b6c-af66-04e8f088acf2.jpg">

</details>

2022-09-16 20:16 UTC, EncryptedDev requested changes

2022-09-16 20:16 UTC, EncryptedDev commented on websites/0-9/5Mods/presence.ts
> +		return;
```suggestion
		return presence.setActivity(presenceData);
```

2022-09-16 20:21 UTC, EncryptedDev approved these changes

2022-09-24 07:13 UTC, Bas950 approved these changes

2022-09-24 07:13 UTC, merged