feat: add pmd cli
PreMiD/Presences pull request #6797
Opened 2022-09-17 15:45 UTC by Timeraa

This pr adds pmd.

2022-09-17 15:55 UTC, Timeraa commented
Please ignore the Schema Validation Check, there is no need to bump the versions as nothing codewise changed.

2022-09-17 23:22 UTC, alexbcberio requested changes

2022-09-17 23:22 UTC, alexbcberio commented on README.md
> +        <img  src="https://discordapp.com/api/guilds/493130730549805057/widget.png?style=banner2" height="75px" draggable="false" alt="Join our Discord!">
Banner height is 76px
```suggestion
        <img  src="https://discordapp.com/api/guilds/493130730549805057/widget.png?style=banner2" height="76px" draggable="false" alt="Join our Discord!">
```

2022-09-18 13:11 UTC, Bas950 approved these changes

2022-09-18 14:24 UTC, EncryptedDev approved these changes

2022-09-18 14:24 UTC, merged