feat(Polywork): add presence
PreMiD/Presences pull request #6801
Opened 2022-09-18 17:44 UTC by Yeikzy

## Description 

Adding presence for https://polywork.com

## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

2022-09-19 11:11 UTC, DarkVillager commented
Also for you include screenshots

2022-09-22 20:05 UTC, EncryptedDev commented
Run `npm run format`

2022-09-23 21:56 UTC, Yeikzy commented
> npm run format

```js
error TS2468: Cannot find global value 'Promise'.

tsconfig.json:4:13 - error TS6046: Argument for '--target' option must be: 'es3', 'es5', 'es6', 'es2015', 'es2016', 'es2017', 'es2018', 'es2019', 'es2020', 'es2021', 'esnext'.

4   "target": "ES2022",
              ~~~~~~~~

util/tools/auto/presenceUpdater.ts:3:49 - error TS2307: Cannot find module '@babel/core' or its corresponding type declarations.

3 import { transformFileAsync as transform } from "@babel/core";
                                                  ~~~~~~~~~~~~~

util/tools/auto/presenceUpdater.ts:5:30 - error TS7016: Could not find a declaration file for module 'glob'. 'C:/Users/bejie/node_modules/glob/glob.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/glob` if it exists or add a new declaration (.d.ts) file containing `declare module 'glob';`

5 import { sync as glob } from "glob";
                               ~~~~~~

util/tools/auto/presenceUpdater.ts:12:8 - error TS2307: Cannot find module 'mongodb' or its corresponding type declarations.

12 } from "mongodb";
          ~~~~~~~~~

util/tools/auto/presenceUpdater.ts:13:57 - error TS2307: Cannot find module 'node:fs' or its corresponding type declarations.

13 import { existsSync, readFileSync, writeFileSync } from "node:fs";
                                                           ~~~~~~~~~

util/tools/auto/presenceUpdater.ts:14:47 - error TS2307: Cannot find module 'node:path' or its corresponding type declarations.

14 import { join, normalize, resolve, sep } from "node:path";
                                                 ~~~~~~~~~~~

util/tools/auto/presenceUpdater.ts:15:23 - error TS2307: Cannot find module 'semver' or its corresponding type declarations.

15 import { valid } from "semver";
                         ~~~~~~~~

util/tools/auto/presenceUpdater.ts:16:34 - error TS2307: Cannot find module 'terser' or its corresponding type declarations.

16 import { minify as terser } from "terser";
                                    ~~~~~~~~

util/tools/auto/presenceUpdater.ts:26:13 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.   

26 const url = process.env.MONGO_URL,
               ~~~~~~~

util/tools/auto/presenceUpdater.ts:38:5 - error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.

38  ): Promise<void> => {
       ~~~~~~~~~~~~~

util/tools/auto/presenceUpdater.ts:61:33 - error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.

61  minify = async (file: string): Promise<void> => {
                                   ~~~~~~~~~~~~~

util/tools/auto/presenceUpdater.ts:74:35 - error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.

74  polyfill = async (file: string): Promise<void> => {
                                     ~~~~~~~~~~~~~

util/tools/auto/presenceUpdater.ts:86:46 - error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.

86  compile = async (filesToCompile: string[]): Promise<void> => {
                                                ~~~~~~~~~~~~~

util/tools/auto/presenceUpdater.ts:88:5 - error TS2304: Cannot find name '__dirname'.

88     __dirname,
       ~~~~~~~~~

util/tools/auto/presenceUpdater.ts:95:15 - error TS2304: Cannot find name '__dirname'.

95    }>(resolve(__dirname, "../../../tsconfig.json"));
                 ~~~~~~~~~

util/tools/auto/presenceUpdater.ts:115:19 - error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.

115  main = async (): Promise<void> => {
                      ~~~~~~~~~~~~~

util/tools/auto/presenceUpdater.ts:116:8 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.   

116   if (!process.env.GITHUB_ACTIONS) {
           ~~~~~~~

util/tools/auto/presenceUpdater.ts:130:4 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.   

130    process.exit(1);
       ~~~~~~~

util/tools/auto/presenceUpdater.ts:138:13 - error TS7006: Parameter 'pF' implicitly has an 'any' type.

138     .filter(pF => existsSync(`${pF}/metadata.json`))
                ~~

util/tools/auto/presenceUpdater.ts:139:30 - error TS7006: Parameter 'pF' implicitly has an 'any' type.

139     .map<[Metadata, string]>(pF => {
                                 ~~

util/tools/auto/presenceUpdater.ts:156:7 - error TS7031: Binding element 'metadata' implicitly has an 'any' type.

156     ([metadata]) =>
          ~~~~~~~~

util/tools/auto/presenceUpdater.ts:157:24 - error TS7006: Parameter 'dbData' implicitly has an 'any' type.

157      !dbPresences.some(dbData => dbData.name === metadata.service)
                           ~~~~~~

util/tools/auto/presenceUpdater.ts:160:5 - error TS7006: Parameter 'dbData' implicitly has an 'any' type.

160     dbData =>
        ~~~~~~

util/tools/auto/presenceUpdater.ts:161:24 - error TS7031: Binding element 'metadata' implicitly has an 'any' type.

161      !presences.some(([metadata]) => metadata.service === dbData.name)
                           ~~~~~~~~

util/tools/auto/presenceUpdater.ts:164:13 - error TS7006: Parameter 'dbData' implicitly has an 'any' type.

164     .filter(dbData =>
                ~~~~~~

util/tools/auto/presenceUpdater.ts:166:9 - error TS7031: Binding element 'metadata' implicitly has an 'any' type.

166       ([metadata]) =>
            ~~~~~~~~

util/tools/auto/presenceUpdater.ts:171:10 - error TS7006: Parameter 'dbData' implicitly has an 'any' type.

171     .map(dbData =>
             ~~~~~~

util/tools/auto/presenceUpdater.ts:172:23 - error TS7031: Binding element 'metadata' implicitly has an 'any' type.

172      presences.find(([metadata]) => metadata.service === dbData.name)
                          ~~~~~~~~

util/tools/auto/presenceUpdater.ts:184:10 - error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.

184    await Promise.all(
             ~~~~~~~

util/tools/auto/presenceUpdater.ts:185:24 - error TS7031: Binding element 'metadata' implicitly has an 'any' type.

185     dbDiff.map(async ([metadata, path]) => {
                           ~~~~~~~~

util/tools/auto/presenceUpdater.ts:185:34 - error TS7031: Binding element 'path' implicitly has an 'any' type.

185     dbDiff.map(async ([metadata, path]) => {
                                     ~~~~

util/tools/auto/presenceUpdater.ts:261:53 - error TS7006: Parameter 'dbData' implicitly has an 'any' type.

261    const newPresenceData = compiledPresences.filter(dbData =>
                                                        ~~~~~~

util/tools/auto/presenceUpdater.ts:262:26 - error TS7031: Binding element 'metadata' implicitly has an 'any' type.

262      newPresences.some(([metadata]) => metadata.service === dbData.name)
                             ~~~~~~~~

util/tools/auto/presenceUpdater.ts:264:52 - error TS7006: Parameter 'dbPresence' implicitly has an 'any' type.

264     updatedPresenceData = compiledPresences.filter(dbPresence =>
                                                       ~~~~~~~~~~

util/tools/auto/presenceUpdater.ts:266:9 - error TS7031: Binding element 'metadata' implicit [...]

2022-09-24 10:13 UTC, EncryptedDev commented
Have you installed deps?

2022-09-24 10:29 UTC, Yeikzy commented
> Have you installed deps?

I just did it, here is the result

```js
> presences@3.0.0 format
> npm run ms && npm run lint


> presences@3.0.0 ms
> npm run compileTools && node ./util/tools/metadataSorter.js


> presences@3.0.0 compileTools
> tsc -p util/tools/tsconfig.json


The following presence doesn't include a metadata file :
./websites/P/Polywork/


> presences@3.0.0 lint
> prettier --write . && eslint --fix .

.github\dependabot.yml 58ms
  46:6   error  Use '===' to compare with null       no-eq-null

✖ 2 problems (2 errors, 0 warnings)```

2022-09-24 20:57 UTC, theusaf requested changes

2022-09-24 20:57 UTC, theusaf commented on websites/P/Polywork/presence.ts
> +	  }
```suggestion
	if (presenceData.details) presence.setActivity(presenceData);
	else {
		presence.setTrayTitle();
		presence.setActivity();
	}
```

2022-09-25 18:46 UTC, Yeikzy commented
> Have you installed deps?

```js
> presences@3.0.0 format
> npm run ms && npm run lint


> presences@3.0.0 ms
> npm run compileTools && node ./util/tools/metadataSorter.js


> presences@3.0.0 compileTools
> tsc -p util/tools/tsconfig.json


The following presence doesn't include a metadata file :
./websites/P/Polywork/


> presences@3.0.0 lint
> prettier --write . && eslint --fix .

.github\dependabot.yml 66ms
.github\FUNDING.yml 5ms
.github\ISSUE_TEMPLATE\bug_report.yml 23ms
.github\ISSUE_TEMPLATE\config.yml 5ms
.github\ISSUE_TEMPLATE\feature_request.yml 16ms
.github\ISSUE_TEMPLATE\service_request.yml 15ms
.github\workflows\compileLint.yml 11ms
.github\workflows\deploy.yml 14ms
.github\workflows\SE.yml 15ms
.github\workflows\SV.yml 10ms
@types\premid\index.d.ts 524ms
util\tools\auto\presenceUpdater.ts 170ms
util\tools\auto\schemaValidator.ts 156ms
util\tools\bumpChanged.ts 47ms
util\tools\compileChanged.ts 31ms
util\tools\massVer.ts 19ms
util\tools\metadataSorter.ts 24ms
util\tools\util.ts 36ms
websites\P\Polywork\presence.ts 18ms

C:\Users\user\Downloads\Code\JavaScript\Discord\Presence\Presences\websites\P\Polywork\presence.ts
  13:33  error  Expected '===' and instead saw '=='  eqeqeq

✖ 1 problem (1 error, 0 warnings)```

2022-09-26 19:46 UTC, EncryptedDev commented
Try again maybe? We pushed a fix

2022-09-30 16:27 UTC, Yeikzy commented
> Try again maybe? We pushed a fix

Always an error

2022-09-30 16:38 UTC, Yeikzy commented
> Try again maybe? We pushed a fix
```js
> presences@3.0.0 prepare
> is-ci || husky install

husky - Git hooks installed

changed 2 packages, and audited 589 packages in 1m

92 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\Users\user\Downloads\Code\JavaScript\Discord\Presence\Presences\websites\P\Polywork> npm run format

> presences@3.0.0 format
> npm run ms && npm run lint


> presences@3.0.0 ms
> npm run compileTools && node ./util/tools/metadataSorter.js


> presences@3.0.0 compileTools
> tsc -p util/tools/tsconfig.json


The following presence doesn't include a metadata file :
./websites/P/Polywork/


> presences@3.0.0 lint
> prettier --write . && eslint --fix .

.github\dependabot.yml 62ms
.github\FUNDING.yml 6ms
.github\ISSUE_TEMPLATE\bug_report.yml 17ms
.github\ISSUE_TEMPLATE\config.yml 5ms
.github\ISSUE_TEMPLATE\feature_request.yml 13ms
.github\ISSUE_TEMPLATE\service_request.yml 16ms
.github\workflows\compileLint.yml 10ms
.github\workflows\deploy.yml 10ms
.github\workflows\SE.yml 15ms
.github\workflows\SV.yml 11ms
@types\premid\index.d.ts 582ms
util\tools\auto\presenceUpdater.ts 199ms
util\tools\auto\schemaValidator.ts 167ms
util\tools\bumpChanged.ts 43ms
util\tools\compileChanged.ts 26ms
util\tools\massVer.ts 15ms
util\tools\metadataSorter.ts 25ms
util\tools\util.ts 36ms
websites\P\Polywork\presence.ts 18ms

C:\Users\user\Downloads\Code\JavaScript\Discord\Presence\Presences\websites\P\Polywork\presence.ts
  13:33  error  Expected '===' and instead saw '=='  eqeqeq

✖ 1 problem (1 error, 0 warnings)```

2022-09-30 18:46 UTC, theusaf requested changes

2022-09-30 18:46 UTC, theusaf commented on websites/P/Polywork/presence.ts
> +			if (document.location.hostname == "polywork.com") {
```suggestion
			if (document.location.hostname === "polywork.com") {
```

2022-09-30 18:46 UTC, theusaf commented on websites/P/Polywork/presence.ts
> +				presenceData.largeImageKey = "polywork";
You already set the image at the top, no need to do so here.
```suggestion
```

2022-09-30 18:46 UTC, theusaf commented on websites/P/Polywork/presence.ts
> +					presenceData.details = "Read are news feeds";
Is this text correct?

2022-09-30 18:49 UTC, theusaf requested changes

2022-09-30 18:49 UTC, theusaf commented on websites/P/Polywork/presence.ts
> +			if (document.location.hostname == "polywork.com") {
Actually, you can completely remove this if statement altogether, as your presence is only running on one hostname...

2022-09-30 19:02 UTC, Yeikzy commented on websites/P/Polywork/presence.ts
> +				largeImageKey: "polywork",
Can you create a commit with all the necessary changes to fix the issues faster?

2022-10-02 21:25 UTC, Yeikzy commented
@theusaf Can you create a commit with all the necessary changes to fix the issues faster?

2022-10-03 08:41 UTC, Yeikzy commented
@theusaf @EncryptedDev 
Is the code good?

2022-10-03 13:24 UTC, EncryptedDev commented
Resolve conversations once they have been dealt with

2022-10-03 13:31 UTC, Yeikzy commented
> Resolve conversations once they have been dealt with

Could you help me? I don't see errors.

2022-10-03 13:34 UTC, EncryptedDev commented
> > Resolve conversations once they have been dealt with
> 
> Could you help me? I don't see errors.

Press the "resolve" button on conversations once you deem that they have been resolved

2022-10-03 13:51 UTC, Yeikzy commented
> > > Resolve conversations once they have been dealt with
> > 
> > 
> > Could you help me? I don't see errors.
> 
> Press the "resolve" button on conversations once you deem that they have been resolved

It's good 👍🏼

2022-10-03 18:24 UTC, theusaf requested changes
Make sure to resolve CI. Run `yarn format`.
Also, some of the conversations marked as resolved are not resolved. Double-check them and explain why they were resolved if you think they are truly resolved.

2022-10-09 10:32 UTC, Yeikzy commented
> Make sure to resolve CI. Run `yarn format`. Also, some of the conversations marked as resolved are not resolved. Double-check them and explain why they were resolved if you think they are truly resolved.

```js 
Internal Error: presences@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at AF.getCandidates (C:\Users\user\.node\corepack\yarn\3.1.1\yarn.js:437:4421)
    at pd.getCandidates (C:\Users\user\.node\corepack\yarn\3.1.1\yarn.js:432:5275)
    at C:\Users\user\.node\corepack\yarn\3.1.1\yarn.js:441:7674
    at du (C:\Users\user\.node\corepack\yarn\3.1.1\yarn.js:382:4003)
    at R (C:\Users\user\.node\corepack\yarn\3.1.1\yarn.js:441:7654)
```

2022-10-09 12:19 UTC, DarkVillager requested changes

2022-10-09 12:19 UTC, DarkVillager commented on websites/P/Polywork/presence.ts
> +			}
```suggestion
			},
			[pathname, hostname, href, URL] = document.location
```

2022-10-09 12:19 UTC, DarkVillager commented on websites/P/Polywork/presence.ts
> +			if (document.location.hostname === "polywork.com") {
```suggestion
			if (hostname === "polywork.com") {
```

2022-10-09 12:19 UTC, DarkVillager commented on websites/P/Polywork/presence.ts
> +			if (document.location.pathname.includes("/feeds/")) {
```suggestion
			if (pathname.includes("/feeds/")) {
```

2022-10-09 12:19 UTC, DarkVillager commented on websites/P/Polywork/presence.ts
> +							url: location.href,
```suggestion
							url: href,
```

2022-10-09 12:19 UTC, DarkVillager commented on websites/P/Polywork/presence.ts
> +						url: location.href,
```suggestion
						url: href,
```

2022-10-09 12:19 UTC, DarkVillager commented on websites/P/Polywork/presence.ts
> +			else if (document.location.href.includes("/clubs/")) {
```suggestion
			else if (href.includes("/clubs/")) {
```

2022-10-09 12:19 UTC, DarkVillager commented on websites/P/Polywork/presence.ts
> +					url: location.href,
```suggestion
					url: href,
```

2022-10-09 12:19 UTC, DarkVillager commented on websites/P/Polywork/presence.ts
> +		presence.setTrayTitle();
What

2022-10-11 20:40 UTC, EncryptedDev commented
Resolve Compile CI issues

2022-10-12 10:43 UTC, DarkVillager requested changes

2022-10-12 10:43 UTC, DarkVillager commented on websites/P/Polywork/presence.ts
> +			[pathname, hostname, href, URL] = document.location
oops u don't use URL
```suggestion
			[ pathname, hostname, href ] = document.location;
```

2022-10-12 10:51 UTC, Yeikzy commented
@DarkVillager 

```js
Error: error TS2488: Type 'Location' must have a '[Symbol.iterator]()' method that returns an iterator.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.```

2022-10-12 10:51 UTC, DarkVillager commented
I am dumb, excuse my stupidity.
```suggestion
			{ pathname, hostname, href } = document.location;
```

2022-10-12 12:49 UTC, Yeikzy commented
> I am dumb, excuse my stupidity (this is what 70 hours of no sleeping does to me). It should be:
> 
> ```
> 			{ pathname, hostname, href } = document.location;
> ```

```js
Run yarn lint:ci
  
yarn run v1.22.1[9](https://github.com/PreMiD/Presences/actions/runs/3234799029/jobs/5298357396#step:6:10)
$ prettier --check . && eslint .
Checking formatting...
[warn] websites/P/Polywork/presence.ts
[warn] Code style issues found in the above file. Forgot to run Prettier?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.```

2022-10-18 23:49 UTC, EncryptedDev commented
Hi, upon looking into this further, I believe this is a low quality presence due to the following reasons: 
- You were unable to run the format script (`yarn format`) and instead you constantly ran `yarn lint:ci` which you were never told to do and even agreed that within the pull request acknowledgements
- This pull request does not include a wide range of pages which Polywork has. For example, the `opportunities` path route has no support. In addition, the crutial part of people's Polywork page won't even be supported too. 

Due to this and your neglect for this PR, it will be closed. If you want more information to rectify the PR, contact me via Discord (Encrypted#0001, PreMiD Product Manager within our [Discord](https://discord.gg/premid))

2022-10-18 23:49 UTC, closed without merging