add Presence
PreMiD/Presences pull request #6802
Opened 2022-09-18 19:01 UTC by WaldperlachFabi

## Description 

Added Presence for the Website https://WaldperlachFabi.de/

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![unknown](https://user-images.githubusercontent.com/80318133/190923993-6b4eca3e-6053-4871-880a-092f5c674a07.png)
![unknown1](https://user-images.githubusercontent.com/80318133/190924000-7c854471-ca95-439f-8dcc-6c36136de5bd.png)

</details>

2022-09-19 11:07 UTC, DarkVillager commented
Where are the screenshots?
Follow the [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

2022-09-19 11:15 UTC, DarkVillager requested changes

2022-09-19 11:15 UTC, DarkVillager commented on websites/W/WaldperlachFabi/dist/presence.js
> +});
Don't include this file.

2022-09-19 11:15 UTC, DarkVillager commented on websites/W/WaldperlachFabi/presence.ts
> +    });
Low quality.

Try using a switch statement & variables.

2022-09-20 17:38 UTC, EncryptedDev commented
Low quality presence

2022-09-24 07:14 UTC, closed without merging

2022-09-30 20:36 UTC, WaldperlachFabi commented
Sorry here are the Pictures!
![image](https://user-images.githubusercontent.com/80318133/193352346-fb4efef6-3426-42aa-be85-78fce4fdd3f7.png)
![image](https://user-images.githubusercontent.com/80318133/193352369-26f69949-5b2b-4b18-bed2-006420094dc3.png)
![image](https://user-images.githubusercontent.com/80318133/193352420-2123e3e5-8209-4fc1-b854-59a81320fc9b.png)
![image](https://user-images.githubusercontent.com/80318133/193352435-65b8e683-83f4-4572-9f06-73e780a15f05.png)
![image](https://user-images.githubusercontent.com/80318133/193352446-330b98cf-3536-47e6-8145-0682b5d6c4fa.png)