feat(D&D Beyond): add presence
PreMiD/Presences pull request #6811
Opened 2022-09-21 16:26 UTC by theusaf

## Description 
Adds a presence for www.dndbeyond.com.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img width="227" alt="2022-09-21 08_58_14" src="https://user-images.githubusercontent.com/32113157/191559235-b0c05189-e995-4baa-9e37-777474cd5a51.png">
<img width="226" alt="2022-09-21 08_58_26" src="https://user-images.githubusercontent.com/32113157/191559242-e6b46d15-3689-4971-ba52-aeb835bd50fa.png">
<img width="226" alt="2022-09-21 09_00_10" src="https://user-images.githubusercontent.com/32113157/191559244-6837efd2-c00e-4f7f-8430-816502f0df8a.png">
<img width="223" alt="2022-09-21 09_01_00" src="https://user-images.githubusercontent.com/32113157/191559245-78f95ed8-ae33-49b4-aef4-e3c5560a6258.png">
<img width="230" alt="2022-09-21 09_01_18" src="https://user-images.githubusercontent.com/32113157/191559247-4ed3fe02-6a67-416f-9e45-a75650b090a8.png">
<img width="228" alt="2022-09-21 09_01_31" src="https://user-images.githubusercontent.com/32113157/191559249-bd03a70b-50e7-470c-b005-db130caafbb1.png">
<img width="223" alt="2022-09-21 09_02_34" src="https://user-images.githubusercontent.com/32113157/191559253-f05c70e5-57aa-48cf-8dc9-ed15a8bc252c.png">
<img width="222" alt="2022-09-21 09_03_38" src="https://user-images.githubusercontent.com/32113157/191559254-1d6e85b6-48c8-4ed5-9821-61c3a8f39a79.png">
<img width="226" alt="2022-09-21 09_03_56" src="https://user-images.githubusercontent.com/32113157/191559259-6661867e-fd45-424e-9d8f-88f7f0bd9c33.png">
<img width="229" alt="2022-09-21 09_04_17" src="https://user-images.githubusercontent.com/32113157/191559263-99c95dc9-b74e-45a8-89d9-8bd3f5a18327.png">
<img width="225" alt="2022-09-21 09_04_34" src="https://user-images.githubusercontent.com/32113157/191559266-18219d17-842d-484d-8ddf-f9218374fb34.png">
<img width="221" alt="2022-09-21 09_04_53" src="https://user-images.githubusercontent.com/32113157/191559268-9786661c-6a89-453f-85ef-e3811b3cc8b3.png">
<img width="230" alt="2022-09-21 09_05_03" src="https://user-images.githubusercontent.com/32113157/191559270-ccb6b2bc-a494-446b-b751-8454d2d15d6a.png">
<img width="233" alt="2022-09-21 09_05_21" src="https://user-images.githubusercontent.com/32113157/191559272-4deca0a2-ff10-4b07-abd5-ff6d7d56aa83.png">
<img width="223" alt="2022-09-21 09_05_35" src="https://user-images.githubusercontent.com/32113157/191559274-63464ab1-5bcc-4f2b-9ee6-1191b47c80b0.png">
<img width="235" alt="2022-09-21 09_05_40" src="https://user-images.githubusercontent.com/32113157/191559277-778b830d-c8fa-4bbe-9bf2-0642dd660818.png">
<img width="226" alt="2022-09-21 09_05_54" src="https://user-images.githubusercontent.com/32113157/191559279-05f42548-5ee6-4566-bf95-568960f28b35.png">
<img width="229" alt="2022-09-21 09_06_07" src="https://user-images.githubusercontent.com/32113157/191559280-68b35ded-17a8-4de0-a1f2-7a30a528b262.png">
<img width="220" alt="2022-09-21 09_06_15" src="https://user-images.githubusercontent.com/32113157/191559283-0a3b385c-e3ef-44ed-9689-dbc62881ce5d.png">
<img width="227" alt="2022-09-21 09_06_19" src="https://user-images.githubusercontent.com/32113157/191559288-d2c46a38-e394-44d5-aa75-e593a3bb3e21.png">
<img width="227" alt="2022-09-21 09_06_28" src="https://user-images.githubusercontent.com/32113157/191559294-457442fb-9673-4ce5-b31f-cb139a8ef551.png">
<img width="221" alt="2022-09-21 09_06_33" src="https://user-images.githubusercontent.com/32113157/191559295-6e9e74a8-7dbd-4de1-9a7d-01d63028c5d5.png">
<img width="229" alt="2022-09-21 09_06_39" src="https://user-images.githubusercontent.com/32113157/191559296-de310229-7027-4812-a8b1-e0e2a6109cce.png">
<img width="223" alt="2022-09-21 09_06_44" src="https://user-images.githubusercontent.com/32113157/191559298-cadb9824-5581-4336-ba50-4ea1122ba3b2.png">
<img width="229" alt="2022-09-21 09_09_00" src="https://user-images.githubusercontent.com/32113157/191559300-24edc0c1-6b27-446e-9306-2cf2d28e0ac0.png">
<img width="224" alt="2022-09-21 09_09_05" src="https://user-images.githubusercontent.com/32113157/191559303-ef22bc21-b34b-43c4-92e2-389529a5da4d.png">
<img width="227" alt="2022-09-21 09_09_12" src="https://user-images.githubusercontent.com/32113157/191559304-9f850810-c56e-496c-9b2d-fd21003c6b91.png">
<img width="230" alt="2022-09-21 09_09_18" src="https://user-images.githubusercontent.com/32113157/191559305-2d6c92f0-84d8-478b-b16c-1b4ba84f40cf.png">
<img width="223" alt="2022-09-21 09_09_49" src="https://user-images.githubusercontent.com/32113157/191559309-b26a013d-435a-41bc-879a-aa66848c43e0.png">
<img width="228" alt="2022-09-21 09_10_07" src="https://user-images.githubusercontent.com/32113157/191559311-acfee1ce-b04c-42c6-93c2-6bdb77778810.png">
<img width="226" alt="2022-09-21 09_10_24" src="https://user-images.githubusercontent.com/32113157/191559313-5777aaa9-d3f3-4a44-b9e2-225eb8748b32.png">
<img width="228" alt="2022-09-21 09_10_33" src="https://user-images.githubusercontent.com/32113157/191559314-670e18ca-6bb1-40cd-b562-e99449b8675c.png">
<img width="225" alt="2022-09-21 09_11_05" src="https://user-images.githubusercontent.com/32113157/191559318-2801ad3b-cf13-4329-a4a0-29f8fa60b2e6.png">
<img width="230" alt="2022-09-21 09_12_35" src="https://user-images.githubusercontent.com/32113157/191559319-e15deb29-d0bc-42f0-8824-bfaceb02c019.png">
<img width="224" alt="2022-09-21 09_14_26" src="https://user-images.githubusercontent.com/32113157/191559321-35ad0601-9a86-4f90-934b-7ca3f17b0de1.png">
<img width="240" alt="2022-09-21 09_14_31" src="https://user-images.githubusercontent.com/32113157/191559326-f6e3a37c-0779-4fd4-9a51-e28a7a5305e2.png">
<img width="226" alt="2022-09-21 09_15_11" src="https://user-images.githubusercontent.com/32113157/191559328-77a9c980-b95e-4101-84f0-6d242caca487.png">
<img width="230" alt="2022-09-21 09_15_14" src="https://user-images.githubusercontent.com/32113157/191559331-69a36511-0b81-40b9-ac7c-df061e49f8a6.png">
<img width="223" alt="2022-09-21 09_16_37" src="https://user-images.githubusercontent.com/32113157/191559332-bd953e70-325b-48f7-b44e-4ca6609bda7f.png">
<img width="220" alt="2022-09-21 09_16_49" src="https://user-images.githubusercontent.com/32113157/191559337-e700e7c1-ab76-4803-8930-3c56a17c6324.png">
<img width="226" alt="2022-09-21 09_17_16" src="https://user-images.githubusercontent.com/32113157/191559344-3423852e-e14e-46bd-bce4-81f0ea33344c.png">
<img width="223" alt="2022-09-21 09_18_30" src="https://user-images.githubusercontent.com/32113157/191559345-393de226-68dd-4b41-9c2e-5e9bbfbf6309.png">
<img width="225" alt="2022-09-21 09_18_59" src="https://user-images.githubusercontent.com/32113157/191559346-52f4ec55-8b85-437b-819a-d49d3ebd9aba.png">
<img width="227" alt="2022-09-21 09_19_06" src="https://user-images.githubusercontent.com/32113157/191559348-fb795871-0936-44e8-8cff-c41461f48e6e.png">
<img width="225" alt="2022-09-21 09_19_27" src="https://user-images.githubusercontent.com/32113157/191559349-1b793457-306e-4914-9fa4-4ce58314d035.png">
<img width="228" alt="2022-09-21 09_19_40" src="https://user-images.githubusercontent.com/32113157/191559350-db2f9732-f770-445b-8aeb-e1a82701e7bd.png">
<img width="223" alt="2022-09-21 09_19_55" src="https://user-images.githubusercontent.com/32113157/191559353-ea0d899d-40ee-4fa7-93b6-af55520134d0.png">
<img width="223" alt="2022-09-21 09_20_03" src="https://user-images.githubusercontent.com/32113157/191559356-b5457253-a49a-45e9-9dae-8334ec8941a1.png">
<img width="227" alt="2022-09-21 09_20_27" src="https://user-images.githubusercontent.com/32113157/191559358-83e18871-2c79-479c-909b-0c70971768d5.png">
<img width="223" alt="2022-09-21 09_20_41" src="https://user-images.git [...]

2022-09-22 20:07 UTC, EncryptedDev requested changes

2022-09-22 20:07 UTC, EncryptedDev commented on websites/D/D&D Beyond/presence.ts
> +						label: "View background",
```suggestion
						label: "View Background",
```

2022-09-23 15:28 UTC, EncryptedDev approved these changes

2022-09-24 07:15 UTC, Bas950 approved these changes

2022-09-24 07:15 UTC, merged