feat(mod.io): add presence
PreMiD/Presences pull request #6816
Opened 2022-09-24 22:12 UTC by theusaf

## Description 
Adds presence for mod.io including blog, docs, and old site.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img width="230" alt="2022-09-24 15_08_13" src="https://user-images.githubusercontent.com/32113157/192120365-5779a7e9-0fd4-4a33-a857-fe97608a40fe.png">
<img width="227" alt="2022-09-24 14_46_46" src="https://user-images.githubusercontent.com/32113157/192120367-735b8e3e-c191-45bb-a501-46ec6f555c84.png">
<img width="227" alt="2022-09-24 14_47_23" src="https://user-images.githubusercontent.com/32113157/192120368-cbcb5c9c-a1d9-46fd-b4db-0b07adfde9f8.png">
<img width="226" alt="2022-09-24 14_49_01" src="https://user-images.githubusercontent.com/32113157/192120369-9d2cede2-c3fa-43c4-9d94-caea3e70cfd0.png">
<img width="222" alt="2022-09-24 14_50_13" src="https://user-images.githubusercontent.com/32113157/192120370-fbf161a4-82d0-4410-b0a8-2df6a6ac89fe.png">
<img width="227" alt="2022-09-24 14_52_03" src="https://user-images.githubusercontent.com/32113157/192120371-1df1719d-00ab-4980-99d1-c243d8b3fc04.png">
<img width="242" alt="2022-09-24 14_52_07" src="https://user-images.githubusercontent.com/32113157/192120372-76a7c4ee-8f98-4be2-b266-384e2bf061d4.png">
<img width="228" alt="2022-09-24 14_52_32" src="https://user-images.githubusercontent.com/32113157/192120373-39ff6aef-6c62-4805-94d3-9064d60dff09.png">
<img width="229" alt="2022-09-24 14_52_52" src="https://user-images.githubusercontent.com/32113157/192120374-f4c1d271-91ca-4e3c-b709-3d1a4f5e469e.png">
<img width="225" alt="2022-09-24 14_53_01" src="https://user-images.githubusercontent.com/32113157/192120375-b2b5c816-2fa3-4a1e-acff-c7fc443b4029.png">
<img width="226" alt="2022-09-24 14_57_05" src="https://user-images.githubusercontent.com/32113157/192120376-61f8dfe9-19d2-4a3e-a61a-f98663b95936.png">
<img width="225" alt="2022-09-24 14_57_40" src="https://user-images.githubusercontent.com/32113157/192120377-bf3cb917-b7ac-47c0-8567-9d7ee64a5e25.png">
<img width="223" alt="2022-09-24 14_57_57" src="https://user-images.githubusercontent.com/32113157/192120378-bc52c5e4-890b-45c6-86d0-9665112f830f.png">
<img width="222" alt="2022-09-24 15_00_49" src="https://user-images.githubusercontent.com/32113157/192120379-06033a89-cedb-4b4a-87f7-65786ce7d3d2.png">
<img width="224" alt="2022-09-24 15_01_16" src="https://user-images.githubusercontent.com/32113157/192120380-4fb7e400-567d-44e5-907a-c54dee9b0ea4.png">
<img width="225" alt="2022-09-24 15_01_49" src="https://user-images.githubusercontent.com/32113157/192120381-b775aa7f-2ab8-4bed-b4f4-95b417633109.png">
<img width="220" alt="2022-09-24 15_02_09" src="https://user-images.githubusercontent.com/32113157/192120383-ad0a2eea-89da-4abd-8b56-d71bb5f6d5e4.png">
<img width="219" alt="2022-09-24 15_02_29" src="https://user-images.githubusercontent.com/32113157/192120384-73c59781-2e27-43f6-bcd6-251a7a6770cc.png">
<img width="222" alt="2022-09-24 15_03_54" src="https://user-images.githubusercontent.com/32113157/192120385-c9c890f1-0eba-4297-a21d-0952b76f5630.png">
<img width="225" alt="2022-09-24 15_04_53" src="https://user-images.githubusercontent.com/32113157/192120386-d697771d-8565-4e2b-9767-de4c8bf438e5.png">
<img width="223" alt="2022-09-24 15_05_16" src="https://user-images.githubusercontent.com/32113157/192120387-eda843bc-d3fd-4916-b148-c2b8733f4b66.png">
<img width="228" alt="2022-09-24 15_05_27" src="https://user-images.githubusercontent.com/32113157/192120388-bb48a330-f45e-4f3b-81ee-62bb21cd5fe4.png">
<img width="225" alt="2022-09-24 15_05_48" src="https://user-images.githubusercontent.com/32113157/192120389-8cf924dd-7696-4fcf-ba16-ab95806dd548.png">
<img width="220" alt="2022-09-24 15_06_12" src="https://user-images.githubusercontent.com/32113157/192120390-4342e8ab-717d-4dd2-ab14-4c7319ce0f11.png">
<img width="220" alt="2022-09-24 15_07_04" src="https://user-images.githubusercontent.com/32113157/192120392-7a07dd91-2294-4483-8f9c-2e3cd1f0433d.png">
<img width="222" alt="2022-09-24 15_07_10" src="https://user-images.githubusercontent.com/32113157/192120394-eb5f260c-3a51-4e52-8ef9-13e897efc611.png">
<img width="220" alt="2022-09-24 15_07_41" src="https://user-images.githubusercontent.com/32113157/192120395-667cfcc7-4a67-43ad-b4b0-b62982e19fa8.png">
<img width="241" alt="2022-09-24 15_07_44" src="https://user-images.githubusercontent.com/32113157/192120397-5bfef123-ddb2-45fb-95c1-c20e81408e0e.png">
<img width="224" alt="2022-09-24 15_07_51" src="https://user-images.githubusercontent.com/32113157/192120398-0fc21430-d129-4eab-a4c8-784504f86766.png">
<img width="223" alt="2022-09-24 15_07_56" src="https://user-images.githubusercontent.com/32113157/192120399-2d3a5f79-846d-4735-9a17-2edf57cd6b2c.png">

</details>

2022-09-26 19:44 UTC, EncryptedDev approved these changes

2022-09-27 07:18 UTC, Bas950 requested changes

2022-09-27 07:18 UTC, Bas950 commented on websites/M/mod.io/metadata.json
> +		"name": "theusaf#4322"
```suggestion
		"name": "theusaf"
```

2022-09-28 11:13 UTC, Bas950 approved these changes

2022-09-30 14:14 UTC, EncryptedDev approved these changes

2022-09-30 14:14 UTC, merged