feat(The Eternal Jukebox): add presence
PreMiD/Presences pull request #6822
Opened 2022-09-27 05:16 UTC by theusaf

## Description 
Adds a presence for [The Eternal Jukebox](https://eternalbox.dev).
This PR resolves #6490

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img width="219" alt="2022-09-26 22_12_01" src="https://user-images.githubusercontent.com/32113157/192438057-6c36e1d8-3896-4dc2-8ad4-6c18ab2c2a35.png">
<img width="219" alt="2022-09-26 22_12_17" src="https://user-images.githubusercontent.com/32113157/192438062-c4542364-f861-4a9d-b0c4-8d3dc77f3c73.png">
<img width="226" alt="2022-09-26 22_16_18" src="https://user-images.githubusercontent.com/32113157/192438064-abe0363a-e761-4c05-b9e2-d91b55e4491b.png">

</details>

2022-09-27 13:11 UTC, plskz requested changes

2022-09-27 13:11 UTC, plskz commented on websites/T/The Eternal Jukebox/metadata.json
> +		"name": "theusaf#4322"
```suggestion
		"name": "theusaf"
```

2022-09-27 13:11 UTC, plskz commented on websites/T/The Eternal Jukebox/metadata.json
> +		"en": "For when your favorite song just isn't long enough"
```suggestion
		"en": "The Eternal Jukebox lets you search a song on Spotify and will then generate a never-ending and ever changing version of the song. It does what Infinite Gangnam Style did but for any song."
```

2022-09-27 13:11 UTC, plskz commented on websites/T/The Eternal Jukebox/metadata.json
> +		"todo"
```suggestion
		"audio"
```

2022-09-27 15:31 UTC, plskz approved these changes

2022-10-06 20:06 UTC, EncryptedDev approved these changes

2022-10-07 18:27 UTC, Bas950 approved these changes

2022-10-07 18:27 UTC, merged