feat(Tebex): add presence
PreMiD/Presences pull request #6825
Opened 2022-09-29 06:52 UTC by DarkVillager

## Description 

Added tebex & store's with Buycraft/Tebex in it's domain
## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://user-images.githubusercontent.com/42322979/192959959-d4a0e36a-fbb8-40fe-bec1-7cc058648e5b.jpg">
<img src="https://user-images.githubusercontent.com/42322979/192959961-f0eee094-11e2-46dc-bd4b-5f56b39135a7.jpg"><img src="https://user-images.githubusercontent.com/42322979/192959964-7de2cd5d-eb28-49f8-b5e4-39b52e50b152.jpg"><img src="https://user-images.githubusercontent.com/42322979/192959966-2a4e7e2d-7f0f-4d11-8ece-c363b4274666.jpg"><img src="https://user-images.githubusercontent.com/42322979/192959968-ee33914c-2b82-4bf0-a4d6-38f85c5dfa07.jpg"><img src="https://user-images.githubusercontent.com/42322979/192959970-ad03f0c4-c16e-48e2-90a1-7937b64c1d01.jpg"><img src="https://user-images.githubusercontent.com/42322979/192959955-e4e8cac0-5cd2-4c81-a611-1ec13142bcff.jpg">

</details>

2022-09-30 14:17 UTC, EncryptedDev requested changes

2022-09-30 14:17 UTC, EncryptedDev commented on websites/T/Tebex/metadata.json
> +		"nl": "Financier jouw game server kosten met Tebex. De vooraanstaande betalingsplugin voor Minecraft, Rust, ARK, GTA V en meer."
@Bas950

2022-09-30 14:17 UTC, EncryptedDev commented on websites/T/Tebex/presence.ts
> +							label: "View All Games",
Sounds really repetitive with `details` possibly `View Page` instead

2022-09-30 14:17 UTC, EncryptedDev commented on websites/T/Tebex/presence.ts
> +							label: "View Partners",
Ditto

2022-09-30 14:17 UTC, EncryptedDev commented on websites/T/Tebex/presence.ts
> +							label: "View The Contact Page",
Not really needed

2022-09-30 14:17 UTC, EncryptedDev commented on websites/T/Tebex/presence.ts
> +						label: "Read The Docs",
```suggestion
						label: "Read Docs",
```

2022-09-30 14:17 UTC, EncryptedDev commented on websites/T/Tebex/presence.ts
> +							label: "View Category",
Not really needed

2022-10-01 11:09 UTC, DarkVillager commented on websites/T/Tebex/metadata.json
> +		"nl": "Financier jouw game server kosten met Tebex. De vooraanstaande betalingsplugin voor Minecraft, Rust, ARK, GTA V en meer."
@QkeleQ10

2022-10-03 13:24 UTC, EncryptedDev approved these changes
lgtm once bas approves translation

2022-10-09 19:06 UTC, Bas950 approved these changes

2022-10-09 19:06 UTC, merged