feat(Hero Forge): add presence
PreMiD/Presences pull request #6846
Opened 2022-10-02 20:45 UTC by theusaf

## Description 

Adds a presence for Hero Forge.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![2022-10-02 13_22_28](https://user-images.githubusercontent.com/32113157/193475493-62b76642-859c-4491-bde8-2146d8872f3b.png)
![2022-10-02 13_28_30](https://user-images.githubusercontent.com/32113157/193475494-bdb06901-c5cd-48be-8964-93c6ebc8f03c.png)

</details>

2022-10-03 13:27 UTC, EncryptedDev reviewed
lgtm

2022-10-03 13:27 UTC, EncryptedDev submitted a review, later dismissed

2022-10-04 11:10 UTC, Bas950 requested changes

2022-10-04 11:10 UTC, Bas950 commented on websites/H/Hero Forge/presence.ts
> +		path = pathname.split("/").find(x => x);
Find x => x?

2022-10-05 09:18 UTC, Bas950 approved these changes

2022-10-09 11:54 UTC, EncryptedDev approved these changes

2022-10-09 11:54 UTC, merged