fix(Disney+): add new domain
PreMiD/Presences pull request #6864
Opened 2022-10-09 14:04 UTC by sarcasterXO

## Description 
Added `www.hotstar.com` domain. As in India, whenever you try to open the website using `www.disneyplus.com` it redirects to `www.hotstar.com/in` and the presence stops by saying `Browsing...` even if I start watching a video. 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

2022-10-09 15:35 UTC, theusaf requested changes

2022-10-09 15:35 UTC, theusaf commented on websites/D/Disney+/metadata.json
>  	"version": "1.4.19",
```suggestion
	"version": "1.4.20"
```

2022-10-10 13:44 UTC, sarcasterXO commented
> That means the url is already supported, and just an FYI, the `url` field is ignored when the `regExp` field is present. So this PR won't fix the issue.

So, you mean I should remove the `regExp` field and only use `url`?

2022-10-10 19:20 UTC, EncryptedDev commented on websites/D/Disney+/metadata.json
>  	"version": "1.4.19",
Missing trailing comma

2022-10-11 02:01 UTC, theusaf commented on websites/D/Disney+/metadata.json
>  	"version": "1.4.19",
Fixed.

2022-10-11 02:45 UTC, sarcasterXO commented
> No, as I said, the url is already supported. 
> Basically, this isn't a solution to your issue.


Okay, I'll test again and commit the new changes.

2022-10-11 12:27 UTC, sarcasterXO commented
@Slowlife01 is correct, I tested it myself with and without the new domain and it works fine. I don't know what's wrong with the current extension though as while testing, it works fine.

2022-10-11 12:27 UTC, closed without merging