feat(The Weather Channel): add presence
PreMiD/Presences pull request #6867
Opened 2022-10-12 03:07 UTC by theusaf

## Description 

* Adds a presence for The Weather Channel (weather.com)
* Resolves #5379

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img width="213" alt="2022-10-11 20_06_07" src="https://user-images.githubusercontent.com/32113157/195240699-e54bfddf-5005-440a-9cec-b61a2e1e0bea.png">
<img width="223" alt="2022-10-11 20_06_21" src="https://user-images.githubusercontent.com/32113157/195240700-1b4d5616-535b-4b3f-8fcb-ac3403f72e1b.png">
<img width="225" alt="2022-10-11 20_07_01" src="https://user-images.githubusercontent.com/32113157/195240703-1ab32fe5-db66-4353-8fc9-2bdb8458fd28.png">
<img width="223" alt="2022-10-11 20_07_18" src="https://user-images.githubusercontent.com/32113157/195240706-d08c65d4-9ed7-49c6-876e-38efefbc88df.png">

</details>

2022-10-15 18:42 UTC, EncryptedDev requested changes

2022-10-15 18:42 UTC, EncryptedDev commented on websites/T/The Weather Channel/presence.ts
> +				presenceData.state = "Home page";
One line ideally

2022-10-18 23:51 UTC, EncryptedDev approved these changes

2022-10-20 16:13 UTC, Bas950 approved these changes

2022-10-20 16:13 UTC, merged