feat(Buienalarm): add presence
PreMiD/Presences pull request #6874
Opened 2022-10-14 07:44 UTC by DarkVillager

## Description 

Added a presence for Buienalarm
## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://user-images.githubusercontent.com/42322979/195791053-0f8a5641-ef45-4126-8a6f-d3030d77c054.png">
<img src="https://user-images.githubusercontent.com/42322979/195791056-5a6ede1f-e06e-4c01-aa14-72003315e941.png">
<img src="https://user-images.githubusercontent.com/42322979/195791059-295943bc-e1a6-48e3-940d-1a3008ac8db7.png">

</details>

2022-10-15 18:48 UTC, EncryptedDev commented on websites/B/Buienalarm/presence.ts
> +	SearchImage = "https://i.imgur.com/oGQtnIY.png",
```suggestion
	Search = "https://i.imgur.com/oGQtnIY.png",
```

2022-10-16 02:42 UTC, theusaf requested changes

2022-10-16 02:42 UTC, theusaf commented on websites/B/Buienalarm/presence.ts
> +		presenceData.smallImageKey = Assets.SearchImage;
```suggestion
		presenceData.smallImageKey = Assets.Search;
```

2022-10-20 16:14 UTC, Bas950 approved these changes

2022-10-23 14:05 UTC, EncryptedDev approved these changes

2022-10-23 14:05 UTC, merged