feat(Shoob): add presence
PreMiD/Presences pull request #6891
Opened 2022-10-16 00:05 UTC by theusaf

## Description 

* From #6857
* Rebased to remove changes to Anime Soul

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img width="227" alt="2022-10-05 15_46_09" src="https://user-images.githubusercontent.com/32113157/194178162-a9c2a704-c817-455a-bd96-9df40c0af982.png">
<img width="223" alt="2022-10-05 15_47_33" src="https://user-images.githubusercontent.com/32113157/194178164-aba55f73-1bfc-4b77-a10d-e62baeacf8ac.png">
<img width="223" alt="2022-10-05 15_48_08" src="https://user-images.githubusercontent.com/32113157/194178167-42e4612a-43da-4495-b86d-3f30bd7e079e.png">

</details>

2022-10-18 23:54 UTC, EncryptedDev requested changes
Add the static pages to a Record, shown in the example here
https://github.com/PreMiD/Presences/blob/cf3631226067d77ada628adbf77d7d5e5e2ca445/websites/T/TruckersMP/presence.ts#L15-L41

2022-10-25 16:01 UTC, EncryptedDev reviewed
LGTM

2022-10-25 16:01 UTC, EncryptedDev approved these changes

2022-10-27 13:10 UTC, Bas950 approved these changes

2022-10-27 13:10 UTC, merged