feat(osu!pppy): add buttons and multiLanguage
PreMiD/Presences pull request #6893
Opened 2022-10-16 00:32 UTC by StrikerFRFX

## Description 

Fixed a few bugs due to site internal updates 
Added localized strings

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

Provided if requested due to volume of screenshots

</details>

2022-10-16 02:39 UTC, theusaf requested changes
It looks like your branch is very old. `metadata.json` files are no longer tracked in `dist`, but in the presence's root directory.

2022-10-19 00:01 UTC, EncryptedDev commented
Rebased your branch, still outdated lol

2022-10-19 00:02 UTC, EncryptedDev commented on websites/O/osu!ppy/metadata.json
> +		"ga_IE": "Níl i rithim ach *cliceáil* ! Le Ouedan / EBA, Taiko agus modhanna bunaidh gameplay, chomh maith le eagarthóir leibhéal ag feidhmiú go hiomlán.",
@callumok2004

2022-10-19 00:04 UTC, EncryptedDev approved these changes
LGTM, PreMiD/Localization#7189 needs merging too

2022-10-25 08:15 UTC, DarkVillager approved these changes

2022-10-31 15:18 UTC, EncryptedDev commented
Conflicts should be resolved

2022-11-01 18:00 UTC, StrikerFRFX commented
> Conflicts should be resolved

what conflicts

2022-11-02 08:11 UTC, Bas950 approved these changes

2022-11-02 08:11 UTC, Bas950 commented
Bruh before I started reviewing 0 conflicts, after review: 
<img width="926" alt="image" src="https://user-images.githubusercontent.com/34792838/199434850-c1c15682-56e7-4cc5-969b-19c5a56a0c23.png">

2022-11-11 21:04 UTC, StrikerFRFX commented
when

2023-01-06 11:47 UTC, closed without merging

2023-01-06 11:47 UTC, Timeraa commented
Never received any updates.