chore(renovate): update config
PreMiD/Presences pull request #6910
Opened 2022-10-18 23:35 UTC by EncryptedDev

## Description

The [PreMiD/Presences](https://github.com/PreMiD/Presences) repository works as an independent repository from the rest of the project and company repositories due to the contributing differences, hence why the config should not be an extension of the company's config. Furthermore, the reason for changing the config settings are below: 
- Removed `reviewers` and `assigneesFromCodeowners` due to what was explained in #6900 
- Disable `automerge` indefinitely in order to ensure reviewers know the dependency changes and the impact they may have-
	- Security patches shouldn't be an issue here because this is a _Presence repository_
	- Reviewers check this repository daily, if not more often so dependency PRs won't be ignored

`stabilityDays`, `semanticCommits`, `configWarningReuseIssue`, `addLabels` remain the same as [Recodive/Configs](https://github.com/Recodive/Configs)

2022-10-18 23:37 UTC, EncryptedDev commented
CI failing due to #6888, should be resolved in #6897

2022-10-23 13:47 UTC, Bas950 approved these changes

2022-10-23 17:43 UTC, Bas950 requested changes

2022-10-23 17:43 UTC, Bas950 commented on .github/renovate.json
> +	"schedule": ["0 17 * * FRI"],
```suggestion
	"schedule": ["0 17 * * 5"],
```

2022-10-24 08:07 UTC, Bas950 approved these changes

2022-10-24 10:25 UTC, Timeraa approved these changes
Would've liked to have it extend the config but 🤷

2022-10-24 10:25 UTC, merged