feat(Discovery+): add presence
PreMiD/Presences pull request #6937
Opened 2022-10-25 09:22 UTC by DarkVillager

## Description 

Added a presence for discovery+. (Some grammar may sound off due to them recognising my language as Dutch.)
## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://i.imgur.com/Awyyufa.png">
<img src="https://i.imgur.com/G2Gj5YF.png">
<img src="https://i.imgur.com/glpxCOt.png">
<img src="https://i.imgur.com/85LrkOa.png">

</details>

2022-10-26 06:59 UTC, DarkVillager commented on websites/D/Discovery+/metadata.json
> +		"nl": "Welkom bij discovery+, the home of real-life entertainment en sport. Abonneer nu en volg volledige seizoenen, bekijk programma’s alvast vooruit of kijk terug wat je hebt gemist."
Official description for the dutch version. So yes it doesn't match but both site version have different descriptions.

2022-11-02 21:01 UTC, EncryptedDev requested changes

2022-11-05 12:35 UTC, EncryptedDev approved these changes

2022-11-06 10:31 UTC, Bas950 approved these changes

2022-11-06 10:31 UTC, merged