fix(Apple): fixed imgur links not working
PreMiD/Presences pull request #6940
Opened 2022-10-27 09:36 UTC by Yan-Jobs

Signed-off-by: Yan <yan@yanjobs.me>

## Description 

### Fixed this: 
![SCR-20221027-fxl](https://user-images.githubusercontent.com/76485792/198247656-ec3871d1-2843-4477-9867-dad7abd85b87.png)

Old imgur links:
<details>

![LOGO](https://i.imgur.com/rBAusA5.png)
![THUMBNAIL](https://i.imgur.com/D5b7fQ5.jpg)

</details>

New ones:
<details>

![test](https://i.imgur.com/w84AMlL.png)
![test](https://i.imgur.com/83wQlSy.jpeg)

</details>

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [/] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

I can't show this, since it's only a metadata change and I can't change the official website.

</details>

2022-10-27 09:38 UTC, Yan-Jobs commented
Version bump isn't mandatory because it is ONLY a metadata change, indeed a new version is useless

2022-10-27 09:52 UTC, EncryptedDev commented
> Version bump isn't mandatory because it is ONLY a metadata change, indeed a new version is useless

Who says a version bump isn’t needed? I’m not sure you know

2022-10-27 16:21 UTC, N0chteil requested changes

2022-10-27 16:21 UTC, N0chteil commented on websites/A/Apple/metadata.json
> +			"id": "735538297815957584"
```suggestion
		}
```

You didn't edit anything of the codebase, so please remove this

https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md
> If you make modifications to a presence and change at **least a quarter** of the presence's **codebase**, you are allowed to add yourself as a contributor. Contact a reviewer for more information about this subject.

2022-10-27 16:21 UTC, N0chteil commented on websites/A/Apple/metadata.json
> +	"thumbnail": "https://i.imgur.com/83wQlSy.jpeg",
```suggestion
	"thumbnail": "https://i.imgur.com/MZecshr.jpg",
```
![image](https://user-images.githubusercontent.com/53608074/198343240-ecffd01b-b2a8-475f-b4a0-374e7e0f1ad3.png)

The thumbnail doesn't fit. We should use this one instead:
![image](https://user-images.githubusercontent.com/53608074/198344520-dcda4fed-42ed-4359-84f2-e9942dad2f95.png)

2022-10-29 20:06 UTC, EncryptedDev approved these changes

2022-10-29 20:06 UTC, Bas950 approved these changes

2022-10-29 20:07 UTC, merged