fix(NetEase Cloud Music): fix and improve usage
PreMiD/Presences pull request #6941
Opened 2022-10-27 09:53 UTC by Kotoki1337

## Description 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://user-images.githubusercontent.com/35394151/198252156-d5c3634a-a9c7-4914-8355-10b0602ec4fe.png)

</details>

2022-10-27 13:39 UTC, EncryptedDev requested changes

2022-10-27 13:39 UTC, EncryptedDev commented on websites/#/网易云音乐/metadata.json
> +	"version": "1.0.13",
Changing the clientId is a breaking change

2022-10-31 15:21 UTC, EncryptedDev approved these changes

2022-11-01 03:31 UTC, theusaf commented
Shouldn't changes made to Stake's metadata be undone first?

2022-11-01 03:34 UTC, Kotoki1337 commented
it's literally `yarn format`, should i revert it (the Stake one)?

2022-11-02 08:10 UTC, Bas950 commented
> it's literally `yarn format`, should i revert it (the Stake one)?

Either, bump it's version, or revert that change please.

2022-11-02 10:55 UTC, Bas950 approved these changes

2022-11-02 10:55 UTC, merged