feat(Flat): add presence
PreMiD/Presences pull request #6950
Opened 2022-10-29 23:45 UTC by theusaf

## Description 

* Continued from #6809 (applies formatting and suggestions)
* Adds a presence for flat.io
* Resolves #6758 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

(Taken from linked PR)

![image](https://user-images.githubusercontent.com/15018948/191353603-f0272f00-f90f-4804-a103-227a4e36d445.png)
![image](https://user-images.githubusercontent.com/15018948/191353722-d24bcfdf-c1ec-4f62-b0f7-13f30150a7f3.png)
![image](https://user-images.githubusercontent.com/15018948/191353775-04b82e4d-e3d0-4031-aaeb-8e2e21597db0.png)
![image](https://user-images.githubusercontent.com/15018948/191353880-6b0870f6-bcf1-49a9-8ce9-efac72da17ea.png) 

</details>

2022-10-31 15:24 UTC, EncryptedDev requested changes

2022-10-31 15:24 UTC, EncryptedDev commented on websites/F/Flat/presence.ts
> +			presenceData.details = title ? "Viewing help:" : "Viewing help";
Ideally shouldn't have colons (`:`)
```suggestion
			presenceData.details = title ? "Viewing help" : "Viewing help";
```

2022-10-31 15:24 UTC, EncryptedDev commented on websites/F/Flat/presence.ts
> +		presenceData.details = "Viewing a collection:";
Ideally shouldn't have colons (`:`)
```suggestion
		presenceData.details = "Viewing a collection";
```

2022-10-31 21:11 UTC, EncryptedDev approved these changes

2022-11-02 08:01 UTC, Bas950 approved these changes

2022-11-02 08:01 UTC, merged