fix(Dsc.gg): update presence
PreMiD/Presences pull request #6958
Opened 2022-10-31 11:23 UTC by DiscordAnaxes

## Description 

Yearly update of some of my presences.

Version 1.1.0, updates and/or implements the following:
- New search support
- Removed unsupported/no longer existing paths.
- New assets.

I apologise if something is incorrect. I haven't used PreMiD in a long time. 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary>Image of search system working (old logo - discord cache)</summary>
![image](https://user-images.githubusercontent.com/68460474/198995406-ed418ce7-eaab-41a8-9273-a48e63c9924e.png)
</details>

2022-10-31 15:39 UTC, EncryptedDev commented
Will push a commit shortly to resolve CI

2022-10-31 15:42 UTC, EncryptedDev requested changes
Inline colons are allowed (e.g. L36); multiline colons aren't (e.g. L53)

2022-10-31 15:42 UTC, EncryptedDev commented on websites/D/Dsc.gg/presence.ts
> +						presenceData.details = "New link creation:";
```suggestion
						presenceData.details = "New link creation";
```

2022-11-02 21:03 UTC, EncryptedDev approved these changes

2022-11-03 13:29 UTC, Bas950 approved these changes

2022-11-03 13:29 UTC, merged