fix(Caards): meet new standard
PreMiD/Presences pull request #6962
Opened 2022-10-31 13:35 UTC by DiscordAnaxes

## Description 

Yearly update of some of my presences. 

Version 1.0.12, updates and/or implements the following (Extremely small update, however planning on implementing some other features in the future.): 
- Updated static page system (now using a record)

I apologise if something is incorrect. I haven't used PreMiD in a long time. 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary>Static record system (and other stuff working)</summary>

![Image_1](https://us-east-1.tixte.net/uploads/cdn.anaxes.codes/DiscordCanary_p2aa428Kve.png)
![Image_2](https://us-east-1.tixte.net/uploads/cdn.anaxes.codes/DiscordCanary_sSrDwR5DnH.png)
![Image_3](https://us-east-1.tixte.net/uploads/cdn.anaxes.codes/DiscordCanary_ooX1u2tl42.png)

</details>

2022-10-31 15:38 UTC, EncryptedDev requested changes

2022-10-31 16:20 UTC, theusaf requested changes

2022-11-01 13:16 UTC, DarkVillager requested changes

2022-11-01 13:16 UTC, DarkVillager commented on websites/C/Caards/presence.ts
>  		showButtons = await presence.getSetting<boolean>("buttons"),
One promise.

2022-11-02 14:21 UTC, EncryptedDev approved these changes

2022-11-02 17:03 UTC, Bas950 approved these changes

2022-11-02 17:03 UTC, merged