fix(Audible): support multiple domain name
PreMiD/Presences pull request #6963
Opened 2022-10-31 14:01 UTC by Kozou4ever

## Description 
Add multi-domain name support using RegEx functionality.
+ Resolves #6860 

## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![screen1](https://i.imgur.com/Q251jeT.png)

![screen2](https://i.imgur.com/yaMajIL.png)

</details>

2022-10-31 15:46 UTC, EncryptedDev requested changes

2022-10-31 15:46 UTC, EncryptedDev commented on websites/A/Audible/metadata.json
> +	"version": "1.0.1",
Functionality is being added thus minor should be bumped instead
```suggestion
	"version": "1.1.0",
```

2022-10-31 21:13 UTC, EncryptedDev approved these changes

2022-11-02 08:02 UTC, Bas950 approved these changes

2022-11-02 08:02 UTC, merged