feat(e-z): new pages and logo update;
PreMiD/Presences pull request #6976
Opened 2022-11-05 11:55 UTC by tsoxas

## Description 
Updated the logo and banner to use the new ones and added some pages that were previously missing

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
![image](https://cdn.e-z.host/e-zimagehosting/84e674be-f5d0-440a-ba36-9564b22d79f1/3fg2y09olh0gb3m811.png)
![image](https://cdn.e-z.host/e-zimagehosting/84e674be-f5d0-440a-ba36-9564b22d79f1/qszahym7ca4chwls23.png)
</details>

2022-11-05 12:07 UTC, ignSKRRRTT commented
I love you tsoxas!!!! Big fan!

2022-11-05 12:24 UTC, EncryptedDev requested changes

2022-11-05 12:24 UTC, EncryptedDev commented on websites/E/e-z/presence.ts
> +					break;
These aren't really needed

2022-11-05 12:24 UTC, EncryptedDev commented on websites/E/e-z/presence.ts
> +					presenceData.state = "Reading about a shit host";
Explicit words are prohibited

2022-11-05 12:24 UTC, EncryptedDev commented on websites/E/e-z/presence.ts
> +					presenceData.state = "Looking at pictures of oliver";
If "Oliver" is a proper noun, it should be given an upper case O

2022-11-05 12:24 UTC, EncryptedDev commented on websites/E/e-z/metadata.json
> +	"version": "1.0.1",
Functionality was added so this should be a minor version bump instead

2022-11-09 13:26 UTC, EncryptedDev commented on websites/E/e-z/presence.ts
> +					presenceData.state = "Reading about a shit host";
Still not an acceptable string

2022-11-10 11:58 UTC, tsoxas commented on websites/E/e-z/presence.ts
> +					presenceData.state = "Reading about a shit host";
Ok I completely removed it

2022-11-11 22:14 UTC, EncryptedDev approved these changes

2022-11-12 10:23 UTC, Bas950 approved these changes

2022-11-12 10:23 UTC, merged