Add Animeflix
PreMiD/Presences pull request #6983
Opened 2022-11-07 19:09 UTC by Micotsu

Pull request to add my site https://animeflix.live.

2022-11-08 02:17 UTC, shiseni commented
You need `yarn format`

2022-11-08 02:39 UTC, shiseni commented on websites/A/Animeflix/presence.ts
> +  console.log(pathname)
Remove console.log.

2022-11-08 02:39 UTC, shiseni commented on websites/A/Animeflix/presence.ts
> +  else if(pathname === "/genres") presenceData.details = "Exploring Genres";
You can add a state. For example, when the anime information window appears, display the title. This also applies to the following lines.

2022-11-08 02:39 UTC, shiseni commented on websites/A/Animeflix/presence.ts
> +	});
You need to get strings like in this example #6973

2022-11-08 02:39 UTC, shiseni commented on websites/A/Animeflix/presence.ts
> +    presenceData.state = episodeName.content.includes("Episode") ? episodeName.content : `${epNum.content}. ${episodeName.content}`
Here you can add video playback duration and a small image with action (play/pause).

2022-11-08 03:35 UTC, shiseni commented on websites/A/Animeflix/presence.ts
> +  console.log(pathname)
```suggestion
```

2022-11-08 03:45 UTC, shiseni commented on websites/A/Animeflix/presence.ts
> +	});
You need to get strings like in this example https://github.com/PreMiD/Presences/blob/5e5f99668ba4800524e66c2a3fc9fd38755025c6/websites/S/Skribbl.io/presence.ts#L14

2022-11-08 03:45 UTC, shiseni commented on websites/A/Animeflix/presence.ts
> +  else if(pathname === "/genres") presenceData.details = "Exploring Genres";
You can add a state. For example, when the anime information window appears, display the title. This also applies to the following lines.

2022-11-08 03:45 UTC, shiseni commented on websites/A/Animeflix/presence.ts
> +    presenceData.state = episodeName.content.includes("Episode") ? episodeName.content : `${epNum.content}. ${episodeName.content}`
Here you can add video playback duration and a small image with action (play/pause).

2022-11-08 03:51 UTC, shiseni commented on websites/A/Animeflix/presence.ts
> +    const epNum = <HTMLMetaElement>document.querySelector('meta[name="anime-skip.episode.number"]');
```suggestion
    const showName = document.querySelector<HTMLMetaElement>('meta[name="anime-skip.show.name"]');
    const episodeName = document.querySelector<HTMLMetaElement>('meta[name="anime-skip.episode.name"]');
    const epNum = document.querySelector<HTMLMetaElement>('meta[name="anime-skip.episode.number"]');
```

2022-11-08 14:35 UTC, Micotsu commented
Thanks for the help! I didn't feel the need for any extra features as my users and me are happy with the current format. I might add some more later.

2022-11-08 23:21 UTC, theusaf requested changes

2022-11-08 23:21 UTC, theusaf commented on websites/A/Animeflix/metadata.json
> +		"name": "Micotsu#2907"
Discriminator number is a mistake caused by an old version of `pmd`
```suggestion
		"name": "Micotsu"
```

2022-11-08 23:21 UTC, theusaf commented on websites/A/Animeflix/metadata.json
> +	"logo": "https://i.imgur.com/4hiyxuW.png",
Logos should be at least 512x512px.

2022-11-08 23:21 UTC, theusaf commented on websites/A/Animeflix/metadata.json
> +	"thumbnail": "https://i.imgur.com/XmDNhW4.png",
This thumbnail may be a bit small/low-quality, but I'm not sure if it *needs* to be replaced.

2022-11-08 23:21 UTC, theusaf commented on websites/A/Animeflix/metadata.json
> +	"url": "animeflix.live",
Site supports `www` 'subdomain'.
```suggestion
	"url": ["animeflix.live", "www.animeflix.live"],
```

2022-11-08 23:21 UTC, theusaf commented on websites/A/Animeflix/presence.ts
> +				},
Buttons that lead to home pages are not allowed.

I'm also not sure if buttons to Discord servers are allowed.

2022-11-09 13:22 UTC, EncryptedDev commented
Title doesn't follow commit convention

2022-11-11 22:03 UTC, EncryptedDev approved these changes

2022-11-12 10:22 UTC, Bas950 approved these changes

2022-11-12 10:22 UTC, merged