feat(BeatLeader): add presence
PreMiD/Presences pull request #6994
Opened 2022-11-12 19:19 UTC by joerkig

## Description 

Add presence for BeatLeader

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![Discord_jtkj65Apzo](https://user-images.githubusercontent.com/44418429/201491027-4600bba1-b64a-4c5a-b4ea-41a95c60dcc3.png)
![Discord_Nr8SFp0ZB0](https://user-images.githubusercontent.com/44418429/201491029-813403f2-1247-4a16-908f-f0dc1da5599a.png)
![Discord_RM8CVGcU5m](https://user-images.githubusercontent.com/44418429/201491030-6de67f9b-5c80-4ddf-9d77-2efaeb8b77d1.png)
![Discord_ZeVWbyzY4h](https://user-images.githubusercontent.com/44418429/201491031-fa8ad843-7cb7-4a62-89cb-df65a2793de7.png)
![D2RgEQskyH](https://user-images.githubusercontent.com/44418429/201491038-d72a842f-b667-4e1f-8077-866d1924fbbb.png)

</details>

2022-11-14 17:35 UTC, theusaf requested changes

2022-11-14 17:35 UTC, theusaf commented on websites/B/BeatLeader/metadata.json
> +		"name": "joerkig#1337"
Discriminator added mistakenly by old version of `pmd`
```suggestion
		"name": "joerkig"
```

2022-11-17 17:23 UTC, EncryptedDev approved these changes

2022-11-18 06:42 UTC, Bas950 approved these changes

2022-11-18 06:42 UTC, merged