fix(Tidal): Presence not working after updates
PreMiD/Presences pull request #7005
Opened 2022-11-16 19:48 UTC by VirusBLITZ

## Description 

After some updates on Tidal's side the presence stopped working as intended, this PR accounts for all the relevant changes.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![title playing on loop](https://user-images.githubusercontent.com/58221423/202276931-19741e68-7625-4a5f-be20-7fe7125dd6c5.png)
![regular title in user popout](https://user-images.githubusercontent.com/58221423/202277338-080f1912-95d1-485c-b50c-1b668d0ef922.png)

</details>

2022-11-16 20:30 UTC, EncryptedDev requested changes
Remove package lock changes

2022-11-16 20:42 UTC, VirusBLITZ commented
@EncryptedDev all done 👍

2022-11-17 21:27 UTC, EncryptedDev approved these changes

2022-11-18 06:40 UTC, Bas950 approved these changes

2022-11-18 06:40 UTC, merged