feat(asset.party): add presence
PreMiD/Presences pull request #7008
Opened 2022-11-16 23:11 UTC by DwifteJB

## Description 

Adds presence to asset.party

## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![key](https://user-images.githubusercontent.com/67983181/202314301-a9bcee65-4bc3-4cd2-873b-70f19808bbff.PNG)
![api-working](https://user-images.githubusercontent.com/67983181/202314297-b0408b03-4569-4d84-a081-092ce63c93dd.PNG)

</details>

2022-11-16 23:12 UTC, DwifteJB commented
new version of https://github.com/PreMiD/Presences/pull/7007

since the lint caused one of the checks to fail

2022-11-17 02:53 UTC, theusaf requested changes

2022-11-17 02:53 UTC, theusaf commented on websites/A/asset.party/metadata.json
> +		"name": "Dwifte#0661"
Discriminator added incorrectly by old version of `pmd`
```suggestion
		"name": "Dwifte"
```

2022-11-17 02:53 UTC, theusaf commented on websites/A/asset.party/presence.ts
> +/* eslint-disable unicorn/prefer-switch */
Why are we disabling eslint?
```suggestion
```

2022-11-17 02:53 UTC, theusaf commented on websites/A/asset.party/metadata.json
> +	"logo": "https://i.imgur.com/vWSslVh.png",
Logos should be 512x512px at minimum. Find or create a larger version (using something like waifu2x).

2022-11-17 02:54 UTC, theusaf commented
> New version of #7007 Lint had caused the Presence Validator to fail.

You do not need to close and create a new PR. Simply push new commits to your branch, and it will automatically appear in this PR, and re-run the checks.

2022-11-17 07:51 UTC, DwifteJB commented
I tried to for about 30 minutes and I was getting some stupid issues with git desktop, it also seemed I had a slightly outdated version of the repo which is why the other json files had linted

2022-11-17 16:44 UTC, DwifteJB commented on websites/A/asset.party/presence.ts
> +		presenceData.details = "Going through key torture...";
It's what the site called it, assumed it was safe for it to use. Changed anyway.

![image](https://user-images.githubusercontent.com/67983181/202505993-f11efffb-d0b7-4bb4-b138-14b3ce274cb8.png)

2022-11-17 16:46 UTC, DwifteJB commented
Addressed all comments.

2022-11-17 17:34 UTC, theusaf commented on websites/A/asset.party/presence.ts
> +				const Details = document.querySelectorAll(".page-header-block");
`camelCase` should be used here too.

2022-11-17 18:42 UTC, DwifteJB commented
Addressed camalCase comment.

2022-11-17 19:50 UTC, theusaf requested changes

2022-11-17 19:50 UTC, theusaf commented on websites/A/asset.party/presence.ts
> +}
Asset names should be capitalized.

2022-11-17 21:24 UTC, EncryptedDev commented
Low quality

2022-11-17 21:24 UTC, closed without merging

2022-11-17 21:25 UTC, DwifteJB commented
gotta love when a few hours of your work just goes away after someone goes "low quality"

2022-11-18 22:27 UTC, EncryptedDev commented
> gotta love when a few hours of your work just goes away after someone goes "low quality"

Take a look at the detail we expect from other presences. Try to include a range of features utilising timestamps, buttons, Records or what not. This is a fairly basic presence and isn't something we allow to be merged anymore.

You're very welcome to DM me on Discord (Encrypted#0001) via the community guild where I'll give you further information too