feat(ITV Hub): rebrand ITV Hub to ITVX
PreMiD/Presences pull request #7023
Opened 2022-11-18 20:21 UTC by hiitsdan

## Description 
ITV recently released ITVX which completely replaces the previous ITV Hub. This PR updates the ITV Hub presence to support the full ITVX rebrand.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://user-images.githubusercontent.com/37845774/202795229-fd328ac6-79f8-4ff4-a5ac-8f1fbc1e846e.png)
![image](https://user-images.githubusercontent.com/37845774/202795270-e06b2efd-ecec-4569-8b38-3e78c9395032.png)
![image](https://user-images.githubusercontent.com/37845774/202795280-1bd51b60-fea2-4507-bb49-5e19336ae6c5.png)

</details>

2022-11-18 20:45 UTC, theusaf requested changes

2022-11-18 20:45 UTC, theusaf commented on websites/I/ITVX/presence.ts
> +			largeImageKey: "itv_logo",
Imgur URLs are preferred over Discord asset names now, replace.
```suggestion
			largeImageKey: "https://i.imgur.com/XisKvdg.png",
```

2022-11-18 20:45 UTC, theusaf commented on websites/I/ITVX/presence.ts
> +						presenceData.smallImageText = "Paused";
Replace with Imgur URLs and use an `Assets` enum

2022-11-18 20:45 UTC, theusaf commented on websites/I/ITVX/presence.ts
> +		path = document.location.pathname,
```suggestion
		{ pathname: path } = document.location,
```
or
```suggestion
		{ pathname } = document.location,
```

2022-11-18 22:24 UTC, EncryptedDev requested changes

2022-11-18 22:24 UTC, EncryptedDev commented on websites/I/ITVX/presence.ts
> +	playing = "https://i.imgur.com/1CbifM8.png",
enum properties should be TitleCase

2022-11-18 22:24 UTC, EncryptedDev commented on websites/I/ITVX/presence.ts
> +	};
These should be 'proper' functions invoked with the `function` keyword instead of variable functions

2022-11-20 21:46 UTC, hiitsdan commented on websites/I/ITVX/presence.ts
> +}
You're right. Not overly familiar with TS so was not aware generics were a thing.

2022-11-22 17:44 UTC, Bas950 approved these changes

2022-11-25 17:48 UTC, EncryptedDev approved these changes

2022-11-25 17:48 UTC, merged