perf(FurAffinity): optimize code
PreMiD/Presences pull request #7091
Opened 2022-12-26 09:17 UTC by DarkVillager

## Description 

optimized code
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://user-images.githubusercontent.com/42322979/209529988-6ce7abd9-6bbb-4ca5-b8ea-178479fcd55f.png">
<img src="https://user-images.githubusercontent.com/42322979/209529992-f7e332e0-ce36-4546-96bd-c296ae5f6827.png">
<img src="https://user-images.githubusercontent.com/42322979/209529994-40342a53-0057-4429-a74d-b52940349bd3.png">
<img src="https://user-images.githubusercontent.com/42322979/209529997-75d17708-d06f-4ae4-ac4a-1eacb63cfa17.png">

</details>

2022-12-29 09:20 UTC, DarkVillager commented on websites/F/FurAffinity/presence.ts
> +	if (!search?.value && !presenceData.buttons && pathname !== "/") {
I forgot that it returrs when searching
```suggestion
	if (!presenceData.buttons && pathname !== "/") {
```

2023-01-04 18:10 UTC, Bas950 requested changes

2023-01-04 18:10 UTC, Bas950 commented on websites/F/FurAffinity/presence.ts
> +	} else return Assets.Logo;
```suggestion
	if (!path) return Assets.Logo;
	if (path.includes(hostname)) return `https://${path.replace("//", "")}`;
	else return `https://${hostname}${path}`;
```

2023-01-05 18:22 UTC, Bas950 approved these changes

2023-01-11 22:16 UTC, EncryptedDev approved these changes

2023-01-11 22:17 UTC, merged