feat(Yugen Anime): add presence
PreMiD/Presences pull request #7092
Opened 2022-12-26 14:15 UTC by DiscordAnaxes

## Description 

This pr implements, adds and or fixes the following:
- Resolves #7090 

## Acknowledgements
- [ ] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ ] I linted the code by running `yarn format`
- [ ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary>Watching an episode</summary>

![image](https://user-images.githubusercontent.com/68460474/209557293-43aec72d-a537-4103-8262-fc8b3a4b48de.png)
</details>
<details>
<summary>Viewing a series/anime</summary>

![image](https://user-images.githubusercontent.com/68460474/209557323-1f9d9633-1abc-418d-9a30-e706825fde94.png)
</details>
<details>
<summary>Viewing a series/anime</summary>

![image](https://user-images.githubusercontent.com/68460474/209557323-1f9d9633-1abc-418d-9a30-e706825fde94.png)
</details>
<details>
<summary>Viewing a anime review</summary>

![image](https://user-images.githubusercontent.com/68460474/209557380-a540ba62-3e15-4990-99a9-8cfdc41b3684.png)
</details>
<details>
<summary>Watching a movie</summary>

![image](https://user-images.githubusercontent.com/68460474/209557667-36cab254-2804-4f6c-9ea7-6315e91b5d87.png)
</details>

2022-12-26 19:37 UTC, crashbash317 commented
great progress so far, thank you.

2022-12-28 12:22 UTC, DarkVillager requested changes

2022-12-28 12:22 UTC, DarkVillager commented on websites/Y/Yugen Anime/presence.ts
> +			watchingSeries: "general.watchingSeries",
This one is not used.

2022-12-28 12:35 UTC, DiscordAnaxes commented on websites/Y/Yugen Anime/presence.ts
> +			watchingSeries: "general.watchingSeries",
I indeed do not.

2023-01-04 18:14 UTC, Bas950 approved these changes

2023-01-11 22:16 UTC, EncryptedDev approved these changes

2023-01-11 22:16 UTC, merged

2023-01-12 15:50 UTC, crashbash317 commented
![image](https://user-images.githubusercontent.com/50211873/212113975-029a7ae9-f997-47b1-8ca5-972782f369d5.png)
Presence not showing anime, episode, timestamp, ect.

2023-01-12 18:37 UTC, DarkVillager commented
> ![image](https://user-images.githubusercontent.com/50211873/212113975-029a7ae9-f997-47b1-8ca5-972782f369d5.png) Presence not showing anime, episode, timestamp, ect.

@DiscordAnaxes

2023-01-13 11:41 UTC, DiscordAnaxes commented
> ![image](https://user-images.githubusercontent.com/50211873/212113975-029a7ae9-f997-47b1-8ca5-972782f369d5.png) Presence not showing anime, episode, timestamp, ect.

Odd it was working before. Did they update their website by any chance? Nonetheless I will fix it shortly.

2023-02-06 20:46 UTC, pmksch101 commented
> > ![image](https://user-images.githubusercontent.com/50211873/212113975-029a7ae9-f997-47b1-8ca5-972782f369d5.png) Presence not showing anime, episode, timestamp, ect.
> 
> Odd it was working before. Did they update their website by any chance? Nonetheless I will fix it shortly.

could you look into this please?