perf(Nuxt.js): optimize code
PreMiD/Presences pull request #7095
Opened 2022-12-29 09:58 UTC by DarkVillager

## Description 

Optimised the code
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://user-images.githubusercontent.com/42322979/209935105-9048d83e-3338-40f8-9e3e-c714d251289e.png">
<img src="https://user-images.githubusercontent.com/42322979/209935107-80b3a447-9b90-4046-95ce-8c6622d52b24.png"><img src="https://user-images.githubusercontent.com/42322979/209935109-115c6114-c4e9-4427-aec4-a51b90b8b74a.png"><img src="https://user-images.githubusercontent.com/42322979/209935112-7e6c408c-cce9-48e3-b10e-23b10ca1f33b.png"><img src="https://user-images.githubusercontent.com/42322979/209935113-34758bbf-2af7-4042-97f4-4538510a5d69.png"><img src="https://user-images.githubusercontent.com/42322979/209935114-e87e006e-7f0a-460a-b8f8-253b6990ab15.png"><img src="https://user-images.githubusercontent.com/42322979/209935115-1ec2acaf-a55c-49c7-b686-dd382e4625c8.png">

</details>

2023-01-04 18:19 UTC, Bas950 requested changes

2023-01-04 18:19 UTC, Bas950 commented on websites/N/Nuxt.js/presence.ts
> +	} else return "Undefined";
```suggestion
	if (!string) return "Undefined";
	return (
		string.trim().charAt(0).toUpperCase() +
		string.trim().slice(1).toLowerCase()
	);
```

2023-01-04 18:19 UTC, Bas950 commented on websites/N/Nuxt.js/presence.ts
> +	} else return Assets.Logo;
```suggestion
	if (!path) return Assets.Logo;
	if (path.includes(hostname)) return `https://${path.replace("//", "")}`;
	else return `https://${hostname}${path}`;
```

2023-01-11 22:16 UTC, EncryptedDev commented on websites/N/Nuxt.js/presence.ts
> +	} else return "Undefined";
Still waiting for this one

2023-01-14 09:37 UTC, Bas950 approved these changes

2023-01-21 10:39 UTC, EncryptedDev requested changes

2023-01-21 10:39 UTC, EncryptedDev commented on websites/N/Nuxt.js/presence.ts
> +					details: "Viewing the nuxt.js team",
```suggestion
					details: "Viewing the Nuxt.js team",
```

2023-01-28 21:45 UTC, EncryptedDev approved these changes

2023-01-28 21:45 UTC, merged