fix(Wiki.gg): rewrite/fix all issues
PreMiD/Presences pull request #7102
Opened 2023-01-03 09:43 UTC by DarkVillager

## Description 

rewrote presence to fix all issues
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

2023-01-04 18:28 UTC, Bas950 requested changes

2023-01-04 18:28 UTC, Bas950 commented on websites/W/Wiki.gg/presence.ts
> +}
```suggestion
	if (!string) return "Undefined";
	return (
		string.trim().charAt(0).toUpperCase() +
		string.trim().slice(1).toLowerCase()
	);
}
```

2023-01-05 18:24 UTC, Bas950 requested changes

2023-01-05 18:24 UTC, Bas950 commented on websites/W/Wiki.gg/presence.ts
> +	);
```suggestion
	return string.trim().charAt(0).toUpperCase() + string.trim().slice(1).toLowerCase();
```
cant it just be this?

2023-01-06 07:50 UTC, DarkVillager commented on websites/W/Wiki.gg/presence.ts
> +	);
idem dito

2023-01-14 09:39 UTC, Bas950 approved these changes

2023-01-21 10:40 UTC, EncryptedDev approved these changes

2023-01-21 10:40 UTC, merged