added new domain
PreMiD/Presences pull request #7108
Opened 2023-01-05 15:26 UTC by HerrSammyDE

Signed-off-by: Sam Schumacher <38103916+HerrSammyDE@users.noreply.github.com>

## Description 

## Acknowledgements
- [ ] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ ] I linted the code by running `yarn format`
- [ ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

2023-01-06 11:46 UTC, Timeraa requested changes
Please include the `presence.ts` changes from #7107 in this PR

2023-01-13 20:51 UTC, EncryptedDev approved these changes

2023-01-14 09:40 UTC, Bas950 approved these changes

2023-01-14 09:40 UTC, merged

2023-01-14 13:40 UTC, DarkVillager commented
@Bas950 Prettier was not ran here so the CI keeps erroring.

2023-01-14 13:42 UTC, Bas950 commented
> @Bas950 Prettier was not ran here so the CI keeps erroring.

@DarkVillager can you pr it for me