Feat(Mangas-Origines): add website support
PreMiD/Presences pull request #7110
Opened 2023-01-06 16:59 UTC by Oneloutre

Adding Mangas-Origines to supported websites

Signed-off-by: Onelots <54822802+Oneloutre@users.noreply.github.com>

## Description 
Adding support for mangas-origines website

## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

2023-01-07 09:54 UTC, DarkVillager commented
@Oneloutre struggled with getting the images to load so here:
<img src="https://user-images.githubusercontent.com/54822802/211059076-57c93d90-15d5-4f14-a38d-fe171f4f5550.png">

<img src="https://user-images.githubusercontent.com/54822802/211059363-412f0f11-977d-4266-8aa2-886fa8ab90b2.png">

<img src="https://user-images.githubusercontent.com/54822802/211059512-ce57e3ab-f8b6-4b8b-8a15-356c79484f3f.png">

<img src="https://user-images.githubusercontent.com/54822802/211059664-e1894dd5-e528-416f-afbd-d8d8080fe093.png">

2023-01-07 17:42 UTC, Oneloutre commented
thanks @DarkVillager, I dunno why it wasn't showing up 👍

2023-01-13 20:56 UTC, EncryptedDev commented
I'm baffled, was your [comment](https://github.com/PreMiD/Presences/pull/7110#issuecomment-1374428702) suggesting something hasn't been fixed or a thanks for fixing it? @DarkVillager

2023-01-13 21:02 UTC, Oneloutre commented
> I'm baffled, was your [comment](https://github.com/PreMiD/Presences/pull/7110#issuecomment-1374428702) suggesting something hasn't been fixed or a thanks for fixing it? @DarkVillager

I dunno why, I couldn't upload images 🤷 so he did it for me

2023-01-14 09:42 UTC, Bas950 requested changes

2023-01-14 09:42 UTC, Bas950 commented on websites/M/Mangas-Origines/metadata.json
> +	"logo": "https://i.imgur.com/MqvvhSw.png",
Logo must be 512x512

2023-01-14 09:42 UTC, Bas950 commented on websites/M/Mangas-Origines/presence.ts
> +			largeImageKey: "https://i.imgur.com/MqvvhSw.png",
`largeImageKey` must be 512x512

2023-01-20 08:31 UTC, DarkVillager commented on websites/M/Mangas-Origines/metadata.json
> +	"thumbnail": "https://i.imgur.com/KZ3FSWl.png",
you changed the thumbnail not the logo

2023-01-21 21:30 UTC, EncryptedDev commented
The presence seems to only support a handful of pages, hence why I've closed the PR due to it being low quality

2023-01-21 21:30 UTC, closed without merging