refactor(pixiv): redo codebase and fix bugs
PreMiD/Presences pull request #7149
Opened 2023-01-29 12:49 UTC by RisingSunLight42

## Description 

### Changelog

- fix bugs in querySelectors
- replace tons of if statements by a Record
- replace others if statements by a Switch
- add buttons for some pages
- switched the owner metadata to me with the agreement of @Bas950 
- Resolves #7035 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![pixiv_proof_6](https://user-images.githubusercontent.com/85577959/215327006-bdb2e7db-4b9a-4860-b3a7-30fc2eea7848.PNG)

![pixiv_proof_5](https://user-images.githubusercontent.com/85577959/215327007-138d1869-c079-4e92-81d1-59be3bdf664b.png)

![pixiv_proof_4](https://user-images.githubusercontent.com/85577959/215327008-c53e1165-bb38-4ee9-8da3-c31c608381f5.png)

![pixiv_proof_3](https://user-images.githubusercontent.com/85577959/215327001-3acb038a-4e0a-47b9-8d00-89a89e95c042.PNG)

![pixiv_proof_2](https://user-images.githubusercontent.com/85577959/215327002-c32fd4d1-ccf3-4c1d-9065-5868e7f9bda2.PNG)

![pixiv_proof_1](https://user-images.githubusercontent.com/85577959/215327005-c3599476-f154-4b4a-85ff-becb06ff4651.png)

</details>

2023-02-03 19:03 UTC, Bas950 approved these changes

2023-02-11 16:49 UTC, EncryptedDev requested changes

2023-02-11 16:49 UTC, EncryptedDev commented on websites/P/pixiv/presence.ts
> +		"ranking.php": { details: "Viewing Novels Ranking" },
```suggestion
		"": { details: "Viewing homepage" },
		fanbox: { details: "Viewing fanbox" },
		event: { details: "Browsing events..." },
		"history.php": { details: "Browsing history" },
		bookmark: { details: "Viewing bookmarks" },
		"mypixivall.php": { details: "Browsing my pixiv" },
		group: { details: "Browsing group" },
		idea: { details: "Browsing idea" },
		howto: { details: "Browsing how-to" },
		eventadd: { details: "Ready to create an event" },
		profileevent: { details: "Manage event..." },
		premium: { details: "Viewing Premier Registered info" },
		"messages.php": { details: "Browsing private message" },
		"ugoiraupload.php": { details: "Submiting new Ugoira(Animations)" },
		manage: { details: "Managing artworks" },
		"settinguser.php": { details: "User settings", state: "Basic settings" },
		settingsnspost: {
			details: "User settings",
			state: "Post on social media",
		},
		"settingprofile.php": {
			details: "Profile settings",
			state: "Profile information",
		},
		"settingprofileimg.php": {
			details: "Profile settings",
			state: "Profile images",
		},
		"settingworkspace.php": {
			details: "Profile settings",
			state: "Workspace",
		},
		settinginfophp: { details: "Notification settings" },
		lives: { details: "Sketch- Browsing livestreams" },
		popular: { details: "Sketch- Viewing popular posts" },
		followings: { details: "Sketch- Viewing following posts" },
		tagshistory: { details: "Sketch- Viewing tags:", state: "Featured tags" },
		"upload.php": { details: "Submitting new novel" },
		discovery: { details: "Viewing recommended novels" },
		"ranking.php": { details: "Viewing novels ranking" },
```

2023-02-14 21:22 UTC, EncryptedDev approved these changes

2023-02-14 21:23 UTC, merged