feat(Canvas): add privacy mode
PreMiD/Presences pull request #7155
Opened 2023-02-01 01:08 UTC by theusaf

## Description 

Adds a privacy mode to Canvas (disabled by default) allowing users to hide specific details about the things they are interacting with on Canvas.
Resolves #7140

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img width="240" alt="2023-01-31 17_01_00" src="https://user-images.githubusercontent.com/32113157/215919729-3d7e5d40-5514-46be-8c0d-7673739376c9.png">

</details>

2023-02-02 16:32 UTC, DarkVillager requested changes

2023-02-02 16:32 UTC, DarkVillager commented on websites/C/Canvas/metadata.json
>  	"logo": "https://i.imgur.com/DRlJvzX.png",
Now that the presence is getting edited/updated, lets change the logo to 512x512
```suggestion
	"logo": "https://i.imgur.com/Bqsnmop.png",
```

2023-02-02 16:32 UTC, DarkVillager commented on websites/C/Canvas/presence.ts
>  			largeImageKey: "https://i.imgur.com/DRlJvzX.png",
Same here
```suggestion
			largeImageKey: "https://i.imgur.com/Bqsnmop.png",
```

2023-02-03 22:06 UTC, Bas950 approved these changes

2023-02-14 21:20 UTC, EncryptedDev approved these changes

2023-02-14 21:20 UTC, merged