feat(Skribbl.io): update presence and add details
PreMiD/Presences pull request #7157
Opened 2023-02-01 05:27 UTC by theusaf

## Description 

* Updates the presence for the new UI
* Adds game details to the presence

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img width="243" alt="2023-01-31 21_09_15" src="https://user-images.githubusercontent.com/32113157/215958729-6c32c774-bb26-47e8-a436-58ae432805f0.png">
<img width="235" alt="2023-01-31 21_02_38" src="https://user-images.githubusercontent.com/32113157/215958738-2748742e-5f02-46ef-8b4e-16cb2b006825.png">
<img width="220" alt="2023-01-31 21_04_08" src="https://user-images.githubusercontent.com/32113157/215958739-deae6930-5204-4a55-9596-753d565faf65.png">

</details>

2023-02-02 16:27 UTC, DarkVillager requested changes

2023-02-02 16:27 UTC, DarkVillager commented on websites/S/Skribbl.io/metadata.json
>  	"logo": "https://i.imgur.com/au4OO2A.jpg",
Let's change it to 512x512
```suggestion
	"logo": "https://i.imgur.com/EYcWQmj.png",
```

2023-02-02 16:27 UTC, DarkVillager commented on websites/S/Skribbl.io/presence.ts
> +	Logo = "https://i.imgur.com/au4OO2A.jpg",
```suggestion
	Logo = "https://i.imgur.com/EYcWQmj.png",
```

2023-02-02 16:27 UTC, DarkVillager commented on websites/S/Skribbl.io/presence.ts
> +	Avatar = "https://i.imgur.com/oMq5qpz.png",
```suggestion
	Avatar = "https://i.imgur.com/gDUX4ox.png",
```
or
```suggestion
	Avatar = "https://i.imgur.com/Uunb9C6.png",
```

2023-02-03 22:13 UTC, Bas950 approved these changes

2023-02-14 21:22 UTC, EncryptedDev approved these changes

2023-02-14 21:22 UTC, merged