feat(NightDesign): inital night design basic presence
PreMiD/Presences pull request #7169
Opened 2023-02-07 19:15 UTC by BCCSTeam

## Description 
Repull request because of stupidness but with every requested change
feat(NightDesign): inital night design basic presence

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
![wWuhU](https://user-images.githubusercontent.com/17223660/217342976-b0c27f5d-b73e-4f87-9d74-cc441b452ff6.png)
![RmFKU](https://user-images.githubusercontent.com/17223660/217342980-aa90b5e0-2a8e-44eb-a421-25f64960bcff.png)

2023-02-08 05:28 UTC, theusaf requested changes
Note: You do not have to close and create a new PR when making new commits. They will automatically appear in the PR and re-run the checks.

2023-02-08 05:28 UTC, theusaf commented on websites/N/NightDesign/metadata.json
> +    "name": "BassKatze#0001"
```suggestion
    "name": "BassKatze"
```

2023-02-08 05:28 UTC, theusaf commented on websites/N/NightDesign/metadata.json
> +}
This file is formatted incorrectly. Use `yarn format` to format it.

2023-02-11 13:13 UTC, DarkVillager requested changes

2023-02-11 13:13 UTC, DarkVillager commented on websites/N/NightDesign/presence.ts
> +			strings.prefix + presenceData.details + strings.suffix;
```suggestion
			`${strings.prefix}  ${presenceData.details} ${strings.suffix}`;
```

2023-02-11 13:13 UTC, DarkVillager commented on websites/N/NightDesign/presence.ts
> +					)
Simplify the selectors.
```suggestion
document.querySelector('[class="breadcrumb justify-content-end"]').lastChild?.textContent
```
or
```suggestion
textContent('[class="page-header-title"]')?.split(": ")[1]
```

2023-02-11 13:13 UTC, DarkVillager commented on websites/N/NightDesign/presence.ts
> +								"div.page-content > div.row > div.col-md-7 > div:nth-child(2) > div.card-block > p > code:nth-child(1)"
Simplify selectors like this:
```suggestion
								'code[routerlink="/resources"]'
```

2023-02-11 13:13 UTC, DarkVillager commented on websites/N/NightDesign/presence.ts
> +						textContent("div.card.mini-profile > div > div > h6 > span > span")
Also here simplify selectors like this:
```suggestion
						textContent('[class="d-inline-block"] > h6')
```

2023-02-15 08:55 UTC, DarkVillager requested changes

2023-02-15 08:55 UTC, DarkVillager commented on websites/N/NightDesign/presence.ts
> +					textContent("div.page-header > div > div > div.col-md-8 > div > h5")
```suggestion
					textContent('[class="page-header-title"]')
```

2023-02-15 08:55 UTC, DarkVillager commented on websites/N/NightDesign/presence.ts
> +			case "server":
Cant seem to access this page?

2023-02-15 18:11 UTC, BCCSTeam commented on websites/N/NightDesign/presence.ts
> +			case "server":
not accessible yet

2023-02-20 18:05 UTC, Bas950 approved these changes

2023-02-21 07:49 UTC, Bas950 commented
Low quality presence, support more pages

2023-02-21 07:49 UTC, closed without merging