fix(AnimesOnlineGames): change name and domain
PreMiD/Presences pull request #7189
Opened 2023-02-21 02:47 UTC by Kuriel23

## Description 
Changed the old domain to new domain
Changed some sentences to new name
Changed the old name to new name

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
n/a
</details>

2023-02-21 06:52 UTC, theusaf requested changes

2023-02-21 06:52 UTC, theusaf commented on websites/A/Animes Games/metadata.json
> +	"version": "1.0.12",
Also, use `yarn format` to reformat the `metadata.json` file.
```suggestion
	"version": "1.0.0",
```

2023-02-26 03:28 UTC, EncryptedDev approved these changes

2023-02-26 11:53 UTC, Bas950 approved these changes

2023-02-26 11:53 UTC, merged