feat(Video Game Mods): add presence
PreMiD/Presences pull request #7197
Opened 2023-02-27 02:23 UTC by Kuriel23

## Description 
Presence for Video Game Mods, a website for downloading mods for video games
Requested by issue #6663 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
![image](https://user-images.githubusercontent.com/37979213/221457170-093f3249-c853-4b91-92e1-13a19f3fb2d4.png)
</details>

2023-02-27 13:18 UTC, DarkVillager requested changes

2023-02-27 13:18 UTC, DarkVillager commented on websites/V/Video Game Mods/presence.ts
> +			if (urlpath[1].startsWith("members")) {
why?

you could have just done this?:
```suggestion
case urlpath[1].startsWith("members")
```

2023-02-27 13:18 UTC, DarkVillager commented on websites/V/Video Game Mods/presence.ts
> +					urlpath[3].length > 0 ? urlpath[3].replace("bp-", "") : "profile"
Or just get it with a querySelector?
```suggestion
					document.querySelector('[class="data"]')?.textContent
```

2023-02-27 13:18 UTC, DarkVillager commented on websites/V/Video Game Mods/presence.ts
> +							)?.innerText
Replace all innerText by textContent

2023-02-27 13:18 UTC, DarkVillager commented on websites/V/Video Game Mods/presence.ts
> +							)?.innerText;
Replace all innerText by textContent

2023-02-27 13:18 UTC, DarkVillager commented on websites/V/Video Game Mods/presence.ts
> +							presenceData.details = "Viewing Mods of";
```suggestion
							presenceData.details = "Viewing mods of";
```

2023-02-27 13:18 UTC, DarkVillager commented on websites/V/Video Game Mods/presence.ts
> +						presenceData.details = "Uploading Mod of";
```suggestion
						presenceData.details = "Uploading mod of";
```

2023-02-27 13:18 UTC, DarkVillager commented on websites/V/Video Game Mods/presence.ts
> +						presenceData.details = "Managing Mods of";
```suggestion
						presenceData.details = "Managing mods of";
```

2023-03-01 20:19 UTC, Bas950 requested changes

2023-03-01 20:19 UTC, Bas950 commented on websites/V/Video Game Mods/metadata.json
> +		"name": "Kuriel#1411"
```suggestion
		"name": "Kuriel"
```

2023-03-02 23:45 UTC, theusaf requested changes

2023-03-02 23:45 UTC, theusaf commented on websites/V/Video Game Mods/presence.ts
> +					url: window.location.href,
In this repository, `document.location` is preferred over `window.location`
```suggestion
					url: document.location.href,
```

2023-03-03 18:03 UTC, DarkVillager commented
Please resolves requested changes that you have changed.

2023-03-03 20:32 UTC, Bas950 approved these changes

2023-03-04 01:36 UTC, EncryptedDev approved these changes

2023-03-04 01:36 UTC, merged