Feat(Coup Critique): add new presence
PreMiD/Presences pull request #7222
Opened 2023-03-08 15:10 UTC by RisingSunLight42

## Description 

Add new presence for the french strategy pokemon website "Coup Critique".

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![coup_critique_proof_8](https://user-images.githubusercontent.com/85577959/223749516-717c0658-044d-48b1-b9fd-1c3f1d343e69.gif)

![coup_critique_proof_7](https://user-images.githubusercontent.com/85577959/223749524-3a42f3ac-a901-4dde-9f44-494c9b1f0c1c.gif)

![coup_critique_proof_6](https://user-images.githubusercontent.com/85577959/223749527-153689bb-1dd0-49bf-84ef-369d01299bf3.png)

![coup_critique_proof_5](https://user-images.githubusercontent.com/85577959/223749533-de583661-a84d-4760-838d-c7b09d5f6c59.png)

![coup_critique_proof_4](https://user-images.githubusercontent.com/85577959/223749535-a2436b12-ec86-4f9e-b9e6-2fa0172024ed.png)

![coup_critique_proof_3](https://user-images.githubusercontent.com/85577959/223749539-4cbb2558-0161-47b4-9281-a09b9a21dca0.png)

![coup_critique_proof_2](https://user-images.githubusercontent.com/85577959/223749542-4232b4b3-fa6f-4634-a589-bb06179c57ce.png)

![coup_critique_proof_1](https://user-images.githubusercontent.com/85577959/223749546-1e7a7682-4132-41b8-b055-837b45e981f3.png)

</details>

2023-03-08 20:12 UTC, theusaf requested changes

2023-03-08 20:12 UTC, theusaf commented on websites/C/Coup Critique/metadata.json
> +	"url": "www.coupcritique.fr",
Site supports non-www domain.
```suggestion
	"url": [
		"www.coupcritique.fr",
		"coupcritique.fr"
	],
```

2023-03-10 08:02 UTC, DarkVillager approved these changes

2023-03-13 17:01 UTC, Bas950 approved these changes

2023-03-26 18:24 UTC, Timeraa approved these changes

2023-03-26 18:24 UTC, merged