feat(TabNews): add presence
PreMiD/Presences pull request #7223
Opened 2023-03-08 22:37 UTC by Kuriel23

## Description 
Presence for TabNews, a forum for programming and technology

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://user-images.githubusercontent.com/37979213/223867258-1289b04d-6a0f-43c8-9ef7-f64648204b14.png)

</details>

2023-03-08 23:33 UTC, theusaf requested changes

2023-03-08 23:33 UTC, theusaf commented on websites/T/TabNews/metadata.json
> +		"name": "Kuriel#1411"
```suggestion
		"name": "Kuriel"
```

2023-03-08 23:33 UTC, theusaf commented on websites/T/TabNews/presence.ts
> +			],
Buttons that can lead to home pages are [not allowed](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#presencets). Generally, buttons should lead to more specific content.
```suggestion
```

2023-03-09 01:40 UTC, Kuriel23 commented
Done!

2023-03-11 19:52 UTC, plskz requested changes

2023-03-11 19:52 UTC, plskz commented on websites/T/TabNews/metadata.json
> +	"thumbnail": "https://i.imgur.com/vUlsC33.png",
use this

```suggestion
	"thumbnail": "https://i.imgur.com/hbQ4bpd.png",
```

2023-03-13 17:03 UTC, Bas950 requested changes

2023-03-16 10:36 UTC, Bas950 approved these changes

2023-03-26 18:23 UTC, Timeraa approved these changes

2023-03-26 18:23 UTC, merged