Add signed.host as a website
PreMiD/Presences pull request #7227
Opened 2023-03-10 21:17 UTC by malwarepad

## Description 
Addition of signed.host, a private media, and bio page hosting service.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://user-images.githubusercontent.com/42353172/224429420-bd80558b-e42f-416d-8995-79c328259b8f.png)

![image](https://user-images.githubusercontent.com/42353172/224429569-c694a356-9534-4714-bf6b-4dbb9a7ae046.png)

![image](https://user-images.githubusercontent.com/42353172/224429805-316e682a-fbd4-457d-9ed2-8a94c86288d1.png)

</details>

I'll be happy to provide additional information in order for the process be sped up.

2023-03-11 00:44 UTC, theusaf requested changes

2023-03-11 00:44 UTC, theusaf commented on websites/S/signed.host/metadata.json
> +    "name": "MalwarePad#0001"
```suggestion
    "name": "MalwarePad"
```

2023-03-11 00:44 UTC, theusaf commented on websites/S/signed.host/metadata.json
> +  "url": ["signed.host", "bio.signed.host"],
Site uses `www` subdomain.
```suggestion
  "url": ["www.signed.host","signed.host", "bio.signed.host"],
```

2023-03-11 00:44 UTC, theusaf commented on websites/S/signed.host/metadata.json
> +  "logo": "https://i.imgur.com/0CyTL1E.png",
Logos should be 512x512px. Also, this image seems to be badly upscaled.

2023-03-11 00:44 UTC, theusaf commented on websites/S/signed.host/metadata.json
> +  "author": {
This file is not formatted properly. Use `yarn format` to format this file.

2023-03-11 00:44 UTC, theusaf commented on websites/S/signed.host/presence.ts
> +		buttonURL = document.location.toString(),
Destructure `href` from `document.location` and use that instead of this for clarity/consistency.
```suggestion
		buttonURL = href,
```

2023-03-11 00:44 UTC, theusaf commented on websites/S/signed.host/presence.ts
> +					: (state = "Not logged in!");
An if statement may make more sense here.

2023-03-11 00:44 UTC, theusaf commented on websites/S/signed.host/presence.ts
> +				buttonURL = "https://signed.host/";
Buttons that lead to main pages are [prohibited](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#presencets).

```suggestion
```

2023-03-11 00:44 UTC, theusaf commented on websites/S/signed.host/presence.ts
> +	lastTimestamp: number | undefined = Date.now();
What does `undefined` do here?
```suggestion
let lastUnique: string,
	lastTimestamp = Date.now();
```

2023-03-11 00:44 UTC, theusaf commented on websites/S/signed.host/presence.ts
> +					buttonURL = "https://signed.host/";
Ditto
```suggestion
```

2023-03-11 00:44 UTC, theusaf commented on websites/S/signed.host/presence.ts
> +			}
These are static sites, so they should be put into a Record-like structure like so: https://github.com/PreMiD/Presences/blob/236523980322a4053a45c691a1739eb50e2aea48/websites/G/Geotastic/presence.ts#L12-L42

2023-03-11 00:44 UTC, theusaf commented on websites/S/signed.host/presence.ts
> +		largeImageKey: "logo",
Imgur links are now used over Discord asset names in this repository.

2023-03-11 00:44 UTC, theusaf commented on websites/S/signed.host/presence.ts
> +		buttonURL = document.location.toString(),
Buttons that can lead to main pages (such as this) are [prohibited](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#presencets). Buttons should have more specific uses.
```suggestion
```

2023-03-11 00:44 UTC, theusaf commented on websites/S/signed.host/presence.ts
> +	const loggedUsername = document.querySelector("#premid-username")?.innerHTML;
`textContent` may be a better/more readable choice over `innerHTML`
```suggestion
	const loggedUsername = document.querySelector("#premid-username")?.textContent;
```

2023-03-11 00:44 UTC, theusaf commented on websites/S/signed.host/presence.ts
> +				// Dashboard routes
These comments may be redundant.
```suggestion
```

2023-03-11 00:45 UTC, theusaf requested changes
PR title does not follow [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md).

2023-03-11 00:52 UTC, theusaf requested changes

2023-03-11 00:52 UTC, theusaf commented on websites/S/signed.host/presence.ts
> +				buttonLabel = "Visit bio";
```suggestion
				buttonLabel = "Visit Bio";
```

2023-03-12 04:09 UTC, theusaf commented
Make sure to mark completed suggestions as resolved.

2023-03-12 10:49 UTC, malwarepad commented
I marked everything as resolved.

2023-03-12 16:14 UTC, RisingSunLight42 approved these changes

2023-03-13 17:06 UTC, Bas950 approved these changes

2023-03-16 04:29 UTC, theusaf approved these changes

2023-03-26 18:21 UTC, Timeraa approved these changes

2023-03-26 18:21 UTC, merged