Update instagram logo
PreMiD/Presences pull request #7232
Opened 2023-03-15 13:30 UTC by lolollllo

## Description 

Instagram logo was outdated so it was replaced with the brighter newer one

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ ] I linted the code by running `yarn format`
- [ ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

2023-03-15 18:02 UTC, theusaf requested changes
* Ensure that the PR title follows commit conventions.
* Use `yarn format` to ensure the code is formatted properly.

2023-03-15 18:02 UTC, theusaf commented on websites/I/Instagram/metadata.json
> +	"logo": "https://i.imgur.com/LeG1Uzz.png",
The current new standard is to have all images be 512x512px

2023-03-15 18:02 UTC, theusaf commented on websites/I/Instagram/metadata.json
>  	"version": "2.2.5",
```suggestion
	"version": "2.2.6",
```

2023-03-16 10:38 UTC, Bas950 approved these changes

2023-03-26 18:23 UTC, Timeraa approved these changes

2023-03-26 18:23 UTC, merged