docs(Guidelines): update for up-to-date guidelines and structure
PreMiD/Presences pull request #7234
Opened 2023-03-16 16:15 UTC by theusaf

## Description 

- Removes `tsconfig.json` references
- Updates the names of PR checks
- Specifies 512x512px for logo image

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

2023-03-24 18:33 UTC, Bas950 requested changes

2023-03-24 18:33 UTC, Bas950 commented on .github/CONTRIBUTING.md
>  ├── presence.ts
Please update most bottom ones to show └ (last item) and not ├ (more items below)

2023-03-25 09:19 UTC, Bas950 approved these changes

2023-03-26 18:25 UTC, Timeraa approved these changes

2023-03-26 18:25 UTC, merged