Teknofest: add presence
PreMiD/Presences pull request #7265
Opened 2023-04-02 08:20 UTC by pxsty0

## Description 

## Acknowledgements
- [ ] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ ] I linted the code by running `yarn format`
- [ ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

2023-04-02 12:04 UTC, DarkVillager commented
There's no presence code?

2023-04-02 15:13 UTC, pxsty0 commented
hello where should i add the presence.ts file

2023-04-02 21:30 UTC, theusaf commented
> hello where should i add the presence.ts file

It goes in the same folder. See the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#creation).

2023-04-03 16:42 UTC, theusaf requested changes
* This presence is currently low quality. Add support for more paths.
* The PR title does not match the repo's commit conventions.
* If you are still working on this, you can also mark it as a draft.

2023-04-03 16:42 UTC, theusaf commented on websites/T/Teknofest/metadata.json
> +	"url": ["teknofest.org"],
Site supports www subdomain
```suggestion
	"url": ["teknofest.org","www.teknofest.org"],
```

2023-04-03 16:42 UTC, theusaf commented on websites/T/Teknofest/metadata.json
> +	"tags": ["turkish", "teknofest", "t3vakfi", "pxsty"],
This file is not formatted properly. Use `yarn format`.

2023-04-03 16:42 UTC, theusaf commented on websites/T/Teknofest/metadata.json
> +	"logo": "https://i.imgur.com/b4It2CL.jpg",
Logos should be 512x512px. See the Presence Guidelines.

2023-04-03 16:42 UTC, theusaf commented on websites/T/Teknofest/metadata.json
> +	"thumbnail": "https://i.imgur.com/b4It2CL.jpg",
The thumbnail should be a screenshot or promotional banner, probably not the same as the logo.

2023-04-03 16:42 UTC, theusaf commented on websites/T/Teknofest/metadata.json
> +		"nl": "TEKNOFEST Havacılık, Uzay ve Teknoloji Festivali"
These descriptions are not correct translations

2023-04-03 16:42 UTC, theusaf commented on websites/T/Teknofest/presence.ts
> +		largeImageKey: "logo",
Imgur links are used instead of Discord asset names in this repo.

2023-04-03 16:42 UTC, theusaf commented on websites/T/Teknofest/presence.ts
> +	if (window.location.pathname.startsWith("/")) {
```suggestion
	if (document.location.pathname.startsWith("/")) {
```

2023-04-06 06:23 UTC, closed without merging