feat(Papara Topluluk): add presence
PreMiD/Presences pull request #7272
Opened 2023-04-05 00:37 UTC by eggsy

## Description 
Turkish community forum for Papara users, new generation banking provider. This presence supports page names, category viewing, tag viewing, user profile viewing, thread reading features. This PR closes #7270.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary>Load screenshots...</summary>

![viewing page](https://user-images.githubusercontent.com/13917975/229952184-c39c0e9b-edd5-4a34-8672-7800c51594d0.png)

![reading thread](https://user-images.githubusercontent.com/13917975/229952169-261d4f81-1c70-4ecd-8ee5-0e8b99249146.png)

![viewing user](https://user-images.githubusercontent.com/13917975/229952196-7f5b8e33-545e-4027-b192-fc1c07de15e9.png)

![viewing user page](https://user-images.githubusercontent.com/13917975/229952207-33883021-bac2-4a3b-b2e0-00cab59d3864.png)

</details>

2023-04-06 18:45 UTC, Bas950 requested changes

2023-04-06 18:45 UTC, Bas950 commented on websites/P/Papara Topluluk/metadata.json
> +  "logo": "https://i.imgur.com/wsEA3eB.png",
Logo must be 512x512

2023-04-06 18:50 UTC, Bas950 approved these changes

2023-04-09 20:56 UTC, Bas950 approved these changes

2023-04-10 05:48 UTC, Timeraa approved these changes

2023-04-10 05:48 UTC, merged