chore: fix deepscan issues
PreMiD/Presences pull request #7274
Opened 2023-04-05 13:31 UTC by DarkVillager

## Description 

fix deepscan issues
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

n/a

</details>

2023-04-06 18:48 UTC, Bas950 requested changes
all ditto

2023-04-06 18:48 UTC, Bas950 commented on websites/B/BBC/presence.ts
> +			setCover(soundData.programmes.current.imageUrl);
yea pretty sure that won't work, as it is deta they get out of a pegeletiable

2023-04-06 18:48 UTC, Bas950 commented on websites/B/BBC/presence.ts
> +			imageUrl: string;
ditto

2023-04-07 12:12 UTC, DarkVillager commented
Issue is already fixed.

2023-04-07 12:12 UTC, closed without merging