feat(3388): add presence
PreMiD/Presences pull request #7284
Opened 2023-04-10 12:13 UTC by alexgokhale

## Description 
Add presence for 3388 (https://3388.to).

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img width="226" alt="image" src="https://user-images.githubusercontent.com/69989246/230899053-0a9f95df-1e48-403d-aad3-188c9af86415.png">
<img width="248" alt="image" src="https://user-images.githubusercontent.com/69989246/230899088-bd635a5e-61dd-4aca-b062-d85c35b53004.png">
<img width="248" alt="image" src="https://user-images.githubusercontent.com/69989246/230899126-277b8572-7130-4d55-8b0b-b0344ab68032.png">
<img width="272" alt="image" src="https://user-images.githubusercontent.com/69989246/230899186-61a4897f-1f9a-4c3a-9ef9-c23f73a1074b.png">
<img width="255" alt="image" src="https://user-images.githubusercontent.com/69989246/230899232-23a9087e-7ba1-4446-81dc-e431186cf730.png">
<img width="254" alt="image" src="https://user-images.githubusercontent.com/69989246/230899476-050e8160-0732-4ce7-b1ce-de1cae96ab50.png">
<img width="232" alt="image" src="https://user-images.githubusercontent.com/69989246/230899507-bac83dfe-7477-4fb5-b6ae-a4059380c442.png">
<img width="238" alt="image" src="https://user-images.githubusercontent.com/69989246/230899561-2a6a1ad3-b04b-4268-8ad5-1403b7bcebc6.png">

</details>

2023-04-10 13:10 UTC, DarkVillager commented on websites/0-9/3388/metadata.json
> +	"logo": "https://i.imgur.com/FhGHKTn.png",
Logo needs to be 512x512

2023-04-10 13:14 UTC, DarkVillager requested changes

2023-04-10 13:14 UTC, DarkVillager commented on websites/0-9/3388/metadata.json
> +	"logo": "https://i.imgur.com/FhGHKTn.png",
Logo needs to be 512x512
```suggestion
	"logo": "https://i.imgur.com/h8N7txd.png",
```

2023-04-10 13:14 UTC, DarkVillager commented on websites/0-9/3388/presence.ts
> +			largeImageKey: "https://i.imgur.com/FhGHKTn.png",
Ditto.
```suggestion
			largeImageKey: "https://i.imgur.com/h8N7txd.png",
```

2023-04-10 13:14 UTC, DarkVillager commented on websites/0-9/3388/presence.ts
> +			smallImageKey: "search",
Also change these Assets to imgur links. If u use them alot use an enum.

2023-04-10 22:35 UTC, theusaf requested changes

2023-04-10 22:35 UTC, theusaf commented on websites/0-9/3388/metadata.json
> +		"name": "xela#0049"
```suggestion
		"name": "xela"
```

2023-04-10 22:35 UTC, theusaf commented on websites/0-9/3388/presence.ts
> +			!document.querySelector("#season-list") ? "a Movie..." : "a TV Show..."
Remove "..." from strings. (Also remove from the lines at the bottom of this)
```suggestion
			!document.querySelector("#season-list") ? "a Movie" : "a TV Show"
```

2023-04-14 07:40 UTC, Bas950 approved these changes

2023-04-21 01:16 UTC, Timeraa approved these changes

2023-04-21 01:16 UTC, merged