feat(Replit): Add new logo, and add support for new areas
PreMiD/Presences pull request #7298
Opened 2023-04-18 04:26 UTC by totally-google-drive

## Description 
Updated to the new Replit logo, and added support for the new(ish) areas (Bounties, Learn, Themes, etc..)
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
![image](https://user-images.githubusercontent.com/125172092/232670589-22c88005-194f-411f-8652-0598de912554.png)
![image](https://user-images.githubusercontent.com/125172092/232670747-ea36e268-8187-48b5-bd44-aa7de9564941.png)
![image](https://user-images.githubusercontent.com/125172092/232670779-8c4f73cd-d50b-4cea-864f-797a4998c096.png)
![image](https://user-images.githubusercontent.com/125172092/232670804-d5188c65-e16c-48bd-9a37-32acf3da1396.png)

</details>

2023-04-19 00:49 UTC, theusaf requested changes

2023-04-19 00:49 UTC, theusaf commented on websites/R/Replit/presence.ts
> +              presenceData.details = `Admiring a theme`;
```suggestion
              presenceData.details = "Admiring a theme";
```

2023-04-19 00:49 UTC, theusaf commented on websites/R/Replit/metadata.json
> +	"logo": "https://i.imgur.com/ge3dweY.png",
Logos must be 512x512px

2023-04-19 00:50 UTC, theusaf commented
* It looks like you uploaded the javascript file rather than the typescript file.
* Resolve CI issues

2023-04-27 08:47 UTC, Bas950 commented
Closing for inactivity

2023-04-27 08:47 UTC, closed without merging