chore(AnimeVost): no one time variables
PreMiD/Presences pull request #7319
Opened 2023-04-29 08:32 UTC by DarkVillager

## Description 

Chore to remove the warnings AnimeVost gives.
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://user-images.githubusercontent.com/42322979/235292485-94e0199f-322b-4342-84df-96f6f006945c.png">

</details>

2023-04-30 13:37 UTC, Bas950 approved these changes

2023-04-30 13:37 UTC, Bas950 requested changes
Presence has metadata.iframe set to true but metadata.iFrameRegExp is not set, you may want to set it

2023-04-30 13:48 UTC, DarkVillager commented
> Presence has metadata.iframe set to true but metadata.iFrameRegExp is not set, you may want to set it

let me check

2023-05-05 11:37 UTC, DarkVillager commented
> > Presence has metadata.iframe set to true but metadata.iFrameRegExp is not set, you may want to set it
> 
> let me check

No cuz they all are on the same domain as the website

2023-05-05 11:45 UTC, Bas950 approved these changes

2023-05-05 15:24 UTC, theusaf approved these changes

2023-05-05 19:22 UTC, merged