fix(paramount): fixed presence
PreMiD/Presences pull request #7351
Opened 2023-05-11 20:03 UTC by calicokatsu

## Description 
- Escaped `if-else hell` (kinda)
- Fixed Live TV Presence
- Fixed Series Presence
- Series Presence now has the Episode Thumbnail as it's Large Image Key

## Acknowledgements
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`

## Screenshots
![image](https://github.com/PreMiD/Presences/assets/62923115/ace11a45-b620-4e67-9725-5abca30c8dbd)
![image](https://github.com/PreMiD/Presences/assets/62923115/f31491bb-9382-4869-bbbd-7ecfdde47896)

<details>
<summary> Series' have been reported to not be working. This push fixes that and the Series presence now also displays the episode thumbnail alongside the Title, Season and Episode. Along with fixing the Live TV Presence</summary>

</details>

2023-05-12 08:46 UTC, DarkVillager commented
Change title to: fix(Paramount): fixed presence

2023-05-12 08:49 UTC, DarkVillager requested changes

2023-05-12 08:49 UTC, DarkVillager commented on websites/P/Paramount+/presence.ts
> +		{ pathname: path } = window.location;
We prefer document.location
```suggestion
		{ pathname: path } = document.location;
```

2023-05-12 08:49 UTC, DarkVillager commented on websites/P/Paramount+/presence.ts
> +			presenceData.smallImageKey = "search";
Change these all to imgur links.

2023-05-12 16:47 UTC, theusaf requested changes

2023-05-12 16:47 UTC, theusaf commented on websites/P/Paramount+/presence.ts
> +			presenceData.details = "Browsing...";
Prefer strings without `...`
```suggestion
			presenceData.details = "Browsing";
```

2023-05-16 09:03 UTC, DarkVillager commented on websites/P/Paramount+/presence.ts
> +enum Assets {
remove

2023-05-16 21:57 UTC, closed without merging

2023-05-18 07:45 UTC, DarkVillager commented
@calicokatsu why close this?

2023-05-18 17:59 UTC, calicokatsu commented
> @calicokatsu why close this?

I don't remember closing it. That's strange. I'll re-open it.

2023-05-19 05:43 UTC, Turtle-Boi commented
how do i get this update

2023-05-19 07:28 UTC, calicokatsu commented
@Turtle-Boi wait for #7360 to merge and it'll update it for you