feat(Mastodon): add new presence
PreMiD/Presences pull request #7356
Opened 2023-05-14 22:22 UTC by Hikki0710

## Description 
I added support for mastodon instances (for the moment I’m just putting the most used ones)

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![immagine](https://github.com/PreMiD/Presences/assets/133604163/94b0870f-47b9-482e-be07-85b480be73b4)
![immagine](https://github.com/PreMiD/Presences/assets/133604163/3cdb3a56-7abc-4cb8-9333-53bd7ce3229d)

![immagine](https://github.com/PreMiD/Presences/assets/133604163/3e25dbb6-7b98-4426-bbb5-b952dc8dd896)
![immagine](https://github.com/PreMiD/Presences/assets/133604163/3eb31117-8f60-4a73-9872-8de0339c69b2)

![immagine](https://github.com/PreMiD/Presences/assets/133604163/f4828c2b-468c-4ace-a7e9-9bf64c84ae6c)
![immagine](https://github.com/PreMiD/Presences/assets/133604163/840143d5-0bee-4eee-a8bc-f7ad5ab29d0f)

![immagine](https://github.com/PreMiD/Presences/assets/133604163/69677374-b669-4f50-9411-9fbd725d93c4)
![immagine](https://github.com/PreMiD/Presences/assets/133604163/421e0aae-d12b-4ef6-88c8-259a922a0614)

</details>

2023-05-15 02:54 UTC, theusaf requested changes

2023-05-15 02:54 UTC, theusaf commented on websites/M/Mastodon/metadata.json
> +	"thumbnail": "https://i.imgur.com/e7gLIsD.jpeg",
This thumbnail is a bit low-res. Try to find a higher-resolution version or upscale it if possible.

2023-05-15 02:54 UTC, theusaf commented on websites/M/Mastodon/presence.ts
> +		largeImageKey: "https://i.imgur.com/jlQv2if.png",
Assets should be 512x512px in size.
Also, as your presence uses many assets, put them in an enum like so:
https://github.com/PreMiD/Presences/blob/3aa7e3fb8e54999012de1d1528f37bc907ae4213/websites/C/Crunchyroll/presence.ts#L52-L58

2023-05-15 02:54 UTC, theusaf commented on websites/M/Mastodon/presence.ts
> +	if (document.location.pathname === "/home") {
`document.location` is used many times in this presence. Destructure the properties to simplify the code a bit:
```ts
const { pathname } = document.location;
```

2023-05-15 11:24 UTC, DarkVillager commented
@Hikki0710 Also run prettier.

if you need help go to discord: https://discord.com/channels/493130730549805057/607524579874832446 or dm me on discord: Dark_Ville#2756

2023-05-15 14:48 UTC, theusaf requested changes

2023-05-15 14:48 UTC, theusaf commented on websites/M/Mastodon/presence.ts
> +						// No default
Remove automated eslint comment
```suggestion
```

2023-05-18 11:41 UTC, DarkVillager commented on websites/M/Mastodon/presence.ts
> +	Search = "https://i.imgur.com/WhzGXp1.png",
Why use a different Asset for this?

2023-05-18 11:42 UTC, DarkVillager requested changes

2023-05-18 11:42 UTC, DarkVillager commented on websites/M/Mastodon/presence.ts
> +enum Assets {
```suggestion
const enum Assets {
```

2023-05-18 20:36 UTC, theusaf requested changes

2023-05-18 20:36 UTC, theusaf commented on websites/M/Mastodon/presence.ts
This file is not formatted properly. Use `yarn format` to format it.

2023-05-24 05:14 UTC, theusaf requested changes

2023-05-24 05:14 UTC, theusaf commented on websites/M/Mastodon/presence.ts
> +					switch (pathname) {
You have a lot of nested switch statements and if statements that could be flattened. 
Consider putting all the static pathnames in a single switch, and the more dynamic conditions in if/else in the default area. Alternatively, use a `switch(true)` kind of structure.

2023-05-24 05:14 UTC, theusaf commented on websites/M/Mastodon/presence.ts
> +								.querySelector("img")
These query statements can be combined
```suggestion
								.querySelector(".about__header__hero img")
```

2023-05-25 19:29 UTC, theusaf commented on websites/M/Mastodon/presence.ts
> +			presenceData.details = `Looking their ${pathName}`;
```suggestion
			presenceData.details = `Looking at their ${pathName}`;
```

2023-05-26 16:19 UTC, theusaf approved these changes

2023-05-26 18:14 UTC, Bas950 requested changes

2023-05-26 18:14 UTC, Bas950 commented on websites/M/Mastodon/metadata.json
> +	"logo": "https://i.imgur.com/B0HPMOQ.png",
```suggestion
	"logo": "https://i.imgur.com/njcb4Wp.png",
```

2023-05-27 08:59 UTC, Bas950 approved these changes

2023-05-27 09:00 UTC, merged