feat(アイドルマスターシャイニーカラーズ): add new presence
PreMiD/Presences pull request #7363
Opened 2023-05-21 09:12 UTC by SINO87

## Description 
Add presence for [アイドルマスターシャイニーカラーズ](https://shinycolors.enza.fun/).
THE iDOLM@STER Shiny Colors (Japanese: アイドルマスター シャイニーカラーズ), or Shinymas (Japanese: シャニマス) for short, is a training simulation browser game in THE iDOLM@STER series.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/PreMiD/Presences/assets/55715737/1ddc76ec-4364-43dc-b9de-b93a7b024f98)
![image](https://github.com/PreMiD/Presences/assets/55715737/bb9760d5-07cf-47b9-9dc3-ac007ff5cc49)

![image](https://github.com/PreMiD/Presences/assets/55715737/2c69de43-cc45-4d78-ac3e-c8a9850b8463)
![image](https://github.com/PreMiD/Presences/assets/55715737/d62445d9-89d7-4173-9623-f8c448549e0e)

![image](https://github.com/PreMiD/Presences/assets/55715737/4605f840-7c83-4485-a302-adff39e00c60)
![image](https://github.com/PreMiD/Presences/assets/55715737/83ee9853-db3a-4386-82ef-1094044ad4d7)

</details>

2023-05-21 15:14 UTC, theusaf requested changes

2023-05-21 15:14 UTC, theusaf commented on websites/#/アイドルマスターシャイニーカラーズ/presence.ts
> +  const { pathname } = window.location;
This repo uses `document.location` rather than `window.location` 
```suggestion
  const { pathname } = document.location;
```

2023-05-21 15:14 UTC, theusaf commented on websites/#/アイドルマスターシャイニーカラーズ/presence.ts
> +    largeImageKey: "https://i.imgur.com/ue8EatG.jpg",
```suggestion
    largeImageKey: "https://i.imgur.com/UJtnJXY.png",
```

2023-05-21 15:14 UTC, theusaf commented on websites/#/アイドルマスターシャイニーカラーズ/presence.ts
> +  if (pathname === "/home") {
Most of the paths in this presence are static. Put the static paths in a structure like so:
https://github.com/PreMiD/Presences/blob/236523980322a4053a45c691a1739eb50e2aea48/websites/G/Geotastic/presence.ts#L12-L42

2023-05-21 15:15 UTC, theusaf requested changes
Also, please resolve CI issues. (run `npm run format`)

2023-05-21 15:19 UTC, theusaf requested changes

2023-05-21 15:19 UTC, theusaf commented on websites/#/アイドルマスターシャイニーカラーズ/metadata.json
> +	"description": {
This service could do with an `altnames` field (romanization, english translation, shorter names, etc.)

2023-05-22 12:17 UTC, DarkVillager requested changes

2023-05-22 12:17 UTC, DarkVillager commented on websites/#/アイドルマスターシャイニーカラーズ/presence.ts
> +  presenceData.startTimestamp = browsingTimestamp;
Move this to the same location as largeImageKey
```suggestion
```

2023-05-22 12:17 UTC, DarkVillager commented on websites/#/アイドルマスターシャイニーカラーズ/presence.ts
> +    largeImageKey: "https://i.imgur.com/YfaIAPE.png",
```suggestion
    largeImageKey: "https://i.imgur.com/YfaIAPE.png",
    startTimestamp: browsingTimestamp,
```

2023-05-23 14:38 UTC, theusaf requested changes

2023-05-23 14:38 UTC, theusaf commented on websites/#/アイドルマスターシャイニーカラーズ/presence.ts
> +		browsingTimestamp = Math.floor(Date.now() / 1000),
This should probably be outside of the `UpdateData` loop, otherwise it will always be saying that the user was playing for 0 seconds.

2023-05-24 05:05 UTC, theusaf requested changes

2023-05-24 05:05 UTC, theusaf commented on websites/#/アイドルマスターシャイニーカラーズ/presence.ts
> +			largeImageKey: "https://i.imgur.com/ue8EatG.jpg",
This image does not seem to exist.
```suggestion
			largeImageKey: "https://i.imgur.com/YfaIAPE.png",
```

2023-05-24 14:23 UTC, theusaf approved these changes

2023-05-24 18:08 UTC, Bas950 approved these changes

2023-05-24 18:08 UTC, merged