feat(Sorryfield): add new presence
PreMiD/Presences pull request #7380
Opened 2023-05-26 18:44 UTC by IAMIHAH

## Description 

I added a presence for Sorryfield which a karaoke songs listing site. And it have an rythm game named "Java!".

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/PreMiD/Presences/assets/64065435/502ac4cd-7b6a-4c60-b0fa-f8ca891f9882)
![image](https://github.com/PreMiD/Presences/assets/64065435/88f4afa7-f992-4bc6-a49a-691c08cbddd1)
![image](https://github.com/PreMiD/Presences/assets/64065435/5e08471e-da71-4552-972e-c43d6da89b70)

</details>

2023-05-26 19:10 UTC, theusaf requested changes
The website's [primary language](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#presencets) appears to be Korean. Therefore, the presence should support Korean strings as well.

2023-05-26 19:10 UTC, theusaf commented on websites/S/Sorryfield/presence.ts
> +			{ label: "Listen the song", url: document.location.href },
Button text should be capitalized.
```suggestion
			{ label: "Listen To The Song", url: document.location.href },
```
```suggestion
			{ label: "Listen", url: document.location.href },
```

2023-05-26 19:10 UTC, theusaf commented on websites/S/Sorryfield/presence.ts
> +				{ label: "Play the chart", url: document.location.href },
Ditto for button capitalization

2023-05-26 19:10 UTC, theusaf commented on websites/S/Sorryfield/presence.ts
> +				.replace('.jpg">', "")
It may be better to query the image and do the text transformations on the image's src itself, rather than relying on a specific html text structure.

2023-05-26 19:10 UTC, theusaf commented on websites/S/Sorryfield/presence.ts
> +				{ label: "Join room", url: document.location.href },
Ditto for capitalization

2023-05-27 21:13 UTC, theusaf requested changes

2023-05-27 21:13 UTC, theusaf commented on websites/S/Sorryfield/presence.ts
> +				.attributes[1].value.replace("/media/images/chart-", "")
This should be a bit clearer.
```suggestion
				.querySelector<HTMLImageElement>(".active>div>img")
				.src.replace("/media/images/chart-", "")
```

2023-05-27 21:13 UTC, theusaf commented on websites/S/Sorryfield/presence.ts
> +		presenceData.buttons = [{ label: "Listen", url: href }];
I know I partially requested this, but perhaps to be consistent, this should also be in Korean.

2023-05-27 21:13 UTC, theusaf commented on websites/S/Sorryfield/presence.ts
> +			} - ${chartHeader.children[1].children[0].innerHTML}`;
Prefer `.textContent` instead of `.innerHTML` where possible

2023-05-27 21:13 UTC, theusaf commented on websites/S/Sorryfield/presence.ts
> +				.replace("/", "of");
Can `.textContent` be used here instead of this specific `.innerHTML` replacement?

2023-05-27 21:13 UTC, theusaf commented on websites/S/Sorryfield/presence.ts
> +		}
Ditto

2023-05-29 06:55 UTC, theusaf requested changes

2023-05-29 06:55 UTC, theusaf commented on websites/S/Sorryfield/presence.ts
> +						.children[0].innerHTML.split("</span>")[1]
```suggestion
					document
						.querySelector(".room-header")
						.children[0].childNodes[1].textContent
```

2023-05-29 06:55 UTC, theusaf commented on websites/S/Sorryfield/presence.ts
> +			document.querySelector(".song").children[2].innerHTML.split("&nbsp;")[0]
```suggestion
		presenceData.state = `${
			document.querySelector(".song").children[2].childNodes[0].textContent
```

2023-05-30 15:34 UTC, theusaf requested changes
Resolve CI issues (run `npm run format`)

2023-05-30 17:01 UTC, Bas950 requested changes

2023-05-31 12:24 UTC, DarkVillager requested changes

2023-05-31 12:24 UTC, DarkVillager commented on websites/S/Sorryfield/metadata.json
> +	"logo": "https://i.imgur.com/TxuMfTd.png",
There is a more high quality version available.
```suggestion
	"logo": "https://i.imgur.com/Rysn3ig.png",
```

2023-05-31 12:24 UTC, DarkVillager commented on websites/S/Sorryfield/presence.ts
> +	LOGO = "https://i.imgur.com/TxuMfTd.png",
Ditto
```suggestion
	LOGO = "https://i.imgur.com/Rysn3ig.png",
```

2023-06-04 13:29 UTC, IAMIHAH commented on websites/S/Sorryfield/presence.ts
> +	CHART_MULTIPLAYER = "https://i.imgur.com/fdGfvt2.jpg",
This assets for rhythm game Java! (in Sorryfield)
![image](https://github.com/PreMiD/Presences/assets/64065435/1217b50f-9bc3-41ba-849a-0a7c97c8690b)

2023-06-04 15:35 UTC, theusaf commented
Make sure to mark previous resolved conversations as resolved

2023-06-06 16:53 UTC, theusaf approved these changes

2023-06-06 18:59 UTC, Bas950 approved these changes

2023-06-06 19:00 UTC, merged