feat(Songsterr): add presence
PreMiD/Presences pull request #7385
Opened 2023-05-28 20:36 UTC by AlperShal

## Description 
I added support for songsterr.com, a website for searching instruments' tabs. It's one of the most popular ones.

## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
![Uwl0Pzt](https://github.com/PreMiD/Presences/assets/34231577/0b6097e8-2788-4348-8c26-89e7a8a7cc4f)
![omdI5Rr](https://github.com/PreMiD/Presences/assets/34231577/dd2a8273-c172-4b13-9866-a744bd4f40e5)

</details>

2023-05-28 20:56 UTC, theusaf requested changes
Make sure to resolve CI issues

2023-05-28 20:56 UTC, theusaf commented on websites/S/Songsterr/metadata.json
> +	"logo": "https://i.imgur.com/MXQP0Lq.png",
[Logos](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#logo) are required to have a resolution of 512x512px

2023-05-29 07:28 UTC, AlperShal commented
Sorry to take your time about the lint failing. I really misunderstood how it works. Also thought the logo was required to have _at least_ 512x512 resolution, not exactly. Sorry about that too. Should be fine now.

2023-05-29 07:33 UTC, theusaf requested changes

2023-05-29 07:33 UTC, theusaf commented on websites/S/Songsterr/presence.ts
> +		largeImageKey: "https://i.imgur.com/MXQP0Lq.png",
```suggestion
		largeImageKey: "https://i.imgur.com/FbLdpEW.png",
```

2023-05-29 07:34 UTC, theusaf commented
> Sorry to take your time about the lint failing. I really misunderstood how it works. Also thought the logo was required to have _at least_ 512x512 resolution, not exactly. Sorry about that too. Should be fine now.

It's fine. The logo being required to be 512x512 was a relatively recent change, and the documentation on the website vs here is a bit out of sync, which may be adding a bit of confusion.

2023-05-30 15:31 UTC, theusaf approved these changes

2023-05-30 16:54 UTC, Bas950 requested changes

2023-05-30 17:34 UTC, theusaf approved these changes

2023-05-31 12:39 UTC, merged