New Presence (Kick)
PreMiD/Presences pull request #7433
Opened 2023-06-17 23:52 UTC by ipexadev

## Description 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/PreMiD/Presences/assets/67909777/36b73ccc-32e1-4f80-8734-6036f6356fc8)
![image](https://github.com/PreMiD/Presences/assets/67909777/a9a0f2b1-6698-4b42-8a82-33475ff3ca8f)
![image](https://github.com/PreMiD/Presences/assets/67909777/c33b6bf6-3e6b-4448-b52e-16b333ead046)
![image](https://github.com/PreMiD/Presences/assets/67909777/d42ed0ac-0fc3-4805-bfe6-1027a3599b5b)
![image](https://github.com/PreMiD/Presences/assets/67909777/d2d83d92-f31e-47d2-90a0-d473fbaf588a)

</details>

2023-06-17 23:55 UTC, ipexadev commented
For me everything works

2023-06-18 06:23 UTC, theusaf commented
> For me everything works

The code may compile/work, but there are things you have to fix, such as code style, and metadata issues. 

https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#checks

2023-06-18 13:00 UTC, ipexadev commented
So i got all checks now, yaay

2023-06-18 18:01 UTC, theusaf requested changes

2023-06-18 18:01 UTC, theusaf commented on websites/K/Kick/presence.ts
> +			"/categories/games/fortnite": {
There seems to be a lot of categories. Preferably find ways to grab the names/images using document queries, rather than hardcoding them.

2023-06-18 18:01 UTC, theusaf commented on websites/K/Kick/presence.ts
> +				details: "Viewing Category:",
Prefer strings without `:`
```ts
details: "Viewing a Game"

details: "Viewing a Category"
```

2023-06-18 20:05 UTC, ipexadev commented
Pull request

2023-06-18 20:22 UTC, ipexadev commented
@theusaf Should all be ready for use

2023-06-19 17:44 UTC, DarkVillager commented
feat(Kick): add presence

2023-06-20 15:14 UTC, ipexadev commented
Do i have to create a new pull request or is it made here

2023-06-21 03:39 UTC, theusaf commented
> Do i have to create a new pull request or is it made here

You should not have to create a new pull request, the title can be changed here.

2023-06-21 11:15 UTC, ipexadev commented
Making new

2023-06-21 11:15 UTC, closed without merging