fix(Disney+): fix presence
PreMiD/Presences pull request #7440
Opened 2023-06-23 11:13 UTC by DarkVillager

## Description 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://github.com/PreMiD/Presences/assets/42322979/b0a4816f-23a0-4a98-8254-f7c4e8b22a51">
<img src="https://github.com/PreMiD/Presences/assets/42322979/c19fdbf5-b617-46b8-88d5-117e10757896">
<img src="https://github.com/PreMiD/Presences/assets/42322979/70ccde8c-ff87-48ca-8b20-bab7edc291e5">
<img src="https://github.com/PreMiD/Presences/assets/42322979/d9d4980a-a2f5-451f-b3cf-7ee77dcf30f1">
<img src="https://github.com/PreMiD/Presences/assets/42322979/b738268f-6e4d-4cd5-b4a5-6f46fbb644fa">

</details>

2023-06-23 18:08 UTC, ipexadev commented
Fix the Problems please.

2023-06-23 18:10 UTC, DarkVillager commented
> Fix the Problems please.

Patience.

2023-06-24 18:19 UTC, Bas950 submitted a review, later dismissed

2023-06-25 04:42 UTC, theusaf requested changes

2023-06-25 04:42 UTC, theusaf commented on websites/D/Disney+/presence.ts
> +							? "Viewing a serie"
```suggestion
							? "Viewing a series"
```

2023-06-26 13:28 UTC, theusaf approved these changes

2023-06-26 14:11 UTC, Bas950 approved these changes

2023-06-26 14:11 UTC, merged