feat(PeaceScans): add website peacescans.life
PreMiD/Presences pull request #7445
Opened 2023-06-26 14:08 UTC by Weemizo

## Description 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/PreMiD/Presences/assets/60063669/e02adbdb-7fb4-4cdd-93fc-0a82887dac32)
![image](https://github.com/PreMiD/Presences/assets/60063669/4a43b4d6-462b-46e3-8279-53a2edb21904)
![image](https://github.com/PreMiD/Presences/assets/60063669/06921326-e61b-49c9-bb6b-0b9d13e19fbd)

</details>

2023-06-27 08:00 UTC, theusaf requested changes

2023-06-27 13:38 UTC, Weemizo commented on websites/P/PeaceScans/presence.ts
> +		)?.textContent,
seems that 
```typescript
body > section h3
``` is working for every single manga title

2023-06-28 22:19 UTC, theusaf requested changes

2023-06-28 22:19 UTC, theusaf commented on websites/P/PeaceScans/metadata.json
> +	"logo": "https://i.imgur.com/OGVEndo.png",
Logos should be at least 512x512px. Find or create a higher-resolution image.

2023-07-01 09:06 UTC, Bas950 approved these changes

2023-07-05 03:11 UTC, theusaf approved these changes

2023-07-05 03:11 UTC, merged