fix(MyCanal): changed new path to img tag
PreMiD/Presences pull request #7460
Opened 2023-07-01 19:02 UTC by itsmelouis

## Description 
I fixed the issue when browsing a live channel, the presence wasn't functionning properly. 
Resolves #7458 

## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>  

![image](https://github.com/PreMiD/Presences/assets/72155852/0a284811-e0fa-428d-8821-208ad3ff7056)  

![image](https://github.com/PreMiD/Presences/assets/72155852/97df1bd8-143c-40e4-9f97-322138d351e4)

</details>

2023-07-05 03:07 UTC, theusaf requested changes

2023-07-05 03:07 UTC, theusaf commented on websites/M/myCANAL/presence.ts
> +							`#\\3${channelID}_toFocus > div.cardLogoChannel___WSRDl.cardLogoChannel--shadow___bE5Zx > div > img`
Try using a more dynamic selector if possible, for example:
```css
div[class*="cardLogoChannel"]
```

2023-07-08 00:54 UTC, itsmelouis commented
Done. Sorry for the wait 😕

2023-07-12 08:58 UTC, Bas950 approved these changes

2023-07-12 08:58 UTC, merged