feat: add and initialize Navidrome presence
PreMiD/Presences pull request #7476
Opened 2023-07-07 18:40 UTC by AlperShal

## Description 
Added support for Navidrome, a self-hosted music streaming service.

## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
Nothing Playing:

![image](https://github.com/PreMiD/Presences/assets/34231577/e8a56854-e811-4d1c-876b-d80b512342fa)

Playing:
![image](https://github.com/PreMiD/Presences/assets/34231577/81f666d3-22df-45e4-b087-49b03edc1747)

Paused:
![image](https://github.com/PreMiD/Presences/assets/34231577/db72990c-b55f-49d2-83eb-784d08970bef)
</details>

2023-07-10 11:01 UTC, DarkVillager requested changes

2023-07-10 11:01 UTC, DarkVillager commented on websites/N/Navidrome/presence.ts
> +				document.querySelectorAll(".current-time")[0].innerHTML
If u get the first one from querySelectorAll then just use querySelector
```suggestion
				document.querySelectol(".current-time").innerHTML
```

2023-07-10 11:13 UTC, DarkVillager requested changes

2023-07-10 11:13 UTC, DarkVillager commented on websites/N/Navidrome/presence.ts
> +				document.querySelectol(".current-time").innerHTML
```suggestion
				document.querySelector(".current-time").innerHTML
```

2023-07-12 07:50 UTC, theusaf requested changes

2023-07-12 07:50 UTC, theusaf commented on websites/N/Navidrome/metadata.json
> +	"url": "navidrome.org",
Website supports www subdomain
```suggestion
	"url": [
		"navidrome.org",
		"www.navidrome.org"
	],
```

2023-07-12 07:50 UTC, theusaf commented on websites/N/Navidrome/presence.ts
> +	if (document.querySelectorAll(".audio-title")[0].innerHTML !== "") {
Prefer `.textContent` over `.innerHTML` where possible.
```suggestion
	if (document.querySelector(".audio-title").textContent) {
```

2023-07-12 07:50 UTC, theusaf commented on websites/N/Navidrome/presence.ts
> +		if (document.querySelectorAll(".react-jinke-music-player-pause-icon")[0])
`.querySelectorAll(...)[0]` can be simplified.
```suggestion
		if (document.querySelector(".react-jinke-music-player-pause-icon"))
```

2023-07-12 07:50 UTC, theusaf commented on websites/N/Navidrome/presence.ts
> +		presenceData.state = document.querySelectorAll(".songArtist")[0].innerHTML;
Ditto

2023-07-14 07:08 UTC, theusaf approved these changes

2023-07-14 14:52 UTC, Bas950 approved these changes

2023-07-14 14:52 UTC, merged