Tempest new website update
PreMiD/Presences pull request #7477
Opened 2023-07-08 08:18 UTC by BySuspect

## Description 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![1](https://github.com/PreMiD/Presences/assets/70052500/c2113000-02b3-44ab-8c7b-ede2dbb4b7ee)
![2](https://github.com/PreMiD/Presences/assets/70052500/97d1a3fe-f083-403a-b814-4ec47a0a900e)
![3](https://github.com/PreMiD/Presences/assets/70052500/495ee11d-f6ae-4e9f-b597-961cf2b3da8f)

</details>

2023-07-10 11:04 UTC, DarkVillager requested changes

2023-07-10 11:04 UTC, DarkVillager commented on websites/T/Tempest Fansub/presence.ts
> +	ecchilogo = "https://imgur.com/BtQLEdY.png";
Please implement this with a const enum Assets.

```suggestion
	browsingTimestamp = Math.floor(Date.now() / 1000);
	
	const enum Assets {
	Logo = "https://cdn.rcd.gg/PreMiD/websites/T/Tempest%20Fansub/assets/logo.png",
	EcchiLogo = "https://imgur.com/BtQLEdY.png",
```

2023-07-10 11:04 UTC, DarkVillager commented on websites/T/Tempest Fansub/presence.ts
> +		if (hostname.startsWith("ecchi")) presenceData.largeImageKey = ecchilogo;
```suggestion
		if (hostname.startsWith("ecchi")) presenceData.largeImageKey = Assets.EcchiLogo;
```

2023-07-10 11:04 UTC, DarkVillager commented on websites/T/Tempest Fansub/presence.ts
> +		else presenceData.largeImageKey = defaultLogo;
```suggestion
		else presenceData.largeImageKey = Assets.Logo;
```

2023-07-12 07:56 UTC, theusaf requested changes

2023-07-12 07:56 UTC, theusaf commented on websites/T/Tempest Fansub/presence.ts
> +	EcchiLogo = "https://imgur.com/BtQLEdY.png",
Assets should be at least 512x512px

2023-07-14 07:21 UTC, theusaf approved these changes

2023-07-14 14:54 UTC, Bas950 approved these changes

2023-07-14 14:54 UTC, merged