feat(aha): add presence
PreMiD/Presences pull request #7501
Opened 2023-07-19 20:06 UTC by vigneshpy

## Description 

## Acknowledgements
- [ ] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ ] I linted the code by running `yarn format`
- [ ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/PreMiD/Presences/assets/40609760/114f9642-3af7-4f72-a4fd-2e0894a5fc3f)
![image](https://github.com/PreMiD/Presences/assets/40609760/44444a20-d41b-4f1b-b879-001c82e22f07)
![image](https://github.com/PreMiD/Presences/assets/40609760/67597e25-fae3-445a-9574-cc8273606e0d)
![image](https://github.com/PreMiD/Presences/assets/40609760/8a02d816-5d32-454b-8c67-0b7ea93554a8)
![image](https://github.com/PreMiD/Presences/assets/40609760/bd295b08-08a9-4846-9c3e-2616182f2b5b)
![image](https://github.com/PreMiD/Presences/assets/40609760/10f27ef1-cdd0-4c89-b06a-12a8a02d5750)

</details>

2023-07-21 11:49 UTC, DarkVillager requested changes

2023-07-21 11:49 UTC, DarkVillager commented on websites/A/aha/metadata.json
> +	"logo": "https://i.imgur.com/GJC1qSm.png",
Logo's must be 512x512 as per [our guideliness](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#logo).

2023-07-21 11:49 UTC, DarkVillager commented on websites/A/aha/presence.ts
> +	Logo = "https://i.imgur.com/GJC1qSm.png",
Ditto

2023-07-21 11:49 UTC, DarkVillager commented on websites/A/aha/presence.ts
> +				presenceData.details = "Viewing account details";
Please change this to the following format
```ts
switch (true) {
case pathname.startsWith("/movie"): {
				presenceData.details = `Viewing ${
					document.querySelector("h1.title").textContent
				}`;
				break;
}
// the other if statements changed to switch
}
```

2023-07-24 22:06 UTC, vigneshpy commented
done

2023-07-26 03:13 UTC, theusaf approved these changes

2023-07-26 06:14 UTC, Bas950 approved these changes

2023-07-26 06:14 UTC, merged