V1.0.8
PreMiD/Presences pull request #7523
Opened 2023-07-24 17:17 UTC by noxzym

## Description 

## Acknowledgements
- [ ] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ ] I linted the code by running `yarn format`
- [ ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
![image](https://github.com/PreMiD/Presences/assets/67855694/4724729f-a4f8-4ac5-a3dc-8ae4af1a34be)
![image](https://github.com/PreMiD/Presences/assets/67855694/33b2b026-8057-4270-a532-c9002c34cf82)
</details>

2023-07-25 10:49 UTC, DarkVillager commented
> ![image](https://github.com/PreMiD/Presences/assets/67855694/4724729f-a4f8-4ac5-a3dc-8ae4af1a34be) ![image](https://github.com/PreMiD/Presences/assets/67855694/33b2b026-8057-4270-a532-c9002c34cf82)

Change it to
`
<img src="https://github.com/PreMiD/Presences/assets/67855694/4724729f-a4f8-4ac5-a3dc-8ae4af1a34be">
<img src="https://github.com/PreMiD/Presences/assets/67855694/33b2b026-8057-4270-a532-c9002c34cf82">
`

2023-07-25 11:08 UTC, DarkVillager requested changes

2023-07-25 11:08 UTC, DarkVillager commented on websites/D/Doronime/presence.ts
> +						: title;
```suggestion
				presenceData.details = trim(document.querySelector('[aria-current="page"]')?.previousElementSibling?.textContent ?? document.querySelector('h5[class="Content__title"]')?.textContent?.replace(/(Episode [0-9]+)|(Subtitle Indonesia)/gm, ""))
```

2023-07-25 11:08 UTC, DarkVillager commented on websites/D/Doronime/presence.ts
> +		str.map(x => x[0].toUpperCase() + x.slice(1)).join(" ");
Let's also add a way to trim e.g.
```suggestion
	const capitalize = (str: string[]) =>
		str.map(x => x[0].toUpperCase() + x.slice(1)).join(" "),
		trim = (str: string[]) =>
		str.trim();
```
![image](https://github.com/PreMiD/Presences/assets/42322979/78dc4bfc-33d5-4cf9-9e16-0255eabd4f6e)

2023-07-25 11:08 UTC, DarkVillager commented on websites/D/Doronime/presence.ts
> +				).textContent;
![image](https://github.com/PreMiD/Presences/assets/42322979/93e23a4a-0d6b-4975-a79b-9bc2c1bf5525)
```suggestion
				presenceData.state = trim(document.querySelector(
					'[aria-current="page"]'
				)?:.textContent);
```

2023-07-25 11:08 UTC, DarkVillager commented on websites/D/Doronime/presence.ts
> +				).textContent;
Ditto
```suggestion
				presenceData.state =  trim(document.querySelector('[aria-current="page"]')?.textContent)
```

2023-07-25 11:08 UTC, DarkVillager commented on websites/D/Doronime/presence.ts
> +				).textContent;
Ditto
```suggestion
				presenceData.state =  trim(document.querySelector('[aria-current="page"]')?.textContent)
```

2023-07-25 11:08 UTC, DarkVillager commented on websites/D/Doronime/presence.ts
> +				).textContent;
Ditto
```suggestion
				presenceData.state =  trim(document.querySelector('[aria-current="page"]')?.textContent)
```

2023-07-25 11:08 UTC, DarkVillager commented on websites/D/Doronime/presence.ts
> +				).textContent;
Ditto
```suggestion
				presenceData.state =  trim(document.querySelector('[aria-current="page"]')?.textContent)
```

2023-07-25 11:08 UTC, DarkVillager commented on websites/D/Doronime/presence.ts
> +			url: document.location.href,
```suggestion
			url: href,
```

2023-07-25 11:08 UTC, DarkVillager commented on websites/D/Doronime/metadata.json
> +	"version": "1.0.8",
This is more than a fix. So update it to:
```suggestion
	"version": "1.1.0",
```

2023-07-25 16:27 UTC, Bas950 approved these changes

2023-07-26 02:59 UTC, theusaf approved these changes

2023-07-26 02:59 UTC, merged