fix(bilibilitv): thumbnail and null property access error
PreMiD/Presences pull request #7524
Opened 2023-07-25 06:21 UTC by ElaXan

## Description

1. The thumbnail was not being displayed correctly due to an incorrect parsing of the `og:image` property.
2. Resolved the "Cannot read properties of null" error that occurred when trying to access the `textContent` property of certain elements.

## Acknowledgements

- [ ] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ ] I linted the code by running `yarn format`
- [ ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots

<details>
<summary>Proof showing the creation/modification is working as expected</summary>
  <img src="https://github.com/ElaXan/BackupDatabase/assets/107149635/6382cf41-520b-4776-b0a1-f6a20710099a" alt="Proof image">
</details>

2023-07-25 10:47 UTC, DarkVillager commented on websites/B/bilibilitv/metadata.json
> +			"id": "506212044152897546"
In my opinion this isn't enough code change to become a contrbutor.

But it's up to @Bas950 & @theusaf

2023-07-25 10:49 UTC, DarkVillager requested changes

2023-07-25 10:49 UTC, DarkVillager commented on websites/B/bilibilitv/presence.ts
> +				.content.split("?")[0];
This is so it falls back to the logo when the element doesn't exist.
```suggestion
				?.content?.split("?")?.[0] ?? "https://cdn.rcd.gg/PreMiD/websites/B/bilibilitv/assets/logo.png";
```

2023-07-25 11:09 UTC, DarkVillager commented
Please resolve requested changes when you have made them.

2023-07-25 11:16 UTC, ElaXan commented
> Please resolve requested changes when you have made them.

Sorry. I forgot

2023-07-25 16:24 UTC, Bas950 approved these changes

2023-07-26 02:57 UTC, theusaf approved these changes

2023-07-26 02:57 UTC, merged