feat(MoviesJoy): add presence
PreMiD/Presences pull request #7556
Opened 2023-08-07 11:39 UTC by DarkVillager

## Description 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://github.com/PreMiD/Presences/assets/42322979/73c484af-0dd6-4532-8c32-86aecfd0a7a9">
<img src="https://github.com/PreMiD/Presences/assets/42322979/674a1f5e-9969-4de2-8bb2-dd06cf4079b5">
<img src="https://github.com/PreMiD/Presences/assets/42322979/1ad79f8d-62d7-4a6a-a8e5-ef804737e7b7">
<img src="https://github.com/PreMiD/Presences/assets/42322979/06e618aa-23cb-4374-a929-f6c6fd421b8d">

</details>

2023-08-08 21:53 UTC, theusaf requested changes

2023-08-08 21:53 UTC, theusaf commented on websites/M/MoviesJoy/presence.ts
> +					label: "Watch Movie",
Is this a movie or a TV series?

2023-08-08 21:53 UTC, theusaf commented on websites/M/MoviesJoy/presence.ts
> +			presenceData.details = privacy ? "Watching a tv series" : tvSplit?.[0];
```suggestion
			presenceData.details = privacy ? "Watching a TV series" : tvSplit?.[0];
```

2023-08-08 21:53 UTC, theusaf commented on websites/M/MoviesJoy/presence.ts
> +				: "Viewing top imdb content";
```suggestion
				: "Viewing top IMDb content";
```

2023-08-09 18:09 UTC, theusaf approved these changes

2023-08-09 20:00 UTC, Bas950 approved these changes

2023-08-09 20:00 UTC, merged