feat(KEXP): add presence
PreMiD/Presences pull request #7575
Opened 2023-08-12 00:21 UTC by alejsalaz

## Description 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/PreMiD/Presences/assets/86681635/50f9d28a-c7e2-4daa-a367-85a343000717)
![image](https://github.com/PreMiD/Presences/assets/86681635/b6090b05-637e-46a4-8e98-94ee1133f12f)
![image](https://github.com/PreMiD/Presences/assets/86681635/9696caf5-d010-443a-a750-58ea6e150453)
![image](https://github.com/PreMiD/Presences/assets/86681635/734d917f-34b2-4d04-8d41-0d9f4b79fa8b)

</details>

2023-08-12 20:26 UTC, theusaf reviewed
Low quality. Consider adding support for other paths/pages on the radio website.
> Presences for online radios are only allowed if the radio has at least 100 weekly listeners and 15 concurrent and **must have some features other than just showing album/song title**, etc.
> — [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#creation)

2023-08-12 20:26 UTC, theusaf commented on websites/K/KEXP/metadata.json
> +	"url": "kexp.org",
Site supports `www` subdomain
```suggestion
	"url": [
		"www.kexp.org",
		"kexp.org"
	],
```

2023-08-12 20:26 UTC, theusaf commented on websites/K/KEXP/metadata.json
> +	"logo": "https://i.imgur.com/RBf6mDU.png",
The logo should be a square.

2023-08-12 20:26 UTC, theusaf commented on websites/K/KEXP/presence.ts
> +				break;
```suggestion
```

2023-08-13 09:56 UTC, DarkVillager requested changes

2023-08-13 09:56 UTC, DarkVillager commented on websites/K/KEXP/metadata.json
> +	"logo": "https://i.imgur.com/RBf6mDU.png",
Logo's must be 512x512 as per [our guideliness](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#logo).

2023-08-19 20:14 UTC, theusaf commented
Closing for inactivity. You may open a new PR after resolving the issues mentioned in this one.

2023-08-19 20:14 UTC, closed without merging