feat(Moopa): add presence
PreMiD/Presences pull request #7576
Opened 2023-08-13 09:37 UTC by DevanAbinaya

## Description 

- Presence for [Moopa](https://moopa.live)
- Updating info dynamically on different pages
- Having buttons to see/watch currently playing anime/manga
- Have icon fallback to return logo if cover not available
- Have options to select what title language to show

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
![image](https://github.com/PreMiD/Presences/assets/97084324/76e4b105-26b3-4106-9b70-0866feb21cdb)
![image](https://github.com/PreMiD/Presences/assets/97084324/04c1701e-4a97-420b-a26d-b4912934c36c)
![image](https://github.com/PreMiD/Presences/assets/97084324/51e47084-cb01-4659-b2e2-f43b86a8b6ac)
![image](https://github.com/PreMiD/Presences/assets/97084324/0359972e-270d-4d4a-8719-7b70ad5ee2c5)
![image](https://github.com/PreMiD/Presences/assets/97084324/d6d73396-b8c8-47fe-9f5b-eb6e1035edcd)
![image](https://github.com/PreMiD/Presences/assets/97084324/779d8799-83a3-4475-a692-e8e1c20e6a81)
![image](https://github.com/PreMiD/Presences/assets/97084324/f729e645-c028-40d9-800b-a9222478860c)
</details>

2023-08-13 09:54 UTC, DarkVillager requested changes

2023-08-13 09:54 UTC, DarkVillager commented on websites/M/Moopa/metadata.json
> +	"logo": "https://i.imgur.com/BzZw6aQ.png",
Logo's must be 512x512 as per [our guideliness](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#logo).

2023-08-13 09:54 UTC, DarkVillager commented on websites/M/Moopa/presence.ts
> +	Logo = "https://i.imgur.com/BzZw6aQ.png",
Ditto

2023-08-13 09:54 UTC, DarkVillager commented on websites/M/Moopa/presence.ts
> +			largeImageKey: Assets.Logo,
Why repeat it when you can just add it here?
```suggestion
			largeImageKey: Assets.Logo,
			startTimestamp: browsingTimestamp,
```

2023-08-13 09:54 UTC, DarkVillager commented on websites/M/Moopa/presence.ts
> +		presenceData.startTimestamp = browsingTimestamp;
```suggestion
```

2023-08-13 09:54 UTC, DarkVillager commented on websites/M/Moopa/presence.ts
> +		presenceData.startTimestamp = browsingTimestamp;
```suggestion
```

2023-08-13 09:54 UTC, DarkVillager commented on websites/M/Moopa/presence.ts
> +		presenceData.startTimestamp = browsingTimestamp;
```suggestion
```

2023-08-15 01:31 UTC, theusaf requested changes

2023-08-15 01:31 UTC, theusaf commented on websites/M/Moopa/presence.ts
> +		presence.clearActivity();
Probably unneeded, as the activity is immediately set after this
```suggestion
```

2023-08-15 01:31 UTC, theusaf commented on websites/M/Moopa/presence.ts
> +			}
This chunk of code is pretty large and repeated, it could be better as its own function.

2023-08-16 10:49 UTC, DarkVillager requested changes

2023-08-16 10:49 UTC, DarkVillager commented on websites/M/Moopa/metadata.json
> +	"color": "#141519",
This color is the base color used when something is selected or hovered on
```suggestion
	"color": "#FF7F57",
```

2023-08-16 20:47 UTC, theusaf approved these changes

2023-08-16 21:25 UTC, Bas950 approved these changes

2023-08-16 21:25 UTC, merged