Sosac
PreMiD/Presences pull request #7596
Opened 2023-08-24 14:57 UTC by jayjakee

feat(Sosac): added to PreMiD

## Description 
Created. Sosac is a streaming platform for movies and series, The service is paid, currently there are just watching statuses (series including ep number) and browsing

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>
![image](https://github.com/PreMiD/Presences/assets/68172465/1a600530-0e4c-4720-9c0b-4f5dd8d6fa44)
![image](https://github.com/PreMiD/Presences/assets/68172465/39528196-9a4c-405f-a8a9-1550ec654769)
![image](https://github.com/PreMiD/Presences/assets/68172465/c19efcf6-7709-48fa-b7b0-a4dde791be0c)
![image](https://github.com/PreMiD/Presences/assets/68172465/ba029a14-4765-48db-bb45-7ee7739b6394)
![image](https://github.com/PreMiD/Presences/assets/68172465/450923a7-417d-419f-b69a-d1911b4cb4fd)

works fine, more features are planned!

2023-08-24 17:26 UTC, theusaf requested changes
Make sure to resolve the CI issues.

2023-08-24 17:26 UTC, theusaf commented on websites/S/Sosac/metadata.json
> +	"$schema": "https://schemas.premid.app/metadata/1.7",
```suggestion
	"$schema": "https://schemas.premid.app/metadata/1.9",
```

2023-08-28 13:51 UTC, jayjakee commented on websites/S/Sosac/presence.ts
> +	presenceData.smallImageText = (await strings).browsing;
Fixed.

2023-08-29 17:41 UTC, theusaf approved these changes
Not much here, but looks okay.

2023-08-29 19:40 UTC, jayjakee commented on websites/S/Sosac/metadata.json
> +	"iFrameRegExp": ".*"
What exactly is on your mind?

2023-08-29 19:43 UTC, Bas950 commented on websites/S/Sosac/metadata.json
> +	"iFrameRegExp": ".*"
Using a different regex for the iframe, `.*` is everything, if you could narrow it down to a url regex it would be better.

2023-09-01 17:46 UTC, theusaf commented on websites/S/Sosac/metadata.json
> +	"iFrameRegExp": ".*"
For example, if the iframes the videos are embedded in are at urls like `https://media.example.com/foo` and/or `https://media2.example.com/bar`, some regular expressions that could work could be:
* `media.*[.]example[.]com[/]`
* `.*[.]example[.]com[/]`
* etc.

2023-09-03 04:17 UTC, theusaf approved these changes

2023-09-03 10:44 UTC, Bas950 approved these changes

2023-09-03 10:44 UTC, merged