Updated the goplay website.
PreMiD/Presences pull request #7641
Opened 2023-09-30 08:32 UTC by lizsdswsd

## Description 

goplay/anontpp changed their domain from "goplay.ml" to "goplay.pw"

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

2023-10-02 20:47 UTC, theusaf requested changes
Please also provide screenshots showing that the presence is working.

2023-10-02 20:47 UTC, theusaf commented on websites/A/Anontpp/metadata.json
>  	"version": "1.1.9",
Bump the version
```suggestion
	"version": "1.1.10",
```

2023-10-03 03:20 UTC, lizsdswsd commented
> Please also provide screenshots showing that the presence is working.

it doesnt seem to be showing on my profile...

2023-10-03 03:50 UTC, theusaf commented
> it doesnt seem to be showing on my profile...

If it doesn't appear on your Discord profile, try the troubleshooting steps listed in the support channel on Discord. If those don't work, try logging the presence data variable and taking a screenshot of the console logs instead?

2023-10-03 04:02 UTC, lizsdswsd commented
> > it doesnt seem to be showing on my profile...
> 
> If it doesn't appear on your Discord profile, try the troubleshooting steps listed in the support channel on Discord. If those don't work, try logging the presence data variable and taking a screenshot of the console logs instead?

how do i do the second part?

2023-10-03 04:41 UTC, theusaf commented
> > > it doesnt seem to be showing on my profile...
> > 
> > 
> > If it doesn't appear on your Discord profile, try the troubleshooting steps listed in the support channel on Discord. If those don't work, try logging the presence data variable and taking a screenshot of the console logs instead?
> 
> how do i do the second part?

Actually, it's okay. I've verified that the site's page content has not changed, so the presence should work.

2023-10-03 04:41 UTC, theusaf approved these changes

2023-10-03 05:10 UTC, Bas950 approved these changes

2023-10-03 05:10 UTC, merged