feat(OneTouchTV): add presence
PreMiD/Presences pull request #7653
Opened 2023-10-08 10:36 UTC by DarkVillager

## Description 

Added the presence
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://github.com/PreMiD/Presences/assets/42322979/b89f8016-a758-4183-b025-0437f9d742af">
<img src="https://github.com/PreMiD/Presences/assets/42322979/55087b56-e6a9-4366-a56f-d82f45fc309f">
<img src="https://github.com/PreMiD/Presences/assets/42322979/abc81968-4b0e-4e4c-9a6d-9fbf78a330fc">
<img src="https://github.com/PreMiD/Presences/assets/42322979/0e8a92ae-f674-431f-8066-3d59198e334b">

</details>

2023-10-08 10:46 UTC, DarkVillager commented on websites/O/OneTouchTV/metadata.json
> +	"iFrameRegExp": ".*"
I'll look into this, cuz i think its possible to change it.

2023-10-08 10:46 UTC, DarkVillager commented on websites/O/OneTouchTV/presence.ts
> +									"flt-scene-host > flt-scene > flt-transform > flt-offset > flt-offset > flt-clip > flt-clip-interior > flt-offset > flt-clip > flt-clip-interior > flt-clip > flt-clip-interior > flt-offset >
This can't be shortened without making it unstable

2023-10-08 10:46 UTC, DarkVillager commented on websites/O/OneTouchTV/presence.ts
> +				episode = title?.includes("Episode");
I will change this.

2023-10-08 13:46 UTC, Bas950 commented on websites/O/OneTouchTV/presence.ts
> +class iframeData {
probs want to use interface here

2023-10-09 08:15 UTC, DarkVillager commented on websites/O/OneTouchTV/presence.ts
> +	let hash: string = href;
```suggestion
		{ href, pathname } = document.location,
	hash = href;
```

2023-10-11 22:23 UTC, theusaf requested changes

2023-10-11 22:23 UTC, theusaf commented on websites/O/OneTouchTV/iframe.ts
> +	}
Strange use of switch, could be an if statement.

2023-10-11 22:23 UTC, theusaf commented on websites/O/OneTouchTV/metadata.json
> +	"url": "onetouchtv.me",
The domain appears to have changed. Perhaps a regex may be useful as well?
```suggestion
	"url": "onetouchtv.cc",
```

2023-10-14 11:44 UTC, Bas950 approved these changes

2023-10-14 20:22 UTC, theusaf approved these changes

2023-10-14 20:22 UTC, merged