feat(v0): add presence
PreMiD/Presences pull request #7654
Opened 2023-10-09 18:47 UTC by Steellgold

Add metadata.json file for the v0 website, which includes information about the author, service, description, URL, version, logo, thumbnail, color, category, and tags.

Add presence.ts file for the v0 website, which handles the presence data for different pages of the website. It sets the details, state, buttons, and images based on the current page being viewed.

## Description 

## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/PreMiD/Presences/assets/51505384/8fccbf6a-d6b1-4590-bf97-c66db52fa096)
![image](https://github.com/PreMiD/Presences/assets/51505384/a6e395e7-ac63-484f-80aa-fd8bd13fd210)
![image](https://github.com/PreMiD/Presences/assets/51505384/14d6249b-96ce-4d5b-8c6e-34a338f19d58)

</details>

2023-10-09 19:02 UTC, Steellgold commented
![image](https://github.com/PreMiD/Presences/assets/51505384/ecc91bfb-48bd-4ff3-a78a-aa24fcca63f0)

https://github.com/PreMiD/Presences/actions/runs/6460632640/job/17538716799?pr=7654

🥸

2023-10-09 19:39 UTC, Bas950 commented
> ![image](https://user-images.githubusercontent.com/51505384/273674717-ecc91bfb-48bd-4ff3-a78a-aa24fcca63f0.png)
> 
> https://github.com/PreMiD/Presences/actions/runs/6460632640/job/17538716799?pr=7654
> 
> 🥸

Schema version is not up to date - expected: https://schemas.premid.app/metadata/1.9, got: https://schemas.premid.app/metadata/1.7

2023-10-09 19:50 UTC, Steellgold commented
> > ![image](https://user-images.githubusercontent.com/51505384/273674717-ecc91bfb-48bd-4ff3-a78a-aa24fcca63f0.png)
> > https://github.com/PreMiD/Presences/actions/runs/6460632640/job/17538716799?pr=7654
> > 🥸
> 
> Schema version is not up to date - expected: https://schemas.premid.app/metadata/1.9, got: https://schemas.premid.app/metadata/1.7

Concretely, what do I have to modify? I don't really understand.

2023-10-09 19:54 UTC, Steellgold commented
@Bas950 Fixed in https://github.com/PreMiD/Presences/pull/7654/commits/97621c16dc6bbdd9dfa24a47dd9ff141e4aefdc7

But: "HTTPError: Response code 403 (rate limit exceeded)" in the github action

2023-10-09 20:06 UTC, Bas950 requested changes
Please do test these changes locally, but some small improvements, for the rest lgtm

2023-10-09 20:06 UTC, Bas950 commented on websites/V/v0/presence.ts
> +			presenceData.smallImageKey = "";
```suggestion
			delete presenceData.smallImageKey;
```

2023-10-09 20:06 UTC, Bas950 commented on websites/V/v0/presence.ts
> +			presenceData.buttons = null;
```suggestion
			delete presenceData.buttons;
```

2023-10-09 20:06 UTC, Bas950 commented on websites/V/v0/presence.ts
> +				document.querySelector("img.rounded-full.h-12.w-12") as HTMLImageElement
```suggestion
				document.querySelector<HTMLImageElement>("img.rounded-full.h-12.w-12")
```

2023-10-09 20:06 UTC, Bas950 commented on websites/V/v0/presence.ts
> +				(document.querySelector("a.flex-none") as HTMLAnchorElement).href.split(
```suggestion
				document.querySelector<HTMLAnchorElement>("a.flex-none").href.split(
```

2023-10-09 20:06 UTC, Bas950 commented on websites/V/v0/presence.ts
> +const presence = new Presence({ clientId: "1160993221854380132" }),
```suggestion
const enum Assets {
	Logo = "https://i.imgur.com/UhCCRnQ.png",
}

const presence = new Presence({ clientId: "1160993221854380132" }),
```

2023-10-09 20:06 UTC, Bas950 commented on websites/V/v0/presence.ts
> +		largeImageKey: "https://i.imgur.com/UhCCRnQ.png",
```suggestion
		largeImageKey: Assets.Logo,
```

2023-10-09 20:06 UTC, Bas950 commented on websites/V/v0/presence.ts
> +			presenceData.largeImageKey = "https://i.imgur.com/UhCCRnQ.png";
```suggestion
			presenceData.largeImageKey = Assets.Logo;
```

2023-10-09 20:06 UTC, Bas950 commented on websites/V/v0/presence.ts
> +			presenceData.smallImageKey = "https://i.imgur.com/UhCCRnQ.png";
```suggestion
			presenceData.smallImageKey = Assets.Logo;
```

2023-10-09 20:06 UTC, Bas950 commented
> @Bas950 Fixed in [97621c1](https://github.com/PreMiD/Presences/commit/97621c16dc6bbdd9dfa24a47dd9ff141e4aefdc7)
> 
> But: "HTTPError: Response code 403 (rate limit exceeded)" in the github action

Yea sorry that happens sometimes.

2023-10-09 20:13 UTC, Steellgold commented on websites/V/v0/presence.ts
> +			presenceData.smallImageKey = "https://i.imgur.com/UhCCRnQ.png";
".Logo" not exist

2023-10-09 20:21 UTC, Steellgold commented
![image](https://github.com/PreMiD/Presences/assets/51505384/f86c5315-4e13-4cf9-9974-24b8ed813fd3)

2023-10-09 20:21 UTC, Steellgold commented
> Please do test these changes locally, but some small improvements, for the rest lgtm

Work

2023-10-10 06:43 UTC, Bas950 approved these changes

2023-10-10 21:14 UTC, theusaf approved these changes

2023-10-10 21:14 UTC, merged