feat(Discord SFX): Add presence
PreMiD/Presences pull request #7661
Opened 2023-10-15 06:38 UTC by chimpdev

## Description 
Added a presence files for discordsfx.com

## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/PreMiD/Presences/assets/55600314/5c8a6717-3923-4054-b2c7-5c17f0aa276e)

![image](https://github.com/PreMiD/Presences/assets/55600314/9d94108f-fc8c-4976-b222-64acd81966b6)

![image](https://github.com/PreMiD/Presences/assets/55600314/2f6c2db0-29fe-40c1-9c10-d6307704572b)

![image](https://github.com/PreMiD/Presences/assets/55600314/900bca5a-4880-485c-bdf8-314824789618)

![image](https://github.com/PreMiD/Presences/assets/55600314/01db56e6-c704-46c2-944a-a5084cf1441e)
</details>

2023-10-18 05:58 UTC, theusaf commented on websites/D/Discord SFX/metadata.json
> +	"logo": "https://i.imgur.com/T6CpbXk.png",
May be difficult to see for light-mode users. Consider adding the background color.

2023-10-18 14:58 UTC, theusaf requested changes

2023-10-18 14:58 UTC, theusaf commented on websites/D/Discord SFX/presence.ts
> +			largeImageKey: "https://i.imgur.com/T6CpbXk.png",
```suggestion
			largeImageKey: "https://i.imgur.com/Sr6B9gS.png",
```

2023-10-20 22:18 UTC, theusaf approved these changes

2023-10-21 09:00 UTC, Bas950 requested changes

2023-10-21 09:00 UTC, Bas950 commented on websites/D/Discord SFX/presence.ts
> +				label: "View on Discord SFX",
View Page or View Sound

2023-10-21 09:00 UTC, Bas950 commented on websites/D/Discord SFX/presence.ts
> +						label: "View on Discord SFX",
Ditto

2023-10-21 09:05 UTC, Bas950 approved these changes

2023-10-21 09:05 UTC, merged