chore: update assets
PreMiD/Presences pull request #7669
Opened 2023-10-18 07:16 UTC by SeMiD

*beep boop* I've updated some assets...

2023-10-18 14:56 UTC, theusaf submitted a review, later dismissed

2023-10-18 17:00 UTC, Bas950 requested changes

2023-10-18 17:00 UTC, Bas950 commented on websites/B/BeatSaver/presence.ts
> +	LegacyNormal = "https://cdn.rcd.gg/PreMiD/websites/B/BeatSaver/assets/4.png",
Don't think  these indexes are correct, will look at it tomorrow at work

2023-10-21 08:57 UTC, Bas950 commented
Well knew I forgot something, will try to look at it later

2023-10-21 18:21 UTC, Bas950 approved these changes

2023-10-21 18:35 UTC, merged