feat(atomicradio): add atomicradio presence
PreMiD/Presences pull request #7689
Opened 2023-10-23 04:14 UTC by VocalZero

## Description 

Added a presence for https://atomic.radio

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://github.com/PreMiD/Presences/assets/20924469/f8a0e113-bfba-4dca-b6a2-853435b758a3" />
<br>
<img src="https://github.com/PreMiD/Presences/assets/20924469/2b270be2-5331-48c5-ae5c-aa29bdab53eb" />

</details>

2023-10-23 22:10 UTC, theusaf requested changes

2023-10-23 22:10 UTC, theusaf commented on websites/A/atomicradio/presence.ts
> +			largeImageKey: "logo",
```suggestion
			largeImageKey: "https://i.imgur.com/16lVdWy.png",
```

2023-10-23 22:10 UTC, theusaf commented on websites/A/atomicradio/presence.ts
> +			smallImageKey: "search",
Use image links or [provided assets](https://github.com/PreMiD/Presences/blob/c598cf31f004d621445e57a67b41c158b291fd2f/%40types/premid/index.d.ts#L78-L96) over Discord asset names.
```suggestion
			smallImageKey: Assets.Search,
```

2023-10-23 22:10 UTC, theusaf commented on websites/A/atomicradio/presence.ts
> +				: "play";
```suggestion
				? Assets.Pause
				: Assets.Play;
```

2023-10-24 11:28 UTC, DarkVillager commented on websites/A/atomicradio/metadata.json
> +	"logo": "https://i.imgur.com/16lVdWy.png",
Logo's must be 512x512 as per our [our guideliness](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#logo).

2023-10-24 11:29 UTC, DarkVillager commented on websites/A/atomicradio/presence.ts
> +			largeImageKey: "https://i.imgur.com/16lVdWy.png",
Ditto (Logo's must be 512x512 as per [our guideliness](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#logo).)

2023-10-24 11:30 UTC, DarkVillager commented on websites/A/atomicradio/presence.ts
> +			"div.container > #artwork"
Try to shorten selectors where possible like here:
```suggestion
			"#artwork"
```

2023-10-24 11:32 UTC, DarkVillager commented on websites/A/atomicradio/presence.ts
> +				"div.container > div.center-controls > button"
Ditto. (Try to shorten selectors where possible like here:)
```suggestion
				'[id*="-button"]'
```

2023-10-24 11:33 UTC, DarkVillager commented on websites/A/atomicradio/presence.ts
> +			"div.container > a > div.track-info > a.track-title"
Ditto. (Try to shorten selectors where possible like here:)
```suggestion
			"a.track-title"
```

2023-10-24 11:33 UTC, DarkVillager commented on websites/A/atomicradio/presence.ts
> +			"div.container > a > div.track-info > div.track-artist"
Ditto. (Try to shorten selectors where possible like here:)
```suggestion
			"div.track-artist"
```

2023-10-24 11:34 UTC, DarkVillager commented on websites/A/atomicradio/presence.ts
> +			"div.container > #spaceId"
Ditto. (Try to shorten selectors where possible like here:)
```suggestion
			" #spaceId"
```

2023-10-24 19:49 UTC, Bas950 approved these changes

2023-10-25 08:23 UTC, DarkVillager requested changes

2023-10-25 08:23 UTC, DarkVillager commented on websites/A/atomicradio/presence.ts
> +		player = document.querySelector<HTMLDivElement>("div.player");
```suggestion
		player = document.querySelector<HTMLDivElement>("div.player"),
		{pathname} = document.location;
```

2023-10-25 08:23 UTC, DarkVillager commented on websites/A/atomicradio/presence.ts
> +	}
```suggestion
		if (pathname.includes("/statistics"))
			presenceData.details = "Viewing statistics";
		else if (pathname.includes("/streams"))
			presenceData.details = "Viewing stream urls";
		else if (pathname.includes("/about"))
			presenceData.details = "Viewing about us";
		else if (pathname.includes("/apply"))
			presenceData.details = "Viewing apply";
		else if (pathname.includes("/contributors"))
			presenceData.details = "Viewing contributors";
		else if (pathname.includes("/partners"))
			presenceData.details = "Viewing partners";
		else if (pathname.includes("/legal/imprint"))
			presenceData.details = "Viewing imprint";
		else if (pathname.includes("/legal/privacy"))
			presenceData.details = "Viewing privacy";
		else if (pathname.includes("/account"))
			presenceData.details = "Viewing account";
	}
```

2023-10-25 15:08 UTC, theusaf approved these changes

2023-10-25 17:58 UTC, Bas950 approved these changes

2023-10-25 17:58 UTC, merged