feat(ッツ Reader): add presence
PreMiD/Presences pull request #7706
Opened 2023-10-26 19:11 UTC by alexay7

## Description 
Add presence for ッツ Reader

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/PreMiD/Presences/assets/43906716/1af14296-d702-4522-b93c-bfb8f609b3fe)

![image](https://github.com/PreMiD/Presences/assets/43906716/03c9a469-d15a-4ce9-901b-a1b183912134)

![image](https://github.com/PreMiD/Presences/assets/43906716/56be1f83-a047-4cff-a240-e57a60e99185)

![image](https://github.com/PreMiD/Presences/assets/43906716/1c48e91e-c7b4-45dd-bbae-8380cf00a61d)

</details>

2023-10-27 16:08 UTC, alexay7 commented on websites/#/ッツ Ebook Reader/metadata.json
> +	"logo": "https://i.imgur.com/Yl7EnGB.png",
Should be fixed now

2023-10-27 17:26 UTC, theusaf requested changes

2023-10-27 17:26 UTC, theusaf commented on websites/#/ッツ Ebook Reader/presence.ts
> +	Logo = "https://github.com/ttu-ttu/ebook-reader/raw/main/assets/readme/icon.png",
```suggestion
	Logo = "https://i.imgur.com/jQqmgCA.png",
```

2023-10-28 16:23 UTC, theusaf approved these changes

2023-10-28 19:14 UTC, Bas950 approved these changes

2023-10-28 19:14 UTC, merged