feat(Character.AI): add presence
PreMiD/Presences pull request #7739
Opened 2023-11-15 19:11 UTC by joerkig

## Description 

Add presence for Character.AI
Resolves #7573 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![Discord_Uvhlb1Mt9q](https://github.com/PreMiD/Presences/assets/44418429/d76b4b38-f6d7-436d-bc83-b8639fcff0db)
![Discord_IDXH4rVlkF](https://github.com/PreMiD/Presences/assets/44418429/d12918ae-2d66-4738-a528-32f9d3474217)
![Discord_J9nMNoKmHB](https://github.com/PreMiD/Presences/assets/44418429/2ad788e0-c714-4b54-9521-a2add667f447)
![Discord_uJwd6LNTxV](https://github.com/PreMiD/Presences/assets/44418429/8375bf94-0292-4121-a52d-23200fc00861)
![tr4rCq6FCp](https://github.com/PreMiD/Presences/assets/44418429/61deadec-7b2a-426b-a0fc-f1a2c3c1e09c)

</details>

2023-11-15 19:22 UTC, Bas950 requested changes

2023-11-15 19:22 UTC, Bas950 commented on websites/C/Character.AI/presence.ts
> +	logo = "https://i.imgur.com/fvjZLpL.png",
Use the const enum

2023-11-15 19:22 UTC, Bas950 commented on websites/C/Character.AI/presence.ts
> +	},
think its better to define this button const in the updatedata event, otherwise it wouldn't get updated on url replacements.

2023-11-16 14:46 UTC, Bas950 approved these changes

2023-11-16 16:17 UTC, theusaf approved these changes

2023-11-16 16:17 UTC, merged