feat(Poolsuite FM): add presence
PreMiD/Presences pull request #7740
Opened 2023-11-16 00:01 UTC by lanewills

## Description 
Add rich presence for the music website Poolsuite FM

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
![Playing](https://github.com/PreMiD/Presences/assets/94198057/5b93ba57-3ce1-4408-a227-9109987484a0)
![paused](https://github.com/PreMiD/Presences/assets/94198057/b1a725ce-d9f4-448e-9b86-6a553761643c)

</details>

2023-11-16 09:49 UTC, Bas950 requested changes

2023-11-16 09:49 UTC, Bas950 commented on websites/P/Poolsuite FM/presence.ts
> +			largeImageKey: "https://i.imgur.com/TpNi1Kf.jpeg",
ditto

2023-11-16 16:21 UTC, theusaf requested changes

2023-11-16 16:21 UTC, theusaf commented on websites/P/Poolsuite FM/metadata.json
> +	"logo": "https://i.imgur.com/TpNi1Kf.jpeg",
Should be 512x512px

2023-11-16 19:19 UTC, theusaf approved these changes

2023-11-17 17:25 UTC, Bas950 approved these changes

2023-11-17 17:25 UTC, merged