feat(Smash Pros): add presence
PreMiD/Presences pull request #7756
Opened 2023-11-24 23:20 UTC by CERLgit

## Description 
Add presence for Smash Pros, a skill based match making service for Super Smash Bros. Ultimate.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>

![Screenshot from 2023-11-24 17-44-37](https://github.com/PreMiD/Presences/assets/52587794/484dc215-916a-4df7-963d-315b05dd6b99)

![Screenshot from 2023-11-24 17-44-28](https://github.com/PreMiD/Presences/assets/52587794/eaff1e51-59ec-47a5-85ee-1293d82fdf1d)

![Screenshot from 2023-11-24 17-43-11](https://github.com/PreMiD/Presences/assets/52587794/defec1d3-7a54-4fbb-b782-1ef64014e0f4)

![Screenshot from 2023-11-24 17-42-56](https://github.com/PreMiD/Presences/assets/52587794/7af607dd-e3c6-4eeb-9dc9-da53dbc04e9e)

![Screenshot from 2023-11-24 17-40-54](https://github.com/PreMiD/Presences/assets/52587794/76b9a26f-d990-4f6c-9800-3c58daa1f866)

![Screenshot from 2023-11-24 17-40-50](https://github.com/PreMiD/Presences/assets/52587794/fd184156-a291-4103-8972-9c9cb6b02d02)

![Screenshot from 2023-11-24 17-40-45](https://github.com/PreMiD/Presences/assets/52587794/870579f1-95e0-4e0d-a7a8-4820c01ce31b)

![Screenshot from 2023-11-24 17-40-39](https://github.com/PreMiD/Presences/assets/52587794/3f509654-02f9-4966-b045-7642ffe6648c)

![Screenshot from 2023-11-24 17-32-28](https://github.com/PreMiD/Presences/assets/52587794/8cf5958f-1eda-4ed8-b2b6-f0b63c9e9443)

</details>

2023-11-24 23:26 UTC, theusaf requested changes

2023-11-24 23:26 UTC, theusaf commented on websites/S/Smash Pros/metadata.json
> +	"url": "smashpros.gg",
Website supports www subdomain
```suggestion
	"url": [
		"smashpros.gg",
		"www.smashpros.gg"
	],
```

2023-11-24 23:26 UTC, theusaf commented on websites/S/Smash Pros/presence.ts
> +		presenceData.buttons = [{ label: "View this profile", url: href }];
Simplify/standardize label
```suggestion
		presenceData.buttons = [{ label: "View Profile", url: href }];
```

2023-11-24 23:32 UTC, theusaf requested changes

2023-11-24 23:32 UTC, theusaf commented on websites/S/Smash Pros/presence.ts
> +		presenceData.buttons = [{ label: "View profile", url: href }];
Button label words should be capitalized
```suggestion
		presenceData.buttons = [{ label: "View Profile", url: href }];
```

2023-11-24 23:38 UTC, theusaf approved these changes

2023-11-25 12:23 UTC, Bas950 approved these changes

2023-11-25 12:23 UTC, merged