fix(Youtube Music): no href temp fix
PreMiD/Presences pull request #7805
Opened 2023-12-06 02:26 UTC by veryCrunchy

## Description 

https://discord.com/channels/493130730549805057/1181769179070734398
![image](https://github.com/PreMiD/Presences/assets/73395916/7a2c907f-7b05-4b0b-98b8-40257bc0df06)

The issue is still there and will have to be looked into.
Only added null check, to prevent error / presence freezing

Currently, the listen along button won't lead to the actual song
![image](https://github.com/PreMiD/Presences/assets/73395916/e8c1baf7-772b-4a0c-96bb-2875c026245c) ![image](https://github.com/PreMiD/Presences/assets/73395916/843b4a96-68d7-48fc-9ac1-636c41d8e4b9)

2023-12-06 02:27 UTC, veryCrunchy commented
[chore: bump schema](https://github.com/PreMiD/Presences/commit/7e407e32f3b5c6090b8d17cb820d83d22c4a2654) should be "bump version"... I'm sleep deprived

2023-12-06 02:38 UTC, veryCrunchy commented
![image](https://github.com/PreMiD/Presences/assets/73395916/f36d18b2-79fb-466f-8687-b91aff9080c8)
They've removed all hrefs to the current playing song....

2023-12-06 04:18 UTC, theusaf requested changes

2023-12-06 04:18 UTC, theusaf commented on websites/Y/YouTube Music/presence.ts
> +			window.location.href.match(/v=([^&#]{5,})/)?.[1] ??
```suggestion
		watchID = href.match(/v=([^&#]{5,})/)?.[1] ??
```

2023-12-06 04:31 UTC, veryCrunchy commented on websites/Y/YouTube Music/presence.ts
> +			window.location.href.match(/v=([^&#]{5,})/)?.[1] ??
Where are you getting href from?

2023-12-06 05:47 UTC, theusaf commented on websites/Y/YouTube Music/presence.ts
> +			window.location.href.match(/v=([^&#]{5,})/)?.[1] ??
> Where are you getting `href` from?

Line 13.
```ts
const { pathname, search, href } = document.location,
```

2023-12-07 22:29 UTC, Bas950 approved these changes

2023-12-08 01:10 UTC, theusaf approved these changes

2023-12-08 01:10 UTC, merged