chore(Instagram): rewrite presence
PreMiD/Presences pull request #7829
Opened 2023-12-23 14:30 UTC by DarkVillager

## Description 

- if/elseif => switch
- add reels support w/ cache & buttons

To do:
- Add buttons
- Cleanup privacy
- Support /reel/ on user profile

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

n/a yet

</details>

2023-12-23 20:21 UTC, DarkVillager commented on websites/I/Instagram/presence.ts
> +				const check = Array.from(videos).filter(video => !video.paused),
```suggestion
			if (!cached?.href || !cached?.video || cached?.href !== href) {
				const check = Array.from(document.querySelectorAll("video")).filter(video => !video.paused),
```

2023-12-24 21:44 UTC, Bas950 requested changes
Can you improve the queryselelectors in any way, cause right now they are just the random generated class names

2023-12-25 10:11 UTC, DarkVillager commented
> Can you improve the queryselelectors in any way, cause right now they are just the random generated class names

No.

2023-12-25 11:24 UTC, Bas950 approved these changes

2023-12-25 16:51 UTC, theusaf approved these changes

2023-12-25 16:51 UTC, merged