feat(Craiyon): update selectors, add blog, search
PreMiD/Presences pull request #7844
Opened 2023-12-25 20:32 UTC by theusaf

## Description 

* Updates query selectors for new layout
* Adds support for blog, search, and individual image pages

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/PreMiD/Presences/assets/32113157/784ea300-8657-4a9a-a4f0-0ef150a287cb)
![image](https://github.com/PreMiD/Presences/assets/32113157/ea6208a0-4b50-47f3-bda9-2156d77c3faa)
![image](https://github.com/PreMiD/Presences/assets/32113157/12670525-7253-4c73-8e1c-d8a6148c2319)
![image](https://github.com/PreMiD/Presences/assets/32113157/eb353642-61c7-4b0c-9f27-be6db7f3dbd7)
![image](https://github.com/PreMiD/Presences/assets/32113157/db6a03da-7569-48ce-b417-5b10ef82f150)

</details>

2023-12-26 10:08 UTC, Bas950 requested changes

2023-12-26 10:08 UTC, Bas950 commented on websites/C/Craiyon/presence.ts
> +				slideshow.currentSlide = slideshow.getSlides()[0].data;
https://discord.com/channels/493130730549805057/1188944048728309770/1188944048728309770
Will convert to draft for now

2023-12-27 20:17 UTC, Bas950 requested changes
This (see previous requested change) code should no longer be needed

2023-12-27 22:02 UTC, Bas950 approved these changes

2023-12-29 22:38 UTC, Timeraa approved these changes

2023-12-29 22:38 UTC, merged