feat(taiyō): Add presence
PreMiD/Presences pull request #7845
Opened 2023-12-25 22:35 UTC by Luscarvalho

## Description 
Add presence for Taiyō, a manga reader

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Saiba mais </summary>

## Home

![image](https://github.com/PreMiD/Presences/assets/71954875/46c6d757-cc3f-4b39-bfb4-3d82b4feea6f)

## Mangá page

![image](https://github.com/PreMiD/Presences/assets/71954875/0e58f8b5-91b3-4feb-b13e-1767d83011cd)

## Chapter page

![image](https://github.com/PreMiD/Presences/assets/71954875/f38ccd08-640d-4a23-949d-36094d96f422)

## Dashboard

![image](https://github.com/PreMiD/Presences/assets/71954875/e768615f-3e46-4179-b906-a991cb0e4bb1)

## Upload

![image](https://github.com/PreMiD/Presences/assets/71954875/15ed014f-7293-4577-a707-d28ae8924dc7)

</details>

2023-12-25 22:49 UTC, theusaf requested changes

2023-12-25 22:49 UTC, theusaf commented on websites/T/Taiyō/metadata.json
> +	"url": "taiyo.moe",
Site supports `www` subdomain.
```suggestion
	"url": [
		"taiyo.moe",
		"www.taiyo.moe"
	],
```

2023-12-25 23:26 UTC, theusaf approved these changes

2023-12-26 10:09 UTC, Bas950 approved these changes

2023-12-26 10:09 UTC, merged