feat(ArcViewer): add presence
PreMiD/Presences pull request #7847
Opened 2023-12-25 22:58 UTC by joerkig

## Description 

First time using getLogs please help me improve if needed. did test leaving page open on new extension version did not seem to cause slowdowns even after leaving open for more than 10 minutes when the old version would've, maybe don't merge until new extension version is on chrome?

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/PreMiD/Presences/assets/44418429/ffe4dfc1-3022-4d92-8521-0db56578fab4)
![image](https://github.com/PreMiD/Presences/assets/44418429/4c26fdcb-c1f3-41ab-b288-deb7497bd1ef)

</details>

2023-12-25 23:09 UTC, theusaf commented
Marking as draft. Currently, `getLogs` is a bit unstable, waiting for updates to extension first. You may continue making changes to this PR.

2023-12-25 23:17 UTC, theusaf requested changes

2023-12-25 23:17 UTC, theusaf commented on websites/A/ArcViewer/presence.ts
> +	for (const line of logs) {
Make sure to merge/rebase the latest main into your branch.

Either:
* Add type check for string
* Assume strings and use string generic with `getLogs`

2023-12-27 20:19 UTC, Bas950 commented
The getLogs issues should be fixed in the extension update that was released, can you please check @joerkig

2023-12-27 21:49 UTC, theusaf approved these changes
Images look good

2023-12-27 22:05 UTC, Bas950 approved these changes

2023-12-27 22:05 UTC, merged