chore(Roblox): rewrite presence
PreMiD/Presences pull request #7860
Opened 2023-12-29 11:26 UTC by DarkVillager

## Description 

- Switch to Assets;;
- If/else if/else => Switch;
- Checks before deleting fields;
- Shorten some selectors;
- Add missing pages;

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://github.com/PreMiD/Presences/assets/42322979/b22d1aba-6b50-4c0f-817a-8a667e0e3247">
<img src="https://github.com/PreMiD/Presences/assets/42322979/ae663cdb-6726-4e0d-ab3a-22d726a22889">
<img src="https://github.com/PreMiD/Presences/assets/42322979/5cff50a3-1feb-4eca-a5bd-4295fb46df63">
<img src="https://github.com/PreMiD/Presences/assets/42322979/41b83bc6-cd04-46cf-9e04-aae41b780b05">
<img src="https://github.com/PreMiD/Presences/assets/42322979/6e9d431c-5fb7-42cb-ba8e-bd94f7fee72c">
<img src="https://github.com/PreMiD/Presences/assets/42322979/55ceff18-52d6-41e6-8db1-519f39fd8759">
<img src="https://github.com/PreMiD/Presences/assets/42322979/1ebb4875-e8f0-49de-b6ba-01b34c7ac366">
<img src="https://github.com/PreMiD/Presences/assets/42322979/408bfcf8-4680-4d93-8d22-92648e34f6aa">

</details>

2023-12-29 11:29 UTC, DarkVillager commented on websites/R/Roblox/presence.ts
> +
Need to change this since developerlogo is also used outside the developerforum thingy

2023-12-29 22:48 UTC, Bas950 requested changes
You should probs cache some of your fetch requests otherwise they might be called every 100ms or so.

2023-12-29 22:48 UTC, Bas950 commented on websites/R/Roblox/presence.ts
> +							.textContent // Friendstab
```suggestion
							.textContent // Friends tab
```

2023-12-30 09:22 UTC, DarkVillager commented
> 

I will, i did some that i could test, but there seems to be an outage.

2023-12-30 13:36 UTC, DarkVillager commented
Planning to add create today or tomorrow.

2024-01-02 22:18 UTC, theusaf requested changes

2024-01-02 22:18 UTC, theusaf commented on websites/R/Roblox/presence.ts
> +								.querySelector('[id="search-text-field"]')
For consistency with other id query selectors
```suggestion
								.querySelector("#search-text-field")
```

2024-01-02 22:18 UTC, theusaf commented on websites/R/Roblox/presence.ts
> +			const search = document.querySelector('[id="search-text-field"]');
```suggestion
			const search = document.querySelector("#search-text-field");
```

2024-01-02 22:18 UTC, theusaf commented on websites/R/Roblox/presence.ts
> +							.querySelector('[class="avatar-card-link avatar-image-link"]')
```suggestion
							.querySelector(".avatar-card-link.avatar-image-link")
```

2024-01-02 22:18 UTC, theusaf commented on websites/R/Roblox/presence.ts
> +						document.querySelector('[class="fancy-title"]')?.textContent
```suggestion
						document.querySelector(".fancy-title")?.textContent
```

2024-01-03 18:55 UTC, Bas950 approved these changes

2024-01-03 19:19 UTC, theusaf approved these changes

2024-01-03 19:34 UTC, merged