feat(Doodstreams): add presence
PreMiD/Presences pull request #7862
Opened 2023-12-29 21:04 UTC by DarkVillager

## Description 

- Added presence for doodstreams (since some series/movies/anime websites now just send you to video hosting sites like doodstreams. E.g. s.to & aniworld.to)
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://github.com/PreMiD/Presences/assets/42322979/0c3ba2a8-375b-43d5-8d5f-f22a85300518">
<img src="https://github.com/PreMiD/Presences/assets/42322979/a75208c0-153d-47f1-afd6-9ad264ad6711">
<img src="https://github.com/PreMiD/Presences/assets/42322979/12827821-090d-480a-9676-a20989919a43">
<img src="https://github.com/PreMiD/Presences/assets/42322979/72e687a0-495d-473a-957d-b3084ab9c853">

</details>

2023-12-29 21:12 UTC, DarkVillager commented on websites/D/Doodstreams/presence.ts
> +		pause: "presence.playback.paused",
```suggestion
		play: "general.playing",
		pause: "general.paused",
```

2023-12-29 22:52 UTC, Bas950 requested changes

2023-12-29 22:52 UTC, Bas950 commented on websites/D/Doodstreams/metadata.json
> +	"regExp": "(ww(w)?([0-9])?[.])?dood(s)?[.][a-z]*",
this regex is probs too narrow as their domain changes a lot cause they had doodstream.com(.tr) too

2023-12-31 17:20 UTC, Bas950 approved these changes

2024-01-03 19:15 UTC, theusaf approved these changes

2024-01-03 19:15 UTC, merged