feat(SlimeRead): add presence
PreMiD/Presences pull request #7866
Opened 2023-12-30 01:53 UTC by Luscarvalho

## Description 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Some images </summary>

home

![image](https://github.com/PreMiD/Presences/assets/71954875/a895fc8f-b73f-40a5-b9c5-5e1b4aa604db)

manga page

![image](https://github.com/PreMiD/Presences/assets/71954875/1072a2a1-16c5-4003-8fe0-386e55dabd7d)

reader page

![image](https://github.com/PreMiD/Presences/assets/71954875/fcfedb03-4424-4903-af58-76724642e9d1)

</details>

2023-12-30 09:33 UTC, DarkVillager requested changes
Try to shorten selectors where possible.

2023-12-30 09:33 UTC, DarkVillager commented on websites/S/SlimeRead/metadata.json
> +	"logo": "https://i.imgur.com/Ht1LSYT.png",
This is without the background:
```suggestion
	"logo": "https://i.imgur.com/x6NuCdk.png",
```

2023-12-30 09:33 UTC, DarkVillager commented on websites/S/SlimeRead/presence.ts
> +			largeImageKey: "https://i.imgur.com/Ht1LSYT.png",
This is without the background:
```suggestion
			largeImageKey: "https://i.imgur.com/x6NuCdk.png",
```

2023-12-30 09:33 UTC, DarkVillager commented on websites/S/SlimeRead/presence.ts
> +				)?.textContent,
```suggestion
			const chapterInfo = document.querySelector(
					'[class="ml-4 mt-4"] > h1'
				)?.textContent,
```

2023-12-30 09:33 UTC, DarkVillager commented on websites/S/SlimeRead/presence.ts
> +				).href,
```suggestion
				mediaLink = document.querySelector<HTMLAnchorElement>(
					'[class="ml-4 mt-4"] > h1 > a'
				)?.href,
```

2023-12-30 09:33 UTC, DarkVillager commented on websites/S/SlimeRead/presence.ts
> +				"p.text-dark.dark\\:text-light.transition.duration-300.text-2xl.font-bold.font-serif"
Also try to shorten selectors here

2023-12-31 10:45 UTC, DarkVillager approved these changes
LGTM

2023-12-31 12:01 UTC, Bas950 requested changes

2023-12-31 16:35 UTC, Luscarvalho commented on websites/S/SlimeRead/presence.ts
> +				'[class="mt-4 sm:ml-4 sm:mt-0  "] > p'
Yes

2023-12-31 17:19 UTC, Bas950 approved these changes

2024-01-02 21:56 UTC, theusaf approved these changes

2024-01-02 21:56 UTC, merged