feat(FlaviBot): add presence
PreMiD/Presences pull request #7869
Opened 2023-12-31 12:46 UTC by DarkVillager

## Description 

- Resolves #7853
- Add presenec for FlaviBot
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://github.com/PreMiD/Presences/assets/42322979/3e564777-eedd-421a-b0be-31bbf1dd9b6f">
<img src="https://github.com/PreMiD/Presences/assets/42322979/3bacfcee-ccff-46f2-ae49-befdb8ea4cff">
<img src="https://github.com/PreMiD/Presences/assets/42322979/cd5cd5b2-3e12-4d92-922c-4a060f174dd2">

</details>

2023-12-31 12:50 UTC, Bas950 requested changes

2023-12-31 12:50 UTC, Bas950 commented on websites/F/FlaviBot/presence.ts
> +			if (!title) presenceData.details = "Viewing te music player";
```suggestion
			if (!title) presenceData.details = "Viewing the music player";
```

2023-12-31 17:21 UTC, Bas950 approved these changes

2024-01-03 19:17 UTC, theusaf approved these changes

2024-01-03 19:17 UTC, merged