feat(Vidoza): add presence
PreMiD/Presences pull request #7872
Opened 2024-01-01 15:07 UTC by DarkVillager

## Description 

- Added presence for vidoza(since some series/movies/anime websites now just send you to video hosting sites like vidoza. E.g. s.to & aniworld.to)
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://github.com/PreMiD/Presences/assets/42322979/71a18e50-4b98-4a56-9a7f-b3a35e94a9c3">

</details>

2024-01-02 22:07 UTC, theusaf requested changes

2024-01-02 22:07 UTC, theusaf commented on websites/V/Vidoza/presence.ts
> +			title = el[el.length - 1].innerHTML
Does `.textContent` work here?

2024-01-02 22:37 UTC, DarkVillager commented on websites/V/Vidoza/presence.ts
> +			title = el[el.length - 1].innerHTML
no.

2024-01-02 23:11 UTC, theusaf approved these changes

2024-01-03 11:27 UTC, Bas950 approved these changes

2024-01-03 11:27 UTC, merged