feat(2048Verse): add presence
PreMiD/Presences pull request #7874
Opened 2024-01-01 16:34 UTC by joerkig

## Description 

Resolves #7870 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![Discord_cQHbyU3XFi](https://github.com/PreMiD/Presences/assets/44418429/71a7f432-ccf6-4131-b865-1456f9302310)
![Discord_HJcO7wFrmA](https://github.com/PreMiD/Presences/assets/44418429/0101ea57-6b1e-4025-acc4-9b3e10105b1b)
![Discord_LzLBMkKpCl](https://github.com/PreMiD/Presences/assets/44418429/985b8d0b-a517-4b9f-8db8-99ec8e74e2d1)
![Discord_YWW2Ip7QCI](https://github.com/PreMiD/Presences/assets/44418429/b2680fb6-720e-4e89-9313-2de6f65c5648)
![image](https://github.com/PreMiD/Presences/assets/44418429/b1b30447-a9e0-439c-bd33-9c6aa2016b25)

</details>

2024-01-02 22:05 UTC, theusaf requested changes

2024-01-02 22:05 UTC, theusaf commented on websites/0-9/2048Verse/metadata.json
> +	"logo": "https://i.imgur.com/wqRX0c7.png",
Appears to be off by a pixel (511x512)

2024-01-02 22:19 UTC, theusaf requested changes

2024-01-02 22:19 UTC, theusaf commented on websites/0-9/2048Verse/metadata.json
> +	"logo": "https://i.imgur.com/wqRX0c7.png",
```suggestion
	"logo": "https://i.imgur.com/aigOGhI.png",
```

2024-01-02 22:23 UTC, theusaf approved these changes

2024-01-03 11:26 UTC, Bas950 approved these changes

2024-01-03 11:26 UTC, merged