feat(BeatLeader): add logo & fix selector
PreMiD/Presences pull request #7882
Opened 2024-01-02 22:00 UTC by joerkig

## Description 

Added new christmas logo
Fixed a selector on profile pages
Buttons

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![Discord_MvMj2hnsqI](https://github.com/PreMiD/Presences/assets/44418429/75bbd509-d741-4eb5-a1b6-0a3272173ef1)
![Discord_KlGFB9Veif](https://github.com/PreMiD/Presences/assets/44418429/14b84c26-0ed2-4291-9468-3c8ba3848d76)

</details>

2024-01-02 22:03 UTC, theusaf approved these changes

2024-01-03 11:24 UTC, Bas950 requested changes

2024-01-03 11:24 UTC, Bas950 commented on websites/B/BeatLeader/presence.ts
> +		"https://i.imgur.com/4dpoXYa.gif", //Christmas 2023
Probs need to do your same fix for the gif, as christmas 2022. Don't think the gif resizing has been fixed.

2024-01-03 18:47 UTC, theusaf approved these changes

2024-01-03 18:57 UTC, merged