feat(KEXP): add presence
PreMiD/Presences pull request #7884
Opened 2024-01-03 01:38 UTC by alejsalaz

## Description 

- Add presence for [KEXP](https://kexp.org/)
- The presence updates based on whether the radio is being listened to or not
- The presence image is taken from the cover of the currently playing song; if not available, it uses the station logo
- It includes a button to listen along simultaneously
- The presence description was taken from the [About KEXP](https://www.kexp.org/about/) page and translated to Spanish as it's my native language
- If there's no song playing, only the show name is showed

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/PreMiD/Presences/assets/86681635/bb573c4f-66b2-4e1b-a866-f6aa1c67a6ee)
![image](https://github.com/PreMiD/Presences/assets/86681635/a85eed6d-ff54-4d6b-bc94-4f9d0279af60)
![image](https://github.com/PreMiD/Presences/assets/86681635/1f344e20-bb97-45d7-a425-20f0f76f5067)
![image](https://github.com/PreMiD/Presences/assets/86681635/df0943c8-3385-46df-a972-c69a3266d0d3)
![image](https://github.com/PreMiD/Presences/assets/86681635/95c685a8-efaf-40b4-8b17-12ba59e28dd1)
![image](https://github.com/PreMiD/Presences/assets/86681635/16f7a55a-ac9c-437a-9ea0-a2bfaeec75be)
![image](https://github.com/PreMiD/Presences/assets/86681635/91271de4-eb6e-4742-bd9e-57e239a26f9c)
![image](https://github.com/PreMiD/Presences/assets/86681635/0803a599-de28-42d0-a5d7-77bd912b7524)

</details>

2024-01-03 18:53 UTC, theusaf requested changes

2024-01-03 18:53 UTC, theusaf commented on websites/K/KEXP/presence.ts
> +			buttons: [{ label: "Check KEXP", url: "https://kexp.org" }],
Buttons that direct to main pages are [not allowed](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#presencets).

2024-01-03 18:53 UTC, theusaf commented on websites/K/KEXP/presence.ts
> +		currentPagePath = window.location.pathname,
This repository prefers `document.location` over `window.location`
```suggestion
		currentPagePath = document.location.pathname,
```

2024-01-03 18:53 UTC, theusaf commented on websites/K/KEXP/presence.ts
> +			: "https://i.imgur.com/RBf6mDU.png";
Use the square image. Alternatively, use an if statement to conditionally set the `largeImageKey`
```suggestion
			: "https://i.imgur.com/uzXz274.png";
```

2024-01-04 01:26 UTC, theusaf approved these changes

2024-01-04 07:45 UTC, DarkVillager requested changes

2024-01-04 07:45 UTC, DarkVillager commented on websites/K/KEXP/metadata.json
> +	"logo": "https://i.imgur.com/uzXz274.png",
Logo's must be 512x512

2024-01-04 07:45 UTC, DarkVillager commented on websites/K/KEXP/presence.ts
> +	defaultImageUrl = "https://i.imgur.com/uzXz274.png",
Ditto

2024-01-04 14:59 UTC, Bas950 approved these changes

2024-01-04 14:59 UTC, merged