feat(CacaX): new presence
PreMiD/Presences pull request #7915
Opened 2024-01-06 22:10 UTC by DorafBG

## Description 
- New presence for the social media [CacaX](https://cacax.fun).
- Shows the name of the user who you are watching. You can go to this user profile with a button "Voir le profil".
- Shows the name of the user of the post which you are watching. You can go to this post with a button "Voir le profil".
- Shows the user avatar when we are on a post or on a profile.
- When we are on the home page, the messages page, about us page, privacy page, this is shown on the presence.

## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image1](https://github.com/PreMiD/Presences/assets/58978093/de85a5ed-8ea7-4b25-a8f0-a4cc88fb7f5f)

![image2](https://github.com/PreMiD/Presences/assets/58978093/b4505c86-1842-4382-88f9-c3401cb7443e)

![image3](https://github.com/PreMiD/Presences/assets/58978093/25f5a8c2-0357-43f0-af2c-d6406acf3bd0)

![image4](https://github.com/PreMiD/Presences/assets/58978093/ca85d906-2ea4-4715-a30a-df32e3a8ad26)

![image5](https://github.com/PreMiD/Presences/assets/58978093/ebdc26ce-1897-49b7-9188-93a5e30113e4)

![image6](https://github.com/PreMiD/Presences/assets/58978093/1e7a92d6-632a-41b3-a450-3b7cbfe042cf)

![image7](https://github.com/PreMiD/Presences/assets/58978093/3f4a5af4-e50c-4626-a3b3-6ef7eba58090)

</details>

2024-01-06 22:23 UTC, theusaf requested changes
Also make sure to resolve the failed CI checks

2024-01-06 22:23 UTC, theusaf commented on websites/C/CacaX/metadata.json
> +	"url": "cacax.fun",
```suggestion
	"url": [
		"www.cacax.fun",
		"cacax.fun"
	],
```

2024-01-06 22:23 UTC, theusaf commented on websites/C/CacaX/presence.ts
> +			state: "",
Empty fields are not necessary.
```suggestion
```

2024-01-06 22:23 UTC, theusaf commented on websites/C/CacaX/presence.ts
> +			presenceData.buttons = [{label: "Voir le profil", url: href}];
Button labels should be capitalized
```suggestion
			presenceData.buttons = [{label: "Voir le Profil", url: href}];
```

2024-01-06 22:23 UTC, theusaf commented on websites/C/CacaX/presence.ts
> +				presenceData.largeImageKey = "https://www.cacax.fun/_next/image?url=%2Fimages%2Fplaceholder.png&w=1920&q=75";
```suggestion
				presenceData.largeImageKey = "https://www.cacax.fun/images/placeholder.png";
```

2024-01-06 22:23 UTC, theusaf commented on websites/C/CacaX/presence.ts
> +			presenceData.buttons = [{label: "Voir le post", url: href}];
```suggestion
			presenceData.buttons = [{label: "Voir le Post", url: href}];
```

2024-01-06 23:07 UTC, DorafBG reviewed
thank you for your comments !

2024-01-06 23:18 UTC, DorafBG commented
I dont understand how do we fix the presence validator ..

2024-01-06 23:20 UTC, theusaf commented on websites/C/CacaX/metadata.json
> +	"$schema": "https://schemas.premid.app/metadata/1.7",
```suggestion
	"$schema": "https://schemas.premid.app/metadata/1.9",
```

2024-01-06 23:26 UTC, theusaf approved these changes

2024-01-07 11:17 UTC, Bas950 approved these changes

2024-01-07 11:17 UTC, merged