feat(4chan): add presence
PreMiD/Presences pull request #7935
Opened 2024-01-13 10:01 UTC by beardotpy

## Description 

A presence for 4chan.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/PreMiD/Presences/assets/82332776/06aea42c-4a9c-427c-b9c7-0e04aa8dc4d5)

![image](https://github.com/PreMiD/Presences/assets/82332776/cb1d1033-34c5-4acc-944b-d9e1f2ca46f6)

![image](https://github.com/PreMiD/Presences/assets/82332776/dfcc16c7-cb6d-4cd5-b300-2f998790b3bf)

</details>

2024-01-13 12:06 UTC, DarkVillager requested changes

2024-01-13 12:06 UTC, DarkVillager commented on websites/0-9/4chan/presence.ts
> +	Cog = "https://i.imgur.com/XAgEs5E.png",
It must be named Logo & also must be 512x512 just like the metadata logo
```suggestion
	Logo = "https://i.imgur.com/7pI9X5M.png",
```

2024-01-13 12:06 UTC, DarkVillager requested changes

2024-01-13 12:06 UTC, DarkVillager commented on websites/0-9/4chan/presence.ts
> +		largeImageKey: Assets.Cog,
```suggestion
		largeImageKey: Assets.Logo,
```

2024-01-14 11:44 UTC, DarkVillager requested changes

2024-01-14 11:44 UTC, DarkVillager commented on websites/0-9/4chan/presence.ts
> +	};
```suggestion
	},
	{ pathname } = document.location;
```

2024-01-14 11:44 UTC, DarkVillager commented on websites/0-9/4chan/presence.ts
> +	}
```suggestion
	if (pathname === "/")
		presenceData.details = "Viewing the front page";
	else if (pathname.startsWith("/faq"))
		presenceData.details = "Reading the FAQ";
	else if (pathname.startsWith("/rules"))
		presenceData.details = "Reading the rules";
	else if (pathname.startsWith("/4channews"))
		presenceData.details = "Viewing news posts";
	else {
		for (const board in boards) {
			if (pathname.includes(board))
				presenceData.details = `Browsing ${board} - ${boards[board]}`;
		}

		if (pathname.includes("/thread/")) {
			const threadNum = pathname.split("/").at(-1),
				threadSubject = document.querySelector(".subject").textContent;

			if (threadSubject)
				presenceData.state = `>>${threadNum} - "${threadSubject}"`;
			else presenceData.state = `>>${threadNum}`;
		} else if (pathname.includes("/archive"))
			presenceData.state = "Checking the archive";
	}
```

2024-01-14 19:01 UTC, theusaf requested changes

2024-01-14 19:47 UTC, beardotpy commented on websites/0-9/4chan/metadata.json
> +	"url": "4chan.org",
fix(4chan): add support for www domain

2024-01-15 07:09 UTC, beardotpy commented
it was more than a couple hours...sorry

2024-01-15 20:10 UTC, Bas950 approved these changes

2024-01-15 20:17 UTC, theusaf approved these changes

2024-01-15 20:17 UTC, merged