feat(YouTube):
PreMiD/Presences pull request #7954
Opened 2024-01-17 23:39 UTC by veryCrunchy

My brain be hurting now..

Adds a button to overwrite the users privacy settings
Overwrites are per privacy mode (on/off) and not global. Overwrites have a 3 hour ttl, ttl gets checked on page load,

## Screenshots
<details>

![image](https://github.com/PreMiD/Presences/assets/73395916/7304a972-0d76-4cac-90de-ba0f00aff6b6)
![image](https://github.com/PreMiD/Presences/assets/73395916/ba14a101-1789-4192-b38d-8c509fb6f8e7)

</details>

2024-01-17 23:48 UTC, theusaf reviewed
Maybe move the code for this to a separate file to keep the main script less messy?

2024-01-17 23:54 UTC, veryCrunchy commented
> Maybe move the code for this to a separate file to keep the main script less messy?

Torture..

2024-01-18 00:06 UTC, veryCrunchy commented
I believe that should do it

2024-01-18 00:32 UTC, veryCrunchy commented
I think people are going to love it.
I already can't go without 😭

2024-01-18 08:49 UTC, Bas950 requested changes
Move it to a util/pvPrimary.ts or something like that

2024-01-18 19:55 UTC, joerkig commented
Would it also be possible to have an option to disable showing the button?

2024-01-18 21:43 UTC, veryCrunchy commented
@joerkig I can add a setting for that if you want me to?

2024-01-18 21:55 UTC, joerkig commented
> @joerkig I can add a setting for that if you want me to?

Would be nice, cause me personally I don't think I will use this that much and would be appreciated to not have extra clutter in that case

2024-01-18 22:08 UTC, veryCrunchy commented
Donesies

2024-01-19 18:28 UTC, Bas950 requested changes

2024-01-19 18:28 UTC, Bas950 commented on websites/Y/YouTube/util/pvPrivacyUI.ts
> +		return array.findIndex(entry => entry.videoId === videoId) !== -1;
```suggestion
		return array.some(entry => entry.videoId === videoId);
```

2024-01-19 18:28 UTC, Bas950 commented on websites/Y/YouTube/presence.ts
> +		}
probs and if-else is more readable here

2024-01-19 18:28 UTC, Bas950 commented on websites/Y/YouTube/util/pvPrivacyUI.ts
> +				) as HTMLElement,
```suggestion
			const svgEnabled = document.querySelector<HTMLElement>(
					"#pmdPrivacyEnabled"
				),
```

2024-01-19 18:28 UTC, Bas950 commented on websites/Y/YouTube/util/pvPrivacyUI.ts
> +				) as HTMLElement;
```suggestion
				svgDisabled = document.querySelector<HTMLElement>(
					"#pmdPrivacyDisabled"
				);
```

2024-01-19 19:28 UTC, theusaf commented
Can you also provide a screenshot of the [settings](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#reviewing)?

2024-01-19 19:30 UTC, veryCrunchy commented
<details><summary>Screenshots</summary>
<p>

![image](https://github.com/PreMiD/Presences/assets/73395916/b22aeb5a-88ef-4840-ba2f-457a86954fe2)
![image](https://github.com/PreMiD/Presences/assets/73395916/254c774f-ef2e-477e-bcde-8b276a277290)

</p>
</details>

2024-01-19 19:31 UTC, theusaf approved these changes

2024-01-19 19:45 UTC, Bas950 approved these changes

2024-01-19 19:45 UTC, merged