feat(WINDOWS93): add presence
PreMiD/Presences pull request #7999
Opened 2024-01-28 14:54 UTC by joerkig

## Description 

Resolves #7316 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![Discord_WhHdfu0JQW](https://github.com/PreMiD/Presences/assets/44418429/ccd0ac64-f4ac-436c-b953-354fa0e0cdaf)
![Discord_WoGJMj7x94](https://github.com/PreMiD/Presences/assets/44418429/dd096cef-7b26-4cf2-9a4d-81819de14451)
![Discord_weWSn7xdU6](https://github.com/PreMiD/Presences/assets/44418429/0cd3b4ad-bd5d-4d87-80d4-c40cc7e0f33e)
![Discord_ZYtLDJ1cxh](https://github.com/PreMiD/Presences/assets/44418429/79918234-d175-47c1-bc40-453e0fbde0db)
![NVIDIA_Share_CTtwA5VIyO](https://github.com/PreMiD/Presences/assets/44418429/3c2a5ca3-0085-44c9-a835-aba46f1529ba)
![Discord_j59A14js1y](https://github.com/PreMiD/Presences/assets/44418429/36a9ed78-93f4-46c3-8368-f23d5970b155)

</details>

2024-01-28 19:56 UTC, Bas950 approved these changes

2024-01-29 00:14 UTC, theusaf requested changes

2024-01-29 00:14 UTC, theusaf commented on websites/W/WINDOWS93/presence.ts
> +		}
This looks like an unnecessary `default` block

2024-01-29 00:14 UTC, theusaf commented on websites/W/WINDOWS93/iframe.ts
> +};
Perhaps these could use `addEventListener` instead of overwriting the global event listener methods just in case?

2024-01-30 02:18 UTC, theusaf approved these changes

2024-01-30 02:19 UTC, merged