feat(Soap2Day) added new Domain
PreMiD/Presences pull request #8018
Opened 2024-02-04 18:44 UTC by taynotfound

## Description 
I just added the domain
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

2024-02-04 21:52 UTC, theusaf requested changes
Make sure to resolve the automated checks.

2024-02-04 22:01 UTC, taynotfound commented
> Make sure to resolve the automated checks.

Done

2024-02-05 07:51 UTC, Bas950 approved these changes

2024-02-05 08:31 UTC, theusaf approved these changes

2024-02-05 08:31 UTC, merged

2024-03-13 07:39 UTC, wariacix commented
Please add soap2dayx.to if possible.