feat(Lazada): Added more domain & Imagekeys
PreMiD/Presences pull request #8059
Opened 2024-02-13 08:05 UTC by ZzzSleepyy

## Description 

Added more domain to support URL for other countries and Imagekeys.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

2024-02-15 06:48 UTC, theusaf requested changes
The url assets are the same, so they do not need to be changed

2024-02-15 06:48 UTC, theusaf commented on websites/L/Lazada/metadata.json
> +	"thumbnail": "https://www.most2414.com/wp-content/uploads/2020/02/02FEB-Insights-Lazada-Service-Marketplace-MOST2414-Cover.jpg",
These assets appear to be the same
```suggestion
	"logo": "https://cdn.rcd.gg/PreMiD/websites/L/Lazada/assets/logo.png",
	"thumbnail": "https://cdn.rcd.gg/PreMiD/websites/L/Lazada/assets/thumbnail.jpg",
```

2024-02-15 06:48 UTC, theusaf commented on websites/L/Lazada/metadata.json
>  	"version": "1.0.1",
Make sure to change the version

2024-02-15 06:48 UTC, theusaf commented on websites/L/Lazada/presence.ts
> +			largeImageKey: "https://i.ibb.co/LpxnMfj/512x512pngoflazada.png",
```suggestion
			largeImageKey: 
				"https://cdn.rcd.gg/PreMiD/websites/L/Lazada/assets/logo.png",
```

2024-02-15 06:48 UTC, theusaf commented on websites/L/Lazada/presence.ts
> +			"https://i.ibb.co/LpxnMfj/512x512pngoflazada.png";
```suggestion
			"https://cdn.rcd.gg/PreMiD/websites/L/Lazada/assets/logo.png";
```

2024-02-15 20:58 UTC, theusaf approved these changes

2024-02-17 08:59 UTC, Bas950 approved these changes

2024-02-17 08:59 UTC, merged