feat(BitView): add presence
PreMiD/Presences pull request #8062
Opened 2024-02-14 23:04 UTC by darkitxu84

## Description 

BitView is a small video repository website in the old YouTube style.

The presence works almost in the same way as the YouTube presence, with some details such as texts or showing the user's image when viewing their channel.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
![](https://github.com/PreMiD/Presences/assets/76633266/3b701098-085b-405f-94ba-b64d94e5a622)
![](https://github.com/PreMiD/Presences/assets/76633266/52540d2f-1e8b-47ea-a98c-0d6464f42a59)
![](https://github.com/PreMiD/Presences/assets/76633266/96d9febe-d0e8-40dc-b2a3-902c6fc730f1)
![](https://github.com/PreMiD/Presences/assets/76633266/a465ebee-edc8-4fdf-8c17-59bd10c97524)
![](https://github.com/PreMiD/Presences/assets/76633266/04693cdb-ec1a-4ac7-9185-35dec0315165)
![](https://github.com/PreMiD/Presences/assets/76633266/6c0ed8d0-a480-429d-877f-46ea8031f3a4)
![](https://github.com/PreMiD/Presences/assets/76633266/605813e8-be0b-4dcd-9b1d-d65f531de3ed)
![](https://github.com/PreMiD/Presences/assets/76633266/1ad73f24-03bd-4781-83ce-24eb52d222e6)
![](https://github.com/PreMiD/Presences/assets/76633266/cbdd240a-441a-4cd7-bb5b-4b037e585562)

2024-02-15 07:00 UTC, theusaf requested changes
Considering the similarity to YouTube, you might want to consider using the `type`  attribute in your `presenceData` as well.

```ts
{
  name: "BitView",
  type: ActivityType.Watching,
  largeImageKey: Assets.Logo,
}
```

2024-02-15 07:00 UTC, theusaf commented on websites/B/BitView/presence.ts
> +}
```suggestion
const enum Assets {
	Logo = "https://i.imgur.com/x7XnGcX.png",
}
```

2024-02-15 07:00 UTC, theusaf commented on websites/B/BitView/presence.ts
> +			name: "Bitview",
```suggestion
			name: "BitView",
```

2024-02-15 20:59 UTC, theusaf approved these changes

2024-02-17 09:00 UTC, Bas950 approved these changes

2024-02-17 09:00 UTC, merged