feat(AniCrush): add anicrush
PreMiD/Presences pull request #8071
Opened 2024-02-17 19:35 UTC by mallusrgreatv2

Closes #8063

## Description 
Add AniCrush website.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<img src="https://github.com/PreMiD/Presences/assets/69511006/5ed92eee-1042-4382-a0e1-4c712bce27a5">
</details>

2024-02-17 20:24 UTC, theusaf requested changes

2024-02-17 20:24 UTC, theusaf commented on websites/A/AniCrush/metadata.json
> +	"logo": "https://anicrush.to/images/favicon.png",
the logo should be 512x512px

2024-02-17 20:24 UTC, theusaf commented on websites/A/AniCrush/presence.ts
> +	Logo = "favicon",
Assets should be an image link, rather than a Discord asset name

2024-02-17 20:24 UTC, theusaf commented on websites/A/AniCrush/presence.ts
> +			const showTimestamps = await presence.getSetting<boolean>("timestamps");
For performance and conciseness, try fetching all the settings at the top of the function.

2024-02-17 20:24 UTC, theusaf commented on websites/A/AniCrush/metadata.json
> +	"iFrameRegExp": ".*",
Consider using a more specific iframe regex if possible.

2024-02-19 18:58 UTC, theusaf requested changes

2024-02-19 18:58 UTC, theusaf commented on websites/A/AniCrush/presence.ts
> +				if (await presence.getSetting<boolean>("timestamps")) {
```suggestion
				if (showTimestamps) {
```

2024-02-19 18:58 UTC, theusaf commented on websites/A/AniCrush/presence.ts
> +		showTimestamps = await presence.getSetting<boolean>("timestamps");
Use `Promise.all` to fetch all settings in parallel

2024-02-20 18:33 UTC, theusaf approved these changes

2024-02-20 19:01 UTC, Bas950 approved these changes

2024-02-20 19:01 UTC, merged