feat(ABEMA): add presence
PreMiD/Presences pull request #8091
Opened 2024-02-21 16:02 UTC by ryunt

## Description 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![abema_settings](https://github.com/PreMiD/Presences/assets/42194754/aca3de4c-e2ca-45e6-99d4-8d0c90d610ae)

![abema_profile_and_website](https://github.com/PreMiD/Presences/assets/42194754/21f4b92b-e3cf-4005-869b-b8a6f23c1810)

![abema_profile](https://github.com/PreMiD/Presences/assets/42194754/c7c86120-6b57-49fc-aea7-854f445b292e)
</details>

2024-02-21 17:58 UTC, theusaf requested changes

2024-02-21 17:58 UTC, theusaf commented on websites/A/ABEMA/metadata.json
> +	"logo": "https://i.imgur.com/8KLnjVb.png",
[Logo](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#logo) should be 512x512px

2024-02-21 17:58 UTC, theusaf commented on websites/A/ABEMA/metadata.json
> +		"atream",
Is this a typo?
```suggestion
		"stream",
```

2024-02-22 00:23 UTC, theusaf approved these changes

2024-02-22 07:51 UTC, Bas950 approved these changes

2024-02-22 07:51 UTC, merged