feat(Dash Radio): change dash radio to litt live, chore: update metadata to support matches
PreMiD/Presences pull request #8118
Opened 2024-02-25 17:13 UTC by bakzkndd

## Description 

Updated metadata to support matches for v3. Also updated the Dash Radio presence to LITT Live, because Dash Radio doesn't exist anymore and is now LITT Live. Also added a feature to it which gets the current radio logo if it can, otherwise it just uses the logo. This way it is clearer for other users which radio is being listened to without causing clutter.
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ ] I linted the code by running `yarn format` (didn't do this since it updated 1k+ metadata files, checked in the discord to see what i had to do and was told to just leave it be for now)
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/PreMiD/Presences/assets/50497725/4a460ed7-58d2-4eea-92f9-8c30a417a881)
![image](https://github.com/PreMiD/Presences/assets/50497725/289437b4-5401-4cae-9e95-1b6c8b3e693d)

</details>

2024-02-25 18:08 UTC, bakzkndd commented
I've run `yarn lint` instead of `yarn format`

2024-02-25 20:32 UTC, theusaf requested changes
Revert changes to TomsHardware and Tweakers, since they aren't relevant to this pr

2024-02-25 20:42 UTC, theusaf requested changes

2024-02-25 20:42 UTC, theusaf commented on websites/L/LITT Live/metadata.json
> +	"logo": "https://cdn.discordapp.com/app-assets/575756169986048004/1211339369386999808.png",
```suggestion
	"logo": "https://cdn.discordapp.com/app-assets/575756169986048004/1211339369386999808.png?size=512",
```

2024-02-25 20:42 UTC, theusaf commented on websites/L/LITT Live/metadata.json
> +	"thumbnail": "https://cdn.discordapp.com/app-assets/575756169986048004/1211339525565976606.png",
> The [thumbnail](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#thumbnail) should preferably be a [wide promotional card](https://i.imgur.com/3QfIc5v.jpg) or a [screenshot](https://i.imgur.com/OAcBmwW.png) if the first is not available.

2024-02-25 20:42 UTC, theusaf commented on websites/L/LITT Live/presence.ts
> +		thumbnail = document.querySelectorAll(".MuiPaper-elevation")[0].childNodes[1].childNodes[0].childNodes[0].childNodes[0] as HTMLImageElement;
* `querySelectorAll(...)[0]` can be simplified to `querySelector(...)`.
* Considering the multiple uses of the same selector, assign the element to a variable.

2024-02-25 20:42 UTC, theusaf commented on websites/L/LITT Live/presence.ts
> +			thumbnail ?? "logo",
```suggestion
			thumbnail ?? "https://cdn.discordapp.com/app-assets/575756169986048004/1211339369386999808.png?size=512",
```

2024-02-26 19:24 UTC, bakzkndd commented
> Make sure to resolve merge conflicts

I can't see the conflict, as in I can see thaat it says that the dash radio/metadata is a conflicting file, but I can't see why, or do anything about it seemingly.

2024-02-29 01:25 UTC, theusaf approved these changes

2024-02-29 07:51 UTC, Bas950 approved these changes

2024-03-02 15:52 UTC, theusaf approved these changes

2024-03-02 15:52 UTC, merged