Feature tabii presence
PreMiD/Presences pull request #8130
Opened 2024-02-27 15:24 UTC by gerigel

## Description 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

2024-02-29 01:21 UTC, theusaf requested changes

2024-02-29 01:21 UTC, theusaf commented on websites/T/Tabii/presence.ts
> +	play = "play",
```suggestion
	Logo = "https://i.imgur.com/ZfDhD5n.png",
```

2024-02-29 01:21 UTC, theusaf commented on websites/T/Tabii/presence.ts
> +				presenceData.smallImageKey = video.paused ? Assets.pause : Assets.play;
These assets are provided in `index.d.ts`
```suggestion
				presenceData.smallImageKey = video.paused ? Assets.Pause : Assets.Play;
```

2024-03-02 15:53 UTC, theusaf requested changes

2024-03-02 15:53 UTC, theusaf commented on websites/T/Tabii/presence.ts
> +			) as HTMLElement
Are you unable to find a smaller selector for this?
```suggestion
			document.querySelector<HTMLElement>(
				"#Main > div > div:nth-child(1) > main > div > div.flex.pt-8 > div > div > span:nth-child(2)"
			)
```

2024-03-03 12:10 UTC, Bas950 approved these changes

2024-03-04 22:51 UTC, theusaf approved these changes

2024-03-04 22:51 UTC, merged