Roo7 k1d fix 1.0.1
PreMiD/Presences pull request #8134
Opened 2024-02-28 09:42 UTC by Roo7K1d

## Description 
The presence didn't work when using the "Show Balance" option.
-> Fixed balance & currency parsing

## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![Screenshot1](https://img001.prntscr.com/file/img001/e08kAAPdSPq-G55B4d2HMA.png)

![Screenshot2](https://img001.prntscr.com/file/img001/g1BhHBYxSBmNDgakK2vcpg.png)

</details>

2024-02-28 19:46 UTC, theusaf requested changes

2024-02-28 19:46 UTC, theusaf commented on websites/S/Stake/metadata.json
>  	"url": "stake.com",
```suggestion
	"url": "stake.com",
	"matches": [
		"*://stake.com/*"
	],
```

2024-02-29 01:18 UTC, theusaf approved these changes

2024-02-29 07:50 UTC, Bas950 approved these changes

2024-02-29 07:50 UTC, merged