feat(Rate Your Music): add presence
PreMiD/Presences pull request #8148
Opened 2024-03-03 03:59 UTC by kitten99

## Description 
Presence for RYM (Rate Your Music)

*Doesn't include the film part of RYM or the forums

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>

![image](https://github.com/PreMiD/Presences/assets/141530947/6c3ed688-028f-45f8-8b5d-d97734b19c48)

![image](https://github.com/PreMiD/Presences/assets/141530947/f6a99e94-3846-408a-98c7-5b2f6aa35257)

![image](https://github.com/PreMiD/Presences/assets/141530947/229e94c2-b6e9-4cd2-b85b-eea4b25c386c)

![image](https://github.com/PreMiD/Presences/assets/141530947/8ff791f1-9e42-43ad-90da-8ee62fe0dfa4)

![image](https://github.com/PreMiD/Presences/assets/141530947/29afe477-82c1-47b1-adc5-8dd619e0a8e3)

![image](https://github.com/PreMiD/Presences/assets/141530947/3378841f-d4b3-4b7c-b56f-b2480beef22f)

![image](https://github.com/PreMiD/Presences/assets/141530947/e02c6ea7-341e-4f5b-928b-7070f5aba4ce)

![image](https://github.com/PreMiD/Presences/assets/141530947/17c26781-4d75-4c17-92d4-fd951ce4316b)

![image](https://github.com/PreMiD/Presences/assets/141530947/70d0611a-c3be-462a-a795-fdf41e27f974)

![image](https://github.com/PreMiD/Presences/assets/141530947/c4fac689-881c-4a48-8c5d-16f5ac335ed7)

![image](https://github.com/PreMiD/Presences/assets/141530947/8e35ebea-6cb1-4d27-853d-fad208a826aa)

![image](https://github.com/PreMiD/Presences/assets/141530947/fa16a173-25be-40c0-9511-16ec56c130be)

<summary> Proof showing the creation/modification is working as expected </summary>

</details>

2024-03-03 12:18 UTC, Bas950 approved these changes

2024-03-04 23:26 UTC, theusaf requested changes

2024-03-04 23:26 UTC, theusaf commented on websites/R/Rate Your Music/metadata.json
There are new fields called `matches` and `iFrameMatches`, which are required for new Presences.
These are an array of strings which need to follow https://developer.chrome.com/docs/extensions/develop/concepts/match-patterns.

2024-03-04 23:26 UTC, theusaf commented on websites/R/Rate Your Music/presence.ts
> +		presenceData.state = new URLSearchParams(window.location.search).get(
Use `document.location` properties rather than `window.location` for consistency with other presences

2024-03-04 23:26 UTC, theusaf commented on websites/R/Rate Your Music/presence.ts
> +	//chart page
These comments are mostly redundant and relatively easy to tell from the if statements

2024-03-04 23:26 UTC, theusaf commented on websites/R/Rate Your Music/presence.ts
> +	if (pathname.startsWith("/recs/to/") || pathname.startsWith("/recs/from/")) {
Consider using `else if` or `switch` rather than a bunch of `if`s for performance and better readabilty

2024-03-04 23:26 UTC, theusaf commented on websites/R/Rate Your Music/presence.ts
> +setInterval(updatePresence, 3000);
Lines 277-279 may cause performance issues while browsing this site for some time.
To resolve this, create a single instance at the top of the script, and/or use the provided `UpdateData` event listener to call your `updatePresences` method.

2024-03-08 19:06 UTC, theusaf requested changes

2024-03-08 19:06 UTC, theusaf commented on websites/R/Rate Your Music/presence.ts
> +document.addEventListener("UpdateData", updatePresence);
This still has the same problems. `new Presence` may cause performance problems over time when done multiple times.
```ts
const presence = new Presence(...);

presence.on("UpdateData", updatePresences);

function updatePresences() {
  // ...
  presence.setActivity(presenceData)
}
```

2024-03-12 19:48 UTC, theusaf approved these changes

2024-03-13 08:09 UTC, Bas950 approved these changes

2024-03-13 08:09 UTC, merged