feat(AnimeYuzu): change to new domain
PreMiD/Presences pull request #8149
Opened 2024-03-03 10:17 UTC by Faelayis

website move to new domain

## Description 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/PreMiD/Presences/assets/48393914/3133bb46-1253-4776-9638-427a0c815a6a)

</details>

2024-03-03 11:01 UTC, DarkVillager requested changes

2024-03-03 11:01 UTC, DarkVillager commented on websites/A/AnimeYuzu/presence.ts
> +			largeImageKey: "site",
no
```suggestion
			largeImageKey: "https://i.imgur.com/8PVGg8d.png",
```

2024-03-03 14:55 UTC, DarkVillager approved these changes
LGTM (im not an actual reviewer)

2024-03-04 23:27 UTC, theusaf requested changes

2024-03-04 23:27 UTC, theusaf commented on websites/A/AnimeYuzu/metadata.json
There are new fields called `matches` and `iFrameMatches`, which are required for new Presences.
These are an array of strings which need to follow https://developer.chrome.com/docs/extensions/develop/concepts/match-patterns.

2024-03-08 19:07 UTC, theusaf approved these changes

2024-03-09 14:50 UTC, Bas950 approved these changes

2024-03-09 14:50 UTC, merged