feat(movie-web): added more sites from official docs
PreMiD/Presences pull request #8191
Opened 2024-03-21 22:04 UTC by Pokeylooted

## Description 

Added sites from the official movie-web docs, and removed the old non working ones since the takedown.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

The screenshots will look literally exact same.
</details>

2024-03-23 23:19 UTC, theusaf requested changes

2024-03-23 23:19 UTC, theusaf commented on websites/M/movie-web/metadata.json
Please update the `matches` field as well.

2024-03-26 20:38 UTC, theusaf approved these changes

2024-03-26 21:28 UTC, Bas950 approved these changes

2024-03-26 21:28 UTC, merged