feat(Japanese Mahjong Wiki): add presence
PreMiD/Presences pull request #8197
Opened 2024-03-24 05:14 UTC by theusaf

## Description 

Adds a presence for the Japanese Mahjong Wiki (riichi.wiki)

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![2024-03-23 21_34_13](https://github.com/PreMiD/Presences/assets/32113157/8bad7969-0453-4927-9500-8bc8b5c320eb)
![2024-03-23 21_35_29](https://github.com/PreMiD/Presences/assets/32113157/f87498eb-b02a-4cd1-9cd1-f483520525e0)
![2024-03-23 21_16_04](https://github.com/PreMiD/Presences/assets/32113157/10e635a4-54a1-46c7-8e84-490e7ae46869)
![2024-03-23 21_24_58](https://github.com/PreMiD/Presences/assets/32113157/a11debba-607b-45ff-b2b1-f5a2dec777df)

</details>

2024-03-26 21:48 UTC, Bas950 requested changes

2024-03-26 21:48 UTC, Bas950 commented on websites/J/Japanese Mahjong Wiki/pages/special.ts
> +	SLIDESHOW_TIMEOUT = 6e3;
Please use full numbers, easier to read.

2024-03-26 21:56 UTC, Bas950 approved these changes

2024-03-29 20:28 UTC, Timeraa approved these changes

2024-03-29 20:28 UTC, merged