feat(Poke) : add presence
PreMiD/Presences pull request #8201
Opened 2024-03-25 16:38 UTC by ashley0143

## Description 
poke is a youtube front-end (like invidious) 
https://codeberg.org/ashley/poke/ 
https://github.com/ashley0143/poke/

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
![image](https://github.com/PreMiD/Presences/assets/65588168/f6819c5e-a275-4d8b-96dc-98d51b1a775a)
![image](https://github.com/PreMiD/Presences/assets/65588168/8097df10-4185-44c4-95a4-afff2cb15e25)

</details>

2024-03-25 22:08 UTC, theusaf requested changes

2024-03-25 22:08 UTC, theusaf commented on websites/P/poke/metadata.json
> +	"logo": "https://cdn.glitch.global/d68d17bb-f2c0-4bc3-993f-50902734f652/yt-ukraine.png",
[Logos](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#logo) must be 512x512px

2024-03-25 22:08 UTC, theusaf commented on websites/P/poke/metadata.json
> +	"version": "1.0.0",
There is a new field called `matches`, which is required for new Presences.
These are an array of strings which need to follow https://developer.chrome.com/docs/extensions/develop/concepts/match-patterns.

2024-03-25 22:08 UTC, theusaf commented on websites/P/poke/presence.ts
> +		smallImageKey: "more",
Use image URLs rather than Discord asset names

2024-03-25 22:08 UTC, theusaf commented on websites/P/poke/presence.ts
> +					: "pause";
```suggestion
					? Assets.Play
					: Assets.Pause;
```

2024-03-25 22:09 UTC, theusaf requested changes
Ensure that the folder capitalization matches the service name. `Poke`, not `poke`

2024-03-25 22:11 UTC, ashley0143 commented
alr im gonna fix those

2024-03-26 02:38 UTC, theusaf requested changes

2024-03-26 02:38 UTC, theusaf commented on websites/P/Poke/presence.ts
> +			"https://cdn.glitch.global/d68d17bb-f2c0-4bc3-993f-50902734f652/yt-ukraine.png?v=1703399674868",
```suggestion
			"https://poketube.fun/css/yt-ukraine-512.png",
```

2024-03-26 02:38 UTC, theusaf commented on websites/P/Poke/presence.ts
> +					: "pause";
```suggestion
					? Assets.Play
					: Assets.Pause;
```

2024-03-26 20:33 UTC, theusaf approved these changes

2024-03-26 21:29 UTC, Bas950 approved these changes

2024-03-26 21:29 UTC, merged