feat(RadiosNet): add presence
PreMiD/Presences pull request #8202
Opened 2024-03-25 21:17 UTC by ntn-ss

2024-03-25 22:21 UTC, theusaf requested changes

2024-03-25 22:21 UTC, theusaf commented on websites/R/RadiosNet/metadata.json
> +	"version": "1.0.0",
There is a new field called `matches`, which is required for new Presences.
These are an array of strings which need to follow https://developer.chrome.com/docs/extensions/develop/concepts/match-patterns.

2024-03-25 22:21 UTC, theusaf commented on websites/R/RadiosNet/presence.ts
> +            document.querySelector(".page-header")?.innerHTML;
This repository prefers `textContent` rather than `innerHTML` if possible

2024-03-25 22:21 UTC, theusaf commented on websites/R/RadiosNet/presence.ts
> +                .querySelector(".page-header")?.innerHTML.split("<small>")[1].split("</small>")[0];
Check if these can be simplified to a different query selector, or done using `textContent`

2024-03-25 22:21 UTC, theusaf commented on websites/R/RadiosNet/presence.ts
> +    else if (document.location.pathname.includes("/favoritos")) {
To make the code more consistent/concise, destructure `document.location` properties.
```ts
const { pathname, href, search } = document.location;
```

2024-03-25 22:21 UTC, theusaf commented on websites/R/RadiosNet/presence.ts
> +        document.location.href.includes("http://play.radios.com.br/")
This may not take into account cases where the site uses https

2024-03-25 22:21 UTC, theusaf commented on websites/R/RadiosNet/presence.ts
> +            document.querySelector(".img-rounded") as HTMLImageElement
Use generics rather than `as type`
```suggestion
            document.querySelector<HTMLImageElement>(".img-rounded")
```

2024-03-25 23:45 UTC, ntn-ss commented
Everything fixed, thank you for being so comprehensive, my code is way better now

2024-03-26 02:41 UTC, theusaf requested changes

2024-03-26 02:41 UTC, theusaf commented on websites/R/RadiosNet/metadata.json
> +	],
Based on the code and visiting the website, the following urls should also be added:
* `www.radios.com.br`
* `play.radios.com.br`

2024-03-26 13:51 UTC, ntn-ss commented
The latest commits were made to fix slogan's query inside `play.radios.com.br`: since I've fixed it using a single quote string, the bot rejected it, and I've faced some minor annoyances after that. Now it's all fine ~(sorry, I'm a big noob in all of this)~.

2024-03-26 20:26 UTC, theusaf approved these changes

2024-03-26 21:31 UTC, Bas950 approved these changes

2024-03-26 21:31 UTC, merged