feat(Anix): add Anix presence
PreMiD/Presences pull request #8206
Opened 2024-03-26 23:34 UTC by vahya

## Description 

Closes #7519 

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/PreMiD/Presences/assets/85792429/f1b36316-2d9b-4a2c-8efd-84158ec6d851)

![image](https://github.com/PreMiD/Presences/assets/85792429/3d097c93-b126-440a-9cbe-39bd3020e3ac)

</details>

2024-03-27 04:21 UTC, theusaf requested changes

2024-03-27 04:21 UTC, theusaf commented on websites/A/Anix/metadata.json
> +	"iFrameRegExp": ".*",
There are new fields called `matches` and `iFrameMatches`, which are required for new Presences.
These are an array of strings which need to follow https://developer.chrome.com/docs/extensions/develop/concepts/match-patterns.

2024-03-27 04:21 UTC, theusaf commented on websites/A/Anix/metadata.json
> +	"logo": "https://i.imgur.com/gtqJrml.png",
[Logos](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#logo) must be 512x512px

2024-03-27 04:21 UTC, theusaf commented on websites/A/Anix/metadata.json
> +	"iFrameRegExp": ".*",
If possible, change the `iFrameRegExp` to be more specific if you can determine all iframe hosts the website uses.

2024-03-27 04:21 UTC, theusaf commented on websites/A/Anix/metadata.json
> +	"settings": [
Please also add a [screenshot of the settings](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#reviewing) to your PR description

2024-03-27 04:21 UTC, theusaf commented on websites/A/Anix/presence.ts
> +	Logo = "logo",
Use an image URL rather than a Discord asset name.

2024-03-27 04:21 UTC, theusaf commented on websites/A/Anix/presence.ts
> +		[buttons] = await Promise.all([presence.getSetting<boolean>("buttons")]);
As you are only reading one setting, `Promise.all` is not needed.

2024-03-27 04:21 UTC, theusaf commented on websites/A/Anix/presence.ts
> +			break;
```suggestion
			}
			break;
```

2024-03-27 04:21 UTC, theusaf commented on websites/A/Anix/presence.ts
> +const enum Assets { // Other default assets can be found at index.d.ts
```suggestion
const enum Assets {
```

2024-04-05 16:38 UTC, theusaf approved these changes

2024-04-06 07:19 UTC, Bas950 approved these changes

2024-04-06 07:19 UTC, merged