feat(EWAIFU): add presence
PreMiD/Presences pull request #8245
Opened 2024-04-02 14:11 UTC by hallerdaniel

## Description 
Add presence

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
![Screenshot 2024-04-02 162637](https://github.com/PreMiD/Presences/assets/140011114/6203e971-6c02-492e-8074-5c471000b4f2)

![Screenshot 2024-04-02 161033](https://github.com/PreMiD/Presences/assets/140011114/170c98ef-69a2-4604-a19d-d208e9e1939f)

2024-04-03 19:00 UTC, theusaf requested changes

2024-04-03 19:00 UTC, theusaf commented on websites/E/EWAIFU/presence.ts
> +			buttons: [{ label: "Discover Ewaifus", url: "https://www.ewaifu.gg/" }],
Buttons redirecting to main pages are not allowed by the [guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#presencets)
```suggestion
```

2024-04-04 07:09 UTC, DarkVillager requested changes

2024-04-04 07:09 UTC, DarkVillager commented on websites/E/EWAIFU/presence.ts
> +	Home = "https://www.ewaifu.gg/img/home.png",
Assets must be 512x512

2024-04-04 08:51 UTC, hallerdaniel commented on websites/E/EWAIFU/presence.ts
> +	Home = "https://www.ewaifu.gg/img/home.png",
fixed

2024-04-05 16:42 UTC, theusaf approved these changes

2024-04-06 07:25 UTC, Bas950 approved these changes

2024-04-06 07:25 UTC, merged