fix(Daily Mail): sports article fix
PreMiD/Presences pull request #8251
Opened 2024-04-05 22:22 UTC by ION606

## Description 

Fixed an issue where articles under the `/sport` path weren't being recognized as articles.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/PreMiD/Presences/assets/58801387/0c46cbf3-7501-4d0a-a914-d3293e2242e4)

from https://www.dailymail.co.uk/sport/formulaone/article-13273503/Guenther-Steiner-Drive-Survive-Miami-Mercedes-Haas-Miami.html
</details>

2024-04-05 22:24 UTC, ION606 commented
I am praying to god I did this right because I can not rebase to save my life

2024-04-09 17:19 UTC, theusaf requested changes

2024-04-09 17:19 UTC, theusaf commented on package-lock.json
Ensure to revert changes to this file

2024-04-11 19:42 UTC, theusaf approved these changes

2024-04-12 16:34 UTC, Bas950 approved these changes

2024-04-12 16:34 UTC, merged