feat(Stake.us): add presence
PreMiD/Presences pull request #8288
Opened 2024-04-20 20:26 UTC by Kevin-Kwan

## Description 

Add PreMiD presence for the online social casino Stake.us (United States version of Stake.com, still owned by Stake). This displays browsing different parts of the sites, games currently being played, and current balance alongisde selected currency for play. It is different from the existing Stake.com presence as it uses different currencies, lacks sports betting, and has many slot games missing (most likely due to US regulation of online casinos?). Thus, this presence is mainly for US users of Stake.us.

## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://github.com/PreMiD/Presences/assets/51896555/a04f2d26-e55b-4ad5-95fd-2a0d3b5dc364.png">
<img src="https://github.com/PreMiD/Presences/assets/51896555/2b0d47f3-f205-40e9-943e-e49793804ba3.png">
<img src="https://github.com/PreMiD/Presences/assets/51896555/81e075c2-5f25-4c33-b950-c40094639572.png">
<img src="https://github.com/PreMiD/Presences/assets/51896555/f3384100-c444-4698-9d63-ea9b80eff2db">
<img src="https://github.com/PreMiD/Presences/assets/51896555/8f35b83d-fcc9-4770-9ab8-36b41c4a7f56.png">
</summary>
</details>

2024-04-20 20:52 UTC, Kevin-Kwan commented
Not quite sure why "Presence Validator / Presence Validator (pull_request)" is failing when it passed on my previous commits. I don't know if it's an issue with my code or with the check. Ran `npm run compileTools` and `node --enable-source-maps tools/auto/presenceValidator.js pull_request` locally and they worked. 

![image](https://github.com/PreMiD/Presences/assets/51896555/4d40723e-a664-4b80-8287-21f021c7d9aa)

2024-04-21 21:34 UTC, theusaf requested changes
Also, since you have settings, add a screenshot of the settings in the extension

2024-04-21 21:34 UTC, theusaf commented on websites/S/Stake.us/presence.ts
> +		{ pathname, search } = window.location;
For consistency across presences, use `document.location`
```suggestion
		{ pathname, search } = document.location;
```

2024-04-21 21:50 UTC, Kevin-Kwan commented
> Also, since you have settings, add a screenshot of the settings in the extension

Thanks, I included a screenshot of the settings as the first Screenshot.

2024-04-22 16:26 UTC, theusaf approved these changes

2024-04-24 04:59 UTC, Bas950 approved these changes

2024-04-24 04:59 UTC, merged