feat(CHZZK): add presence
PreMiD/Presences pull request #8302
Opened 2024-04-25 11:28 UTC by Slowlife01

## Description 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/PreMiD/Presences/assets/54318514/509ffd1c-1c9b-4c7d-884b-c6d91a860014)
![image](https://github.com/PreMiD/Presences/assets/54318514/ccefc689-e20c-451b-b377-bf438b663a60)
![image](https://github.com/PreMiD/Presences/assets/54318514/b407ca3b-35aa-4262-aaed-7fb0d9ec8ab9)

</details>

2024-04-25 19:13 UTC, theusaf requested changes

2024-04-25 19:13 UTC, theusaf commented on websites/C/CHZZK/presence.ts
> +	Pause = "https://cdn.discordapp.com/app-assets/1232944311415603281/1232952455101419540.png",
Assets should be 512x512px. You can also consider using the default assets.
```suggestion
	Browse = "https://cdn.discordapp.com/app-assets/1232944311415603281/1232952455562526731.png?size=512",
	Live = "https://cdn.discordapp.com/app-assets/1232944311415603281/1232952455369850910.png?size=512",
	Play = "https://cdn.discordapp.com/app-assets/1232944311415603281/1232952455625707581.png?size=512",
	Pause = "https://cdn.discordapp.com/app-assets/1232944311415603281/1232952455101419540.png?size=512",
```

2024-04-25 19:13 UTC, theusaf commented on websites/C/CHZZK/presence.ts
> +					if (location.pathname.startsWith("/live")) {
```suggestion
					if (document.location.pathname.startsWith("/live")) {
```

2024-04-25 19:13 UTC, theusaf commented on websites/C/CHZZK/presence.ts
> +							{ url: location.href, label: strings.watchStream },
```suggestion
							{ url: document.location.href, label: strings.watchStream },
```

2024-04-25 19:13 UTC, theusaf commented on websites/C/CHZZK/presence.ts
> +							{ url: location.href, label: strings.watchVideo },
```suggestion
							{ url: document.location.href, label: strings.watchVideo },
```

2024-04-26 04:34 UTC, theusaf requested changes

2024-04-26 04:34 UTC, theusaf commented on websites/C/CHZZK/presence.ts
> +		showElapsedTime = await presence.getSetting<boolean>("time");
For improved performance, use `Promise.all`

2024-04-26 17:15 UTC, Timeraa approved these changes

2024-04-26 19:43 UTC, theusaf approved these changes

2024-04-26 19:43 UTC, merged