feat(Naver): rewrite Presence
PreMiD/Presences pull request #8303
Opened 2024-04-25 11:59 UTC by Slowlife01

## Description 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/PreMiD/Presences/assets/54318514/2c06174c-f2d2-46bb-85f2-734ee77f3fd3)
![image](https://github.com/PreMiD/Presences/assets/54318514/320a6132-0f2f-4155-881c-128871cf9581)
![image](https://github.com/PreMiD/Presences/assets/54318514/e91a4ace-e1fa-4fbd-ba96-731f8c658455)

</details>

2024-04-25 12:27 UTC, Slowlife01 commented on websites/N/Naver/presence.ts
Not sure if this would actually work..

2024-04-25 12:28 UTC, Slowlife01 commented on websites/N/Naver/presence.ts
> +	if (location.hostname.includes("chzzk")) return;
Not sure if this would actually work..

2024-04-25 19:18 UTC, theusaf requested changes

2024-04-25 19:18 UTC, theusaf commented on websites/N/Naver/presence.ts
> +			"https://cdn.discordapp.com/app-assets/827171204288872449/827173061572296804.png",
```suggestion
			"https://cdn.discordapp.com/app-assets/827171204288872449/827173061572296804.png?size=512",
```

2024-04-25 19:18 UTC, theusaf commented on websites/N/Naver/presence.ts
> +}
Assets should be 512x512px
```suggestion
const enum MainAssets {
	Browse = "https://cdn.discordapp.com/app-assets/825307070584586250/826435062756278273.png?size=512",
	Book = "https://cdn.discordapp.com/app-assets/825307070584586250/826447462554140704.png?size=512",
	Play = "https://cdn.discordapp.com/app-assets/827170810870890517/827172409979305995.png?size=512",
	Pause = "https://cdn.discordapp.com/app-assets/827170810870890517/827172409936314378.png?size=512",
	Language = "https://cdn.discordapp.com/app-assets/827170714729578546/827172528383590460.png?size=512",
}
```

2024-04-25 19:18 UTC, theusaf commented on websites/N/Naver/presence.ts
> +							url: location.href,
For consistency with other presences, use `document.location` properties.
```ts
const { pathname, href } = document.location;
{ url: href, label: "..." }
```

2024-04-26 04:37 UTC, theusaf approved these changes

2024-04-26 17:14 UTC, Timeraa approved these changes

2024-04-26 17:14 UTC, merged