chore(Videoland): rewrite presence & fix null & undefined issues
PreMiD/Presences pull request #8321
Opened 2024-04-28 14:28 UTC by DarkVillager

## Description 

- Fix issues
- Rewrite presence
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://github.com/PreMiD/Presences/assets/42322979/a754c074-a30f-4787-a1f4-56eb235e1745">
<img src="https://github.com/PreMiD/Presences/assets/42322979/961bd10b-99e6-4ee0-abaa-5b9a54f074fe">

</details>

2024-04-28 19:24 UTC, theusaf requested changes

2024-04-28 19:24 UTC, theusaf commented on websites/V/Videoland/presence.ts
> +			  )
Could `textContent` be used instead?

2024-04-30 17:52 UTC, DarkVillager commented on websites/V/Videoland/presence.ts
> +			  )
No because its the innerhtml

2024-05-01 11:44 UTC, DarkVillager commented on websites/V/Videoland/presence.ts
> +			  )
Nvm it can be used.

2024-05-01 22:02 UTC, theusaf approved these changes

2024-05-02 03:25 UTC, Bas950 commented on websites/V/Videoland/presence.ts
> +				.split("op videoland")[0]
Split on the same thing twice?

2024-05-02 06:04 UTC, DarkVillager commented on websites/V/Videoland/presence.ts
> +				.split("op videoland")[0]
> Split on the same thing twice?
on / op

2024-05-02 09:01 UTC, merged