feat(Writers Duet): adding presence
PreMiD/Presences pull request #8322
Opened 2024-04-28 16:54 UTC by ION606

## Description 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>

![image](https://github.com/PreMiD/Presences/assets/58801387/0b3805c7-04f4-418d-ad1c-3c1565facf0b)
<summary> Proof showing the creation/modification is working as expected
</summary>

</details>

2024-04-28 16:56 UTC, ION606 commented
from https://github.com/PreMiD/Presences/issues/7798

2024-04-28 19:27 UTC, theusaf requested changes
It's a bit low-quality. Consider adding other parts of the page (blog, etc) to the presence.

2024-04-28 19:27 UTC, theusaf commented on websites/W/WriterDuet/metadata.json
> +	"url": "writerduet.com",
```suggestion
	"url": "www.writerduet.com",
```

2024-04-28 19:28 UTC, ION606 commented
> It's a bit low-quality. Consider adding other parts of the page (blog, etc) to the presence.

I just added what the issue asked for

2024-04-29 01:46 UTC, Bas950 commented
Please add support for other pages

2024-04-29 17:27 UTC, theusaf approved these changes

2024-04-29 23:25 UTC, Bas950 approved these changes

2024-04-29 23:25 UTC, merged