fix(Invidious): adding privacy mode
PreMiD/Presences pull request #8323
Opened 2024-04-28 17:32 UTC by ION606

## Description 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>

![image](https://github.com/PreMiD/Presences/assets/58801387/a1561747-2a97-4d34-8070-8bdc66536cb0)

![image](https://github.com/PreMiD/Presences/assets/58801387/61bdbdc8-441b-468a-b6a5-cbe24c1d4d15)

![image](https://github.com/PreMiD/Presences/assets/58801387/cea04aeb-32e2-4c87-9400-925c60066b54)

<summary> Proof showing the creation/modification is working as expected </summary>

</details>

Reference Issue: https://github.com/PreMiD/Presences/issues/8248

2024-04-28 19:29 UTC, theusaf requested changes

2024-04-28 19:29 UTC, theusaf commented on websites/I/Invidious/presence.ts
`querySelectorAll(...)[0]` can be simplified to `.querySelector(...)`

2024-04-28 23:49 UTC, ION606 commented on websites/I/Invidious/presence.ts
I didn't add that code, I just pushed a fix

2024-04-28 23:50 UTC, ION606 commented on websites/I/Invidious/presence.ts
I'll fix it anyways

2024-04-29 17:08 UTC, theusaf approved these changes

2024-04-29 23:26 UTC, Bas950 approved these changes

2024-04-29 23:26 UTC, merged