fix(Youtube Music): timestamps
PreMiD/Presences pull request #8324
Opened 2024-04-28 18:48 UTC by ION606

## Description 

* Changed all `ActivityType.Listening` to `ActivityType.Playing` so the timestamps are actually displayed
* Added the "Use Time Left" setting that allows a user to switch between displaying the time left and displaying the time elapsed

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>

![image](https://github.com/PreMiD/Presences/assets/58801387/19974c40-4d16-4c27-a07f-2c3dcd16d252)

![image](https://github.com/PreMiD/Presences/assets/58801387/02532c9c-4c39-4d72-99b7-a1b00da3a808)

![image](https://github.com/PreMiD/Presences/assets/58801387/cce0c91d-8c4f-4ec9-9197-341e5092d500)

<summary> Proof showing the creation/modification is working as expected </summary>

</details>

Referenced Issue: https://github.com/PreMiD/Presences/issues/8262

2024-04-28 19:28 UTC, veryCrunchy requested changes

2024-04-28 19:28 UTC, veryCrunchy commented on websites/Y/YouTube Music/presence.ts
> +			presenceData.type = ActivityType.Playing;
```suggestion
			presenceData.type = ActivityType.Listening;
```
We have a global setting to use playing status over of any other.
Please keep the listening type.

2024-04-28 19:28 UTC, veryCrunchy commented on websites/Y/YouTube Music/presence.ts
> +			presenceData.type = ActivityType.Playing;
```suggestion
			presenceData.type = ActivityType.Listening;
```

2024-04-28 19:28 UTC, veryCrunchy commented on websites/Y/YouTube Music/presence.ts
> +	presenceData.type = ActivityType.Playing;
```suggestion
	presenceData.type = ActivityType.Listening;
```

2024-04-28 19:37 UTC, theusaf requested changes

2024-04-28 19:37 UTC, theusaf commented on websites/Y/YouTube Music/presence.ts
> +			usetimeleft,
To better align with JS conventions, change variable to `useTimeLeft`

2024-04-28 19:56 UTC, veryCrunchy approved these changes

2024-04-28 23:32 UTC, theusaf approved these changes

2024-04-29 01:40 UTC, Bas950 approved these changes

2024-04-29 01:40 UTC, merged