fix(Replit): rewrite presence to fix issues
PreMiD/Presences pull request #8347
Opened 2024-05-02 11:33 UTC by DarkVillager

## Description 

Resolves #8218 
rewrite presence to fix issues
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://github.com/PreMiD/Presences/assets/42322979/ad75034e-76a2-4a80-b9a5-411ea5389c99">
<img src="https://github.com/PreMiD/Presences/assets/42322979/715158f6-a73c-4b9a-84d9-f1eb5761de68">
<img src="https://github.com/PreMiD/Presences/assets/42322979/0eba1eef-07fc-4091-99ff-79ebd868696f">

</details>

2024-05-02 17:55 UTC, theusaf requested changes

2024-05-02 17:55 UTC, theusaf commented on websites/R/Replit/presence.ts
> +			largeImageKey: "https://i.imgur.com/rKlupJp.png",
It may make sense to combine this with the other Assets.

2024-05-02 17:55 UTC, theusaf commented on websites/R/Replit/presence.ts
> +				presenceData.buttons = [{ label: "View Replit", url: href }];
I think the more accurate term is "REPL". "Replit" is the website which contains "REPLs"

2024-05-05 19:00 UTC, theusaf approved these changes

2024-05-06 14:13 UTC, Bas950 approved these changes

2024-05-06 14:13 UTC, merged