feat(Sorryfield): Corresponding to Sorryfield 1.11.0 update
PreMiD/Presences pull request #8353
Opened 2024-05-05 07:22 UTC by IAMIHAH

## Description 

## Acknowledgements
- [ ] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ ] I linted the code by running `yarn format`
- [ ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/PreMiD/Presences/assets/64065435/f9bcbc58-dbd7-4bd2-8e1e-ed1982dc2ad3)
![image](https://github.com/PreMiD/Presences/assets/64065435/6ae8ec4f-6685-4d0d-be61-c78bf4360d47)

</details>

2024-05-05 18:59 UTC, theusaf requested changes

2024-05-05 18:59 UTC, theusaf commented on websites/S/Sorryfield/presence.ts
> +	ChartSpotlighted = "https://i.imgur.com/jfS5s7A.png",
Assets should ideally be a square

2024-05-06 22:48 UTC, theusaf requested changes

2024-05-06 22:48 UTC, theusaf commented on websites/S/Sorryfield/presence.ts
> +	ChartSpotlighted = "https://i.imgur.com/GrClrlG.png",
Assets should be 512x512px

2024-05-07 21:03 UTC, theusaf approved these changes

2024-05-08 00:05 UTC, Bas950 approved these changes

2024-05-08 00:05 UTC, merged