fix(youtube): channel name and viewed content
PreMiD/Presences pull request #8362
Opened 2024-05-08 18:13 UTC by DMCroww

## Description 
Came across instance where channel name and selected tabs were not showing up in Presence (`undefined` and `null` respectively)

Line 330: Adjusted an `if` statement that was causing channel name to be reported as `null` when an element on page was not found (`String.includes('')` is always true)

Line 349: Changed querystring to properly find selected tab of viewed content (Featured, Videos, ...) as it was returning `undefined`

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![Screenshot 2024-05-08 19-58-46](https://github.com/PreMiD/Presences/assets/43938522/8b862f30-03a8-4394-885d-abb5312d30aa)

![Screenshot 2024-05-08 19-59-39](https://github.com/PreMiD/Presences/assets/43938522/4e0fd292-a2ac-4099-bee6-3054daba75fa)

</details>

2024-05-09 10:34 UTC, DarkVillager requested changes

2024-05-09 10:34 UTC, DarkVillager commented on websites/Y/YouTube/presence.ts
> +						"" &&
[Empty string are false.](https://stackoverflow.com/a/8693015/17773757)
```suggestion
					!document.querySelector("#text.ytd-channel-name")?.textContent &&
```

2024-05-11 04:56 UTC, theusaf approved these changes

2024-05-11 05:42 UTC, Bas950 approved these changes

2024-05-11 05:42 UTC, merged