Threads
PreMiD/Presences pull request #8363
Opened 2024-05-08 19:10 UTC by down-bad

## Description 

Add Threads presence

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img src="https://i.imgur.com/7B84orS.png" />
<img src="https://i.imgur.com/bfOJOEy.png" />
<img src="https://i.imgur.com/bC5JaJo.png" />

</details>

2024-05-09 10:32 UTC, DarkVillager requested changes

2024-05-09 10:32 UTC, DarkVillager commented on websites/T/Threads/metadata.json
> +	"logo": "https://i.imgur.com/qR37ayt.png",
Logo's must be 512x512 as per [our guideliness](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#logo).

2024-05-09 10:32 UTC, DarkVillager commented on websites/T/Threads/presence.ts
> +			largeImageKey: "https://i.imgur.com/qR37ayt.png",
Logo's must be 512x512 as per [our guideliness](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#logo).

2024-05-09 10:32 UTC, DarkVillager commented on websites/T/Threads/presence.ts
> +	let details: string, state: string;
no.
just use 
```ts
presenceData.state 
presenceData.details
```

2024-05-09 10:32 UTC, DarkVillager commented on websites/T/Threads/presence.ts
> +			).src;
```suggestion
			presenceData.smallImageKey = 
				document.querySelector<HTMLImageElement>(
					`img[alt*="${state.split("@")[1]}"]`
				).src;
```

2024-05-11 04:53 UTC, theusaf approved these changes

2024-05-11 05:41 UTC, Bas950 approved these changes

2024-05-11 05:41 UTC, merged