feat(multiplayerpiano.net): add presence
PreMiD/Presences pull request #8375
Opened 2024-05-15 14:33 UTC by AntoKek

## Description 
Added a presence for [multiplayerpiano.net](multiplayerpiano.net), a website used for playing piano in custom lobbies with other people. \
There are settings for both showing the name of the room and for showing a button that allows other users to join the room.\
The presence keeps track of the user's status on the website in order to determine whether they're active or AFK.

## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

### Description and settings: 
![](https://cdn.discordapp.com/attachments/587336926533648409/1240290676609126400/image.png?ex=66460634&is=6644b4b4&hm=4393ef5a3003bd4f4b42d28d20b82ff7118db45e62007a1f165a118f3f6a601e&)

### Not AFK, Both settings enabled:
![](https://cdn.discordapp.com/attachments/587336926533648409/1240280544705773611/image.png?ex=6645fcc5&is=6644ab45&hm=cadb911657ec15f4bbd76bbe55676b9bdd73ae76df30fa130a9593e55fcf9931&)

### AFK, Both settings enabled:
![](https://cdn.discordapp.com/attachments/587336926533648409/1240281895783239700/image.png?ex=6645fe07&is=6644ac87&hm=c4f6d12ce57b40b8e35ef98a0f72220240fdd853d6ffa982a32fd736223e25ed&)

### Not AFK, Both settings disabled:
![](https://cdn.discordapp.com/attachments/587336926533648409/1240286964591235094/image.png?ex=664602bf&is=6644b13f&hm=db356f34ab384d59307352598947426816fb3d2cbe4871f3fd354d23dd2336b8&)

### AFK, Both settings disabled
![](https://cdn.discordapp.com/attachments/587336926533648409/1240288203836227707/image.png?ex=664603e7&is=6644b267&hm=71fb98d5cd333714e8e6703db8df181bd04d1bcb861fb36f46739842b0f41d86&)

</details>

2024-05-15 20:35 UTC, theusaf requested changes
Make sure to resolve automated checks

2024-05-15 20:35 UTC, theusaf commented on .github/PULL_REQUEST_TEMPLATE.MD
Ensure to revert changes to this file

2024-05-15 20:35 UTC, theusaf commented on websites/M/MultiplayerPiano.net/metadata.json
> +	"logo": "https://cdn.discordapp.com/icons/813217128529264710/911b06d8a1a9af24fac16b843165cc0f.png",
The [logo](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#logo) should be a 512x512px image

2024-05-15 20:35 UTC, theusaf commented on websites/M/MultiplayerPiano.net/presence.ts
> +	Logo = "logo",
Use image links over Discord asset names

2024-05-15 20:35 UTC, theusaf commented on websites/M/MultiplayerPiano.net/presence.ts
> +	const url = window.location.href;
Use `document.location` instead of `window.location`

2024-05-19 20:50 UTC, DarkVillager requested changes

2024-05-19 20:50 UTC, DarkVillager commented on .github/PULL_REQUEST_TEMPLATE.MD
> +</details>
huh

2024-05-19 20:50 UTC, DarkVillager commented on websites/M/MultiplayerPiano.net/metadata.json
> +		"en": "An online website used for playing piano with friends. It supports input from both MIDI keyboards and QWERTY keyboards."
Official description.
```suggestion
		"en": "An online piano you can play alone or with others in real-time. MIDI support, 88 keys, velocity sensitive. You can show off your skill or chat while listening to others play."
```

2024-05-19 20:50 UTC, DarkVillager commented on websites/M/MultiplayerPiano.net/presence.ts
> +				url: `https://multiplayerpiano.net/?c=${getRoomName()}`,
```suggestion
				url: href,
```

2024-05-19 20:50 UTC, DarkVillager commented on websites/M/MultiplayerPiano.net/presence.ts
> +presence.on("UpdateData", async () => {
```suggestion
presence.on("UpdateData", async () => {
cons {href} = document.location;
```

2024-05-21 02:24 UTC, theusaf requested changes

2024-05-21 02:24 UTC, theusaf commented on websites/M/MultiplayerPiano.net/presence.ts
> +	Logo = "https://cdn.discordapp.com/attachments/587336926533648409/1240591699034767380/mpp2.png?ex=66471e8e&is=6645cd0e&hm=b288e175fe293d96c41c4041773d370a231a52a4cdd818eaa88342731a6762f9&",
These Discord links are temporary and may not work. The link in the metadata should be fine.
```suggestion
	Logo = "https://www.virtualdrumming.com/icons-piano/icons-512.png",
```

2024-05-22 16:52 UTC, DarkVillager requested changes

2024-05-22 16:52 UTC, DarkVillager commented on websites/M/MultiplayerPiano.net/presence.ts
> +const enum Assets { // Other default assets can be found at index.d.ts
```suggestion
const enum Assets {
```

2024-05-23 17:45 UTC, theusaf requested changes
Make sure to resolve the lint check

2024-05-29 22:18 UTC, theusaf approved these changes

2024-05-30 06:47 UTC, Bas950 requested changes

2024-05-30 06:47 UTC, Bas950 commented on websites/M/MultiplayerPiano.net/metadata.json
> +	"service": "MultiplayerPiano.net",
```suggestion
	"service": "Multiplayer Piano",
```
Same with folder name.

2024-06-04 18:22 UTC, theusaf commented
Closing for inactivity. You may open a new PR after resolving the issues mentioned in this one.

2024-06-04 18:22 UTC, closed without merging