fix(Codewars): show states aside from browsing
PreMiD/Presences pull request #8382
Opened 2024-05-18 22:32 UTC by nitrogem35

## Description 

- Fixed a major issue that prevented anything besides "Browsing..." from being displayed in the description
- Added a small feature that shows the difficulty of the kata being searched for

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/PreMiD/Presences/assets/69062894/7d102463-96c4-40ca-9e88-ce33c9b9a7c8)
![image](https://github.com/PreMiD/Presences/assets/69062894/6074af89-05de-4148-97e5-95dc8700750f)

</details>

2024-05-19 20:37 UTC, DarkVillager approved these changes
LGTM

2024-05-20 09:19 UTC, Bas950 submitted a review, later dismissed

2024-05-21 02:11 UTC, theusaf requested changes

2024-05-21 02:11 UTC, theusaf commented on websites/C/Codewars/presence.ts
> +						)[0] as HTMLInputElement
```suggestion
						document.querySelector<HTMLInputElement>(
							'[Label="Difficulty"]'
						)
```

2024-05-21 02:11 UTC, theusaf commented on websites/C/Codewars/presence.ts
> +						document.querySelectorAll(".w-full>div>div>div>span")[0].textContent
```suggestion
						document.querySelector(".w-full>div>div>div>span").textContent
```

2024-05-22 22:34 UTC, theusaf approved these changes

2024-05-23 06:47 UTC, Bas950 approved these changes

2024-05-23 06:47 UTC, merged