Increment version
PreMiD/Presences pull request #8386
Opened 2024-05-19 14:40 UTC by mx-mic

Increased version number from 1.0.6 to 1.0.7 as this is a minor change that doesn't affect the functionality of the presence
Changed URL to `chatgpt.com` following ChatGPTs new domain from `chat.openai.com`

2024-05-19 20:34 UTC, DarkVillager commented
@mx-mic show proof the presence still works.

2024-05-20 09:17 UTC, Bas950 requested changes
Upload proof of the presence working after this change.

2024-05-27 18:32 UTC, theusaf commented
<details>

![image](https://github.com/PreMiD/Presences/assets/32113157/46bc3231-320e-4a06-9509-b8611a1c9652)
![image](https://github.com/PreMiD/Presences/assets/32113157/d370fb42-80a0-48f1-b3d8-5fad29003baf)

</details>

2024-05-27 18:32 UTC, theusaf approved these changes

2024-05-27 19:19 UTC, Bas950 approved these changes

2024-05-27 19:19 UTC, merged