fix(Songsterr): fix search tab not showing and make details title-case
PreMiD/Presences pull request #8392
Opened 2024-05-20 18:51 UTC by AlperShal

## Description 
Presence was not working as expected in the previous version as "#sticky-list-header" is no more a thing. Also, since complementary role is also available when doing a search, the condition was blocking details to change accordingly for search. Rewritten the problematic part. Also made details title-case as it is more consistent and aesthetic.

## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/PreMiD/Presences/assets/34231577/b7cc09b5-1c78-4caa-af02-cd4fb15e0a17)

![image](https://github.com/PreMiD/Presences/assets/34231577/26aa2595-10b4-461f-8636-865ded856ae3)

</details>

2024-05-21 02:08 UTC, theusaf requested changes

2024-05-21 02:08 UTC, theusaf commented on websites/S/Songsterr/presence.ts
> +				))?.value
Preferably use generic types for `querySelector` rather than casts. If possible, use non-computer generated selectors.

2024-05-27 18:33 UTC, theusaf approved these changes

2024-05-27 19:20 UTC, Bas950 approved these changes

2024-05-27 19:20 UTC, merged