feat(Masuru): add presence
PreMiD/Presences pull request #8394
Opened 2024-05-21 05:06 UTC by aomkoyo

## Description 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
![image](https://github.com/PreMiD/Presences/assets/59776731/6b35c69b-48e2-4719-a1c1-11d6d553cc54)
![image](https://github.com/PreMiD/Presences/assets/59776731/ebd020a3-627b-42a7-af53-a9a58d41489d)
![image](https://github.com/PreMiD/Presences/assets/59776731/625d28c4-31e9-4c7d-9d47-ec52e6cc18ac)
![image](https://github.com/PreMiD/Presences/assets/59776731/6247a98c-ae73-4b91-b962-298d9a4abc0e)
![image](https://github.com/PreMiD/Presences/assets/59776731/e5e02942-e487-4fd2-a0d9-a3ce6d87c152)

</details>

2024-05-21 05:06 UTC, aomkoyo commented
![image](https://github.com/PreMiD/Presences/assets/59776731/07ac5979-d88a-4c20-9296-27224d03d3ab)
![image](https://github.com/PreMiD/Presences/assets/59776731/589a46dd-6454-48ad-a9b6-c54dde1217bf)
![image](https://github.com/PreMiD/Presences/assets/59776731/26ca213b-7da5-4063-8f25-4df9f91c8a23)
![image](https://github.com/PreMiD/Presences/assets/59776731/394864b0-5879-43ad-bd3b-a5d43c0717d3)
![image](https://github.com/PreMiD/Presences/assets/59776731/79d6b934-647d-48ef-84a1-904a3c5489d6)

2024-05-22 22:38 UTC, theusaf requested changes

2024-05-22 22:38 UTC, theusaf commented on websites/M/Masuru/metadata.json
> +	"logo": "https://cdn.masuru.in.th/assets/masuru/apple-touch-icon.webp",
Logos should be 512x512px

2024-05-22 22:38 UTC, theusaf commented on websites/M/Masuru/presence.ts
> +}
Use image urls instead of discord asset names

2024-05-22 22:38 UTC, theusaf commented on websites/M/Masuru/presence.ts
> +					]);
Separate these assignments with semicolons rather than commas

2024-05-23 17:43 UTC, theusaf requested changes

2024-05-23 17:43 UTC, theusaf commented on websites/M/Masuru/presence.ts
> +										label: "Discovery Page",
Button label should be a verb.
- View Discovery
- View Discovery Page
- Discover
- etc.

2024-05-23 17:43 UTC, theusaf commented on websites/M/Masuru/presence.ts
> +				];
This button is generic and may redirect to the home page, which is not allowed according to current guidelines.
```suggestion
```

2024-05-23 18:08 UTC, tag27 commented
Why is the name of the presence Lilia and not the name of the website (Masaru)?

2024-05-24 15:26 UTC, theusaf approved these changes

2024-05-24 16:17 UTC, Bas950 approved these changes

2024-05-24 16:17 UTC, merged