feat(Hoppscotch): add presence
PreMiD/Presences pull request #8411
Opened 2024-05-24 10:14 UTC by itsmeeudrino

## Description 

This PR adds the [Hoppscotch](https://hoppscotch.io/) presence service, including:

1. REST APIs (Homepage)
2. GraphQL
3. Realtime: Websocket, SSE, SocketIO, MQTT
4. Settings

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/PreMiD/Presences/assets/142719764/d7d80097-05d8-4b1f-a7a1-1b6011df9555)
![image](https://github.com/PreMiD/Presences/assets/142719764/fe7ee6bc-d9fa-42e1-be0f-c0b39c77e480)
![image](https://github.com/PreMiD/Presences/assets/142719764/297dfeef-d6a7-4e4f-9f69-a0bf44a8b288)
![image](https://github.com/PreMiD/Presences/assets/142719764/dab5b8be-10e5-478c-a3f6-54a2474aed3b)

</details>

2024-05-24 10:26 UTC, itsmeeudrino commented
I might've went a little overboard with the code structure in this one, please feel free to suggest any changes!

2024-05-24 15:23 UTC, theusaf requested changes

2024-05-24 15:23 UTC, theusaf commented on websites/H/Hoppscotch/lib/realtime.ts
> +	const input = document.querySelector("input[type=url]") as HTMLInputElement;
```suggestion
	const input = document.querySelector<HTMLInputElement>("input[type=url]")
```

2024-05-24 15:23 UTC, theusaf commented on websites/H/Hoppscotch/lib/workspace.ts
> +	// eslint-disable-next-line no-one-time-vars/no-one-time-vars
Avoid disabling eslint rules unless it breaks how the code works. These rules are there to ensure code consistency across the project.

2024-05-24 15:23 UTC, theusaf commented on websites/H/Hoppscotch/metadata.json
> +	"thumbnail": "https://hoppscotch.io/icon.png",
> The [thumbnail](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#thumbnail) should preferably be a [wide promotional card](https://i.imgur.com/3QfIc5v.jpg) or a [screenshot](https://i.imgur.com/OAcBmwW.png) if the first is not available.

2024-05-24 15:23 UTC, theusaf commented on websites/H/Hoppscotch/presence.ts
> +	Settings = "https://i.imgur.com/UxuTIv7.png",
[Assets](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#presencets) should be 512x512px

2024-05-24 15:23 UTC, theusaf commented on websites/H/Hoppscotch/routes/graphql.ts
> +	const input = document.querySelector("input#url") as HTMLInputElement;
```suggestion
	const input = document.querySelector<HTMLInputElement>("input#url");
```

2024-05-24 18:25 UTC, itsmeeudrino reviewed
Thanks for taking the time to look at my PR!

2024-05-25 00:06 UTC, theusaf approved these changes

2024-05-25 08:30 UTC, Bas950 approved these changes

2024-05-25 08:30 UTC, merged