feat(Voirdrama): add presence
PreMiD/Presences pull request #8436
Opened 2024-05-30 08:34 UTC by zvbt

## Description 

This site is a plain copy of the already existing Voiranime presence.
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/PreMiD/Presences/assets/61088560/b31b830c-743c-486f-8e26-72bd629cce4b)

</details>

2024-05-31 16:54 UTC, theusaf requested changes

2024-05-31 16:54 UTC, theusaf commented on websites/V/Voirdrama/metadata.json
> +		"en": "Voiranime is a streaming website where you can watch Asian drama."
This description seems to describe the wrong service. Try using an official description from the service itself

2024-06-03 05:33 UTC, theusaf approved these changes

2024-06-03 05:42 UTC, Bas950 approved these changes

2024-06-03 05:42 UTC, merged