feat(LiveATC): add presence
PreMiD/Presences pull request #8484
Opened 2024-06-09 12:30 UTC by joerkig

## Description 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![Discord_9tRFFcmAsn](https://github.com/PreMiD/Presences/assets/44418429/9cdaffa5-6f21-4b88-8777-91a705b0eceb)
![Discord_HQGlW6a5YK](https://github.com/PreMiD/Presences/assets/44418429/fc3f2e53-5f2b-43fa-b93f-66e98ad318ba)
![Discord_UIIkDcz7md](https://github.com/PreMiD/Presences/assets/44418429/d83d27d7-d6f6-4301-9b69-d89b34a0f853)
![Discord_56lU6uoJRj](https://github.com/PreMiD/Presences/assets/44418429/d8a10055-5f5c-4737-a2f8-13fa53dc76c8)

</details>

2024-06-10 06:30 UTC, Bas950 approved these changes

2024-06-10 06:31 UTC, Bas950 requested changes

2024-06-10 06:31 UTC, Bas950 commented on websites/L/LiveATC/presence.ts
> +					params.get("icao");
You don't do anything with these params...

2024-06-10 09:11 UTC, Bas950 approved these changes

2024-06-14 02:01 UTC, theusaf approved these changes

2024-06-14 02:01 UTC, merged