fix(iheartradio): fixed song and station presence/data
PreMiD/Presences pull request #8494
Opened 2024-06-14 03:03 UTC by iiTxicz

## Description 

## Acknowledgements
- [✅ ] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ ] I linted the code by running `yarn format`
- [ ✅] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

https://cdn.rrc.bz/static/jackasu/2024-06-13+20-45-09.mp4
https://cdn.rrc.bz/static/jackasu/proof0.PNG
https://cdn.rrc.bz/static/jackasu/proof1.PNG

</details>

2024-06-14 08:25 UTC, Bas950 requested changes
Fix the errors from compile lint etc.

2024-06-14 17:39 UTC, iiTxicz commented
everything should be good to go, had a quick question. Is it possible to get added a contributor? Fixed a good amount of bugs and added some new features to the presence.

2024-06-14 17:41 UTC, iiTxicz commented
Also, had another question for another presence I'm trying to fix, do you guys accept wildcard domains? I'm trying to revise the edgenuity presence but i'm not able to do *.core.learn.edgenuity.com cause its not part of the regex, and since I'm not for sure how many domains are ending in r*, it'll be a pain to try and find all when i believe there are 20+ regions. Ex. r03.core.learn.edgenuity.com

2024-06-15 09:39 UTC, DarkVillager commented
> Also, had another question for another presence I'm trying to fix, do you guys accept wildcard domains? I'm trying to revise the edgenuity presence but i'm not able to do `*`.core.learn.edgenuity.com cause its not part of the regex, and I don't know how many subdomains are ending in r`*`, think there are around 20+ regions. Ex. r03.core.learn.edgenuity.com

uhhh just add it to regex?

2024-06-15 09:41 UTC, DarkVillager commented
> everything should be good to go, had a quick question. Is it possible to get added as a contributor to the iHeartRadio presence? Fixed a good amount of bugs and added some new features to the presence.

Imo yes.

2024-06-15 09:44 UTC, DarkVillager requested changes

2024-06-15 09:44 UTC, DarkVillager commented on websites/I/iHeartRadio/presence.ts
> +					? `${srcImage}`
```suggestion
					? srcImage
```

2024-06-15 09:44 UTC, DarkVillager commented on websites/I/iHeartRadio/presence.ts
> +						? `${srcImage}`
```suggestion
						? srcImage
```

2024-06-15 19:16 UTC, iiTxicz commented
Everything should be good to go now, feel free to let me know if anything else is needed. If not, feel free to merge whenever, appreciate it.

2024-06-17 04:41 UTC, theusaf requested changes

2024-06-17 04:41 UTC, theusaf commented on websites/I/iHeartRadio/presence.ts
> +							url: document.URL,
Use `document.location.href` instead of `document.URL`

2024-06-17 04:41 UTC, theusaf commented on websites/I/iHeartRadio/presence.ts
> +					: null;
Use `if` statements rather than ternaries for better readability.

2024-06-17 04:41 UTC, theusaf commented on websites/I/iHeartRadio/presence.ts
> +								  })
combine this with the `if` statement.

2024-06-17 04:41 UTC, theusaf commented on websites/I/iHeartRadio/presence.ts
> +				]);
Separate all assignment like these with `;` rather than `,`

2024-06-17 21:16 UTC, iiTxicz commented
Everything should be good to go now

2024-06-21 08:57 UTC, Bas950 approved these changes

2024-06-21 09:13 UTC, DarkVillager approved these changes

2024-06-21 12:09 UTC, Timeraa approved these changes

2024-06-21 12:13 UTC, merged