add(awtwa.site): added support for awtwa.site
PreMiD/Presences pull request #8499
Opened 2024-06-15 13:55 UTC by emberantz

## Description 
Hello, I added support for french anime streaming website AWTWA.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<img width="285" alt="image" src="https://github.com/PreMiD/Presences/assets/128653732/885ebff9-4604-4f9c-a9a1-27cbd201e09e">
<img width="266" alt="image" src="https://github.com/PreMiD/Presences/assets/128653732/d704e03c-6949-4710-9b9c-d32c977169f8">
<img width="266" alt="image" src="https://github.com/PreMiD/Presences/assets/128653732/1104a2f9-3e15-4887-81d5-402af080b4bb">
<img width="263" alt="image" src="https://github.com/PreMiD/Presences/assets/128653732/c5162402-02ab-4e59-ad41-03254623ad5e">
</details>

2024-06-16 13:23 UTC, DarkVillager requested changes

2024-06-16 13:23 UTC, DarkVillager commented on websites/A/AWTWA/metadata.json
> +	"logo": "https://i.imgur.com/AoJisOX.png",
Logo's must be 512x512 as per [our guideliness](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#logo).

2024-06-17 04:34 UTC, theusaf requested changes

2024-06-17 18:06 UTC, emberantz commented on websites/A/AWTWA/presence.ts
> +				(document.querySelector("#episode") as HTMLSelectElement).value
fixed.

2024-06-19 10:39 UTC, DarkVillager requested changes

2024-06-19 10:39 UTC, DarkVillager commented on websites/A/AWTWA/presence.ts
> +		presenceData.largeImageKey = Assets.Logo;
```suggestion
```

2024-06-19 10:39 UTC, DarkVillager commented on websites/A/AWTWA/presence.ts
> +	const presenceData: PresenceData = {},
```suggestion
	const presenceData: PresenceData = {
	largeImageKey: Assets.Logo
	},
```

2024-06-19 10:39 UTC, DarkVillager commented on websites/A/AWTWA/presence.ts
> +		presenceData.largeImageKey = Assets.Logo;
```suggestion
```

2024-06-19 10:39 UTC, DarkVillager commented on websites/A/AWTWA/presence.ts
> +			presenceData.largeImageKey = Assets.Logo;
```suggestion
```

2024-06-19 10:39 UTC, DarkVillager commented on websites/A/AWTWA/presence.ts
> +			presenceData.largeImageKey = poster;
```suggestion
			presenceData.largeImageKey = poster ?? Assets.Logo;
```

2024-06-19 10:42 UTC, DarkVillager requested changes

2024-06-19 10:42 UTC, DarkVillager commented on websites/A/AWTWA/presence.ts
> +const animeBrowsingTimestamp = Math.floor(Date.now() / 1000),
```suggestion
const browsingTimestamp = Math.floor(Date.now() / 1000),
```

2024-06-19 10:42 UTC, DarkVillager commented on websites/A/AWTWA/presence.ts
> +		presenceData.startTimestamp = animeBrowsingTimestamp;
```suggestion
		presenceData.startTimestamp = browsingTimestamp;
```

2024-06-19 10:42 UTC, DarkVillager commented on websites/A/AWTWA/presence.ts
> +			}
```suggestion
			if (!iFrameData?.paused) {
				[, presenceData.endTimestamp] = presence.getTimestamps(
					iFrameData.currentTime,
					iFrameData.duration
				);
				}
				presenceData.smallImageKey = iFrameData?.paused ? Assets.Pause : Assets.Play;
				presenceData.smallImageText = iFrameData?.paused ? "En pause" : "En train de regarder";
```

2024-06-19 10:43 UTC, DarkVillager commented
If you have any questions about any of the requested changes feel free to ask in the discord server or in my dms on discord.

2024-06-20 10:20 UTC, DarkVillager requested changes
Must match discord name other than that LGTM

2024-06-20 10:20 UTC, DarkVillager commented on websites/A/AWTWA/metadata.json
> +		"name": "ember"
```suggestion
		"name": "emberantz"
```

2024-06-21 08:59 UTC, Bas950 approved these changes

2024-06-21 09:13 UTC, DarkVillager approved these changes

2024-06-21 12:10 UTC, Timeraa approved these changes

2024-06-21 12:13 UTC, merged