feat(League of Angels: Pact): add presence
PreMiD/Presences pull request #8516
Opened 2024-06-20 19:19 UTC by CH40S734D3R

## Description 

League of Angels: Pact is the latest action-idle MMORPG in the League of Angels series. Participate in fierce battles, awaken hundreds of Angels and empower them and finally, defend the Holy Land of Justice with their help!
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![Screenshot 2024-06-21 191523](https://github.com/PreMiD/Presences/assets/90152861/eb29f7ef-f1b0-4f38-ba1a-0584a299fd5e)

![Screenshot 2024-06-21 191554](https://github.com/PreMiD/Presences/assets/90152861/9c51277d-4c2a-422d-a32c-fa0ebfa7a202)
</details>

2024-06-21 09:15 UTC, Bas950 requested changes
Maybe instead of setting the activity in every if case, set it once at the end of all if cases.

2024-06-21 09:15 UTC, Bas950 commented on websites/L/LOAP/metadata.json
> +	},
This should be a description of what LOAP is, not the Presence.
If possible, get an official description of a website

2024-06-21 09:15 UTC, Bas950 commented on websites/L/LOAP/metadata.json
> +	"logo": "https://r2.arkhanths.com/logo.jpg",
Logo must be 512x512

2024-06-21 09:15 UTC, Bas950 commented on websites/L/LOAP/presence.ts
> +			largeImageKey: "https://r2.arkhanths.com/logo.jpg",
Ditto for largeImagekey

2024-06-21 09:15 UTC, Bas950 commented on websites/L/LOAP/presence.ts
> +			window.location.origin + window.location.pathname + window.location.search
```suggestion
			document.location.href
```

2024-06-21 12:12 UTC, Bas950 requested changes
Maybe add `League of Angels: Pact` as an alt name (`"altnames": ["League of Angels: Pact"],`) so users can search for this in the store too. Or just rename the whole presence to it.

2024-06-21 12:12 UTC, Bas950 commented on websites/L/LOAP/metadata.json
> +	],
Maybe add some more tags, like `mmorpg`, etc.

2024-06-22 10:44 UTC, Bas950 approved these changes

2024-06-22 10:54 UTC, Timeraa approved these changes

2024-06-22 10:54 UTC, merged