Wolvesville Presence updated
PreMiD/Presences pull request #8562
Opened 2024-07-13 18:55 UTC by BlackWither17

## Description 

## Acknowledgements
- [ ✅ ] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ ✅ ] I linted the code by running `yarn format`
- [ ✅ ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
![image](https://github.com/user-attachments/assets/36089630-b049-4f61-889f-b5ba54327aef)
![image](https://github.com/user-attachments/assets/37500f04-cef4-4589-8be1-e7f421dda284)
![image](https://github.com/user-attachments/assets/8f6aad31-3a60-4cce-aae6-118113315704)
![image](https://github.com/user-attachments/assets/7796e9b0-4afe-423a-9263-41dbdaf60970)
![image](https://github.com/user-attachments/assets/0c6dad49-7951-48f6-a73b-e18f7debb6bb)

<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

2024-07-14 13:10 UTC, theusaf requested changes

2024-07-14 13:10 UTC, theusaf commented on websites/W/Wolvesville/presence.ts
> +	Voting = "https://imgur.com/Nt9hAOP.png",
Assets must be 512x512px

2024-07-14 13:10 UTC, theusaf commented on websites/W/Wolvesville/presence.ts
> +						url: document.URL,
```suggestion
						label: "Read Documentation",
						url: document.location.href,
```

2024-07-19 14:00 UTC, theusaf commented
Looks like the recent push just erased all changes previously made in this PR

2024-07-19 19:33 UTC, merged

2024-07-19 19:49 UTC, BlackWither17 commented
> Looks like the recent push just erased all changes previously made in this PR

Should I create a new merge request?