chore(PaparaTopluluk): update logo url
PreMiD/Presences pull request #8572
Opened 2024-07-16 14:07 UTC by eggsy

## Description 
They updated the logo.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

2024-07-16 18:08 UTC, theusaf requested changes
Additionally, ensure to resolve the automated checks

2024-07-16 18:08 UTC, theusaf commented on websites/P/Papara Topluluk/metadata.json
> +	"logo": "https://i.imgur.com/3L9gPyD.png",
Image should be 512x512px

2024-07-19 11:41 UTC, DarkVillager requested changes

2024-07-19 11:41 UTC, DarkVillager commented on websites/P/Papara Topluluk/metadata.json
>  	"version": "1.0.7",
```suggestion
	"version": "1.0.8",
```

2024-07-19 15:44 UTC, DarkVillager approved these changes
LGTM Boss

2024-07-19 19:34 UTC, theusaf approved these changes

2024-07-20 10:34 UTC, Bas950 approved these changes

2024-07-20 10:34 UTC, merged