Submission of salad.com presence
PreMiD/Presences pull request #8573
Opened 2024-07-16 19:43 UTC by daglaroglou

## Description 

## Acknowledgements
- [ ] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ ] I linted the code by running `yarn format`
- [ ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

2024-07-19 11:40 UTC, DarkVillager requested changes
Just some changes. If you have questions feel free to ask on discord in the presence-dev channel or in my dms: @dark_ville

2024-07-19 11:40 UTC, DarkVillager commented on websites/S/Salad/metadata.json
> +	"$schema": "https://schemas.premid.app/metadata/1.9",
```suggestion
	"$schema": "https://schemas.premid.app/metadata/1.10",
```

2024-07-19 11:40 UTC, DarkVillager commented on websites/S/Salad/presence.ts
> +	const privacy = await presence.getSetting<boolean>("privacy");
```suggestion
	},
	privacy = await presence.getSetting<boolean>("privacy"),
	{ hostname, pathname } = document.location;
```

2024-07-19 11:40 UTC, DarkVillager commented on websites/S/Salad/presence.ts
> +		presenceData.state = "Balance: " + document.querySelector(".c0116").textContent;
```suggestion
		presenceData.state = `Balance: ${document.querySelector(".c0116").textContent}`
```

2024-07-19 11:40 UTC, DarkVillager commented on websites/S/Salad/presence.ts
> +	}
```suggestion
	}
```

2024-07-19 11:40 UTC, DarkVillager commented on websites/S/Salad/presence.ts
> +	presence.setActivity(presenceData);
```suggestion
if (privacy && presenceData.state) delete presenceData.state
	presence.setActivity(presenceData);
```

2024-07-19 11:40 UTC, DarkVillager commented on websites/S/Salad/presence.ts
> +	if (document.location.pathname.includes("/earn/summary")) {
Simplify it, do this for all mentions of this.
```suggestion
	if (pathname.includes("/earn/summary")) {
```

2024-07-19 11:40 UTC, DarkVillager commented on websites/S/Salad/presence.ts
> +	else if (document.location.hostname.startsWith("community")) {
```suggestion
	else if (hostname.startsWith("community")) {
```

2024-07-19 11:41 UTC, DarkVillager commented
Also change the title to: feat(Salad): add presence

2024-07-19 14:08 UTC, theusaf requested changes

2024-07-19 14:08 UTC, theusaf commented on websites/S/Salad/metadata.json
> +	"logo": "https://blog.salad.com/wp-content/uploads/2023/08/Salad-Logo.png",
Logo should be 512x512px

2024-07-19 14:08 UTC, theusaf commented on websites/S/Salad/presence.ts
> +		presenceData.state = "Searching for " + (document.documentURI.split("?q=")[1]).split("&")[0].trim();
Use `document.location.href` instead of `documentURI`

2024-07-20 14:42 UTC, daglaroglou commented
can you change that please? ill be away from home for some days...

2024-07-22 13:20 UTC, daglaroglou commented
updated stuff

2024-07-22 17:32 UTC, DarkVillager requested changes
I love your attempt, but the code is too low quality. But since you put in effort, i'll suggest this change, that will make the presence high enough quality for the store.

If you have any questions, dm me on discord (@Dark_Ville) 

Changes include:
* Logo should be 512x512
* State & Details can only start with a capital (just like a normal sentence)
* Remove duplicate code
* Sort ifs to be more readable
* [Destructure variables ](https://dmitripavlutin.com/javascript-object-destructuring/)
* Change document.title to selectors so we don't have to split
* Implement privacy in a way so you have logical structure

2024-07-22 17:32 UTC, DarkVillager commented on websites/S/Salad/presence.ts
> +});
```suggestion
const presence = new Presence({
		clientId: "911546577485725706",
	}),
	browsingTimestamp = Math.floor(Date.now() / 1000);

const enum Assets {
	Logo = "https://i.imgur.com/Lc9wcdl.gif",
}

presence.on("UpdateData", async () => {
	const presenceData: PresenceData = {
			largeImageKey: Assets.Logo,
			startTimestamp: browsingTimestamp,
		},
		privacy = await presence.getSetting<boolean>("privacy"),
		{ hostname, pathname } = document.location;

	if (hostname.startsWith("support")) {
		if (pathname.includes("troubleshooting"))
			presenceData.state = "Troubleshooting";
		else if (pathname.includes("app-guides")) presenceData.state = "App guides";
		else if (pathname.includes("faq")) presenceData.state = "The faq";
		else if (pathname.includes("company")) presenceData.state = "Company";
		else if (pathname.includes("article")) {
			presenceData.details = privacy
				? "Support - reading an article"
				: "Support - Reading article";
			presenceData.state = document.querySelector(".title")?.textContent;
			presenceData.smallImageKey = Assets.Reading;
		} else if (pathname.includes("category")) {
			presenceData.details = privacy
				? "Support - viewing an article category"
				: "Support - viewing article category";
			presenceData.state = document.querySelector(".title")?.textContent;
			presenceData.smallImageKey = Assets.Search;
		} else presenceData.state = "Home";

		if (!presenceData.details)
			presenceData.details = privacy
				? "Support - viewing"
				: "Support - browsing";
	} else if (hostname.startsWith("community")) {
		if (pathname.includes("-")) {
			presenceData.details = privacy
				? "Community - reading a blog post"
				: "Community - reading about";
			presenceData.state = document.querySelector(".xpro-post-title");
			presenceData.smallImageKey = Assets.Reading;
		} else {
			presenceData.details = "Community - Browsing...";
			presenceData.smallImageKey = Assets.Search;
		}
	} else if (pathname.includes("/earn/summary")) {
		presenceData.details = privacy
			? "Viewing their summary"
			: "Summary - earnings";
		presenceData.state = `Balance: ${
			document.querySelector(".c0116")?.textContent
		}`;
	} else if (pathname.includes("/account/")) {
		presenceData.details = privacy
			? "Viewing their account settings"
			: "Account - viewing";
		if (pathname.endsWith("/summary"))
			presenceData.state = "Account management";
		else if (pathname.endsWith("/referrals")) presenceData.state = "Referrals";
		else if (pathname.endsWith("/bonuses")) presenceData.state = "Bonuses";
	} else if (pathname.includes("/rewards/")) {
		presenceData.details = privacy
			? "Store - viewing all items"
			: "Store - Viewing";
		presenceData.state = document?.title?.split("|")?.[0];
		presenceData.smallImageKey = Assets.Viewing;
	} else if (pathname.endsWith("/store")) {
		presenceData.details = "Store - browsing";
		presenceData.smallImageKey = Assets.Search;
	} else if (pathname.includes("/search")) {
		presenceData.details = privacy
			? "Store - searching for something"
			: "Store - searching for";
		presenceData.state = `Searching for ${
			document.querySelector<HTMLInputElement>('[placeholder="SEARCH"]')?.value
		}`;
		presenceData.smallImageKey = Assets.Search;
	} else if (pathname.endsWith("/download"))
		presenceData.details = "Viewing the download page";
	else if (pathname.endsWith("/vault"))
		presenceData.details = "Vault - viewing their vault";

	if (privacy && presenceData.state) delete presenceData.state;
	presence.setActivity(presenceData);
});

```

2024-07-22 21:57 UTC, DarkVillager approved these changes
I forgot to remove this and fix that, other than that LGTM

2024-07-22 21:57 UTC, DarkVillager commented on websites/S/Salad/presence.ts
> +				: "Support - browsing";
```suggestion
		if (!presenceData.details) {
			presenceData.details = privacy
				? "Support - viewing"
				: "Support - browsing";
			}
```

2024-07-22 21:57 UTC, DarkVillager commented on websites/S/Salad/presence.ts
> +
```suggestion
```

2024-07-23 09:20 UTC, DarkVillager requested changes
format

2024-07-23 09:20 UTC, DarkVillager commented on websites/S/Salad/presence.ts
> +});
```suggestion
const presence = new Presence({
		clientId: "911546577485725706",
	}),
	browsingTimestamp = Math.floor(Date.now() / 1000);

const enum Assets {
	Logo = "https://i.imgur.com/Lc9wcdl.gif",
}

presence.on("UpdateData", async () => {
	const presenceData: PresenceData = {
			largeImageKey: Assets.Logo,
			startTimestamp: browsingTimestamp,
		},
		privacy = await presence.getSetting<boolean>("privacy"),
		{ hostname, pathname } = document.location;

	if (hostname.startsWith("support")) {
		if (pathname.includes("troubleshooting"))
			presenceData.state = "Troubleshooting";
		else if (pathname.includes("app-guides")) presenceData.state = "App guides";
		else if (pathname.includes("faq")) presenceData.state = "The faq";
		else if (pathname.includes("company")) presenceData.state = "Company";
		else if (pathname.includes("article")) {
			presenceData.details = privacy
				? "Support - reading an article"
				: "Support - Reading article";
			presenceData.state = document.querySelector(".title")?.textContent;
			presenceData.smallImageKey = Assets.Reading;
		} else if (pathname.includes("category")) {
			presenceData.details = privacy
				? "Support - viewing an article category"
				: "Support - viewing article category";
			presenceData.state = document.querySelector(".title")?.textContent;
			presenceData.smallImageKey = Assets.Search;
		} else presenceData.state = "Home";

		if (!presenceData.details) {
			presenceData.details = privacy
				? "Support - viewing"
				: "Support - browsing";
		}
	} else if (hostname.startsWith("community")) {
		if (pathname.includes("-")) {
			presenceData.details = privacy
				? "Community - reading a blog post"
				: "Community - reading about";
			presenceData.state =
				document.querySelector(".xpro-post-title")?.textContent;
			presenceData.smallImageKey = Assets.Reading;
		} else {
			presenceData.details = "Community - Browsing...";
			presenceData.smallImageKey = Assets.Search;
		}
	} else if (pathname.includes("/earn/summary")) {
		presenceData.details = privacy
			? "Viewing their summary"
			: "Summary - earnings";
		presenceData.state = `Balance: ${
			document.querySelector(".c0116")?.textContent
		}`;
	} else if (pathname.includes("/account/")) {
		presenceData.details = privacy
			? "Viewing their account settings"
			: "Account - viewing";
		if (pathname.endsWith("/summary"))
			presenceData.state = "Account management";
		else if (pathname.endsWith("/referrals")) presenceData.state = "Referrals";
		else if (pathname.endsWith("/bonuses")) presenceData.state = "Bonuses";
	} else if (pathname.includes("/rewards/")) {
		presenceData.details = privacy
			? "Store - viewing all items"
			: "Store - Viewing";
		presenceData.state = document?.title?.split("|")?.[0];
		presenceData.smallImageKey = Assets.Viewing;
	} else if (pathname.endsWith("/store")) {
		presenceData.details = "Store - browsing";
		presenceData.smallImageKey = Assets.Search;
	} else if (pathname.includes("/search")) {
		presenceData.details = privacy
			? "Store - searching for something"
			: "Store - searching for";
		presenceData.state = `Searching for ${
			document.querySelector<HTMLInputElement>('[placeholder="SEARCH"]')?.value
		}`;
		presenceData.smallImageKey = Assets.Search;
	} else if (pathname.endsWith("/download"))
		presenceData.details = "Viewing the download page";
	else if (pathname.endsWith("/vault"))
		presenceData.details = "Vault - viewing their vault";

	if (privacy && presenceData.state) delete presenceData.state;
	presence.setActivity(presenceData);
});
```

2024-07-23 13:55 UTC, DarkVillager approved these changes
LGTM

2024-07-23 20:48 UTC, theusaf approved these changes

2024-07-24 17:11 UTC, Bas950 approved these changes

2024-07-24 17:11 UTC, merged