feat(AnimeUnity): add new presence
PreMiD/Presences pull request #8587
Opened 2024-07-21 19:43 UTC by Hikki0710

## Description 

Add animeUnity, an Italian website for watching anime

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/user-attachments/assets/ea205ea6-9d1d-4dbd-8822-e2e3302b8b6e)
![image](https://github.com/user-attachments/assets/70a11b58-4df4-4a1d-8c7c-e8f510acca67)
![image](https://github.com/user-attachments/assets/eac7af43-9531-4c9b-8bdb-7e7f67d15b34)
![image](https://github.com/user-attachments/assets/ef5ce48a-9285-4da1-b08e-ef70929ae494)
![image](https://github.com/user-attachments/assets/2fa710c8-8b26-4e35-9a48-32bbf3e102da)
![image](https://github.com/user-attachments/assets/a4cf396e-53a2-49ae-95ff-703eccdb7318)
![image](https://github.com/user-attachments/assets/867b5523-0256-4b91-8943-5eb7317bf221)

</details>

2024-07-21 19:57 UTC, Bas950 requested changes

2024-07-21 19:57 UTC, Bas950 commented on websites/A/AnimeUnity/presence.ts
> +				document.querySelector(".nav-link.active").innerHTML
Please don't use innerHTML, try using .textContent

2024-07-22 12:11 UTC, DarkVillager requested changes
Hi, thanks for the PR.

I have some suggested changes.

If you have any questions feel free to ask in #presence-dev or in dms (@dark_ville) on discord.

2024-07-22 17:06 UTC, DarkVillager approved these changes
LGTM :"D

2024-07-23 19:05 UTC, Bas950 approved these changes

2024-07-23 19:05 UTC, merged