feat(9anime): add presence
PreMiD/Presences pull request #8592
Opened 2024-07-22 10:15 UTC by julianxchang

## Description 
This is a presence for the 9anime website. It will display which page the user is currently viewing and the name of the anime the user is

## Acknowledgements
- [Yes] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [Yes] I linted the code by running `yarn format`
- [Yes] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![home](https://github.com/user-attachments/assets/4642f052-0516-458b-9443-a501d5bc1d81)
![result](https://github.com/user-attachments/assets/1aa43947-2b73-44a7-bb4b-a62b385bd2bd)
![watching](https://github.com/user-attachments/assets/ab8af3c0-9bc6-44da-8493-1b516db2d9d4)
 watching.

</details>

2024-07-22 10:20 UTC, julianxchang commented
Hi, this is the first version of the app so I'm not too sure why it's telling me to bump the version.

2024-07-22 12:04 UTC, DarkVillager requested changes

2024-07-22 12:04 UTC, DarkVillager commented on websites/I/iBroadcast/metadata.json
> +		}
Undo these changes.

2024-07-22 12:04 UTC, DarkVillager commented on package-lock.json
Same here, undo these changes.

2024-07-22 12:11 UTC, DarkVillager commented
Also change the title: feat(9anime): add presence

2024-07-22 12:14 UTC, DarkVillager requested changes
[DarkVillager](https://github.com/DarkVillager) left a comment
Hi, thanks for the PR.

I have some suggested changes.

If you have any questions feel free to ask in #presence-dev or in dms (@dark_ville) on discord.

2024-07-22 12:14 UTC, DarkVillager commented on websites/0-9/9anime/presence.ts
> +				?.getAttribute("src"),
This could give you an incomplete URL and its already has the type HTMLImageElement so ?.src exists.
```suggestion
				?.src
```

2024-07-22 12:14 UTC, DarkVillager commented on websites/0-9/9anime/presence.ts
> +		presenceData.largeImageKey = coverArt;
```suggestion
		presenceData.largeImageKey = coverArt ?? Assets.Logo;
```

2024-07-22 12:14 UTC, DarkVillager commented on websites/0-9/9anime/presence.ts
> +		presenceData.smallImageKey = Assets.Logo;
Just a check so you don't set its a smallimage when the largeimage is already the logo.
```suggestion
		presenceData.smallImageKey = !!coverArt ? Assets.Logo : "";
```

2024-07-22 12:15 UTC, DarkVillager commented
Resolves #8024

2024-07-22 20:45 UTC, julianxchang commented
I'm not too sure what Dark_Vile means by undo the changes I didn't make any changes to the iBroadCast presence. Also, it still seems like I'm failing the version bump test.

2024-07-22 20:55 UTC, theusaf commented
> I'm not too sure what Dark_Vile means by undo the changes I didn't make any changes to the iBroadCast presence. Also, it still seems like I'm failing the version bump test.

It is likely that earlier, you ran the format script and installed dependencies, which caused it to modify the package lockfile and format presences unrelated to this PR. To resolve all issues, ensure changes to those files are reverted.

The current CI check failure is related to your presence's code style. The previous version check has been resolved.

2024-07-22 20:57 UTC, julianxchang commented
I see thank you I will look into that right now

2024-07-22 21:00 UTC, julianxchang commented
Is there an easy way to revert the changes I made to package-lock.json rather than just replace line by line

2024-07-22 21:04 UTC, theusaf commented
> Is there an easy way to revert the changes I made to package-lock.json rather than just replace line by line

Git should have some useful commands for this. Look into `git restore`, `git checkout`, etc.

2024-07-22 21:05 UTC, julianxchang commented
Yup figured it out thank you! Committing the reverted changes now.

2024-07-22 21:33 UTC, theusaf approved these changes

2024-07-23 07:29 UTC, DarkVillager approved these changes
LGTM

2024-07-23 19:05 UTC, Bas950 approved these changes

2024-07-23 19:05 UTC, merged