feat(notespace): update presence
PreMiD/Presences pull request #8595
Opened 2024-07-23 17:19 UTC by ItsMateo20

## Description
- added the english part of the site (forgot to do it last time)
- changed how the paths and herfs are checked

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
### https://notespace.edu.pl/en/home
![image](https://github.com/user-attachments/assets/cceafe95-b9d2-49fc-82b6-37ce939ba56e)
![image](https://github.com/user-attachments/assets/09b81ff1-6a2c-4488-8f9f-8c0645a52186)

2024-07-23 20:51 UTC, theusaf approved these changes

2024-07-23 20:52 UTC, theusaf requested changes
Bump version

2024-07-24 16:06 UTC, theusaf approved these changes

2024-07-24 17:05 UTC, Bas950 approved these changes

2024-07-24 17:05 UTC, merged