New instances and watching status
PreMiD/Presences pull request #8607
Opened 2024-07-24 23:30 UTC by myysty

## Description 

sudo-flix is gone, added working instances, added watching status and moved episode and season after the show title.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/user-attachments/assets/d7eac01a-8170-4139-aa06-5467d977eb61)
![image](https://github.com/user-attachments/assets/34cadcff-994a-4c8e-a584-b043a829d17a)

</details>

2024-07-25 08:14 UTC, DarkVillager approved these changes
Run prettier other than that LGTM

2024-07-25 17:45 UTC, DarkVillager commented
@myysty attempt the following cmd: npm run format
After make sure to discard non movie-web changed files

2024-07-26 09:02 UTC, DarkVillager commented
Interesting. Have you run: npm i
before?

2024-07-26 12:28 UTC, myysty commented
yes i have

2024-07-27 13:20 UTC, DarkVillager requested changes
This _should_ fix it

2024-07-27 13:20 UTC, DarkVillager commented on websites/M/movie-web/presence.ts
> +				document.querySelector("video"),
```suggestion
				document.querySelector("video")
```

2024-07-27 13:20 UTC, DarkVillager commented on websites/M/movie-web/presence.ts
> +		barLength - numChars,
```suggestion
		barLength - numChars
```

2024-07-27 13:20 UTC, DarkVillager commented on websites/M/movie-web/presence.ts
> +	},
```suggestion
	}
```

2024-07-28 15:52 UTC, theusaf approved these changes
LGTM

2024-07-28 16:02 UTC, Bas950 approved these changes

2024-07-28 16:02 UTC, merged