Update presence.ts
PreMiD/Presences pull request #8630
Opened 2024-07-30 23:34 UTC by Kotir7k

Added /leagues page descrption.

## Description 

## Acknowledgements
- [ ] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ ] I linted the code by running `yarn format`
- [ ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

2024-07-30 23:42 UTC, veryCrunchy requested changes

2024-07-30 23:42 UTC, veryCrunchy commented on websites/N/Nitro Type/metadata.json
> +	"version": "1.3.23",
```suggestion
	"version": "1.2.24",
```

the change is so small in my opinion that a patch should be fine

2024-07-31 06:20 UTC, DarkVillager approved these changes
LGTM

2024-07-31 16:10 UTC, veryCrunchy commented
Can you change the title of the pr to `feat(Nitro Type): add leagues page`?

2024-07-31 17:32 UTC, theusaf approved these changes

2024-07-31 19:25 UTC, Bas950 approved these changes

2024-07-31 19:25 UTC, merged