feat(NameMC): privacy mode
PreMiD/Presences pull request #8668
Opened 2024-08-20 13:00 UTC by Kathund

## Description 

Added privacy mode
Fixed bugs when viewing different pages

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

Privacy Mode
![image](https://github.com/user-attachments/assets/0ae6a297-57ae-4510-8fc2-91273caf8cae)

Fix for search
![image](https://github.com/user-attachments/assets/05514273-5368-426e-bfbc-754d918e36e6)

Fix for viewing profile
![image](https://github.com/user-attachments/assets/1bf45daf-e255-4b7e-a568-e0bc8ba67a92)

Fix for viewing cape
![image](https://github.com/user-attachments/assets/80ffe2c9-6bd4-4c87-9b03-e4253804e443)

</details>

2024-08-20 23:00 UTC, theusaf requested changes

2024-08-20 23:00 UTC, theusaf commented on websites/N/NameMC/presence.ts
> +					.replace(`https://${location.hostname}`, "")
Use `document.location` rather than `location` for repository consistency

2024-08-21 23:11 UTC, theusaf approved these changes

2024-08-22 06:57 UTC, Bas950 approved these changes

2024-08-22 06:57 UTC, merged