feat(MangaGo): add new presence
PreMiD/Presences pull request #8683
Opened 2024-08-26 10:36 UTC by Hikki0710

## Description 
Resolves #7786 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/user-attachments/assets/c35a94aa-2799-4cc0-a7b1-c2bc84456bf2)
![image](https://github.com/user-attachments/assets/01e384a4-f04b-47b0-8a81-682391ff46e0)
![image](https://github.com/user-attachments/assets/23be4f96-591d-4128-aeb7-176bda3d1509)
![image](https://github.com/user-attachments/assets/0dcb9902-6302-43f3-a091-079ebb31cb0d)
![image](https://github.com/user-attachments/assets/aef1b61a-0d09-4349-aece-9b6c0812b44b)
![image](https://github.com/user-attachments/assets/3ff7888b-a64f-4ff0-b29f-82b102864f6b)

with privacy enabled
![image](https://github.com/user-attachments/assets/31cd7eb4-13bc-4489-82c3-2afeb68a726a)
![image](https://github.com/user-attachments/assets/a39b9541-7e4d-4578-9fbd-953aa8dd6a0d)
![image](https://github.com/user-attachments/assets/01ab45db-e98e-40e7-9c60-fb014dfa1d6e)

</details>

2024-08-26 15:43 UTC, theusaf requested changes

2024-08-26 15:43 UTC, theusaf commented on websites/M/MangaGo/metadata.json
> +	"url": "mangago.me",
```suggestion
	"url": ["www.mangago.me","mangago.me"],
```

2024-08-27 18:24 UTC, theusaf approved these changes

2024-08-27 21:48 UTC, Hikki0710 commented
> Images kinda blurry can you improve that?

Unfortunately the logos and thumbnail are from the official website and they only have a resolution of 70x70 (so they become blurry when I change them to 512x512 with [imageresizer](https://imageresizer.com/)). Could I change the thumbnail using a screenshot from the website?

https://i.imgur.com/1YR03XH.png

![image](https://github.com/user-attachments/assets/3a4fdb90-264a-4866-ae1e-a70c787018de)

2024-08-27 22:56 UTC, theusaf commented
> > Images kinda blurry can you improve that?
> 
> Unfortunately the logos and thumbnail are from the official website and they only have a resolution of 70x70 (so they become blurry when I change them to 512x512 with [imageresizer](https://imageresizer.com/)). Could I change the thumbnail using a screenshot from the website?

Yes, the thumbnail can be a screenshot of the website. For the logo, you could try using tools like [waifu2x](http://waifu2x.udp.jp/) as recommended in the guidelines, converting it to an svg, or other similar methods.

2024-08-28 09:33 UTC, Hikki0710 commented
okay they look good to me

2024-08-28 11:00 UTC, Bas950 approved these changes

2024-08-28 11:00 UTC, merged