feat(AnimixPlay): add new presence
PreMiD/Presences pull request #8693
Opened 2024-08-28 18:04 UTC by SafuGit

## Description 
Add Presence for AnimixPlay.

## Acknowledgements
- [ ] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ ] I linted the code by running `yarn format`
- [ ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/user-attachments/assets/ef6c104c-80c9-49d0-b41e-f88ac7034c2e)
![image](https://github.com/user-attachments/assets/72662f7b-1305-4a48-9a4c-d5e547b6c5cb)
![image](https://github.com/user-attachments/assets/83a849e5-7cfc-4d69-a3e6-ebb2d58ce41b)

</details>

2024-08-28 20:46 UTC, theusaf commented
Note: previously removed in #7084

2024-08-29 11:30 UTC, Bas950 submitted a review, later dismissed

2024-08-29 17:46 UTC, theusaf requested changes

2024-08-29 17:46 UTC, theusaf commented on websites/A/AnimixPlay/metadata.json
> +	"logo": "https://animixplay.fun/themes/zanimix/icon.png",
Logo should be 512x512px

2024-08-29 17:46 UTC, theusaf commented on websites/A/AnimixPlay/presence.ts
> +	}),
```suggestion
```

2024-08-29 17:46 UTC, theusaf commented on websites/A/AnimixPlay/presence.ts
> +			],
Buttons like these are prohibited based on the guidelines.
```suggestion
```

2024-08-29 17:46 UTC, theusaf commented on websites/A/AnimixPlay/presence.ts
> +			TitleAndEpisode = document.querySelector(".animetitle").textContent;
variable name should be in `camelCase`

2024-08-31 17:43 UTC, theusaf requested changes

2024-08-31 17:43 UTC, theusaf commented on websites/A/AnimixPlay/presence.ts
> +	Logo = "https://animixplay.fun/themes/zanimix/icon.png",
```suggestion
	Logo = "https://i.postimg.cc/9XLKNDt8/icon-animixplay.png",
```

2024-09-02 16:08 UTC, Bas950 approved these changes

2024-09-03 20:21 UTC, theusaf approved these changes

2024-09-03 20:21 UTC, merged