feat(AnimeElysium): Added new presence
PreMiD/Presences pull request #8704
Opened 2024-09-01 10:59 UTC by DevJustMert

## Description 

## Acknowledgements
- [ ] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ ] I linted the code by running `yarn format`
- [ ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/user-attachments/assets/a3d5f561-396f-4921-9ab0-565b13177c22)
![image1](https://github.com/user-attachments/assets/f79378a2-638c-470e-ae09-cb0185ab943b)
![image3](https://github.com/user-attachments/assets/79fccf66-58f6-47ae-b91e-f1d622e0024f)
![image4](https://github.com/user-attachments/assets/5fd789f3-7e63-47f7-8a15-cf4c5ed04230)
![image5](https://github.com/user-attachments/assets/8a629712-5054-4413-8a13-1fe098cff1e6)

</details>

2024-09-03 11:26 UTC, Bas950 requested changes

2024-09-03 11:26 UTC, Bas950 commented on websites/A/AnimeElysium/metadata.json
> +	"logo": "https://i.imgur.com/8wSwOLJ.png",
Logo should be 512x512

2024-09-03 11:26 UTC, Bas950 commented on websites/A/AnimeElysium/presence.ts
> +}
Ditto the url returns a 500x500 image.

2024-09-03 11:26 UTC, Bas950 commented on websites/A/AnimeElysium/presence.ts
> +			)
Are there any better query selectors you may be able to use? If they change one bit of styling, the selector won't work anymore.

2024-09-03 11:26 UTC, Bas950 commented on websites/A/AnimeElysium/presence.ts
> +		presenceData.startTimestamp = Math.floor(Date.now() / 1000);
await strings before instead of `(await string).` (check what other presences do)

2024-09-03 20:25 UTC, theusaf requested changes

2024-09-03 20:25 UTC, theusaf commented on websites/A/AnimeElysium/presence.ts
> +	if (window.location.pathname === "/") {
For consistency with other presences, use `document.location` instead of `window.location`

2024-09-03 20:25 UTC, theusaf commented on websites/A/AnimeElysium/presence.ts
> +				url: document.URL,
Rather than `document.URL`, use `document.location.href`

2024-09-03 20:25 UTC, theusaf commented on websites/A/AnimeElysium/presence.ts
> +		presenceData.startTimestamp = Math.floor(Date.now() / 1000);
Consider placing the start timestamp in a variable at the outermost scope. This prevents the timestamp from being constantly reset to '0 seconds elapsed'

2024-09-11 17:05 UTC, theusaf commented
Closing for inactivity. You may open a new PR after resolving the issues mentioned in this one.

2024-09-11 17:05 UTC, closed without merging