feat(ApplePodcasts): add Presence
PreMiD/Presences pull request #8726
Opened 2024-09-15 10:33 UTC by 1RB

2024-09-17 20:36 UTC, Bas950 requested changes

2024-09-17 20:36 UTC, Bas950 commented on websites/A/Apple Podcasts/presence.ts
> +		[privacy] = await Promise.all([presence.getSetting("privacy")]),
useless promise.all if there is only 1 promise

2024-09-17 20:36 UTC, Bas950 commented on websites/A/Apple Podcasts/presence.ts
> +				)[0] as HTMLImageElement
```suggestion
				shadowRootDir.querySelector<HTMLImageElement>(
					".lcd__artwork > picture > img"
				)
```

2024-09-17 20:36 UTC, Bas950 commented on websites/A/Apple Podcasts/presence.ts
> +	if (shadowRootDir?.querySelector(".lcd__active").ariaHidden !== "true") {
this comment needed here?

2024-09-17 20:36 UTC, Bas950 commented on websites/A/Apple Podcasts/presence.ts
> +		)[0].textContent;
Don't use querySelectorAll if you are just going to get the first item, then just use querySelector

2024-09-17 20:36 UTC, Bas950 commented on websites/A/Apple Podcasts/presence.ts
> +		const progress = shadowRootDir.querySelectorAll("#playback-progress")[0],
ditto

2024-09-17 20:36 UTC, Bas950 commented on websites/A/Apple Podcasts/presence.ts
> +			document.querySelectorAll(".headings > .headings__title")[0].textContent
ditto

2024-09-17 20:36 UTC, Bas950 commented on websites/A/Apple Podcasts/presence.ts
> +			document.querySelectorAll(".headings > .headings__subtitles")[0]
ditto

2024-09-17 20:36 UTC, Bas950 commented on websites/A/Apple Podcasts/presence.ts
> +			document.querySelector("picture > img") as HTMLImageElement
```suggestion
			document.querySelector<HTMLImageElement>("picture > img")
```

2024-09-17 22:52 UTC, 1RB commented
# updated images

| Setting | Result |
| --- | --- |
|![image](https://github.com/user-attachments/assets/01d875f1-7447-476b-bed1-59672588bddc)| ![image](https://github.com/user-attachments/assets/3efd5377-c3e6-4e0f-9b3e-3a73d9153d84) |
|![image](https://github.com/user-attachments/assets/e568da08-11fd-4e4c-bcfa-5e9c852933c8)|![image](https://github.com/user-attachments/assets/1e9f3827-33bb-4305-9bb6-981a0f26d4ad)|
|![image](https://github.com/user-attachments/assets/84cd6bc8-2c32-4014-807d-12b023040c23)|![image](https://github.com/user-attachments/assets/8e0aac59-3808-4ef4-beae-4e484f036835)|


|![image](https://github.com/user-attachments/assets/a118e124-41d3-41b4-beb9-f1562375703d)
| --- | 
|![image](https://github.com/user-attachments/assets/2fde6be9-6134-41cb-ae36-7148a4983f9c)|

2024-09-18 01:38 UTC, theusaf requested changes

2024-09-18 01:38 UTC, theusaf commented on package-lock.json
Undo changes to this file

2024-09-19 00:53 UTC, theusaf approved these changes

2024-09-19 08:26 UTC, Bas950 approved these changes

2024-09-19 08:26 UTC, merged