chore: change use case of Endtimestamp to also have starttimestamp
PreMiD/Presences pull request #8727
Opened 2024-09-15 10:37 UTC by darkvillager2

## Description 

## Acknowledgements
- [ ] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ ] I linted the code by running `yarn format`
- [ ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

2024-09-17 12:09 UTC, Bas950 commented on websites/A/ARD Mediathek/presence.ts
> +					Math.floor(video.duration)
use getTimestampsfromMedia

2024-09-17 12:14 UTC, Bas950 commented on websites/A/AnimeYuzu/presence.ts
> +						);
ditto

2024-09-17 12:15 UTC, Bas950 commented on websites/A/AnimixPlay/metadata.json
> +	"version": "1.0.7",
huge version bump?

2024-09-17 12:15 UTC, Bas950 commented on websites/A/AnimixPlay/presence.ts
>  				Math.floor(video.duration)
ditto

2024-09-17 12:16 UTC, Bas950 commented on websites/A/aha/presence.ts
> +				);
ditto

2024-09-17 12:17 UTC, Bas950 commented on websites/B/Behance/presence.ts
> +					);
Ditto

2024-09-17 12:17 UTC, Bas950 commented on websites/B/BetterAnime/presence.ts
> +					presence.getTimestamps(video.currentTime, video.duration);
ditto

2024-09-17 12:18 UTC, Bas950 commented on websites/B/BetterAnime/presence.ts
> +					presence.getTimestamps(video.currentTime, video.duration);
ditto

2024-09-17 12:33 UTC, darkvillager2 commented on websites/0-9/2048Verse/presence.ts
> +
To meet current guideliness while i was at it for the other thing.

2024-09-17 12:33 UTC, darkvillager2 commented on websites/A/ARD Mediathek/presence.ts
> +					Math.floor(video.duration)
here it is required.

2024-09-17 12:33 UTC, darkvillager2 commented on websites/A/Anime4up/presence.ts
> +						);
cant.

2024-09-17 12:34 UTC, darkvillager2 commented on websites/A/AnimeYuzu/presence.ts
> +						);
cant

2024-09-17 12:34 UTC, darkvillager2 commented on websites/A/AnimeYuzu/presence.ts
> +						);
cant

2024-09-17 12:34 UTC, darkvillager2 commented on websites/A/AnimesOnline/presence.ts
> +				);
cant

2024-09-17 12:35 UTC, darkvillager2 commented on websites/A/Animevietsub/presence.ts
> +				);
here it is required.

2024-09-17 12:35 UTC, darkvillager2 commented on websites/A/AnimixPlay/metadata.json
> +	"version": "1.0.7",
i will look into it

2024-09-17 12:35 UTC, darkvillager2 commented on websites/A/AnimixPlay/presence.ts
>  				Math.floor(video.duration)
cant

2024-09-17 12:36 UTC, darkvillager2 commented on websites/A/aha/presence.ts
> +				);
here it is required.

2024-09-17 12:36 UTC, darkvillager2 commented on websites/B/Behance/presence.ts
> +					);
cant

2024-09-17 12:36 UTC, darkvillager2 commented on websites/B/BetterAnime/presence.ts
> +					presence.getTimestamps(video.currentTime, video.duration);
cant

2024-09-17 12:36 UTC, darkvillager2 commented on websites/B/BetterAnime/presence.ts
> +					presence.getTimestamps(video.currentTime, video.duration);
cant

2024-09-17 19:00 UTC, Bas950 requested changes

2024-09-17 19:00 UTC, Bas950 commented on websites/M/MyOnlineRadio/handleStation.ts
> +					if (startTS && endTS) {
No version bump?

2024-09-17 19:00 UTC, Bas950 commented on websites/M/movie-web/metadata.json
> +	"version": "1.1.8",
Big increase

2024-09-17 19:00 UTC, Bas950 commented on websites/S/Skribbl.io/metadata.json
> +	"version": "1.2.8",
Bump but no changes

2024-09-19 01:43 UTC, theusaf requested changes

2024-09-19 01:43 UTC, theusaf commented on websites/B/BeatLeader/metadata.json
> +	"version": "1.10.6",
```suggestion
	"version": "1.10.2",
```

2024-09-19 01:43 UTC, theusaf commented on websites/B/Behance/presence.ts
> +						Math.floor(video.duration)
Video time stamps are retrieved as text from html elements. Review interface and data when changing this presence.

2024-09-19 01:43 UTC, theusaf commented on websites/C/Canvas/presence.ts
> +												presence.getTimestamps(elapsed, duration);
Due to the way this presence works, this should probably just set the start timestamp to `Date.now() / 1000` in addition to the previous `endTimestamp` code

2024-09-19 01:43 UTC, theusaf commented on websites/C/Crave/presence.ts
> +				presence.getTimestamps(elapsed, duration);
Duplicate fix attempt?
```suggestion
```

2024-09-19 01:43 UTC, theusaf commented on websites/C/Cuevana 3/presence.ts
> +						presence.getTimestampsfromMedia(video);
`video` doesn't exist. Some data is retrieved from an iframe. Consider adding a `startTimestamp` global variable to the original code instead.

2024-09-19 01:43 UTC, theusaf commented on websites/F/FormulaOneTv/presence.ts
> +	presenceData.startTimestamp = browingTimestamp;
```suggestion
	presenceData.startTimestamp = browsingTimestamp;
```

2024-09-19 01:43 UTC, theusaf commented on websites/G/Gaia/metadata.json
> +	"version": "1.0.15",
```suggestion
	"version": "1.0.14",
```

2024-09-19 01:43 UTC, theusaf commented on websites/K/Kayoanime/presence.ts
> +							presence.getTimestampsfromMedia(video);
`video` is iframe data, not an actual video element.

2024-09-19 01:43 UTC, theusaf commented on websites/A/AnimixPlay/presence.ts
Changes made but version not bumped

2024-09-19 09:05 UTC, darkvillager2 commented on websites/S/Skribbl.io/metadata.json
> +	"version": "1.2.8",
There are changes...

2024-09-20 08:57 UTC, Bas950 requested changes

2024-09-20 08:57 UTC, Bas950 commented on websites/Y/YouTube/metadata.json
> +	"version": "5.13.1",
bumped without changes for the rest LGTM

2024-09-20 09:41 UTC, Bas950 approved these changes

2024-09-20 14:31 UTC, merged