feat(iHeartRadio): add site support update presence
PreMiD/Presences pull request #8729
Opened 2024-09-15 17:59 UTC by iiTxicz

## Description 
Added new Site Support (https://listen.iheart.com/)
Remodeled entire architecture of presence
#8150 - Giving more support towards this request

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
https://imgur.com/a/hp6A0rr 

</details>

2024-09-15 17:59 UTC, iiTxicz commented
Also requesting I take over the Presence due to entire makeover over the presence.

2024-09-15 19:02 UTC, iiTxicz commented
> Also requesting I take over the Presence due to entire makeover over the presence.

Let me know if I can change it to my name before concluding the PR.

2024-09-17 15:27 UTC, darkvillager2 commented on websites/I/iHeartRadio/metadata.json
> -		"name": "Striker",
Do add him as contributor.

2024-09-17 15:29 UTC, iiTxicz commented on websites/I/iHeartRadio/metadata.json
> -		"name": "Striker",
Done

2024-09-17 20:39 UTC, Bas950 requested changes

2024-09-17 20:39 UTC, Bas950 commented on websites/I/iHeartRadio/presence.ts
> +		largeImageKey: "https://i.imgur.com/Z5CAqIw.png",
```suggestion
		largeImageKey: baseImage,
```

2024-09-18 15:39 UTC, iiTxicz commented
Everything should be good now

2024-09-18 17:58 UTC, Bas950 approved these changes

2024-09-19 00:52 UTC, theusaf approved these changes

2024-09-19 00:52 UTC, merged