feat(PresenceValidator): provide presence name in errors
PreMiD/Presences pull request #8731
Opened 2024-09-17 10:17 UTC by darkvillager2

## Description 

Add presence name to warnings/errors for multiple presence PRs.

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

Locally:
![image](https://github.com/user-attachments/assets/fbdc191b-0e72-4247-8cae-f2de1dc8dd17)

</details>

2024-09-17 20:42 UTC, Bas950 requested changes

2024-09-17 20:42 UTC, Bas950 commented on tools/auto/presenceValidator.ts
> +			message: `Schema version is not up to date for presence (${presence}) - expected: ${schema.url}, got: ${metadata.$schema}`,
```suggestion
			message: `Schema version is not up to date (Presence: ${presence}) - expected: ${schema.url}, got: ${metadata.$schema}`,
```

2024-09-17 20:42 UTC, Bas950 commented on tools/auto/presenceValidator.ts
> +				message: `Version has not been bumped for presence (${presence})`,
```suggestion
				message: `Version has not been bumped (Presence: ${presence})`,
```

2024-09-17 20:42 UTC, Bas950 commented on tools/auto/presenceValidator.ts
> +			message: `Initial version must be 1.0.0 for presence (${presence})`,
```suggestion
			message: `Initial version must be 1.0.0 (Presence: ${presence})`,
```

2024-09-18 17:57 UTC, Bas950 approved these changes

2024-09-19 00:51 UTC, theusaf approved these changes

2024-09-19 00:51 UTC, merged