feat(Miruro): add Presence
PreMiD/Presences pull request #8744
Opened 2024-09-20 14:39 UTC by Neo1912

## Description 
add presence for Miruro

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
![image](https://github.com/user-attachments/assets/323a0371-4d4f-41bf-a9ae-c79793229e4c)
![image](https://github.com/user-attachments/assets/fa988ae5-da3e-4b80-9d08-5f2b7d6ccb69)
![image](https://github.com/user-attachments/assets/f9a1bb4a-c1bf-4267-81ab-d94c23266ede)

</details>

2024-09-20 19:58 UTC, darkvillager2 requested changes
Hello, thanks for contributing!

If you have any questions about the requested changes feel free to dm me (Discord ois @Dark_Ville) or to ask in here!

2024-09-20 19:58 UTC, darkvillager2 commented on websites/M/Miruro/presence.ts
> +const enum Assets { // Other default assets can be found at index.d.ts
This is a placeholder comment, please remove.
```suggestion
const enum Assets { 
```

2024-09-20 19:58 UTC, darkvillager2 commented on websites/M/Miruro/presence.ts
> +				{ label: "Join Discord", url: "https://discord.com/invite/pjsdJp96mY" }, // Miruro Discord server
You can't advertise in the presence like this.

2024-09-20 19:58 UTC, darkvillager2 commented on websites/M/Miruro/presence.ts
> +				?.childNodes[0]?.textContent.trim(),
Childnodes[0] isn;t the best option here.
```suggestion
		const infoTitle = document
				.querySelector("h1.sc-eZxvvn.cywezh")?.firstChild?.textContent.trim(),
```

2024-09-20 19:58 UTC, darkvillager2 commented on websites/M/Miruro/presence.ts
> +			presenceData.smallImageText = "miruro.com";
```suggestion
		if (video) {
				presenceData.smallImageKey = !video?.paused ? Assets.Play : Assets.Pause;
				presenceData.smallImageText = !video?.paused ? "Now Watching" : !!currentAnimeProgress ? `Paused | ${currentAnimeProgress}` : "Paused"
		} else {
			presenceData.smallImageKey = Assets.Logo;
			presenceData.smallImageText = "miruro.com";
```

2024-09-20 19:58 UTC, darkvillager2 commented on websites/M/Miruro/presence.ts
> +			)?.textContent;
```suggestion
```

2024-09-20 19:58 UTC, darkvillager2 commented on websites/M/Miruro/presence.ts
> +			currentAnimeProgress = `${currentTime}/${duration}`;
```suggestion
		if (video?.currentTime && video?.duration)
			currentAnimeProgress = `${video?.currentTime}/${video?.duration}`;
```

2024-09-20 19:58 UTC, darkvillager2 commented on websites/M/Miruro/presence.ts
> +		let currentAnimeProgress;
```suggestion
		let currentAnimeProgress: String;
```

2024-09-20 19:59 UTC, darkvillager2 commented
Also i don't seen any timestamps getting used is there a reason for that?

2024-09-21 16:37 UTC, darkvillager2 requested changes

2024-09-21 16:37 UTC, darkvillager2 commented on websites/M/Miruro/metadata.json
> +	"$schema": "https://schemas.premid.app/metadata/1.10",
```suggestion
	"$schema": "https://schemas.premid.app/metadata/1.11",
	"apiVersion": 1,
```

2024-09-21 18:21 UTC, Bas950 requested changes
For the rest LGTM

2024-09-21 18:21 UTC, Bas950 commented on websites/M/Miruro/presence.ts
> +			presenceData.smallImageText = "miruro.com";
```suggestion
```

2024-09-21 19:26 UTC, theusaf requested changes

2024-09-21 19:26 UTC, theusaf commented on websites/M/Miruro/presence.ts
> +			)?.src;
If possible, try using query selectors which avoid computer-generated classes or ids.

2024-09-26 02:30 UTC, theusaf requested changes
Other than this, LGTM

2024-09-26 02:30 UTC, theusaf commented on websites/M/Miruro/presence.ts
> +		const searchQuery = new URLSearchParams(window.location.search).get(
Use `document.location` for repository consistency
```suggestion
		const searchQuery = new URLSearchParams(document.location.search).get(
```

2024-09-27 01:54 UTC, theusaf approved these changes

2024-09-27 08:54 UTC, Bas950 approved these changes

2024-09-27 08:54 UTC, merged