feat(YTPLR): add Presence
PreMiD/Presences pull request #8759
Opened 2024-09-26 09:57 UTC by PeterStrick

## Description 
Adds a Presence for YTPLR (YouTube Playlist Randomizer)

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![YTPLR Modification](https://github.com/user-attachments/assets/4d6a1f02-d068-4a68-9d6b-6dd5aeccbd9b)
</details>

<details>
<summary> Proof showing the Website and Discord Profile without the Presence </summary>

![YTPLR WithoutPresence](https://github.com/user-attachments/assets/7885cd0c-38fb-4ca9-bd46-b26b879916a9)
</details>

<details>
<summary> Proof showing the Website and Discord Profile with the Presence enabled </summary>

![YTPLR WithPresence BetaExtension](https://github.com/user-attachments/assets/097452fb-86c5-487b-822f-713b1eb21203)
</details>

<details>
<summary> Screenshot of the Settings Window </summary>

![YTPLR Settings](https://github.com/user-attachments/assets/a84f608d-d6b8-4137-9f16-830cb97c2930)
</details>

2024-09-27 01:59 UTC, theusaf requested changes

2024-09-27 01:59 UTC, theusaf commented on websites/Y/YTPLR/metadata.json
> +	"logo": "https://youtube-playlist-randomizer.bitbucket.io/music-icon.png",
Logo must be 512x512px. You may use tools like waifu2x to upscale if needed.

2024-09-27 01:59 UTC, theusaf commented on websites/Y/YTPLR/presence.ts
> +	}),
See the [localization repository](https://github.com/PreMiD/Localization/blob/main/src/Presence/general.json) for keys to use for strings.

2024-09-27 01:59 UTC, theusaf commented on websites/Y/YTPLR/presence.ts
> +	videoPlaylistID = (document.querySelector("#pid") as HTMLInputElement).value;
```suggestion
	videoPlaylistID = document.querySelector<HTMLInputElement>("#pid").value;
```

2024-09-27 01:59 UTC, theusaf commented on websites/Y/YTPLR/presence.ts
> +		]);
As there is only one setting, `Promise.all` is not needed here.
```suggestion
		showButtons = await presence.getSetting<boolean>("buttons");
```

2024-09-27 02:08 UTC, theusaf requested changes

2024-09-27 02:08 UTC, theusaf commented on websites/Y/YTPLR/metadata.json
> +	"readLogs": false
This field is by default `false`
```suggestion
```

2024-09-28 06:13 UTC, theusaf approved these changes

2024-09-28 09:43 UTC, Bas950 requested changes

2024-09-28 09:43 UTC, Bas950 commented on websites/Y/YTPLR/metadata.json
> +	"iFrameRegExp": ".*",
Are you able to narrow this regex?

2024-09-28 09:43 UTC, Bas950 commented on websites/Y/YTPLR/presence.ts
> +	Logo = "https://youtube-playlist-randomizer.bitbucket.io/music-icon.png",
```suggestion
	Logo = "https://i.imgur.com/hsDOqgw.png",
```

2024-09-28 09:47 UTC, Bas950 commented
Also maybe add an altname for the full name

2024-09-28 21:32 UTC, PeterStrick commented on websites/Y/YTPLR/metadata.json
> +	"iFrameRegExp": ".*",
I can try to do so tomorrow

2024-09-29 22:53 UTC, theusaf approved these changes

2024-09-30 05:42 UTC, Bas950 approved these changes

2024-09-30 05:42 UTC, merged