feat(Simkl): add presence
PreMiD/Presences pull request #8780
Opened 2024-10-03 21:17 UTC by Kuriel23

## Description 
Add presence for Simkl. The presence shows what movies, lists, profiles, anime, and TV shows users are currently viewing and searching for information about.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/user-attachments/assets/b95ad637-5aec-4794-8518-16ee166b74b5)
![image](https://github.com/user-attachments/assets/acd4150b-14c8-4155-a1cd-885179f67ae1)
![image](https://github.com/user-attachments/assets/5b8a295a-79d4-4bbe-96df-9f4095a0fc1e)
![image](https://github.com/user-attachments/assets/fe28fc07-26d7-4906-a292-a13332ca392a)
![image](https://github.com/user-attachments/assets/a48c8e7f-b866-4207-ad44-8be5b769d62b)
![image](https://github.com/user-attachments/assets/7a9db847-27db-48d0-824f-cb9e29531475)

</details>

2024-10-04 19:09 UTC, darkvillager2 commented on websites/S/Simkl/metadata.json
> +		"en": "Your All-in-One TV, Anime and Movie Tracking Platform"
Official description
```suggestion
		"en": "Track what you watch. Discover new shows and movies. Receive episode notifications. Get personalized recommendations. Join Simkl for free."
```

2024-10-04 19:17 UTC, darkvillager2 requested changes

2024-10-04 19:17 UTC, darkvillager2 commented on websites/S/Simkl/metadata.json
> +		"en": "Your All-in-One TV, Anime and Movie Tracking Platform"
Official description
```suggestion
		"en": "Track what you watch. Discover new shows and movies. Receive episode notifications. Get personalized recommendations. Join Simkl for free."
```

2024-10-04 19:17 UTC, darkvillager2 commented on websites/S/Simkl/presence.ts
> +							"#global_div > div.SimklHeaderBgShaddow > div > div > div.SimklTVReviewHeaderBottom > table > tbody > tr > td > table > tbody > tr > td:nth-child(2) > table > tbody > tr:nth-child(2) > td"
try to shorten selectors where possible.
```suggestion
							"span.ajLinkInside"
```

2024-10-04 19:17 UTC, darkvillager2 commented on websites/S/Simkl/presence.ts
> +		presenceData: PresenceData = {
```suggestion
		presenceData: PresenceData = {
		largeImageKey: Assets.Logo,
```

2024-10-04 19:17 UTC, darkvillager2 commented on websites/S/Simkl/presence.ts
> +
```suggestion

const enum Assets {
Logo =  "https://i.imgur.com/1m6HokC.png",
}
```

2024-10-04 19:17 UTC, darkvillager2 commented on websites/S/Simkl/presence.ts
> +	return document.querySelector<HTMLImageElement>(tags)?.src;
```suggestion
	return document.querySelector<HTMLImageElement>(tags)?.src ?? Assets.Logo;
```

2024-10-04 21:18 UTC, Kuriel23 commented
Done.

2024-10-04 23:43 UTC, theusaf submitted a review, later dismissed

2024-10-05 10:08 UTC, darkvillager2 commented
@theusaf there is no largeimagekey?

2024-10-07 06:33 UTC, Bas950 approved these changes

2024-10-07 06:34 UTC, Bas950 commented
> @theusaf there is no largeimagekey?

there is?

2024-10-07 17:57 UTC, darkvillager2 commented
> > @theusaf there is no largeimagekey?
> 
> there is?

Woops i was viewing an old commit xd

2024-10-08 15:38 UTC, merged