feat(Brave Search): add presence
PreMiD/Presences pull request #8804
Opened 2024-10-09 02:22 UTC by Kuriel23

## Description 
Add presence for Brave Search. The presence shows what the user is searching on index, news, images, videos, or goggles and the help pages or settings. Solves #8437 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![Discord_2vij8dR4nG](https://github.com/user-attachments/assets/b1be79b8-5efc-4846-b8b1-cf9711dfda72)

![Discord_blKjWDFpA8](https://github.com/user-attachments/assets/bdf65d04-1832-4793-b3e1-b0aaba5f090f)

![Discord_TGQ9oRehCk](https://github.com/user-attachments/assets/481cc0a9-768a-43b5-af1a-ba7c8a3d4737)

![Discord_TyvTKGAzAX](https://github.com/user-attachments/assets/ea8c006b-13fe-43bc-95d4-9ce9f91f8854)

</details>

2024-10-09 17:45 UTC, darkvillager2 requested changes

2024-10-09 17:45 UTC, darkvillager2 commented on websites/B/Brave Search/metadata.json
> +		"en": "The smarter way to search."
```suggestion
		"en": "Search the Web. Privately. Truly useful results, AI-powered answers, & more. All from an independent index. No profiling, no bias, no Big Tech."
```

2024-10-09 17:45 UTC, darkvillager2 commented on websites/B/Brave Search/metadata.json
> +	]
Privacy setting for this is a must imo.

2024-10-09 21:05 UTC, Kuriel23 commented
Done.

2024-10-10 01:54 UTC, theusaf approved these changes

2024-10-10 06:07 UTC, darkvillager2 approved these changes

2024-10-10 06:54 UTC, Bas950 commented on websites/B/Brave Search/presence.ts
> +				? ""
```suggestion
				? undefined
```

2024-10-10 15:56 UTC, Bas950 approved these changes

2024-10-10 15:56 UTC, merged

2024-10-12 08:46 UTC, darkvillager2 commented on websites/B/Brave Search/presence.ts
> +				  undefined
no