fix(IDLIX): update domain
PreMiD/Presences pull request #8819
Opened 2024-10-13 19:36 UTC by skullysmods

## Description 
Update domain 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/user-attachments/assets/10e48dda-75e1-4854-a7c2-19aea1afb18c)

</details>

2024-10-14 21:27 UTC, darkvillager2 requested changes

2024-10-14 21:27 UTC, darkvillager2 commented on websites/I/IDLIX/metadata.json
> +	],
Not enough contribution for this.

2024-10-14 21:28 UTC, darkvillager2 requested changes

2024-10-14 21:28 UTC, darkvillager2 commented on websites/I/IDLIX/metadata.json
> +	"regExp": "([0-9]+)(?<!10)[.]([0-9]+)(?<!192[.]168)(?<!172[.](1[6-9]|2[0-9]|3[0-1]))[.]([0-9]+)[.]([0-9]+)|(((tv([0-9]?))?(vip)?[.])?id(f)?lix(officialx)?[.][a-z]{2,6})",
```suggestion
	"regExp": "([0-9]+)(?<!10)[.]([0-9]+)(?<!192[.]168)(?<!172[.](1[6-9]|2[0-9]|3[0-1]))[.]([0-9]+)[.]([0-9]+)|(((tv([0-9]?))?(vip)?[.])?id(f)?lix(official(x)?)?[.][a-z]{2,6})",
```

2024-10-15 06:18 UTC, skullysmods commented on websites/I/IDLIX/metadata.json
> +	],
Okay, I changed it, no worries

2024-10-15 14:41 UTC, darkvillager2 approved these changes
lgtM

2024-10-15 15:13 UTC, Bas950 approved these changes

2024-10-17 00:23 UTC, theusaf approved these changes

2024-10-17 00:23 UTC, merged