feat(Voiranime): add privacy mode && show button/show timestamp settings
PreMiD/Presences pull request #8840
Opened 2024-10-25 20:48 UTC by skullysmods

## Description 
Add multilanguage, privacy mode, show buttons settings && show timestamps settings

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

2024-10-26 09:45 UTC, darkvillager2 requested changes

2024-10-26 09:45 UTC, darkvillager2 commented on websites/V/Voiranime/presence.ts
> +			presence.getSetting<string>("lang").catch(() => "en"),
```suggestion
			presence.getSetting<string>("lang").catch(() => "fr"),
```

2024-10-28 20:47 UTC, Bas950 approved these changes

2024-10-29 23:36 UTC, theusaf approved these changes

2024-10-29 23:37 UTC, merged