Update metadata.json (ANOTHER DOMAIN)
PreMiD/Presences pull request #8877
Opened 2024-11-08 18:10 UTC by Zukuchi

add 'watchasia.to' please. it's another domain of dramacool, i think it myt be the original because it's easier to find drama names there unlike the dramacool.vc one. Thank you
(also, i dont know how to code so I just put it like that but anyways, yeah)

## Description 

## Acknowledgements
- [ ] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ ] I linted the code by running `yarn format`
- [ ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

2024-11-11 21:17 UTC, theusaf requested changes

2024-11-11 21:17 UTC, theusaf commented on websites/D/DramaCool/metadata.json
>  	"version": "1.3.0",
```suggestion
	"version": "1.3.1",
```

2024-11-11 21:18 UTC, theusaf commented
Consider also adding the domain from #8723 too

2024-11-18 18:11 UTC, darkvillager2 commented on websites/D/DramaCool/metadata.json
> +	"url": "watchasia.to",
huh

2024-11-21 21:41 UTC, theusaf commented
Closing for inactivity. You can open a new PR after resolving existing conversatoins

2024-11-21 21:41 UTC, closed without merging