feat(YNOProject): add Presence
PreMiD/Presences pull request #8879
Opened 2024-11-10 04:46 UTC by luo3house

## Description 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

<img width="284" alt="Screenshot 2024-11-10 at 12 27 25" src="https://github.com/user-attachments/assets/d7391a78-cb6a-460f-a7ae-7242e5653510">
<img width="284" alt="Screenshot 2024-11-10 at 12 30 22" src="https://github.com/user-attachments/assets/4f53ac6a-39f1-4238-8c00-6529ceaf5a67">
<img width="284" alt="Screenshot 2024-11-10 at 12 31 28" src="https://github.com/user-attachments/assets/26389cd2-73ea-45ea-98cf-b2440c982074">
<img width="284" alt="Screenshot 2024-11-10 at 12 32 11" src="https://github.com/user-attachments/assets/fef36d00-3075-4666-b717-d376b3021ba1">
<img width="284" alt="Screenshot 2024-11-10 at 12 32 57" src="https://github.com/user-attachments/assets/483dfce6-b222-4f3c-9ee3-7e46309d8ad4">
<img width="284" alt="Screenshot 2024-11-10 at 12 35 18" src="https://github.com/user-attachments/assets/4abef5fc-82ee-4631-beca-dbf6dfeb552d">
<img width="284" alt="Screenshot 2024-11-10 at 12 45 39" src="https://github.com/user-attachments/assets/e5ac1e15-49ec-4b4e-913f-3b5c62984f55">

</details>

2024-11-10 11:35 UTC, darkvillager2 approved these changes
LGTM

2024-11-11 15:26 UTC, luo3house commented
<img width="284" alt="Screenshot 2024-11-11 at 22 27 01" src="https://github.com/user-attachments/assets/50b2af0c-abaf-48ad-8b90-188c6c04fa65">

<img width="284" alt="Screenshot 2024-11-11 at 22 19 58" src="https://github.com/user-attachments/assets/788690c8-3594-441a-9ea7-20de17b90010">

<details>
<summary> See more </summary>



<img width="284" alt="Screenshot 2024-11-11 at 22 23 21" src="https://github.com/user-attachments/assets/1f7113b1-d81c-41c3-bd88-55c93603c72d">
<img width="284" alt="Screenshot 2024-11-11 at 22 29 09" src="https://github.com/user-attachments/assets/fccce487-9845-4706-b4f1-c4bec89c3a24">
<img width="284" alt="Screenshot 2024-11-11 at 22 26 13" src="https://github.com/user-attachments/assets/dd5a5f9e-ac63-47ad-b660-21b001eead46">
<img width="284" alt="Screenshot 2024-11-11 at 22 24 48" src="https://github.com/user-attachments/assets/0c19d016-c70c-40aa-ba85-37cf1389f042">
<img width="284" alt="Screenshot 2024-11-11 at 22 23 50" src="https://github.com/user-attachments/assets/c7e49312-9369-4e1c-978a-b2ded587193c">
<img width="284" alt="Screenshot 2024-11-11 at 22 18 15" src="https://github.com/user-attachments/assets/dc04d70a-e0ba-4630-928d-11ab1695a5ec">


</details>

2024-11-11 21:16 UTC, theusaf requested changes
Logic looks good, just a couple of stylistic things to fix to be consistent with other presence's quality and readability.

2024-11-11 21:16 UTC, theusaf commented on websites/Y/YNOProject/presence.ts
> +// });
Remove commented out code

2024-11-11 21:16 UTC, theusaf commented on websites/Y/YNOProject/presence.ts
> +		document.querySelector("#favicon") as HTMLLinkElement | undefined
```suggestion
		document.querySelector<HTMLLinkElement >("#favicon")
```

2024-11-11 21:16 UTC, theusaf commented on websites/Y/YNOProject/presence.ts
> +		document.querySelector("title") as HTMLElement | null
```suggestion
		document.querySelector("title")
```

2024-11-11 21:16 UTC, theusaf commented on websites/Y/YNOProject/presence.ts
> +	return (document.querySelector("#locationText") as HTMLElement | null)
```suggestion
	return document.querySelector("#locationText")
```

2024-11-11 21:16 UTC, theusaf commented on websites/Y/YNOProject/presence.ts
> +			? [{ label: `Play ${gameName}`, url: location.href }]
```suggestion
			? [{ label: `Play ${gameName}`, url: document.location.href }]
```

2024-11-12 01:22 UTC, luo3house commented
Thanks for typo suggestions

2024-11-12 02:54 UTC, luo3house commented
(Animated) badges for logged-in players
<img width="284" alt="Screenshot 2024-11-12 at 10 23 56" src="https://github.com/user-attachments/assets/f6862f26-37f3-4f7a-87ed-5b45ff605b07">

2024-11-13 16:30 UTC, theusaf approved these changes

2024-11-13 17:33 UTC, Bas950 requested changes

2024-11-14 06:49 UTC, luo3house commented
draw glitches occurs while performing animated actions cuz blobs of animation frame inquired were quickly got gc
<img width="184" alt="Screenshot 2024-11-14 at 14 03 21" src="https://github.com/user-attachments/assets/d30ee85f-4efc-424f-8e88-c8bd42bc8361">

2024-11-14 08:00 UTC, Bas950 approved these changes

2024-11-15 19:19 UTC, merged