feat(HBO GO): use watching type & fix only show browsing
PreMiD/Presences pull request #8890
Opened 2024-11-14 15:39 UTC by Slowlife01

## Description 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/user-attachments/assets/e8ef114e-a4ac-4f87-9cc7-0492e357f040)
![{69728F1E-2353-4FB9-A1C8-8BF5971C3758}](https://github.com/user-attachments/assets/7ad13252-4013-4964-a40e-73b7d94ea6a2)

</details>

2024-11-15 08:29 UTC, Slowlife01 commented on websites/H/HBO GO/presence.ts
> +		if (location.pathname.includes("/series/")) {
Forgot to show the series name itself 😆

2024-11-15 19:16 UTC, theusaf requested changes

2024-11-15 19:16 UTC, theusaf commented on websites/H/HBO GO/presence.ts
> +		if (location.pathname.includes("/series/")) {
```suggestion
		if (document.location.pathname.includes("/series/")) {
```

2024-11-15 19:16 UTC, theusaf commented on websites/H/HBO GO/presence.ts
> +			presenceData.state = location.pathname.includes("/movies/")
```suggestion
			presenceData.state = document.location.pathname.includes("/movies/")
```

2024-11-19 08:14 UTC, Bas950 approved these changes

2024-11-19 08:14 UTC, merged