fix(Physics Wallah): Website updated
PreMiD/Presences pull request #8900
Opened 2024-11-20 08:32 UTC by armup31

## Description 
The website had changed a few things so the thing wasn't working, the code is mildly updated and everything works

## Acknowledgements
- [ ] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ ] I linted the code by running `yarn format`
- [ ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

https://file.infiinite.live/kflow48rb0.png

</details>

2024-11-20 13:38 UTC, Bas950 requested changes

2024-11-20 13:38 UTC, Bas950 commented on websites/P/Physics Wallah/presence.ts
> +				).subject.name;
json parse it once, save as a variable, then use the .tags / .subject

2024-11-21 21:43 UTC, theusaf requested changes

2024-11-21 21:43 UTC, theusaf commented on websites/P/Physics Wallah/presence.ts
> +		fullurl = document.URL,
Use `document.location.href` instead of `document.URL` for code consistency

2024-11-26 05:27 UTC, armup31 commented
don't merge, something broke again the website is getting kinda buggy

2024-11-26 22:29 UTC, theusaf approved these changes

2024-11-27 09:43 UTC, Bas950 requested changes

2024-11-27 09:49 UTC, armup31 commented on websites/P/Physics Wallah/presence.ts
> +		fullurl = href,
probably i was testing out something and i forgot to remove it, can't we just ignore it?

2024-11-27 09:52 UTC, Bas950 approved these changes

2024-11-27 19:00 UTC, theusaf approved these changes

2024-11-27 19:00 UTC, merged