feat(LessWrong) add presence
PreMiD/Presences pull request #8913
Opened 2024-11-25 07:47 UTC by tonybolivar

## Description 
Add presence for LessWrong. The presence shows whether the user is on the homepage or browsing through forum posts.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary>Proof showing the creation/modification is working as expected</summary>

![image](https://github.com/user-attachments/assets/14792a90-0d37-42fc-a40d-dfedeff2027b)
![image](https://github.com/user-attachments/assets/f65c2c2a-3073-4d9e-ae26-60da33d9e75f)
</details>

2024-11-25 18:39 UTC, darkvillager2 requested changes

2024-11-25 18:39 UTC, darkvillager2 commented on websites/L/LessWrong/presence.ts
> +		presenceData.state = " ";
```suggestion
```

2024-11-26 22:19 UTC, theusaf approved these changes

2024-11-27 19:01 UTC, theusaf approved these changes

2024-11-28 09:28 UTC, Bas950 approved these changes

2024-11-28 09:28 UTC, merged