feat(AniLibria): add presence
PreMiD/Presences pull request #8929
Opened 2024-12-03 06:42 UTC by FlimixST

## Description 
Added presence for [AniLibria](https://anilibria.top/).

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
![image](https://github.com/user-attachments/assets/c63c3acc-be95-49c7-b29f-5e9209269523)
![image](https://github.com/user-attachments/assets/0671fd18-82fb-4e1b-a473-a4030fa7d91a)
![image](https://github.com/user-attachments/assets/e8a310a0-82bc-4beb-94a5-d2f7ab324fdb)
![image](https://github.com/user-attachments/assets/40bccb6e-5fd1-4ce4-904a-1605b47fc898)
![image](https://github.com/user-attachments/assets/0f7bb69a-17c4-4348-ac58-4b9c0ed35cd9)
![image](https://github.com/user-attachments/assets/301b5d6c-4e02-4a02-9d91-7df1c743fa4a)
![image](https://github.com/user-attachments/assets/9345c126-758c-4a8b-bd21-b48c47032f1a)
![image](https://github.com/user-attachments/assets/18de4b66-7956-4e9d-a47c-a4d12c3d0dfd)
![image](https://github.com/user-attachments/assets/0855c997-38d9-4ca0-94b3-a97ca1392f0a)
![image](https://github.com/user-attachments/assets/49b50323-5bbf-4d8a-8e27-244396638272)
![image](https://github.com/user-attachments/assets/aca1eea0-fc21-4db9-a59b-189a3547628d)
![image](https://github.com/user-attachments/assets/3780b48f-99af-4ef6-99a6-7a2fb523d193)
![image](https://github.com/user-attachments/assets/74d134e7-57f0-4a3b-a068-62392e7a20da)
![image](https://github.com/user-attachments/assets/0ae89c80-08ed-42fb-b61b-c96ae90be3a2)
![image](https://github.com/user-attachments/assets/36581257-f627-4a12-b8a1-2a8115ce6453)
![image](https://github.com/user-attachments/assets/3542c974-aecd-4093-936c-14ffcecd6141)
![image](https://github.com/user-attachments/assets/2f36051d-59dd-4187-8dd0-9a28b8b35a4c)

</details>

2024-12-03 07:34 UTC, FlimixST commented
very funny error in metadata was, forgot to change the site address in the description, because the description was taken from another project xD

2024-12-03 07:35 UTC, FlimixST commented on websites/A/AniLibria/metadata.json
> +		"ru": "Jut.su — это русский сайт с аниме"
xD

2024-12-03 23:20 UTC, theusaf requested changes

2024-12-03 23:20 UTC, theusaf commented on websites/A/AniLibria/metadata.json
> +	"logo": "https://i.imgur.com/HrvpNEc.png",
Logo must be 512x512px

2024-12-03 23:20 UTC, theusaf commented on websites/A/AniLibria/presence.ts
> +		PATHS = {
Consider placing this variable outside of the main loop for readability and performance

2024-12-03 23:20 UTC, theusaf commented on websites/A/AniLibria/presence.ts
> +}
This function may be unnecessary

2024-12-05 19:37 UTC, theusaf requested changes

2024-12-05 19:37 UTC, theusaf commented on websites/A/AniLibria/presence.ts
> +	};
```suggestion
	const presenceData: PresenceData = {
		type: ActivityType.Watching,
		largeImageKey: "https://i.imgur.com/shUaioa.png",
	};
```

2024-12-07 00:32 UTC, theusaf approved these changes

2024-12-07 22:34 UTC, Bas950 approved these changes

2024-12-07 22:34 UTC, merged