feat(Websim): add presence
PreMiD/Presences pull request #8942
Opened 2024-12-08 21:41 UTC by gwashark

## Description 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

2024-12-09 23:50 UTC, theusaf requested changes

2024-12-09 23:50 UTC, theusaf commented on websites/W/Websim/presence.ts
> +		path = window.location.pathname;
```suggestion
		path = document.location.pathname;
```

2024-12-09 23:50 UTC, theusaf commented on websites/W/Websim/presence.ts
> +		btnPrivacy = await presence.getSetting("btnPrivacy"),
Combine these using `Promise.all`

2024-12-09 23:50 UTC, theusaf commented on websites/W/Websim/presence.ts
> +			startTimestamp: browsingTimestamp,
```suggestion
			startTimestamp: browsingTimestamp,
			largeImageKey: "https://i.imgur.com/zDNmRxT.png",
```

2024-12-10 07:56 UTC, merged

2024-12-10 16:27 UTC, gwashark commented
@theusaf there wasn't anything to merge with...