feat(StreamEast): add presence
PreMiD/Presences pull request #8953
Opened 2024-12-12 07:20 UTC by Dlunhappy226

## Description 

This PR adds presence for the popular sports streaming platform, StreamEast.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/user-attachments/assets/a83da650-9d88-4470-81f6-29d219071fa3)

![image](https://github.com/user-attachments/assets/e90f194f-3cea-4a44-b695-9b188973ebf8)
</details>

2024-12-12 23:39 UTC, theusaf requested changes
Also this presence is low-quality. See if there are any additional details that can be added

2024-12-12 23:39 UTC, theusaf commented on websites/S/StreamEast/metadata.json
> +	"logo": "https://i.ibb.co/nMsJbMX/favicon-48x48.png",
Logo should be 512x512px

2024-12-13 19:25 UTC, Bas950 requested changes
Too low quality

2024-12-15 02:23 UTC, Dlunhappy226 commented
The detail is changed based on what the user is watching.
![image](https://github.com/user-attachments/assets/ba89adc9-6def-4ace-bb9f-d4f981f77918)
![image](https://github.com/user-attachments/assets/f7880c7c-f312-427d-a008-0d886479b1a7)

2024-12-18 19:08 UTC, theusaf requested changes
Try adding some of the other pages other than the streams (blog, categories, search, etc.)

2024-12-22 17:41 UTC, darkvillager2 requested changes
Hello,

Thanks for opening this Pull Request. 

I have requested changes to the code.

If you have any questions feel free to ask them here or on discord (@Dark_Ville)

2024-12-22 17:41 UTC, darkvillager2 commented on websites/S/StreamEast/presence.ts
> +	};
```suggestion
	},
	{pathname} = document.location;
```

2024-12-22 17:41 UTC, darkvillager2 commented on websites/S/StreamEast/presence.ts
> +	switch (document.location.pathname) {
```suggestion
	switch (pathname) {
```

2024-12-22 17:41 UTC, darkvillager2 commented on websites/S/StreamEast/presence.ts
> +			if (document.location.pathname.includes("/blog/"))
```suggestion
			if (pathname.includes("/blog/"))
```

2024-12-22 17:41 UTC, darkvillager2 commented on websites/S/StreamEast/presence.ts
> +				presenceData.details = `Watching: [${window.location.pathname
```suggestion
				presenceData.details = `Watching: [${pathname
```

2024-12-25 23:47 UTC, theusaf approved these changes

2024-12-26 00:58 UTC, Bas950 approved these changes

2024-12-26 00:58 UTC, merged