feat(LessWrong): add button for posts and profiles, display currently viewed profile
PreMiD/Presences pull request #8959
Opened 2024-12-15 03:19 UTC by tonybolivar

## Description

Added a button to view the title of the post the user is currently viewing. Handled getting the title of the post in a more effective way. Additionally added functionality to display profiles and a button to access said profile.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary>Proof showing the creation/modification is working as expected</summary>

![Proof 1](https://github.com/user-attachments/assets/56991a4f-09a1-41ae-a10e-990090daca68)
![Proof 2](https://github.com/user-attachments/assets/33db9e08-1de9-451c-85cd-8536c31f2e1f)

</details>

2024-12-17 19:37 UTC, Bas950 submitted a review, later dismissed

2024-12-18 19:10 UTC, theusaf requested changes

2024-12-18 19:10 UTC, theusaf commented on websites/L/LessWrong/presence.ts
> +				url: new URL(document.location.pathname, window.location.origin).href,
Use `document.location` for both for consistency
```suggestion
				url: new URL(document.location.pathname, document.location.origin).href,
```
Or use href directly
```suggestion
				url: document.location.href,
```

2024-12-18 19:10 UTC, theusaf commented on websites/L/LessWrong/presence.ts
> +				url: new URL(document.location.pathname, window.location.origin).href,
ditto

2024-12-21 00:09 UTC, theusaf approved these changes

2024-12-21 11:50 UTC, Bas950 approved these changes

2024-12-21 11:50 UTC, merged