feat(Dek-d): add presence
PreMiD/Presences pull request #8992
Opened 2024-12-22 11:32 UTC by pupiesa

## Description 
add new presence Dek-d

## Acknowledgements
- [ yes] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ yes] I linted the code by running `yarn format`
- [ yes] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
home page
<img width="1440" alt="Screen Shot 2567-12-22 at 18 22 55" src="https://github.com/user-attachments/assets/cdbd519a-a981-4249-a9c2-56e6d36154bf" />
blog with header name display
<img width="1440" alt="Screen Shot 2567-12-22 at 18 23 59" src="https://github.com/user-attachments/assets/ddaa5a63-a82d-4f7e-aa7a-b1dabe5762c1" />
quiz
<img width="1440" alt="Screen Shot 2567-12-22 at 18 24 50" src="https://github.com/user-attachments/assets/48a68c86-5076-4552-b119-61be841b72bd" />

<details>
<summary> Proof showing the creation/modifica
tion is working as expected
novel section
<img width="1440" alt="Screen Shot 2567-12-22 at 18 28 13" src="https://github.com/user-attachments/assets/4b2d5655-beac-4155-a31a-bffdc1d76750" />
setting
<img width="1440" alt="Screen Shot 2567-12-22 at 18 29 16" src="https://github.com/user-attachments/assets/f5bb9dc1-c61f-4367-ab92-b29e6d9167ac" />
 </summary>
</details>

2024-12-22 11:52 UTC, pupiesa commented
how to make the check pass

2024-12-22 17:36 UTC, darkvillager2 requested changes
Hello,
Thanks for the Pull Request. I have several questions about the code in ur request or changes.

If you have any questions feel free to ask them here or on discord (@Dark_Ville)

2024-12-22 17:36 UTC, darkvillager2 commented on websites/D/Dek-d/metadata.json
> +	"logo": "https://i.imgur.com/eq3Nmvz.png",
Logo's must be 512x512 as per [our guideliness](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#logo).

2024-12-22 17:36 UTC, darkvillager2 commented on websites/D/Dek-d/metadata.json
> +	"thumbnail": "https://i.imgur.com/dIQlWyP.png",
The thumbnails should be an actual thumbnail as per [our guideliness](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#thumbnail)

2024-12-22 17:36 UTC, darkvillager2 commented on websites/D/Dek-d/presence.ts
> +	Logo = "https://i.imgur.com/9wQMfAA.png",
Logo's must be 512x512 as per [our guideliness](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md#logo).

2024-12-22 17:36 UTC, darkvillager2 commented on websites/D/Dek-d/presence.ts
> +					presenceData.largeImageKey = urlMatch ? urlMatch[1] : "";
```suggestion
					presenceData.largeImageKey = urlMatch ? urlMatch[1] : Assets.Logo
```

2024-12-22 17:36 UTC, darkvillager2 commented on websites/D/Dek-d/presence.ts
> +			presenceData.details = "Browsing dek-d.com";
Not sure if this is allowed.

2024-12-22 17:36 UTC, darkvillager2 commented on websites/D/Dek-d/presence.ts
> +						presenceData.largeImageKey = urlMatch ? urlMatch[1] : "";
```suggestion
						presenceData.largeImageKey = urlMatch ? urlMatch[1] : Assets.Logo;
						if (presenceData.largeImageKey !== Assets.Logo) presenceData.smallImageKey = Assets.Logo;
```

2024-12-22 17:36 UTC, darkvillager2 commented on websites/D/Dek-d/presence.ts
> +					presenceData.smallImageKey = Assets.Logo;
```suggestion
```

2024-12-22 17:36 UTC, darkvillager2 commented on websites/D/Dek-d/presence.ts
> +					presenceData.smallImageKey = Assets.Logo;
```suggestion
if (presenceData.largeImageKey !== Assets.Logo) presenceData.smallImageKey = Assets.Logo;
```

2024-12-22 17:36 UTC, darkvillager2 commented on websites/D/Dek-d/presence.ts
> +								)[0];
```suggestion
								const img = document.querySelector(
									"div.thumb-img .image"
								);
```

2024-12-22 17:36 UTC, darkvillager2 commented on websites/D/Dek-d/presence.ts
> +								.querySelectorAll("a.link img")[0]
```suggestion
								.querySelector("a.link img")
```

2024-12-22 17:36 UTC, darkvillager2 commented on websites/D/Dek-d/presence.ts
> +								.querySelectorAll(".image img")[0]
```suggestion
								.querySelector(".image img")
```

2024-12-22 17:36 UTC, darkvillager2 commented on websites/D/Dek-d/presence.ts
> +								.querySelectorAll(".image img")[0]
```suggestion
								.querySelector(".image img")
```

2024-12-22 17:36 UTC, darkvillager2 commented on websites/D/Dek-d/presence.ts
> +							const img = document.querySelectorAll(".image img")[0];
```suggestion
							const img = document.querySelector(".image img");
```

2024-12-22 17:36 UTC, darkvillager2 commented on websites/D/Dek-d/presence.ts
> +							}
what

2024-12-22 17:36 UTC, darkvillager2 commented on websites/D/Dek-d/presence.ts
> +								.querySelectorAll(".image img")[0]
```suggestion
								.querySelector(".image img")
```

2024-12-22 17:36 UTC, darkvillager2 commented on websites/D/Dek-d/presence.ts
> +					const headerTexts = document.querySelectorAll(".special-intro")[0],
```suggestion
					const headerTexts = document.querySelector(".special-intro"),
```

2024-12-22 17:36 UTC, darkvillager2 commented on websites/D/Dek-d/presence.ts
> +							? headerTexts.querySelectorAll("h2")[0].textContent
```suggestion
							? headerTexts.querySelector("h2").textContent
```

2024-12-22 17:36 UTC, darkvillager2 commented on websites/D/Dek-d/presence.ts
> +						];
huh?? example?

2024-12-23 08:56 UTC, darkvillager2 requested changes

2024-12-23 08:56 UTC, darkvillager2 commented on websites/D/Dek-d/presence.ts
> +		titleText = titleElement ? titleElement.textContent : "",
```suggestion
		titleText = document.querySelector("h1.title")?.textContent ?? "",
```

2024-12-23 08:56 UTC, darkvillager2 commented on websites/D/Dek-d/presence.ts
> +					const headerTexts = document.querySelectorAll(".special-intro")[0],
Make requested change.

2024-12-25 19:09 UTC, Bas950 requested changes

2024-12-25 19:09 UTC, Bas950 commented on websites/D/Dek-d/metadata.json
> +		"en": "Dek-D.com is a popular Thai online platform that serves as a hub for teenagers and young adults. The website offers a variety of features and content, including Educational Resources , Creat
```suggestion
		"en": "Dek-D.com is a popular Thai online platform that serves as a hub for teenagers and young adults. The website offers a variety of features and content, including Educational Resources, Creative Writing Community, University Admissions Tools (TCAS), Interactive Forums and Social Features"
```

2024-12-25 19:09 UTC, Bas950 commented on websites/D/Dek-d/presence.ts
> +			presenceData.details = "Browsing dek-d.com";
```suggestion
			presenceData.details = "Browsing...";
```

2024-12-25 23:54 UTC, theusaf requested changes

2024-12-25 23:54 UTC, theusaf commented on websites/D/Dek-d/metadata.json
> +	"apiVersion": 2,
This looks like an api version 1 activity
```suggestion
	"apiVersion": 1,
```

2024-12-25 23:54 UTC, theusaf commented on websites/D/Dek-d/presence.ts
> +			buttons: [{ label: "Visit", url: document.URL }],
Avoid generic buttons like these. Instead, set the button field when needed.

2024-12-25 23:54 UTC, theusaf commented on websites/D/Dek-d/presence.ts
> +	switch (location.hostname) {
Use `document.location` rather than `location` for repository consistency

2024-12-25 23:54 UTC, theusaf commented on websites/D/Dek-d/presence.ts
> +						presenceData.buttons = [{ label: "View", url: document.URL }];
Use `document.location.href` instead of` document.URL`. Also consider using a more specific button label.

2024-12-25 23:54 UTC, theusaf commented on websites/D/Dek-d/presence.ts
> +					// console.log(headerT.split(" "));
```suggestion
```

2024-12-27 18:35 UTC, theusaf requested changes

2024-12-27 18:35 UTC, theusaf commented on websites/D/Dek-d/presence.ts
> +			// buttons: [{ label: "Visit", url: document.URL }],
```suggestion
```

2024-12-27 18:35 UTC, theusaf commented on websites/D/Dek-d/presence.ts
> +				document.URL.split("/")[5].split(".")[0] === "view"
Use `document.location.href` for consistency

2025-01-02 01:28 UTC, theusaf commented
Check all conversations and ensure they are resolved

2025-01-02 13:09 UTC, pupiesa commented
> Check all conversations and ensure they are resolved

all good now i think.

2025-01-02 23:00 UTC, theusaf approved these changes

2025-01-03 13:05 UTC, Bas950 approved these changes

2025-01-03 13:07 UTC, merged