feat(stremio): many improvements
PreMiD/Presences pull request #8994
Opened 2024-12-22 19:54 UTC by veryCrunchy

Fixes some of the major flaws in the previous version.
Some things probably still need fixing, the important parts now work as expected.

2024-12-25 19:08 UTC, Timeraa commented
There's a deepscan issue @veryCrunchy

2024-12-25 23:57 UTC, theusaf requested changes

2024-12-25 23:57 UTC, theusaf commented on websites/S/Stremio/metadata.json
> +	"logo": "https://stremio.crun.zip/e8417074974250bc5c8613be8dac6aa46f432bad/images/stremio_symbol.png",
Logo should be 512x512px

2024-12-26 00:02 UTC, veryCrunchy commented on websites/S/Stremio/metadata.json
> +	"logo": "https://stremio.crun.zip/e8417074974250bc5c8613be8dac6aa46f432bad/images/stremio_symbol.png",
Oops. wrong url..
```suggestion
	"logo": "https://stremio.crun.zip/e8417074974250bc5c8613be8dac6aa46f432bad/images/icon.png",
```

2024-12-26 00:18 UTC, theusaf approved these changes

2024-12-26 00:58 UTC, merged