feat(Royal Road): add presence
PreMiD/Presences pull request #9003
Opened 2024-12-24 10:37 UTC by DiscordAnaxes

This pr implements the following:

Resolves #8791
Adds Royal Road presence with most functionality and pages, excluding localisation as it seems to be a bit buggy.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Fiction (Actual Books) </summary>

![image](https://github.com/user-attachments/assets/bd23c24e-8d56-462a-8861-120cc57cfc93)
![image](https://github.com/user-attachments/assets/959aa655-891b-4879-835f-8e5f42e35301)
![image](https://github.com/user-attachments/assets/8dfdc160-8045-44c7-a574-8228593ae4c2)

</details>
<details>
<summary> Fictions (More of a 'find a fiction type section') </summary>

![image](https://github.com/user-attachments/assets/84a07797-d28c-4e26-819c-4eea7d5de204)

</details>
<details>
<summary> Evidence of buttons working </summary>

![image](https://github.com/user-attachments/assets/9ae4d2c4-be3d-419c-a922-957dfaf280e0)

</details>
<details>
<summary> Forums </summary>

![image](https://github.com/user-attachments/assets/7fd534cc-2eb2-4810-b129-29718ad644ac)
![image](https://github.com/user-attachments/assets/1fa9b25c-64cd-4820-88d3-6e2e01a56ef4)

</details>
<details>
<summary> Suggestions/Ideas Page </summary>

![image](https://github.com/user-attachments/assets/c79c5428-a42c-4ff7-80d4-ea626d04eb15)

</details>

Sorry if it is not up to latest standards, I haven't made a PreMiD presence in 2 years.

2024-12-25 19:21 UTC, Bas950 requested changes

2024-12-25 19:21 UTC, Bas950 commented on websites/R/Royal Road/presence.ts
> +const enum Assets { // Other default assets can be found at index.d.ts
```suggestion
const enum Assets {

2024-12-25 19:21 UTC, Bas950 commented on websites/R/Royal Road/presence.ts
> +		await presence.getSetting<string>("lang").catch(() => "en")
```suggestion
		}
```
Passing the language is deprecated

2024-12-26 00:01 UTC, theusaf requested changes

2024-12-26 00:01 UTC, theusaf commented on websites/R/Royal Road/presence.ts
> +				? document.URL.split("?page=")[1]?.split("&genre")[0]
Use `href` instead of `document.URL` for consistency

2024-12-29 23:21 UTC, theusaf approved these changes

2024-12-30 06:32 UTC, merged