fix(StreamingCommunity): update domain
PreMiD/Presences pull request #9024
Opened 2024-12-27 20:59 UTC by Hikki0710

## Description 
The site changes url often  so i tried to use regex

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

![image](https://github.com/user-attachments/assets/a72fcd22-2c6d-4ec4-9e90-0bcfe5a21322)
![image](https://github.com/user-attachments/assets/e3e59341-bb30-411f-b3bd-7b34af2fa076)

</details>

2024-12-28 13:55 UTC, darkvillager2 requested changes

2024-12-28 13:55 UTC, darkvillager2 commented on websites/S/StreamingCommunity/metadata.json
> +	"regExp": "streamingcommunity.[a-z\\d]+",
```suggestion
	"regExp": "streamingcommunity[.][a-z\\d]+",
```

2024-12-29 09:35 UTC, Hikki0710 commented on websites/S/StreamingCommunity/metadata.json
> +	"regExp": "streamingcommunity.[a-z\\d]+",
ops my bad 😅

2024-12-29 11:54 UTC, darkvillager2 approved these changes
LGTM

2024-12-29 23:27 UTC, theusaf approved these changes

2024-12-29 23:29 UTC, theusaf requested changes
Looks like your branch was a bit behind. Make sure to update your branch and update the version number

2024-12-30 09:17 UTC, Bas950 approved these changes

2025-01-02 01:31 UTC, theusaf approved these changes

2025-01-02 01:31 UTC, merged