Update metadata.json
PreMiD/Presences pull request #9043
Opened 2024-12-30 13:43 UTC by r4euk

Updated Logos to their newer logos which were introduced in a Brand Refresh. These Logos use a more modern look to the older logos seen on site.

## Description 

## Acknowledgements
- [ ] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ ] I linted the code by running `yarn format`
- [ ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

2024-12-30 14:12 UTC, DiscordAnaxes commented on websites/B/BBC/metadata.json
> +	"logo": "https://i.imgur.com/EuQ5Aid.png",
Not sure what changed with the logo in particular, but either way it must be 512x512.

2024-12-31 11:55 UTC, darkvillager2 commented on websites/B/BBC/metadata.json
> +	"logo": "https://i.imgur.com/R6ueMoU.png",
Its the same?

2025-01-02 01:40 UTC, theusaf commented on websites/B/BBC/metadata.json
> +	"logo": "https://i.imgur.com/R6ueMoU.png",
Not the same - font and padding difference

2025-01-02 01:40 UTC, theusaf approved these changes

2025-01-02 01:57 UTC, Slowlife01 commented
You might want to update this in the code as well

2025-01-02 14:29 UTC, r4euk commented on websites/B/BBC/metadata.json
> +	"logo": "https://i.imgur.com/R6ueMoU.png",
@darkvillager2 they updated the logo in 2022. More modern design with a new font family on the logo.

2025-01-02 23:02 UTC, theusaf requested changes
update the url in the code and bump version

2025-01-14 01:15 UTC, closed without merging