fix(Netflix): pause and showsmallimages issues
PreMiD/Presences pull request #9049
Opened 2024-12-31 17:28 UTC by iuriineves

## Description 

- Set timestamps to `0` when the video is paused - setting it to `null` breaks the `.setActivity()` function, only updating the information when the video is running;
- Set `smallImageKey` to `null` when `showSmallImages` is `false` - setting it to `""` didn't remove the image.

Closes #9031.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

(pausing)
![image](https://github.com/user-attachments/assets/8e9f1612-d137-4b40-9e55-da2fcae4d104)

(`showSmallImages` set to `false`)
![image](https://github.com/user-attachments/assets/16f07ad1-832d-431c-9aab-815f6e8e359a)

</details>

2025-01-02 01:44 UTC, theusaf approved these changes

2025-01-02 02:47 UTC, Timeraa reviewed
When you want to not show a certain thing just remove its property from the setactivity, setting it to something invalid will just cause more issues

2025-01-02 11:40 UTC, Timeraa requested changes
When you want to not show a certain thing just remove its property from the setactivity, setting it to something invalid will just cause more issues

2025-01-03 03:43 UTC, Timeraa commented
> > When you want to not show a certain thing just remove its property from the setactivity, setting it to something invalid will just cause more issues
> 
> The way the activity is coded, it has to be set to null for some reason. When I was testing it, setting `smallImageKey` to an empty string didn't remove the image, but setting it to `null` did.

I pushed to the PR, look at what I changed, learn more about it here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax
![image](https://github.com/user-attachments/assets/d1e10b23-79b8-45de-a7fb-346a41a03aee)

2025-01-03 13:07 UTC, Bas950 approved these changes

2025-01-03 13:07 UTC, merged